### ISSUE TITLE
Is C++ plugin API deprecated for 10.0?

### ISSUE THREAD

**Issue by ksqrtr** [apache/trafficserver#10233]
Hello!

Recently I was browsing ATS mailing lists archive and stumbled upon this email https://lists.apache.org/thread/4fkys3xktlm2w4k4ll0bxp462w32r4m2

Can some please elaborate a little on this? Will there be another C++ plugin API or C++ plugin API will be removed altogether?

**Comment by ywkaras** [comment]
No, changes to the TS API to make it utilize C++ features are not planned.  The current, C-style API is in a `c` sub-namespace within the `tsapi` namespace.  But this only allows for the possibility for a more up-to-date API.

**Comment by bryancall** [comment]
We are deprecating the C++ API in 10.0.0 and removing it for ATS 11.0.0.  The existing C API has been modified to be C++ for ATS 10.0.0.  It will still be very similar to the C API.
