### ISSUE TITLE
9.x -> 10.x: Increase in Origin Connection Counts

### ISSUE THREAD

**Issue by bneradt** [apache/trafficserver#10476]
While testing ATS 10 in production, I noticed that we had about 3 times the connection counts to the origin than we had in peer ATS 9.x hosts within the same colo. `ss` corroborated the connection counts so it wasn't metrics issue. Doing a binary search on commits, I noticed that the increased count was correlated with #9872. Locally we'll work around the issue by simply backing out #9872, #10104, and #10106 which gets us back to the ts IntrusiveHashMap rather than the libswoc one.

@SolidWallOfCode and I have discussed this. There will likely be a libswoc update to address the issue.

**Comment by traeak** [comment]
I found some performance regressions while working on https://github.com/apache/trafficserver/pull/10897  I'll probably add those changes there.  The primary one is with swoc::IntrusiveHashMap
