### ISSUE TITLE
cmake: need an enable for hardening compilation

### ISSUE THREAD

**Issue by bneradt** [apache/trafficserver#10608]
Our autotools build currently supports `--enable-hardening` and our debian CI job exercises it:
https://github.com/apache/trafficserver-ci/blob/348c03c726d32fdc6f5992e30bb92e0b998392d9/jenkins/github/debian.pipeline#L51C38-L51C38

In order to exercise this in CI with cmake, we will need support of something like `-DENABLE_HARDENING=ON`.

**Comment by cmcfarlen** [comment]
Modern cmake seems to frown on setting optional compiler flags inside the cmake files but instead put that stuff in presets or leaving that up to users and package maintainers.  This seems reasonable to avoid having to micromanage differences between compiler vendors and versions.  For this issue, we could add options to the ci-debian preset to manage these flags.  We could create a base "hardening" preset that can be inherited from, but there is some awkwardness with merging cache variables from multiple inheritance.

If we thing this is a reasonable approach for ATS, here are the flags that --enable-hardening sets:

CMAKE_CXX_FLAGS="-D_FORTIFY_SOURCE=2 -fPIE -fstack-protector"
CMAKE_EXE_LINKER_FLAGS="-pie -Wl,-z,relro -Wl,-z,now"

**Comment by cmcfarlen** [comment]
See #10629 for hardening preset
