### ISSUE TITLE
Support new 'Forwarded' standard (RFC7239)

### ISSUE THREAD

**Issue by PSUdaemon** [apache/trafficserver#1071]
This is a feature that will eventually displace X-Forwarded-For and friends. We should make a config option for this and default it to off until 8.0.0 (unless this gets backported for 7.0.0.

https://tools.ietf.org/html/rfc7239

**Comment by zwoop** [comment]
We should make the old behavior optional to enable as well, there's a significant number of backends (origins) that do not support RFC7239 yet but need the old semantics.

**Comment by PSUdaemon** [comment]
I thought the old behavior was already optional.

`  {RECT_CONFIG, "proxy.config.http.insert_squid_x_forwarded_for", RECD_INT, "1", RECU_DYNAMIC, RR_NULL, RECC_NULL, NULL, RECA_NULL}`

**Comment by zwoop** [comment]
Right, but your comments say "replaces". I think we should keep both, indefinitely.

**Comment by PSUdaemon** [comment]
Fair enough, description fixed.

**Comment by SolidWallOfCode** [comment]
I have some one here at Y! who will be working on this.

**Comment by ywkaras** [comment]
Y! doesn't have a current need for obfuscation or "unknown".

To records.config I'm thinking to add:

CONFIG proxy.config.http.insert_forwarded STRING <value>

In the first phase, the possibilities for <value> would be:

none
for|by|proto|host
for|by|proto|host|connection|full

'none' would be the default.

The second value would put all standard variables in the header.

The third value would put a non-standard "connection" variable in the header.  It would contain the protocol information from the Via: header, the full version, with dashes replacing spaces.

In a subsequent phase, any combination of 'for', 'by', 'proto', 'host', 'connection' could be configured, with 'full' increasing the level of detail in the connection value.

**Comment by SolidWallOfCode** [comment]
I'd like to add to "connection" the ability to specific some levels of detail, e.g.
`connection=full`
`connection=std`
`connection=compact`
with the same meaning as for the VIA header.

**Comment by ywkaras** [comment]
It's already in there and ready to be savaged.

**Comment by bryancall** [comment]
I believe this has been fully completed.  Please reopen if need be.
