### ISSUE TITLE
CI clang-format fails for differences in CMakeLists.txt files but "clang-format" target does not fix that.

### ISSUE THREAD

**Issue by SolidWallOfCode** [apache/trafficserver#10775]
See [here](https://ci.trafficserver.apache.org/job/Github_Builds/job/clang-format/3772/console). While this can be discovered by diving in to the output, it can be surprising that failing "clang-format" on CI isn't fixed by running "clang-format" locally. Nor is there any indication during commit there is a format issue (unlike code format changes).

**Comment by cmcfarlen** [comment]
There is a `cmake-format` target for fixing formatting on cmake files.  @bneradt suggested we rename the clang-format CI job to just format so its not assumed that it was clang-format that failed the build.

**Comment by bneradt** [comment]
I think this can be closed now:

* The CI job is now called “format” and running that target should address all format issues.
* And Chris fixed the pre-commit update logic to always update.

@SolidWallOfCode : are you OK closing this?
