### ISSUE TITLE
Verify that logging.yaml can be reloaded in ATS 10

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#10850]
We are seeing internally on our ATS 9 that logging.yaml can't be reloaded after adding fields.  Need to verity that this feature is working on ATS 10 (master).

**Comment by lzx404243** [comment]
I will take a look at this.

**Comment by lzx404243** [comment]
logging.yaml reloading doesn't work in master. Creating a PR to fix this.

**Comment by masaori335** [comment]
It'd be great if we have a AuTest to cover this scenario.
