### ISSUE TITLE
simple_retry_responses not deallocated

### ISSUE THREAD

**Issue by jasmine-nahrain** [apache/trafficserver#11043]
https://github.com/apache/trafficserver/blob/075dcda4ae01338b155846917db6035fd0788d5a/src/proxy/ParentSelection.cc#L869

simple_server_retry_responses is not deallocated. Should be the same as unavailable_server_retry_responses

**Comment by ywkaras** [comment]
Where is simple_retry_responses in the code?

**Comment by jasmine-nahrain** [comment]
> Where is simple_retry_responses in the code?

Sorry, it should be `simple_server_retry_responses`. I have updated the description now
