### ISSUE TITLE
Some unit tests are failing under asan on master

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#11140]
Here is a list of them: 

- [x]  1 - test_libswoc (Failed)
- [x]  10 - test_AIO (Failed)
- [x]  11 - test_cache_Cache (Failed) - `(Bryan) - looks like it is an issue with g_ssl_hooks`
- [x]  2 - test_cache_Populated_Cache (Failed)
- [x]  13 - test_cache_CacheDir (Failed)
- [x]  14 - test_cache_CacheVol (Failed)
- [x]  15 - test_cache_RWW (Failed)
- [x]  16 - test_cache_Alternate_L_to_S (Failed)
- [x]  17 - test_cache_Alternate_S_to_L (Failed)
- [x]  18 - test_cache_Alternate_L_to_S_remove_L (Failed)
- [x]  19 - test_cache_Alternate_L_to_S_remove_S (Failed)
- [x]  20 - test_cache_Alternate_S_to_L_remove_L (Failed)
- [x]  21 - test_cache_Alternate_S_to_L_remove_S (Failed)
- [x]  22 - test_cache_Update_L_to_S (Failed)
- [x]  23 - test_cache_Update_S_to_L (Failed)
- [x]  24 - test_cache_Update_Header (Failed)
- [x]  37 - test_jsonrpcserver (Failed) (Walt - https://github.com/apache/trafficserver/pull/11164)
- [x]  42 - verify_background_fetch (Failed)
- [x]   62 - verify_remap_stats (Failed)
- [x]  65 - verify_slice (Failed)
- [x]  88 - verify_sslheaders (Failed)
- [x]  93 - verify_tls_bridge (Failed)
- [x]  94 - test_txn_box (Failed)  (Damian  - https://github.com/apache/trafficserver/pull/11156)
- [x]  95 - verify_magick (Failed)
- [x]  97 - verify_webp_transform (Failed)
- [x]  98 - uri_signing_test (Failed)

**Comment by brbzull0** [comment]
when I manually run `test_jsonrpcserver` it seems fine, though when running `--target test` it does fail.
```
./test_jsonrpcserver
...
All tests passed (44 assertions in 12 test cases)
```
