### ISSUE TITLE
Documentation's latest no longer has version drop down

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#11144]
I have my documentation version set to 9.2
https://docs.trafficserver.apache.org/admin-guide/index.en.html
in the lower right, the version number appears

<img width="297" alt="Screenshot 2024-03-07 at 1 17 11 PM" src="https://github.com/apache/trafficserver/assets/387053/a225c564-574f-455f-a00e-d895af88ae7a">

In "latest"
https://docs.trafficserver.apache.org/en/latest/
the version number disappears (as does the project name)
<img width="306" alt="Screenshot 2024-03-07 at 1 17 57 PM" src="https://github.com/apache/trafficserver/assets/387053/8f5be39a-385e-4494-b813-b9414bbe645d">
the whole div class=rst-versions isn't there...

**Comment by ezelkow1** [comment]
been looking into this, I believe it's an issue with sphinx/docs build where now that it's built out of source it can no longer see the templates dir that injects that drop down
