### ISSUE TITLE
records.yaml validation on loading

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#11153]
`RecordElement` has a member for validation of value called `regex`, it's used when a config is given through `traffic_ctl config set` command. However, it looks like it's not used when the records.yaml (records.config for 9.2.x) is loaded.

https://github.com/apache/trafficserver/blob/master/src/records/RecordsConfig.cc#L39C14-L39C27

Link: #11110

**Comment by brbzull0** [comment]
@masaori335  I can look at this is none else is already looking at it.
