### ISSUE TITLE
Support for Early Data is not checked properly

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#11203]
The check was broken when we switch to CMake.

We used to check multiple functions
https://github.com/apache/trafficserver/blob/17b9c5f389ccc266c967261df85262a9206041dd/build/crypto.m4#L320-L326
but now we check just one
https://github.com/apache/trafficserver/blob/db9db293c55d419acda4c9a89731c579ca0da005/CMakeLists.txt#L443

**Comment by brbzull0** [comment]
It seems `SSL_read_early_data` is only available in openssl. 


| API | Vendor |
 |-----------------------------------|--------------|
| SSL_set_max_early_data | openssl |
|SSL_read_early_data   | openssl |
|SSL_write_early_data |  openssl |
|SSL_in_early_data    |  boringssl |

For the sake of setting the ED flag, should set the variables depending of the ssl vendor?

**Comment by maskit** [comment]
I think we should not rely on vender names at all unless it's really necessary. My preference is to check the availability of functions. OpenSSL 3.x deprecated many functions and those may be unavailable on 4.x. Also, checking `OPENSSL_IS_BORINGSSL` does not work for aws-lc but checking the availability of `SSL_in_early_data` works.

**Comment by duke8253** [comment]
Pretty sure this is why the 0-rtt autests are failing with a boringssl build for now. I compared some logs and looks like when built with boringssl, none of the early data functions are being executed.

**Comment by brbzull0** [comment]
Fixed by https://github.com/apache/trafficserver/pull/11215
