### ISSUE TITLE
Trafficserver fails to load plugin on Debian

### ISSUE THREAD

**Issue by jbfavre** [apache/trafficserver#11253]
As explained [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020989#32), none of the remap plugins can be loaded by trafficserver running on Debian.

> Trafficserver copies the plugins from `/usr/lib` to `/run` and tries to dlopen them from there.  This is doomed to fail because, exactly as the OP said, `/run` is mounted with the `noexec` option.  Upstream logic behind this is to dynamically reload plugins that are changed while the server is running.  I guess it makes sense with custom plugins and some other scenarios but there's no way for this to work on Debian systems.

Do you have any insights or advice to workaround this?
My understanding is that mounting `/run` without the `noexec` option is not an option for Debian.

The bug report also proposes a patch.
However, before integrating it either in the Debian package or upstream, it'll need to be carefully reviewed.

Best

**Comment by bryancall** [comment]
You might want to change this option to disable reloadable remap plugin without restarting ATS: `proxy.config.plugin.dynamic_reload_mode`.  This option will copy and rename the plugin into the `run` directory.

https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-plugin-dynamic-reload-mode
