### ISSUE TITLE
The Apache Traffic Server is not listening on port 80 after starting the service ( service is active! )

### ISSUE THREAD

**Issue by Abodovic** [apache/trafficserver#11292]
Greetings,
So, I have walked through the [documentation](https://docs.trafficserver.apache.org/en/latest/getting-started/index.en.html#installing-from-source-code) of installing Traffic Sever with source code.. long story short, I have configured the map rule, edited the storage size, and did the below:

`systemctl enable trafficserver.service`
`systemctl start trafficserver.service`

and it shows the service is up and running as shown below:

![image](https://github.com/apache/trafficserver/assets/74303369/5af4a63d-406a-455b-8af8-82db58a9f540)

However, when doing `ss -pltn` it shows the Traffic Server is not listening on port 80

![image](https://github.com/apache/trafficserver/assets/74303369/50b008a7-0532-463d-9adb-6d94cd1cb83d)

It seems the issue is that the Traffic Server itself is either not properly Implemented/Installed or maybe I missed something (All the configurations are correct, I have reviewed them three times :( )

Please for your help and support!
Thank you,

**Comment by bryancall** [comment]
What version of ATS are you running? 

On ATS 9.x:
What is your port set to in records.config?    The setting name is `proxy.config.http.server_ports` and the default is port 8080.

documentation:
https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-http-server-ports
