### ISSUE TITLE
Event handles with VC_EVENT_ERROR but not VC_EVENT_EOS

### ISSUE THREAD

**Issue by cmcfarlen** [apache/trafficserver#11358]
While reviewing #11346, I went through and found other places where the EOS event was not handled but ERROR was:

```
src/iocore/net/QUICNextProtocolAccept.cc|44 col 8| case VC_EVENT_ERROR:
src/proxy/http/HttpSM.cc|1232 col 8| case VC_EVENT_ERROR:
src/proxy/http/HttpSM.cc|1808 col 8| case VC_EVENT_ERROR:
src/proxy/Transform.cc|634 col 10| case VC_EVENT_ERROR:
src/proxy/Transform.cc|793 col 10| case VC_EVENT_ERROR:
```

I wonder, should we add EOS to these switch statements as well?

**Comment by maskit** [comment]
I'm not sure whether QUICNextProtocolAccept.cc receives EOS, but we can add it.

Is the list complete? I wonder why SSLNextProtocolAccept.cc isn't on the list.

**Comment by cmcfarlen** [comment]
Its likely not complete, just me staring at the code
