### ISSUE TITLE
Autest tls_tunnel fails because of a slightly different error message from python

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#11409]
`test proxy_protocol_port - not in connect_ports` fails, because it can't find "ssl.SSLEOFError" in the output.

The expected error message is probably like this
```
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
```
but the error message can be like this (it probably depends on the version of python or its library)
```
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1129)
```

**Comment by bryancall** [comment]
@maskit Ask for @bneradt's help

**Comment by ywkaras** [comment]
Is this related to https://github.com/apache/trafficserver/issues/9550 ?

**Comment by maskit** [comment]
Yes, looks like the same as the issue you reported. The one Masaori mentioned seems like a different issue.
