### ISSUE TITLE
What is the current status of http3 support in ATS 10.x?

### ISSUE THREAD

**Issue by ksqrtr** [apache/trafficserver#11422]
Hello!
What is the current status of HTTP3 support in 10.0.x branch and what configuration settings should be enabled/disabled if I'd like to play with http3 in ATS? Or maybe I should use master branch for http3?

**Comment by maskit** [comment]
It's still experimental support on either branch. There is no difference (or only tiny difference) between 10.0.x and master in terms of HTTP/3 at the moment. If you are going to play with HTTP/3 some time later, master is better option.

As for the settings, [this page](https://github.com/apache/trafficserver/wiki/HTTP-3-Documentation#5-configuring-trafficserver-with-http3-support) should cover the minimal configuration.
