### ISSUE TITLE
Should we retry to open cache span on signal interrupt or out of memory

### ISSUE THREAD

**Issue by JosiahWI** [apache/trafficserver#11513]
We currently retry on these error cases in `Span::init`, because `SocketManager::open` retries them, and as far as I can tell, nowhere else.

https://github.com/apache/trafficserver/blob/89264ff7da0ae5a2e6db9197c75d248b6bd9c3b9/src/iocore/cache/Store.cc#L370-L375

These are the cases in which the open() call will be retried:

https://github.com/apache/trafficserver/blob/89264ff7da0ae5a2e6db9197c75d248b6bd9c3b9/src/iocore/eventsystem/UnixSocket.h#L297-L308

**Comment by ywkaras** [comment]
This is resolved by https://github.com/apache/trafficserver/pull/11526 .
