### ISSUE TITLE
ATS 10.0.x,    does it support purge with wildcard ( * )

### ISSUE THREAD

**Issue by Solarisbf** [apache/trafficserver#11625]
i found solution about directory purge with Remap Purge plugin

https://docs.trafficserver.apache.org/en/10.0.x/admin-guide/plugins/remap_purge.en.html

so, i could implement directory purge like this

remap.config

map https://test1234.com/ https://xxxxx.ap-northeast-2.amazonaws.com@plugin=remap_purge.so @pparam=--state-file=example @pparam=--secret=8BFE-656DC3564C05

curl -X PURGE https://test1234.com/    --> same as https://test1234.com/*

**But, when i would like to send wildcard Purge like this

curl -X PURGE https://test1234.com/*.jpg**

any support please ! thx

@calavera @janfrode @biilmann @jpeach

**Comment by bryancall** [comment]
We don't have the ability to do this in our cache since we don't have a index of all the URLs stored in the cache.  This would require walking the entire cache to see if the URLs match the pattern.

**Comment by Solarisbf** [comment]
i got it 
thanks a lot! @bryancall
