### ISSUE TITLE
records.yaml YAML examples in documentation have wrong root

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#11642]
The root for records.yaml changed from "ts" to "records", but the documentation in https://docs.trafficserver.apache.org/en/10.0.x/admin-guide/files/records.yaml.en.html Is still showing a root of "ts" in the yaml examples.

I'm not sure how those examples are generated otherwise I'd just put up a PR.

**Comment by brbzull0** [comment]
Thanks Susan. Thought I fixed this [here](https://github.com/apache/trafficserver/blob/master/doc/ext/traffic-server.py#L144)  but nop.

Just added a PR for this.
Thanks.
