### ISSUE TITLE
socks.config - dest_ip rule issue

### ISSUE THREAD

**Issue by 06chaynes** [apache/trafficserver#1175]
I have added a rule to the socks.config file to use a SOCKS server for a specific destination IP with the dest_ip primary specifier but it does not appear to be working. I am able to change my system setting to use the SOCKS server and that does work, I just can't get ATS to use it via the rule in socks.config.

Any help would be much appreciated!

**Comment by jpeach** [comment]
Which version of Traffic Server are you running? @oknet fixed the SOCKS proxy recently and those changes will be available in the forthcoming [7.0 release](https://lists.apache.org/thread.html/7b1ce4e5ce4156fb61a2756a7073477ed759f037ceae734afc874364@%3Cdev.trafficserver.apache.org%3E).

**Comment by 06chaynes** [comment]
Awesome news. I am currently on the latest in the FreeBSD repo, 6.1. I have been using Polipo for now but for many reasons would love to use ATS. I look forward to building 7 once stable. Thanks for the answer!

**Comment by oknet** [comment]
backport to 6.2.1.

2016-11-04 21:32 GMT+08:00 Christian Haynes <notifications@github.com>:

**Comment by 06chaynes** [comment]
@oknet Very cool, will 6.2.1 be added as a release and propagated through the master sites?

**Comment by oknet** [comment]
yes, the v6.2.1 will be released recently.

2016-11-07 21:53 GMT+08:00 Christian Haynes <notifications@github.com>:

**Comment by 06chaynes** [comment]
Has this fix already been applied to the 7.0 release? I ask because I am currently running 7.0 but not getting any traffic through my SOCKS proxy still.

**Comment by oknet** [comment]
Can you post your socks config in records.config file? and socks.config
file.

2016-11-16 23:46 GMT+08:00 Christian Haynes <notifications@github.com>:

**Comment by oknet** [comment]
The PR#937 https://github.com/apache/trafficserver/pull/937 fix the socks
bug for ATS 7.0.0. and backport to 6.2.x by PR#1203
https://github.com/apache/trafficserver/pull/1203.

2016-11-23 16:28 GMT+08:00 Chao Xu <xuchao@gmail.com>:

**Comment by oknet** [comment]
To proxy any request by socks proxy server:
```
CONFIG proxy.config.socks.socks_needed INT 1
```
Then set socks proxy server and exception rules in socks.config.

To accept socks request on ATS 1080 tcp port and proxy it to socks proxy server:
```
CONFIG proxy.config.socks.socks_needed INT 1
CONFIG proxy.config.socks.accept_enabled INT 1
```

And you can define a default socks proxy server:
```
CONFIG proxy.config.socks.default_servers STRING "x.x.x.x:1080;x.x.x.x:1080"
```
Please do not include any SPACE in default_servers string, and put ";" between multi servers.

**Comment by 06chaynes** [comment]
Right now I am working with a default config but have added the following line into records.config:

`CONFIG proxy.config.socks.socks_needed INT 1`

After adding the line I get ERR_EMPTY_RESPONSE for every page I browse to. Right now I have a single site added (removed ip from post): 

`dest_ip=<site-ip> parent="127.0.0.1:38080"`

After setting socks_needed back to 0 traffic starts flowing again

FYI - My SOCKS proxy is listening on 38080 as you can see and if I connect to it directly all works as expected.

**Comment by oknet** [comment]
Can you enable socks debug message？

```
CONFIG proxy.config.diags.debug.enabled INT 1
CONFIG proxy.config.diags.debug.tags STRING Socks.*
```

And make a request to ATS, then you will see:

```
(Socks) Using Socks ip: <dst ip>:<port>
(SocksParents) findServer result: 127.0.0.1:38080
...
```

please mail the logs to me or just post here, thanks.

**Comment by 06chaynes** [comment]
I will enable logging and check for issues as soon as I can circle back around to this. Thanks again for your assistance.

**Comment by oknet** [comment]
ping @06chaynes

**Comment by 06chaynes** [comment]
Sorry for the silence on my end, I have been swamped lately. I was testing again, after adding your logging config changes, and noticed that the trafficserver service was crashing in a loop. I am troubleshooting that issue now as it would obviously be a possible cause for my "SOCKS" issue :)

**Comment by 06chaynes** [comment]
Here is what I have found so far,
Before setting socks_needed = 1 the proxy works as expected. Once I set socks_needed = 1,  I start to see what appears to be the service crashing and restarting. Here is what I see in /var/log/messages:

Dec 20 19:00:52 server traffic_server[72819]: NOTE: RLIMIT_NOFILE(8):cur(190530),max(190530)
Dec 20 19:00:52 server kernel: pid 72819 (traffic_server), uid 65534: exited on signal 6
Dec 20 19:00:55 server traffic_server[72821]: NOTE: --- traffic_server Starting ---
Dec 20 19:00:55 server traffic_server[72821]: NOTE: traffic_server Version: Apache Traffic Server - traffic_server - 7.0.0 - (build # 122016 on Dec 20 2016 at 16:14:02)
Dec 20 19:00:55 server traffic_server[72821]: NOTE: RLIMIT_NOFILE(8):cur(190530),max(190530)
Dec 20 19:00:55 server kernel: pid 72821 (traffic_server), uid 65534: exited on signal 6
Dec 20 19:00:58 server traffic_server[72823]: NOTE: --- traffic_server Starting ---
Dec 20 19:00:58 server traffic_server[72823]: NOTE: traffic_server Version: Apache Traffic Server - traffic_server - 7.0.0 - (build # 122016 on Dec 20 2016 at 16:14:02) 


I see the following in diags.log:

[Dec 20 19:07:10.084] Server {0x804006400} NOTE: traffic server running
[Dec 20 19:07:10.088] Server {0x804007c00} NOTE: cache enabled
[Dec 20 19:07:13.006] Server {0x804008000} NOTE: updated diags config
[Dec 20 19:07:13.006] Server {0x804008000} NOTE: updated diags config
[Dec 20 19:07:19.974] Server {0x804006400} STATUS: opened /var/log/trafficserver/diags.log
[Dec 20 19:07:19.975] Server {0x804006400} NOTE: updated diags config
[Dec 20 19:07:19.982] Server {0x804006400} NOTE: cache clustering disabled
[Dec 20 19:07:20.000] Server {0x804006400} NOTE: ip_allow.config updated, reloading
[Dec 20 19:07:20.020] Server {0x804006400} NOTE: cache clustering disabled
[Dec 20 19:07:20.025] Server {0x804006400} NOTE: logging initialized[3], logging_mode = 3
[Dec 20 19:07:20.028] Server {0x804006400} NOTE: loading SSL certificate configuration from /usr/local/etc/trafficserver/ssl_multicert.config
[Dec 20 19:07:20.046] Server {0x804006400} NOTE: resetting hardware sector size from 32768 to 8192
[Dec 20 19:07:20.080] Server {0x804006400} NOTE: traffic server running
[Dec 20 19:07:20.085] Server {0x804007c00} NOTE: cache enabled

**Comment by 06chaynes** [comment]
Here is what I found in traffic.out:

[Dec 20 19:17:06.714] Server {0x804006400} DEBUG: <Socks.cc:517 (loadSocksConfiguration)> (Socks) Socks Turned on
[Dec 20 19:17:06.863] Server {0x804007c00} DEBUG: <UnixNetProcessor.cc:228 (connect_re_internal)> (Socks) Using Socks ip: 162.242.159.221:80
Assertion failed: (ats_is_ip4(&target_addr)), function init, file Socks.cc, line 67.
traffic_server: using root directory '/usr/local'
traffic_server: Abort trap
traffic_server - STACK TRACE:
0x4afa59 <_Z19crash_logger_invokeiP9__siginfoPv+0x69> at /usr/local/bin/traffic_server
0x802769b37 <pthread_sigmask+0x507> at /lib/libthr.so.3
0x80276922c <pthread_getspecific+0xe1c> at /lib/libthr.so.3
[Dec 20 19:17:09.999] Server {0x804006400} DEBUG: <Socks.cc:462 (loadSocksConfiguration)> (Socks) Socks Version 4
[Dec 20 19:17:09.999] Server {0x804006400} DEBUG: <Socks.cc:472 (loadSocksConfiguration)> (Socks) server connect timeout: 10 socks respnonse timeout 100
[Dec 20 19:17:09.999] Server {0x804006400} DEBUG: <Socks.cc:482 (loadSocksConfiguration)> (SocksProxy) Read SocksProxy info: accept_enabled = 0 accept_port = 1080 http_port = 80
[Dec 20 19:17:10.000] Server {0x804006400} DEBUG: <Socks.cc:489 (loadSocksConfiguration)> (Socks) Socks Config File: /usr/local/etc/trafficserver/socks.config
[Dec 20 19:17:10.003] Server {0x804006400} DEBUG: <Socks.cc:517 (loadSocksConfiguration)> (Socks) Socks Turned on
[Dec 20 19:17:10.105] Server {0x804007800} DEBUG: <UnixNetProcessor.cc:228 (connect_re_internal)> (Socks) Using Socks ip: 162.242.159.221:80
Assertion failed: (ats_is_ip4(&target_addr)), function init, file Socks.cc, line 67.
traffic_server: using root directory '/usr/local'
traffic_server: Abort trap
traffic_server - STACK TRACE:
0x4afa59 <_Z19crash_logger_invokeiP9__siginfoPv+0x69> at /usr/local/bin/traffic_server
0x802769b37 <pthread_sigmask+0x507> at /lib/libthr.so.3
0x80276922c <pthread_getspecific+0xe1c> at /lib/libthr.so.3
FATAL: [ProcessManager::pollLMConnection] Lost Manager EOF!

**Comment by oknet** [comment]
It seems that you ATS code is old and did not apply socks patch.
https://github.com/apache/trafficserver/pull/937/files for 7.0
https://github.com/apache/trafficserver/pull/1203/files for 6.2

```
iocore/net/Socks.cc
 58 
 59   ats_ip_copy(&target_addr, vc->get_local_addr());
 60 
```

You should fetch the newest source code if your ats code shows the same as above.

**Comment by 06chaynes** [comment]
Ok, thanks for the quick response. I have just cloned the repo and I am rebuilding from it rather than the tagged release. I will test again and update you shortly.

**Comment by 06chaynes** [comment]
I am still getting an error but now I do have a new question related to the SOCKS versions supported. Are socks5 servers supported or just socks4? 

The reason I ask is that in the error I noticed it says Socks version 4 but my server is running version 5.

**Comment by 06chaynes** [comment]
I went ahead and modified my upstream proxy server to be compatible with socks4. I am still getting an error though after enabling socks_needed. I did confirm I was using the latest build and the patch does look to be present (it was in the source I built from at least). Here is the output in traffic.out:

traffic_server: using root directory '/usr/local'
traffic_server: Abort trap
traffic_server - STACK TRACE:
0x4b07a9 <_Z19crash_logger_invokeiP9__siginfoPv+0x69> at /usr/local/bin/traffic_server
0x80275ab37 <pthread_sigmask+0x507> at /lib/libthr.so.3
0x80275a22c <pthread_getspecific+0xe1c> at /lib/libthr.so.3
[Dec 21 17:27:34.840] Server {0x804006400} DEBUG: <Socks.cc:462 (loadSocksConfiguration)> (Socks) Socks Version 4
[Dec 21 17:27:34.840] Server {0x804006400} DEBUG: <Socks.cc:472 (loadSocksConfiguration)> (Socks) server connect timeout: 10 socks respnonse timeout 100
[Dec 21 17:27:34.840] Server {0x804006400} DEBUG: <Socks.cc:482 (loadSocksConfiguration)> (SocksProxy) Read SocksProxy info: accept_enabled = 0 accept_port = 1080 http_port = 80
[Dec 21 17:27:34.841] Server {0x804006400} DEBUG: <Socks.cc:489 (loadSocksConfiguration)> (Socks) Socks Config File: /usr/local/etc/trafficserver/socks.config
[Dec 21 17:27:34.842] Server {0x804006400} DEBUG: <Socks.cc:517 (loadSocksConfiguration)> (Socks) Socks Turned on
[Dec 21 17:27:35.052] Server {0x804008000} DEBUG: <UnixNetProcessor.cc:228 (connect_re_internal)> (Socks) Using Socks ip: 216.58.192.142:80
Assertion failed: (ats_is_ip4(&target_addr)), function init, file Socks.cc, line 67.
traffic_server: using root directory '/usr/local'
traffic_server: Abort trap
traffic_server - STACK TRACE:
0x4b07a9 <_Z19crash_logger_invokeiP9__siginfoPv+0x69> at /usr/local/bin/traffic_server
0x80275ab37 <pthread_sigmask+0x507> at /lib/libthr.so.3
0x80275a22c <pthread_getspecific+0xe1c> at /lib/libthr.so.3

**Comment by oknet** [comment]
To set the socks version:

```
CONFIG proxy.config.socks.socks_version INT 5
```

Are you sure that you have the lastest source code?

```
Assertion failed: (ats_is_ip4(&target_addr)), function init, file Socks.cc, line 67.
```

You still hit the assert in Socks.cc:67. Can you open the source file iocore/net/Socks.cc and show me the Line 58 to 60.

**Comment by 06chaynes** [comment]
Sweet, thanks for the info. Here is what I see in the source I am building from:

ats_ip_copy(&target_addr, vc->get_remote_addr());

**Comment by oknet** [comment]
Thanks, I have located a bug in UnixNetProcessor.cc and will create a PR to fix it.

**Comment by oknet** [comment]
@06chaynes There are 2 patches to resolve this issue, please try to apply them.

https://github.com/apache/trafficserver/pull/1274/files
https://github.com/apache/trafficserver/pull/1275/files

I have try it with dante-server. The /etc/danted.conf list below:
```
external: 172.22.21.211
internal: 127.0.0.1 port = 10800
logoutput: /var/log/socks.log
method: none
clientmethod: none
user.privileged: proxy
user.notprivileged: nobody
user.libwrap: nobody

client pass {
    from: 0.0.0.0/0 port 1-65535 to: 0.0.0.0/0
    log: connect disconnect error
}

pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    protocol: tcp udp
    log: connect disconnect error
}
```

Try to make a HTTP request to 172.21.21.254:80 by connect-proxy
```
root@xuc:~/package/oknet-ats# connect-proxy -S localhost:1080 172.21.21.254 80
GET / HTTP/1.0
Host: 172.21.21.254

HTTP/1.0 200 OK
Date: Fri, 23 Dec 2016 08:41:40 GMT
Server: ATS/7.1.0
Last-Modified: Tue, 07 Jul 2015 12:21:55 GMT
ETag: "22682-b1-51a481162477f"
Accept-Ranges: bytes
Content-Length: 177
Vary: Accept-Encoding
Content-Type: text/html
X-Pad: avoid browser bug
Age: 0

<html><body><h1>It works!</h1>
<p>This is the default web page for this server.</p>
<p>The web server software is running but no content has been added, yet.</p>
</body></html>
```

the /var/log/socks.log:
```
Dec 23 15:28:33 (1482478113) danted[21091]: pass(1): tcp/accept [: 127.0.0.1.50906 -> 127.0.0.1.10800
Dec 23 15:28:33 (1482478113) danted[21092]: pass(1): tcp/connect [: 127.0.0.1.50906 -> 172.21.21.254.80
Dec 23 15:30:28 (1482478228) danted[21096]: pass(1): tcp/connect ]: 484 -> 127.0.0.1.50906 -> 158,  158 -> 127.0.0.1.10800 -> 484: remote closed
Dec 23 15:30:28 (1482478228) danted[21096]: pass(1): tcp/connect ]: 484 -> 127.0.0.1.50906 -> 158,  158 -> 172.21.21.254.80 -> 484: remote closed
```

and the ats configs:

```
/etc/trafficserver/records.config:
CONFIG proxy.config.socks.socks_needed INT 1
CONFIG proxy.config.socks.accept_enabled INT 1
CONFIG proxy.config.socks.default_servers STRING 127.0.0.1:10800
CONFIG proxy.config.socks.socks_version INT 5
```

or

```
/etc/trafficserver/records.config:
CONFIG proxy.config.socks.socks_needed INT 1
CONFIG proxy.config.socks.accept_enabled INT 1
CONFIG proxy.config.socks.socks_version INT 5

/etc/trafficserver/socks.config:
dest_ip=172.21.21.254 parent="127.0.0.1:10800"
```

**Comment by oknet** [comment]
TS-5106 #1274  merged

**Comment by oknet** [comment]
TS-5015 #1275 merged

@06chaynes, please try the master branch.

**Comment by 06chaynes** [comment]
Sorry for the late response but I just tested the latest patch and found another issue it seems.

[Jan  6 15:40:39.885] Server {0x804006400} DEBUG: <Socks.cc:462 (loadSocksConfiguration)> (Socks) Socks Version 4
[Jan  6 15:40:39.885] Server {0x804006400} DEBUG: <Socks.cc:472 (loadSocksConfiguration)> (Socks) server connect timeout: 10 socks respnonse timeout 100
[Jan  6 15:40:39.885] Server {0x804006400} DEBUG: <Socks.cc:482 (loadSocksConfiguration)> (SocksProxy) Read SocksProxy info: accept_enabled = 0 accept_port = 1080 http_port = 80
[Jan  6 15:40:39.885] Server {0x804006400} DEBUG: <Socks.cc:489 (loadSocksConfiguration)> (Socks) Socks Config File: /usr/local/etc/trafficserver/socks.config
[Jan  6 15:40:39.887] Server {0x804006400} DEBUG: <Socks.cc:517 (loadSocksConfiguration)> (Socks) Socks Turned on
/usr/local/lib/libssl.so.8: Undefined symbol "EVP_aes_128_cbc_hmac_sha256"

**Comment by oknet** [comment]
The libssl error is not related to this issue. Do you running the ats in another server that different to build server?

In the last message you post here, the log line missing:
```
[Dec 21 17:27:35.052] Server {0x804008000} DEBUG: <UnixNetProcessor.cc:228 (connect_re_internal)> (Socks) Using Socks ip: 216.58.192.142:80
```

Can you try to rebuild the ATS ?

**Comment by 06chaynes** [comment]
The build server is FreeBSD 10.3 but the device it runs on is actually pfSense 2.3. Right now I have asked the port maintainer to include patches related to this issue, it's possible I haven't provided him with all the commits that need to be added as a patch. 

Here is a link to the port with the SOCKS patches: https://propus.hychen.org/files/trafficserver-7.0.0_1.tgz

**Comment by oknet** [comment]
I think the message at below indicate your run-time openssl library is different from your build server.

```
/usr/local/lib/libssl.so.8: Undefined symbol "EVP_aes_128_cbc_hmac_sha256"
```

It seems that your build server has latest version of openssl library.

**Comment by 06chaynes** [comment]
I apologize for the lack of updates on this, i Just now got a chance to pull this back out and start testing. I verified that the setup works properly in Debian. I also agree that my issue on the FreeBSD box is related to dependency issues. I will be working those issues out soon and will close the ticket once I have verified the issue. Thanks again for all your help.

**Comment by oknet** [comment]
The bugs was fixed in 6.2.x branch too. You can try 6.2.x since the 7.x branch is not stable enough.
Don't hesitate to contact with me if you meet any question in SocksProxy.

**Comment by oknet** [comment]
@06chaynes  Is there any issues ?  or please close this issue, thanks.

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
