### ISSUE TITLE
http_ui_enabled not work in version 10.0.0

### ISSUE THREAD

**Issue by Sorata** [apache/trafficserver#11829]
Old version support http_ui_enabled. But I found 10.0.0 not support http_ui_enabled in records.yaml.

Is this feature lost or is there another way to enable it?

**Comment by bryancall** [comment]
Yes, this feature was removed in the ATS 10.0.0 release.  It was removed in PR #10710.  An email went to the users mailing list on 10/30/2023 about removing this feature: https://lists.apache.org/thread/rz4lscsbv050db2w3hbgln5ogjqo21v9
