### ISSUE TITLE
s3_auth does not retry after a file read error

### ISSUE THREAD

**Issue by moonchen** [apache/trafficserver#11831]
If s3_auth attempts to load its configuration from file and fails due to a file system error, it will not retry on its own.  This can cause credentials to expire without being renewed.

**Comment by mlibbey** [comment]
related... the docs (https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/origin_server_auth.en.html / https://docs.trafficserver.apache.org/en/10.0.x/admin-guide/plugins/s3_auth.en.html) don't appear mention the new reload functionality.

**Comment by mlibbey** [comment]
It also seems to remove a non-expired token when the error occurrs.
