### ISSUE TITLE
Cant open Pages on latest stable firefox

### ISSUE THREAD

**Issue by V1TA5** [apache/trafficserver#11851]
#### Client:
Operating system: Windows 10
Firefox version: Firefox 132.0
#### Server:
Ubuntu 20 LTS focal
ATS  8.0.5+ds-3

### Steps to reproduce:

    Navigate to: https://spacedock.info/
    Observe

### Expected Behavior:
The page loads

### Actual Behavior::
"Secure connection failed" error

### Diagnosis by mozilla Devs:
The server seems to reset the connection upon receiving SETTINGS_NO_RFC7540_PRIORITIES
This is ultimately a server bug, but I just checked, and it seems Chrome doesn't send SETTINGS_NO_RFC7540_PRIORITIES at all, even though it's using the priority header.

### Reference issue in mozilla Firefox Bug Tracker:
https://bugzilla.mozilla.org/show_bug.cgi?id=1928600

Any way to solve that with config settings?
### bonus question:
any distro with proxmox lxc templates or repo for one that always offers the latest stable release?

**Comment by maskit** [comment]
The issue should be fixed on 9.x and later (#5266). Version 8.x is EOL and no longer maintained.
