### ISSUE TITLE
ATS 9.2.6 fails to start as root

### ISSUE THREAD

**Issue by jvgutierrez** [apache/trafficserver#11869]
As a side effect of https://github.com/apache/trafficserver/pull/11855 ATS is now unable to start as root:

[traffic_manager uses ImpersonateUser() ](https://github.com/apache/trafficserver/blob/de3e58726f6f58a95266a41eaa31ff3c6fc14336/src/traffic_manager/traffic_manager.cc#L1084)to drop privileges triggering the following syscalls:
```
450941 setgroups(1, [123])              = 0
450941 setresgid(-1, 123, -1)           = 0
450941 setresuid(-1, 118, -1)           = 0
```

afterwards traffic_server attempts to drop privileges as well but setgroups fails due to lack of permissions:
```
450952 setgroups(1, [123])              = -1 EPERM (Operation not permitted)
```

**Comment by jvgutierrez** [comment]
```diff
-  if (initgroups(pwd->pw_name, pwd->pw_gid) != 0) {
-    Fatal("switching to user %s, failed to initialize supplementary groups ID %ld", pwd->pw_name, (long)pwd->pw_gid);
+  if (geteuid() == 0) {
+    if (initgroups(pwd->pw_name, pwd->pw_gid) != 0) {
+      Fatal("switching to user %s, failed to initialize supplementary groups ID %ld", pwd->pw_name, (long)pwd->pw_gid);
+    }
```

 could be a potential solution for this, @maskit what do you think?

**Comment by maskit** [comment]
Oh, traffic_manager... Yeah, it's an oversight and there was no intention to make ATS unable to start as root. Would you make a PR?
