### ISSUE TITLE
Could you add the tag 7.0.0?

### ISSUE THREAD

**Issue by hnakamur** [apache/trafficserver#1222]
Since trafficserver 7.0.0 was released, the tag `7.0.0` would be helpful.
Thanks!

**Comment by bryancall** [comment]
It is on the Apache git repo.  I don’t know why it didn’t sync with github.  I will have to investigate.

https://git-dual.apache.org/repos/asf?p=trafficserver.git

**Comment by hnakamur** [comment]
Thanks.
For my memo, https://github.com/apache/trafficserver/commit/6c1c6cf20e7d0e287d697a0f4181436013d17c30 is the commit tagged 7.0.0

**Comment by bryancall** [comment]
I manually pushed the tags to github.  Thank you for bringing this up.

**Comment by hnakamur** [comment]
I confirmed the tag `7.0.0` now exists.
Thanks for a quick response!
