### ISSUE TITLE
remap plugin won't work

### ISSUE THREAD

**Issue by abbycin** [apache/trafficserver#1251]
### Brief
calling the following functions before **TS_HTTP_POST_REMAP_HOOK** cause rule in remap plugin don't work.
```c++
TSUrlPortSet();
TSUlPathSet();
TSUrlHostSet();
TSUrlSchemeSet();
```
here is one line in `remap.config`
```
map http://192.168.16.174/ http://192.168.16.174/  @plugin=libtslua.so  @pparam=/usr/local/etc/trafficserver/sta_modifyurl.lua
```
-----
### Detail
here is code fragment from `cacheurl.cc`, the left side only `#if 1` and `#endif` is new code and the right side is a new header file to modify client request url.  
the hook point is **TS_HTTP_READ_REQUEST_HDR_HOOK**
![cacheurl](https://cloud.githubusercontent.com/assets/6814167/20957749/88d3712e-bc8c-11e6-8873-5ee07892d460.png)

the code in above picture will cause the `libtslua.so` won't work, even not enter in any of the following functions in `ts_lua.c` (the ts-lua plugin source is [here](https://github.com/portl4t/ts-lua))
```c++
TSReturnCode
TSRemapInit(TSRemapInterface *api_info, char *errbuf, int errbuf_size);

TSReturnCode
TSRemapNewInstance(int argc, char *argv[], void **ih, char *errbuf, int errbuf_size);

void
TSRemapDeleteInstance(void *ih);


TSRemapStatus
TSRemapDoRemap(void *ih, TSHttpTxn rh, TSRemapRequestInfo *rri);

static int
globalHookHandler(TSCont contp, TSEvent event ATS_UNUSED, void *edata);
```

-----

So, what's wrong after calling those **Set** functions, and how to solve this problem ?
Thank you!

**Comment by shukitchan** [comment]
If you called TSSkipRemappingSet() after doing those Set functions, then the remap related functionality will be skipped.

**Comment by abbycin** [comment]
@shukitchan 
There's not such function in both `cacheurl` plugin and `ts-lua` plugin, and I'm pretty sure I never called `TSSkipRemappingSet()`. The only thing I've done is add some functions to change request URL.

**Comment by shukitchan** [comment]
is it only ts-lua plugin not working? or all remap plugins are not working?

**Comment by abbycin** [comment]
@shukitchan
there are three map rule in remap.config
```
map http://192.168.56.102:80/cache/ http://{cache}
map http://192.168.56.102/ http://192.168.56.102/  @plugin=libtslua.so  @pparam=/usr/local/etc/trafficserver/sta_modifyurl.lua
regex_map http://(.*) http://$1
```
as you can see, the remap plugin is only `ts-lua`, and only `cacheurl` plugin is enabled in plugin.config.

**Comment by shukitchan** [comment]
i mean if you use other remap plugins in your remap rule (e.g. conf_remap) , do they also not work?
just trying to see if it is a ts_lua specific problem or not.

**Comment by shukitchan** [comment]
oh. also if you set the host/port in read request hook (i.e. before mapping happens), it may not match the second line at all  (the one with the lua plugin).
It may leverage the third line (i.e. the regex_map line) instead.

**Comment by abbycin** [comment]
@shukitchan 
problem solved, thank you!!!
