### ISSUE TITLE
Can trafficserver proxy to another proxy?

### ISSUE THREAD

**Issue by lucaswxp** [apache/trafficserver#1301]
So, I have a third party proxy (probably under squid) which will only accept connections from one of my IP's, but I need to be able to access it from a variety of IPs.

So I'm trying to put a trafficserver to forward requests to this proxy. I tried the following:

```
regex_map http://(.*)/ http://myproxy:80/
```

But I get in logs status 502 (Server Hangup) for my requests, I guess because trafficserver is proxying like this:

```
http_proxy=http://trafficserver.com curl -v http://www.targetdomain.com.br/index.html

> GET /index.html HTTP/1.1
> Host: www.targetdomain.com.br
```

But I need it to proxy like this:

```
http_proxy=http://trafficserver.com curl -v http://www.targetdomain.com.br/index.html

> GET http://www.targetdomain.com.br/index.html HTTP/1.1
```

So that the third party proxy understands it.

Can trafficserver do this?

**Comment by zwoop** [comment]
This really belongs on the users@trafficserver.apache.org mailing list. I'm going to close this, but the short answer is that you could use the parent.config instead of remap.

**Comment by lucaswxp** [comment]
@zwoop That's already helpful. Thanks!
