### ISSUE TITLE
[openbsd] pthread_np.h needs to be included

### ISSUE THREAD

**Issue by jirib** [apache/trafficserver#1306]
This passes at least some first steps in trying to build trafficserver on OpenBSD. Please consider this or better variation, thank you.

```
kern.version=OpenBSD 6.0-current (GENERIC.MP) #0: Wed Nov 23 20:54:10 MST 2016
    build@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
```

```
--- lib/ts/ink_thread.h.orig    Thu Oct 20 21:08:55 2016
+++ lib/ts/ink_thread.h Sat Jan  7 21:16:56 2017
@@ -44,6 +44,10 @@
 #include <signal.h>
 #include <semaphore.h>

+#if defined(openbsd)
+#include <pthread_np.h>
+#endif
+
 #if HAVE_PTHREAD_NP_H
 #include <pthread_np.h>
 #endif
```

**Comment by jpeach** [comment]
The doesn't the existing configure check pick this header up?

**Comment by jirib** [comment]
config.log https://gist.github.com/jirib/70174b76156791036eca9a80f5ff0120

**Comment by jirib** [comment]
putting this -  ac_cv_header_pthread_np_h=yes - as configure env doesn't need to change ink_thread_.h

**Comment by zwoop** [comment]
Yeh, I agree with peach, it seems very odd that it's not picking it up properly. It'd be better to fix that, instead of ifdef on openbsd IMO.
