### ISSUE TITLE
NULL in records.config being interpreted as a string

### ISSUE THREAD

**Issue by persiaAziz** [apache/trafficserver#1323]
CONFIG proxy.config.ssl.client.cert.path STRING NULL
CONFIG proxy.config.ssl.client.cert.filename STRING NULL
 The two configs above make SSLClientUtils.cc: SSLInitClientContext() make a path "NULL/NULL" and try to load certificate from it which means the configs are pointing to string "NULL". Looks like a parsing error

**Comment by zwoop** [comment]
I think this got broken with ced4da13279f834c381925f2ecd1649bfb459e8b.

**Comment by persiaAziz** [comment]
PR: https://github.com/apache/trafficserver/pull/1325
