### ISSUE TITLE
openssl errors for every request

### ISSUE THREAD

**Issue by randall** [apache/trafficserver#1341]
With ATS 7.1, the server will come up cleanly (same configs that work fine under 7.0.0), but a request will generate the following log lines.

`Jan 18 17:36:05 hostname traffic_server[380]: {0x2ae6a690c700} ERROR: SSL::47170125350656:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting: TRUSTED CERTIFICATE
 Jan 18 17:36:05 hostname traffic_server[380]: {0x2ae6a690c700} ERROR: SSL::47170125350656:error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib:ssl_rsa.c:708
 Jan 18 17:36:05 hostname traffic_server[380]: {0x2ae6a690c700} ERROR: failed to load client certificate from (null)`

The request completes successfully, but is very noisy server side.

**Comment by zwoop** [comment]
Looking at 63b924e8, it seems we produce this error, and do these expensive lookups / additions on every request?

```C++
@@ -4018,7 +4020,7 @@ HttpSM::do_remap_request(bool run_inline)
 {
   DebugSM("http_seq", "[HttpSM::do_remap_request] Remapping request");
   DebugSM("url_rewrite", "Starting a possible remapping for request [%" PRId64 "]", sm_id);
-
+  SSLConfig::scoped_config params;
   bool ret = false;
   if (t_state.cop_test_page == false) {
     ret = remapProcessor.setup_for_remap(&t_state);
@@ -4059,6 +4061,16 @@ HttpSM::do_remap_request(bool run_inline)
     pending_action = remap_action_handle;
   }

+  // check if the overridden client cert filename is already attached to an existing ssl context
+  ats_scoped_str clientCert(Layout::relative_to(t_state.txn_conf->client_cert_filepath, t_state.txn_conf->client_cert_filename));
+  auto tCTX = params->getCTX(clientCert);
+
+  if (tCTX == nullptr) {
+    // make new client ctx and add it to the ctx list
+    auto tctx = params->getNewCTX(clientCert);
+    params->InsertCTX(clientCert, tctx);
+  }
+
```

**Comment by randall** [comment]
The full stack from the thread hitting this:

[stack.txt](https://github.com/apache/trafficserver/files/715338/stack.txt)

**Comment by persiaAziz** [comment]
PR: https://github.com/apache/trafficserver/pull/1347/files

**Comment by bryancall** [comment]
This has been resloved
