### ISSUE TITLE
Origin SNI

### ISSUE THREAD

**Issue by jp557198** [apache/trafficserver#1344]
I currently have ATS configured to support a pristine host header.

   proxy.config.url_remap.pristine_host_hdr 1

I also have ATS configured to verify the origin server certificate.

   proxy.config.ssl.client.verify.server 1

My remap looks like this.

   map https://edge.tld/ https://origin.tld/

Because pristine is enabled, when ATS sends a request back to the origin, it uses a SNI value of:

     edge.tld

However, the origin returns a certificate that does not match the SNI. Specifically a CN of 'origin.tld'

Because the requested SNI and the returned CN/SAN do not match, coupled with verify.server enabled, ATS throws a TLS alert and sends a 502 back to the client.

After some testing it appears that when the origin request is built, the SNI is derived from the original client HOST header.  In situations where the origin certificate will not match the requested SNI value, the ATS administrator needs the ability to change the SNI accordingly.

A current work around is to use a lua script to modify the original client HOST header as the origin request is being built. This work around allows the administrator to modify the SNI to the desired value. This workaround as shown here(after cache lookup) does not impact cache key, or change the stored URL as part of an object's stored metadata. Changing the client HOST header before cache lookup impacts the cache key, etc. So an administrator must take care whenever the client HOST header is modified,. 

++++++++
function cache_lookup()
   ts.client_request.header['Host'] = 'origin.tld'
    return 0
end
function do_remap()
  ts.hook(TS_LUA_HOOK_CACHE_LOOKUP_COMPLETE, cache_lookup)
     return 0
end
++++++++     

Ideally there should be an over-ride option that sets the SNI which has priority over the client HOST header. One thought is to pass origin TLS options on the remap line.

Something like..

map https://edge.tld/ https://origin.tld/ tlsopt:sni=origin.tld;tlsopt2=foo;tlsopt3=bar

(maybe as a start only support a SNI tlsopt. add support for more tlsopts as ATS evolves)

**Comment by brkishore** [comment]
I will work on the solution for this issue. Can someone assign it to me?

**Comment by bryancall** [comment]
@brkishore Only committers can have issues assigned to them.  It is a limitation of GitHub.

Please submit a PR for it once you have a fix.  Thank you!

**Comment by brkishore** [comment]
Thanks Bryan. I will first share my solution approach with you then I will submit PR.

**Comment by persiaAziz** [comment]
@brkishore are you still working on this?

**Comment by jp557198** [comment]
kishore has moved onto another group.
i will talk to our other dev members and move assignment to one of them.

**Comment by jp557198** [comment]
persia.. btw.. i dont have your contact information.. if possible can you post your SNI presentation somewhere or maybe email it to me?

thanks!

jeremy

**Comment by persiaAziz** [comment]
Hey Jeremy,

Sure . I will send you a link to my presentation.

**Comment by persiaAziz** [comment]
sent to your gmail account

**Comment by mlibbey** [comment]
Does https://github.com/apache/trafficserver/pull/254 solve this?

**Comment by pbchou** [comment]
@jp557198 can you review the discussion mentioned and indicate whether this issue should remain open?

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
