### ISSUE TITLE
relative_to(char* path, char* filename) should return null if path is null

### ISSUE THREAD

**Issue by persiaAziz** [apache/trafficserver#1346]
Digging down the code, ink_filepath_merge(char *path, int pathsz, const char *rootpath, const char *addpath, int flags) concatenates the current working directory with the filename if the rootpath is null. If this is expected to do this, then at least, we should not let relative_to function call ink_filepath_merge if either filepath or filename is null

also set_paths_helper should check if either filename or filepath is null before calling the concat function

**Comment by webdriverrr** [comment]
@bryancall set_paths_helper() already checks for *path || *filename to be nullptr.

**Comment by webdriverrr** [comment]
@bryancall relative_to() doesn't call ink_filepath_merge() directly anymore. Arguments *dir and *file now are not PODs (pointers) - they are string_view class instances instead.
I believe this issue doesn’t reflect actual source code thus can be closed.

**Comment by bryancall** [comment]
ink_filepath_merge is still called by _relative which is called by layout_relative.

**Comment by webdriverrr** [comment]
Yes but pointer arguments are not present anymore. As I get it the main concern was about pointer args and possibility of getting segfault in case of nullptr. @persiaAziz isn't ?

**Comment by bryancall** [comment]
If this is still an issue please reopen.
