### ISSUE TITLE
Possible spurious warning in InkAPI

### ISSUE THREAD

**Issue by clearswift** [apache/trafficserver#1351]
The InkAPI.cc code has a warning in the handle_event method:
 Warning("INKCont Deletable but not deleted %d", m_event_count);

This seems to get triggered when I do not think there is an issue. This can be recreated by running the NullTransformation C++ SDK example plugin. While monitoring the diags.log file this warning can be observed sometimes while browsing. I used wget a number of times and this warning would be raised sometimes.

I added logging to the InkAPI.cc where the free() method is called and it seems that all of the continuations/vconns are being freed.

The bnull-transform example does not show this problem but it can be adapted to use the same logic as the C++ SDK and then the warning does start to appear. To do this I added a TS_HTTP_TXN_CLOSE_HOOK hook and then called TSContDestroy on the transform vconn where it was originally destroyed in the transform event handler. I have attached the source code for this.

Is my assumption correct that this warning is not required?

[bnull-transform-warning.zip](https://github.com/apache/trafficserver/files/719272/bnull-transform-warning.zip)

**Comment by randall** [comment]
This was addressed by commit 093778c
