### ISSUE TITLE
Documentation for volume.config is confusing and obsolete

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1352]
In particular, the example with scheme=http / scheme=https is invalid, there's only one protocol that's supported, http (for all HTTP versions).

**Comment by mlibbey** [comment]
https://docs.trafficserver.apache.org/en/latest/admin-guide/files/volume.config.en.html
no longer has scheme=https.

What else needs to happen?

**Comment by zwoop** [comment]
Sounds good, lets close this :)
