### ISSUE TITLE
HdrHeap potential corruption

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#1367]
Would see this sometimes during the host header manipulation.  The original code assumes that the string pointer from the field will stay static over other header manipulation calls.  But thanks to coalescing, the string pointers may move around causing bad behavior.

**Comment by maskit** [comment]
I faced a similar problem over 2 years ago.
https://issues.apache.org/jira/browse/TS-2792

**Comment by shinrich** [comment]
Hopefully this fixes what you saw @maskit.  Looking at the discussion on TS-2792 had it been solved before?

**Comment by maskit** [comment]
Yes, I solved the problem, but the coalescing issue is still alive. This kind of bugs can be made again until we get some measure for it.

**Comment by shinrich** [comment]
PR commited.
