### ISSUE TITLE
Traffic Server - 6.2.1: Client streams count not updated in Http2ConnectionState.

### ISSUE THREAD

**Issue by jaaju** [apache/trafficserver#1394]
The `client_streams_count` member is incremented when a new stream is created, but never decremented. This causes a protocol error leading to "Connection closed" errors in the client.

Traffic Server details:
Branch: 6.2.x
Platform: Linux, 64-bit, compiler `g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)`

Steps to repro:
Enable `http2` in records.config.
Fetch from Chrome an HTML resource that references several other resources (javascript or css), all proxied by the same ATS instance.

Most of the fetched resources should be reported by Chome as `cancelled` or report a `net::ERR_CONNECTION_CLOSED` error.

The fix is just one line, to decrement the `client_streams_count` member of `Http2ConnectionState` when a stream is released. I shall send a pull request.

**Comment by masaori335** [comment]
@jaaju Does this happen on 7.x?

**Comment by masaori335** [comment]
I confirmed that this issue happens only 6.2.x.

**Comment by jaaju** [comment]
@masaori335, yes that's right. It's only seen in 6.2.x.

**Comment by masaori335** [comment]
@jaaju Thanks!
It looks like the code is dropped accidentally, when back port TS-4813 to 6.2.x.
