### ISSUE TITLE
Paft of tcp_congestion_control code was erased by push TS-3612

### ISSUE THREAD

**Issue by shenzhang920** [apache/trafficserver#1399]
ATS can change the tcp_congestion_control algorithm on both client side and server side, this functionality was added in 5.x.  The push of TS-3612 accidentally remove some part of the code. (by removing HttpClientSession.cc and adding Http1ClientSession.cc/Http2ClientSession.cc,  some of the code in HttpClientSession.cc was missing)

**Comment by maskit** [comment]
@shenzhang920 Thank you for the pull-requests and your patience.
The fix has been merged on master and 6.2.x.

@zwoop This is not a critical issue but I think we should backport the fix to 7.1 too, or it will be degradation when migrating from 6.2.2 to 7.1.x.
Please let me know if you want me to send a pull-request for 7.1.

**Comment by maskit** [comment]
Fixed on 6.2.x, 7.1.x and master.
