### ISSUE TITLE
idempotent requests should be retryable irrespective of the state of the connection

### ISSUE THREAD

**Issue by vmamidi** [apache/trafficserver#1403]
According to RFC  ( https://tools.ietf.org/html/rfc7231#section-4.2.1 ) all the idempotent methods should be retryable but we can at least try to retry the safe requests. The methods GET, HEAD, OPTIONS, and TRACE are considered safe. 

ATS does not retry any requests based on the connection state with Origin Server and bytes sent to Origin Server. ATS should retry all the safe requests to give a chance to serve the request instead of responding with 502. 

Also, we can make this configurable so that ATS can handle special scenarios.

**Comment by zwoop** [comment]
Closing, since we have a PR already.

**Comment by bryancall** [comment]
This is the PR for this issue: #1404
