### ISSUE TITLE
PURGE request returns 404 when map rule uses authproxy

### ISSUE THREAD

**Issue by happyaron** [apache/trafficserver#1417]
Testing environment:

OS: Debian testing amd64
ATS: 7.0.0
package version: 7.0.0-4

1. remap.config:
> map http://auth.internal/ http://auth.internal/
> map http://test.example.com/ http://backend.internal/    @plugin=authproxy.so @pparam=--auth-transform=redirect @pparam=--auth-host=auth.internal @pparam=--auth-port=80

2. records.config snip:
> CONFIG proxy.config.url_remap.remap_required INT 1
> CONFIG proxy.config.url_remap.pristine_host_hdr INT 1
> CONFIG proxy.config.reverse_proxy.enabled INT 1
> CONFIG proxy.config.http.doc_in_cache_skip_dns INT 0

3. auth.internal always return 200 OK here:
> $ curl -v4X PURGE http://auth.internal/
> \* Hostname was NOT found in DNS cache
> \*   Trying a.b.c.d...
> \* Connected to auth.internal (a.b.c.d) port 80 (#0)
> \> PURGE / HTTP/1.1
> \> User-Agent: curl/7.38.0
> \> Host: auth.internal
> \> Accept: */*
> \> 
> \< HTTP/1.1 200 OK
> \< Date: Fri, 03 Feb 2017 17:13:21 GMT
> \* Server Apache is not blacklisted
> \< Server: Apache
> \< Expires: Thu, 19 Nov 1981 08:52:00 GMT
> \< Cache-Control: no-store, no-cache, must-revalidate
> \< Pragma: no-cache
> \< Set-Cookie: SESSION_NAME=ir6l53v0474cffo7bv0o21qmn6; path=/; HttpOnly
> \< Content-Length: 0
> \< Content-Type: text/html; charset=UTF-8
> \< 
> \* Connection #0 to host auth.internal left intact

4. Make some modifications to index.html, test to PURGE:
> $ curl -v4X PURGE http://test.example.com/
> \* Hostname was NOT found in DNS cache
> \*   Trying e.f.g.h…
> \* Connected to test.example.com (e.f.g.h) port 80 (#0)
> \> PURGE / HTTP/1.1
> \> User-Agent: curl/7.38.0
> \> Host: test.example.com
> \> Accept: */*
> \>
> \< HTTP/1.1 404 Not Found
> \< Date: Fri, 03 Feb 2017 17:24:48 GMT
> \< Connection: close
> \* Server ATS is not blacklisted
> \< Server: ATS
> \< Content-Length: 14
> \< Content-Type: text/plain
> \* Closing connection 0
> 404 Not Found

5. ATS log:
> 1486142993.517 0 192.168.1.1 TCP_MISS/404 114 PURGE http://auth.internal/ - NONE/- -
> 1486142993.517 0 192.168.1.1 TCP_MISS/404 155 PURGE http://backend.internal/ - DIRECT/- text/plain

6. Verified that the content is not actually purged (index.html content not updated).

**Comment by bryancall** [comment]
If this is still an issue please reopen.

**Comment by mlibbey** [comment]
oh. I was assuming it was related to the title.

From your mapping, it doesn't seem to follow the pattern on the examples link (https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/plugins/authproxy.en.html#examples)

like, I think I'd expect something along the lines of
map inboundurl temporary_origin_name @plugin=authproxy ...

map temporary_origin_name origin

(eg, I don't see how ATS would get from the1st rules' mapped "https://example.com/"  to the next mapping's inbound "http://127.0.0.1:9000/ (and thus, then to origin) [and then your last comment confuses me more -- based on the mapping, I would have thought that the curl would be to http://192.168.1.6:9000/)

**Comment by mbakturk** [comment]
Hi @mlibbey I updated my remap.config according to your comment. Authproxy started to work. ATS sends request to my auth server however in this time I have "Cycle Prohibited".

curl http://localhost:8080

Cycle Prohibited
Description: Could not process your request for the document because it would cause an HTTP proxy cycle. Please check the URL and your browser's proxy settings.

**remap.config:**
map http://127.0.0.1:9000/ http://192.168.1.6:9000/
map http://localhost:8080/ http://admin.internal:8080/ @plugin=authproxy.so \
    @pparam=--auth-transform=redirect @pparam=--auth-host=127.0.0.1 @pparam=--auth-port=9000

map http://admin.internal:8080/ http://example.com/

**/etc/hosts:**
127.0.0.1 admin.internal

**P.S.** I can get example.com's response when I send request to admin.internal:8080 (curl http://admin.internal:8080).

**Comment by mlibbey** [comment]
This is one of ours:
map http://inbound \
    http://origin \
    @plugin=authproxy.so @pparam=--auth-transform=range

map http://origin \
    http://origin \
    @plugin=conf_remap.so @pparam=proxy.config.http.cache.http=0 \
      @pparam=proxy.config.url_remap.pristine_host_hdr=1

(I don't know why we have that pristine host setting -- looks pointless to me). If that doesn't work, could also try setting
proxy.config.http.insert_request_via_str (https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-http-insert-request-via-str) in one of them (dunno if it matters which!). Stripping the via should prevent the loop detection.

**Comment by mbakturk** [comment]
Hi @mlibbey thanks for your answers. As you mentioned after using proxy.config.http.insert_request_via_str, cycle prohibited problem fixed. My last configuration is below:

**remap.config:**
map http://127.0.0.1:9000/ http://192.168.1.6:9000/
map http://localhost:8080/ http://admin.internal/ \
 @plugin=conf_remap.so @pparam=proxy.config.http.insert_request_via_str=0 \
 @plugin=authproxy.so @pparam=--auth-transform=redirect @pparam=--auth-host=127.0.0.1 @pparam=--auth-port=9000

map http://admin.internal/ http://example.com/

**Comment by mlibbey** [comment]
The admin to example rule definitely needs caching turned off to prevent caching being used for the auth request/response.
