### ISSUE TITLE
Segmentation fault on TLS when destination server issues Reset

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1421]
Creating this issue, copying from the original Jira to capture all the details.

On HEAD as of 16DEC2016 (102b66b9730780289ef71fa1ee33214cbcbcdde2)
When in Forward proxy mode, connecting to an HTTPS site, where the destination site responds with TCP RESET, Traffic Server will restart due to Sig 11: Segmentation fault.
If the upstream site instead silently drops the response, ATS will successfully proceed with 502 (Tunnel Connection Failed).
No proxy chaining involved, direct: client -> ATS -> destination.
Test machine: Debian Jessie (8.6) x86_64
To replicate, make an HTTPS request - via ATS in forward-proxy-mode - to a local (non-firewalled) server, with nothing running on TCP/443.
Watch manager.log for near immediate "[LocalManager::pollMgmtProcessServer] Server Process terminated due to Sig 11: Segmentation fault" followed by "[Alarms::signalAlarm] Server Process was reset"
The issue was introduced in c1ac5f8bf87fd4bc3a8e06507219970d83965acd TS-4796

No promises - I'll see what I can do.
I've tracked it down to the change to line 508 in iocore/net/UnixNet.cc
https://github.com/apache/trafficserver/commit/c1ac5f8bf87fd4bc3a8e06507219970d83965acd#diff-24ea729d4646e63a76dd276a189da30cR508

This is all from "Craig B" in TS-5098.

**Comment by zwoop** [comment]
@jacksontj Ping on this one?

**Comment by shinrich** [comment]
Related discussion on issue #1401.  I have a hacky PR related to that issue, which has enabled us to continue on.  It is definitely triggered by the error bubbling changes.  I didn't pin it to a server reset though.  Makes our servers crash within a minute.

**Comment by shinrich** [comment]
Issue has been solved.  See comment on issue #1401
