### ISSUE TITLE
PROXY_CONFIG_CONFIG_DIR doesn't change sysconfig directory at run time

### ISSUE THREAD

**Issue by gksalil** [apache/trafficserver#1425]
Hello 

   I have been trying to change the runtime directory and config directory for traffic_server in my server… I got to know that by over riding PROXY_CONFIG_LOCAL_STATE_DIR and PROXY_CONFIG_CONFIG_DIR, this can be achieved

This is what I tried 

`PROXY_CONFIG_LOCAL_STATE_DIR=/newtrafficserver/var/trafficserver PROXY_CONFIG_CONFIG_DIR=/newtrafficserver/etc  TS_ROOT=/trafficserver/ /trafficserver/bin/traffic_layout
`
```
PREFIX: /trafficserver

BINDIR: /trafficserver/bin

SYSCONFDIR: /newtrafficserver/etc

LIBDIR: /lib64

LOGDIR: /mnt/harddisk/log/trafficserver

RUNTIMEDIR: /newtrafficserver/var/trafficserver

PLUGINDIR: /trafficserver/libexec/trafficserver

INCLUDEDIR: /trafficserver/include

SNAPSHOTDIR: /newtrafficserver/etc/snapshots

records.config: /newtrafficserver/etc/records.config

remap.config: /newtrafficserver/etc/remap.config

plugin.config: /newtrafficserver/etc/plugin.config

ssl_multicert.config: /newtrafficserver/etc/ssl_multicert.config

storage.config: /newtrafficserver/etc/storage.config

hosting.config: /newtrafficserver//etc/hosting.config

volume.config: /newtrafficserver/etc/volume.config

ip_allow.config: /newtrafficserver/etc/ip_allow.config

[E. Mgmt] log ==> [TrafficManager] using root directory '/trafficserver'

traffic_server: using root directory '/trafficserver'

URL Rewrite table with 1 entries

  Reverse Proxy is On

  Forward Mapping Table with 1 entries

    Regex mappings:

http://(.{3,1023}):8443/ => http://invalidhost_/  <> [plugins are enabled; running with 4 plugins]

  Reverse Mapping Table with 0 entries

  Permanent Redirect Mapping Table with 0 entries

  Temporary Redirect Mapping Table with 0 entries

  Forward Mapping With Recv Port Table with 0 entries

  Referer filter default redirect URL: "http://www.example.com/"


```

Layout shows the correct values. But what happens is - the records.conf file from /newtrafficserver/etc/ is not considered for internal configuration traffic_server. The reason is - in /newtrafficserver/etc/records.conf, I have set server_port as 

`CONFIG proxy.config.http.server_ports STRING 8445
`

but when I run ps -ef | grep traffic_server the following is the output

 ```
ps -ef | grep traffic

_ats      5720  5695  0 17:47 pts/0    00:00:00 /trafficserver/bin/traffic_manager

_ats      5811  5720  1 17:47 pts/0    00:00:00 /trafficserver/bin/traffic_server -M --httpport ip-in=[127.0.0.1]:8443:fd=7

root      6256  3250  0 17:47 pts/1    00:00:00 grep traffic
```

8443 is the port set in a records.conf in the default location of records.conf.

Even the server.locks manager.lock and processserver.sock etc are created in the default location only ( where the prefix and sysconfigdir and localstatedir variable set during ./config phase )

Thanks
Salil

Thanks
Salil

**Comment by maskit** [comment]
`config_dir` is a read-only configuration. Some of configurations are not configurable at runtime.
https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-config-dir

Because overriding takes place WHILE (not before) reading `records.config`, changing `config_dir` with the environment variable is too late, though `traffic_layout` shows the new value. Even if you specify the new location in the config file, it wouldn't work due to the same reason, the file has already been open.

I've never used `TS_ROOT`, but it might work.
