### ISSUE TITLE
Mysterious uptick in user_agent SSL errors moving to 7.1

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#1459]
Comparing a machine running 7.1.x against its peer running our version of 5.3.x.  A number of the proxy.process.ssl.user_agent_* metrics started increasing in the 7.1 build.  Namely proxy.process.ssl.user_agent_unknown_cert and proxy.process.ssl.user_agent_bad_cert.

I did packet captures for a few seconds on both machines to verify that this wasn't just a change in logging behavior.  On the 7.1.x box with 5000 TLS handshakes captured we saw 81 Certificate Unknown alerts and 5 Bad Cert alerts. On the 5.3.x box with 23000 handshakes captured, 1 Bad Cert alert (from an internal IP) and 4 Certificate Unknown alerts (3 from the same IP address).

After running for a few minutes, the rate of alerts in the 7.1 build does not go down.  It isn't huge, but the difference is alarming me enough that I am not expanding my testing until I have a good story for this.

Will go back and run 7.1.x with ASAN.  Perhaps the cert buffers are getting corrupted in some cases?

**Comment by shinrich** [comment]
Found this was an issue in the changes made in our version of 7.1 shown in PR #1446.  I will update the PR with the fix.  As it stands, if there is no servername hook, the cert hook will never be called.  This means that certificates specified by the SNI name will never be selected.

**Comment by SolidWallOfCode** [comment]
Will you be updating this PR?

**Comment by zwoop** [comment]
Is this still an issue? Or should it be closed?

**Comment by shinrich** [comment]
Yes, this is still an issue.  I need to do some more testing on PR #1446.  Some variant of that will need to be added to 7.1.

**Comment by shinrich** [comment]
Solution merged.  Issue is addressed.
