### ISSUE TITLE
On restart proxy.node.user_agent_xacts_per_second stat nonsensical

### ISSUE THREAD

**Issue by realpdm** [apache/trafficserver#1463]
When I restart ATS the proxy.node.user_agent_xacts_per_second stat goes very high before turning to normal This is captured by our graphing system and confuses graph scales.

It is reproducible by simply restarting ATS

In one window I had a while loop running:
>while; do sudo traffic_line -r proxy.node.user_agent_xacts_per_second; sleep 5; done
In other window restarted ATS on my dev machine with no load. 

0.000000
0.000000
0.000000
153903.171875
153903.171875
0.090898
0.090898

Apache Traffic Server - traffic_server - 6.2.1 - (build # 020315 on Feb  3 2017 at 15:54:56)

**Comment by realpdm** [comment]
It might be useful to note that when ATS crashes it doesn't seem to have this behavior, bur a proper shut down/restart does

**Comment by bryancall** [comment]
No longer valid in newer releases of ATS.
