### ISSUE TITLE
HTTP Transaction Debugging Feature

### ISSUE THREAD

**Issue by chenglongwei** [apache/trafficserver#1483]
### Goals
HTTP request debugging feature in ATS core can help ATS DevOps to quickly locate an issue at development, staging or production environments. Users can specify a single request they want to debug by marking it with a cookie. This feature logs the HTTP headers of the debugged request and its response before and after each plugin execution for each hook. This will allow engineers to identify issues due to plugin bugs and help them make sense of various changes happening throughout the request/response pipe.

### Specifications

1. Only allow certain IPs to use this feature.
For security reason, the IPs allowed to use this feature should be limited.

2. Specify the debugging request with a cookie “__ts_debug=on”.
This is added to cookie to specify that this request is to be debugged and headers are collected to be logged before and after executing each plugin at every hook.

3. Specify the path of httpdebugger.so with a config item in record.conf “CONFIG proxy.config.http.debugger [path of httpdebugger.so] ”.
This is the implementation of http request debugging.

### Proposed design

![debugging proposal_v5](https://cloud.githubusercontent.com/assets/7145562/24569996/04faf25a-161e-11e7-8909-6ced5fb0f5bf.png)

1. Make a specified request to debug this request and its response. 
2. Before and after each plugin execution for each hook, ATS record the hdrs (HTTP headers) of the debugged request and its response. A blacklist of headers (Cookie, Set-Cookie, Authorization, etc) could be used to avoid sensitive information going to logs.
3. Log the debug information to a log file (Or other implementations).
4. TSHttpTxnBegin() and TSHttpTxnEnd() will be called in the beginning and at the end of the transaction.

**Comment by danobi** [comment]
I wonder if there's a way to roll in header logging for 4xx/5xx transactions into this idea as well.
See #1210.

**Comment by chenglongwei** [comment]
@danobi It could be. But the feature I proposed is mainly to debug plugins. This feature will log headers before and after each plugin execution. As respect to header logging for 4xx/5xx, it only needs to do logging after accept response from origin server.

**Comment by chenglongwei** [comment]
Hi @zwoop @jpeach @SolidWallOfCode , could you give some feedbacks. This debug feature is very useful when dealing with plugin-related bugs and help us make sense of various changes happening throughout trafficserver.

**Comment by chenglongwei** [comment]
#1624

**Comment by bryancall** [comment]
Closing since the PR has been closed.
