### ISSUE TITLE
Inconsistent "exit" strategy on remap.config (and possibly other configurations)

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1490]
It seems, remap.config will allow some bad configurations to still startup, but not others. This seems inconsistent, and we should make it behave. I think (but not sure) that our desired behavior in general is:

1. Don't startup with a bad configuration

2. Don't switch (config reload) from a good configuration to a bad configuration, instead keep using the old one.

**Comment by webdriverrr** [comment]
Hello @zwoop, I can start looking into this if you don't mind.

**Comment by webdriverrr** [comment]
Checking it only with remap.config for a while.
Currently TS doesn't start with invalid remap.config and it seems that new mapping from invalid remap.config are not applied:

In file proxy/http/remap/RemapConfig.cc at line 1114 gets into condition where malformed line is present (true).

**Comment by zwoop** [comment]
Going to close this for now.
