### ISSUE TITLE
Create a keep alive session timeout and/or max # of requests from client on a single session

### ISSUE THREAD

**Issue by realpdm** [apache/trafficserver#1500]
I think there should be a setting for the maximum time a keep alive session can be active and/or a maximum number of requests that can be issued on a client's keep_alive session.  

While I don't want to timeout an active request ever, keep alive sessions that are allowed to live forever pose a problem for draining traffic from an ATS by removing it from a load balancer. Clients who maintain long keep alive sessions will never drain away and will continue to send requests on that session despite the load balancer quiescing the ATS server.

**Comment by maskit** [comment]
previous discussion: https://issues.apache.org/jira/browse/TS-4277

**Comment by bryancall** [comment]
If this is still an issue please reopen.
