### ISSUE TITLE
incorrect configuration in parent.config impacted next line configuration

### ISSUE THREAD

**Issue by zhilhuan** [apache/trafficserver#1501]
Testing ATS 5.3.2 with the following configuration in parent.config:

 dest_domain=live.demo01.labs.com go_direct=true
 dest_domain=vod.demo05.labs.com parent=""  round_robin=consistent_hash go_direct=false qstring=ignore
 dest_domain=live.demo05.labs.com go_direct=true

A warning will be reported as:

[Feb 21 09:21:37.320] Server {0x2af5516f5940} WARNING: [ParentSelection] No parents specified at line 2

However, this impacts the correct configuration in the next line. The default value for "parent_is_proxy" should be "true", but overwritten to "false". 
With debug enabled, we got the following print:

[Feb 21 09:18:53.076] Server {0x2ae3bbc92940} DEBUG: (parent_select) Using a round robin parent selection strategy of type P_NO_ROUND_R
OBIN.
Parent Selection Config
        Enabled 1       RetryTime 300   Parent DNS Only 0
        No Default Parent
  Control Matcher Table: [ParentSelection]
        Host/Domain Matcher with 2 elements
                Domain (Partial) for llive.demo01.labs.com
                 direct=true
 parent_is_proxy=true
                Domain (Partial) for live.demo05.labs.com
                 direct=true
 parent_is_proxy=false

**Comment by zwoop** [comment]
Can you add milestones / labels? Or does the system not let you do that?

**Comment by zhilhuan** [comment]
The system does not allow me to do that. All the options like "Assignees", "Labels" in the right side of this window are grey and not clickable.

**Comment by zhilhuan** [comment]
Close this issue as the fix merged by PR #1502
