### ISSUE TITLE
Set proxy.node.config.reconfigure_time when configurations have finished reloading.

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#1505]
In ATS7, we have a messages line that notes, "remap.config done reloading!", when reload is finished (in proxy/ReverseProxy.cc, reloadUrlRewrite()).

We should set the proxy.node.config.reconfigure_time stat here too -- it currently has the time of the reload request, as opposed to the time of the reload request finish.  The former does not allow one to correlate behavior with a config change -- there is an unknown time delta between the event and the load. Similarly, the former happens regardless of the success of the reload.

**Comment by zwoop** [comment]
But that seems slightly out of order, because that config is, afaik, for any "reconfigure" event (i.e. traffic_ctl config reload), not necessarily remap.config?

**Comment by mlibbey** [comment]
Sure... then set at every place that has the config atomic swap, call some function whose job is to set the proxy.node.config.reconfigure_time ?

**Comment by mlibbey** [comment]
still would like this.

**Comment by bryancall** [comment]
We got rid of the cluster code.
