### ISSUE TITLE
Wrong protocol version in the Via header

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#1506]
```
[bcall@homer ats_ssl_config]$ nghttp -v https://127.0.0.1:4443/200.php
[  0.000] Connected
The negotiated protocol: h2
...
[from ATS going to the origin]
Via: https/1.1 homer.bryancall.com[aa274815-0002-4b4a-a1b2-058c8a2e0829] (ApacheTrafficServer/7.2.0)
```

**Comment by maskit** [comment]
Just FYI:
https://issues.apache.org/jira/browse/TS-4457
https://github.com/apache/trafficserver/pull/1066

**Comment by shukitchan** [comment]
interesting. That's done in the response "Via" header. But not in the request "Via" header. 
https://github.com/apache/trafficserver/blob/master/proxy/http/HttpTransactHeaders.cc#L754-L763

**Comment by shukitchan** [comment]
The fix is merged
