### ISSUE TITLE
Add pkg-config fallback to --enable-system-luajit

### ISSUE THREAD

**Issue by postwait** [apache/trafficserver#1507]
The `--enable-system-luajit` configure option trusts that the invoker has set CPPFLAGS and LDFLAGS appropriately for autoconf to find the luajit headers and libraries.  If they are not found, *as a fallback* pkg-config should be invoked to ask the system to provide assistance and the headers and libs should be rechecked.

pkg-config should not be invoked if the operator has provided sufficient information in CPPFLAGS and LDFLAGS for the AC_CHECK_HEADER and AC_CHECK_LIB checks to pass without the use of pkg-config.

**Comment by bryancall** [comment]
We don't have luajit in our tree anymore and rely on the installed package.
