### ISSUE TITLE
More and slower active connections in 7.1.x

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1527]
I think, but still working on confirming, that the commit in 425b696240ea213. The net effect is that

1. I'm seeing roughly twice as many active connections, even though it's pushing the exact same amount of Gbps.

2. Effectively, I think the average throughput / client is 1/2 of what it should be.

**Comment by shinrich** [comment]
So do you think this is making a real performance difference?  Or are we just not timing out connections as quickly now?

I hadn't noticed a difference in number of active connections, but I'll keep an eye out for that in my testing.

**Comment by oknet** [comment]
Our product based on 6.0.x and backport some commits from master.

With the commit 425b696 , we did not found any vc leaks and performance decrease.

Can you show me how to re-produce it ?

**Comment by zwoop** [comment]
On our boxes, it was very noticeable. I can try again, but the net result was roughly 2-3x the number of active connections, and each transaction was 1/2 - 1/3 the speed (throughput in Mbps). This was measured for large downloads, greater than 1MB in object size.

**Comment by bryancall** [comment]
I backed out the change on master and didn't see a difference with or without this change.

**Comment by zwoop** [comment]
I'm gonna try it again on our prod boxes, but it was very noticeable at high throughput (5-10Gbps).

**Comment by zwoop** [comment]
Yeh, I'm still seeing this. It's roughly half the throughput on each connection, which means I'm also seeing 2x the number of connections. Backing out  425b696 fixes it.

**Comment by keesspoelstra** [comment]
@zwoop  Maybe this has something to do with it:

https://github.com/apache/trafficserver/commit/425b696240ea2133eeb2bbfaf08136b6caa24fe0#diff-907feb7aed591abaaf6cbd94105160f2R413

In read_disable and write_disable 
vc->set_inactivity_timeout(0);  is not the same as vc->next_inactivity_timeout_at = 0; 
The former also resets the inactivity_timeout_in, which might prohibit the net_activity function from setting the inactivity value when stuff gets enabled again and thus not timing. Or timing out on the active timeout, which might be later. I have not followed codepaths to check this.

**Comment by keesspoelstra** [comment]
@zwoop @bryancall when backing out this commit this pull for 6.2.1 might become applicable to 7.1 https://github.com/apache/trafficserver/pull/1675

**Comment by zwoop** [comment]
I backed out this from 7.1.x, but this is still on master, so we still have to address that there. I'm ok with a fix, or reverting as well. @oknet  Any ideas ?

**Comment by zwoop** [comment]
This has been resolved on Master and 7.1.x.

**Comment by oknet** [comment]
resolved by PR #1716
