### ISSUE TITLE
Unable to build 6.2.x with --enable-static-proxy flag

### ISSUE THREAD

**Issue by Tchinmai7** [apache/trafficserver#1528]
I tried building 6.2.x with  --enable-static-proxy flag and it fails during make. 

System details : Ubuntu 14.04.5

Steps followed : 
autoreconf -if
./configure --enable-static-proxy
make

Expected output: 
Successful build

Actual Output:
[makelogs.txt](https://github.com/apache/trafficserver/files/816013/makelogs.txt)
Build aborts. 

Configure logs:
[Configure output.txt](https://github.com/apache/trafficserver/files/815999/Configure.output.txt)

Am I doing something wrong here? Should i be passing any more options to configure? My objective is to have a binary, which i can install on other machines. I donot want to do a `make install`

**Comment by Tchinmai7** [comment]
Any updates on this one? Do you need more info?

**Comment by masaori335** [comment]
Please ignore linked issue. It's my mistake.

**Comment by bryancall** [comment]
6.2 is no longer supported and I believe this build option was removed from later versions.
