### ISSUE TITLE
Consistent hashing in parent.config can use suboptimal URL for hash

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#1553]
(was TS-4025 https://issues.apache.org/jira/browse/TS-4025)
--
original description:
In a setup, where the same assets can have different URLs (e.g. query parameters, or two paths normalized to the same cache key), parent proxy can be suboptimal. This is TS-4020, and the solutions would be similar; Use the cache key (CacheInfo->md5) which is internally what we call LookupURL. LookupURL is that URL that plugins modify to change the cache key.
This has to be rolled out carefully as well, we're thinking something like
6.x - We add a new configuration, that lets you use the LookupURL for the hash (default off)
7.x - We change this new configuration to be enabled by default
8.x - We remove this configuration.
This Jira tracks the first step, we'll file subsequent Jira's for 7.x and 8.x.
--
This is still important to us. We frequently use the cachekey plugin to modify query parameters, the hostname, etc. However, the parent choice is equally important. If we choose the 'wrong parent', the request goes to a parent that has not seen the request before, the effect is the same as an inconsistent cachekey.

**Comment by mlibbey** [comment]
This is still important to us.

Think the steps here imply that it needs to be overwritable. ... parent.config could have the setting too.

**Comment by bryancall** [comment]
If this is still an issue please reopen.

**Comment by gtenev** [comment]
@bryancall , this is something I plan to work on.

**Comment by gtenev** [comment]
The following features were added to 9.x branch to facilitate this functionality 
PR #5872 - "cachekey: added `--key-type` to allow parent selection URL to be modified"
PR #5865 - "cachekey: added `--canonical-prefix` parameter"

Closing.
