### ISSUE TITLE
Support for brotli in gzip plugin.

### ISSUE THREAD

**Issue by myraid** [apache/trafficserver#1555]
Here are the requirements for supporting brotli encoding.

- If the Accept-Encoding has brotli, then the normalize AE should pick up brotli. (Should we send both "br" and "gzip" in AE?
- If the response is already encoded then do nothing. Should we have a configuration to force brotli encode the response?
- If the response is unencoded and if Accept-Encoding has brotli then encode using brotli.

**Comment by bryancall** [comment]
@myraid Issues don't need to be created if there is a PR for it.

The PR for it is: #1557

**Comment by myraid** [comment]
@bryancall realized it after creating the issue.
