### ISSUE TITLE
redundant url encoding for logging field "cquuc"

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#1558]
when client request with query string like %30,
use "cqu" logging filed, it will be recorded it as %30,
but when log with "cquuc", it  will be recorded as %2530,

redundant encoding happened...

**Comment by zwoop** [comment]
What version is this? I could have sworn we fixed this.

**Comment by esmq2092** [comment]
currently i use v6.1.1 and found the problem,

recheck with v7.0.0 and the problem gone.

**Comment by zwoop** [comment]
You should upgrade to 6.2.x, if that doesn't have this fix, you can request this to be back ported to 6.2.2, since 6.2 is an LTS version.
