### ISSUE TITLE
StringView should be made compatible with std::string_view for C++17

### ISSUE THREAD

**Issue by SolidWallOfCode** [apache/trafficserver#1571]
`StringView` is strongly different from the original proposals for string reference classes (e.g. `Boost.StringRef`) but the current proposal for C++17, `std::string_view`, is quite close in design and use. While `StringView` should be retained as it provides a number of essential methods not in `std::string_view`, `StringView` can be made to be a strict superset of `std::string_view` so that any code that uses `std::string_view` can replace `std::string_view` with `StringView`, and any developer used to `std::string_view` could immediately use `StringView`. In addition, `StringView` should promote direct interoperability, providing implicit conversions to and from `std::string_view`.

**Comment by bryancall** [comment]
👍

**Comment by SolidWallOfCode** [comment]
Done.
