### ISSUE TITLE
Clean up h2client.py to be a general testing tool

### ISSUE THREAD

**Issue by dragon512** [apache/trafficserver#1579]
This would require.
1) move h2client.py to tests/tools/...
2) update the autest test extensions under tests/gold_tests/autest-site to support calling h2client more directly as an api

**Comment by persiaAziz** [comment]
I am working (read "hacking hyper") on the h2 module of Traffic-Replay. Once that gets open sourced, we will have a better h2 client. The current h2client is meant just for basic h2 test.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
