### ISSUE TITLE
Make regex_revalidate.c use ref-counted config data

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#1582]
Instead of scheduling a "delete" of the data sometime in the future, a more reliable pattern is to ref-count the configurations, and acquire / release as necessary through the life cycle of the TXN. This would eliminate the **free_cont**, and make things more inline with how we normally do things.

Now, I haven't analyzed the code thoroughly; maybe there is a reason to use the delayed deletes. If so, just close this Issue with a "Won't Fix".

@jrushford You want to take a quick look on this, and see if this is viable at least?

**Comment by jrushford** [comment]
@zwoop I'll take a look.

**Comment by zwoop** [comment]
Going to close this, since this really is not needed for ATS v8.0 and later.

**Comment by zwoop** [comment]
Closing, since traeak is the best.
