### ISSUE TITLE
Remove combohandler feature gate for 8.0 release

### ISSUE THREAD

**Issue by danobi** [apache/trafficserver#1599]
I recently noticed `combohandler` was marking all of its generated documents as `Cache-Control: Public` regardless of what the requested documents contained in `Cache-Control`. That's a bug. I've feature-gated the fix using a `#define FEAT_GATE_8_0` in commit 9d33ca20. It should be undef'd for 8.0 since it's a breaking change.

**Comment by bryancall** [comment]
This define and ifdef should be remove for the 9.0.0 release.

**Comment by zwoop** [comment]
Blocks #5457
