### ISSUE TITLE
if we had a server with big diskspace, function build_vol_hash_table cost to much to build the vol_hash_table for CacheVol

### ISSUE THREAD

**Issue by bluestn** [apache/trafficserver#1603]
**if the Volume  space is 50TB, the rtable_size will be 50* 1000 * 1000 / 8=6250000,it cost too much memory and cpu usage( see the code in build_vol_hash_table listed below), maybe we need to optimize this build_vol_hash_table function.** 

 ```
 rtable_pair *rtable = (rtable_pair *)ats_malloc(sizeof(rtable_pair) * rtable_size);
  int rindex = 0;
  for (int i = 0; i < num_vols; i++)
    for (int j = 0; j < (int)rtable_entries[i]; j++) {
      rtable[rindex].rval = next_rand(&rnd[i]);
      rtable[rindex].idx = i;
      rindex++;
    }

```

**Comment by bryancall** [comment]
The size of the cache index should be vol space / average object size * 10 bytes.

What is your average object size set to (proxy.config.cache.min_average_object_size)?

**Comment by bryancall** [comment]
If this is still an issue please reopen.
