### ISSUE TITLE
Upgrade AWS S3 Origin Request Signing Plugin 

### ISSUE THREAD

**Issue by ryandurfey** [apache/trafficserver#1605]
Upgrade AWS S3 Origin Request Signing Plugin
1. Upgrade to AWS S3 v4
2. Add in query string support

Current Plugin Documentation
https://docs.trafficserver.apache.org/en/6.2.x/admin-guide/plugins/s3_auth.en.html?highlight=amazon

Amazon S3 Signing Current Documentation
http://docs.aws.amazon.com/general/latest/gr/sigv4_changes.html 

Reference:  https://issues.apache.org/jira/browse/TS-4176?jql=project%20%3D%20TS%20AND%20text%20~%20s3

Code Examples
http://docs.aws.amazon.com/general/latest/gr/signature-v4-examples.html

**Comment by ryandurfey** [comment]
Solution should also work to access google cloud origin.
https://github.com/saltstack/salt/issues/31522

**Comment by mlibbey** [comment]
Shall we close this as fixed?

**Comment by ryandurfey** [comment]
Yes, please.  Thank you!
