### ISSUE TITLE
Some headers are not sent on 408 timeout responses

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#1607]
Date, Via and Server header are not sent on 408 timeout response. Currently, only Connection header is sent.

`HttpTransact::build_error_response()` stores the headers into `t_state.hdr_info.client_response.m_http` but they are not used.
https://github.com/apache/trafficserver/blob/7.0.0/proxy/http/HttpSM.cc#L3497

Note that Connection header should always be present on 408.
https://tools.ietf.org/html/rfc7231#section-6.5.7

**Comment by scw00** [comment]
mark !
