### ISSUE TITLE
Delete proxy/AbstractBuffer.{cc,h}

### ISSUE THREAD

**Issue by danobi** [apache/trafficserver#1622]
These files are never used, despite the fact that other comments seem to indicate otherwise.

Just another day in the logging subsystem, I guess.

**Comment by zwoop** [comment]
Dupe of #1623. Please don't file a PR and Issue at the same time. You only need an issue if you don't have code.

**Comment by danobi** [comment]
Sorry. I made this issue to put off the task but I never ended up putting it off.
