### ISSUE TITLE
enable proxy.config.http.negative_revalidating_enabled by default

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#1626]
I think we should enable [proxy.config.http.negative_revalidating_enabled](https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-http-negative-revalidating-enabled) by default in ATS 8. This config allows ATS to serve stale when it cannot reach the origin. With the current settings the client receives 502s.  The config is overridable.

**Comment by SolidWallOfCode** [comment]
The documentation is not completely clear. If this is enabled, then on *subsequent* requests to the failed object, ATS will revalidate the negatively cached item against the origin? And in that case, if the revalidation fails, it will serve stale content? Although that seems wrong because the cached object would be the negative reply.

**Comment by mlibbey** [comment]
How about if I add:
That is, when enabled, |TS| will serve stale when it can not reach the origin server (similar to the stale-if-error Cache-Control directive).

**Comment by SolidWallOfCode** [comment]
What about this -

.. ts:cv:: CONFIG proxy.config.http.negative_revalidating_enabled INT 0
   :reloadable:
   :overridable:

   Negative revalidating allows |TS| to return stale content if revalidation to the origin fails due
   to network or HTTP errors. If it is enabled, than caching the negative response, the current
   (possibly stale) content is preserved and served. Note this is considered only on a revalidation
   of already cached content and failure means unable to communicate via HTTP to the origin. If the
   origin provides a valid response that is not considered a failure in this context.

   A value of ``0`` disables serving stale content and a value of ``1`` enables keeping and serving stale content if revalidation fails.

.. ts:cv:: CONFIG proxy.config.http.negative_revalidating_lifetime INT 1800

   How long, in seconds, to consider a stale cached document valid if If
   :ts:cv:`proxy.config.http.negative_revalidating_enabled` is enabled and |TS| receives a negative
   (``5xx`` only) response from the origin server during revalidation.

**Comment by mlibbey** [comment]
Don't get this sentence:

> If it is enabled, than caching the negative response, the current (possibly stale) content is preserved and served.

I think this should only be in play for stale content -- wouldn't be revalidating fresh content, right? Perhaps
 If it is enabled, rather than caching the negative response, the current stale content is preserved and served.

> If the origin provides a valid response that is not considered a failure in this context.

Perhaps missing a comma after response?
Would a 5xx error be considered a valid response? We use cache hierarchies extensively, and this setting kicks in when our parents return a 5xx error to the children. Perhaps 'a valid response specific to the object'?

proxy.config.http.negative_revalidating_lifetime
appears to be both reloadable and overridable.

**Comment by SolidWallOfCode** [comment]
1) "If enabled, *rather* than caching the negative response on a revalidate, the ..."

2) Hmmm. I need to look at the code.

**Comment by SolidWallOfCode** [comment]
Docs updated, ship this in ATS 8.

**Comment by mlibbey** [comment]
Still think proxy.config.http.negative_revalidating_enabled  needs to be enabled by default in 8.

**Comment by mlibbey** [comment]
Looks like this is done.
