### ISSUE TITLE
plugin mp4 

### ISSUE THREAD

**Issue by GarfieldLinux** [apache/trafficserver#1666]
Hi  all:
    mp4 file seek with  module "mp4"   , mplayer  vlc  chrome  can play video  but safari can not play the stream like "http:://XXX/test.mp4?start=20".
   so  anybody test this case?  or that's a bug for mp4 plugin ? 

    thanks  all   .

**Comment by scw00** [comment]
Safari will send IMS request  while playing this video, and ats will response 304 without Content-Type header. So May be we need to fix that !

**Comment by GarfieldLinux** [comment]
Hi all  ：
    Nothing need to do  .  I figure out that    safari seek with range request  via the mp4 meta header . 
    Thanks all .
