### ISSUE TITLE
Access logs aren't flusing on traffic_server death

### ISSUE THREAD

**Issue by danobi** [apache/trafficserver#1670]
If there are logs in the flush buffer when we kill `traffic_server`, we lose these logs. There needs to be a way for ATS to flush these logs upon receiving a signal.

The obvious way would be to call `Log::flush_thread_main(..)` in `Main::proxy_signal_handler(..)`, but I highly doubt that function is signal safe.

**Comment by mingzym** [comment]
well, I don't know it is still the old style, but TS have a shutdown command(way) to stop the server safely, while most init scripts just kill, you should prefer the shutdown if it still works, because you care it. flush on kill or crash sounds cool but may bring too many code complex or trouble, IMO

**Comment by danobi** [comment]
Is the shutdown command `./trafficserver stop`? That makes sense if the script did a safe shutdown. The reason I bring this up is because @dragon512 is working on a testing framework and (I assume) only starting up the `traffic_server` binary and skipping the script. When we test for the presence of logs, if we kill too fast we get nothing in the logs.

**Comment by mingzym** [comment]
Back some version early, there is a command line traffic_line:  ```-S, --shutdown          on    false     Shutdown traffic_server (local node)``` please find out. as I am sure the scripts mostly will do a kill, and trafficserver is the sysV init script.

**Comment by mingzym** [comment]
I am not updated with the current traffic ctl commands etc, so maybe you can find it out current status on this.

**Comment by danobi** [comment]
70ef31e8ac76 removed `traffic_line`. I worked with the `traffic_ctl` code for process control earlier and I don't recall seeing any logging related code. I have a feeling this issue has always existed but just nobody noticed.

**Comment by mingzym** [comment]
great that you take care of the ctl codes. afaict, MGMT_EVENT_SHUTDOWN handling is still in the codes, maybe you can find a way to use it?

**Comment by maskit** [comment]
#1937 may provide a chance for flushing logs.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
