### ISSUE TITLE
Undocumented LogFilter feature

### ISSUE THREAD

**Issue by danobi** [apache/trafficserver#1671]
LogFilter supports comma separated values for `accept` and `reject` (and possibly `wipe`) values. However, this feature is not documented. Since this feature isn't stated, it's easy to assume that you'd want to attach multiple `filter.accept(..)`s onto a log object to achieve the same effect. However, attaching multiple accept filters does the opposite of what you'd think.

If, for example, we had 2 accept log filters, each disjoint from the other, nothing will ever get logged on the given log object.

Here is an example of the undocumented feature in action: https://github.com/apache/trafficserver/blob/master/proxy/config/logging.config.default#L115

**Comment by mlibbey** [comment]
Want to suggest an update to 
https://docs.trafficserver.apache.org/en/latest/admin-guide/files/logging.config.en.html#admin-custom-logs-filters ?

**Comment by danobi** [comment]
Yes, after I get a chance to test out the csv feature. Just wanted to make sure this find isn't lost to oblivion if I forget.

**Comment by bryancall** [comment]
Looks like this has been documented
