### ISSUE TITLE
config reload after touching the records.config triggers reload of remap.config and ssl_multicert.config

### ISSUE THREAD

**Issue by vmamidi** [apache/trafficserver#1672]
traffic_ctl config reload after touching records.config  causes remap.config and ssl_multicert.config to reload multiple times.

Apr 13 17:43:28  traffic_server[44740]: {0x2aaab750c700} NOTE: loading SSL certificate configuration from /opt/bazinga/etc/trafficserver/ssl_multicert.config
Apr 13 17:45:05  traffic_server[44740]: {0x2aaaedf00700} NOTE: remap.config done reloading!
Apr 13 17:46:00  traffic_server[44740]: {0x2aaab710c700} NOTE: loading SSL certificate configuration from /opt/bazinga/etc/trafficserver/ssl_multicert.config
Apr 13 17:46:43  traffic_server[44740]: {0x2aaaedf00700} NOTE: remap.config done reloading!
Apr 13 17:48:20  traffic_server[44740]: {0x2aaaee001700} NOTE: remap.config done reloading!
Apr 13 17:48:27  traffic_server[44740]: {0x2aaab730c700} NOTE: loading SSL certificate configuration from /opt/bazinga/etc/trafficserver/ssl_multicert.config

**Comment by mlibbey** [comment]
We think that each of these records.config cause ssl_multicert to load an additional time:
proxy.config.ssl.server.cert.path
proxy.config.ssl.server.cert_chain.filename
proxy.config.ssl.server.multicert.filename
proxy.config.ssl.server.private_key.path
proxy.config.ssl.server.session_ticket.enable
proxy.config.ssl.server.ticket_key.filename

iocore/net/SSLConfig.cc:  sslCertUpdate->attach("proxy.config.ssl.server.multicert.filename");
iocore/net/SSLConfig.cc:  sslCertUpdate->attach("proxy.config.ssl.server.ticket_key.filename");
iocore/net/SSLConfig.cc:  sslCertUpdate->attach("proxy.config.ssl.server.cert.path");
iocore/net/SSLConfig.cc:  sslCertUpdate->attach("proxy.config.ssl.server.private_key.path");
iocore/net/SSLConfig.cc:  sslCertUpdate->attach("proxy.config.ssl.server.cert_chain.filename");
iocore/net/SSLConfig.cc:  sslCertUpdate->attach("proxy.config.ssl.server.session_ticket.enable");

The triggering mechanism doesn't track if these records have changed, and always schedule an update, regardless if one is needed.

**Comment by mlibbey** [comment]
Similarly, diags is also loaded many times with a record.config variable changed:

```
Apr 20 22:55:57 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3e5fe700} NOTE: User has changed config file remap.config
Apr 20 22:55:57 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3e5fe700} NOTE: User has changed config file records.config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:55:59 s_sys@myats.example.com traffic_manager[44567]: {0x7f3e3f9f0700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
Apr 20 22:56:03 s_sys@myats.example.com traffic_server[47671]: {0x2aaab4f0c700} NOTE: updated diags config
```

**Comment by bryancall** [comment]
If this is still an issue please reopen.
