### ISSUE TITLE
cqtq logs transaction end time, not start time.

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#1685]
ATS has several log fields that claim to log the client request time:
cqtd	Client Request	Client request timestamp. Specifies the date of the client request in the format YYYY-MM-DD (four digit year, two digit month, two digit day - with leading zeroes as necessary for the latter two).
cqtn	Client Request	Client request timestamp in the Netscape timestamp format.
cqtq	Client Request	The time at which the client request was received expressed as fractional (floating point) seconds since midnight January 1, 1970 UTC (epoch), with millisecond resolution.

However, these log the time that the client request ends, not the beginning of the request. In our logs, the cqtq time are 'now', despite ttms (download time) being several minutes, and always decreasing. If cqtq were the client request time, then the logs would not be ordered -- newly logged requests could have started many minutes ago, intermixed with quick requests that only take milliseconds.

We see this in ATS 5.3.1, 6.1, and 7.0.

**Comment by maskit** [comment]
This relates #1733

**Comment by masaori335** [comment]
Fixed by #1980
