### ISSUE TITLE
Ability to shed traffic with HTTP/2

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#1693]
Migrate a ticket from JIRA. Details in [TS-3864](https://issues.apache.org/jira/browse/TS-3864).

**Comment by masaori335** [comment]
From #1673, it looks like @zizhong has some ideas:)

**Comment by mlibbey** [comment]
This would also be a great feature addition to the header rewrite plugin -- eg, allowing it to send a GO AWAY frame as an action.

**Comment by maskit** [comment]
The feature is implemented, and "Connection: close" in response header triggers a GOAWAY frame. It'll be available on 8.0.
