### ISSUE TITLE
Add option to count range requests in cache_promote plugin

### ISSUE THREAD

**Issue by mustafa1024m** [apache/trafficserver#1694]
I have a VOD CDN, most requests are byte range requests, adding the option to count these requests in the cache_promote plugin will greatly improve the caching for these use cases.

**Comment by zwoop** [comment]
Are you able / planning on contributing this code? It probably isn't terribly complicated, you would basically want to include the Range: header value into the hash key. But, it could mean that you need to bump up the LRU size :).

**Comment by mustafa1024m** [comment]
I actually meant to cache the whole object, not specific byte ranges, after a number of range requests, and I don't think I can contribute code (at least not now).

**Comment by bryancall** [comment]
If this is still an issue please reopen.

**Comment by mustafa1024m** [comment]
I'm not sure if anything has changed about this, let's assume there are multiple requests to a 10MB object:
Range: 0 - 100,000
Range: 100,000 - 200,000
Range: 100,000 - 200,000
Range: 100,000 - 200,000
Range: 100,000 - 200,000

**Comment by mustafa1024m** [comment]
I don't think anything has changed about this, the idea is that, e.g. I have a 100MB object, and got a 1000 range requests, each one specifying a random 4 MB chunk, the current behavior doesn't take range request into account for caching, so it doesn't get promoted, I want to set a number of range requests after which the whole object gets cached.

**Comment by mustafa1024m** [comment]
> If this is still an issue please reopen.

Can you reopen this please, this behaviour has not changed so it is still causing problems to VOD usecase, thousands of range requests but no whole object requests.
