### ISSUE TITLE
SM_ACTION_CACHE_LOOKUP takes a really long time

### ISSUE THREAD

**Issue by serDrem** [apache/trafficserver#1718]
While debugging an edge cache communicating to a mid cache with possible network error present, I came across an interesting case where a SM_ACTION_CACHE_LOOKUP takes 10 seconds to result in CACHE_EVENT_OPEN_READ_FAILED, instead of immediately. The particular state id is 87384503.  the request from the client comes in at 

409651	21:31:26.561912	<client>	<edge>	HTTP	222	GET /NHLCI_HD_NAT_27106_0_5439705077043833163/root_audio106/8452479769.ts HTTP/1.1 

10 seconds later, the edge cache is asking the mid for the file, instead of right away.

13954	21:31:35.875754	<edge>	<mid>	HTTP	454	GET <origin hostname>/NHLCI_HD_NAT_27106_0_5439705077043833163/root_audio106/8452479769.ts HTTP/1.1 

I don't understand why it does not happen right away as per usual, as no networking is involved in looking up the file in the local cache.

Pcap and slow logs available upon request.

**Comment by bryancall** [comment]
@serDrem Can you post the slow log information into the bug?  Do you have any plugins that are running on this transaction?

**Comment by bryancall** [comment]
If this is still an issue please reopen.
