### ISSUE TITLE
Client request timestamps are not correct

### ISSUE THREAD

**Issue by danobi** [apache/trafficserver#1733]
`cqtd`, `cqtn`, `cqtq`, `cqts`, and `cqtt` all represent initial the client request timestamp in various formats. Now that's all well and good, but the problem is that these timestamps are not accurate due to a fundamental issue with the code.

What these fields should measure is when the request came into ATS. What they currently measure is when the log entry entered a LogBuffer. (See the code [here](https://github.com/apache/trafficserver/blob/master/proxy/logging/LogBuffer.cc#L742)). Even under the best conditions, these timestamps will be **guaranteed** to be greater than or equal to the time the transaction completed. Under heavy load, the logging code will probably get backed up and cause larger drifts in the timestamps. This is clearly wrong and we have milestones (`TS_MILESTONE_UA_BEGIN`) for the real values.

**Comment by danobi** [comment]
This begs the question: is the documentation wrong or is the code wrong?

But the answer is simple (imo): if the documentation was wrong, then the timestamp is completely meaningless. At best, it would just record how backed up the logging system is.

My proposal is to use the `TS_MILESTONE_UA_BEGIN` milestone instead of the buffer timestamp.

**Comment by masaori335** [comment]
Close as duplicated. Please see #1980 :)
