### ISSUE TITLE
Would like a way to create an outgoing TLS VConn

### ISSUE THREAD

**Issue by unixwitch** [apache/trafficserver#1736]
I'd like an API function that looks like this:

```
tsapi TSAction TSSslNetConnect(TSCont, const struct sockaddr *, TSSslContext *);
```

This would initiate an outgoing connection and negotiate TLS with the remote server, then return a TLS VConn that I can use for I/O.

**Comment by bryancall** [comment]
The recommendation from the ATS Community is to use the OpenSSL API directly.
