### ISSUE TITLE
About clustering ATS

### ISSUE THREAD

**Issue by anhldbk** [apache/trafficserver#1899]
Hi guys,

I'm sorry if this is NOT a proper way to ask questions. There's not much discussions on `Stackoverflow` regarding ATS. 

My question is: There's no section in [ATS documentation](https://docs.trafficserver.apache.org/en/latest/#) for configuring clusters in the latest version (8.0). The older ones have. Would you please tell me why?

**Comment by anhldbk** [comment]
Btw, still I have an unanswered question about [handling large files](http://stackoverflow.com/questions/43896938/how-ats-handles-large-files)

**Comment by mlibbey** [comment]
Clustering has been removed for ATS 8. Most users are:
- using some external deployment system to get configuration to their nodes (chef/puppet/salt/Traffic Control...)
- using some sort of cache hierarchy to have a larger cache footprint (eg, child accepts request, and proxies to a parent using parent.config (probably using 'consistent_hash') for cache misses.

**Comment by anhldbk** [comment]
@mlibbey Thank you so much!

**Comment by anhldbk** [comment]
@mlibbey ATS does NOT support clustering out of the box. To support clustering, we need a of load balancer (for example: say NGINX) standing right in front of ATS instances. But each cached object is stored only once in an instance, right? And then if there's any trouble with the instance, we have to fetch it again from origin servers. Why ATS does NOT support object replications (and so, distributed caching).

> PS: I'm trying to understand how ATS works under the hood. Please correct me if I'm wrong.

**Comment by mlibbey** [comment]
Some users use anycast to their local router to create a ECMP clusters to avoid load balancers.

There are a ton of failed cache replication standards. ICP, ICPv2, CARP, WCCP, HTCP, ICAP... Seems like the ATS users are more and more using cache hierarchies (parent.config) to handle hot objects while minimizing the fetches from origin.

**Comment by anhldbk** [comment]
@mlibbey Hura! You make my day. Thank you!

**Comment by anhldbk** [comment]
@mlibbey Hey, if documentations about clustering is removed, do you think that we should remove code for [Raft consensus protocol](https://github.com/apache/trafficserver/blob/master/lib/raft/raft.h) ?
