### ISSUE TITLE
Create a plugin API to indicate that the SSL connection should shutdown

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#1922]
Suggested by @reveller .  If in the handshake callback, we decide that the handshake cannot succeed, the plugin should have a means to "cleanly" fail the handshake.  Something like TSSSLConnError(error code).  This API will cause ATS to send an appropriate SSL alert and shutdown the connection.

**Comment by shinrich** [comment]
We have the start of a solution with TSVConnReenableEx (PR #4427).  This allows the callback to send an error event on reenabled.  Currently only stops processing when received during the server verify processing (I think).  Needs to be checked for the other SSL hook points specifically the certificate selection.

**Comment by bryancall** [comment]
If this is still an issue please reopen.  Do you still want to do work on this?
