### ISSUE TITLE
OverridableHttpConfigParams should be separated by subsystem

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#1925]
This came up in the Miami Summit.  The overridable settings are housed in the OverridableHttpConfigParams structured defined in the Http area.  Some of the overridable settings are used in other subsystems, e.g. TLS or caching.  The way the current data structure is defined this results in some unfortunately dependency loops.  

We should restructure OverridableHttpConfigParams to contain substructures defined by the relevant subsystems (e.g., OverridableTLSConfigParams).  Then only the substructure would be passed to the system system and the subsystem would not have to know about the HTTP system

**Comment by bryancall** [comment]
This will be fixed when we move to YAML
