### ISSUE TITLE
Run clang-tidy before branching 9.0.0

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#1926]
Now that we have committed to c++11, we can clean up our constructors by moving from per constructor member initializers to class defaults in many cases.

**Comment by morrme** [comment]
I am new to this codebase, is there support available to help me get started?

**Comment by shinrich** [comment]
morrme sorry for not getting back sooner.  Pinging folks on the IRC is probably the best way to get timely support.

For this particular issue, pull the master branch.  Some folks have already been tidying up the initializers.  For example Steven Feltner has updated HttpSM member initializers in commit 6c2081e4.  Actually it looks like many of the classes in the proxy/http area have been updated.

**Comment by webdriverrr** [comment]
@shinrich This is confusing a little bit - so are you talking about default _member initializer list_ feature or _default arguments_ ?

**Comment by shinrich** [comment]
Here is the reference http://en.cppreference.com/w/cpp/language/initializer_list

I think this is officially called the class default initialization.

**Comment by benvenutti** [comment]
Is there anyone doing this? I ask because I have sometime next week and I could help with this = )

**Comment by scw00** [comment]
just do it ! :)

**Comment by bryancall** [comment]
There is an option for clang tidy to do this automatically for us.  I will run it and see what happens.

**Comment by alokrahul513** [comment]
Hi, I want to work on this issue. How to get started?
