### ISSUE TITLE
Race condition in SSL hooks with new TS_SSL_SERVERNAME_HOOK in 7.1.x branch

### ISSUE THREAD

**Issue by calavera** [apache/trafficserver#1944]
I have a plugin that used to use TS_SSL_CERT_HOOK to lazy load certificates. The plugin uses AsyncHttpRequest to request the certificates to an external API. This used to work in 7.0.x, but it looks like 7.1.x has a race condition using the new hook.

I can see responses from my certificates api arriving to ATS as they used to be, but the OpenSSL raises an error because the connection is closed:

```
SSL_ERROR_ZERO_RETURN
The TLS/SSL connection has been closed. If the protocol version is SSL 3.0 or higher, this result code is returned only if a closure alert has occurred in the protocol, i.e. if the connection has been closed cleanly. Note that in this case SSL_ERROR_ZERO_RETURN does not necessarily indicate that the underlying transport has been closed.
```

This is part of the log in my server: https://pastebin.com/uPJStx5a

The plugin sets the ssl context properly and re-enables the continuation, but the SSL connection is closed when ATS tries to send the certificate to the client.

**Comment by calavera** [comment]
This doesn't always happen, that's why I think it's a race condition. I get the right certificate response after our plugin has cached the certificate in an internal LRU cache.

**Comment by calavera** [comment]
Btw, I'm using OpenSSL 1.0.2k, if that helps.

**Comment by shinrich** [comment]
I assume that the certificate is not immediately returned from AsyncHttpRequest, and in that case you don't reenable in the plugin, but you setcontext and reenable in the callback.  Is that correct?  

It could be that I messed up one of the paths back from the plugin in the don't reenable case.  I'll try to set up some test cases there to track the problem and catch future regressions.

**Comment by calavera** [comment]
> I assume that the certificate is not immediately returned from AsyncHttpRequest, and in that case you don't reenable in the plugin, but you setcontext and reenable in the callback. Is that correct?

yes, that's correct. We reenable in the handleAsyncComplete callback.

**Comment by calavera** [comment]
I wrote a plugin to try to reproduce this behavior: https://github.com/lost-mountain/ts-sni-loader

**Comment by calavera** [comment]
After much debugging, I think the new behavior with SERVERNAME is correct. But there is another change that is not working as 7.0 used to work. I'll open a different issue.
