### ISSUE TITLE
Truncated objects in the cache

### ISSUE THREAD

**Issue by taoyunxing** [apache/trafficserver#1960]
We also found the same warings in the diags.log of production host，both on edge and parent nodes. The ATS version vary from 4.2.3, 5.3.2 to 6.x, we deem this is a serious bug which dramatically decrease our quality of service.

Who can help us? Welcome some suggestion,  thanks in advance !

[May 22 10:45:54.656] Server {0x2ba58c706700} WARNING: <CacheRead.cc:781 (openReadMain)> Document E23CB52F truncated at 3669512 of 4194304, missing fragment C8B70BFF

Also see similar issues in JIRA
https://issues.apache.org/jira/browse/TS-4221

**Comment by bryancall** [comment]
@zwoop 
Are you seeing this issue on ATS 7.0.0?

**Comment by zwoop** [comment]
Not seeing it on any of the boxes I took a quick glance at.

**Comment by taoyunxing** [comment]
more and more warnings occur in diags.log of ATS 5.3.2:

[May 23 22:31:28.932] Server {0x2b753630cac0} WARNING: Document 59CE69E8622215DFB11EAAB431E46E24 truncated
[May 23 22:31:30.662] Server {0x2b753d110700} WARNING: Middle: Doc magic does not match for AC3DCFC471C845A8A76EB44275FBDAB5
[May 23 22:31:30.662] Server {0x2b753d110700} WARNING: Document B455E70ADFF174002E7C6DE0397E334F truncated
[May 23 22:31:32.192] Server {0x2b753630cac0} WARNING: Earliest : Doc magic does not match for 1254208E5EF16F864311731B62229CDC
[May 23 22:31:32.668] Server {0x2b753ea29700} WARNING: Middle: Doc magic does not match for 516DDF0FEA7D4A5A3D423B2969377339
[May 23 22:31:32.668] Server {0x2b753ea29700} WARNING: Document 466FC9360FBB0655B5D79D28CF4BD789 truncated
[May 23 22:31:39.160] Server {0x2b753d211700} WARNING: Middle: Doc magic does not match for C9A99A287EF771E0B7FBF22842A2FBBF
[May 23 22:31:40.511] Server {0x2b753d211700} WARNING: Middle: Doc magic does not match for D7EDC1387622A099B276968F17B58DFC
[May 23 22:31:48.207] Server {0x2b753cf0e700} WARNING: Earliest : Doc magic does not match for E61C0097DA1C860A67F15063CB3C824B
[May 23 22:31:50.720] Server {0x2b753de1d700} WARNING: Earliest : Doc magic does not match for 47604F69448C1BA77F36D90AA2AB23EB
[May 23 22:32:01.367] Server {0x2b753e120700} WARNING: Middle: Doc magic does not match for F57307E1815FE57AD911690DFE581694
[May 23 22:32:01.367] Server {0x2b753e120700} WARNING: Document 26A4277C2E965E9976839370DE71E9A3 truncated
[May 23 22:32:08.404] Server {0x2b753dc1b700} WARNING: Head : Doc magic does not match for B72D32D3C60CEED04D197ED41D4BD01B
[May 23 22:32:08.420] Server {0x2b753dc1b700} WARNING: Middle: Doc magic does not match for 4C837C271A3D10667BE02E25F9FC1F2C
[May 23 22:32:08.420] Server {0x2b753dc1b700} WARNING: Document CE8A649E6D0C5C4323ED3638544193C0 truncated

**Comment by zwoop** [comment]
Looks like we're still seeing this in prod. :-/

**Comment by taoyunxing** [comment]
@zwoop : why remove the Bug label? Is this not a bug?

**Comment by zhxiaom5** [comment]
did this cause same header but wrong content md5？

**Comment by scw00** [comment]
This issue has been fixed with #2699 and #2871 .
