### ISSUE TITLE
Ticket key file should be read on every config reload

### ISSUE THREAD

**Issue by persiaAziz** [apache/trafficserver#1962]
Ticket key is now set in records.config via CONFIG proxy.config.ssl.server.ticket_key.filename. Now to reload a new ticket key, the filename also has to change in the records.config, which is a painful thing to do. So the ticket key needs to be reloaded every time `config reload` is called no matter the content of the file changed or not.

**Comment by jpeach** [comment]
This should work the same as all the other config files.

**Comment by persiaAziz** [comment]
PR : https://github.com/apache/trafficserver/pull/1970

**Comment by mlibbey** [comment]
with #1970 merged, close this?

**Comment by persiaAziz** [comment]
yes.. I am closing this one :)
