### ISSUE TITLE
Add to RAM Cache on every request

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#1966]
This came up in the spring 2017 ATS summit.  With the LRU strategy, objects are only put on RAM cache on second request.  There is no reason not to put objects into the RAM cache on first request.

**Comment by jpeach** [comment]
As a tunable?

**Comment by shinrich** [comment]
You mean as a setting to adjust the behavior?  I am just transcribing my notes.  As I recall @zwoop and @solidwallofcode were discussing this.

**Comment by jpeach** [comment]
Yeh it seems useful to make it a tunable, but to change the default I would like a lot more information, including benchmarks.

**Comment by zwoop** [comment]
The discussion was actually around the "fast-fill" feature of the CLFUS. Basically, we should allow things to get promoted to the LRU RAM cache immediately, until it gets filled. Then we can go back to normal behavior (which I think has many benefits).

**Comment by scw00** [comment]
This issue will pollute ram cache, if client failed.

**Comment by bryancall** [comment]
Yes, it is a good idea to fast fill on LRU.

**Comment by alokrahul513** [comment]
Hi, I want to work on this issue. How to get started?

**Comment by bryancall** [comment]
@alokrahul513 We had a discussion and took off the "good first issue".  This would be more complex.

**Comment by bryancall** [comment]
Closing for now if anyone is interested in it please reopen.
