### ISSUE TITLE
Support proxy protocol

### ISSUE THREAD

**Issue by unixwitch** [apache/trafficserver#1985]
Proxy protocol is a way for a load balancer to indicate the original client address of the connection.   It serves a similar function to the `X-Forwarded-For` header, but it's protocol-agnostic, e.g. it works with tunneled TLS requests and any other non-HTTP TCP connection.   Proxy protocol is gaining wide adoption in "cloud" environments, so it would be nice to see support for it in TS.

The protocol is documented [here](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt); essentially, some data is sent at the start of the TCP connection containing the client address.

There are two separate parts to feature:

* TS should optionally accept proxy protocol in incoming requests, and store the client address somewhere.
* TS should optionally send a proxy protocol header in origin connections.  This header would contain the stored client address if the client sent its own proxy protocol header, or else the client socket address.

This should be configurable:

* On TCP listeners to accept incoming proxy protocol (e.g. using a port definition like `80:proxy 8443:ssl,proxy`).
* On origin connections, possibly by a default records.config option that can be changed in a remap.
* On origin connections in a plugin, using `TSHttpTxnConfigIntSet(txnp, TS_CONFIG_PROXY_PROTOCOL, 1)`.
* There should be a way for plugins to change the stored client address, e.g. with `TSHttpTxnSetProxyAddress(txnp, sockaddr)`.

**Comment by unixwitch** [comment]
Previous JIRA issue for this: https://issues.apache.org/jira/browse/TS-4398

**Comment by realpdm** [comment]
Chiming in, this would be pretty handy to have. There are times when we have some abstraction layer that doesn't talk HTTP and we need to pass along the client IP in some way.

**Comment by klk-** [comment]
I would be willing to take a stab at implementing this, if I could get some guidance on the direction to take.

After my first look at the code, my impression is to follow the pattern of the handoff to SocksProxy in UnixNetProcessor.  If we are using proxy protocol, create a Continuation that will handle events until the proxy protocol header is fully parsed, and afterwards pass through all events to the original Continuation.

**Comment by SolidWallOfCode** [comment]
I will try to do a sketch of how this should be implemented.

**Comment by klk-** [comment]
@SolidWallOfCode bump

**Comment by bryancall** [comment]
Support has been added for incoming/client connections.
I am closing this for now until someone wants to add support for origin connections.
