### ISSUE TITLE
master dumping core randomly

### ISSUE THREAD

**Issue by persiaAziz** [apache/trafficserver#1999]
traffic_server: received signal 11 (Segmentation fault)
traffic_server - STACK TRACE: 
traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0xd2)[0x504b03]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f1ec2e72390]
traffic_server[0x78f7a4]
traffic_server[0x78e338]
traffic_server(_Z16RecSetRawStatSumP15RecRawStatBlockil+0x24)[0x78f00d]
traffic_server[0x703ceb]
traffic_server(_Z20register_cache_statsP15RecRawStatBlockPKc+0x33)[0x703d51]
traffic_server(_ZN14CacheProcessor15diskInitializedEv+0x41c)[0x6f8cb4]
traffic_server(_ZN9CacheDisk8openDoneEiPv+0x50)[0x711e40]
traffic_server(_ZN9CacheDisk9clearDoneEiPv+0x10c)[0x711ace]
traffic_server(_ZN12Continuation11handleEventEiPv+0x72)[0x507df4]
traffic_server(_ZN19AIOCallbackInternal11io_completeEiPv+0x3f)[0x705c39]
traffic_server(_ZN12Continuation11handleEventEiPv+0x72)[0x507df4]
traffic_server(_ZN7EThread13process_eventEP5Eventi+0x143)[0x794cc7]
traffic_server(_ZN7EThread7executeEv+0x10c)[0x794f68]
traffic_server[0x7941a9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f1ec2e686ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f1ec20f982d]

**Comment by persiaAziz** [comment]
this seems to go away with Alan's fix :)

**Comment by SolidWallOfCode** [comment]
"Seems" - thanks for the vote of confidence :-).
