### ISSUE TITLE
gzip plugin not matching on deflate

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#2117]
When using the gzip plugin as a remap plugin, I don't see it matching the deflate algorithm for use.

```
map http://example.com http://origin.example.com \
    @plugin=gzip.so @pparam=gzip.config

$ cat gzip.config
enabled true
cache true
compressible-content-type *xml
supported-algorithms deflate
```

Then, making a request:
```
$ curl -v -x 127.0.0.1:80 "http://example.com/xml" --compressed
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET http://example.com/xml HTTP/1.1
> Host: example.com
> User-Agent: curl/7.45.0
> Accept: */*
> Accept-Encoding: deflate, gzip
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< Server: ATS/7.1.0
< Date: Mon, 12 Jun 2017 19:22:45 GMT
< Content-Type: application/xml
< Content-Length: 522
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Accept-Ranges: bytes
< Age: 0
< Proxy-Connection: keep-alive
```

and in traffic.out with debugging turned on for gzip*
```
[Jun 12 19:22:45.786] Server {0x2aaab730c700} DIAG: (gzip) INFO: no acceptable encoding match found in request header, not compressible
```

The same will happen if the request has  ```-H "Accept-Encoding: deflate"```

In contrast, if the config has ```supported-algorithms gzip``` the response has the expected ```Content-Encoding: gzip``` header

**Comment by shukitchan** [comment]
There is a normalization process going on here by default in ATS 
https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-http-normalize-ae-gzip

**Comment by shukitchan** [comment]
I think @bryancall also refers to that in #2100

**Comment by mlibbey** [comment]
oh -- so enabling proxy-config-http-normalize-ae-gzip will prevent brotli from being used, as it will remove any Accept-Encoding from the request that does not have gzip, and change the AE to just have gzip if it is enabled.

Changed proxy-config-http-normalize-ae-gzip to 0, and my test above works.
