### ISSUE TITLE
periodic server restarts in [LocalManager::pollMgmtProcessServer]

### ISSUE THREAD

**Issue by zajakala** [apache/trafficserver#2141]
ATS: 6.2.0
OS: CentOS 7 Linux x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 3.10.0-327.36.1.el7.x86_64
---
ATS as reverse proxy, remap to 5 origin servers, only static content, RAM-disk based cache, traffic (out) at  1-5Gbps.

A couple times every day (!) server is restarted with the following logs in manager.log
```
[Jun 15 04:43:33.613] Manager {0x7f5154d3d880} FATAL: [LocalManager::pollMgmtProcessServer] Error in read (errno: 104)
[Jun 15 04:43:33.613] Manager {0x7f5154d3d880} NOTE: [LocalManager::mgmtShutdown] Executing shutdown request.
[Jun 15 04:43:33.613] Manager {0x7f5154d3d880} NOTE: [LocalManager::processShutdown] Executing process shutdown request.
[Jun 15 04:43:33.613] Manager {0x7f5154d3d880} ERROR: [LocalManager::sendMgmtMsgToProcesses] Error writing message
[Jun 15 04:43:33.613] Manager {0x7f5154d3d880} ERROR: <MgmtUtils.cc:289 (mgmt_elog)>  (last system error 32: Broken pipe)
[Jun 15 04:43:33.635] {0x7f84ba80d880} STATUS: opened /opt/trafficserver/var/logs/manager.log
[Jun 15 04:43:33.635] {0x7f84ba80d880} NOTE: <DiagsConfig.cc:141 (reconfigure_diags)> updated diags config
[Jun 15 04:43:33.637] Manager {0x7f84ba80d880} NOTE: [ClusterCom::ClusterCom] Node running on OS: 'Linux' Release: '3.10.0-327.36.1.el7.x86_64'
[Jun 15 04:43:33.638] Manager {0x7f84ba80d880} NOTE: [LocalManager::listenForProxy] Listening on port: 80 (IPv4)
[Jun 15 04:43:33.638] Manager {0x7f84ba80d880} NOTE: [TrafficManager] Setup complete
[Jun 15 04:43:34.652] Manager {0x7f84ba80d880} NOTE: [LocalManager::startProxy] Launching ts process
[Jun 15 04:43:34.677] Manager {0x7f84ba80d880} NOTE: [LocalManager::pollMgmtProcessServer] New process connecting fd '16'
[Jun 15 04:43:34.677] Manager {0x7f84ba80d880} NOTE: [Alarms::signalAlarm] Server Process born
```

In /var/log/messages
```
Jun 15 04:43:33 ucs6 traffic_manager[9842]: {0x7f5154d3d880} FATAL: [LocalManager::pollMgmtProcessServer] Error in read (errno: 104)
Jun 15 04:43:33 ucs6 traffic_manager[9842]: {0x7f5154d3d880} ERROR: [LocalManager::sendMgmtMsgToProcesses] Error writing message
Jun 15 04:43:33 ucs6 traffic_manager[9842]: {0x7f5154d3d880} ERROR: <MgmtUtils.cc:289 (mgmt_elog)>  (last system error 32: Broken pipe)
Jun 15 04:43:33 ucs6 traffic_cop[6261]: cop received child status signal [9842 256]
Jun 15 04:43:33 ucs6 traffic_cop[6261]: traffic_manager not running, making sure traffic_server is dead
Jun 15 04:43:33 ucs6 traffic_cop[6261]: spawning traffic_manager
Jun 15 04:43:33 ucs6 traffic_manager[7727]: NOTE: --- Manager Starting ---
Jun 15 04:43:33 ucs6 traffic_manager[7727]: NOTE: Manager Version: Apache Traffic Server - traffic_manager - 6.2.0 - (build # 082717 on Aug 27 2016 at 17:41:04)
Jun 15 04:43:33 ucs6 traffic_manager[7727]: NOTE: RLIMIT_NOFILE(7):cur(256000),max(256000)
Jun 15 04:43:38 ucs6 traffic_server[8872]: NOTE: --- traffic_server Starting ---
Jun 15 04:43:38 ucs6 traffic_server[8872]: NOTE: traffic_server Version: Apache Traffic Server - traffic_server - 6.2.0 - (build # 082717 on Aug 27 2016 at 17:40:43)
```
This seems to have started occuring when traffic grew. Does not happen on our other instance of ATS 6.2.0 serving much lower trarfic.

Please advise what logs could be turned on to help diagnose the problem. 

Please note - this is PROD setup, recompiling with debugs, core dumps and longer downtimes are not an option. We could set up a test instance and try to reproduce.

output of traffic_crashlog attached

[crash-2017-06-15-122916.zip](https://github.com/apache/trafficserver/files/1077346/crash-2017-06-15-122916.zip)

**Comment by bryancall** [comment]
Does this happen when you are restarting the server?  It look like the server is coming up and then traffic_cop can't speak to traffic_manager.  I did some searching and found that when someone moved from 6.2.0 to 7.0.0 it resolved this issue.  (http://apache-traffic-server.24303.n7.nabble.com/Problem-starting-traffic-server-td2760.html)

Also, you might want to try to increasing `proxy.config.cop.init_sleep_time` (https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-cop-init-sleep-time).

**Comment by zajakala** [comment]
No, this happens after server has been in operation for hours. First line indicating the problem is 
```FATAL: [LocalManager::pollMgmtProcessServer] Error in read (errno: 104)```
after that server is restarted and then it goes back to working again for some time.

**Comment by zajakala** [comment]
Any suggestion on what we can do to debug that?

**Comment by hahayaoniming** [comment]
@zajakala  The same problem occurred on my test server(5.3.x)，How did you deal with it?

**Comment by bryancall** [comment]
If this is still an issue in 7 or 8 please reopen.
