### ISSUE TITLE
many strange ERR_CLIENT_ABORTand cache behavior

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#2189]
hi,all

when enable read_while_writer, 
i found many ERR_CLIENT_ABORT log records indicated 'ttms' all around 900000,
and this is the timeout_in i set for transaction activity...

`CONFIG proxy.config.cache.enable_read_while_writer INT 1
CONFIG proxy.config.http.transaction_active_timeout_in INT 900`

------------------------------
following are the log samples

`1498091553.134 900278 124.135.108.186 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091553.148 900235 114.217.181.44 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091553.286 900089 42.232.247.107 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091553.527 900254 112.248.66.153 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091553.978 900840 112.239.66.236 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091554.133 900684 112.248.185.147 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091554.808 900425 115.51.237.29 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091555.162 900327 119.185.240.112 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091556.184 900329 60.24.95.104 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091556.290 900926 115.60.83.249 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091556.316 900085 27.215.180.100 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091556.477 900281 218.107.55.254 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091556.610 900761 112.245.230.166 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"
1498091556.648 900648 1.25.18.1 ERR_CLIENT_ABORT/200 2999 GET http://update.xyz.abc.com/server5_2.txt - NONE/- text/plain "-"`

**Comment by bryancall** [comment]
If this is still an issue please reopen.
