### ISSUE TITLE
TS API to get Client request protocol and version

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#2206]
TS API to get Client request protocol and version is useful for some protocol and version specific plugin. 
e.g. HTTP/2 Server-Push Plugin

**Comment by shukitchan** [comment]
I used this in my plugin - TSHttpTxnClientProtocolStackGet

https://github.com/apache/trafficserver/blob/master/proxy/InkAPI.cc#L9331

That should work. right?

**Comment by shukitchan** [comment]
More info here - https://docs.trafficserver.apache.org/en/latest/developer-guide/api/functions/TSClientProtocolStack.en.html

**Comment by masaori335** [comment]
That's what I'm looking for. Thanks!
