### ISSUE TITLE
memory/hdrStrHeap and  memory/hdrHeap increasing all the time

### ISSUE THREAD

**Issue by hurkgu** [apache/trafficserver#2235]
ats version:7.0.0
ram :32G
disk_cache:900G
ram_cache:32G
min_average_object_size: 65536

memory/hdrStrHeap and  memory/hdrHeap increasing all the time ,the cost can be 6G both of them,
how to slove this problem?

**Comment by scw00** [comment]
Please disabling all plugins and try it again.

**Comment by hurkgu** [comment]
@scw00  i disabled all the plugin in plugin.config  but the memory also increase with memory/hdrHeap and  memory/hdrStrHeap

the records.config:

##############################################################################
# *NOTE*: All options covered in this file should be documented in the docs:
#
#    https://docs.trafficserver.apache.org/records.config
##############################################################################
##############################################################################
# Thread configurations. Docs:
#    https://docs.trafficserver.apache.org/records.config#thread-variables
##############################################################################
CONFIG proxy.config.exec_thread.autoconfig INT 1
CONFIG proxy.config.exec_thread.autoconfig.scale FLOAT 1.500000
CONFIG proxy.config.exec_thread.limit INT 2
CONFIG proxy.config.accept_threads INT 1
CONFIG proxy.config.task_threads INT 2
CONFIG proxy.config.cache.threads_per_disk INT 8
CONFIG proxy.config.exec_thread.affinity INT 1
##############################################################################
# Specify server addresses and ports to bind for HTTP and HTTPS. Docs:
#    https://docs.trafficserver.apache.org/records.config#proxy.config.http.server_ports
##############################################################################
CONFIG proxy.config.http.server_ports STRING 8080
#CONFIG proxy.config.cluster.ethernet_interface STRING bond0
##############################################################################
# Via: headers. Docs:
#     https://docs.trafficserver.apache.org/records.config#proxy-config-http-insert-response-via-str
##############################################################################
CONFIG proxy.config.http.insert_request_via_str INT 1
CONFIG proxy.config.http.insert_response_via_str INT 0
##############################################################################
# Parent proxy configuration, in addition to these settings also see parent.config. Docs:
#    https://docs.trafficserver.apache.org/records.config#parent-proxy-configuration
#    https://docs.trafficserver.apache.org/en/latest/admin-guide/files/parent.config.en.html
##############################################################################
CONFIG proxy.config.http.parent_proxy_routing_enable INT 0
CONFIG proxy.config.http.parent_proxy.retry_time INT 300
CONFIG proxy.config.http.parent_proxy.connect_attempts_timeout INT 30
CONFIG proxy.config.http.forward.proxy_auth_to_parent INT 0
CONFIG proxy.config.http.uncacheable_requests_bypass_parent INT 1
##############################################################################
# HTTP connection timeouts (secs). Docs:
#    https://docs.trafficserver.apache.org/records.config#http-connection-timeouts
##############################################################################
CONFIG proxy.config.http.keep_alive_no_activity_timeout_in INT 115
CONFIG proxy.config.http.keep_alive_no_activity_timeout_out INT 120
CONFIG proxy.config.http.transaction_no_activity_timeout_in INT 30
CONFIG proxy.config.http.transaction_no_activity_timeout_out INT 30
CONFIG proxy.config.http.transaction_active_timeout_in INT 900
CONFIG proxy.config.http.transaction_active_timeout_out INT 0
CONFIG proxy.config.http.accept_no_activity_timeout INT 120
CONFIG proxy.config.net.default_inactivity_timeout INT 600
##############################################################################
# Origin server connect attempts. Docs:
#    https://docs.trafficserver.apache.org/records.config#origin-server-connect-attempts
##############################################################################
CONFIG proxy.config.http.connect_attempts_max_retries INT 3
CONFIG proxy.config.http.connect_attempts_max_retries_dead_server INT 1
CONFIG proxy.config.http.connect_attempts_rr_retries INT 3
CONFIG proxy.config.http.connect_attempts_timeout INT 30
CONFIG proxy.config.http.post_connect_attempts_timeout INT 1800
CONFIG proxy.config.http.down_server.cache_time INT 60
CONFIG proxy.config.http.down_server.abort_threshold INT 10
##############################################################################
# Negative response caching, for redirects and errors. Docs:
#    https://docs.trafficserver.apache.org/records.config#negative-response-caching
##############################################################################
CONFIG proxy.config.http.negative_caching_enabled INT 0
CONFIG proxy.config.http.negative_caching_lifetime INT 1800
##############################################################################
# Proxy users variables. Docs:
#    https://docs.trafficserver.apache.org/records.config#proxy-user-variables
##############################################################################
CONFIG proxy.config.http.insert_client_ip INT 1
CONFIG proxy.config.http.insert_squid_x_forwarded_for INT 1
##############################################################################
# Security. Docs:
#    https://docs.trafficserver.apache.org/records.config#security
##############################################################################
CONFIG proxy.config.http.push_method_enabled INT 0
##############################################################################
# Enable / disable HTTP caching. Useful for testing, but also as an
# overridable (per remap) config
##############################################################################
CONFIG proxy.config.http.cache.http INT 1
CONFIG proxy.config.http.cache.ims_on_client_no_cache INT 0
##############################################################################
# Cache control. Docs:
#    https://docs.trafficserver.apache.org/records.config#cache-control
#    https://docs.trafficserver.apache.org/en/latest/admin-guide/files/cache.config.en.html
##############################################################################
CONFIG proxy.config.http.cache.ignore_client_cc_max_age INT 1
CONFIG proxy.config.http.normalize_ae_gzip INT 1
CONFIG proxy.config.http.cache.cache_responses_to_cookies INT 1
CONFIG proxy.config.http.cache.cache_urls_that_look_dynamic INT 1
    # https://docs.trafficserver.apache.org/records.config#proxy-config-http-cache-when-to-revalidate
CONFIG proxy.config.http.cache.when_to_revalidate INT 0
    # https://docs.trafficserver.apache.org/records.config#proxy-config-http-cache-required-headers
CONFIG proxy.config.http.cache.required_headers INT 2
##############################################################################
# Heuristic cache expiration. Docs:
#    https://docs.trafficserver.apache.org/records.config#heuristic-expiration
##############################################################################
CONFIG proxy.config.http.cache.heuristic_min_lifetime INT 3600
CONFIG proxy.config.http.cache.heuristic_max_lifetime INT 86400
CONFIG proxy.config.http.cache.heuristic_lm_factor FLOAT 0.100000
##############################################################################
# Network. Docs:
#    https://docs.trafficserver.apache.org/records.config#network
##############################################################################
CONFIG proxy.config.net.connections_throttle INT 65536
CONFIG proxy.config.net.max_connections_in INT 65536
CONFIG proxy.config.net.max_connections_active_in INT 30000
##############################################################################
# RAM and disk cache configurations. Docs:
#    https://docs.trafficserver.apache.org/records.config#ram-cache
#    https://docs.trafficserver.apache.org/en/latest/admin-guide/files/storage.config.en.html
##############################################################################
CONFIG proxy.config.cache.ram_cache.size INT 8589934592
CONFIG proxy.config.cache.ram_cache_cutoff INT 4194304
    # https://docs.trafficserver.apache.org/records.config#proxy-config-cache-limits-http-max-alts
CONFIG proxy.config.cache.limits.http.max_alts INT 5
    # https://docs.trafficserver.apache.org/records.config#proxy-config-cache-max-doc-size
CONFIG proxy.config.cache.max_doc_size INT 0
CONFIG proxy.config.cache.min_average_object_size INT 65536
##############################################################################
# Logging Config. Docs:
#    https://docs.trafficserver.apache.org/records.config#logging-configuration
#    https://docs.trafficserver.apache.org/en/latest/admin-guide/files/logging.config.en.html
##############################################################################
CONFIG proxy.config.log.logging_enabled INT 3
CONFIG proxy.config.log.max_space_mb_for_logs INT 25000
CONFIG proxy.config.log.max_space_mb_headroom INT 1000
CONFIG proxy.config.log.rolling_enabled INT 1
CONFIG proxy.config.log.rolling_interval_sec INT 86400
CONFIG proxy.config.log.rolling_size_mb INT 5000
CONFIG proxy.config.log.auto_delete_rolled_files INT 1
CONFIG proxy.config.log.periodic_tasks_interval INT 5
CONFIG proxy.config.log.logfile_dir STRING /data/log/ats
##############################################################################
# These settings control remapping, and if the proxy allows (open) forward proxy or not. Docs:
#    https://docs.trafficserver.apache.org/records.config#url-remap-rules
#    https://docs.trafficserver.apache.org/en/latest/admin-guide/files/remap.config.en.html
##############################################################################
CONFIG proxy.config.url_remap.remap_required INT 1
    # https://docs.trafficserver.apache.org/records.config#proxy-config-url-remap-pristine-host-hdr
CONFIG proxy.config.url_remap.pristine_host_hdr INT 0
    # https://docs.trafficserver.apache.org/records.config#reverse-proxy
CONFIG proxy.config.reverse_proxy.enabled INT 1
##############################################################################
# SSL Termination. Docs:
#    https://docs.trafficserver.apache.org/records.config#client-related-configuration
#    https://docs.trafficserver.apache.org/en/latest/admin-guide/files/ssl_multicert.config.en.html
##############################################################################
CONFIG proxy.config.ssl.client.verify.server INT 0
CONFIG proxy.config.ssl.client.CA.cert.filename STRING NULL
CONFIG proxy.config.ssl.server.cipher_suite STRING ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
##############################################################################
# Debugging. Docs:
#    https://docs.trafficserver.apache.org/records.config#diagnostic-logging-configuration
##############################################################################
CONFIG proxy.config.diags.debug.enabled INT 0
CONFIG proxy.config.diags.debug.tags STRING http.*|dns.*
# ToDo: Undocumented
CONFIG proxy.config.dump_mem_info_frequency INT 300
CONFIG proxy.config.http.slow.log.threshold INT 0
CONFIG proxy.config.body_factory.template_sets_dir STRING etc/trafficserver/body_factory
CONFIG proxy.config.log.config.filename STRING logging.config
CONFIG proxy.config.url_remap.filename STRING remap.config
#ui
CONFIG proxy.config.http_ui_enabled INT 1
CONFIG proxy.config.cache.target_fragment_size INT 131072

**Comment by hurkgu** [comment]
@mingzym for help!!!

**Comment by hurkgu** [comment]
now change: 
  proxy.config.cache.ram_cache.algorithm: lru
  proxy.config.url_remap.pristine_host_hdr:1

and disable all plguins  except regex_map
but the memory/hdrHeap and memory/hdrStrHeap increasing all the time
traffic.out:

```shell
   Allocated      |        In-Use      | Type Size  |   Free List Name
--------------------|--------------------|------------|----------------------------------
           67108864 |                  0 |    2097152 | memory/ioBufAllocator[14]
           33554432 |            2097152 |    1048576 | memory/ioBufAllocator[13]
           16777216 |            3145728 |     524288 | memory/ioBufAllocator[12]
         1744830464 |         1693712384 |     262144 | memory/ioBufAllocator[11]
         5154799616 |         5052956672 |     131072 | memory/ioBufAllocator[10]
         1145044992 |         1113391104 |      65536 | memory/ioBufAllocator[9]
          457179136 |          440958976 |      32768 | memory/ioBufAllocator[8]
          184549376 |          179798016 |      16384 | memory/ioBufAllocator[7]
           43778048 |           40714240 |       8192 | memory/ioBufAllocator[6]
           54001664 |           51138560 |       4096 | memory/ioBufAllocator[5]
                  0 |                  0 |       2048 | memory/ioBufAllocator[4]
                  0 |                  0 |       1024 | memory/ioBufAllocator[3]
                  0 |                  0 |        512 | memory/ioBufAllocator[2]
              32768 |                  0 |        256 | memory/ioBufAllocator[1]
              16384 |                256 |        128 | memory/ioBufAllocator[0]
             196608 |              51744 |         96 | memory/eventAllocator
            1542240 |            1419760 |         80 | memory/mutexAllocator
             163840 |             159552 |         64 | memory/ioBlockAllocator
            5450880 |            5421936 |         48 | memory/ioDataAllocator
             816000 |             543120 |        240 | memory/ioAllocator
                  0 |                  0 |        416 | memory/socksAllocator
                  0 |                  0 |        128 | memory/udpReadContAllocator
                  0 |                  0 |        160 | memory/udpPacketAllocator
            1789952 |             771328 |        736 | memory/netVCAllocator
                  0 |                  0 |        128 | memory/UDPIOEventAllocator
                  0 |                  0 |        864 | memory/sslNetVCAllocator
            7233536 |            7198720 |         64 | memory/RamCacheLRUEntry
                  0 |                  0 |         96 | memory/RamCacheCLFUSEntry
              61440 |              58720 |        160 | memory/openDirEntry
                  0 |                  0 |         48 | memory/evacuationKey
                  0 |                  0 |         64 | memory/cacheRemoveCont
              12288 |               5760 |         96 | memory/evacuationBlock
             368160 |             365328 |        944 | memory/cacheVConnection
                  0 |                  0 |         48 | memory/ClusterVConnectionCache::Entry
                  0 |                  0 |        576 | memory/cacheContAllocator
                  0 |                  0 |         32 | memory/byteBankAllocator
                  0 |                  0 |        592 | memory/clusterVCAllocator
                  0 |                  0 |        112 | memory/inControlAllocator
                  0 |                  0 |        128 | memory/outControlAllocator
                  0 |                  0 |         16 | memory/DNSRequestDataAllocator
                  0 |                  0 |      33856 | memory/dnsBufAllocator
                  0 |                  0 |       1280 | memory/dnsEntryAllocator
               4096 |                 32 |         16 | memory/expiryQueueEntry
              16384 |              14976 |         64 | memory/refCountCacheHashingValueAllocator
                  0 |                  0 |         96 | memory/hostDBFileContAllocator
             296960 |               2320 |       2320 | memory/hostDBContAllocator
                  0 |                  0 |        128 | memory/OneWayTunnelAllocator
          498073600 |          498003968 |       2048 | memory/hdrStrHeap
          498597888 |          498524160 |       2048 | memory/hdrHeap
              32768 |                  0 |        256 | memory/httpCacheAltAllocator
                  0 |                  0 |         48 | memory/CongestRequestParamAllocator
                  0 |                  0 |        160 | memory/CongestionDBContAllocator
                  0 |                  0 |        128 | memory/RemapPluginsAlloc
                  0 |                  0 |        944 | memory/http2ClientSessionAllocator
                  0 |                  0 |       1200 | memory/http2StreamAllocator
                  0 |                  0 |         48 | memory/CacheLookupHttpConfigAllocator
             221184 |             198912 |        192 | memory/httpServerSessionAllocator
           22515712 |              91776 |       7648 | memory/httpSMAllocator
            1830400 |             912560 |        880 | memory/http1ClientSessionAllocator
                  0 |                  0 |        128 | memory/socksProxyAllocator
                  0 |                  0 |         32 | memory/MIMEFieldSDKHandle
                  0 |                  0 |        240 | memory/INKVConnAllocator
                  0 |                  0 |         96 | memory/INKContAllocator
                  0 |                  0 |         32 | memory/apiHookAllocator
                  0 |                  0 |        592 | memory/ICPRequestCont_allocator
                  0 |                  0 |        128 | memory/ICPPeerReadContAllocator
                  0 |                  0 |        432 | memory/PeerReadDataAllocator
                  0 |                  0 |        512 | memory/FetchSMAllocator
            1703936 |              12288 |       1024 | memory/ArenaBlock
         9942600832 |         9591670048 |            | TOTAL
```
