### ISSUE TITLE
rate_of metrics (exacts_per_second) reported as 0 in ats 7.x

### ISSUE THREAD

**Issue by realpdm** [apache/trafficserver#2237]
Testing builds from ats 7.x branch I find that the xacts_per_second  per second metrics report as 0 even though other metrics seem to work where the requests/sec can be deduced from. 

traffic_ctl metric match xacts                               
proxy.node.http.user_agent_xacts_per_second 0
proxy.cluster.http.user_agent_xacts_per_second 0
proxy.node.user_agent_xacts_per_second 0
proxy.cluster.user_agent_xacts_per_second 0

Looking at the metric **proxy.process.http.incoming_requests** it does increase and this seems to be the metric the others are calculated from.

**Comment by realpdm** [comment]
the other metric defined that uses rate_of_10s also is reporting 0s.

proxy.node.dns.lookups_per_second

**Comment by zwoop** [comment]
@jpeach any thoughts? Is this an issue with the Lua processing of metrics.config?

**Comment by shukitchan** [comment]
This should be fixed by #2660

**Comment by ravilr** [comment]
@zwoop Any plans to backport this to a 7.x release. Thanks.
