### ISSUE TITLE
[HELP] An odd proxy scene

### ISSUE THREAD

**Issue by DonghuaLau** [apache/trafficserver#2246]
I have an odd proxy scene, like the below flow. Can I implement a plugin to do this and how? There is a way implementing this scene If deploy 3 proxy servers, but I want to find a simpler way.
**Proxy flow:**
```(1).forward proxy(https) -> (2).reverse proxy(https and certificate) -> (3).forward proxy(http) -> (4).origin server(https)```

**Comment by bryancall** [comment]
If this is still an issue please reopen.
