### ISSUE TITLE
header_rewrite's STATUS gets 0'd after 1st READ_RESPONSE rule

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#2261]
In ATS 7 (have not tried reproducing in <7), We have a header_rewrite like:
# removed a path rule for simplicity -- the behavior remains
cond %{READ_RESPONSE_HDR_HOOK}
    set-header Content-Type application/pkix-crl

cond %{READ_RESPONSE_HDR_HOOK} [AND]
cond %{STATUS} >199
    set-header Cache-Control "max-age=600, public"

A 200 from origin does not survive the 1st rule. eg, debug says
[Jul 11 14:02:47.314] Server {0x7fc996fab700} DIAG: (header_rewrite) Evaluating STATUS()
[Jul 11 14:02:47.314] Server {0x7fc996fab700} DIAG: (header_rewrite)   testing: "0" > "199" -> 0

whereas, when switching the rules around:
cond %{READ_RESPONSE_HDR_HOOK} [AND]
cond %{STATUS} >199
    set-header Cache-Control "max-age=600, public"
cond %{READ_RESPONSE_HDR_HOOK}
    set-header Content-Type application/pkix-crl

the STATUS remains 200:
[Jul 11 19:32:36.407] Server {0x2aaab4b0c700} DIAG: (header_rewrite) Evaluating STATUS()
[Jul 11 19:32:36.407] Server {0x2aaab4b0c700} DIAG: (header_rewrite)   testing: "200" > "199" -> 1

**Comment by zwoop** [comment]
I have a fix for this, PR coming soon.
