### ISSUE TITLE
Next-hop self detection

### ISSUE THREAD

**Issue by vmamidi** [apache/trafficserver#2269]
find parent should use the next parent if selected parent is the same host based on configuration.

**Comment by zwoop** [comment]
@vmamidi Please add some more details on this (and all :) Issues. At least Labels, and likely Milestone and Assiggnee if you are working on something. Thanks!

**Comment by jrushford** [comment]
@zwoop, thanks for moving that document but, I’m no-longer able to edit it.  Are you able to give me permission to edit it, I wanted to add more information.

**Comment by zwoop** [comment]
You guys weren't added, I've fixed that so now there's no excuse not to fix all the bad documents!

**Comment by jrushford** [comment]
[approve ci]
