### ISSUE TITLE
lj_record_ins of LuaJIT has very high cpu utilization

### ISSUE THREAD

**Issue by taoyunxing** [apache/trafficserver#2278]
I have a ATS 6.2.1 production host without using any lua script or ts_lua plugin,
but I found the cpu utilization always rise and fall dramatically which cause traffic_server process frequently restart，several times in a day.

why ATS call j_record_ins function of LuaJIT source code ? I don't have any lua config.
Does anyone have any ideas on why this happens or a way to fix it?
Thanks in advance.

perf top -p $(pidof traffic_server)

Samples: 3M of event 'cycles', Event count (approx.): 597008779262
 76.93%  traffic_server                  [.] lj_record_ins
 11.23%  [kernel]                        [k] _spin_lock
  1.07%  [kernel]                        [k] rmap_walk
  1.03%  [kernel]                        [k] try_to_unmap_anon
  0.73%  [ixgbe]                         [k] 0x00000000000013f0
  0.26%  [kernel]                        [k] _read_lock
  0.26%  [kernel]                        [k] _spin_lock_irqsave
  0.24%  libpcre.so.0.0.1                [.] 0x0000000000010020
  0.23%  [bonding]                       [k] bond_start_xmit
  0.22%  [kernel]                        [k] skb_release_data
  0.21%  [kernel]                        [k] tcp_v4_rcv
  0.21%  [kernel]                        [k] __kfree_skb
  0.21%  [kernel]                        [k] __inet_lookup_established
  0.20%  [kernel]                        [k] ip_route_input
  0.19%  [kernel]                        [k] dst_release
  0.16%  [kernel]                        [k] dev_queue_xmit
  0.16%  [appex0]                        [k] 0x000000000003b0a9
  0.14%  [kernel]                        [k] _spin_lock_irq
  0.13%  [kernel]                        [k] csum_partial
  0.13%  [kernel]                        [k] _spin_lock_bh
  0.13%  [kernel]                        [k] tcp_wfree
  0.12%  [kernel]                        [k] futex_wait_setup
  0.12%  [kernel]                        [k] smp_invalidate_interrupt

ATS 6.2.1 compile command in .spec file On CentOS 6.x:
NOCONFIGURE=1 autoreconf -vif
./configure                         \
  --enable-layout=Gentoo            \
  --libdir=%{_libdir}/trafficserver \
  --with-tcl=%{_libdir}             \
  --with-user=ats --with-group=ats  \
  --disable-silent-rules            \
  --disable-tests                   \
  --enable-experimental-plugins     \
  --enable-example-plugins          \
  --enable-imgcdn-plugins           #\
  #--enable-debug                    \
  #CXXFLAGS="-fsanitize=address -fno-omit-frame-pointer"

make

**Comment by shukitchan** [comment]
Please check out the following 
https://issues.apache.org/jira/browse/TS-4099
The metrics definition is using lua starting in 6.2.0

So it should have something to do with that.

**Comment by taoyunxing** [comment]
But the default value of proxy.config.stats.enable_lua is 0, which means traffic_manager of ATS 6.2.1 still using stats.config.xml, not metrics.config !  In such case, no bindings and metrics codes been  executed，why/where use lj_record_ins function ?

**Comment by taoyunxing** [comment]
Note some codes in ATS 6.2.1:
 
RecBool enable_lua  = false;
BindingInstance *binding = NULL;

RecGetRecordBool("proxy.config.stats.enable_lua", &enable_lua);
  
if (enable_lua) {                                                                                                                                                      
    binding = new BindingInstance;
    metrics_binding_initialize(*binding);
  }

    if (enable_lua) {
      metrics_binding_evaluate(*binding);
    } else {
      if (statProcessor) {
        statProcessor->processStat();
      }
    }

  if (binding) {
    metrics_binding_destroy(*binding);
    delete binding;
  }

**Comment by taoyunxing** [comment]
performance of lua metrics in ats core is OK? 
@james @shukitchan

**Comment by shukitchan** [comment]
if you use "perf top" with "-g" option, would it show the functions calling lj_record_ins?
I think you can also use gdb and stop the process in the middle to examine the stack trace of some of the execution threads. Then you can perhaps see who's calling lj_record_ins. 

Performance should be fine. There are production deployments with 7.x which has the lua metrics working full time.

**Comment by taoyunxing** [comment]
I know what you mean, but perf top could'nt show functions call stack using -g, on the other hand, the high cpu utilization of lj_record_ins usually occurs on a huge network traffic of production host, on a short moment, so gdb backtrac is very difficult to do.
I have backported TS-4100 and make a new rpm of ATS 6.2.1, I want to verify lua metrics performance on production environment.

**Comment by taoyunxing** [comment]
I backport TS-4100 & PR 705 (remove XML and use lua metric default), and found the issue was addressed.

**Comment by PSUdaemon** [comment]
Can this be closed now or is there a backport to be made here?

**Comment by shukitchan** [comment]
I think it can be close.
