### ISSUE TITLE
when in high concurrent scenarios，the rt will be high even if all the request are mem hit

### ISSUE THREAD

**Issue by Triater** [apache/trafficserver#2279]
I use trafficserver 7.0.0 on centos6.5, only use cachekey plugin. even when all requests are mem hit, the rt is still very high. how can I find the reason to optimize?

below is the squid.log:

![snip20170718_67](https://user-images.githubusercontent.com/1321961/28311578-add0c8f4-6be2-11e7-8a0f-7d35c1d16932.png)

**Comment by shukitchan** [comment]
You can try to display milestones using the XDebug plugin 
https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/xdebug.en.html

And see if it will reveal some clues.

**Comment by shukitchan** [comment]
or perhaps you don't have enough threads to handle the load since you mentioned "high concurrent scenarios"

**Comment by Triater** [comment]
@shukitchan is it possible related to the config of cachekey plugin ? below is my config:
![image](https://user-images.githubusercontent.com/1321961/28348156-e75298ce-6c6d-11e7-9f8a-7a1a922967f6.png)

**Comment by scw00** [comment]
Please try to configure the volume.config. ATS will use the global mutex when access the same disk (actually, we divided the disk into several vols. There is only one vol for a disk if we don't use volume.config).

**Comment by shukitchan** [comment]
I am not too familiar with the cachekey plugin. You can of course try the xdebug plugin to see the milestones reported. 

Also you can turn on the debug message and see the traffic.out and it should also give me hints on why some mem_hit is taking so long.

**Comment by bryancall** [comment]
It looks like you are benchmarking with 1 URL.  This would have lock contention on 1 lock.  You can benchmark with multiple URLs and configure volume.config to have multiple volumes.
