### ISSUE TITLE
ats 7.1.0 (rc1) gets stuck in high CPU state some times

### ISSUE THREAD

**Issue by realpdm** [apache/trafficserver#2295]
I have had a node running ats 7.1.0 (rc1) in production and some times it gets stuck into a very high CPU use state consuming all 20 cores. Server has 48G RAM and 2x10G nics. 

The traffic levels were about 1000 requests/sec peaking with around 40,000 http.current_client_connections. However this node was handling TLS/POST uploads at a rate of about 100+ TLS uploads/sec and an inbound network traffic level of about 2.5Gbps.

As traffic levels ramp up the CPU usage seems to go up as well but at some point it goes up in a way unrelated to traffic levels.

CPU Usage:
![image](https://user-images.githubusercontent.com/1679707/28553457-64da8ff0-70b9-11e7-9e90-544a674534a9.png)

TLS/POST Rate:
![image](https://user-images.githubusercontent.com/1679707/28553497-b24f5fe0-70b9-11e7-8aae-f73aebf59c2e.png)

While the CPU usage issue was occurring I ran perf top -g and drilled into the spin_lock and captured this:

![image](https://user-images.githubusercontent.com/1679707/28553519-d9d39bb2-70b9-11e7-95a0-e4b81b4c1003.png)

This seems to suggest it is getting stuck doing something with TLS but what I have no idea. 

2.6.32-696.1.1.el6.x86_64
OpenSSL 1.0.1e-fips 11 Feb 2013 (fips mode not enabled)

If anyone can suggest additional debugging I might do when this happens I am happy to do so.

**Comment by taoyunxing** [comment]
try perf top -p $(pidof traffic_server) and check the func with high cpu usage?

**Comment by realpdm** [comment]
This may have been an extreme high load situation causing this. I'm going to close it for now as i've not seen a recurrence.
