### ISSUE TITLE
Non-optimal string identifier lookups may be impacting performance

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#2307]
ATS seems to do a lot of associative lookups of string identifiers.  This seems to include code that runs per-message for high frequency message streams.  In some cases, the lookup is done with if-else-if statements and <cstring> compare functions.

Code generation is one possible way of improving these associative lookups.  I have written some short, crude examples here:  https://github.com/ywkaras/MiscRepo/tree/master/Idents .

Log formats seem to be an important case to look at with respect to this.  Are the cryptic, abbreviated field names in the format strings a way of trying to optimize associative lookups of the names?  Why can't/shouldn't the log format that the (high-frequency) log line generation code is using be an array of entries of the form:

```
struct LogLineSegment
{
  bool isLIteral;
  union
  {
    ts::StringView literal;
    FieldCode code;
  };
};
```

where FieldCode is an enum?

**Comment by ywkaras** [comment]
After looking at the logging code in greater detail, it appears the field name lookup _is_ generally done using a hash table.  But, the lookup of MIME header tags is not done with a hash table, and it is not clear to me why not.

**Comment by SolidWallOfCode** [comment]
There are two layers of MIME header lookup acceleration done so that common headers are found in constant time.

**Comment by ywkaras** [comment]
It seemed to me that MIME header keywords are looked up using regular expression matching code (PCRE).  I don't understand how that makes sense.

**Comment by ywkaras** [comment]
This is not likely to be a significant performance issue.
