### ISSUE TITLE
crash occasionally in full cluster mode

### ISSUE THREAD

**Issue by zhshli8324** [apache/trafficserver#2311]
version: 6.2.1.  3 machines, 12 cluster threads.  crash occasionally  at this code "ink_assert(magicno == (int)MagicNo);" 
can't figure out why there is a invalid magicno.
system information:
Linux 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Thread 21408, [ET_CLUSTER 3]:
0    0x00000000004a465d crash_logger_invoke(int, siginfo*, void*) + 0x7d
1    0x0000003102232510 __restore_rt + (nil)
2    0x0000003102232495 gsignal + 0x35
3    0x0000003102233c75 abort + 0x175
4    0x00002ba3d001e883 ink_fatal_va(char const*, __va_list_tag*) + 0x83
5    0x00002ba3d001e91d ink_fatal(char const*, ...) + 0x8d
6    0x00002ba3d001c125 _ink_assert + 0x15
7    0x00000000006b2caf CacheContinuation::tunnelClosedEvent(int, void*) + 0x5f
8    0x000000000066bcc3 OneWayTunnel::startEvent(int, void*) + 0x4d3
9    0x000000000069a5f3 ClusterHandler::cluster_signal_and_update(int, ClusterVConnection*, ClusterVConnState*) + 0x33
10   0x0000000000696098 ClusterHandler::valid_for_data_write(ClusterVConnection*) + 0x298
11   0x0000000000696555 ClusterHandler::build_write_descriptors() + 0x145
12   0x0000000000698da0 _ZN14ClusterHandler13process_writeElb.clone.1 + 0x5f0
13   0x0000000000699064 ClusterHandler::mainClusterEvent(int, Event*) + 0x1d4
14   0x000000000069c05a ClusterState::IOComplete() + 0x8a
15   0x000000000069c347 ClusterState::doIO_read_event(int, void*) + 0xa7
16   0x0000000000722a27 read_signal_done(int, NetHandler*, UnixNetVConnection*) + 0x47
17   0x00000000007238fc read_from_net(NetHandler*, UnixNetVConnection*, EThread*) + 0x85c
18   0x0000000000716280 NetHandler::mainNetEvent(int, Event*) + 0x200
19   0x000000000074313d EThread::process_event(Event*, int) + 0x12d
20   0x0000000000743a89 EThread::execute() + 0x4c9
21   0x000000000074257a spawn_thread_internal(void*) + 0x4a
22   0x00002ba3d06a4aa1 start_thread + 0xd1
23   0x00000031022e8bcd clone + 0x6d
24   0x0000000000000000 0x0 + 0x6d

**Comment by zwoop** [comment]
I'm not sure anyone will work on this, since this feature is removed, but if you have a fix we'll consider it for the 6.2.x LTS branch.

**Comment by DonghuaLau** [comment]
@zwoop It's that means the clustering is removed from 7.x? Why?

**Comment by zwoop** [comment]
Clustering is no longer supported.
