### ISSUE TITLE
Clearing the active node in deactivate

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#2350]
It seems like we clear the active node if it's child do deactivate.

```
template <typename T>
void
Http2DependencyTree<T>::deactivate(Node *node, uint32_t sent)
{
  node->active = false;

  while (node->queue->empty() && node->parent != NULL) {
    node->parent->queue->erase(node->entry);
    node->queued = false;

    node = node->parent;
  }

  update(node, sent);
}
```

**Comment by masaori335** [comment]
Did https://github.com/apache/trafficserver/commit/8d982c8cd77923ac5ca8276a20dcabc18ee3c6fa fix this? Now, `node->active` is checked in the while loop.

https://github.com/apache/trafficserver/blob/322e97b84a8f7e9d2956c902d619ef959411000a/proxy/http2/Http2DependencyTree.h#L534-L550

**Comment by scw00** [comment]
[8d982c8](https://github.com/apache/trafficserver/commit/8d982c8cd77923ac5ca8276a20dcabc18ee3c6fa)

fixed that . thanks
