### ISSUE TITLE
Possible memory leak in ATS plug-in API

### ISSUE THREAD

**Issue by deeonis-ru** [apache/trafficserver#2354]
The leak happens when the call of TSHttpTxnReenable is postponed and is not called immediately in hook callback. Some ATS memory pools permanently rise, e.g. cacheVConnection, hdrStrHeap, and some other.

I have created a small dummy plugin which just sets up a global hook for TS_HTTP_READ_REQUEST_HDR_HOOK event and does delayed reenable of it. Additionally, the plugin can be built to immediately reenable a transaction in the hook callback. The source of the dummy plugin is attached.

I have created a small Selenium test which repeatedly visit a couple of web pages and emulate an user activity. Additionally, I activated the memory dump ATS feature vie "proxy.config.dump_mem_info_frequency" config option. The value is 60 sec. I ran the test for both versions of the dummy plug-in (immediately reenable and delayed reenable versions). In the attachment you can find 2 archives with results:

- dummy_global_imm_reenable.zip - a memory statistic dumps (proxy.log) and visual graphs (*.png) for case when we reenable a transaction immediately
- dummy_global_delayed_reenable.zip - a memory statistic dumps (proxy.log) and visual graphs (*.png) for case when we do a delayed reenable of transaction. 

Consumption of some memory pools looks different.

Affected ATS version: 6.2.1, 7.2
Environment: Ubuntu 16.04
Compiler: gcc version 4.9.4

I'm happy to provide any additional information in order to fix the issue.

[dummy_plugin_src.zip](https://github.com/apache/trafficserver/files/1211943/dummy_plugin_src.zip)
[dummy_global_imm_reenable.zip](https://github.com/apache/trafficserver/files/1211944/dummy_global_imm_reenable.zip)
[dummy_global_delayed_reenable.zip](https://github.com/apache/trafficserver/files/1211945/dummy_global_delayed_reenable.zip)
[trafficserver_configs.zip](https://github.com/apache/trafficserver/files/1211999/trafficserver_configs.zip)

**Comment by randall** [comment]
I only tested this on master (aka 9.x at the time of this comment), but it looks like the `TSMutex` is leaking every request with this particular plugin. If I free the mutex, I no longer see a leak.

**Comment by bryancall** [comment]
@deeonis-ru You need to call TSMutexDestroy() to free the mutex.
