### ISSUE TITLE
TS crashes during SSL handshake

### ISSUE THREAD

**Issue by adimallikarjunareddy** [apache/trafficserver#2364]
> Thread 28046, [ET_SSL 1]:
0    0x000000000051911d crash_logger_invoke(int, siginfo*, void*) + 0x98
1    0x00002b4e06f777e0 __restore_rt + (nil)
2    0x00002b4e08b59495 gsignal + 0x35
3    0x00002b4e08b5ac75 abort + 0x175
4    0x00002b4e05ef8579 ink_fatal_va(char const*, __va_list_tag*) + (nil)
5    0x00002b4e05ef8632 ink_fatal(char const*, ...) + (nil)
6    0x00002b4e05ef86d1 ink_pfatal(char const*, ...) + (nil)
7    0x00002b4e05ef5e36 ink_get_rand() + (nil)
8    0x0000000000767035 SSLNetVConnection::net_read_io(NetHandler*, EThread*) + 0x66d
9    0x000000000077bac5 NetHandler::waitForActivity(long) + 0x69b
10   0x00000000007a308d EThread::execute_regular() + 0x4e3
11   0x00000000007a31ca EThread::execute() + 0x30
12   0x00000000007a1e23 spawn_thread_internal(void*) + 0x75
13   0x00002b4e06f6faa1 start_thread + 0xd1
14   0x00002b4e08c0fbcd clone + 0x6d
15   0x0000000000000000 0x0 + 0x6d

Above is the stack trace from the crash log. Any insights on this would be really helpful.

**Comment by scw00** [comment]
Version ?

**Comment by adimallikarjunareddy** [comment]
5.3.0

**Comment by bryancall** [comment]
ATS 5.3.0 isn't support anymore.  If this is happening in a later version please reopen.
