### ISSUE TITLE
Preserve some client request headers in H2 Server Push promises

### ISSUE THREAD

**Issue by calavera** [apache/trafficserver#2372]
This is an improvement on top of the H2 Server Push API.

In the current implementation, the API creates a new empty header for the push promise, ignoring the client request headers received by ATS:

https://github.com/apache/trafficserver/blob/a50aaf1a4f0a76faeb3050dec3a5e75ff90b9f94/proxy/InkAPI.cc#L7637-L7653

A disadvantage of this approach is that ATS drops useful information sent by the client, for example the Accept-Encoding headers, sending all push promises without any encoding whatsoever. ATS will always serve the pushed content without any compression, even if the client supports gzip, brotli or any other.

I think there are three ways to improve the Push API:

1. Preserve some header fields from the original client request in the push promise, for example Accept-Encoding. This would make compression transparent to anyone that wants to use the Push API. This disadvantage of this approach is that what might be useful for my use case my not be good enough for other use cases.

2. Allow to pass an extra set of header fields to the Server Push promise. This approach would delegate to the Plugin developer to decide which header fields they want to propagate to the push promise.

3. Combine 1 and 2. If the plugin developer doesn't set any extra headers, set a sane defaults we agree upon, like Accept-Encoding.

I'm opening this issue before implementing any change because this could be a breaking change in the API that we might want to discuss in other places, like the mailing list. Since this Server Push API is still experimental, we might be still in time to make this changes before worrying too much about backwards compatibility.

/cc @maskit

**Comment by maskit** [comment]
Nice idea. Preserving Accept-Encoding makes much sense.

**Comment by calavera** [comment]
Fixed by #2557
