### ISSUE TITLE
Simplify UDP packet send queue

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#2373]
When sending UDP packets, the API has an argument to specify when to delivery the packet (delivery_time). And `PacketQueue` is handling them.
But it looks like no one is using this feature now and this is not accessible from TSAPI. 
So we can remove this feature and make UDP layer more simple.

**Comment by scw00** [comment]
Why do not add TSAPI instead of removing ?

**Comment by masaori335** [comment]
Who need that feature? I'd like remove the overhead and complexity comes from that feature.

**Comment by scw00** [comment]
@maskit I think this feature can do better as we discussed .

**Comment by maskit** [comment]
@scw00 Hmm, I'm not sure. Maybe not.

A QUIC packet can contain multiple QUIC frames, but a UDP packet always contains only one QUIC packet. So, I think adjusting delivery time of UDP packets wouldn't help that issue (https://github.com/apache/trafficserver/pull/2342#discussion_r133125525).

Am I missing something?

**Comment by scw00** [comment]
No, you are right !

**Comment by masaori335** [comment]
We'll revisit if this is performance issue.

**Comment by maskit** [comment]
#6316

**Comment by maskit** [comment]
Pushed back to TODO since nobody is actively working on it.

**Comment by maskit** [comment]
Maybe we can use SO_TXTIME instead. See https://docs.rs/quiche/latest/quiche/#pacing.

**Comment by maskit** [comment]
@brbzull0 You might be interested in this issue since you are working on GRO and sendmsg stuff.

**Comment by maskit** [comment]
`ts.quic.pacing` looks reasonable. I can't think of a case that a user want to turn it off, but turning it off could skip unnecessary steps (i.e. setting timing info) on platforms that don't support pacing. I wonder what we can do on FreeBSD.

**Comment by brbzull0** [comment]
> `ts.quic.pacing` looks reasonable. I can't think of a case that a user want to turn it off, but turning it off could skip unnecessary steps (i.e. setting timing info) on platforms that don't support pacing. I wonder what we can do on FreeBSD.


https://github.com/apache/trafficserver/pull/11330
No coinfig flag though

**Comment by brbzull0** [comment]
https://github.com/apache/trafficserver/pull/11330 should cover this I guess.
