### ISSUE TITLE
Dynamic TLS record size tuning

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#2377]
These constant values are copied from SSLNetVConnection but aren't used currently. We should probably use these for QUIC, and they are based on the maximum QUIC packet size.
https://github.com/apache/trafficserver/blob/85155fa607828380f9b55d2a7ebfbb1b32b1976c/iocore/net/P_QUICNetVConnection.h#L79-L82

**Comment by webdriverrr** [comment]
@maskit Since IETF QUIC uses TLS as its impartible part not underlying separate _special_ protocol (as TLS in case of HTTPS) nor protocol encapsulated inside another one (as DNS within UDP) *these* defines do lose their meaning as their are presented now inside *P_QUICNetVConnection.h*.

**Comment by webdriverrr** [comment]
@maskit what should be done is that we need to replace magic constants with defines such like

https://github.com/apache/trafficserver/blob/85155fa607828380f9b55d2a7ebfbb1b32b1976c/iocore/net/P_QUICNetVConnection.h#L189

**Comment by maskit** [comment]
@webdriverrr Right, I didn't understand what they are and how QUIC does the similar things. Since PMTU Discovery is not a target of the second implementation, we can simply remove the constant values and should create a todo issue for PMTU Discovery instead.

**Comment by webdriverrr** [comment]
@maskit Yeap, that's a better approach in this case. Should I remove those QUIC_TLS* defines and create a PR in regards?

**Comment by maskit** [comment]
@webdriverrr That would be great. 😄

**Comment by webdriverrr** [comment]
@maskit FYI #2717

**Comment by maskit** [comment]
Resolved with #2717.
