### ISSUE TITLE
Support TLS hooks on QUIC

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#2378]
These are copied from SSLNetVConnection but aren't used currently. It would be great if we could use the same hooks for both SSL and QUIC. Also, we should use `enum class`.
https://github.com/apache/trafficserver/blob/85155fa607828380f9b55d2a7ebfbb1b32b1976c/iocore/net/P_QUICNetVConnection.h#L87-L92

**Comment by masaori335** [comment]
We should also support extend QUIC Frames from Plugin.

**Comment by maskit** [comment]
The enum was removed. Seems like it was for tunneling, which is currently out of scope. Closing for todo cleanup.
