### ISSUE TITLE
Missing pre session clean-up hook

### ISSUE THREAD

**Issue by clearswift** [apache/trafficserver#2380]
ATS does not provide a hook which gets called on pre-session close.

This means, if a plugin does something which needs clean-up in one of the following pre-session hooks:
* TS_VCONN_PRE_ACCEPT_HOOK
* TS_SSL_SNI_HOOK
* TS_SSL_CERT_HOOK
* TS_SSL_SERVERNAME_HOOK
* TS_SSL_LAST_HOOK

the plugin has no chance to release the allocated resources if the connection closes before a session context was established (e.g. error in TLS handshake).

**Comment by keesspoelstra** [comment]
Could this be a local TS_VCONN_END_HOOK, TS_VCONN_CLOSE_HOOK?
And it's no problem if it returns and continues directly?

**Comment by Enteee** [comment]
In general: yes. But what would be the difference between a TS_VCONN_END_HOOK and a TS_VCONN_CLOSE_HOOK?

**Comment by SolidWallOfCode** [comment]
This came up recently on the mailing list. I am undecided about whether this should be a synchronous hook or not. It could be made asynchronous if clean up is the only goal and it is acceptable to not have access to the VConn. With regard to #2388 it might be reasonable to put the args in an IOBufferBlock which can be detached from the VConn so the close hook can operate asynchronously.

**Comment by bryancall** [comment]
Should this be closed?

**Comment by SolidWallOfCode** [comment]
Yes. I reviewed the code and discussed this with @shinrich and we agree various patches, starting with the two linked here, fixed this issue.
