### ISSUE TITLE
Ability to align schedules and reenables to threads from plugins

### ISSUE THREAD

**Issue by keesspoelstra** [apache/trafficserver#2391]
The ATS code is very thread aligned, but this pattern cannot be followed by plugins as there is no possibility to align to threads, this means that sometimes txns get reenabled on a different thread and code is not run as optimal as it could be. Reenables now check for the threadpool not the preferred thread.

Plugins can profit from having more control over thread alignment:
- "free concurrency" when run on calling thread
- no thread misalignment of core ATS entities
- locality of cpu-core and data

Proposed:
- TSContScheduleOnThread
- TSContScheduleEveryOnThread
- TSHttpTxnThread, TS*Thread -> get preferred thread for HttpTxn,HttpSsn,Vio,VCONN
- TSHttpTxnRenableOwnThread, TS*ReenableOwnThread -> reenable HttpTxn,HttpSsn,Vio,VCONN on preferred thread 

We have a very rough implementation of TSContSchedule*Thread, if there is interest I'll prepare a PR for discussion.

**Comment by oschaaf** [comment]
Cross linking https://github.com/duke8253/trafficserver/pull/5 where a related discussion is going on

**Comment by bryancall** [comment]
The thread affinity APIs should be able to to handle this.  If this is still an issue please reopen.
