### ISSUE TITLE
ATS proxy header

### ISSUE THREAD

**Issue by rameshvrao** [apache/trafficserver#2399]
We are passing authorization value in header to Apache traffic server. But it is not reflecting in the header of ATS. We used mtm proxy to check whether it is added to the header . It is present. 

This error occurs when we pass the value to headers after login. During login it is present. But on further screen though we pass it is not reflected.

We used this link to set the header https://stackoverflow.com/questions/39939121/android-webview-add-header-to-http-request

**Comment by bryancall** [comment]
What version of ATS are you running?  Can you turn on debug mode in ATS do dump the headers?

**Comment by bryancall** [comment]
If this is still an issue please send an email to the users@ mailing list for support
