### ISSUE TITLE
problem of gzip plugin with empty file

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#2406]
when enabled gzip plugin with default settings,  empty file was gziped as expected，

but when that empty file had been gzipped，ats will return compressed object ignore user's choice,

please check the screenshot as follow, ats return gzipped data....

![img20170821_132147](https://user-images.githubusercontent.com/13267484/29509047-6e1a5268-8689-11e7-88ff-1df098ca1518.png)

**Comment by shukitchan** [comment]
i dont think "no-Accept-Encoding" is a supported header.

**Comment by zwoop** [comment]
This only happens with an empty body?

**Comment by bryancall** [comment]
If this is still an issue please reopen.
