### ISSUE TITLE
memory leak - unreachable log collation host 

### ISSUE THREAD

**Issue by jp557198** [apache/trafficserver#2416]
This memory leak is the result of configuring a log collation host in “logs_xml.config” and then having the host be down during the traffic run. We verified that this occurs with vanilla 6.2.1. We also noticed that there was a memory leak fix in this function patched in TS-4872, which is present in 6.2.x, 7.1.x, and master. So we tried the latest 6.2.x (current) from yesterday, but the memory leak still occurred. We have also seen that bringing up the log host during the test run stabilizes the memory allocation so we’re pretty sure that this is the trigger for the memory leak.
 
Some heap-check output from ATS compiled with tcmalloc --
Total: 3014.2 MB
  2902.3  96.3%  96.3%   2902.3  96.3% ats_malloc
    76.0   2.5%  98.8%     76.0   2.5% ats_memalign
    35.8   1.2% 100.0%   2938.1  97.5% LogObject::_checkout_write
     0.1   0.0% 100.0%      0.1   0.0% BaseLogFile::open_file
     0.0   0.0% 100.0%      0.0   0.0% ResourceTracker::lookup (inline)

**Comment by pbchou** [comment]
Confirmed this memory leak still occurs with 7.1.3.

**Comment by zwoop** [comment]
Collation is gone, so closing this.
