### ISSUE TITLE
Mid Tier Origin Retry Behavior Improvements - DNS Failover

### ISSUE THREAD

**Issue by ryandurfey** [apache/trafficserver#2418]
When the mid tier is trying to access the origin we noticed that if the DNS server lookup fails to respond that the mid tier does not switch to an alternate DNS IP.  The mid tier should retry the DNS lookup on an alternate IP (assuming one is available)  if the first lookup fails to respond.

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by guzzijason** [comment]
Based on my observations, this was primarily a problem with SERVFAIL responses, failing to retry with alternate resolver(s).

**Comment by bryancall** [comment]
@ezelkow1 Can you handle this one and close if it not an issue anymore?

**Comment by jrushford** [comment]
parent selection and strategies implements mid-tier retries
