### ISSUE TITLE
Mid Tier Origin Retry Behavior Improvements - Origin IP List Handling

### ISSUE THREAD

**Issue by ryandurfey** [apache/trafficserver#2419]
When the origin DNS lookup hands back multiple IPs to the mid tier, the ATS mid tier should allow for trying each of them in order.  

Other thoughts:
 I assume it should try the first origin based on the number of retries configured and then move on to the second origin.  We may want to limit the total number of retries here because the origin could hand back a long list of IPs which could hang the mid tier in a large number of retries.  As an alternate logic, maybe the origin should try each IP in the list once before going to the retry logic.

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by bryancall** [comment]
Relates to #2424

**Comment by jrushford** [comment]
closed, not to be implemented
