### ISSUE TITLE
header_rewrite crash if regex malformed

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#2424]
I managed to crash ATS with a header_rewrite config:

cond %{REMAP_PSEUDO_HOOK} [AND]
cond %{IP:CLIENT} /(1.2.3.4|127.0.0.1|^10\./ [NOT]
    set-status 403

(note the missing ")" in the IP:CLIENT regex).

ATS went into a crash loop with this traffic log
traffic_manager[29290]: {0x7f3043b1c840} NOTE: [LocalManager::pollMgmtProcessServer] Server Process terminated due to Sig 6: Aborted

Putting in the missing ")" stopped the loop.

Would be better to not crash, but, instead, throw a log error and not load the config.

**Comment by mlibbey** [comment]
still crashes.

**Comment by zwoop** [comment]
Indeed, crashes two years later too... Maybe time I fix it?
