### ISSUE TITLE
TextBuffer.cc: missing stdio.h (alpine 3.6/musl)

### ISSUE THREAD

**Issue by jbergstroem** [apache/trafficserver#2445]
```
  CXX      TextBuffer.lo
TextBuffer.cc: In member function 'void textBuffer::format(const char*, ...)':
TextBuffer.cc:248:60: error: 'vsnprintf' was not declared in this scope
     num = vsnprintf(this->nextAdd, this->spaceLeft, fmt, ap);
```

Thinking we want to inlude `<stdio.h>` from Textbuffer.h?

**Comment by jbergstroem** [comment]
On closer thought this perhaps should be managed from `ts/ink_apidefs.h`?

**Comment by jbergstroem** [comment]
fwiw, made a small (wip) container to simplify reproducing these things: https://github.com/jbergstroem/ts-alpine

**Comment by bryancall** [comment]
Added cstdio to the file in the PR #5565
