### ISSUE TITLE
ink_memory.cc: mallopt is GLIBC only (alpine3.6/musl)

### ISSUE THREAD

**Issue by jbergstroem** [apache/trafficserver#2448]
While building TS with musl, we will fail around here:
```
ink_memory.cc: In function 'int ats_mallopt(int, int)':
ink_memory.cc:159:30: error: 'mallopt' was not declared in this scope
   return mallopt(param, value);
```

[This guard](https://github.com/apache/trafficserver/blob/master/lib/ts/ink_memory.cc#L162) shouldn't really be `defined(linux)`, rather `defined(__GLIBC__)`.

**Comment by webdriverrr** [comment]
@jbergstroem Hmmm, maybe _features.h_ from musl-libc would be best solution? It is well spread approach of multi target builds like this.

**Comment by webdriverrr** [comment]
@jbergstroem Hmmm, maybe _features.h_ from musl-libc would be best solution? It is well spread approach of multi target builds like this.

**Comment by zwoop** [comment]
Merged.
