### ISSUE TITLE
NTLM is not working with ATS (6.2.1) recursive popup for Authentication.

### ISSUE THREAD

**Issue by sharmavijay1991** [apache/trafficserver#2486]
This is in line with (Traffic ServerTS-3866) Issue. 
Tried patch available in this bug but still facing same issue.

My Setup looks like:
Client --> ATS ( + plugin ) ---> Server
(+ plugin ) means --> plugin code which commuincates with a Auth-Server where we are using NTLM.

Here plugin communicates with Authentication server and in case of authentication we return 407 + NTLM challenge to browser. But the problem is, ATS is closing connection due to which we are not able use previous connection.

Note:- In my problem, till now we did not hit Server. It's plugin who is serving 407 and connection close to Browser(curl).

-------- On ATS pages we posted below information(detailed) -------------------
I have configured ATS as a web proxy in a NTLM authentication domain; and, have a plugin with a function for TS_HTTP_READ_REQUEST_HDR_HOOK say, func_1.

In func_1 which is invoked during the request header, I create a hook for TS_HTTP_SEND_RESPONSE_HDR_HOOK (say, func_2) and then do a TSHttpTxnReenable(txnp, TS_EVENT_HTTP_ERROR);

 

Subsequently, when func_2 is invoked during the SEND_RESPONSE_HEADER event, I frame a “407 Proxy Auth required” response header along with Proxy-Authenticate set to “NTLM” and then do a TSHttpTxnReenable(txnp, TS_EVENT_HTTP_CONTINUE);

 

Func_1() {

….

…

TSHttpTxnHookAdd(txnp, TS_HTTP_SEND_RESPONSE_HDR_HOOK,

                                 TSContCreate(responseHook, TS_NULL_MUTEX));

            }

            TSHttpTxnReenable(txnp, TS_EVENT_HTTP_ERROR);

….

return;

}

 

func_2() {

 

…

TSHttpTxnReenable(txnp, TS_EVENT_HTTP_CONTINUE);

return;

}

 

What happens is that even though the client sends a “Connection: keep-alive”, ATS seems to be returning a “Connection: close” which results in the connection getting closed.

 

 

> GET http://www.purple.com/ HTTP/1.1

> Host: www.purple.com

> Proxy-Authorization: NTLM TlRMTVNTUAABAAAABoIIAAAAAAAAAAAAAAAAAAAAAAA=

> User-Agent: curl/7.44.0

> Accept: */*

> Proxy-Connection: Keep-Alive

>

< HTTP/1.1 407 Proxy Authentication Required

< Date: Sun, 03 Sep 2017 10:47:24 GMT

< Connection: close

< Via: http/1.1 POD128-CentOS7-01 (ApacheTrafficServer/6.2.1)

< Server: ATS/6.2.1

< Proxy-Authenticate: NTLM

< Content-Length: 15

< Content-Type: text/plain

<

  0    15    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

* Closing connection 7

 

Why is ATS closing the connection?And, how can I control this behavior?

**Comment by sharmavijay1991** [comment]
There few suggestions Like:-
-------------------------------------
ATS sets the "Connection: close" header + configures the connection to close internally whenever a plugin re-enables with an error. 
You need to hook on the SEND_RESPONSE_HDRS hookpoint and: 
1) Set the Connection / Proxy-Connection headers as desired (ie - to 'keep-alive') 
2) Tell ATS to not close the connection by calling TSHttpTxnCloseAfterResponse(txn, 0) 

You may also need to call TSHttpTxnClientKeepaliveSet(txn, 1) 
-------------------------------------

Tried this too, but it did not work.

**Comment by zwoop** [comment]
I assume this is also an issue with more modern versions of ATS? 7.1.1 or current master ?

**Comment by sharmavijay1991** [comment]
There is a patch available (https://issues.apache.org/jira/browse/TS-3866) after which it works in 5.x version but 6.x is still having NTLM issue. In my case I am using ATS 6.2.1.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
