### ISSUE TITLE
Generate Stateless Reset Token with a configurable value

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#2494]
[draft-05] 7.8.2.  Calculating a Stateless Reset Token

> The stateless reset token MUST be difficult to guess.  In order to
   create a Stateless Reset Token, a server could randomly generate
   [RFC4086] a secret for every connection that it creates.  However,
   this presents a coordination problem when there are multiple servers
   in a cluster or a storage problem for a server that might lose state.
   Stateless reset specifically exists to handle the case where state is
   lost, so this approach is suboptimal.

Currently, the token is generated based on QUIC Connection ID and an ATS internal sequence number (`net_connection_number`).

**Comment by zizhong** [comment]
In the draft, it's said we can use `HMAC(static_key, server_id || connection_id)` as the algorithm. Is this ticket aiming to make static_key configurable? If so, I can try to implement it.

**Comment by maskit** [comment]
It's aiming to make `server_id` configurable.

> In order to
   create a Stateless Reset Token, a server could randomly generate
   [RFC4086] a secret for every connection that it creates.  However,
   this presents a coordination problem when there are multiple servers
   in a cluster or a storage problem for a server that might lose state.

From my understanding `server_id` in the HMAC example have to be a configurable value which is shared with multiple servers in a cluster. We may be able to use some existing configuration, and I'm fine with it. If I remember correctly, currently the token is just a sequential number on a server.

**Comment by zizhong** [comment]
Thanks for the clarification. What I do not fully understand is why we want to share the server_id among all the servers in a cluster. Do the servers share the connection states too? What does it try to solve here?

**Comment by maskit** [comment]
The servers may share the connection states too, but that doesn't matter because it's *stateless* reset token. A key point is that a server have to be able to generate consistent reset token even if the server lost state information, when the same connection_id is passed.

Technically speaking, using only a connection_id would work. However, in that case, anyone who knows the connection_id can reset the connection. So we need to make sure that tokens are difficult to guess and also consistent.

I'm not 100% sure, but this is my understanding.

**Comment by zizhong** [comment]
Hmm, consider a cluster of 2 boxes, A and B, suppose that a client has a QUIC connection with box A, then box A is down, and the connection gets to box B. If box A and box B doesn't share the connection states, box B should send a stateless reset token to the client.
If we use the same server_id for A and B, in an edge case, B might also have the same connection_id generated. Then box B can treat the incoming connection as an old connection and apply wrong states to the connection.
So IMO, if we can't share connection states or guarantee no duplicate connection_ids in the cluster, we cannot use the same server_id in the cluster.
I can definitely be wrong. xD

It's great to discuss this logic with you. Really helpful to me for a better understanding of QUIC.

**Comment by maskit** [comment]
> If we use the same server_id for A and B, in an edge case, B might also have the same connection_id generated. Then box B can treat the incoming connection as an old connection and apply wrong states to the connection.

Right, and it's not only about stateless reset but entire connection state management. That case will be a problem even if box A and B use different server_ids. If we cannot guarantee uniqueness of each connection ids in a cluster, we cannot make a cluster. We definitely need to think about this eventually. 

> So IMO, if we can't share connection states or guarantee no duplicate connection_ids in the cluster, we cannot use the same server_id in the cluster.

Because we need to guarantee connection id uniqueness in a cluster anyway, I think we can focus on state sharing here.

If states are shared in a cluster, there's no need to send a stateless reset as long as the state store is fine. If states are not shared in a cluster, connections on box A were gone when box A went down, so box B should send a stateless reset when it found an unknown connection id. In both cases, box A and B need to use the same server_id.

> It's great to discuss this logic with you. Really helpful to me for a better understanding of QUIC.

Same here :)
