### ISSUE TITLE
Address validation and HelloRetryRequest

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#2499]
#2345

**Comment by masaori335** [comment]
Leave this for a while until OpenSSL support APIs to send a cookie from server. Details in https://mta.openssl.org/pipermail/openssl-dev/2017-September/009713.html

**Comment by SolidWallOfCode** [comment]
If you want to leave it, mark it "WIP".

**Comment by masaori335** [comment]
## TODOs
- [x] SSL_stateless() support ( f9651e3 )
- [ ] Retry Packet support
- [ ] Generate Stateless Token
