### ISSUE TITLE
how to enable http2 ?

### ISSUE THREAD

**Issue by biao007h** [apache/trafficserver#2502]
i use ats7.1x and i had try "CONFIG proxy.config.http.server_ports STRING 80 443:proto=http2;http:ssl" ,but it doesn't work .so i  update openssl to version 1.0.2h and rebuild ats,but it still use http1.1.  i am sure my source support h2,  i used nginx  as reverse proxy before,and it works. so how can i enable h2 on ats?   my english is very poor ,i hope i had express what i need  ,thank you

**Comment by maskit** [comment]
How did you test it? With browsers, curl, openssl s_client? Does HTTP 1.1 with SSL (usual HTTPS) work?

**Comment by zizhong** [comment]
You can try to enable diag logs with the tag as such 'ssl|http'. Then you could easily spot what goes wrong.

**Comment by zwoop** [comment]
This belongs on the mailing list, and is not an Issue.

**Comment by biao007h** [comment]
@maskit all browsers got same issue, http1.1 is work fine,  sometimes chrome can switch to proto h2, but most of time  it just work in http1.1 .

**Comment by biao007h** [comment]
@zizhong  i had  enable diag logs with the tag as such 'ssl|http',but it got nothing about http2 infomation. how can i do more?
