### ISSUE TITLE
FIX THAT "ATS can't live with read-only /etc"

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#2505]
FRANKLY I HAVE ENOUGH OF THAT BROKEN BY DESIGN CRAP AFTER 5 YEARS OF COMPLAINING

[root@proxy:/var/log/trafficserver]$ nano /etc/trafficserver/ssl_multicert.config
[root@proxy:/var/log/trafficserver]$ cat *
[root@proxy:/var/log/trafficserver]$ systemctl reload trafficserver.service
[root@proxy:/var/log/trafficserver]$ cat *
[Sep 12 17:52:47.317] Manager {0x7f2581dea700} NOTE: [Rollback::openFile] Open of ssl_multicert.config failed: Read-only file system
[Sep 12 17:52:47.317] Manager {0x7f2581dea700} NOTE: [Rollback::internalUpdate] Unable to create new version of ssl_multicert.config : Read-only file system
[Sep 12 17:52:47.317] Manager {0x7f2581dea700} NOTE: [Rollback::checkForUserUpdate] Failed to roll changed user file ssl_multicert.config: System Call Error
[Sep 12 17:52:47.317] Manager {0x7f2581dea700} NOTE: User has changed config file ssl_multicert.config
[root@proxy:/var/log/trafficserver]$

FUCK IT

Am 02.09.2017 um 04:51 schrieb Miles Libbey:
> On Fri, Sep 1, 2017 at 6:40 PM, Reindl Harald <h.reindl@thelounge.net> wrote:
>>
>>
>> Am 01.09.2017 um 22:43 schrieb Alan Carroll:
>>>
>>> Is that addressed by
>>> https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html?highlight=records%20config#proxy-config-disable-configuration-modification
>>
>> sounds good - when is 8.0 planned to be released?
>
> It's also available in 7.  We do a terrible job of having the
> documentation match the actual version (eg why we default to a version
> that won't be released for quite some time is beyond me,

IT DON'T WORK

>> that you currently need a hard restart for config changes is a pain and will
>> be much more pain when you have to use letsencrypt with it's frequent
>> certificate updates in the next month after Chrome is starting to warn about
>> any site containing a from-tag without TLS
>
> They don't. Remap, SSL cert, and parents just need reloads, not
> restarts. Many record config values are also reloads

IT DON'T RELOAD because of readonly /etc

"/usr/bin/traffic_ctl config reload" don't do anything beause of this "[Rollback::Rollback] Config file is read-only : ssl_multicert.config" bullshit and i am currently working to implement letsencrypt for hundrets of domains which means that at every point in time certificates can be changed and a reload is needed and HARD RESTART IS A NO-GO

why in the world is that broken-by-design not fixed after 5 years of complaining or at least a option called "proxy.config.disable_configuration_modification" not tested at all?

is it really that hard to create a basic systemd unit and set the OS to redonly which should be the case for every network service in 2017 and test BASIC OPERATIONS?

ReadOnlyDirectories=/etc
ReadOnlyDirectories=/usr
ReadOnlyDirectories=/var/lib
ReadWriteDirectories=/etc/trafficserver/internal
ReadWriteDirectories=/etc/trafficserver/snapshots

[root@proxy:~]$ cat records.config | grep configuration
# Main threads configuration (worker threads). Also see configurations for   #
# parent proxy configuration     #
CONFIG proxy.config.disable_configuration_modification INT 1
CONFIG proxy.config.cluster.cluster_configuration STRING cluster.config

IT JUST DON'T WORK 
FUCK IT

**Comment by mingzym** [comment]
please set proxy.config.admin.number_config_bak = 0 and report back

**Comment by thelounge-zz** [comment]
[root@proxy:~]$ cat records.config | grep bak
CONFIG proxy.config.admin.number_config_bak INT 0

frankly why people suggesting options to try not just put " ReadOnlyDirectories=/etc" in their systemd units and try how far they come when configs are changed and "/usr/bin/traffic_ctl config reload" is supposed to work?

**Comment by mingzym** [comment]
we set trafficserver config directory write-able because we do need to write to the config files:
1, config backup
2, config updated with traffic ctl command
and by other means such as cluster sync, in some very old version

we do need it write-able if we want to provide that feature, and we do provide that feature by default, and by no means to disable it, so this is a required point

and by opensource, you always have another way to do it:
set the config directory outside of /etc/ in your case it is readonly, for example /var/lib/trafficserver is a good please to hold your changing files, you can definitely configure it from source.

any other solutions? patch is always welcome, just do it

**Comment by thelounge-zz** [comment]
* the reason i started to set it readonl was because of that backup-mess
* there is no reason to backup unconditional
* there is no reason to write when nobody uses "traffic ctl"
* there is no reason to refuse read a changed file because you can't rite to it
* there is no reason to have clustering enabled unconditional at all on a single machine
* that below MUST not happen
* frankly, i can't write a patch - write one and send me an invoice for the worktime

[root@proxy:/var/log/trafficserver]$ cat *
[root@proxy:/var/log/trafficserver]$ touch /etc/trafficserver/ssl_multicert.config
[root@proxy:/var/log/trafficserver]$ /usr/bin/traffic_ctl config reload
[root@proxy:/var/log/trafficserver]$ cat *
[Sep 14 11:16:28.625] Manager {0x7f8d3efea700} NOTE: [Rollback::openFile] Open of ssl_multicert.config failed: Read-only file system
[Sep 14 11:16:28.625] Manager {0x7f8d3efea700} NOTE: [Rollback::internalUpdate] Unable to create new version of ssl_multicert.config : Read-only file system
[Sep 14 11:16:28.625] Manager {0x7f8d3efea700} NOTE: [Alarms::signalAlarm] Skipping Alarm: '[TrafficManager] Configuration File Update Failed: Read-only file system'
[Sep 14 11:16:28.625] Manager {0x7f8d3efea700} NOTE: [Rollback::checkForUserUpdate] Failed to roll changed user file ssl_multicert.config: System Call Error
[Sep 14 11:16:28.625] Manager {0x7f8d3efea700} NOTE: User has changed config file ssl_multicert.config

**Comment by thelounge-zz** [comment]
wow - i seriously offer you money for solve that problem in 7.1.x and your reaction is "removed this from the 8.0.0 milestone 3 minutes ago"

**Comment by mingzym** [comment]
sorry, I help you to get some help from others, that someone may would like to help, if you like to fight anyone on this community, keep on. on myself, r u kidding??

**Comment by thelounge-zz** [comment]
it's not about fighting - i am just tired that every time when i raise this iusse people are coming with "try that config option" while in the past few years i even forgot which one i had already set

the point is: even with and traffic ctl "this is a required point" in case of writeable configdir is not true - it's just a implementation bug to completly refuse a soft reload - set some "Newbie" flag don't change that

**Comment by mingzym** [comment]
you just ignore my suggestion " reconfigure to use the writhe-able directory for config " and remove from ms8.0 is a good point in my committer view as no-one is now assigned to this issue and no-one  accept this is a issue to fix, leave it open is a good idea for now, add the Newbie Label to encourage someone fresh can work on it as it is a newbie project to TS. so you take that I am fight with you?? offering money is not our community style, instead you can always hire someone work on TS and join or not join this community.

btw, when I ask someone to help, I don't fuck them

**Comment by thelounge-zz** [comment]
i ignore it because it is set *by intention* and besides the security point that /etc is *not* something a software has ever to touch (the same for /usr) as i started with ATS set the folder readonly was done even before systemd to stop it write to files it should not do and making backups which it doe snot need to make leading in a complete mess in a clean and perfectly configured folder

**Comment by thelounge-zz** [comment]
CONFIG proxy.config.admin.number_config_bak INT 0

don't work at all after build a hack so that /etc/trafficserver is rsynced before start/reload from a well maintained there are still the backup files and that is a mess when you have "etckepper" for versioning running and the main reason i tried to get it way

[Service]
Type=simple
PermissionsStartOnly=true
ExecStartPre=/usr/bin/rsync -qtrpogEAX --delete-after /etc/trafficserver-managed/ /etc/trafficserver/
ExecStart=/usr/bin/traffic_cop
ExecReload=/usr/bin/rsync -qtrpogEAX /etc/trafficserver-managed/ /etc/trafficserver/
ExecReload=/usr/bin/traffic_ctl config reload
Restart=always
RestartSec=1
LimitNOFILE=1000000
LimitMEMLOCK=infinity
OOMScoreAdjust=-1000
TasksMax=30000
PrivateTmp=yes
CapabilityBoundingSet=CAP_CHOWN CAP_DAC_OVERRIDE CAP_IPC_LOCK CAP_KILL CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SETGID CAP_SETUID
ReadOnlyDirectories=/etc
ReadOnlyDirectories=/usr
ReadOnlyDirectories=/var/lib
ReadWriteDirectories=/etc/trafficserver

[root@proxy:~]$ ls /etc/trafficserver
insgesamt 348K
drwxrwxr-x 3 root ats 4,0K 2017-09-08 00:33 body_factory
drwxrwxr-x 2 root ats 4,0K 2017-09-08 00:33 internal
drwxrwxr-x 2 root ats 4,0K 2017-09-08 00:33 snapshots
drwxr-xr-x 2 root ats 4,0K 2017-09-13 13:12 ssl
-rw-rw-r-- 1 root ats   19 2017-09-08 00:33 trafficserver-release
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 ae_ua.config
-rw-r--r-- 1 ats  ats 2,1K 2017-09-14 23:21 cache.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 cluster.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 congestion.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 hosting.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 icp.config
-rw-r--r-- 1 ats  ats  455 2017-09-14 23:21 ip_allow.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 logging.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 log_hosts.config
-rw-rw-r-- 1 root ats  15K 2013-08-10 20:09 logs_xml.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 metrics.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 parent.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 plugin.config
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 prefetch.config
-rw-r--r-- 1 ats  ats  18K 2017-09-14 23:21 records.config
-rw-r--r-- 1 ats  ats 100K 2017-09-14 23:21 remap.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 socks.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 splitdns.config
-rw-r--r-- 1 ats  ats  22K 2017-09-14 23:21 ssl_multicert.config
-rw-r--r-- 1 ats  ats  151 2017-09-14 23:21 storage.config
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 update.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 vaddrs.config
-rw-r--r-- 1 ats  ats    0 2017-09-14 23:21 volume.config
-rw-rw-r-- 1 root ats 2,1K 2016-12-21 15:23 cache.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 cluster.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 congestion.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 hosting.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 icp.config_1
-rw-rw-r-- 1 root ats  455 2013-08-10 20:09 ip_allow.config_1
-rw-rw-r-- 1 root ats    0 2016-12-08 22:25 logging.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 log_hosts.config_1
-rw-rw-r-- 1 root ats    0 2016-12-08 22:25 metrics.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 parent.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 plugin.config_1
-rw-rw-r-- 1 root ats  18K 2017-08-21 16:28 records.config_1
-rw-rw-r-- 1 root ats 100K 2017-09-14 22:45 remap.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 socks.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 splitdns.config_1
-rw-rw-r-- 1 root ats  22K 2017-09-14 23:20 ssl_multicert.config_1
-rw-rw-r-- 1 root ats  151 2013-08-10 20:09 storage.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 vaddrs.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 volume.config_1
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 wpad.dat
-rw-rw-r-- 1 root ats    0 2013-08-10 20:09 proxy.pac

**Comment by ema** [comment]
@randall your patch (84ca1657) does **fix disable_configuration_modification**. It also makes it possible to run trafficserver with the systemd setting ReadOnlyDirectories=/etc. Please consider merging it and backporting it to 8.x.

**Comment by zwoop** [comment]
I'm working on getting rid of the Rollback feature, so closing this for now since there are more specific Issues filed on the topic.

**Comment by thelounge-zz** [comment]
no diea why "work in progress" justifies closing this after so many years and why a *wokring* config option to diable that bullshit is that hard

**Comment by zwoop** [comment]
You are of course more than welcome to produce such an easy fix for that bullshit yourself.

As been documented through the many years of Traffic Server as both commercial and free software, being able to write and create files in etc/ is a critical piece of code and functionality. It's been deeply nested in the design and implementation of ATS since inception. We've since made read-only etc/ achievable by fixing and eliminating various pieces that depends on this behavior. The option to stop writing the config files was added years ago (and in 9.0.0 will be the only way to run ATS). There's now one (known) functionality that I'm working on to eliminate, and the patch is rather extensive and needs a lot of testing before I can merge it.

But of course, you are just too fucking lazy to actually look at any of this code or god forbid, contribute to it. Keep up the great work please...

**Comment by thelounge-zz** [comment]
OK, i didn't expect the whole codebase to be spaghetti code where writing and versioning is spread all over the code so that "CONFIG proxy.config.disable_configuration_modification INT 1" is really respected and the function writing the config juest returns void or false....

**Comment by thelounge-zz** [comment]
i needed to solve that anyways because after implement letsencrypt and push updated certificates all day long from the backend servers hard restart the proxy dozens of times is a no-go, just place your real config somewhere else and say thank you to systemd which can fire up rsync before reload/restart/start

works at least for certificates, cipher options in recods.config still need a hard restart to get active

[root@testserver:~]$ cat /usr/lib/systemd/system/trafficserver.service
[Unit]
Description=Apache Traffic Server
After=dnsmasq.service

[Service]
Type=simple
PermissionsStartOnly=true
ExecStartPre=/usr/bin/rsync -qtrpogEAX --delete-after /etc/trafficserver-managed/ /etc/trafficserver/
ExecStart=/usr/bin/traffic_manager --nosyslog
ExecReload=/usr/bin/rsync -qtrpogEAX /etc/trafficserver-managed/ /etc/trafficserver/
ExecReload=/usr/bin/traffic_ctl config reload
ExecStopPost=/usr/bin/rsync -qtrpogEAX --delete-after /etc/trafficserver-managed/ /etc/trafficserver/
SuccessExitStatus=15
Restart=always
RestartSec=1

LimitNOFILE=1000000
LimitMEMLOCK=infinity
TasksMax=30000

CapabilityBoundingSet=CAP_CHOWN CAP_DAC_OVERRIDE CAP_IPC_LOCK CAP_KILL CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_SETGID CAP_SETUID
MemoryDenyWriteExecute=yes
PrivateTmp=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_LOCAL AF_UNIX AF_NETLINK
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @mount @obsolete @reboot @swap

ProtectSystem=full
ReadOnlyPaths=/var/lib
ReadWritePaths=/etc/trafficserver

**Comment by zwoop** [comment]
Can you test https://github.com/apache/trafficserver/pull/5603 and see that it doesn't write things to  .../etc ? There might be other things touch ../etc, but this should a least not let it write configurations. This patch is for master.

**Comment by thelounge-zz** [comment]
sorry, ATM i can't touch the ATS setup at all because of millions other tasks and all my prayers in context of ATS are that somewehere in time a release past 8.0.1 is useable in production while solve at the same time broken 'ab' to TLS

see https://github.com/apache/trafficserver/issues/4921#issuecomment-481914551

while 8.x obviously fixes some header_rewrite bugs and makes the compression plugin useable also with brotli support to move compression away from the backend servers the whole shape don't make me terrible happy
