### ISSUE TITLE
Lua metrics not working

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#2511]
I think we broke Lua metrics at some point, in 7.1.x and master, I don't see any of the synthetic metrics that Lua ought to produce.

**Comment by shukitchan** [comment]
I think it is related to "cluster". If we remove all cluster related stuff in metrics.config, it seems to be fine. Let me submit something in a couple days

**Comment by shukitchan** [comment]
Actually it is already removed from metrics.config. Did you still see this? Did you see any error in any of the log files?

**Comment by zwoop** [comment]
Well, I think I overstated the severity of this. I think the "avg" and "10s" etc. metrics are always zero :-..

**Comment by shukitchan** [comment]
@jpeach 
i think it never worked. According to this line - https://github.com/apache/trafficserver/blob/master/cmd/traffic_manager/metrics.cc#L319 , the evaluation is once and done. Right? It never redo the fetch of the time dynamically.

**Comment by jpeach** [comment]
https://github.com/apache/trafficserver/blob/master/cmd/traffic_manager/metrics.cc#L362

**Comment by vrpano** [comment]
Yup. I missed that. So it does get evaluated constantly. Not too sure why now() is still always the same. Still debugging.

**Comment by shukitchan** [comment]
Yup. I missed that. So it does get evaluated constantly. Not too sure why now() is still always the same. Still debugging.

**Comment by shukitchan** [comment]
Ok. I have some time now to debug. 
Here is another problem 
https://github.com/apache/trafficserver/blob/master/lib/bindings/bindings.cc#L190-L200

So @jpeach, because the "metrics.now.msec" was previously set, it can't be set again since the the current value is no longer nil.

**Comment by zwoop** [comment]
Sounds like we can close this now.
