### ISSUE TITLE
IP CIDR subnet mask logging

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#2535]
We'd like to have a way to mask an IP address in the ATS logs to it's CIDR subnet. For instance,
perhaps logging a user's specific IP gives away too much personal information, but,
logging their IPv4 /24 subnet would sufficiently mask their identity, while still providing useful network troubleshooting information.

[Log field slicing](https://docs.trafficserver.apache.org/en/latest/admin-guide/logging/formatting.en.html#log-field-slicing) does not apply to IP addresses as 'Slice notation only applies to a log field that is of type string and can not be applied to IPs or timestamp which are converted to string from integer.'

Perhaps we could have a similar notation that allows the administrator to indicate the IP should be
logged as the specified subnet mask. It would be nice to allow the administrator to specify a different subnet mask for IPv6 than IPv4. Not only would many subnets not make sense for both (eg /120 would be an invalid v4 subnet); but, practically, a v6 /24 would likely encompass too many AS to be useful in network troubleshooting, while a v4 /24 would likely be sufficient.

For instance, '<%chi[v4/24|v6/48]>' could tell ATS to log 1.2.3.0/24 when the client IP is 1.2.3.4 and 
1:2:3:0:0:0:0:0/48 when the client IP is 1:2:3:4:5:6:7:8.  Suggestions welcome for syntax!

**Comment by mlibbey** [comment]
Still want this.

**Comment by zwoop** [comment]
Resolved with f14efb4
