### ISSUE TITLE
header rewrite plugin cannot add some HTTP headers, like `Alt-Svc: quic=“:443”;v=“32,33”`

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#2537]
The config line is like `add-header Alt-Svc quic=“:443”;v=“32,33”`

The root cause is in `Parser::Parser()` of `parser.cc`, it doesn't allow escaping double quotes.

**Comment by mlibbey** [comment]
In 7+, can use
`add-header Alt-Svc "quic=\":443\"; v=\"32,33\""`

**Comment by zizhong** [comment]
Great! Thanks @mlibbey
