### ISSUE TITLE
Initialization takes over 10sec 

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#2565]
It looks like something stops ATS over 10 seconds on initialization. I saw this only on master branch.

```
(lldb) run
Process 85273 launched: '/Users/masaori/opt/ats-master/bin/traffic_server' (x86_64)
traffic_server: using root directory '/Users/masaori/opt/ats-master'
2017-09-25 11:21:33.717490+0900 traffic_server[85273:7383362] NOTE: --- traffic_server Starting ---
2017-09-25 11:21:33.717621+0900 traffic_server[85273:7383362] NOTE: traffic_server Version: Apache Traffic Server - traffic_server - 8.0.0 - (build # 092511 on Sep 25 2017 at 11:11:35)
[Sep 25 11:21:48.748] Server {0x7fffcb17d3c0} DEBUG: <SSLConfig.cc:397 (freeCTXmap)> (ssl) freeing CTX Map
```

**Comment by masaori335** [comment]
This consumes over 10 secs.
https://github.com/apache/trafficserver/blob/c1a656e372d2577fdf63d34769a898acd1ab804f/proxy/Main.cc#L1710

**Comment by masaori335** [comment]
All network interfaces are checked in the constructor of `Machine`, and `getnameinfo` takes few seconds with some of them.
https://github.com/apache/trafficserver/blob/c1a656e372d2577fdf63d34769a898acd1ab804f/iocore/utils/Machine.cc#L178

**Comment by zwoop** [comment]
Hmmm, I'm not seeing this on my VMs ... What platform are you seeing this on?

**Comment by maskit** [comment]
We saw this on macOS.

**Comment by masaori335** [comment]
The `getnameinfo` is added for self-detection. ( https://github.com/apache/trafficserver/commit/7530f775f603e055eb8cfab2a4d6fdcf8685d3b4 ) Could we mitigate this issue by skipping this code when `proxy.config.http.parent_proxy_routing_enable` is `0` ?

/cc @jrushford

**Comment by jrushford** [comment]
?It probably could but could this be a problem with your dns configuration?

________________________________

**Comment by masaori335** [comment]
@jrushford I'm not sure this will be problem with dns. Could you check the PR?

**Comment by masaori335** [comment]
@scw00 do you still see this issue?

**Comment by scw00** [comment]
I haven't saw this issue for a while. Close it for now.
