### ISSUE TITLE
Remove entry from QUICNetVConnection table when close QUICNetVConnection

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#2585]
There're `Connection ID` - `QUICNetVConnection` table on `QUICPacketHandler`. Currently we don't remove the entry from this table when `QUICNetVConnection` is closed or freed.

**Comment by masaori335** [comment]
We should also remove (or change) an entry which is created by Client Initial packet, when TS sends Server Cleartext packet with new value for the Connection ID.

**Comment by maskit** [comment]
Currently there's no way to *remove* entries from the table because of ts/Map interface.

For now, put `nullptr` to indicate the connection is already gone.
0551bfdb9673b71cbfd64c5fb59c502c82ee60b4

**Comment by masaori335** [comment]
#3013 will also fix this
