### ISSUE TITLE
Origin connection retry backoff

### ISSUE THREAD

**Issue by d2r** [apache/trafficserver#2591]
As an origin server provider, I would like ATS to less aggressively retry connections, so that my service does not suffer from amplification.

The default maximum retries for a host that is not marked dead is `3`. However, we currently retry as fast as possible. It might be better to use a bounded exponential back-off scheme in order to avoid making things much worse for the origin in such cases.

**Comment by d2r** [comment]
This is still an issue.

**Comment by d2r** [comment]
This issue is still valid.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
