### ISSUE TITLE
Pristine Request support

### ISSUE THREAD

**Issue by SolidWallOfCode** [apache/trafficserver#2594]
As the Layer 7 routing project moves forward, an issue that comes up repeatedly is the ability to recover the *exact* request of the user agent to be examined or forwarded. Currently this is effectively impossible to recover after remap because remap modified the client request. In this forces L7 routing to operate pre-remap where critical information is not available (such as the actual cache key used for the request). 

I think the best approach to deal with this is to be able to preserve the "pristine" user agent request, somewhat similarly to the pristine host header. If this pristine request were available for examination or forwarding for plugins, L7 related operations could then easily be done post-remap making them simpler, more robust, and more performant.

**Comment by ywkaras** [comment]
OK I will start in on this.

**Comment by ywkaras** [comment]
So do we want to add a new plugin API function?  Like TSHttPTxnPristineClientReqGet() ?  For which reading functions like TSMimeHdrFieldGet() would work, but modifying functions like TSMimeHdrFieldCreate() would not?

**Comment by bryancall** [comment]
@SolidWallOfCode Shouldn't the cache key be the origin URL?

**Comment by SolidWallOfCode** [comment]
Yes, it should. That's the point of this work. Now CARP uses the pre-remap URL precisely because it has to work with the pristine header. If that were preserved, CARP could easily operate post-remap and use the actual origin URL.
