### ISSUE TITLE
Log QUIC Connection ID

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#2616]
It's useful for QUIC Connection ID is logged. In the interop session, people checks what happened with CID.

**Comment by maskit** [comment]
IIRC, we recently added a log field for ATS connection id (not QUIC connection id).

**Comment by maskit** [comment]
https://github.com/apache/trafficserver/pull/2508

**Comment by masaori335** [comment]
`ccid` looks suitable log field. Let's make `HQClientSession::connection_id()` returns QUIC Connection ID.

**Comment by masaori335** [comment]
We should also log CID when QUICError is happened.

**Comment by maskit** [comment]
> We should also log CID when QUICError is happened.

As far as I know all QUICErrors should be logged (right before sending CONNECTION_CLOSE or RST_STREAM). Probably only we need to do is adding Connection ID to `DebugQUICStream`.

**Comment by masaori335** [comment]
Done by https://github.com/apache/trafficserver/commit/3e3938fc972276cb82dffd84bda421fc4bf7185c.
