### ISSUE TITLE
Allocator.h, ink_resource.cc unconditionally imports execinfo.h

### ISSUE THREAD

**Issue by jbergstroem** [apache/trafficserver#2624]
Some systems doesn't come bundled with `execinfo.h`. There is a [check in `configure.ac` to cater for this](https://github.com/apache/trafficserver/blob/master/configure.ac#L1255..L1264), but these files still seems to unconditionally lean on `execinfo.h`: [`Allocator.h`](https://github.com/apache/trafficserver/blob/master/lib/ts/Allocator.h#L48) and [`ink_resource.cc`](https://github.com/apache/trafficserver/blob/master/lib/ts/ink_resource.cc#L27).

**Comment by bryancall** [comment]
@jbergstroem What platform are you running this on?

**Comment by jbergstroem** [comment]
Ouf, long time ago. Best guess old version of Alpine Linux, Illumos or FreeBSD. I'll close and reopen once I can reproduce with sufficient info.
