### ISSUE TITLE
Regex_Revalidate Plugin Existing Invalidations Re-Triggered Each Time a New Invalidation is Added

### ISSUE THREAD

**Issue by ryandurfey** [apache/trafficserver#2651]
Regex_Revalidate Plugin Existing Invalidations Re-Triggered Each Time a New Invalidation is Added

Scenario - 
1. Add an invalidation to the regex_revalidate.conf with an expiration of 30 days
2. Request comes in to cache for a url and url is revalidate at the origin
3. Add a second unrelated  invalidation to the regex_revalidate.conf
4. First invalidation is re-triggered and revalidates file again (as long as it is within the 30 days)
5. This recurs for every new invalidation add to the regex_revalidate.conf

regex_revalidate.conf only contains a regex expression and an expiration for each record.  It doesn't contain a submit date for each record so it is impossible to tell from the data in the file whether an invalidation is new or old when a new file is loaded.

**Comment by chassell** [comment]
Have a fix for master I'm putting up today.

**Comment by chassell** [comment]
Okay ... a now "today" ...

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by chassell** [comment]
The later versions of this plugin (7.x) appear to function correctly ... if not over restarts.

**Comment by ezelkow1** [comment]
Tested here and regex_reval does look good for all instances (except the restart case when the reval list is lost of course)
