### ISSUE TITLE
Crash when scheduled events are processed after closing QUICNetVC

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#2674]
Since events for QUICNetVConnection are scheduled without checking the vc state and the vc is freed in event handlers, it crashes when the QUICNetVC is freed and events for the vc are still in event queues.

Like other NetVConnections, it has to be done by NetHandler (check the vc state and choose whether to call the vc with an event or initiate closing the vc).

**Comment by maskit** [comment]
@oknet I think this is a cause of crashes (BAD_ACCESS) that happen random places on QUIC transactions, it would relate your proposal for QUICNetHandler. What do you think? Does it make sense?

**Comment by oknet** [comment]
The `QUICNetVC` is a request or task over the QUIC Connection. The `NetHandler` is a processor to handle it.

The `QUICConnection` is a request or task over the UDP Connection. The `QUICNetHandler` is a processor to handle it.

The `Processor` and the `Request` are base components of sub system.

**Comment by maskit** [comment]
> The QUICConnection is a request or task over the UDP Connection. The QUICNetHandler is a processor to handle it.

This is confusing. `QUICConnection` is *currently* not something like that. I don't against using the name for descriptor(?) in your proposal and renaming the current classes, but please don't mix current design and proposed design since the crashes happen on current design.

I wanted to know whether invoking `QUICNetVConnection`'s functions from some other class (NetHandler, QUICNetHandler, whatever) on events to prevent the crashes makes sense or not.

If I understand correctly, `UnixNetVConnection` is called from `NetHandler` on read /write events, and this mechanism prevents processing events on closed NetVConnections. Is this correct?

Is this model still alive on your proposal?

**Comment by oknet** [comment]
Sorry about that.

yes, you should assign a manager for QUICNetVConnection. Only the manager can invoking the `QUICNetVConnection`'s functions.

Once the QUICNetVConnection is marked closed, it is deallocated by the manager.

**Comment by oknet** [comment]
A `Request` has a member `cancelled` or `closed` indicated the status of it. once it is cancelled or closed, it is deallocated by the `Processor`.

A `Request` has a method `free()` to deallocate itself. once it is assigned to a `Processor`, it is the `Processor`'s responsibility to deallocate it by calling `free()`. Otherwise it is the responsibility of the `Request`'s holder to deallocate it.

**Comment by oknet** [comment]
I write a design doc for the `NetHandler`. Please refer to the comment in the #2503 .

These classes are type of `Request`:

- Event
- UnixNetVConnection

These are type of `Processor`:

- EThread
- NetHandler

**Comment by maskit** [comment]
Aha, thanks for the explanation. Now I'm starting to get it.

I may not use `NetHandler` for now to prevent the crashes quickly, but I'm looking forward to your PR for NetHandler integration. 😄

**Comment by maskit** [comment]
I might be able to write some workaround but I just removed `free` for now. This need to be figured out with QUICNetHandler. Also, even if we introduced QUICNetHandler, some of timing issues will remain because we schedule events for streams too so that they can be processed concurrently.

**Comment by oknet** [comment]
To operate on the `QUICNetVConnection::_packet_recv_queue`, it does not get the mutex of QUICNetVC first. It makes the UDPPacket may be lost from the queue.

**Comment by maskit** [comment]
OK, that's possible. We didn't care much about thread safety because we were going to replace containers with something (TBB, ink_atomiclist, etc.).

**Comment by masaori335** [comment]
At QUIC Hackathon in Tokyo, @oknet's new QUICPollCont and QUICNetHandler will fix this.

**Comment by bryancall** [comment]
@maskit Is this still an issue?

**Comment by maskit** [comment]
yes, please keep this open.

**Comment by maskit** [comment]
This is not going to be completely addressed on 9.0.0 release, but ATS doesn't crash now because QUICNetVC is intentionally leaked as a workaround.

**Comment by bryancall** [comment]
@maskit Is this still an issue?

**Comment by maskit** [comment]
Closing this since I don't see crashes because of events for closed QUIC connections. It would be nice to have another issue for memory leak.
