### ISSUE TITLE
no_dns_just_forward_to_parent is broken in 7.1.1

### ISSUE THREAD

**Issue by Tchinmai7** [apache/trafficserver#2695]
--request--
curl  -vv http://www.google.com -o /dev/null 
(google.com resolves to the proxy IP)

--records.config--
CONFIG proxy.config.http.no_dns_just_forward_to_parent INT 1

--diags.log--
```
[Oct 21 08:43:35.530] Server {0x7f679d7c4700} DEBUG: <HttpSM.cc:4193 (do_hostdb_lookup)> (http_seq) [HttpSM::do_hostdb_lookup] Doing DNS Lookup
[Oct 21 08:43:35.530] Server {0x7f679d7c4700} DEBUG: <HttpTransact.cc:8415 (ink_cluster_time)> (http_trans) [ink_cluster_time] local: 1508575415, highest_delta: 0, cluster: 1508575415
[Oct 21 08:43:35.530] Server {0x7f679d7c4700} DEBUG: <HttpTransact.cc:1640 (OSDNSLookup)> (http_trans) [4] [HttpTransact::OSDNSLookup] This was attempt 0
[Oct 21 08:43:35.530] Server {0x7f679d7c4700} DEBUG: <HttpTransact.cc:1702 (OSDNSLookup)> (http_seq) [4] [HttpTransact::OSDNSLookup] DNS Lookup successful
[Oct 21 08:43:35.530] Server {0x7f679d7c4700} DEBUG: <HttpTransact.cc:1741 (OSDNSLookup)> (http_trans) [4] [OSDNSLookup] DNS lookup for O.S. successful IP: 216.58.207.164
[Oct 21 08:43:35.530] Server {0x7f679d7c4700} DEBUG: <HttpTransact.cc:1848 (HandleRequestAuthorized)> (http_trans) Next action SM_ACTION_API_OS_DNS; HttpTransact::DecideCacheLookup

```

I don't understand why TrafficServer is doing DNS lookups when explicitly instructed not to do so. This behavior was not seen in 6.2.1. Has anything changed?

**Comment by Tchinmai7** [comment]
Any update on this?

**Comment by Tchinmai7** [comment]
more logs
`
[Nov 16 18:14:44.819] Server {0x7f6c63ffe700} DEBUG: <DNS.cc:1091 (getby)> (dns) received query www.google.com type = 1, timeout = 0
[Nov 16 18:14:44.819] Server {0x7f6c68a61700} DEBUG: <DNS.cc:1057 (mainEvent)> (dns) enqueing query www.google.com
[Nov 16 18:14:44.819] Server {0x7f6c68a61700} DEBUG: <DNS.cc:1063 (mainEvent)> (dns) adding first to collapsing queue
[Nov 16 18:14:44.819] Server {0x7f6c68a61700} DEBUG: <DNS.cc:978 (write_dns_event)> (dns) send query (qtype=1) for www.google.com to fd 42
[Nov 16 18:14:44.819] Server {0x7f6c68a61700} DEBUG: <DNS.cc:1010 (write_dns_event)> (dns) sent qname = www.google.com, id = 47148, nameserver = 1
[Nov 16 18:14:44.819] Server {0x7f6c68a61700} DEBUG: <P_DNSProcessor.h:239 (sent_one)> (dns) sent_one: failover_number for resolver 1 is 1
[Nov 16 18:14:44.874] Server {0x7f6c68a61700} DEBUG: <DNS.cc:759 (recv_dns)> (dns) received packet size = 184
[Nov 16 18:14:44.874] Server {0x7f6c68a61700} DEBUG: <DNS.cc:761 (recv_dns)> (dns) round-robin: nameserver 1 DNS response code = 12
[Nov 16 18:14:44.874] Server {0x7f6c68a61700} DEBUG: <DNS.cc:1560 (dns_process)> (dns) received A name = www.google.com
[Nov 16 18:14:44.874] Server {0x7f6c68a61700} DEBUG: <DNS.cc:1180 (dns_result)> (dns) SUCCESS result for www.google.com = 172.217.18.4 retry 0
[Nov 16 18:14:44.874] Server {0x7f6c63ffe700} DEBUG: <DNS.cc:1268 (postEvent)> (dns) called back continuation for www.google.com
`

**Comment by vmamidi** [comment]
this should be working in 8.0.

**Comment by vmamidi** [comment]
Closing this issue. Please reopen if you see this issue again.
