### ISSUE TITLE
Failure to clean up nameserver connection when only one nameserver defined

### ISSUE THREAD

**Issue by reveller** [apache/trafficserver#2700]
For systems configured with a single nameserver, ATS will be processing requests normally, then all of a sudden clients start receiving an ‘Unknown host’ response and the ATS logs fill with:
 
[Oct 20 05:21:20.438] Server {0x2b1690201700} WARNING: failover: connection to DNS server 192.168.192.10 lost, retrying
[Oct 20 05:21:20.449] Server {0x2b1690201700} WARNING: failover: connection to DNS server 192.168.192.10 lost, retrying
[Oct 20 05:21:20.459] Server {0x2b1690201700} WARNING: failover: connection to DNS server 192.168.192.10 lost, retrying
 
(thousands and thousands of lines)

When there's more than one nameserver, open_con is called which tries to re/open the connection and recursively calls failover if that fails:
 
    failover() -> open_con() -> failover()
 
However, when there's only one nameserver defined, failover() just prints a message and doesn't do any connection maintenance.
 
If its connection goes bad, the original connection is never torn down so a new connection can be created.

**Comment by zwoop** [comment]
@reveller If you make a PR, you don't have to file an Issue as well. Only file Issues if you don't have a fix, or plan to have a fix "soon".
