### ISSUE TITLE
missing support for RSA/ECDSA dual stack

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#2722]
for httpd it is no problem to have "SSLCertificateFile" twice, one pointing to the RSA and one to the ECDSA certificate and so mordern clients negotiate ECDSA (much faster handshakes) while older clients still can use RSA

see here for httpd and nginx versus the error messages at bottom in case of Trafficserver
https://blog.joelj.org/dual-rsaecdsa-certificates-in-apache-2-4/
https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/

[root@testserver:/var/log/trafficserver]$ cat /etc/trafficserver/ssl_multicert.config
ssl_cert_name=/var/lib/letsencrypt/certs/rhsoft.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/uploadprogress.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/mailadmin.conf_rsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/uploadprogress.conf_rsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/0000-default.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/contentlounge.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/rhsoft.conf_rsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/webmail.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/contentlounge.conf_rsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/0000-default.conf_rsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/corecms.conf_rsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/afi.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/corecms.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/mailadmin.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/afi.conf_rsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/webmail.conf_rsa.pem

[Oct 29 18:01:50.921] Server {0x154f5b4d1cc0} NOTE: loading SSL certificate configuration from /etc/trafficserver/ssl_multicert.config
[Oct 29 18:01:50.944] Server {0x154f5b4d1cc0} WARNING: previously indexed 'uploadprogress.testserver.rhsoft.net' with SSL_CTX 0x2, cannot index it with SSL_CTX #4 now
[Oct 29 18:01:50.961] Server {0x154f5b4d1cc0} WARNING: previously indexed 'rhsoft.testserver.rhsoft.net' with SSL_CTX (nil), cannot index it with SSL_CTX #6 now
[Oct 29 18:01:50.961] Server {0x154f5b4d1cc0} WARNING: previously indexed 'testserver.rhsoft.net' with SSL_CTX 0x1, cannot index it with SSL_CTX #6 now
[Oct 29 18:01:50.972] Server {0x154f5b4d1cc0} WARNING: previously indexed 'contentlounge.testserver.rhsoft.net' with SSL_CTX 0x5, cannot index it with SSL_CTX #7 now
[Oct 29 18:01:50.978] Server {0x154f5b4d1cc0} WARNING: previously indexed 'default.testserver.rhsoft.net' with SSL_CTX 0x4, cannot index it with SSL_CTX #7 now
[Oct 29 18:01:50.995] Server {0x154f5b4d1cc0} WARNING: previously indexed 'corecms.testserver.rhsoft.net' with SSL_CTX 0x7, cannot index it with SSL_CTX #9 now
[Oct 29 18:01:51.001] Server {0x154f5b4d1cc0} WARNING: previously indexed 'mailadmin.testserver.rhsoft.net' with SSL_CTX 0x3, cannot index it with SSL_CTX #9 now
[Oct 29 18:01:51.006] Server {0x154f5b4d1cc0} WARNING: previously indexed 'afi.testserver.rhsoft.net' with SSL_CTX 0x8, cannot index it with SSL_CTX #9 now
[Oct 29 18:01:51.012] Server {0x154f5b4d1cc0} WARNING: previously indexed 'webmail.testserver.rhsoft.net' with SSL_CTX 0x6, cannot index it with SSL_CTX #9 now

**Comment by mlibbey** [comment]
The [ssl_multicert.config doc](https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/ssl_multicert.config.en.html) says this should work, but, not in the format you have. Can you try
ssl_cert_name=FILENAME[,FILENAME …]
eg,
ssl_cert_name=/var/lib/letsencrypt/certs/rhsoft.conf_ecdsa.pem,/var/lib/letsencrypt/certs/rhsoft.conf_rsa.pem

**Comment by thelounge-zz** [comment]
well, that makes things complicated when you push letsencrypt generated certificate files from a dozen backendservers to the trafficserver machine - need to figure out how to get that sorted

ats really should support just configure a directory and figure out the rest by CN/SAN of the certificate files

**Comment by thelounge-zz** [comment]
according to "Calomel SSL Validation" (firefox extension) it indeed seems to work and also "ab" is using TLSv1.2,ECDHE-ECDSA-AES128-GCM-SHA256,256,128 but that annyoing warnings are still in the logs and when you have hundrets of certificates that becomes a problem because it burries real errors

[root@testserver:/var/log/trafficserver]$ cat /etc/trafficserver/ssl_multicert.config
ssl_cert_name=/var/lib/letsencrypt/certs/mailadmin.conf_rsa.pem,/var/lib/letsencrypt/certs/mailadmin.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/uploadprogress.conf_rsa.pem,/var/lib/letsencrypt/certs/uploadprogress.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/rhsoft.conf_rsa.pem,/var/lib/letsencrypt/certs/rhsoft.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/contentlounge.conf_rsa.pem,/var/lib/letsencrypt/certs/contentlounge.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/0000-default.conf_rsa.pem,/var/lib/letsencrypt/certs/0000-default.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/corecms.conf_rsa.pem,/var/lib/letsencrypt/certs/corecms.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/afi.conf_rsa.pem,/var/lib/letsencrypt/certs/afi.conf_ecdsa.pem
ssl_cert_name=/var/lib/letsencrypt/certs/webmail.conf_rsa.pem,/var/lib/letsencrypt/certs/webmail.conf_ecdsa.pem

[root@testserver:/var/log/trafficserver]$ cat diags.log
[Oct 29 22:10:37.837] Server {0x146ff1d20cc0} STATUS: opened /var/log/trafficserver/diags.log
[Oct 29 22:10:37.837] Server {0x146ff1d20cc0} NOTE: updated diags config
[Oct 29 22:10:37.840] Server {0x146ff1d20cc0} NOTE: cache clustering disabled
[Oct 29 22:10:37.842] Server {0x146ff1d20cc0} NOTE: ip_allow.config updated, reloading
[Oct 29 22:10:37.844] Server {0x146ff1d20cc0} NOTE: cache clustering disabled
[Oct 29 22:10:37.845] Server {0x146ff1d20cc0} NOTE: logging initialized[3], logging_mode = 1
[Oct 29 22:10:37.846] Server {0x146ff1d20cc0} NOTE: loading SSL certificate configuration from /etc/trafficserver/ssl_multicert.config
[Oct 29 22:10:37.852] Server {0x146ff1d20cc0} WARNING: previously indexed 'mailadmin.testserver.rhsoft.net' with SSL_CTX (nil), cannot index it with SSL_CTX #1 now
[Oct 29 22:10:37.860] Server {0x146ff1d20cc0} WARNING: previously indexed 'uploadprogress.testserver.rhsoft.net' with SSL_CTX 0x1, cannot index it with SSL_CTX #2 now
[Oct 29 22:10:37.866] Server {0x146ff1d20cc0} WARNING: previously indexed 'rhsoft.testserver.rhsoft.net' with SSL_CTX 0x2, cannot index it with SSL_CTX #4 now
[Oct 29 22:10:37.866] Server {0x146ff1d20cc0} WARNING: previously indexed 'testserver.rhsoft.net' with SSL_CTX 0x3, cannot index it with SSL_CTX #4 now
[Oct 29 22:10:37.873] Server {0x146ff1d20cc0} WARNING: previously indexed 'contentlounge.testserver.rhsoft.net' with SSL_CTX 0x4, cannot index it with SSL_CTX #5 now
[Oct 29 22:10:37.878] Server {0x146ff1d20cc0} WARNING: previously indexed 'default.testserver.rhsoft.net' with SSL_CTX 0x5, cannot index it with SSL_CTX #6 now
[Oct 29 22:10:37.885] Server {0x146ff1d20cc0} WARNING: previously indexed 'corecms.testserver.rhsoft.net' with SSL_CTX 0x6, cannot index it with SSL_CTX #7 now
[Oct 29 22:10:37.891] Server {0x146ff1d20cc0} WARNING: previously indexed 'afi.testserver.rhsoft.net' with SSL_CTX 0x7, cannot index it with SSL_CTX #8 now
[Oct 29 22:10:37.897] Server {0x146ff1d20cc0} WARNING: previously indexed 'webmail.testserver.rhsoft.net' with SSL_CTX 0x8, cannot index it with SSL_CTX #9 now
[Oct 29 22:10:37.910] Server {0x146ff1d20cc0} NOTE: traffic server running
[Oct 29 22:10:37.935] Server {0x146fecb0c700} NOTE: cache enabled
[root@testserver:/var/log/trafficserver]$

**Comment by mlibbey** [comment]
bleck. does that mean the first version worked, but just gave log errors?

**Comment by thelounge-zz** [comment]
no, the first version did not work either, only RSA negotiated but when you play around with the config and the warnings still appear unchanged you don't expect it to work while the second one technically does and only the logging is wrong

**Comment by shinrich** [comment]
Yes, we need to clean up the previously indexed messages.  They do clutter, and particularly so in the dual certificate situation.

The comma separated form should work.  It did at least last time I tried it.  You need to run with at least openssl-1.0.2.

I suppose there is enough info in the cert files that ATS could line things up (assuming the private keys were in the same file).  Having an explicit separate config seems safer though perhaps more configing work.

**Comment by thelounge-zz** [comment]
> The comma separated form should work

frankly i have alread confirmed that above:

according to "Calomel SSL Validation" (firefox extension) it indeed seems to work and also "ab" is using TLSv1.2,ECDHE-ECDSA-AES128-GCM-SHA256,256,128 but that annyoing warnings are still in the logs and when you have hundrets of certificates that becomes a problem because it burries real errors

**Comment by thelounge-zz** [comment]
and it is terrible broken at all!

ERR_SSL_PROTOCOL_ERROR

* LineageOS stock browser
* iphone
* opera android

Firefox Desktop/Android as well as Safari on OSX desktop works, httpd does not have a single problem with a RSA/ECDSA dual configuration but Trafficserver is just a lottery

< ssl_cert_name=www.mrandmrsdog.at.conf_rsa.pem,www.mrandmrsdog.at.conf_ecdsa.pem
> ssl_cert_name=www.mrandmrsdog.at.conf_rsa.pem

**Comment by thelounge-zz** [comment]
since LineagoOS and iPhone had no problem with my testserver @home which where already on Fedora 26 / OpenSSL 1.1 i upgraded the production trafficserver machine and now it seems to work with all devices - while to be honest i am not sure if the warnings and several soft reloads (/usr/bin/traffic_ctl config reload) and a security scan in between may have triggered some interanl fuckup, at least after touch ssl_multicert.config as well as the certificate files currentyl on Fedora 26 it still works - i will make a notice here if the problem comes back

**Comment by mlibbey** [comment]
FWIW, we've been running in production with dual certs for several quarters now... Sounds like this was all sorted

**Comment by thelounge-zz** [comment]
yes, it's another weird ATS behavior that you need to say "ssl_cert_name=FILENAME[,FILENAME …]" instead just a "ssl_cert_name" line with each certificate file you have and ATS takes the right one automatically

unexpected behavior because in general you throw certificates in the multi-ssl-config and it's automatically selected by SNI so nobody expects that you need a specific config to make dual stack working
