### ISSUE TITLE
Invalid aggregate specification: AVERAGE

### ISSUE THREAD

**Issue by j-manu** [apache/trafficserver#2728]
With the following in logging.config

```
summary = format {
   Format = "%<LAST(cqtn)> : %<COUNT(*)> : %<AVERAGE(ttms)>",
   Interval = "60"
}

log.ascii {
  Format = summary,
  Filename = 'summary'
}
```

I'm getting the error `Invalid aggregate specification: AVERAGE` in `diags.log` and the summary log file is empty

**Comment by shukitchan** [comment]
Try to use AVG please instead of AVERAGE.

**Comment by j-manu** [comment]
That fixed it. Thanks!

The documentation says AVERAGE though - https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/logging/understanding.en.html#admin-logging-type-summary

**Comment by shukitchan** [comment]
That's a good one. Would you like to submit a PR to fix it?
It is here - https://github.com/apache/trafficserver/blob/master/doc/admin-guide/logging/understanding.en.rst

And I think @mlibbey can help to review as well.

**Comment by j-manu** [comment]
Done. https://github.com/apache/trafficserver/pull/2980
