### ISSUE TITLE
proxy.node.hostname_FQ can'

### ISSUE THREAD

**Issue by holinhot** [apache/trafficserver#2729]
Hello,
I want Customize the servername on via tag
default is Via:http/1.0 localhost.localdomain
CONFIG proxy.node.hostname_FQ TEST.S
CONFIG proxy.node.hostname STRING TEST

I add these line to records but server via still output is default is Via:http/1.0 localhost.localdomain

Thanks

**Comment by maskit** [comment]
You can customize Via header value with these:
- proxy.config.http.insert_response_via_str
- proxy.config.http.response_via_str

https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html

Issues are for issues. Please use mailing list (users@trafficserver.apache.org) for this kind of questions next time.

**Comment by shukitchan** [comment]
Just one more note. You can try to change this proxy.config.proxy_name as well. Perhaps that's actually what you want.

**Comment by holinhot** [comment]
thanks @maskit these only changed Via:http/1.1 localhost.localdomain (CDN [uScMs f p eN:t cCMi p sS])
can't change localhost.localdomain

**Comment by holinhot** [comment]
@maskit thank i'll use mailing list

**Comment by holinhot** [comment]
@shukitchan thanks CONFIG proxy.config.proxy_name STRING  is worked
