### ISSUE TITLE
help me out

### ISSUE THREAD

**Issue by nikhil-khandelwal2** [apache/trafficserver#2730]
static int
gen_bfc_dist(double f = 10.0)
{
  if (docsize >= 0) {
    return docsize;
  }

  double rand  = 0.0;
  double rand2 = 0.0;
  bool f_given = f < 9.0;
  if (!f_given) {
    // coverity[dont_call]
    rand = drand48();
    // coverity[dont_call]
    rand2 = drand48();
  } else {
    rand  = f;
    rand2 = (f * 13.0) - floor(f * 13.0);
  }

**Comment by persiaAziz** [comment]
????
