### ISSUE TITLE
httpSM received signal SIGABRT, Aborted

### ISSUE THREAD

**Issue by jingshaoqi** [apache/trafficserver#2752]
version 7.1.0 release
(gdb) bt
#0  0x00007ffff55b0765 in raise () from /lib64/libc.so.6
#1  0x00007ffff55b236a in abort () from /lib64/libc.so.6
#2  0x00007ffff7bb3d29 in ink_abort (message_format=0x7ffff7bc5a50 "%s:%d: failed assertion `%s`") at ink_error.cc:99
#3  0x00007ffff7bb1403 in _ink_assert (expression=0x802a08 "t_state.current.server->state == HttpTransact::STATE_UNDEFINED", file=0x801bec "HttpSM.cc", line=1838)
    at ink_assert.cc:37
#4  0x00000000005f3752 in HttpSM::state_read_server_response_header (this=0x7fff74b71cb0, event=104, data=0x7ffefc03bb58) at HttpSM.cc:1838
#5  0x00000000005f6da2 in HttpSM::main_handler (this=0x7fff74b71cb0, event=104, data=0x7ffefc03bb58) at HttpSM.cc:2689
#6  0x000000000051b754 in Continuation::handleEvent (this=0x7fff74b71cb0, event=104, data=0x7ffefc03bb58)
    at /root/chencichang/trafficserver-7.1.0/iocore/eventsystem/I_Continuation.h:153
#7  0x0000000000562ffe in PluginVC::process_read_side (this=0x7ffefc03ba30, other_side_call=false) at PluginVC.cc:634
#8  0x0000000000561470 in PluginVC::main_handler (this=0x7ffefc03ba30, event=1, data=0x7fffc812c9c0) at PluginVC.cc:227
#9  0x000000000051b754 in Continuation::handleEvent (this=0x7ffefc03ba30, event=1, data=0x7fffc812c9c0)
    at /root/chencichang/trafficserver-7.1.0/iocore/eventsystem/I_Continuation.h:153
#10 0x00000000007ced60 in EThread::process_event (this=0x7ffff2ca5010, e=0x7fffc812c9c0, calling_code=1) at UnixEThread.cc:143
#11 0x00000000007cf26f in EThread::execute (this=0x7ffff2ca5010) at UnixEThread.cc:240
#12 0x00000000007ce37a in spawn_thread_internal (a=0x1161350) at Thread.cc:84
#13 0x00007ffff63f15ca in start_thread () from /lib64/libpthread.so.0
#14 0x00007ffff567f0ed in clone () from /lib64/libc.so.6
(gdb) f 4
#4  0x00000000005f3752 in HttpSM::state_read_server_response_header (this=0x7fff74b71cb0, event=104, data=0x7ffefc03bb58) at HttpSM.cc:1838
1838	  ink_assert(t_state.current.server->state == HttpTransact::STATE_UNDEFINED);
(gdb) l
1833	int
1834	HttpSM::state_read_server_response_header(int event, void *data)
1835	{
1836	  STATE_ENTER(&HttpSM::state_read_server_response_header, event);
1837	  ink_assert(server_entry->read_vio == (VIO *)data);
1838	  ink_assert(t_state.current.server->state == HttpTransact::STATE_UNDEFINED);
1839	  ink_assert(t_state.current.state == HttpTransact::STATE_UNDEFINED);
1840	
1841	  int bytes_used = 0;
1842	  VIO *vio       = (VIO *)data;
(gdb) f 5
#5  0x00000000005f6da2 in HttpSM::main_handler (this=0x7fff74b71cb0, event=104, data=0x7ffefc03bb58) at HttpSM.cc:2689
2689	    (this->*jump_point)(event, data);
(gdb) l
2684	
2685	  if (vc_entry) {
2686	    jump_point = vc_entry->vc_handler;
2687	    ink_assert(jump_point != (HttpSMHandler) nullptr);
2688	    ink_assert(vc_entry->vc != (VConnection *)nullptr);
2689	    (this->*jump_point)(event, data);
2690	  } else {
2691	    ink_assert(default_handler != (HttpSMHandler) nullptr);
2692	    (this->*default_handler)(event, data);
2693	  }

t_state.current.server->state is CONNECTION_CLOSED

**Comment by bryancall** [comment]
If this is still an issue please reopen.
