### ISSUE TITLE
Error loading cache from host.db

### ISSUE THREAD

**Issue by jagannadharaju** [apache/trafficserver#2790]
We are trying to upgrade to 7.1.1 .

And when I do start ATS, I am seeing following warning in diags.log file
"WARNING: Error loading cache from /opt/ats/var/trafficserver/host.db: -1"

I haven't overridden any of the properties related hostdb in records.config.

Can some one please help on this.

**Comment by SolidWallOfCode** [comment]
We have been seeing that, but as far as we can tell it's innocuous. Please let us know if you observe any negative effects. In our experiments this causes the old host DB file to be deleted and the HostDB repopulated with no observable problems.

**Comment by jagannadharaju** [comment]
Can you please also help me on, whether there is any known issue in hostdb.config file not getting generated? I am able to see hostdb.config getting in 6.1.0 while I don't find it in 7.1.1 .

**Comment by bryancall** [comment]
If this is still an issue please reopen.
