### ISSUE TITLE
override order in cache.config is questionable

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#2796]
this works, jpg file starts after 60 seconds with 0 according to curl --head
___________________________________________________
url_regex=. suffix=jpg   revalidate=60s cache-responses-to-cookies=1
url_regex=. revalidate=3600s
url_regex=. suffix=php action=never-cache
url_regex=^https?://[\.-a-zA-Z]/$ action=never-cache
___________________________________________________
in that case age: counts up, touch of the origin file don't get respected within 60 seconds so the global revalidate=3600s overrides

url_regex=. revalidate=3600s
url_regex=. suffix=jpg   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=php action=never-cache
url_regex=^https?://[\.-a-zA-Z]/$ action=never-cache
___________________________________________________

this is NOT what the documentation says because "suffix=jpg" is "more targeted"
https://docs.trafficserver.apache.org/en/latest/admin-guide/files/cache.config.en.html

# Incorrect!
dest_domain=example.com prefix=foo suffix=js revalidate=7d
dest_domain=example.com suffix=js revalidate=1d

# Correct!
dest_domain=example.com suffix=js revalidate=1d
dest_domain=example.com prefix=foo suffix=js revalidate=7d

The latter accomplishes the implied goal of having a default, or global, timer for cache object revalidations on Javascript files, as well as a more targeted (and longer) revalidation time on just those Javascript files with a particular prefix. The former fails at this goal, because the second rule will match all Javascript files and will override any previous revalidate values that may have been set by prior rules.

**Comment by mlibbey** [comment]
Do you want to make a pull request to update the doc?

**Comment by thelounge-zz** [comment]
i would say it's a software bug because it is completly unusual to put generic things *after* specific overrides

**Comment by mlibbey** [comment]
I don't think cache.config is in heavy use, but, the way I read the doc, "When multiple rules are specified in cache.config, Traffic Server will check all of them in order for each request." Which is the way remap.config also works -- the most specific things have to be first.

**Comment by mlibbey** [comment]
Still not clear what the documentation should be updated to. Please re-open with a documentation update PR.

**Comment by thelounge-zz** [comment]
github is not my world nor are PR's

url_regex=. revalidate=3600s
url_regex=. suffix=jpg revalidate=60s cache-responses-to-cookies=1

the point is that in every other software on that planet a config like this would work with the meaning "everything has 3600 until a more specific configuration exists and so for .jpg 60 seconds are active" while in the ATS world you need to wrap the line order because obvisouly it proceeds the config from top to bottom and the first match wins

that's iptables behavior but nothing someone expects in a server config

**Comment by SolidWallOfCode** [comment]
I'm looking at that code now and I thought I was not reading it correctly, but AFAICT, while the rules are not first match, the _directives_ are. For examle, considering @thelounge-zz's last example, the first rule that has a `revalidate` directive sets that value and it cannot be changed by a later rule. Such later rules can, however, set other directives, such as `never-cache`.

**Comment by SolidWallOfCode** [comment]
Here is the code that does the result updating for `revalidate`
```
  case CC_REVALIDATE_AFTER:
    if (this->CheckForMatch(h_rdata, result->reval_line) == true) {
```
This calls `CheckForMatch`, passing in the line where the `revalidate` directive was first found (-1 if it hasn't been seen yet). What does `CheckForMatch` do?
```
  return (last_number < 0 || last_number > this->line_num) && this->CheckModifiers(request_data);
```
It always returns `false` if the passed in line number is non-negative and larger than the current rule line number. In the example, for the second rule `last_number` would be 0 and `this->line_num` would be 1, which means the line is not matched because it has the same directive, `revalidate`, as line 0, which means `last_number == 0` and therefore `last_number > this->line_num` is `false`.

**Comment by bryancall** [comment]
Relates to #1329

**Comment by bryancall** [comment]
This is going to be handled #7701
