### ISSUE TITLE
Rename all "Debug*()" macros to "*Debug()"

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#2802]
To make all Debug() macros greppable, they all should be named like "FooBarDebug()" but not "DebugFooBar()".

See also #2797.

**Comment by Tchinmai7** [comment]
Can I take this?

**Comment by maskit** [comment]
Sure, why not? :-)

**Comment by Tchinmai7** [comment]
@maskit can you please close the issue? the PR has been merged.
