### ISSUE TITLE
Rename ua_session of HttpSM

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#2810]
After TS-3612, `ua_session` is `ProxyClientTransaction *` now. This made confusion very much.
It'd be great if this is renamed to `ua_transaction`.
https://github.com/apache/trafficserver/blob/4d4283ea26f709fc9a7efea3283f1acc401bab0a/proxy/http/HttpSM.h#L334

**Comment by shinrich** [comment]
Yep,  seems like a good idea.
