### ISSUE TITLE
7.1.1: gzip plugin don't compress with Content-Type: text/html; charset=ISO-8859-1

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#2849]
see the response headers from server-spy firefox extension at bottom and it's the "text/html; charset=ISO-8859-1" where "compressible-content-type text/html" no longer matches because of the charset because with "compressible-content-type text/*" it works

besides that because of "Multiple algorthims can be selected using ',' delimiter, for instance, supported-algorithms deflate,gzip,br. Note that if ts:cv:proxy.config.http.normalize_ae is 1, only gzip will be considered, and if it is 2, only br or gzip will be considered" as long as 7.1.1 don't support "proxy.config.http.normalize_ae" but only "proxy.config.http.normalize_ae_gzip" brotli support is compiled and linked but impossible to use uncacheable content is *not* compressed

the whole idea of the configuration below (including remove-accept-encoding true) is to offload besides TLS also the compression to the proxy server but CMS pages don't contain a "content-encoding: gzip" header (.css and .js files does) while when comment out the plugin the origin server get the accept-encondig from the client and respoonds with a compressed version of the page
_____________________________________
[root@testserver:/etc/trafficserver]$ cat plugin.config
gzip.so /etc/trafficserver/gzip.config
_____________________________________
[root@testserver:/etc/trafficserver]$ cat gzip.config 
enabled true
cache true
flush true
remove-accept-encoding true
supported-algorithms br,gzip,deflate
compressible-content-type text/html
compressible-content-type text/javascript
compressible-content-type text/css
compressible-content-type text/plain
compressible-content-type text/xml
compressible-content-type text/x-component
compressible-content-type application/xhtml+xml
compressible-content-type application/xml+rss
compressible-content-type application/rss+xml
compressible-content-type application/xml
compressible-content-type application/javascript
compressible-content-type application/x-javascript
compressible-content-type application/json
compressible-content-type application/msword
compressible-content-type application/msexcel
compressible-content-type application/mspowerpoint
compressible-content-type application/msaccess
compressible-content-type application/mshelp
compressible-content-type application/pdf
compressible-content-type application/postscript
compressible-content-type audio/x-wav
compressible-content-type text/rtf
compressible-content-type text/comma-separated-values
compressible-content-type text/tab-separated-values
compressible-content-type text/vnd.wap.wml
compressible-content-type text/vnd.wap.wmlscript
compressible-content-type text/vnd.wap.wmlscript
compressible-content-type application/vnd.wap.wmlc
compressible-content-type text/x-setext
compressible-content-type text/x-sgml
compressible-content-type text/x-speech
compressible-content-type application/x-sh
compressible-content-type application/x-latex
compressible-content-type application/x-httpd-php-source
compressible-content-type application/vnd.ms-fontobject
compressible-content-type font/ttf
compressible-content-type font/otf
compressible-content-type font/woff
compressible-content-type font/woff2
compressible-content-type font/x-woff
compressible-content-type image/svg+xml
compressible-content-type application/vnd.ms-word.document.macroEnabled.12
compressible-content-type application/vnd.openxmlformats-officedocument.wordprocessingml.document
compressible-content-type application/vnd.ms-word.template.macroEnabled.12
compressible-content-type application/vnd.openxmlformats-officedocument.wordprocessingml.template
compressible-content-type application/vnd.ms-powerpoint.template.macroEnabled.12
compressible-content-type application/vnd.openxmlformats-officedocument.presentationml.template
compressible-content-type application/vnd.ms-powerpoint.addin.macroEnabled.12
compressible-content-type application/vnd.ms-powerpoint.slideshow.macroEnabled.12
compressible-content-type application/vnd.openxmlformats-officedocument.presentationml.slideshow
compressible-content-type application/vnd.ms-powerpoint.presentation.macroEnabled.12
compressible-content-type application/vnd.openxmlformats-officedocument.presentationml.presentation
compressible-content-type application/vnd.ms-excel.addin.macroEnabled.12
compressible-content-type application/vnd.ms-excel.sheet.binary.macroEnabled.12
compressible-content-type application/vnd.ms-excel.sheet.macroEnabled.12
compressible-content-type application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
compressible-content-type application/vnd.ms-excel.template.macroEnabled.12
compressible-content-type application/vnd.openxmlformats-officedocument.spreadsheetml.template
_____________________________________
[root@testserver:/etc/trafficserver]$ cat cache.config
# cache.config

url_regex=. suffix=css   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=js    revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=htc   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=html  revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=htm   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=txt   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=xml   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=jpg   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=jpeg  revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=gif   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=png   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=ico   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=ttf   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=otf   revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=woff  revalidate=60s cache-responses-to-cookies=1
url_regex=. suffix=woff2 revalidate=60s cache-responses-to-cookies=1

# don't cache landing pages and dynamic content
url_regex=. suffix=php action=never-cache
url_regex=^https?://[\.-a-zA-Z]/$ action=never-cache
_____________________________________

HTTP/2.0 200 OK
date: Tue, 21 Nov 2017 14:36:06 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: private
etag: 62806da34a07a0d98b360a1dc4b39f94
last-modified: Thu, 19 Dec 2013 18:26:50 GMT
vary: Accept-Encoding,User-Agent
x-content-type-options: nosniff
x-response-time: D=37586 us
content-type: text/html; charset=ISO-8859-1
age: 0
X-Firefox-Spdy: h2

**Comment by mlibbey** [comment]
For the meantime, could add * after some of the rules. For instance.
compressible-content-type text/html*

(similarly, you could get rid of several of these rules by doing
compressible-content-type text/*)

**Comment by thelounge-zz** [comment]
@millbery as long as https://github.com/apache/trafficserver/issues/2850 is not fixed the plugin is unuseable at all so that plugin needs some love anyways and "supported-algorithms br,gzip,deflate" also don#t work properly beause "CONFIG proxy.config.http.normalize_ae INT 2" is not supported in any released version

**Comment by bryancall** [comment]
If this is still an issue please reopen.
