### ISSUE TITLE
7.1.1: gzip plugin logflood WARNING: INKCont Deletable but not deleted

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#2850]
after enable gzip.so the log get flooded with stuff like below

practically the config from https://github.com/apache/trafficserver/issues/2849 but because of this bug replaced all text-mimetypes with "compressible-content-type text/*" - this logflood disqaulifies the plugin for production

[Nov 21 16:33:50.369] Server {0x1495e3b0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:33:50.375] Server {0x1495e3d0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:33:50.385] Server {0x1495e3d0c700} WARNING: INKCont Deletable but not deleted 3
[Nov 21 16:33:50.385] Server {0x1495e3f0c700} WARNING: INKCont Deletable but not deleted 2
[Nov 21 16:33:50.391] Server {0x1495e3f0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:33:50.621] Server {0x1495e3b0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:33:50.742] Server {0x1495e3d0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:33:53.462] Server {0x1495e410c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:33:55.327] Server {0x1495e3f0c700} WARNING: INKCont Deletable but not deleted 2
[Nov 21 16:33:55.352] Server {0x1495e3b0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:33:59.639] Server {0x1495e410c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:01.161] Server {0x1495e3d0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:03.480] Server {0x1495e3f0c700} WARNING: INKCont Deletable but not deleted 2
[Nov 21 16:34:03.480] Server {0x1495e3f0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:04.753] Server {0x1495e3b0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:05.609] Server {0x1495e3d0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:11.417] Server {0x1495e410c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:15.753] Server {0x1495e3f0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:17.874] Server {0x1495e3b0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:29.744] Server {0x1495e3d0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:36.942] Server {0x1495e410c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:38.134] Server {0x1495e3f0c700} WARNING: INKCont Deletable but not deleted 1
[Nov 21 16:34:49.785] Server {0x1495e3f0c700} WARNING: INKCont Deletable but not deleted 1

**Comment by randall** [comment]
This was addressed by commit 093778c
