### ISSUE TITLE
relative redirects: url_canonicalize_port has no default without a scheme

### ISSUE THREAD

**Issue by d2r** [apache/trafficserver#2851]
This might not be a bug.

https://github.com/apache/trafficserver/blob/a0b5bd760f1cc67a98eeb0396970c733bc4d26fe/proxy/hdrs/URL.h#L253-L263

When following redirects, if a relative redirect is returned without a scheme (or a host name), then this code cannot choose a port number to use when following the redirect.

It might be good if ATS would be updated to be smarter when following such redirects (use the previous client request's scheme/port).

**Comment by d2r** [comment]
Labels: HTTP

**Comment by d2r** [comment]
This is still an issue.

**Comment by bryancall** [comment]
Relates to #2742

**Comment by ywkaras** [comment]
I think I may have fixed this or at least broke it differently, you can give me the issue if you want.

**Comment by ywkaras** [comment]
This PR may have changed this behavior:  https://github.com/apache/trafficserver/pull/7545 .

**Comment by bryancall** [comment]
@ywkaras Can you please take look at see if you "fixed" it.

**Comment by ywkaras** [comment]
I ran the redirect Au test under gdb, with a breakpoint in url_canonicalize_port().  The type parameter was never NONE, even though the test includes relative redirects, so looks like we're good.
