### ISSUE TITLE
Header Rewrite: rm-cookie operator has no effect on cache lookup

### ISSUE THREAD

**Issue by fjarrett** [apache/trafficserver#2857]
Consider the following:

```sh
# /etc/trafficserver/records.config
CONFIG proxy.config.http.cache.cache_responses_to_cookies INT 0

# /etc/trafficserver/plugin.config
header_rewrite.so /etc/trafficserver/header_rewrite.config
xdebug.so

# /etc/trafficserver/header_rewrite.config
cond %{READ_REQUEST_HDR_HOOK}
add-header X-Debug x-cache
rm-cookie foo
```

And a little background [about the hook](https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/header_rewrite.en.html#read-request-hdr-hook):

> **READ_REQUEST_HDR_HOOK**
> Evaluates as soon as the client request has been read, but prior to any further processing (including contacting origin servers or fetching objects from cache).

The response _should be_ a `hit-fresh` since the `foo` cookie is being removed from request header before cache lookup, but instead it always shows a cache `miss`:

```sh
$ curl -is -H 'Cookie: foo=bar' https://fjarrett.com | grep X-Cache
X-Cache: miss
```

Everything works as expected if you completely remove the `Cookie` header from the request, which seems to prove that the hook is capable of intercepting the cache lookup with other Header Rewrite operators manipulating cookies:

```sh
# /etc/trafficserver/header_rewrite.config
cond %{READ_REQUEST_HDR_HOOK}
add-header X-Debug x-cache
rm-header Cookie
```

```sh
$ curl -is -H 'Cookie: foo=bar' https://fjarrett.com | grep X-Cache
X-Cache: hit-fresh
```

**Comment by fjarrett** [comment]
**Update:** It seems the real underlying problem here is that when all cookies have been removed, an empty`Cookie` header is still left in the request, which triggers the cache MISS.

So I think the real bug is that `cache_responses_to_cookies` only checks for the presence of the `Cookie` header, and doesn't validate the value to see if it's empty.

**Comment by zwoop** [comment]
I believe this has been fixed, closing.
