### ISSUE TITLE
Implement host_allow for HTTP whitelisting

### ISSUE THREAD

**Issue by seanpeters86** [apache/trafficserver#2859]
It would be nice to have the ability to use the `ip_allow.config` style with hostnames AND ip ranges where applicable. Effectively giving an easier way to create a whitelist only proxy solution. 

Squid offers something to this effect via:
```
acl whitelist dstdomain "/etc/squid/whitelist.txt"
http_access allow whitelist
# Deny all other access to this proxy
http_access deny all
```

where you can specify hostnames in a list like so:
```
www.google.com
www.yahoo.com
.starbucks.com
```

**Comment by bryancall** [comment]
I don't think anyone is interested in doing this.  There are implications on performance on the ACLs.  An alternative is to write a plugin that would do this.
