### ISSUE TITLE
Problem with proxy CONNECT via upstream Proxy on OSX/iOS 

### ISSUE THREAD

**Issue by devZer0** [apache/trafficserver#2861]
We have ATS 5.3.0 on CentOS7 run as a normal forwarding http/https proxy in front of an unknown upstream proxy at a customer site. For application testing and for security reason, our developers should connect via that proxy for testing different applications on OSX and iOS 

We have problems with Safari&Webkit based Browsers and HTTPS (on OSX and iOS) - whenever a HTTPS  URL is used we see the ATS connect to the upstream proxy and connection is declared successfully  established from the upstream and from the ATS proxy, but Safari does not load any HTTPS page. 

Non upstream proxied HTTPS URLs can be fetched.
It also works if we use the upstream proxy directly from Safari browser.
It also works if we put mitmproxy between Safari and ATS

We are unsure if this is a safari or an ATS issue and need some help for further analysis

This works:
<pre>
Safari               -> mitmproxy -> ats proxy -> customer proxy -> https://customer-site
OtherBrowser         -> mitmproxy -> ats proxy -> customer proxy -> https://customer-site
Safari               ---------------------------> customer proxy -> https://customer-site
Safari               --------------> ats proxy -> https://non-customer-non-proxied-site
</pre>
This does NOT work:
<pre>
Safari               --------------> ats proxy -> customer proxy -> https://customer-site
</pre>

**Comment by devZer0** [comment]
Further testing revealed, that this seems more to be a browser issue. What i see from  wireshark is that after CONNECT is confirmend from both proxies ,  Safari seems to act no further, i.e. Firefox starts SSL/TLS Handshake trough the tunnel, but Safari doesn't. I installed OSX 10.11 (El Capitan) in a VM and tested with Safari 9.0.1 and found that it also works, so the problem is related to recent Safari Version (My OSX 10.12 Sierra has Safari 11.0.1). I somewhere read (sorry, no link) that Safari Proxy capability would suck, but i cannot substantiate this with any qualified reference...

It`s weird....

**Comment by devZer0** [comment]
No it`s getting completely crazy - i updated Safari Browser to 11.0.1 on El Capitan and it works there - same browser Version on Sierra or High Sierra does NOT work, so the issue is related to OSX 10.12 and 10.13.

**Comment by devZer0** [comment]
On OSX, Safari hangs forever and never returns or give any error message.

On iOS 10.3.3 testing with Safari gives "Safari could not open Page because server is not responding". As other Browsers are all Webkit-based on iOS , they also don`t work there. On Chrome i`m getting ERR_CONNECTION_TIMED_OUT and Firefox hangs forever

User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) CriOS/62.0.3202.70 Mobile/14G60 Safari/602.1

**Comment by devZer0** [comment]
https://bugs.webkit.org/show_bug.cgi?id=180003

**Comment by devZer0** [comment]
As recommended by WebKit dev, opened Bug for Safari Browser: https://bugreport.apple.com/web/?problemID=35686649

**Comment by bryancall** [comment]
If this is still an issue please reopen.
