### ISSUE TITLE
In Lua plugin, response transform hook hangs indefinitely if the response contents are empty

### ISSUE THREAD

**Issue by utkuzih** [apache/trafficserver#2887]
- ATS Version: 7.1 (compiled using `--enable-experimental-plugins`)
- Debian Jessie within Docker 17.11

**Lua plugin:**
```
function transform_response(data, eos)
    ts.debug("transform_response") -- Never printed
    return data, eos
end

function do_global_txn_start()
    ts.hook(TS_LUA_RESPONSE_TRANSFORM, transform_response)
    return 0
end
```

**Steps to reproduce:**

1. Configure ATS using the lua plugin above
2. Make forward proxy request to an http page with 0 byte body
3. Request hangs forever, `transform_response` is never invoked

**Comment by shukitchan** [comment]
let me take a look tomorrow

**Comment by shukitchan** [comment]
Yeah. I confirmed the behavior in the master branch as well. With a remap rule going to http://httpbin.org/status/200

**Comment by shukitchan** [comment]
It is actually a corner case in which the input vio is not available.
One quick question. In this case you would still want a lua function to be called or not?

**Comment by shukitchan** [comment]
ok... let me assume that you still want a lua function to be called in this case. 
Will provide a patch soon.

**Comment by utkuzih** [comment]
Thanks for checking this issue! 

I think it's a good idea to call the lua function regardless of the input size for consistency sake. This is especially useful if we are initializing variables in the lua transform function.

**Comment by shukitchan** [comment]
can you try out PR #2939 ?
