### ISSUE TITLE
Pass through does not work on v7.0.0-5

### ISSUE THREAD

**Issue by aminlatifi** [apache/trafficserver#2889]
Hi,
I'm using Traffic Server version 7.0.0-5 on debian server and want to pass through non-http traffic running on port 80. I have modified records.conf file as below:

`CONFIG proxy.config.http.server_ports STRING 8080:tr-full:tr-pass 8080:ipv6`

Unfortunately, I cannot connect to https or ssh services running on port 80. As an example, connecting to some https server running on port 80, following error line is generated to squid.blog:
`1512298757.585 0 192.168.1.135 ERR_INVALID_REQ/400 0 - / - NONE/- text/html`

**Comment by bryancall** [comment]
If this is still an issue please reopen.
