### ISSUE TITLE
improve draining

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#2906]
After reviewing suggestions and emails for http2 graceful shutdown from @jpeach @mlibbey @maskit @masaori335 , I find some action items to improve drain functionalities even after we got https://github.com/apache/trafficserver/pull/2106 and https://github.com/maskit/trafficserver/pull/1.

1. Draining traffic without restarting or stopping.
2. Recovery from draining state.

Any ideas about how to achieve these?

P.S. I notice that sometimes we need to wait for max time or metrics going down thresholds then perform the actions. If we can implement different actions in some uniform style, that would be great.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
