### ISSUE TITLE
header_rewrite OR condition flag broken

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#2950]
sorry but this is a joke

cond %{SEND_REQUEST_HDR_HOOK} AND (cond %{INCOMING-PORT}=8443 OR cond %{INCOMING-PORT}=443)
set-header X-TL-TLS-Offload 1
set-header X-TL-TLS-Offload-Port %{INCOMING-PORT}

[harry@srv-rhsoft:~]$ curl https://testserver.rhsoft.net:8443/headers.php | grep TLS
    [HTTP_X_TL_TLS_OFFLOAD] => 1
    [HTTP_X_TL_TLS_OFFLOAD_PORT] => 8443

[harry@srv-rhsoft:~]$ curl http://testserver.rhsoft.net:8080/headers.php | grep TLS
    [HTTP_X_TL_TLS_OFFLOAD] => 1
    [HTTP_X_TL_TLS_OFFLOAD_PORT] => 8080
_________________________________________

that works as expected but that is no excuse for OR beeing terrible broken

cond %{SEND_REQUEST_HDR_HOOK}
cond %{INCOMING-PORT}=443
set-header X-TL-TLS-Offload 1
set-header X-TL-TLS-Offload-Port %{INCOMING-PORT}

cond %{SEND_REQUEST_HDR_HOOK}
cond %{INCOMING-PORT}=8443
set-header X-TL-TLS-Offload 1
set-header X-TL-TLS-Offload-Port %{INCOMING-PORT}

**Comment by mlibbey** [comment]
Issue is apparently a joke. But, in case that was sarcasm, could work around limitation of header_rewrite's "language" (eg, lack of parenthesis for IF statements) by using regex for this case.

cond %{SEND_REQUEST_HDR_HOOK}
cond %{INCOMING-PORT} /^(443|8443)$/
set-header X-TL-TLS-Offload 1
set-header X-TL-TLS-Offload-Port %{INCOMING-PORT}

**Comment by thelounge-zz** [comment]
the issue is not ajoke nor sarcasm

https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/plugins/header_rewrite.en.html

Condition Flags

The condition flags are optional, and you can combine more than one into a comma-separated list of flags. Note that whitespaces are not allowed inside the brackets:
Flag 	Description
AND 	Indicates that both the current condition and the next must be true. This is the default behavior for all conditions when no flags are provided.
NOT 	Inverts the condition.
OR 	Indicates that either the current condition or the next one must be true, as contrasted with the default behavior from [AND].

**Comment by thelounge-zz** [comment]
the regex crap don't work at all, i had that tried with cond %{INCOMING-PORT} /(443|8443)/ before and your syntax also don't work otherwise i would see that headers below, it don't hit at all

[root@testserver:/var/log/trafficserver]$ cat /etc/trafficserver/header_rewrite.config
cond %{SEND_REQUEST_HDR_HOOK}
cond %{INCOMING-PORT} /^(443|8443)$/
set-header X-TL-TLS-Offload 1
set-header X-TL-TLS-Offload-Port %{INCOMING-PORT}

[harry@srv-rhsoft:~]$ curl https://testserver.rhsoft.net:8443/headers.php | grep TLS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1002  100  1002    0     0   4877      0 --:--:-- --:--:-- --:--:--  4864
