### ISSUE TITLE
HTTP/0.9 impl doesn't wait for fin flag.

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#2952]
If ATS couldn't read whole request at the first read, it fails to convert the request into HTTP/1.1 and causes 400 bad request.

**Comment by maskit** [comment]
From slack channel:

> mcmanus [12:18 AM] 
> so it arrives in 3 frames.. "GET " "/" and "\r\n(withfin)"
> 
> 
> [12:18] 
> that's been known to confuse people :slightly_smiling_face:
> 
> 
> maskit [12:39 AM] 
> Confirmed that ATS returns 400 bad request if it couldn’t read whole request at the first read (because it doesn’t wait for fin flag). Thanks.
> 
> 
> mcmanus [12:40 AM] 
> yeah.. I've never been clear on if we decided the req was terminated by fin or crlf
> 
> 
> nibanks [12:41 AM] 
> I thought it was decided that FIN was the terminator,

**Comment by masaori335** [comment]
Fixed by https://github.com/apache/trafficserver/commit/ac2e13dcd1c59fb98eeefd3f69505680ebeb0dd2
