### ISSUE TITLE
Append PADDING frames only if necessary

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#2953]
Now ATS appends PADDING frames whenever the frame size is small but it shouldn't.

**Comment by maskit** [comment]
According to the spec, PADDING frames are allowed to use for protection against traffic analysis. When should we use it exactly?

> Padding can be used to
   increase an initial client packet to the minimum required size, or to
   provide protection against traffic analysis for protected packets.

**Comment by masaori335** [comment]
FWIW, current quic-latest branch adds PADDING frames only on client INITIAL packet.
https://github.com/apache/trafficserver/blob/29bba883ce44ddbfa329b957a36e8509f2af4432/iocore/net/QUICNetVConnection.cc#L1349

**Comment by zwoop** [comment]
Is this for H2 or QUIC, or both ?

**Comment by maskit** [comment]
This is for QUIC.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
