### ISSUE TITLE
TCP_SWAPFAILS_MISS cause incorrect http response(incomplete response content)

### ISSUE THREAD

**Issue by JHsorth** [apache/trafficserver#2983]
Recently, we found some taged '**TCP_SWAPFAIL_MISS**' logs on ts-4.2.3. These urls can not be completely downloaded but interrupted halfway, just like:
`curl: (18) transfer closed with 47090107 bytes remaining to read`

The corresponding log is:
`127.0.0.1 http 26/Dec/2017:14:50:46 +0800 GET xxxx xxxxx 200 521 my_debug 2774 TCP_SWAPFAIL_MISS -`

The KEY is 684FEEBB04842BA70FBB11C908FE740E, the following is cache.* debug log:
>[Dec 26 14:58:05.293] Server {0x2ba4d4e0d700} DEBUG: (cache_hosting) Generic volume: c000918d for host: private.domain.com
[Dec 26 14:58:05.293] Server {0x2ba4d4e0d700} DEBUG: (cache_new) new 0x2ba54c026a20
[Dec 26 14:58:05.293] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 684FEEBB04842BA70FBB11C908FE740E. Length: data payload=0 this fragment=4432 total doc=411982027 prefix=4432
[Dec 26 14:58:05.293] Server {0x2ba4d4e0d700} DEBUG: (cache_read) CacheReadStartHead - read 684FEEBB04842BA70FBB11C908FE740E target E04141550AB2802F5818C7C0460D598C - multi 4432 of 411982027 bytes, 196 fragments
[Dec 26 14:58:05.305] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment E04141550AB2802F5818C7C0460D598C. Length: data payload=2097080 this fragment=2097152 total doc=2099037 prefix=72
[Dec 26 14:58:05.426] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 5E43B37389B8472DD6D53A79B5307B97. Length: data payload=2097080 this fragment=2097152 total doc=4195597 prefix=72
[Dec 26 14:58:05.451] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 2B7A7D1C07B55521D18AC1FCF55ADE91. Length: data payload=2097080 this fragment=2097152 total doc=6292157 prefix=72
......
[Dec 26 14:58:07.719] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 37E664E54A392C0AF8EF6C673E0A1B35. Length: data payload=2097080 this fragment=2097152 total doc=362800000 prefix=72
[Dec 26 14:58:07.725] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 017C5E37590FB83084E15DC1C6C8994C. Length: data payload=2097080 this fragment=2097152 total doc=364892180 prefix=72
[Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 5C14E7B860AB11FC4449BC1835A281F5. Length: **data payload=-1679916650** this fragment=1289101612 total doc=-8190407036451738202 prefix=-1325949034
[Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} WARNING: Middle: Doc magic does not match for 35F56632C2D0FBA66E571906B0AB0D0A
[Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} WARNING: Document E04141550AB2802F5818C7C0460D598C truncated
[Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} DEBUG: (cache_free) free 0x2ba54c026a20

1、We checked the cache disk but no errors so why cause 'data payload=-1679916650' ? 
2、In addition, why ats did not forward to the origin server and update local cache copy?

Thanks much.

**Comment by bryancall** [comment]
If this is still an issue please reopen.

**Comment by twoholes** [comment]
I have found the problem , incomplete response content.  I guess the problem relate to read while write  and negative cache.
who can help me~~

**Comment by twoholes** [comment]
> 
> 
> Recently, we found some taged '**TCP_SWAPFAIL_MISS**' logs on ts-4.2.3. These urls can not be completely downloaded but interrupted halfway, just like:
> `curl: (18) transfer closed with 47090107 bytes remaining to read`
> 
> The corresponding log is:
> `127.0.0.1 http 26/Dec/2017:14:50:46 +0800 GET xxxx xxxxx 200 521 my_debug 2774 TCP_SWAPFAIL_MISS -`
> 
> The KEY is 684FEEBB04842BA70FBB11C908FE740E, the following is cache.* debug log:
> 
> > [Dec 26 14:58:05.293] Server {0x2ba4d4e0d700} DEBUG: (cache_hosting) Generic volume: c000918d for host: private.domain.com
> > [Dec 26 14:58:05.293] Server {0x2ba4d4e0d700} DEBUG: (cache_new) new 0x2ba54c026a20
> > [Dec 26 14:58:05.293] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 684FEEBB04842BA70FBB11C908FE740E. Length: data payload=0 this fragment=4432 total doc=411982027 prefix=4432
> > [Dec 26 14:58:05.293] Server {0x2ba4d4e0d700} DEBUG: (cache_read) CacheReadStartHead - read 684FEEBB04842BA70FBB11C908FE740E target E04141550AB2802F5818C7C0460D598C - multi 4432 of 411982027 bytes, 196 fragments
> > [Dec 26 14:58:05.305] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment E04141550AB2802F5818C7C0460D598C. Length: data payload=2097080 this fragment=2097152 total doc=2099037 prefix=72
> > [Dec 26 14:58:05.426] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 5E43B37389B8472DD6D53A79B5307B97. Length: data payload=2097080 this fragment=2097152 total doc=4195597 prefix=72
> > [Dec 26 14:58:05.451] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 2B7A7D1C07B55521D18AC1FCF55ADE91. Length: data payload=2097080 this fragment=2097152 total doc=6292157 prefix=72
> > ......
> > [Dec 26 14:58:07.719] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 37E664E54A392C0AF8EF6C673E0A1B35. Length: data payload=2097080 this fragment=2097152 total doc=362800000 prefix=72
> > [Dec 26 14:58:07.725] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 017C5E37590FB83084E15DC1C6C8994C. Length: data payload=2097080 this fragment=2097152 total doc=364892180 prefix=72
> > [Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} DEBUG: (cache_read) Read complete on fragment 5C14E7B860AB11FC4449BC1835A281F5. Length: **data payload=-1679916650** this fragment=1289101612 total doc=-8190407036451738202 prefix=-1325949034
> > [Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} WARNING: Middle: Doc magic does not match for 35F56632C2D0FBA66E571906B0AB0D0A
> > [Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} WARNING: Document E04141550AB2802F5818C7C0460D598C truncated
> > [Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} DEBUG: (cache_free) free 0x2ba54c026a20
> 
> 1、We checked the cache disk but no errors so why cause 'data payload=-1679916650' ?
> 2、In addition, why ats did not forward to the origin server and update local cache copy?
> 
> Thanks much.

hi, how does the problem be resolved..
thank you
