### ISSUE TITLE
Debian/Ubuntu package stuck at 7.0.0-5

### ISSUE THREAD

**Issue by jcordeirobeseguros** [apache/trafficserver#2987]
Hi,
The package on debian qa repo as been locked on 7.0.0. As can be seen in:
https://packages.qa.debian.org/t/trafficserver.html

Apparently Britney (system) as removed the package from new testings at 2017-09-26 with the message:
https://packages.qa.debian.org/t/trafficserver/news/20170926T043911Z.html

Can you please fix it, if it needs fixing and/or kick it back into testing with the debian ppl?

**Comment by linnaea** [comment]
Debian policy forbids bundling anything so it gets the system-wide LuaJIT, which became 2.1 at that time, and ATS is not compatible with that.

See #2676, should be possible to pull that in and enable building with LuaJIT 2.1, as can be seen here: https://build.opensuse.org/public/build/home:linnaea/openSUSE_Factory/x86_64/apache-trafficserver/_log

Ask the maintainer for inclusion of that PR as it has been rejected here.

**Comment by jbfavre** [comment]
I've included the patch into Debian package.
7.1.3 is now available in sid.
I think tis issue can be closed now
