### ISSUE TITLE
7.1.x - crash in HttpSM:main_handler from dnsPendingEvent

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#2991]
We are seeing a crash following this series of events:
```C++
abort 
ink_abort
ink_error.cc:99

HttpSM::main_handler(int, void*) 
HttpSM.cc:2672

handleEvent
I_Continuation.h:153

reply_to_cont(Continuation*, HostDBInfo*, bool)
HostDB.cc:477

HostDBContinuation::probeEvent(int, Event*)
HostDB.cc:1707

HostDBContinuation::dnsPendingEvent(int, Event*)
HostDB.cc:1181

HostDBContinuation::remove_trigger_pending_dns()
HostDB.cc:1764

HostDBContinuation::dnsEvent(int, HostEnt*)
HostDB.cc:1458

DNSEntry::postEvent(int, Event*)
DNS.cc:1271

EThread::process_event(Event*, int)
EThread::process_queue(Queue<Event, Event::Link_link>*) 
EThread::execute_regular()
spawn_thread_internal
```
At the time of the crash in main_handler the magic value is already DEAD as well as the mutex pointer being NULL, so something has already destroyed this SM instance before it propagated through

**Comment by ezelkow1** [comment]
From a debug build we got a new one:

[ 0  ] libc-2.17.so       raise                                                 ( :undefined                 ) 
[ 1  ] libc-2.17.so       __GI_abort                                            ( :undefined                 ) 
[ 2  ] libtsutil.so.7.1.2 ink_abort                                             ( ink_error.cc:99            ) 
[ 3  ] libtsutil.so.7.1.2 _ink_assert                                           ( ink_assert.cc:37           ) 
[ 4  ] traffic_server     HttpSM::state_read_server_response_header(int, void*) ( HttpSM.cc:1842             ) 
[ 5  ] traffic_server     HttpSM::main_handler(int, void*)                      ( HttpSM.cc:2697             ) 
[ 6  ] traffic_server     Continuation::handleEvent(int, void*)                 ( I_Continuation.h:153       ) 
[ 7  ] traffic_server     read_signal_and_update                                ( UnixNetVConnection.cc:144  ) 
[ 8  ] traffic_server     UnixNetVConnection::readSignalAndUpdate(int)          ( UnixNetVConnection.cc:1092 ) 
[ 9  ] traffic_server     SSLNetVConnection::net_read_io(NetHandler*, EThread*) ( SSLNetVConnection.cc:596   ) 
[ 10 ] traffic_server     NetHandler::waitForActivity(long)                     ( UnixNet.cc:498             ) 
[ 11 ] traffic_server     EThread::execute_regular()                            ( UnixEThread.cc:248         ) 
[ 12 ] traffic_server     EThread::execute()                                    ( UnixEThread.cc:278         ) 
[ 13 ] traffic_server     spawn_thread_internal                                 ( Thread.cc:84               ) 
[ 14 ] libpthread-2.17.so start_thread                                          ( :undefined                 )

**Comment by shinrich** [comment]
We still see some events kick up on dead transactions.  Here is a stack from last night.

```
[ 0  ] libc-2.17.so       __GI_raise                                             ( :undefined                ) 
[ 1  ] libc-2.17.so       __GI_abort                                             ( :undefined                ) 
[ 2  ] libtsutil.so.7     ink_abort                                              ( ink_error.cc:99           ) 
[ 3  ] libtsutil.so.7     _ink_assert                                            ( ink_assert.cc:37          ) 
[ 4  ] traffic_server     _TSReleaseAssert                                       ( InkAPI.cc:405             ) 
[ 5  ] traffic_server     TSHttpTxnReenable                                      ( InkAPI.cc:5873            ) 
[ 6  ] ats_yca_plugin.so  auth_plugin_local_handler                              ( yca_plugin.cpp:1653       ) 
[ 7  ] traffic_server     INKContInternal::handle_event(int, void*)              ( InkAPI.cc:1053            ) 
[ 8  ] traffic_server     Continuation::handleEvent(int, void*)                  ( I_Continuation.h:153      ) 
[ 9  ] traffic_server     read_signal_and_update                                 ( UnixNetVConnection.cc:144 ) 
[ 10 ] traffic_server     read_signal_done                                       ( UnixNetVConnection.cc:205 ) 
[ 11 ] traffic_server     read_signal_error                                      ( UnixNetVConnection.cc:229 ) 
[ 12 ] traffic_server     read_from_net                                          ( UnixNetVConnection.cc:359 ) 
[ 13 ] traffic_server     UnixNetVConnection::net_read_io(NetHandler*, EThread*) ( UnixNetVConnection.cc:961 ) 
[ 14 ] traffic_server     NetHandler::waitForActivity(long)                      ( UnixNet.cc:497            ) 
[ 15 ] traffic_server     EThread::execute_regular()                             ( UnixEThread.cc:232        ) 
[ 16 ] traffic_server     EThread::execute()                                     ( UnixEThread.cc:262        ) 
[ 17 ] traffic_server     spawn_thread_internal                                  ( Thread.cc:85              ) 
[ 18 ] libpthread-2.17.so start_thread                                           ( :undefined                )
```

This is from our 7.1.1 based build.  I haven't seen a crash like this on our 7.1.2 based build yet, but we have only started rolling that build out in earnest this week.

**Comment by alficles** [comment]
Ok, I've got a bit more information on this particular bug. It's pretty consistent for us; it happens whenever all the parents of an origin that uses RR DNS are marked down. (It's quite possible that they're flapping up and down, but they're generally speaking not working.)

Here's the stack:

| Function | Location |
| --- | --- |
| __libc_waitpid | undefined:undefined |
| crash_logger_invoke | Crash.cc:164 |
| \<address\> | undefined:undefined |
| raise | undefined:undefined |
| __GI_abort | undefined:undefined |
| ink_abort | ink_error.cc:99 |
| _ink_assert | ink_assert.cc:37 |
| HttpSM::state_http_server_open(int, void*) | HttpSM.cc:1770 |
| HttpSM::main_handler(int, void*) | HttpSM.cc:2629 |
| handleEvent | I_Continuation.h:152 |
| reply_to_cont(Continuation*, HostDBInfo*, bool) | HostDB.cc:479 |
| HostDBContinuation::probeEvent(int, Event*) | HostDB.cc:1703 |
| HostDBContinuation::dnsPendingEvent(int, Event*) | HostDB.cc:1177 |
| handleEvent | I_Continuation.h:152 |
| HostDBContinuation::remove_trigger_pending_dns() | HostDB.cc:1760 |
| HostDBContinuation::dnsEvent(int, HostEnt*) | HostDB.cc:1454 |
| handleEvent | I_Continuation.h:152 |
| DNSEntry::postEvent(int, Event*) | DNS.cc:1271 |
| handleEvent | I_Continuation.h:152 |
| EThread::process_event(Event*, int) | UnixEThread.cc:140 |
| EThread::process_queue(Queue<Event, Event::Link_link>*) | UnixEThread.cc:175 |
| EThread::execute_regular() | UnixEThread.cc:207 |
| spawn_thread_internal | Thread.cc:84 |
| start_thread | undefined:undefined |

Additionally, the state machine history looks like this:

| Location            | Event                          | Reentrancy |
| ------------------- | ------------------------------ | ---------- |
| HttpSM.cc:629       | VC_EVENT_READ_READY            | 1 |
| HttpSM.cc:1298      | HTTP_API_CONTINUE              | 2 |
| HttpSM.cc:1338      | HTTP_API_CONTINUE              | 3 |
| HttpSM.cc:7406      | 65535                          | 3 |
| HttpSM.cc:4542      | 7264                           | 3 |
| HttpCacheSM.cc:118  | CACHE_EVENT_OPEN_READ_FAILED   | -1 |
| HttpCacheSM.cc:118  | EVENT_INTERVAL                 | -1 |
| HttpCacheSM.cc:118  | CACHE_EVENT_OPEN_READ_FAILED   | -1 |
| HttpCacheSM.cc:118  | EVENT_INTERVAL                 | -1 |
| HttpCacheSM.cc:118  | CACHE_EVENT_OPEN_READ_FAILED   | -1 |
| HttpCacheSM.cc:118  | EVENT_INTERVAL                 | -1 |
| HttpSM.cc:837       | VC_EVENT_EOS                   | 1 |
| HttpCacheSM.cc:118  | CACHE_EVENT_OPEN_READ_FAILED   | -1 |
| HttpCacheSM.cc:118  | EVENT_INTERVAL                 | -1 |
| HttpCacheSM.cc:118  | CACHE_EVENT_OPEN_READ_FAILED   | -1 |
| HttpCacheSM.cc:118  | EVENT_INTERVAL                 | -1 |
| HttpCacheSM.cc:118  | CACHE_EVENT_OPEN_READ_FAILED   | -1 |
| HttpSM:2540         | CACHE_EVENT_OPEN_READ_FAILED   | 1 |
| HttpSM.cc:1298      | HTTP_API_CONTINUE              | 2 |
| HttpSM.cc:1338      | HTTP_API_CONTINUE              | 2 |
| HttpSM.cc:7366      | 65535                          | 2 |
| HttpSM.cc:7523      | 65535                          | 2 |
| HttpCacheSM.cc:177  | CACHE_EVENT_OPEN_WRITE_FAILED  | -1 |
| HttpCacheSM.cc:177  | EVENT_INTERVAL                 | -1 |
| HttpSM.cc:2418      | CACHE_EVENT_OPEN_WRITE_FAILED  | 1 |
| HttpSM.cc:7419      | 65535                          | 1 |
| HttpSM.cc:1683      | NET_EVENT_OPEN                 | 2 |
| HttpSM.cc:1938      | EVENT_ERROR                    | 1 |
| HttpSM.cc:5457      | EVENT_ERROR                    | 1 |
| HttpSM.cc:7591      | 65535                          | 1 |
| HttpSM.cc:1938      | VC_EVENT_INACTIVITY_TIMEOUT    | 1 |
| HttpSM.cc:5457      | VC_EVENT_INACTIVITY_TIMEOUT    | 1 |
| HttpSM.cc:7419      | 65535                          | 1 |
| HttpSM.cc:1683      | NET_EVENT_OPEN                 | 2 |
| HttpSM.cc:1683      | EVENT_HOST_DB_LOOKUP           | 1 |

_Our HttpSM.cc has a bit of logging code added. Lines before 7200 are 2 higher than in 7.1.x (44efe9a5c902e953b2ba330aac72c3c69ffb0cf4). Lines after it are 19 higher._

The `last_action` is `SM_ACTION_ORIGIN_SERVER_RR_MARK_DOWN`.

The `t_state->next_action` is `SM_ACTION_ORIGIN_SERVER_OPEN`.

The `t_state->transact_return_point` is `HttpTransact::ReDNSRoundRobin(HttpTransact::State*)`.

The `default_handler` is `HttpSM::state_http_server_open(int, void*)`.

I have a core I can get more information from, if theres anything specific that might help. (For my future reference, it is core 6246.)

**Comment by bryancall** [comment]
@ezelkow1 What do you want to do with this issue?

**Comment by ezelkow1** [comment]
We can close it, we havent seen it since I originally reported and there have been enough hostdb and other crash fixes that it may have been taken care of
