### ISSUE TITLE
7.1.x - mismatch with HttpTransact::ServerState_t and TSServerState

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#2998]
While looking through our crash I got to the ServerState_t enum. It mentions that it should match the TSServerState one.  In ServerState_t it has PARENT_ORIGIN_RETRY as the last entry however in the apidefs.h.in the last state listed for TSServerState is TS_SSRVSTATE_CONGEST_CONTROL_CONGESTED_ON_M

**Comment by maskit** [comment]
It seems like master has the same issue.
