### ISSUE TITLE
7.1.1 crash - assert in HttpSM::parse_range_and_compare

### ISSUE THREAD

**Issue by skyever** [apache/trafficserver#3007]
Fatal: HttpSM.cc:4464: failed assertion `start >= 0 && end >= 0 && start < content_length && end < content_length`
traffic_server: using root directory '/usr'
traffic_server: received signal 6 (Aborted)
traffic_server - STACK TRACE:
/usr/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0xa7)[0x55e7e798eeb7]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110c0)[0x2b85f89df0c0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcf)[0x2b85f96befcf]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x2b85f96c03fa]
/usr/lib/trafficserver/libtsutil.so.7(+0x2c228)[0x2b85f7689228]
/usr/lib/trafficserver/libtsutil.so.7(+0x2a255)[0x2b85f7687255]
/usr/bin/traffic_server(_ZN6HttpSM23parse_range_and_compareEP9MIMEFieldl+0x5c8)[0x55e7e7a84388]
/usr/bin/traffic_server(_ZN6HttpSM14do_range_parseEP9MIMEField+0xda)[0x55e7e7a8487a]
/usr/bin/traffic_server(_ZN6HttpSM27do_range_setup_if_necessaryEv+0xd0)[0x55e7e7a84990]
/usr/bin/traffic_server(_ZN12HttpTransact25build_response_from_cacheEPNS_5StateE15HTTPWarningCode+0x272)[0x55e7e7acd642]
/usr/bin/traffic_server(_ZN12HttpTransact22HandleCacheOpenReadHitEPNS_5StateE+0x4da)[0x55e7e7acdf4a]
/usr/bin/traffic_server(_ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE+0x76)[0x55e7e7a88986]
/usr/bin/traffic_server(_ZN6HttpSM17handle_api_returnEv+0xa2)[0x55e7e7a9f662]
/usr/bin/traffic_server(_ZN6HttpSM17state_api_calloutEiPv+0x46e)[0x55e7e7a958ee]
/usr/bin/traffic_server(_ZN6HttpSM14set_next_stateEv+0x90b)[0x55e7e7aa03db]
/usr/bin/traffic_server(_ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE+0x45)[0x55e7e7a88955]
/usr/bin/traffic_server(_ZN6HttpSM17handle_api_returnEv+0xa2)[0x55e7e7a9f662]
/usr/bin/traffic_server(_ZN6HttpSM17state_api_calloutEiPv+0x46e)[0x55e7e7a958ee]
/usr/bin/traffic_server(_ZN6HttpSM14set_next_stateEv+0x90b)[0x55e7e7aa03db]
/usr/bin/traffic_server(_ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE+0x45)[0x55e7e7a88955]
/usr/bin/traffic_server(_ZN6HttpSM21state_cache_open_readEiPv+0x1bd)[0x55e7e7a97bed]
/usr/bin/traffic_server(_ZN6HttpSM12main_handlerEiPv+0x98)[0x55e7e7a9eec8]
/usr/bin/traffic_server(_ZN11HttpCacheSM21state_cache_open_readEiPv+0x2e0)[0x55e7e7a71ce0]
/usr/bin/traffic_server(_ZN7CacheVC8callcontEi+0x63)[0x55e7e7ba2063]
/usr/bin/traffic_server(_ZN7CacheVC21openReadStartEarliestEiP5Event+0xa12)[0x55e7e7c20062]
/usr/bin/traffic_server(_ZN7CacheVC21openReadStartEarliestEiP5Event+0x566)[0x55e7e7c1fbb6]
/usr/bin/traffic_server(_ZN7CacheVC17openReadStartHeadEiP5Event+0xf10)[0x55e7e7c21320]
/usr/bin/traffic_server(_ZN5Cache9open_readEP12ContinuationPKN3ats10CryptoHashEP7HTTPHdrP21CacheLookupHttpConfig13CacheFragTypePKci+0x90b)[0x55e7e7c1b9eb]
/usr/bin/traffic_server(_ZN11HttpCacheSM9open_readEPK12HttpCacheKeyP3URLP7HTTPHdrP21CacheLookupHttpConfigl+0xc0)[0x55e7e7a71ee0]
/usr/bin/traffic_server(_ZN6HttpSM24do_cache_lookup_and_readEv+0x14f)[0x55e7e7a84cff]
/usr/bin/traffic_server(_ZN6HttpSM14set_next_stateEv+0x848)[0x55e7e7aa0318]
/usr/bin/traffic_server(_ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE+0x45)[0x55e7e7a88955]
/usr/bin/traffic_server(_ZN6HttpSM17handle_api_returnEv+0xa2)[0x55e7e7a9f662]
/usr/bin/traffic_server(_ZN6HttpSM17state_api_calloutEiPv+0x46e)[0x55e7e7a958ee]
/usr/bin/traffic_server(_ZN6HttpSM14set_next_stateEv+0x90b)[0x55e7e7aa03db]
/usr/bin/traffic_server(_ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE+0x45)[0x55e7e7a88955]
/usr/bin/traffic_server(_ZN6HttpSM14set_next_stateEv+0x26a)[0x55e7e7a9fd3a]
/usr/bin/traffic_server(_ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE+0x45)[0x55e7e7a88955]
/usr/bin/traffic_server(_ZN6HttpSM17handle_api_returnEv+0xa2)[0x55e7e7a9f662]
/usr/bin/traffic_server(_ZN6HttpSM17state_api_calloutEiPv+0x46e)[0x55e7e7a958ee]
/usr/bin/traffic_server(_ZN6HttpSM14set_next_stateEv+0x90b)[0x55e7e7aa03db]
/usr/bin/traffic_server(_ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE+0x45)[0x55e7e7a88955]
/usr/bin/traffic_server(_ZN6HttpSM17handle_api_returnEv+0xa2)[0x55e7e7a9f662]
/usr/bin/traffic_server(_ZN6HttpSM17state_api_calloutEiPv+0x46e)[0x55e7e7a958ee]
/usr/bin/traffic_server(_ZN6HttpSM18state_api_callbackEiPv+0x154)[0x55e7e7a9eca4]
/usr/bin/traffic_server(TSHttpTxnReenable+0x2d0)[0x55e7e79c0dc0]
/usr/lib/trafficserver/modules/stats_over_http.so(+0x1828)[0x2b86d4bb8828]
/usr/bin/traffic_server(_ZN15INKContInternal12handle_eventEiPv+0x10e)[0x55e7e79a99ae]
/usr/bin/traffic_server(_ZN6HttpSM17state_api_calloutEiPv+0x2a5)[0x55e7e7a95725]
/usr/bin/traffic_server(_ZN6HttpSM14set_next_stateEv+0x90b)[0x55e7e7aa03db]
/usr/bin/traffic_server(_ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE+0x45)[0x55e7e7a88955]
/usr/bin/traffic_server(_ZN6HttpSM32state_read_client_request_headerEiPv+0x64f)[0x55e7e7a8ff1f]
/usr/bin/traffic_server(_ZN6HttpSM12main_handlerEiPv+0x98)[0x55e7e7a9eec8]
/usr/bin/traffic_server(_ZN6HttpSM17handle_api_returnEv+0x162)[0x55e7e7a9f722]
/usr/bin/traffic_server(_ZN6HttpSM17state_api_calloutEiPv+0x46e)[0x55e7e7a958ee]
/usr/bin/traffic_server(_ZN6HttpSM17state_add_to_listEiPv+0x278)[0x55e7e7a98538]
/usr/bin/traffic_server(_ZN6HttpSM21attach_client_sessionEP22ProxyClientTransactionP14IOBufferReader+0x453)[0x55e7e7a9e783]
/usr/bin/traffic_server(_ZN22ProxyClientTransaction15new_transactionEv+0x130)[0x55e7e79e36e0]
/usr/bin/traffic_server(_ZN18ProxyClientSession17handle_api_returnEi+0x186)[0x55e7e79e2436]
/usr/bin/traffic_server(_ZN18ProxyClientSession14do_api_calloutE12TSHttpHookID+0x3fd)[0x55e7e79e300d]
/usr/bin/traffic_server(_ZN18Http1ClientSession14new_connectionEP14NetVConnectionP9MIOBufferP14IOBufferReaderb+0x35b)[0x55e7e7a74aab]
/usr/bin/traffic_server(_ZN17HttpSessionAccept6acceptEP14NetVConnectionP9MIOBufferP14IOBufferReader+0x184)[0x55e7e7a6d9f4]
/usr/bin/traffic_server(_ZN23ProtocolProbeTrampoline17ioCompletionEventEiPv+0x2a2)[0x55e7e79e1f02]
/usr/bin/traffic_server(+0x3bb11d)[0x55e7e7c7d11d]
/usr/bin/traffic_server(+0x3c0361)[0x55e7e7c82361]
/usr/bin/traffic_server(_ZN10NetHandler12mainNetEventEiP5Event+0x2d5)[0x55e7e7c6cdf5]
/usr/bin/traffic_server(_ZN7EThread13process_eventEP5Eventi+0x1b3)[0x55e7e7cacca3]
/usr/bin/traffic_server(_ZN7EThread7executeEv+0x1276)[0x55e7e7cae8b6]
/usr/bin/traffic_server(+0x3ea4de)[0x55e7e7cac4de]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7494)[0x2b85f89d5494]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x2b85f9774aff]

**Comment by bryancall** [comment]
If this is still an issue please reopen.
