### ISSUE TITLE
Parent selection - Multi Site Origin logging oddities

### ISSUE THREAD

**Issue by MattMills** [apache/trafficserver#3012]
When using multi site origin there are a few quirks in the logs where it doesn't log as it normally would, or as expected. phr gets logged as EMPTY where normally it'd log DIRECT, and shn can get logged using the "wrong" hostname (not the server it actually accessed), although that may just be that the intention of that field is unclear within the docs and it is logging what is expected.

**Comment by vmamidi** [comment]
are you still seeing this issue?

**Comment by MattMills** [comment]
Unknown, I don't run Traffic Server anymore, sorry. Feel free to close.
