### ISSUE TITLE
Unknown configure option --enable-system-luajit for 7.1.2

### ISSUE THREAD

**Issue by jbfavre** [apache/trafficserver#3041]
Despite what CHANGELOG & documentation say regarding this option (announced in 7.1.0), I can't find it for 7.1.2.
Any plan to add it before 8.0 ?

**Comment by shukitchan** [comment]
It is at least here in the master - https://github.com/apache/trafficserver/blob/master/configure.ac#L319-L328

**Comment by shukitchan** [comment]
It is added by this PR - https://github.com/apache/trafficserver/pull/1494

**Comment by shukitchan** [comment]
But i think you are right. I can't find this being included in 7.1.2

**Comment by shukitchan** [comment]
perhaps @zwoop can shed some lights here.

**Comment by jbfavre** [comment]
> But i think you are right. I can't find this being included in 7.1.2
@shukitchan didn't find it either

**Comment by bryancall** [comment]
We always use the system luajit now.
