### ISSUE TITLE
Dual Live Origin Ingest Race Feature

### ISSUE THREAD

**Issue by ryandurfey** [apache/trafficserver#3067]
A live video customer runs two live origins in separate locations.  Because live content latency is so critical, they want the CDN to attempt to ingest each live video request from both origins simultaneously.  Requests both start at the same time from the same mid tier, whichever finishes first with a 200 or 206 response is kept and the other is dropped.  

@ryandurfey
@ashish-timilsina
@PSUdaemon

**Comment by jrushford** [comment]
I have misgivings about this approach.  I don't like the idea of opening multiple connections like this for one request, it could lead to problems using resources like this.

Currently we're working on the next hop feature which eventually will allow plugins to do next hop selection (parent/origin).  What do you think of a plugin that measures the response time of a request to an origin and then the plugin would always select the parent with the lowest response time.  the measurements would be updated after each request.

**Comment by ryandurfey** [comment]
@jrushford The user rescinded this request. This request can be closed.
