### ISSUE TITLE
CACHE: dest_domain don't work.

### ISSUE THREAD

**Issue by elmemis** [apache/trafficserver#3071]
In server 1.1.1.1 has Apache web server 2.4.29 on port 443 with: 
```
domain1.com -> Wordpress
domain2.com -> Wordpress
domain3.com -> Custom site
domain4.com -> Custom site on local.domain4.com
```

In server 1.1.1.2 has ATS 7.1.2 on port 443:

in records.config: 
```
CONFIG proxy.config.url_remap.remap_required INT 1
CONFIG proxy.config.url_remap.pristine_host_hdr INT 0
CONFIG proxy.config.reverse_proxy.enabled INT 1
```

in remap.config:
```
map https://domain1.com/ https://1.1.1.2/ @plugin=conf_remap.so @pparam=proxy.config.url_remap.pristine_host_hdr=1
map https://domain2.com/ https://1.1.1.2/ @plugin=conf_remap.so @pparam=proxy.config.url_remap.pristine_host_hdr=1
map https://domain3.com/ https://1.1.1.2/ @plugin=conf_remap.so @pparam=proxy.config.url_remap.pristine_host_hdr=1
map https://domain4.com/ https://local.domain4.com/
```

in cache.config:
```
dest_domain=domain1.com pin-in-cache=1h
dest_domain=domain2.com action=never-cache
dest_domain=domain3.com revalidate=3h
dest_domain=domain4.com action=ignore-no-cache
```
This config don't work.

```
dest_host=1.1.1.2 pin-in-cache=1h
dest_domain=local.domain4.com action=ignore-no-cache
```
This config work. With this config can't discriminate domain1.com, domain2.com, domain3.com resources. For example, domain1.com and domain2.com have same paths and files but I need no cache domain2.com.

**Comment by mlibbey** [comment]
In other files dest_host is a specific hostname, whereas dest_domain matches all subdomains. For instance, in parent.config, dest_domain=example.com would match both foo.example.com and example.com, while dest_host=example.com would only match example.com, not foo.example.com. Want to try that?

In general I'd recommend staying away from cache.config. IMHO pin-in-cache is a real corner case -- if an object is not popular enough to remain in cache, its unusual to make ATS remove a more recently requested thing in its favor.

For domain=2, this would be equivalent:
map https://domain2.com/ https://1.1.1.2/  @plugin=conf_remap.so @pparam=proxy.config.url_remap.pristine_host_hdr=1 @pparam=proxy.config.http.cache.http=0

For domain4, I'd use another header_rewrite to get replace Cache-Control matching no-store with some other value.

**Comment by elmemis** [comment]
My problem is dest_domain, not pin, action, revalidate or other. When use remap.config with map to host IP address and set pristine_host_hdr to 1 on remap.config line, dest_domain it stop working with domain name.

When use remap.config with pristine to 1, Primary Destinations of the cache.config file equals to destination map. I need Primary Destinations of the cache.config file equals to primary (origin) destination of map file.

For example:
```
map https://domain1.com/ https://1.1.1.2/ @plugin=conf_remap.so @pparam=proxy.config.url_remap.pristine_host_hdr=1
```
Primary destination of the cache.config is: https://1.1.1.2/.

Sorry my bad english.

**Comment by SolidWallOfCode** [comment]
The root issue here is `cache.config` uses post-remap data, e.g. the proxy request and not the client request. Therefore if various domains are remapped to the same upstream, `cache.config` can't distinguish between them. On the other hand, I'm not sure I see why that would be useful - why cache something differently from the same upstream depending on which the inbound request? That would give you some odd race conditions, the cache state depending on which particular client first requested the resource.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
