### ISSUE TITLE
How to get cache object overtime?

### ISSUE THREAD

**Issue by sangli00** [apache/trafficserver#3093]
eg: header Max-age 
what time cache object is release in cache?
could you ask me about this code in Trafficserver ?

**Comment by mlibbey** [comment]
There is an Age: header that reports the current age of the object. It would become stale when the Age value exceeds the max-age.

**Comment by zwoop** [comment]
Looking at the proxy.process.cache.wrap_count metrics is probably the best way to see how long objects *typically* stay in the cache.

**Comment by bryancall** [comment]
You can do use the Age header if the origin doesn't supply an Age header.  ATS logs when the cache wraps and that would be the maximum age of objects in cache.
