### ISSUE TITLE
Parent Selection with HTTP/2 has performance issue

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#3100]
# Summary
We found weird performance issue with parent.config. Using h2load, requests with HTTP/1.1 seems ok, but some requests (2 ~ 9%) with HTTP/2 is failed.

# Conditions
- Origin server is running on 127.0.0.1:8001. 
- ATS has below configs
  - HEAD of 7.1.x branch (eeae4118315283dc188249a4f3c7826836a4b4cb)
  - records.config and ssl_multicert.config has some changes to enable HTTP/2 on 4443
  -  parant.config
  ```
  dest_domain=. parent="localhost:8001" round_robin=consistent_hash
  ```
  - remap.config
  ```
  map / http://127.0.0.1:8001/
  ```
- 100KB content is cached

# Tests
## HTTP/2
```
$ h2load -n 10000 -m 100 -c 2 https://127.0.0.1:4443/100k
starting benchmark...
spawning thread #0: 2 total client(s). 10000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 5.87s, 1661.31 req/s, 162.37MB/s
requests: 10000 total, 10000 started, 10000 done, 9744 succeeded, 256 failed, 256 errored, 0 timeout
status codes: 9744 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 952.34MB (998598258) total, 105.15KB (107676) headers (space savings 96.39%), 951.56MB (997785600) data
                     min         max         mean         sd        +/- sd
time for request:      954us       1.90s    112.14ms    160.98ms    96.13%
time for connect:     5.43ms      8.64ms      7.03ms      2.27ms   100.00%
time to 1st byte:   440.40ms    444.99ms    442.69ms      3.24ms   100.00%
req/s           :     808.84      966.39      887.62      111.40   100.00%
```

## HTTP/1.1
```
$ h2load --h1 -n 10000 -m 100 -c 2 https://127.0.0.1:4443/100k
starting benchmark...
spawning thread #0: 2 total client(s). 10000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
Application protocol: http/1.1
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 2.90s, 3453.07 req/s, 338.46MB/s
requests: 10000 total, 10000 started, 10000 done, 10000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 10000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 980.18MB (1027790000) total, 3.01MB (3160000) headers (space savings 0.00%), 976.56MB (1024000000) data
                     min         max         mean         sd        +/- sd
time for request:      622us    366.62ms     51.13ms     59.50ms    88.65%
time for connect:     3.47ms      3.52ms      3.50ms        39us   100.00%
time to 1st byte:     4.04ms      4.97ms      4.50ms       660us   100.00%
req/s           :    1726.73     2223.60     1975.17      351.34   100.00%
```

**Comment by masaori335** [comment]
I couldn't try this with latest master by another bug.

**Comment by maskit** [comment]
another bug == #3101

**Comment by masaori335** [comment]
When requests faild, TS sends RST frame and I'm seeing below error log.
```
[Feb  9 15:23:34.824] Server {0xb0016000} DEBUG: <Http2ConnectionState.cc:202 (rcv_headers_frame)> (http2_con) [1] [937] Received HEADERS frame
[Feb  9 15:23:34.824] Server {0xb0016000} DEBUG: <Http2ConnectionState.cc:1565 (send_rst_stream_frame)> (http2_con) [1] [937] Send RST_STREAM frame
```

```
[Feb  9 16:02:59.870] Server {0xb0016000} ERROR: HTTP/2 stream error client_ip=127.0.0.1 session_id=1 recv headers creating inbound stream beyond max_concurrent limit
```

But I'm not sure, how parent.config effects concurrent stream number.

**Comment by masaori335** [comment]
I add debug logs on increment/deceement `client_streams_in_count`. (https://paste.apache.org/vCwi)
And I counted some logs until first “Send RST_STREAM FRAME” appears.

```
 752  ++client_streams_in_count
 652  --client_streams_in_count
 657  Delete stream
 753  Received HEADERS frame
   1  Send RST_STREAM frame
```

This means `delete_stream` is already called (client will open new stream), but the `client_streams_in_count` is not decremented. Currently the `client_streams_in_count` is decremented by `release_stream`, so it's possible if event processor is too busy.

So we have 2 issues.

a) `client_streams_in_count` is not decremented correctly when event processor is busy.
b) the settings of parent.config make ATS slow

**Comment by masaori335** [comment]
Still wondering why the parent.config trigger the problem.
@vmamidi @jrushford Could you take a look?

**Comment by masaori335** [comment]
1. parent.config and dns reverse lookup
When some rules are written in parent.config, it triggers SM_ACTION_DNS_REVERSE_LOOKUP regardless value of `proxy.config.http.parent_proxy_routing_enable` in records.config.
https://github.com/apache/trafficserver/blob/e4aa18e3337929bb1c9dc4272f369c86a1325c61/proxy/http/HttpTransact.cc#L1701-L1705

2. HTTP/1.1 vs HTTP/2
As for HTTP/1.1, only one transaction is proceeded on one connection. So only one dns query is scheduled.
As for HTTP/2, some transactions (up to 100) are proceeded on one connection simultaneously. So many dns queries are scheduled in same time. IMO this made event processor busy and triggered the problems. Below is metrics of eventloop against master. You can see huge spike of HTTP/2 with  the parent.config.

![screen shot 2018-02-20 at 11 10 28](https://user-images.githubusercontent.com/741391/36404763-0a638b4a-1630-11e8-9233-4db417545f1e.png)
