### ISSUE TITLE
Collect tcp_info log at end of the TCP connection in tcpinfo plugin.

### ISSUE THREAD

**Issue by NilooF** [apache/trafficserver#3138]
Please collect either the full tcp_info log or at least the following fields, right before end of the connection:
tcpi_total_retrans
tcpi_rtt
tcpi_rttvar
tcpi_lost
tcpi_unacked
tcpi_sacked
tcpi_fackets
tcpi_bytes_acked
tcpi_bytes_received
tcpi_delivery_rate_app_limited
tcpi_delivery_rate

Thanks
Niloofar

**Comment by zwoop** [comment]
Note that you, the user, control when / where you collect this. The end of the session might not work, we'll have to look into that.

Which of the above are missing from the "full" log? Most if not all of those should be there already.

**Comment by NilooF** [comment]
What is missing is the difference of the two:
tcpi_total_retrans
tcpi_bytes_acked
tcpi_bytes_received
tcpi_delivery_rate_app_limited
tcpi_delivery_rate

Thanks

**Comment by zwoop** [comment]
Curious as to what tcpi_total_retrans is vs tcpi_retrans ? @PSUdaemon  ?

**Comment by NilooF** [comment]
Hi Leif,
As far as I understand, tcpi_total_retrans is the cumulative number of retransmissions during the life of a TCP connection whereas tcpi_retrans is more of the count of the currently queued retransmissions in flight.
Hence tcpi_retrans seems to be a subset of tcpi_total_retrans

Probably the same applies for tcpi_lost, which may be why all the values  for tcpi_lost and tcpi_retrans in the collected log are zero.

Thanks
Niloofar

**Comment by zwoop** [comment]
Ok, well, we can add tcpi_total_retrans, but the others would be a no-go I think, unless someone else has a brilliant solution how to get those in the normal getsockopt APIs.

**Comment by NilooF** [comment]
Thanks Leif!
Are the changes in #3153 already deployed in USDEN5?

Thanks
Niloofar
