### ISSUE TITLE
example plugins don't build in jenkins

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#3149]
https://ci.trafficserver.apache.org/job/autest-github/3836/consoleFull Failed because 
```
checking whether to install example plugins... no
```

However, I checked `ci/jenkins`. Seems they have --enable-example-plugins.
For plugins and experimental-plugins, they get built and autests against them work well.
I also noticed there are some plugins duplicated in `tests/tools/plugins/`, which I don't think is the right way.

@zwoop @dragon512 @scw00 @SolidWallOfCode @bryancall

**Comment by bryancall** [comment]
If this is still an issue please reopen.
