### ISSUE TITLE
HAVE_POSIX_MEMALIGN might not useful anymore

### ISSUE THREAD

**Issue by duke8253** [apache/trafficserver#3151]
Tracking down some memory related issues and noticed that in certain places we still check for `HAVE_POSIX_MEMALIGN`. The man page states that `posix_memalign()` is available since glibc 2.1.91, so I'm wondering what is the version of glibc we support, if it is newer than 2.1.91 we can just remove the define and checks, and use `posix_memalign()` by default.

**Comment by SolidWallOfCode** [comment]
What version of the compiler does that correspond to? Also, what's the `glibc` version on say CentOS 7 base?

**Comment by duke8253** [comment]
From https://distrowatch.com/table.php?distribution=centos, CentOS 2.0 was using 2.2.4. And it looks like 7.1708 ships with 2.17, 6.9 ships with 2.12.

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
