### ISSUE TITLE
Missing documentation on TLS settings from ATS to origin

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#3162]
Noted by motherclangercs on the IRC.  The proxy.config.ssl.server.cipher_suite is documented, but not the proxy.config.ssl.client.cipher_suite.  Similarly the ATS to origin settings for the TLS protocols allowed are not documented.  Possibly other ATS to origin TLS settings are also missing.

**Comment by persiaAziz** [comment]
PR for documentation of origin side cipher_suite. 
https://github.com/apache/trafficserver/pull/3370

The protocol versions are already documented in the doc of records.config
