### ISSUE TITLE
Retransmit Initial Packet will create new QVC

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#3167]
Retransmit Initial Packet will select new connection id. We will create a new qvc for every new connection id.

**Comment by scw00** [comment]
Spec says 
>The client populates the connection ID field with randomly selected values, unless it has received a packet from the server.

I'm not sure what it means.

**Comment by scw00** [comment]
Also we should not create new qvc with the same connection id in retransmit initial packet.

**Comment by masaori335** [comment]
Current spec (draft-14) says below in 4.6.1.  Connection IDs
> Until a packet is received from the server, the client MUST use the same value unless it abandons the connection attempt and starts a new one.

And current quic-latest branch (83dfc5a) doesn't create new QUICNetVC when it retransmit INITIAL packet.
