### ISSUE TITLE
Call to setsockopt fails when running in a container

### ISSUE THREAD

**Issue by larytet** [apache/trafficserver#3182]
Hi,

My host system is Ubuntu 17.10, Docker container CentOS 6.7
`./configure --prefix=/ --enable-debug`
I am using sources of ATS 5.3.2
I am getting 
`[Feb 25 12:42:56.725] Server {0x7f9afe5b0800} ERROR: [Server::listen] Unable to set transparent socket option [1] Operation not permitted`
It looks like the following call fails 
`setsockopt(fd, SOL_IP, TS_IP_TRANSPARENT, SOCKOPT_ON, sizeof(int))`
I tried to add --disable-posix-cap. This resolves the issue, but then I get assert similar to https://github.com/apache/trafficserver/issues/2483 

What am I missing?
Is it possible to run the ATS with root privileges?

**Comment by larytet** [comment]
I did the following 

diff --git a/trafficserver-etc/records.config b/trafficserver-etc/records.config
index 00efa5283..7d9011430 100644
--- a/trafficserver-etc/records.config
+++ b/trafficserver-etc/records.config
@@ -50,7 +50,7 @@ CONFIG proxy.config.accept_threads INT 4
 CONFIG proxy.config.admin.admin_user STRING admin
 CONFIG proxy.config.admin.number_config_bak INT 3
 
-CONFIG proxy.config.admin.user_id STRING ats
+CONFIG proxy.config.admin.user_id STRING  #-1
 ``
 CONFIG proxy.config.task_threads INT 2
 CONFIG proxy.config.cache.threads_per_disk INT 8
``
Solved the problem

**Comment by bryancall** [comment]
If this is still an issue please reopen.
