### ISSUE TITLE
Create a Web Application Firewall Plugin (modsecurity?)

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#3186]
It would be great if we had a Web Application Firewall option for traffic server.  Porting modsecurity into a traffic server plugin would be a reasonable place to start looking 
https://www.modsecurity.org/

modsecurity seems to have gained acceptance and is supposed via nginix, Apache Httpd, and IIS.

GSoC Jira COMDEV-272 points at this issue.

**Comment by shukitchan** [comment]
interesting. I am actually working on that myself in my spare time.

**Comment by phonehold** [comment]
@shukitchan  good jobs, is there an open code plan point in time?

**Comment by shukitchan** [comment]
Here is what I have so far and what I was planning to do

https://github.com/shukitchan/ats-luajit-modsecurity

**Comment by shukitchan** [comment]
@bryancall 
my work on modsecurity integration is mostly finished and is in my own repo.
you want me to move my script over to example directory?

**Comment by shinrich** [comment]
@shukitchan did you add your script to the example directory?  Andrey has also worked with https://github.com/VerizonDigital/waflz.  Will talk with him to see what makes sense to share there.

**Comment by shukitchan** [comment]
not yet . it is here for now - https://github.com/shukitchan/ats-luajit-modsecurity
Andrey also has worked with my code as well for his works. 

I can try my script to the example directory later this week.
