### ISSUE TITLE
ATS lack of API to temporarily reload remap file from specified file

### ISSUE THREAD

**Issue by shenzhang920** [apache/trafficserver#3210]
Currently, ATS reload remap file by calling reloadUrlRewrite(), the filename is fixed (either default "remap.config" or configured by "proxy.config.url_remap.filename").  But if ATS crashes after reloading remap.config (due to some bug in some remap plugin), ATS will keep crashing since the remap.config is always bad.  We have a module which can periodically detect if there's new remap.config available and reload that file.  We would like to do is saving the new file as remap_temp.config and reload that; if after a period of time and the ATS is running normal, we rename remap_temp.config to remap.config.   In this case, if remap_temp.config has issue, ATS crashes; ATS can start up normal by using the old remap.config.
Currently, ATS doesn't have API to reload a specified remap file.  I would like to add another API - reloadUrlRewrite(const char *filename) to reload a remap file to achieve this goal.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
