### ISSUE TITLE
broken acl with special requests

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#3259]
multiple slash can bypass mappings.

regex_map http://(.*).example.com/internal/ http://$1.orig.example.com/inernal/ @plugin=regex_remap.so @pparam=xxx.conf

when access http://(.*).example.com////internal/, the above config will not take effect.

**Comment by esmq2092** [comment]
i wonder it was a bug or i miss something...

**Comment by SolidWallOfCode** [comment]
It's hard to imagine a general rule that covers this, without breaking other things. What can be done is to have a "catch all" rule after which would route anything matching `example.com` to an error page. Then success requires a positive match of a rule.

**Comment by bryancall** [comment]
I don't think we should collapse slashes by default.  If you want to normalize URLs you should do this in a plugin with your own business logic.

**Comment by zwoop** [comment]
You can move the path matching (all of it) to the regex_remap.so plugin, which can then deal with such odd cases and collapsing. Like

```
regex_map http://(.*).example.com http://whatever @plugin=regex_remap.so @pparam=host @pparam=regexes.conf
```

Then in regexes.conf, you have to match the host again, as well as dealing with ///'s etc. and then do the entire rewrite there.
