### ISSUE TITLE
Cache clustering in 7.1.2

### ISSUE THREAD

**Issue by jaymalya** [apache/trafficserver#3260]
Hello, 

Sorry if this question is already asked & answered. I have been struggling to get cache clustering to work in TS 7.1.2. All Config parameters seem to exist & configured properly. However, diags.log always throw this - NOTE: cache clustering disabled.

I read the clustering is removed in 8.0 - is that true for 7.1.2 as well?

Thx

Jay

**Comment by ling-zhou** [comment]
You can use: 

**hash key [consistent];**

docs: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#hash

**Comment by bryancall** [comment]
We have removed clustering the code.  We have moved to use parent selection with the ability to have all the servers operate as peers and server with the incoming request to identify itself and not route again to itself.
