### ISSUE TITLE
Null dereference in PluginVC.cc

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#3310]
VIO *
PluginVC::do_io_read(Continuation *c, int64_t nbytes, MIOBuffer *buf)
{
....  
read_state.vio.mutex     = c->mutex;

This is called from HttpTunnel::producer_handler(int event, HttpTunnelProducer *p)
{
....
      p->vc->do_io_read(nullptr, 0, 0);
.....

So when you hit these 4 VC events it looks like it will always crash since there are no checks on the continuation in do_io_read

**Comment by calavera** [comment]
This can be closed @SolidWallOfCode: https://github.com/apache/trafficserver/pull/3311

**Comment by SolidWallOfCode** [comment]
Cool.
