### ISSUE TITLE
100 continue documentation is wrong

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#3328]
I'm pretty certain that ATS support the Expect header and 100 continue.  I've tested this in the past, and I just looked through the code and there is support in there.

Someone internally claimed it wasn't supported because of a FAQ note in the 5.3 documentation.  In fact it is in the current documentation https://docs.trafficserver.apache.org/en/latest/appendices/faq.en.html?highlight=expect#support-for-http-expect-header

It seems like we should update the docs or remove some code.

**Comment by Tchinmai7** [comment]
@shinrich Should we remove update the docs? I have tested that it works in ATS 7.1.1

**Comment by shinrich** [comment]
Fixed with PR #4527.  Two people verified that the feature works.
