### ISSUE TITLE
Can't compile with --enable-fips option again

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#3335]
```
Making all in traffic_cache_tool
  CXX      CacheDefs.o
In file included from CacheDefs.cc:24:
In file included from ./CacheDefs.h:28:
../../lib/ts/INK_MD5.h:34:3: error: unknown type name 'MD5_CTX'
  MD5_CTX _ctx;
  ^
1 error generated.
```

**Comment by maskit** [comment]
@SolidWallOfCode

**Comment by persiaAziz** [comment]
let me know if you are seeing this again. I don't see this on my end. It should get fixed by #3466

**Comment by maskit** [comment]
Why CacheDefs.h has own `struct Doc`? It's in iocore/cache/P_CacheVol.h and seems like FIPS ready.

**Comment by SolidWallOfCode** [comment]
The goal, which has somewhat fallen by the wayside, was to test new and improved data structures in the CacheTool and then back port them in to the TS cache.

**Comment by maskit** [comment]
Closing. I don't see the error now.
