### ISSUE TITLE
Performance tests related to freelist and jemalloc.

### ISSUE THREAD

**Issue by duke8253** [apache/trafficserver#3354]
![1](https://user-images.githubusercontent.com/7103785/37995789-3a098b76-31db-11e8-8831-1e67ab85df79.png)
![2](https://user-images.githubusercontent.com/7103785/37995799-3e6b4858-31db-11e8-985a-4f7a597ac027.png)

Default = with freelist
Old Disable Freelist = -f option
New Disable Freelist = -f option and disable freelist in ProxyAllocator
jemalloc = New Disable Freelist and compiled with jemalloc

**Comment by chassell** [comment]
How is it going?  Looked at my code at all .. or just got a smaller version of it going?

**Comment by duke8253** [comment]
We're breaking it into tiny tiny parts. :-)

**Comment by mingzym** [comment]
nice work, numbers always better than anything else. add oil 加油！
