### ISSUE TITLE
⛱ QUIC Client for testing and Origin Server Side Connection

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#3381]
This is an umbrella ticket to track quic client of ATS. The purposes of client side implementation are a) self-test b) origin server side quic connection. Currently, a command line tool called `traffic_quic` is on going for a).

## QUIC Specific Features
- [x] Version Negotiation
- [x] Handshake
- [x] Stream Data
- [x] Connection Close
- [x] Resumption
- [ ] 0-RTT
- [x] Stateless Retry
- [ ] Stateless Reset
- [x] Address Validation (#4672)
- [x] HTTP/3

**Comment by masaori335** [comment]
Resumption is done by #4405. Thanks @scw00.

**Comment by maskit** [comment]
Added Address Validation (#4672).

**Comment by maskit** [comment]
Closing as the client implementation has not been maintained since we start using quiche and the client is no longer built.
