### ISSUE TITLE
QUIC: Should not pend RTO retransmitted packet

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#3385]
>A packet sent on an RTO alarm MUST NOT be blocked by the sender’s congestion controller. A sender MUST however count these bytes as additional bytes in flight, since this packet adds network load without establishing packet loss.

**Comment by bryancall** [comment]
@maskit is this still an issue?

**Comment by maskit** [comment]
yes it is.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
