### ISSUE TITLE
Assert failing in master

### ISSUE THREAD

**Issue by persiaAziz** [apache/trafficserver#3428]
chrisr-cs informed on IRC about assert failure happening in master with server verification enabled. This is happening when the origin certificate verification is failing.

Backtrace:

https://pastebin.com/HnUAvmPS

**Comment by mlibbey** [comment]
@shinrich

**Comment by bryancall** [comment]
If this is still an issue please reopen.

**Comment by bryancall** [comment]
@shinrich Can you check to see if this is still an issue before the 9.0.0 release?

**Comment by zwoop** [comment]
@randall  I tried reproducing this on master, with a map rule of

```
map /foo https://localhost:81
```

And then a request of

```
curl https://calculus.ogre.com/foo/
```

It did not crash. Is there some other setting I must enable ?

**Comment by shinrich** [comment]
The later commit 5a759ed4 also cleans up server_entry in the error case not just the timeout case.  Based on the original gist that @persiaAziz posted, it was the error event causing the problem.

**Comment by shinrich** [comment]
I tried both the scenario that @randall described and the origin server verification case that @persiaAziz identified.  The tunnel.alive == false assert is not going off.  Given that there have been a number of cleanups on the connection error path in the past year, I assume this issue has been addressed.  Closing.  Please reopen or open a new issue if this still a problem in 9.x.
