### ISSUE TITLE
Use RTT when calculating remaining credit of flow control

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#3431]
> To avoid blocking a sender, and to reasonably account for
   the possibiity of loss, a receiver should send a MAX_DATA or
 MAX_STREAM_DATA frame at least two roundtrips before it expects the
   sender to get blocked.

**Comment by scw00** [comment]
How to get smooth rtt in QUICStream ? Should we save the pointer for loss detector ?

**Comment by maskit** [comment]
That would be a simplest way. I'd introduce `RTTProvider` interface if we are going to go that way because "Loss Detector" is not needed for flow control.

**Comment by scw00** [comment]
It seems we need to calculate the average  recv rate to "expect"  the sender to get blocked.

**Comment by maskit** [comment]
Yes, we need that too.

Receiver should send MAX_DATA frame before remaining credit gets lower than the calculated value (average recv rate * smoothed rtt * 2).

**Comment by maskit** [comment]
Closed with  #3441
