### ISSUE TITLE
Add doc Makefile target to detect absence of --enable-docs

### ISSUE THREAD

**Issue by d2r** [apache/trafficserver#3432]
I tried to build documentation by going to `/docs` and typing `make html`. The `sbuild` tool exited with `1` and did not give any error.

It would be nice to add a simple target that detects when documentation building has not been configured.

Our documentation for how to build the documentation is [here](https://docs.trafficserver.apache.org/en/latest/developer-guide/documentation/building.en.html).

**Comment by SolidWallOfCode** [comment]
I presume this is covered by #3925 and #3951.

**Comment by d2r** [comment]
Good catch @SolidWallOfCode.
