### ISSUE TITLE
Has the code of QUIC support been open sourced? 

### ISSUE THREAD

**Issue by caozhihua12** [apache/trafficserver#3442]
Looks like traffic server has supported quic:
https://cwiki.apache.org/confluence/display/TS/QUIC
But I didn't find the related code.

**Comment by scw00** [comment]
Hi, you can switch to quic-latest branch.

**Comment by caozhihua12** [comment]
Thanks very much.
Can I ask some questions about the quic implementation?
1.Traffic serverSome applications are multiple threads support which share a single listening socket. If thread1 processes part of a http request using QUIC, how can we guarantee the remaining request also can be delivered to the same thread? 
2.The connection ID table is global or per thread? 
3.If 2 clients use same connection id, how can traffic server handle it?

**Comment by scw00** [comment]
>1.Traffic serverSome applications are multiple threads support which share a single listening socket. If thread1 processes part of a http request using QUIC, how can we guarantee the remaining request also can be delivered to the same thread?

Every request should be bound with a thread . Searching the connections table and finding the corresponding thread when request is coming.

> 2.The connection ID table is global or per thread?

It is global

3.If 2 clients use same connection id, how can traffic server handle it?

Prefer to use the connection id connection ID that the server has chosen.

**Comment by caozhihua12** [comment]
Thanks very much for your reply!

3.If 2 clients use same connection id, how can traffic server handle it?

Prefer to use the connection ID that the server has chosen. Also 5-tuple can help us to distinguish different clients.

If the connection migrated and 5-tuple may be changed, how does TS handle it?

**Comment by scw00** [comment]
spec says 
```
To ensure that the client is
   not linkable across each of these changes, a new connection ID and
   packet number gap are needed for each network.  To support this, a
   server sends multiple NEW_CONNECTION_ID messages.  Each
   NEW_CONNECTION_ID is marked with a sequence number.  Connection IDs
   MUST be used in the order in which they are numbered.
```

So ats will dispatch several NEW_CONNECTION_IDs to client. Client should use one of them when connection migrated. Otherwise ats will give a connection error to client.
