### ISSUE TITLE
How does Traffic Server process the http request which in 2 QUIC packets?

### ISSUE THREAD

**Issue by caozhihua12** [apache/trafficserver#3443]
Hi,
I have some questions about QUIC support in TS, could you help answer it?
1.Traffic server is multiple threads support which share a single listening socket. If thread1 processes part of a http request using QUIC, how can we guarantee the remaining request also can be delivered to the same thread?
2.The connection ID table is global or per thread?
3.If 2 clients use same connection id, how can traffic server handle it?

**Comment by scw00** [comment]
Closing now. Your answer is in #3442 , if you have any question, please feel to ask on dev@trafficserver.apache.org or open another issue.
