### ISSUE TITLE
Run clang-tidy

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#3455]
Add "clang-tidy-local" target to quic/ and run it before merging quic-latest to master.

**Comment by maskit** [comment]
clang-tidy targets for quic/ and http3/ were updated 2a2107c11af28726bc568512c185b26b2b782ef6

**Comment by bryancall** [comment]
@maskit Please do this before merging to master.

**Comment by maskit** [comment]
I forgot we have an issue for clang-tidy on QUIC. It was ran, and draft-20 support is already merged
