### ISSUE TITLE
When and where to unschedule the path validation event

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#3457]
It seems we didn't unschedule the path validation event even if path validation succeed.

**Comment by maskit** [comment]
Confirmed. The event happens and QNetVC switches to close state.

A lazy way is that let the event happen, check the result in a event handler, and switch to close state only if the result is failure.

**Comment by maskit** [comment]
I think this was resolved with 5fa569877e56cdddb0bae36effd61140b3218809 and fd837f81d9.
