### ISSUE TITLE
Set proxy.config.cache.auto_clear_stripe=0 default in ATS 8.0

### ISSUE THREAD

**Issue by djcarlin** [apache/trafficserver#3482]
I propose making proxy.config.cache.auto_clear_stripe disabled by default in ATS 8.0

We had an unknown issue where cache was wiped on start for a couple machines running ATS 7.  I think its safer to disable this behavior by default and instead prevent ATS from starting for further troubleshooting.

**Comment by zwoop** [comment]
Why didn't you make a PR? :-).

**Comment by bryancall** [comment]
@djcarlin I don't see this option in open source.  If this is still an issue please reopen.

**Comment by bryancall** [comment]
It looks like it is an internal change that wasn't open sourced.

**Comment by bryancall** [comment]
@SolidWallOfCode We should decided if we should auto clear or not.  Please take this to the mailing list.

**Comment by SolidWallOfCode** [comment]
This was never back ported to open source, it was a Verizon only patch to see if it was reasonable. Given @djcarlin's reaction I think we should close this issue and leave it out of ATS 9 entirely.
