### ISSUE TITLE
Remove AdminClient.pm

### ISSUE THREAD

**Issue by xf6wang** [apache/trafficserver#3515]
I this file https://github.com/apache/trafficserver/blob/master/lib/perl/lib/Apache/TS/AdminClient.pm used anywhere? If not it should be removed. If it is used, it must also change with any changes to the RPC protocol (ie. adding type info headers in #3504).

**Comment by SolidWallOfCode** [comment]
The problem is that it isn't used inside Traffic Server but may well be used by third parties. It would be interesting to see if any of the [Traffic Control](https://trafficcontrol.incubator.apache.org) code uses that interface.

**Comment by bryancall** [comment]
We use this for internal tools at our company.
