### ISSUE TITLE
Can "traffic_ctl config describe" report which settings are overridable via conf_remap?

### ISSUE THREAD

**Issue by djcarlin** [apache/trafficserver#3546]
I would be handy if `traffic_ctl config describe <setting>` reported if a setting was overridable via conf_remap

This list seems incomplete: https://cwiki.apache.org/confluence/display/TS/conf_remap+Plug-In

Some settings mention if they are overridable: 

https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html

**Comment by SolidWallOfCode** [comment]
That should be the case. If it's not, it's a bug in the description of the overridable config or the implementation of the configuration variable.

**Comment by mlibbey** [comment]
Is there a config that you are finding missing djcarlin? 
eg.
$ traffic_ctl config describe proxy.config.url_remap.pristine_host_hdr
Name            : proxy.config.url_remap.pristine_host_hdr
Current Value   : 1
Default Value   : 0
Record Type     : standard config
Data Type       : INT
Access Control  : default
**Update Type     : dynamic, no restart**
Update Status   : 0x0
Source          : administratively set
Syntax Check    : integer with a specified range, '[0-1]'
Version         : 0
Order           : 396
Raw Stat Block  : 0

**Comment by djcarlin** [comment]
So if something is **dynamic** that means its overridable via conf_remap?

For example, proxy.config.http2.no_activity_timeout_in is "dynamic, no restart" but I have tried to set it via conf_remap and it doesn't work.  Using 7.1.2

In fact, all of the proxy.config.http2.* settings (except http2.enable) are described as  "dynamic, no restart" - but I don't see any of them as being overridable in TSOverridableConfigKey

**Comment by zwoop** [comment]
Dynamic doesn't imply reloadable (but the inverse is true, reloadable implies dynamic).
