### ISSUE TITLE
Add a lifecycle hook for config reload

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#3557]
The hook would be triggered by 'traffic_ctl config reload'.  It would be useful for global plugins.

**Comment by ywkaras** [comment]
@shukitchan Thanks didn't know about that.

**Comment by shukitchan** [comment]
As a closing remark, I do think eventually it makes sense to have a lifecycle hook for config reload in the future. It makes things more consistent to each other in the eco system.
