### ISSUE TITLE
How to get Cache object?

### ISSUE THREAD

**Issue by sangli00** [apache/trafficserver#3561]
How to use  command line ```traffic_ctl metric``` get TrafficServer cache object list?

**Comment by sangli00** [comment]
[root@localhost bin]# ./traffic_ctl metric get proxy.process.http.cache_hit_fresh
proxy.process.http.cache_hit_fresh 25707

this is all fresh  cache object?

**Comment by bryancall** [comment]
If this is still an issue please send an email to the users@ mailing list.
