### ISSUE TITLE
ATS request cycle in multiple network interface

### ISSUE THREAD

**Issue by zhang15535135608** [apache/trafficserver#3654]
settings and oper:
proxy.config.url_remap.remap_required  INT 0
not set  outbound_ip4/ip6 or inbound_ip4/ip6
request a url without remap case http proxy cycle.

I have eht(172.17.200.101) and br0(172.18.200.101). The ATS Machine::Machine use 172.17.200.101 init. In HttpTransact::will_this_request_self_loop check requesut cycle use Machine::instance()->ip.sa. case from 172.18.200.101 request cycle (no remap rule).

**Comment by SolidWallOfCode** [comment]
This should be detected by embedding a UUID in the `Via` header. Is that getting stripped?

**Comment by zwoop** [comment]
Didn't we recently add the UUID into something here too for cycle detection ?

**Comment by SolidWallOfCode** [comment]
Yes, but that depends on having `VIA` set in the header. If not, it does IP address detection.

I have been able to replicate this by requesting one of the host IP addresses as the destination. One of the host IP addresses won't loop, all of the others will. I see that some work has already been done here, I think if I clean it up and extend it a bit I can fix this problem as well.

**Comment by SolidWallOfCode** [comment]
I ended up finding two bugs on this subject. The basic IP address based loop detection is broken, as far as I can tell it doesn't work even with a single homed machine. The other bug is this one.
