### ISSUE TITLE
Crash at TransformVConnection::do_io_close

### ISSUE THREAD

**Issue by gksalil** [apache/trafficserver#3661]
Hello

   I am using ATS **6.2.2** and is experiencing a crash at the TransformVConnection::do_io_close. The stack trace is as below
>>>

#1 0x00007f42727282a8 in _Unwind_Backtrace () from /lib/x86_64/libgcc_s.so.1
#2 0x00007f427245fa88 in backtrace () from /lib/x86_64/libc.so.6
#3 0x00007f4274c9bd7f in ink_stack_trace_dump () at ink_stack_trace.cc:61
#4 0x00007f4274c9e2f3 in signal_crash_handler (signo=11) at signals.cc:180
#5 0x00005575fdf9f68a in crash_logger_invoke (signo=11,
info=0x7f427174e630, ctx=0x7f427174e500) at Crash.cc:169
#6 <signal handler called>
#7 0x00000000000000b8 in ?? ()
#8 0x00005575fdff8b5e in TransformVConnection::do_io_close
(this=0x5575ff57eb20, error=20600) at Transform.cc:467
#9 0x00005575fe08d691 in HttpTunnel::chain_abort_all
(this=0x7f426a9d54e8, p=0x7f426a9d56e8) at HttpTunnel.cc:1444
#10 0x00005575fe03761a in HttpSM::tunnel_handler_post_ua
(this=0x7f426a9d41b0, event=104, p=0x7f426a9d56e8) at HttpSM.cc:3505
#11 0x00005575fe08cdeb in HttpTunnel::producer_handler
(this=0x7f426a9d54e8, event=104, p=0x7f426a9d56e8) at
HttpTunnel.cc:1240
#12 0x00005575fe08dc3b in HttpTunnel::main_handler
(this=0x7f426a9d54e8, event=104, data=0x5575ff201e18) at
HttpTunnel.cc:1623
#13 0x00005575fdfa282f in Continuation::handleEvent
(this=0x7f426a9d54e8, event=104, data=0x5575ff201e18) at
../iocore/eventsystem/I_Continuation.h:153
#14 0x00005575fe1f9a08 in read_signal_and_update (event=104,
vc=0x5575ff201d00) at UnixNetVConnection.cc:148
#15 0x00005575fe1f9da1 in read_signal_done (event=104,
nh=0x7f4271858cd0, vc=0x5575ff201d00) at UnixNetVConnection.cc:209
#16 0x00005575fe1fa61f in read_from_net (nh=0x7f4271858cd0,
vc=0x5575ff201d00, thread=0x7f4271855010) at UnixNetVConnection.cc:359
#17 0x00005575fe1fc78a in UnixNetVConnection::net_read_io
(this=0x5575ff201d00, nh=0x7f4271858cd0, lthread=0x7f4271855010) at
UnixNetVConnection.cc:933
#18 0x00005575fe1f0bc1 in NetHandler::mainNetEvent
(this=0x7f4271858cd0, event=5, e=0x5575ff06ec40) at UnixNet.cc:513
#19 0x00005575fdfa282f in Continuation::handleEvent
(this=0x7f4271858cd0, event=5, data=0x5575ff06ec40) at
../iocore/eventsystem/I_Continuation.h:153
#20 0x00005575fe21fe1f in EThread::process_event (this=0x7f4271855010,
e=0x5575ff06ec40, calling_code=5) at UnixEThread.cc:148
#21 0x00005575fe22037c in EThread::execute (this=0x7f4271855010) at
UnixEThread.cc:275
#22 0x00005575fe21f312 in spawn_thread_internal (a=0x5575ff03ee10) at
Thread.cc:86
#23 0x00007f4272ecb633 in start_thread (arg=0x7f4271753700) at
pthread_create.c:463
#24 0x00007f427245198f in clone () from /lib/x86_64/libc.so.6

<<<<<<

This looks similar to bug 1765, but I think the code changes proposed in bug 1765 is difference from where crash is happening in my server. Hence opening a new issue. 

This is a bit urgent for me as our releases are a kind of stuck !!

Thanks in advance
~S

**Comment by gksalil** [comment]
Do I get some reply on if it is a known issue - or is there any pattern of operation by which this issue may be reproduced etc.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
