### ISSUE TITLE
document about  pipelining to origin servers 

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#3712]
when refer to https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html ,

it says that ats will pipelining to origin. but actually it never doing that.

i think the  document  shoud clarify this.

**Comment by mlibbey** [comment]
Docs updated.  https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-http-chunking-enabled no longer mentions pipelining.
