### ISSUE TITLE
No more debug output after removal of traffic.cop

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#3730]
There is no longer debug output in traffic.out since the removal of the traffic.cop process

-Enable debug
-Set debug string, e.g. http*

traffic.out not generated and no debug output seen

**Comment by zwoop** [comment]
This was triggered by the elimination of traffic_cop.

**Comment by bryancall** [comment]
Debug output is now going to traffic_server.stderr

**Comment by bryancall** [comment]
Looks like there is a problem with systemd.

**Comment by bryancall** [comment]
I changed the startup scripts to output stdout and stderr to traffic.out.  This is how traffic_cop handled it before.
