### ISSUE TITLE
QUIC Congestion window limits

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#3739]
Currently the packet will be pending until the congestion controller has enough credit. 

Actually we should limit the packet size on generating frame, because it may cause the peer spurious retransmmition  (ack frame may be delayed).

So I'd like to pre-allocate a buffer with limit size and fill the buffer with frames. And send it all. 

```
while(1) {
   limit = std::min(this->_cc.credit(), max_packet_size)
   if (limit < min_packet_size) {
      return
   }

   buf = new buf[limit]

   frame = frameGenerator1.generate_frame(limit)
   limit -= frame->size()
   frame->store(buf) 

   frame = frameGenerator2.generate_frame(limit)
   limit -= frame->size()
   frame->store(buf)   
  
   frame = frameGenerator3.generate_frame(limit)
   limit -= frame->size()
   frame->store(buf)   

    .....

    packet = new packet(buf)
    send_packet(packet)
}
    
```

**Comment by masaori335** [comment]
Do you mean removing `_packet_send_queue` from `QUICNetVConnection` and combining `store_frame()`, `transmit_packet()`, and `_state_common_send_packet()` ?

**Comment by scw00** [comment]
I'm not sure we need to _packet_send_queue from QUICNetVConnection. But we may need to combing the QVC::packetize_frame and QVC::store_frame, because QVC::store_frame allocate a new buffer to hold the frame which not satisfied the buffer length or type .

**Comment by masaori335** [comment]
OK, regardless removing `_packet_send_queue` or not, you should increase `bytes_in_flight` in `send_packet(packet)` in above pseudocode. Otherwise, `this->_cc.credit()` might be wrong.

**Comment by masaori335** [comment]
I'm curious about how much this fix the situation.

> because it may cause the peer spurious retransmmition (ack frame may be delayed).

ACK frame could be delayed when we consume all window (even if this change is applied), right?
So, this will mitigate the situation, but this looks not fixing root cause. What I'm missing?

**Comment by masaori335** [comment]
I thought endpoint can't send anything when there're no available congestion window, but I was wrong. From 4., 4.7.2., and 4.7.4., it looks like endpoint can send ACK only packet because it doesn't increase `bytes_in_flight`.

Well, I think when `this->_cc.credit()` is small, we should create ACK only packet and sent it.

**Comment by scw00** [comment]
The packet , which is not ack-only packet, will be pended when cc doesn't have enough credit. So we may need to make ack creator independently .

**Comment by masaori335** [comment]
It's kind of rough, but I did some changes to check congestion window first on packet sending in draft-13 support.
@scw00 could you take a look at latest quic-latest branch?
https://github.com/apache/trafficserver/blob/a1a942be2d650f9d4b5ada00b51dafcf9fd92be9/iocore/net/QUICNetVConnection.cc#L1079-L1086

**Comment by scw00** [comment]
Nice work, I think it can be closed for now.
