### ISSUE TITLE
dns resolution - use alternative ip address if first one fails.

### ISSUE THREAD

**Issue by gksalil** [apache/trafficserver#3742]
Hi

  I have an ATS deployment configured as forward proxy. My dns server returns two address for origin server. But ATS consider only one address. In case the first address is not accessible, ATS return error to the client. Can we incorporate this feature in ATS code, to consider the remaining addresses too in case it fail to reach first address. 

Thanks and regards
gks

**Comment by zizhong** [comment]
I remember if the first request has a server connecting issue, the HostDB record will be updated and the following request will be successful.

**Comment by gksalil** [comment]
It doesn't work like this .
Is there any specific configuration that I need to do to achieve this?

Thanks and regards
gks

**Comment by SolidWallOfCode** [comment]
Wouldn't something like [this](https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html#proxy-config-http-connect-attempts-rr-retries) do what you want? You could set it to "1" and force ATS to use next address on failure.

**Comment by bryancall** [comment]
Please take look at https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html#proxy-config-http-connect-attempts-rr-retries and see if that fixes the issue.

If this is still an issue please reopen.
