### ISSUE TITLE
how can i config ats to retry another origin server like squid do;

### ISSUE THREAD

**Issue by isolosun** [apache/trafficserver#3778]
in my test,
try through proxy(ats/squid) to access a domian which has two ip A and B;
when A is not accessible，squid will try to access B to get response,and return client 200;
but ats will always try to access A , until timeout and return client 502;
is there some config options can let ats do the samething?

thx a lot；

**Comment by SolidWallOfCode** [comment]
See [here](https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html#proxy-config-http-connect-attempts-max-retries) and [here](https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html#proxy-config-http-connect-attempts-rr-retries).

**Comment by mlibbey** [comment]
@isolosun With SolidWallOfCode 's comment, closing this out.
