### ISSUE TITLE
QUIC trace ack frame

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#3780]
>3.4.2. Receiver Tracking of ACK Frames
When a packet containing an ACK frame is sent, the largest acknowledged in that frame may be saved. When a packet containing an ACK frame is acknowledged, the receiver can stop acknowledging packets less than or equal to the largest acknowledged in the sent ACK frame.

>In cases without ACK frame loss, this algorithm allows for a minimum of 1 RTT of reordering. In cases with ACK frame loss, this approach does not guarantee that every acknowledgement is seen by the sender before it is no longer included in the ACK frame. Packets could be received out of order and all subsequent ACK frames containing them could be lost. In this case, the loss recovery algorithm may cause spurious retransmits, but the sender will continue making forward progress.

**Comment by maskit** [comment]
Can we close this?

**Comment by scw00** [comment]
Done
