### ISSUE TITLE
fatal error: string_view: No such file or directory

### ISSUE THREAD

**Issue by purplehorse** [apache/trafficserver#3849]
I follow this guide:
```
$ git clone --depth 1 --branch quic-latest https://github.com/apache/trafficserver
$ cd trafficserver
$ autoreconf -if
$ ./configure --prefix=/PATH/TO/THE/ATS --with-openssl=/PATH/TO/THE/OPENSSL --enable-debug

```
That last line is exactly:
`delia@delia-VirtualBox:~/trafficserver$ ./configure --prefix=/home/delia/trafficserver/build --with-openssl=/home/delia/openssl/build --enable-debug`

When I make:
`
$ make
`

The output is:
```
make[3]: Entering directory '/home/delia/trafficserver/lib/ts'
  CXX      Arena.lo
In file included from Arena.cc:25:0:
../../lib/ts/ink_memory.h:30:23: fatal error: string_view: No such file or directory
compilation terminated.
Makefile:1382: recipe for target 'Arena.lo' failed
make[3]: *** [Arena.lo] Error 1
make[3]: Leaving directory '/home/delia/trafficserver/lib/ts'
Makefile:610: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/delia/trafficserver/lib'
Makefile:549: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/delia/trafficserver/lib'
Makefile:853: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

And I can't perform make successfully. I'm using Ubuntu 16.04 and I have installed everything recommended in readme. 

Edit: gcc version is 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)

**Comment by bryancall** [comment]
@purplehorse You will need to have gcc 7 to compile ATS now.  We moved to require C++17 and it is not fully supported until gcc 7.  There are updated instructions under "ATS v8.0" here:
https://cwiki.apache.org/confluence/display/TS/Ubuntu

**Comment by purplehorse** [comment]
solved!
