### ISSUE TITLE
How to fast find cache object in Trafficserver?

### ISSUE THREAD

**Issue by sangli00** [apache/trafficserver#3872]
I cache so many data in Disk.
sometimes,I used Key```CID ``` find this object is cache,how to fast find it?
I know ```lookup``` is OK,but this is bad idea.

**Comment by SolidWallOfCode** [comment]
From where do you want to find the object? Externally, via HTTP, or internally, via a plugin, or in the TS core?

**Comment by sangli00** [comment]
@SolidWallOfCode 
Externally

**Comment by SolidWallOfCode** [comment]
That's a bit challenging. For now, the best option is the Cache Tool, `traffic_cache_tool`, but it's still very much a work in progress.

**Comment by SolidWallOfCode** [comment]
[This might also be of use](https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/storage/index.en.html#inspecting-the-cache), if you have a specific URL you want to find (although it must be noted this uses the cache key, which is generally the post-remap URL, not the user agent supplied URL).

**Comment by sangli00** [comment]
@SolidWallOfCode  7.1 version is not find  ```traffic_cache_tool``` ,what version support this tools?
This is support API ? maybe i used others program lookup cache.

**Comment by zwoop** [comment]
It's in 8.0.x and later.
