### ISSUE TITLE
Problem with body factory's host target user response page

### ISSUE THREAD

**Issue by shukitchan** [apache/trafficserver#3877]
Hi, with TS-3779, we started to support body factory's host target user response page. All changes are listed here 

https://github.com/apache/trafficserver/search?q=TS-3779&type=Commits

However we haven't changed this 

https://github.com/apache/trafficserver/blob/master/mgmt/RecordsConfig.cc#L664-L665

So I can't set 3 for "proxy.config.body_factory.enable_customizations"

**Comment by zizhong** [comment]
let me take a look.
