### ISSUE TITLE
"proxy.config.hostdb.ip_resolve" config doesn't work as documented

### ISSUE THREAD

**Issue by GUI** [apache/trafficserver#3880]
The `none` option in the `proxy.config.hostdb.ip_resolve` configuration doesn't seem to work [as documented](https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html?highlight=ip_resolve#proxy.config.hostdb.ip_resolve). With a setting of `CONFIG proxy.config.hostdb.ip_resolve STRING ipv4;none`, the documentation indicates that only IPv4 addresses should be resolved, but instead IPv6 addresses will continue to be looked up if IPv4 resolution fails.

I discovered that there's an undocumented `only` value, that actually does what the `none` value should be doing. I'd be happy to submit a pull request to fix this, but I'm unsure what should be updated: Should the docs simply be updated to reference this `only` value, or should the code actually be updated to support the `none` value?

I ran into this in Trafficserver v7.1.3, but it looks like this affects master (and I think it's also been a long-standing issue).

As a quick example:

records.config:
```
CONFIG proxy.config.hostdb.ip_resolve STRING ipv4;none
```

remap.config (this `v6.ipv6-test.com` domain is just an IPv6-only domain to test against, since it has only AAAA records and no A records):
```
map / http://v6.ipv6-test.com:80/
```

Debug logs—note that an AAAA record is looked up and used after the A record lookup fails:
```
[Jun 23 17:07:23.221] Server {0xb0016000} DEBUG: <HttpSM.cc:4086 (do_hostdb_lookup)> (http_seq) [HttpSM::do_hostdb_lookup] Doing DNS Lookup
[Jun 23 17:07:23.237] Server {0xb0016000} DEBUG: <DNS.cc:1093 (getby)> (dns) received query v6.ipv6-test.com type = 1, timeout = 0
[Jun 23 17:07:23.237] Server {0xb0000000} DEBUG: <DNS.cc:1059 (mainEvent)> (dns) enqueing query v6.ipv6-test.com
[Jun 23 17:07:23.237] Server {0xb0000000} DEBUG: <DNS.cc:1065 (mainEvent)> (dns) adding first to collapsing queue
[Jun 23 17:07:23.238] Server {0xb0000000} DEBUG: <DNS.cc:980 (write_dns_event)> (dns) send query (qtype=1) for v6.ipv6-test.com to fd 60
[Jun 23 17:07:23.238] Server {0xb0000000} DEBUG: <DNS.cc:1012 (write_dns_event)> (dns) sent qname = v6.ipv6-test.com, id = 45442, nameserver = 1
[Jun 23 17:07:23.238] Server {0xb0000000} DEBUG: <P_DNSProcessor.h:239 (sent_one)> (dns) sent_one: failover_number for resolver 1 is 1
[Jun 23 17:07:23.269] Server {0xb0000000} DEBUG: <DNS.cc:761 (recv_dns)> (dns) received packet size = 92
[Jun 23 17:07:23.269] Server {0xb0000000} DEBUG: <DNS.cc:763 (recv_dns)> (dns) round-robin: nameserver 1 DNS response code = 5
[Jun 23 17:07:23.269] Server {0xb0000000} DEBUG: <DNS.cc:1308 (dns_process)> (dns) received rcode = 0
[Jun 23 17:07:23.269] Server {0xb0000000} DEBUG: <DNS.cc:1331 (dns_process)> (dns) DNS error 0 for [v6.ipv6-test.com]
[Jun 23 17:07:23.269] Server {0xb0000000} DEBUG: <DNS.cc:1182 (dns_result)> (dns) FAIL result for v6.ipv6-test.com = <none> retry 0
[Jun 23 17:07:23.302] Server {0xb0016000} DEBUG: <DNS.cc:1270 (postEvent)> (dns) called back continuation for v6.ipv6-test.com
[Jun 23 17:07:23.365] Server {0xb0016000} DEBUG: <DNS.cc:1093 (getby)> (dns) received query v6.ipv6-test.com type = 1, timeout = 0
[Jun 23 17:07:23.366] Server {0xb0000000} DEBUG: <DNS.cc:1059 (mainEvent)> (dns) enqueing query v6.ipv6-test.com
[Jun 23 17:07:23.366] Server {0xb0000000} DEBUG: <DNS.cc:1065 (mainEvent)> (dns) adding first to collapsing queue
[Jun 23 17:07:23.366] Server {0xb0000000} DEBUG: <DNS.cc:980 (write_dns_event)> (dns) send query (qtype=28) for v6.ipv6-test.com to fd 58
[Jun 23 17:07:23.366] Server {0xb0000000} DEBUG: <DNS.cc:1012 (write_dns_event)> (dns) sent qname = v6.ipv6-test.com, id = 59642, nameserver = 0
[Jun 23 17:07:23.366] Server {0xb0000000} DEBUG: <P_DNSProcessor.h:239 (sent_one)> (dns) sent_one: failover_number for resolver 0 is 1
[Jun 23 17:07:23.448] Server {0xb0000000} DEBUG: <DNS.cc:761 (recv_dns)> (dns) received packet size = 62
[Jun 23 17:07:23.448] Server {0xb0000000} DEBUG: <DNS.cc:763 (recv_dns)> (dns) round-robin: nameserver 0 DNS response code = 5
[Jun 23 17:07:23.448] Server {0xb0000000} DEBUG: <DNS.cc:1562 (dns_process)> (dns) received AAAA name = v6.ipv6-test.com
[Jun 23 17:07:23.448] Server {0xb0000000} DEBUG: <DNS.cc:1579 (dns_process)> (dns) received AAAA = 2001:41d0:8:e8ad::1
[Jun 23 17:07:23.448] Server {0xb0000000} DEBUG: <DNS.cc:1182 (dns_result)> (dns) SUCCESS result for v6.ipv6-test.com = 2001:41d0:8:e8ad::1 retry 0
[Jun 23 17:07:23.448] Server {0xb0016000} DEBUG: <DNS.cc:1270 (postEvent)> (dns) called back continuation for v6.ipv6-test.com
[Jun 23 17:07:23.448] Server {0xb0016000} DEBUG: <HttpSM.cc:2610 (main_handler)> (http) [2] [HttpSM::main_handler, EVENT_HOST_DB_LOOKUP]
[Jun 23 17:07:23.448] Server {0xb0016000} DEBUG: <HttpSM.cc:2171 (state_hostdb_lookup)> (http) [2] [&HttpSM::state_hostdb_lookup, EVENT_HOST_DB_LOOKUP]
[Jun 23 17:07:23.448] Server {0xb0016000} DEBUG: <HttpTransact.cc:8487 (ink_cluster_time)> (http_trans) [ink_cluster_time] local: 1529795243, highest_delta: 0, cluster: 1529795243
[Jun 23 17:07:23.448] Server {0xb0016000} DEBUG: <HttpTransact.cc:1678 (OSDNSLookup)> (http_trans) [2] [HttpTransact::OSDNSLookup] This was attempt 0
[Jun 23 17:07:23.448] Server {0xb0016000} DEBUG: <HttpTransact.cc:1748 (OSDNSLookup)> (http_seq) [2] [HttpTransact::OSDNSLookup] DNS Lookup successful
[Jun 23 17:07:23.448] Server {0xb0016000} DEBUG: <HttpTransact.cc:1787 (OSDNSLookup)> (http_trans) [2] [OSDNSLookup] DNS lookup for O.S. successful IP: 2001:41d0:8:e8ad::1
```

The culprit of this bug can be found here: https://github.com/apache/trafficserver/blob/f6cb212e0133894e4e3a883a6497ce645ebce7b7/lib/ts/ink_res_init.cc#L100

Essentially, the parsing of `ip_resolve` doesn't actually ever look for a `"none"` string. Instead, it's looking for `"only"`, which it then associates with `HOST_RES_PREFER_NONE` value used throughout the rest of the code. Simply replacing `"only"` with `"none"` in that `HOST_RES_PREFERENCE_STRING` array seems to fix things so they work as documented with `none` values. However, again, I'm not entirely sure what the preferred fix here is: Updating the docs to use `only` or switching the code to fix `none` handling (and in that case whether continuing to support the `only` value is important for backwards-compatibility).

And this same issue was noted in this earlier issue, but since it wasn't the original issue, I thought I'd open a new one specifically for this: https://github.com/apache/trafficserver/issues/1562#issuecomment-285593584

**Comment by SolidWallOfCode** [comment]
That's a typo in the documentation. "only" is what should be used in the configuration.

**Comment by GUI** [comment]
Thanks for confirming! I opened up a quick pull request to fix the documentation aspect of this.
