### ISSUE TITLE
Unable to connect server

### ISSUE THREAD

**Issue by purplehorse** [apache/trafficserver#3882]
I have installed apache traffic server and I have followed this guide https://cwiki.apache.org/confluence/display/TS/QUIC to configure:

- records.config
```
# run 1 UDP thread at least
CONFIG proxy.config.udp.threads INT 1
  
# open server port for quic
CONFIG proxy.config.http.server_ports STRING 4433:quic
  
# Append ciphers for TLS 1.3 (the three at the beginning)
CONFIG proxy.config.ssl.server.cipher_suite STRING TLS13-AES-128-GCM-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-CHACHA20-POLY1305-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
  
# enable debug log if you want
CONFIG proxy.config.diags.debug.enabled INT 1
CONFIG proxy.config.diags.debug.tags STRING quic
```

- ssl_multicert.config
`
dest_ip=* ssl_cert_name=/PATH/TO/THE/CERT ssl_key_name=/PATH/TO/THE/PRIVATE/KEY/OF/CERT
`

- remap.config
`map / http://127.0.0.1:8000/`

And finally I run trafficserver:
` * Starting Apache Traffic Server trafficserver                  [OK]
`

But when I try to access to localhost:8000, localhost:8080 or localhost I get "the site can't be reached".
If I try to access to localhost:4433 it keeps loading and doesn't work either.

**Comment by SolidWallOfCode** [comment]
Yes, that's expected. The value `proxy.config.http.server_ports` configures the "proxy ports", or the ports on which ATS will listen. Your configuration lists only port 4433 and so that is the only port opened by ATS. If you want to connect on port 8000 or 8080 you will need to add those as well, e.g. something like "4433:quic 8000 8080".

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
