### ISSUE TITLE
Add a proxy between the ATS and Certificate Authority's responder server

### ISSUE THREAD

**Issue by mrmiywj** [apache/trafficserver#3887]
Hi ATS team,

I'm wondering if we can add a HOOK before the ATS send request to the CA's responder and a HOOK after receiving the response.

Since the ATS may be deployed in a network in which the CA's server is blocked, we need a proxy or a gateway to access the CA's responder server. 

So one solution is add a hook before the ATS sending the request, modifying the host and content of the request. 

Can we do this?

**Comment by zizhong** [comment]
@shinrich @SolidWallOfCode @zwoop @bryancall how do you do OCSP stapling when directly calling the CA server is not an option?

**Comment by maskit** [comment]
This reminded me [TS-3186](https://issues.apache.org/jira/browse/TS-3186).

**Comment by SolidWallOfCode** [comment]
Yes, that's the basic approach. I think it's probably sufficient, since the goal is to force the OCSP request to a specific host for proxying.
