### ISSUE TITLE
Debug message confusing when selecting alternates

### ISSUE THREAD

**Issue by djcarlin** [apache/trafficserver#3914]
This debug message is confusing, because different indexes are being used.  It seems to be referring to the same alternate.

This comes up when looking up alternates in cache

```
[Jul  2 23:23:58.408] {0x2aaf811c5700} DEBUG: (http_seq) [SelectFromAlternates] Chosen alternate # 0
[alts] and the winner is alternate number 1
```

**Comment by zwoop** [comment]
This has been fixed.
