### ISSUE TITLE
S3 can omit "Vary: Origin" in HTTP response, can poison cache

### ISSUE THREAD

**Issue by d2r** [apache/trafficserver#3954]
Amazon AWS S3 will return a `Vary` header containing `Origin` when an `Origin` header is present in the request, but not when the `Origin` header is missing from the request.

In the case when our cache does not contain the resource requested, if a request for the resource lacks the `Origin` header, we will cache S3's response without the `Origin` value in a `Vary` header.

As a result, we cache no alternates for the resource, and so we will respond without the `Origin` value in any Vary header returned from ATS—whether or not the request has an `Origin` field—whereas the same request to S3 would return the value and the header when the `Origin` field is present in the request. Thus the cache is "poisoned" after the first request without the `Origin` field.

Browsers that expect specific CORS headers that vary by `Origin` (e.g. `Access-Control-Allow-Origin`) would never receive the needed headers and will be unable to render the resource.

Currently one solution is to use Amazon Cloudfront, but this is another commercial service. Another solution is to have a custom plugin with logic to work around the issue.

It may be good to implement a common work-around in an official plugin.

**Comment by d2r** [comment]
As far as I am aware, this is an issue so long as S3 continues to behave this way.

**Comment by mlibbey** [comment]
Some quick solutions:
header rewrite --
```
cond %{SEND_REQUEST_HDR_HOOK}
cond %{HEADER:Origin} =""
  set-header Origin="something"
```

cachekey --include-headers (`@plugin=cachekey.so @pparam=--include-headers=origin`)

**Comment by zwoop** [comment]
Maybe this is a documentation issue?

**Comment by bryancall** [comment]
@mlibbey Do you want to handle this one?

**Comment by karendolan** [comment]
This is the AWS thread on this issue https://forums.aws.amazon.com/thread.jspa?threadID=156134, it's still open.

**Comment by bryancall** [comment]
This should be fixed on the origin and ATS can override the header using the example in this issue.
