### ISSUE TITLE
ATS 6.2.1 returning truncated range requests with read_while_writer on.

### ISSUE THREAD

**Issue by pbchou** [apache/trafficserver#3991]
We are running ATS 6.2.1 with read_while_writer. The clients we are serving are issuing range requests of approximately 1 MB each, but there are instances where the served content is truncated to within some tens of KB of the 1 MB threshold. We thought that this might be related to the old TS-2314 and TS-1955, so we made use of the work-around of forwarding byte range requests directly to the origin instead of waiting on read_while_writer. While this solves the problem, we are wondering whether there are plans to address the underlying issue in the old Jira issues referenced above?

**Comment by zhxiaom5** [comment]
Seems We meet this error too,We will dig more and report here

**Comment by zhxiaom5** [comment]
@pbchou  Could I have you email ? So we can communication on this issue

**Comment by pbchou** [comment]
@zhxiaom5 -- You can e-mail me at pbchou@labs.att.com. I also started a thread on the mailing list if you want to look there as well.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
