### ISSUE TITLE
Add an API to register user-defined OCSP refresher function

### ISSUE THREAD

**Issue by mrmiywj** [apache/trafficserver#3997]
After reviewing [TS-3186](https://issues.apache.org/jira/browse/TS-3186), we found that solution could not solve our requirement. We need a customized request to the proxy and get response from the proxy. Simply remaping url cannot resolve it.

# Goal
Add an API in ATS core to replace the function to send the request to the CA’s responder server with a user customized function. The customized function can implemented in a plugin and registered by the plugin.

# Motivation
In some use cases, the datacenter where ATS deployed in may be unable to connect to the CA’s responder server, due to security concerns. Thus we need to connect to outside via a specific proxy. The data schema of the proxy is JSON. Thus we need to customize our own connecting function.

# Specification
1. Add a function pointer entry in the SSLConfig.
2. Add an API in `ts.h` to register a user-customized function
3. Check if there is a user-customized stapling function before calling `stapling_refresh_response` in OCSPStapling.cc

# Proposed design

1. Add a `bool (*ocsp_refresh_func)(certinfo*, OCSP_RESPONSE **) field in `SSLConfigParams` in `iocore/net/P_SSLConfig.h`.
2. Add an API in `proxy/api/ts/ts.h`, called `TSRegisterOCSPRefresher`.
3. Implement the `TSRegisterOCSPRefresher` in `proxy/InkAPI.cc`, assigning the user passed function pointer to that in the SSLConfig.

**Comment by mrmiywj** [comment]
#3996

**Comment by bryancall** [comment]
@mrmiywj Please take look at this new feature that will allow you to prefetch the ocsp responses. #5228 

If this is still an issue please reopen.
