### ISSUE TITLE
thread local SSL_CTX

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#3998]
Was debugging an HTTPS perf issue. Found a lot of lock_wait because of ssl_locking_callback().
Then a bit of searching led me to this discussion between @bryancall and OpenSSL email list.
Sorry, didn't familiar about SSL implementation. Merely would like to confirm if we fixed this or not? Thanks!
@bryancall @shinrich @oknet @SolidWallOfCode 

https://mta.openssl.org/pipermail/openssl-users/2015-April/001197.html
```
another item to check is whether you're
instantiating an SSL_CTX for each thread.  I've seen some developers use
a single SSL_CTX for multiple threads.  This results in a single
instance of the server cert and private key being shared across all the
threads.  This results in thread contention on the asymmetric key
operations associated with the cert and private key (e.g. RSA).  Be sure
that each thread instantiates it's own SSL_CTX and certificate/private key.
```

**Comment by shinrich** [comment]
What @bryancall found that the main contention was on the SSL error locking.  I verified that by updating the locking callback to return immediately in the case of the error lock.  This is kind of dicey, but in lab tests, the load limit was avoided.  This error lock is particularly bad with Traffic Server non-blocking socket.  We must check the error and most of the errors are benign needs read/write.  In the blocking socket case, the error lookup would be called less are ignored (just assume a bad return code is bad and don't go into the details).

Are you running with openssl 1.0.2?  Things are much better locking-wise with openssl 1.1.0.

**Comment by zizhong** [comment]
Thanks, Susan, yes, ran it for 10 mins and found
```proxy.process.ssl.user_agent_other_errors": "0",
"proxy.process.ssl.origin_server_other_errors": "0",
"proxy.process.ssl.ssl_error_want_write": "0",
"proxy.process.ssl.ssl_error_want_read": "132434297",
```


Only if OpenSSL didn't lock when it's not a real error..

I tested with open 1.0.1. Thanks for the suggestion and we'll try 1.10.

From another thread, I learnt you've done an HTTPS perf and the result is not far different from HTTP. Have you tested HTTPS to HTTPS? Because ATS doesn't support session resumption as a client, I thought performance with HTTPS to HTTPS will be much worse.

**Comment by shinrich** [comment]
In our workflow, we use global server session pools, so we get a good bit of connection reuse.  I haven't done a systematic perf measurement comparing HTTP vs HTTPs to origin.

@DaveThompson got about 90% of the way there for session support for ATS as a client quite a few years ago.  Should look around to our junior folks and see if we can resurrect that.

**Comment by zizhong** [comment]
We tried OpenSSL 1.1 and the locking issue is gone. Thanks for the suggestions @shinrich
