### ISSUE TITLE
Crash in cachekey with specific capture-prefix-uri

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#4015]
I was doing some testing with cachekey and managed to make one that crashed it:
@plugin=cachekey.so @pparam=--separator= @pparam=--remove-all-params=true @pparam=--remove-path=true @pparam=--capture-prefix-uri=/http(s)?:\/\/([^?]*)/$1:\/\/$2/

The (s)? is what was added to cause the crash

**Comment by gtenev** [comment]
Hi Evan,

Thanks for reporting it!

Based on the info you provided I was able to get a crash (exception thrown from unhandled case).

Here is the PR https://github.com/apache/trafficserver/pull/4101 <https://github.com/apache/trafficserver/pull/4101> that should fix it.

Here is the test-case that got fixed.

@plugin=cachekey.so \
    @pparam=--separator= \
    @pparam=--remove-all-params=true \
    @pparam=--remove-path=true \
    @pparam=--capture-prefix-uri=/http(s)?:\/\/([^?]*)/$1:\/\/$2/


$ curl  http://example-cdn.com/path/file

Results in the following log:

[Aug 11 11:30:41.800] {0xb000c000} DIAG: (cachekey) cachekey/cachekey.cc:208:CacheKey() setting cache key from a remap plugin
[Aug 11 11:30:41.800] {0xb000c000} DIAG: (cachekey) cachekey/cachekey.cc:219:CacheKey() using remap uri 'http://example-cdn.com:8080/path/file'
[Aug 11 11:30:41.800] {0xb000c000} DIAG: (cachekey) cachekey/pattern.cc:277:replace() replacing:'$1://$2' in pattern:'http(s)?://([^?]*)', subject:'http://example-cdn.com:8080/path/file'
[Aug 11 11:30:41.800] {0xb000c000} DIAG: (cachekey) cachekey/pattern.cc:309:replace() start -1, len 0
[Aug 11 11:30:41.800] {0xb000c000} DIAG: (cachekey) cachekey/pattern.cc:313:replace() replacing '$1' with ''
[Aug 11 11:30:41.800] {0xb000c000} DIAG: (cachekey) cachekey/pattern.cc:313:replace() replacing '$2' with 'example-cdn.com:8080/path/file'
[Aug 11 11:30:41.800] {0xb000c000} DIAG: (cachekey) cachekey/pattern.cc:323:replace() replacing '$1://$2' resulted in '://example-cdn.com:8080/path/file'
[Aug 11 11:30:41.801] {0xb000c000} DIAG: (cachekey) cachekey/cachekey.cc:372:appendPrefix() added URI capture prefix, key: '://example-cdn.com:8080/path/file'
[Aug 11 11:30:41.801] {0xb000c000} DIAG: (cachekey) cachekey/cachekey.cc:663:finalize() finalizing cache key '://example-cdn.com:8080/path/file' from a remap plugin


$ curl  https://example-cdn.com/path/file

Results in the following log:

[Aug 11 11:30:48.543] {0xb000e000} DIAG: (cachekey) cachekey/cachekey.cc:208:CacheKey() setting cache key from a remap plugin
[Aug 11 11:30:48.543] {0xb000e000} DIAG: (cachekey) cachekey/cachekey.cc:219:CacheKey() using remap uri 'https://example-cdn.com:8443/path/file'
[Aug 11 11:30:48.543] {0xb000e000} DIAG: (cachekey) cachekey/pattern.cc:277:replace() replacing:'$1://$2' in pattern:'http(s)?://([^?]*)', subject:'https://example-cdn.com:8443/path/file'
[Aug 11 11:30:48.543] {0xb000e000} DIAG: (cachekey) cachekey/pattern.cc:313:replace() replacing '$1' with 's'
[Aug 11 11:30:48.543] {0xb000e000} DIAG: (cachekey) cachekey/pattern.cc:313:replace() replacing '$2' with 'example-cdn.com:8443/path/file'
[Aug 11 11:30:48.543] {0xb000e000} DIAG: (cachekey) cachekey/pattern.cc:323:replace() replacing '$1://$2' resulted in 's://example-cdn.com:8443/path/file'
[Aug 11 11:30:48.543] {0xb000e000} DIAG: (cachekey) cachekey/cachekey.cc:372:appendPrefix() added URI capture prefix, key: 's://example-cdn.com:8443/path/file'
[Aug 11 11:30:48.543] {0xb000e000} DIAG: (cachekey) cachekey/cachekey.cc:663:finalize() finalizing cache key 's://example-cdn.com:8443/path/file' from a remap plugin


Please let me know if any questions or problems!
Cheers,
—Gancho

**Comment by mlibbey** [comment]
@ezelkow1 Sounds like this can be closed?

**Comment by ezelkow1** [comment]
@mlibbey yes
