### ISSUE TITLE
Stale object gets deleted if the origin server is down on master

### ISSUE THREAD

**Issue by vmamidi** [apache/trafficserver#4017]
ATS should serve stale when the server is down based on proxy.config.http.cache.max_stale_age configuration. On master this is broken and here is the debug related to the deletion of the object.
[Jul 26 11:44:16.048] {0xb001e000} DEBUG: <HttpSM.cc:5705 (perform_cache_write_action)> (http) [0] perform_cache_write_action CACHE_DO_SERVE
[Jul 26 11:44:16.048] {0xb001e000} DEBUG: <CacheWrite.cc:75 (updateVector)> (cache_update) updating alternate index 0 frags 0
[Jul 26 11:44:16.048] {0xb001e000} DEBUG: <CacheWrite.cc:1125 (openWriteCloseDir)> (cache_update) alt delete, 3355, (15627494785833730372, 8629982903010169646)
[Jul 26 11:44:16.048] {0xb001e000} DEBUG: <P_CacheInternal.h:568 (free_CacheVC)> (cache_free) free 0x7fa2fd08d800

**Comment by zwoop** [comment]
I believe this is done? Remember to close Issues :).
