### ISSUE TITLE
meet problem when configure traffic server connection to origin server using https

### ISSUE THREAD

**Issue by ranxuxin** [apache/trafficserver#4023]
@oknet @scw00 @bryancall 
I set some ssl configuration in records.config, eg:
CONFIG proxy.config.ssl.client.verify.server INT 1
CONFIG proxy.config.ssl.client.CA.cert.filename STRING ca-bundle.crt
CONFIG proxy.config.ssl.client.CA.cert.path STRING /etc/pki/tls/certs

remap.config:
map http://www.cat.com https://www.baidu.com

curl:
curl -H "host: www.cat.com" "http://10.210.136.54:8080/a.txt" -v > a

However, it returns “HTTP/1.1 502 connect failed”. It seems ats cannot verify the origin server. I have tested it with ats 6.2.1 and 7.1.3. Could you give me some suggestion. Thank you!

**Comment by oknet** [comment]
The issue was resolved with the config:

```
CONFIG proxy.config.url_remap.pristine_host_hdr INT 0
```

The key points are the hostname and SNI to the original server.
