### ISSUE TITLE
Bug in new SNI config parsing

### ISSUE THREAD

**Issue by pushkar2017** [apache/trafficserver#4034]
There is a copy paste error in SNI config parsing when we moved to YAML syntax.
The disable_h2 option is parsed and assigned to the fqdn as a boolean.
Proposed fix:
diff --git a/iocore/net/YamlSNIConfig.cc b/iocore/net/YamlSNIConfig.cc
index 06f8c6f5c..da53fe22a 100644
--- a/iocore/net/YamlSNIConfig.cc
+++ b/iocore/net/YamlSNIConfig.cc
@@ -79,7 +79,7 @@ template <> struct convert<YamlSNIConfig::Item> {
       return false; // servername must be present
     }
     if (node[TS_disable_H2]) {
-      item.fqdn = node[TS_disable_H2].as<bool>();
+      item.disable_h2 = node[TS_disable_H2].as<bool>();
     }
 
     // enum

**Comment by SolidWallOfCode** [comment]
Fixed by #4035.
