### ISSUE TITLE
Add missing details to Layer 4 routing doc

### ISSUE THREAD

**Issue by pushkar2017** [apache/trafficserver#4056]
https://docs.trafficserver.apache.org/en/latest/admin-guide/layer-4-routing.en.html?highlight=tunnel_route

The page does not mention that the tunnel destination ports must be added in records.config tag:
CONFIG proxy.config.http.connect_ports

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
