### ISSUE TITLE
What is the relationship between records.config and cache.config?

### ISSUE THREAD

**Issue by yywf** [apache/trafficserver#4066]
I have configuration as fellow:
records.config
CONFIG proxy.config.http.cache.http INT 1
cache.config
url_regex=http://.* suffix=jpg action=never-cache

and TS can cache all object but jpg url, it is ok.

---
but when I modify config as fellow
records.config
CONFIG proxy.config.http.cache.http INT 0
cache.config
url_regex=http://.* suffix=jpg revalidate=12h

and TS never cache any object, include jpg url.

so What is the relationship between records.config and cache.config? how can cache only configuration use suffix= ?

**Comment by mlibbey** [comment]
CONFIG proxy.config.http.cache.http INT 0 in records.config means turning off the cache entirely -- it overrides everything else.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
