### ISSUE TITLE
Segmentation fault branch 8.0.x

### ISSUE THREAD

**Issue by jingshaoqi** [apache/trafficserver#4094]
==1400== Memcheck, a memory error detector
==1400== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1400== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==1400== Command: /usr/bin/traffic_server
==1400== 
Traffic Server 8.0.0 Aug  7 2018 09:25:33 localhost.localdomain
traffic_server: using root directory '/usr'
==1400== Warning: noted but unhandled ioctl 0x127a with no size/direction hints.
==1400==    This could cause spurious value errors to appear.
==1400==    See README_MISSING_SYSCALL_OR_IOCTL for guidance on writing a proper wrapper.
cccctraffic_ctl: configuration reload request failed: [5] Error establishing socket connection.
cc==1400== Thread 10 [ET_NET 8]:
==1400== Invalid read of size 8
==1400==    at 0x565F60: _ZN10HttpTunnel12producer_runEP18HttpTunnelProducer (HttpTunnel.cc:1021)
==1400==    by 0x56731E: _ZN10HttpTunnel10tunnel_runEP18HttpTunnelProducer (HttpTunnel.cc:759)
==1400==    by 0x51C0E1: _ZN6HttpSM17handle_api_returnEv (HttpSM.cc:1617)
==1400==    by 0x5148EB: _ZN6HttpSM17state_api_calloutEiPv (HttpSM.cc:1516)
==1400==    by 0x51B697: _ZN6HttpSM18state_api_callbackEiPv (HttpSM.cc:1283)
==1400==    by 0x4C31CC: TSHttpTxnReenable (InkAPI.cc:5825)
==1400==    by 0x2887DF58: _ZL8cachefunP10tsapi_cont7TSEventPv (main.cpp:3180)
==1400==    by 0x4AFBD2: _ZN15INKContInternal12handle_eventEiPv (InkAPI.cc:1070)
==1400==    by 0x5149C4: _ZN6HttpSM17state_api_calloutEiPv (HttpSM.cc:1443)
==1400==    by 0x51B89F: _ZN6HttpSM12main_handlerEiPv (HttpSM.cc:2543)
==1400==    by 0x75DEF1: _ZN7EThread13process_eventEP5Eventi (I_Continuation.h:160)
==1400==    by 0x75EE62: _ZN7EThread15execute_regularEv (UnixEThread.cc:244)
==1400==    by 0x75D849: _ZL21spawn_thread_internalPv (Thread.cc:85)
==1400==    by 0x68E8593: start_thread (in /usr/lib64/libpthread-2.27.so)
==1400==    by 0x773C0DE: clone (in /usr/lib64/libc-2.27.so)
==1400==  Address 0xf2f4330 is 0 bytes inside a block of size 288 free'd
==1400==    at 0x4C3029C: _ZdlPv (vg_replace_malloc.c:576)
==1400==    by 0x6CBF88: _ZN17TransformTerminus12handle_eventEiPv (Transform.cc:419)
==1400==    by 0x75DEF1: _ZN7EThread13process_eventEP5Eventi (I_Continuation.h:160)
==1400==    by 0x75EE62: _ZN7EThread15execute_regularEv (UnixEThread.cc:244)
==1400==    by 0x75D849: _ZL21spawn_thread_internalPv (Thread.cc:85)
==1400==    by 0x68E8593: start_thread (in /usr/lib64/libpthread-2.27.so)
==1400==    by 0x773C0DE: clone (in /usr/lib64/libc-2.27.so)
==1400==  Block was alloc'd at
==1400==    at 0x4C2F226: _Znwm (vg_replace_malloc.c:334)
==1400==    by 0x6CA6D8: _ZN18TransformProcessor4openEP12ContinuationP7APIHook (Transform.cc:91)
==1400==    by 0x5020F9: _ZN6HttpSM17do_transform_openEv (HttpSM.cc:5094)
==1400==    by 0x54C5C8: _ZN12HttpTransact49handle_cache_operation_on_forward_server_responseEPNS_5StateE (HttpTransact.cc:4364)
==1400==    by 0x54DAE2: _ZN12HttpTransact37handle_forward_server_connection_openEPNS_5StateE (HttpTransact.cc:3805)
==1400==    by 0x550E2C: _ZN12HttpTransact27handle_response_from_serverEPNS_5StateE (HttpTransact.cc:3459)
==1400==    by 0x551687: _ZN12HttpTransact14HandleResponseEPNS_5StateE (HttpTransact.cc:3160)
==1400==    by 0x505445: _ZN6HttpSM32call_transact_and_set_next_stateEPFvPN12HttpTransact5StateEE (HttpSM.cc:7109)
==1400==    by 0x51BDB9: _ZN6HttpSM17handle_api_returnEv (HttpSM.cc:1581)
==1400==    by 0x5148EB: _ZN6HttpSM17state_api_calloutEiPv (HttpSM.cc:1516)
==1400==    by 0x51B697: _ZN6HttpSM18state_api_callbackEiPv (HttpSM.cc:1283)
==1400==    by 0x4C31CC: TSHttpTxnReenable (InkAPI.cc:5825)
==1400==    by 0x2887DA38: _ZL8cachefunP10tsapi_cont7TSEventPv (main.cpp:2906)
==1400==    by 0x4AFBD2: _ZN15INKContInternal12handle_eventEiPv (InkAPI.cc:1070)
==1400==    by 0x5149C4: _ZN6HttpSM17state_api_calloutEiPv (HttpSM.cc:1443)
==1400==    by 0x51B89F: _ZN6HttpSM12main_handlerEiPv (HttpSM.cc:2543)
==1400==    by 0x75DEF1: _ZN7EThread13process_eventEP5Eventi (I_Continuation.h:160)
==1400==    by 0x75EE62: _ZN7EThread15execute_regularEv (UnixEThread.cc:244)
==1400==    by 0x75D849: _ZL21spawn_thread_internalPv (Thread.cc:85)
==1400==    by 0x68E8593: start_thread (in /usr/lib64/libpthread-2.27.so)
==1400==    by 0x773C0DE: clone (in /usr/lib64/libc-2.27.so)
==1400== 
==1400== Jump to the invalid address stated on the next line
==1400==    at 0x0: ???
==1400==    by 0x566E44: _ZN10HttpTunnel12producer_runEP18HttpTunnelProducer (HttpTunnel.cc:1023)
==1400==    by 0x56731E: _ZN10HttpTunnel10tunnel_runEP18HttpTunnelProducer (HttpTunnel.cc:759)
==1400==    by 0x51C0E1: _ZN6HttpSM17handle_api_returnEv (HttpSM.cc:1617)
==1400==    by 0x5148EB: _ZN6HttpSM17state_api_calloutEiPv (HttpSM.cc:1516)
==1400==    by 0x51B697: _ZN6HttpSM18state_api_callbackEiPv (HttpSM.cc:1283)
==1400==    by 0x4C31CC: TSHttpTxnReenable (InkAPI.cc:5825)
==1400==    by 0x2887DF58: _ZL8cachefunP10tsapi_cont7TSEventPv (main.cpp:3180)
==1400==    by 0x4AFBD2: _ZN15INKContInternal12handle_eventEiPv (InkAPI.cc:1070)
==1400==    by 0x5149C4: _ZN6HttpSM17state_api_calloutEiPv (HttpSM.cc:1443)
==1400==    by 0x51B89F: _ZN6HttpSM12main_handlerEiPv (HttpSM.cc:2543)
==1400==    by 0x75DEF1: _ZN7EThread13process_eventEP5Eventi (I_Continuation.h:160)
==1400==    by 0x75EE62: _ZN7EThread15execute_regularEv (UnixEThread.cc:244)
==1400==    by 0x75D849: _ZL21spawn_thread_internalPv (Thread.cc:85)
==1400==    by 0x68E8593: start_thread (in /usr/lib64/libpthread-2.27.so)
==1400==    by 0x773C0DE: clone (in /usr/lib64/libc-2.27.so)
==1400==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==1400== 
traffic_server: received signal 11 (Segmentation fault)
traffic_server - STACK TRACE: 
/usr/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0x8e)[0x4a5b7e]
/lib64/libpthread.so.0(+0x11fc0)[0x68f2fc0]
==1400== 
==1400== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==1400==    at 0x68F2E39: raise (in /usr/lib64/libpthread-2.27.so)
==1400==    by 0x4E98F86: _Z20signal_crash_handleriP9siginfo_tPv (signals.cc:184)
==1400==    by 0x4A5B7D: _Z19crash_logger_invokeiP9siginfo_tPv (Crash.cc:170)
==1400==    by 0x68F2FBF: ??? (in /usr/lib64/libpthread-2.27.so)
==1400== 
==1400== HEAP SUMMARY:
==1400==     in use at exit: 884,260,699 bytes in 496,376 blocks
==1400==   total heap usage: 97,770,089 allocs, 97,273,713 frees, 6,554,975,437 bytes allocated
==1400== 
==1400== For a detailed leak analysis, rerun with: --leak-check=full
==1400== 
==1400== For counts of detected and suppressed errors, rerun with: -v
==1400== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault

**Comment by traeak** [comment]
Please provide a sequence of events that lead up to this crash?  Was there during an actual simple remap?

**Comment by bryancall** [comment]
If this is still an issue please reopen.
