### ISSUE TITLE
Building the ATS from source

### ISSUE THREAD

**Issue by itstamil** [apache/trafficserver#4096]
hi,
while building from source with several configuration parameters then the **make** have initiated 
After that i need that complete build source as an deb package for my use (because i won't like repeating the same thing) for that i have installed an package called **checkinstall**  even i obtain the .deb package 
but the issue is i have installed that .deb on my other machine it shows that 
**starting traffic server                                                              [fail]**

can please tell me what is the error cause

**Comment by bryancall** [comment]
If this is still an issue please email the users@ mailing list.
