### ISSUE TITLE
openclose_h2 and double tests are brittle

### ISSUE THREAD

**Issue by d2r** [apache/trafficserver#4120]
See #4113 .

This test is inconsistent when run repeatedly and is causing Alarm Fatigue among developers.

It needs to be fixed so that it can be effective without creating false negatives.

**Comment by d2r** [comment]
See also #4131, where a running tests for a documentation change resulted in an error.

**Comment by d2r** [comment]
A new test was added with #4145 that was exhibiting similar brittle behavior. If we find the common fix, we should enable that test too.

**Comment by d2r** [comment]
@macisasandwich had been looking into whether the root cause for the unstable behavior was actually in autest, which was found to be closing pipes to sub-processes without reading all of the output streams first.

If this has been fixed, then we should restore the tests that have been skipped.

**Comment by ywkaras** [comment]
openclose_h2 and double tests are not skipped don't seem to be causing any problems.  This issue should be closed by a committer.

**Comment by d2r** [comment]
Yes I think this probably was fixed with a change to autest—maybe @macisasandwich knows which version—and with #4580.
