### ISSUE TITLE
Duplicate code handling address types (ink_inet, Machine)

### ISSUE THREAD

**Issue by d2r** [apache/trafficserver#4159]
Both [ink_inet](https://github.com/apache/trafficserver/blob/3fc04c4590d7e47ba648b06f973c874d6ff900fc/lib/ts/ink_inet.cc#L540-L644) and [Machine]( https://github.com/apache/trafficserver/blob/3fc04c4590d7e47ba648b06f973c874d6ff900fc/iocore/utils/Machine.cc#L68-L234) share structures and logic.

It would be good to consolidate the common code so that it is clear what code is used and so that changes are not missed via duplication.

**Comment by d2r** [comment]
This issue is still valid.

**Comment by SolidWallOfCode** [comment]
Fixed by #8095.
