### ISSUE TITLE
Log in Squid format it not working 

### ISSUE THREAD

**Issue by itsmalathi** [apache/trafficserver#4162]
Hi,
I was using apache traffic server with version 7.1.x which is build in custom configuration in that i have enabled the log in squid format using the following command 

CONFIG proxy.config.log.squid_log_enabled INT 1
CONFIG proxy.config.log.squid_log_is_ascii INT 1
CONFIG proxy.config.log.squid_log_name STRING access.log
CONFIG proxy.config.log.squid_log_header STRING NULL

but there is no event log is entering in the file **access.log**    i have configured every thing with correct manner then I won't know what's happening here

please help to enable the log file on apache traffic server

**Comment by masaori335** [comment]
These configs looks deprecated. Please use `proxy.config.log.logging_enabled` in `records.config` and `logging.config`.
More details are in
- https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/logging/understanding.en.html#understanding-ts-logs
- https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/logging.config.en.html

**Comment by masaori335** [comment]
Please reopen this issue, if you have any trouble with logging.config.
