### ISSUE TITLE
Fix config syntax in Layer 4 routing

### ISSUE THREAD

**Issue by pushkar2017** [apache/trafficserver#4180]
https://docs.trafficserver.apache.org/en/latest/admin-guide/layer-4-routing.en.html#sni-routing
The example config uses JSON format, but we have moved to YAML parsing so it would be wrong.

The HTTP CONNECT arrow in the diagram is also misleading. That is an internal mechanism through which ATS tunnels the bytes to the upstream.

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
