### ISSUE TITLE
push method 返回404

### ISSUE THREAD

**Issue by zxh555** [apache/trafficserver#4197]
ats按照官方配置如下：
ip_allow.config
src_ip=127.0.0.1                                  action=ip_allow method=ALL
records.config
CONFIG proxy.config.http.push_method_enabled INT 1

telnet发送push请求：
telnet 127.0.0.1 8080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
PUSH http://www.company.com HTTP/1.0
Content-length: 84

HTTP/1.0 200 OK
Content-type: text/html
Content-length: 17

<HTML>
a
</HTML>HTTP/1.0 404 Not Found
Date: Wed, 05 Sep 2018 11:57:03 GMT
Server: ATS/7.1.4
Cache-Control: no-store
Content-Type: text/html
Content-Language: en
Content-Length: 297

<HTML>
<HEAD>
<TITLE>Not Found on Accelerator</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>Not Found on Accelerator</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: Your request on the specified host was not found.
Check the location and try again.
</B></FONT>
<HR>
</BODY>
Connection closed by foreign host.

返回404？ why

**Comment by shukitchan** [comment]
I think you are still required to have an entry in remap.config. 
Or you can try setting this to 0 and see - https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-url-remap-remap-required

**Comment by scw00** [comment]
@zxh555 close this issue now since the author has figured it out .
