### ISSUE TITLE
Overridable config list is not complete

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#4202]
Overridable configurations below are undocumented.

TS_CONFIG_HTTP_CACHE_ENABLE_DEFAULT_VARY_HEADER
TS_CONFIG_HTTP_CACHE_IGNORE_ACCEPT_CHARSET_MISMATCH
TS_CONFIG_HTTP_CACHE_IGNORE_ACCEPT_ENCODING_MISMATCH
TS_CONFIG_HTTP_CACHE_IGNORE_ACCEPT_LANGUAGE_MISMATCH
TS_CONFIG_HTTP_CACHE_IGNORE_ACCEPT_MISMATCH
TS_CONFIG_HTTP_CACHE_VARY_DEFAULT_IMAGES
TS_CONFIG_HTTP_CACHE_VARY_DEFAULT_OTHER
TS_CONFIG_HTTP_CACHE_VARY_DEFAULT_TEXT
TS_CONFIG_HTTP_REQUEST_BUFFER_ENABLED
TS_CONFIG_SSL_CLIENT_VERIFY_SERVER

https://docs.trafficserver.apache.org/en/latest/developer-guide/api/functions/TSHttpOverridableConfig.en.html

**Comment by maskit** [comment]
This is still a valid issue.

**Comment by mlibbey** [comment]
Shall we close this out? with #4581 merged?

**Comment by maskit** [comment]
Yes, thanks.
