### ISSUE TITLE
Send MAX_STREAMS frame if needed

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#4224]
Like sending `MAX_(STREAM_)DATA` frame, endpoints need to increase `max_(uni|bidi)_streams` via sending `MAX_STREMA_ID` frame. Details are written in [Draft-14 10.2.  Stream Limit Increment](https://tools.ietf.org/html/draft-ietf-quic-transport-14#section-10.2).

It looks like `QUICStreamManager` is suitable to generate `MAX_STREAM_ID` frame.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
