### ISSUE TITLE
ATS as Forward Proxy - For an Origin server with two IPs, and when the first IP is down, requests fail with 502 error

### ISSUE THREAD

**Issue by vksiva** [apache/trafficserver#4236]
ATS as a Forward Proxy - For a url whose domain name resolves to two IPs and the first IP is down - ATS fails with a 502 error.

ATS never falls back to the second IP, which incidentally is up. Tried the same with Squid Proxy and it forwarded the request to the working IP.

Config:
proxy.config.http.connect_attempts_rr_retries 3

Is there some configuration that I need to set to ensure that if one of the IPs is not working, ATS should fallback to the working IP.

**Comment by hankai17** [comment]
same as https://github.com/apache/trafficserver/issues/4214 ?

**Comment by vksiva** [comment]
@hankai17 - exact same issue - but there doesn't seem to be any resolution. Also, #4214 is closed. Even if one of the IP is working, ATS throws a 502 error. Is there any configuration 

I am missing or is it by design?

**Comment by SolidWallOfCode** [comment]
Have you tried adjusting [this](https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html#proxy-config-http-connect-attempts-max-retries)? That might cause ATS to move on before existing all upstream retries.

**Comment by vksiva** [comment]
@SolidWallOfCode - proxy.config.http.connect_attempts_max_retries is unchanged, and is defaulted to 3. While there are only two IPs for the OS, it should have moved to the second IP after the first try, it did not. 
proxy.config.http.connect_attempts_rr_retries defaults to 3. I will limit this parameter to 1 and see if that helps.
Thanks for the suggestion.

**Comment by bryancall** [comment]
@vksiva Did you try setting proxy.config.http.connect_attempts_rr_retries to a lower value?

**Comment by hankai17** [comment]
Refer https://github.com/apache/trafficserver/pull/4810. May resolved this.

**Comment by bryancall** [comment]
@vksiva Please reopen if this is still and issue.
