### ISSUE TITLE
Host resolution from /etc/hosts file

### ISSUE THREAD

**Issue by vksiva** [apache/trafficserver#4237]
ATS v7.1.3 as Forward Proxy:

Though the /etc/nsswitch.conf has the  following
```
hosts:          files dns
```
TS is not using the /etc/hosts entries, rather resolves the domain using the dns server.

How do I force TS to use /etc/hosts entries before trying the dns servers to resolve hosts?

**Comment by mlibbey** [comment]
I think you need to set
https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html#proxy-config-hostdb-host-file-path
(and
https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html#proxy-config-hostdb-host-file-interval
)

**Comment by SolidWallOfCode** [comment]
@mlibbey is correct, this is the mechanism for doing as requested.

**Comment by vksiva** [comment]
I had set proxy-config-hostdb-host-file-path to /etc/hosts but had left the proxy-config-hostdb-host-file-interval as 1 day. I will check if the host file has been used for host resolution and report back.

**Comment by SolidWallOfCode** [comment]
Allright.

**Comment by vksiva** [comment]
@mlibbey, @SolidWallOfCode  - Thanks for tip. It worked like a charm.
