### ISSUE TITLE
ATS 7.1.4 crash

### ISSUE THREAD

**Issue by l2lizard** [apache/trafficserver#4246]
Apache Traffic Server - traffic_server - 7.1.4 - (build # 083006 on Aug 30 2018 at 06:16:21)

traffic_server: received signal 11 (Segmentation fault)
traffic_server - STACK TRACE:
/usr/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0x9e)[0x4b105e]
/lib64/libpthread.so.0(+0xf6d0)[0x2b1ed9b1c6d0]
Fatal: PluginVC.cc:126: failed assertion `magic == PLUGIN_VC_MAGIC_ALIVE`
traffic_server: using root directory '/usr'
traffic_server: received signal 6 (Aborted)
traffic_server - STACK TRACE:
/usr/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0x9e)[0x4b105e]
/lib64/libpthread.so.0(+0xf6d0)[0x2b175c04a6d0]
/lib64/libc.so.6(gsignal+0x37)[0x2b175ccb0277]
/lib64/libc.so.6(abort+0x148)[0x2b175ccb1968]
/usr/lib64/trafficserver/libtsutil.so.7(+0x2d6b8)[0x2b175a72d6b8]
/usr/lib64/trafficserver/libtsutil.so.7(+0x2b575)[0x2b175a72b575]
/usr/bin/traffic_server(_ZN8PluginVC12main_handlerEiPv+0x4a6)[0x4f09c6]
/usr/bin/traffic_server(_ZN7EThread13process_eventEP5Eventi+0x140)[0x7263d0]
/usr/bin/traffic_server(_ZN7EThread15execute_regularEv+0x2f1)[0x727001]
/usr/bin/traffic_server[0x725e3a]
/lib64/libpthread.so.0(+0x7e25)[0x2b175c042e25]
/lib64/libc.so.6(clone+0x6d)[0x2b175cd78bad]
traffic_server: received signal 11 (Segmentation fault)
traffic_server - STACK TRACE:
/usr/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0x9e)[0x4b105e]
/lib64/libpthread.so.0(+0xf6d0)[0x2acdbabc16d0]

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
