### ISSUE TITLE
Missing Error Check in function SSL_CTX_new()

### ISSUE THREAD

**Issue by lc3412** [apache/trafficserver#4292]
Function SSL_CTX_new() returns NULL if the creation of a new SSL_CTX object failed. However , the return value of function SSL_CTX_new() is not checked. See the following code:

line : 1166
https://github.com/apache/trafficserver/blob/5ee6a5f554880b02535e6ee84268df922e87274d/tools/http_load/http_load.c#L1166-L1177

==============================================================================

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/apps folder

line : 178
Ref : https://github.com/openssl/openssl/blob/0db957dbbcf6a432086ab913378c23636d8c374c/apps/ciphers.c#L178-L180
```c
line 178:    ctx = SSL_CTX_new(meth);
line 179:    if (ctx == NULL)
line 180:        goto err;
```
Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by bryancall** [comment]
@lc3412 Did you want to make a PR for the change?

**Comment by alokrahul513** [comment]
Hi, I want to work on this issue. Can you help me to get started?

**Comment by bryancall** [comment]
@shinrich is going to put up a PR for this
