### ISSUE TITLE
Missing Error Check in function SSL_new()

### ISSUE THREAD

**Issue by lc3412** [apache/trafficserver#4293]
Function SSL_new() returns NULL if the creation of a new SSL structure failed. However , the return value of function SSL_new() is not checked. See the following code:

line : 1189
https://github.com/apache/trafficserver/blob/5ee6a5f554880b02535e6ee84268df922e87274d/tools/http_load/http_load.c#L1189-L1197

===============================================================================

We find the return value of this call been checked in openssl project with the version of openssl 1.1.2.
Such as in openssl/apps folder

line :  206
Ref : https://github.com/openssl/openssl/blob/0db957dbbcf6a432086ab913378c23636d8c374c/apps/ciphers.c#L206-L208
```c
line 206:    ssl = SSL_new(ctx);
line 207:    if (ssl == NULL)
line 208:       goto err;
```

Chi Li, Zuxing Gu, Jiecheng Wu

**Comment by bryancall** [comment]
Relates to #4292

**Comment by bryancall** [comment]
@lc3412 Did you want to make a PR for this?

**Comment by alokrahul513** [comment]
Hi, I want to work on this issue. How to get started?

**Comment by bryancall** [comment]
@shinrich is going to put up a PR for this
