### ISSUE TITLE
QUIC: Ceases transmission and retransmission of STREAM frames on the identified stream

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#4295]
>After sending a RST_STREAM, an endpoint ceases transmission and retransmission of STREAM frames on the identified stream. A receiver of RST_STREAM can discard any data that it already received on that stream.

**Comment by maskit** [comment]
QUICStreamState should know which frames are allowed to be transmitted on the current state of a stream, and I think QUICStream does the check before generating frames.

QUICPacketRetransmitter would need a way to access QUICStreamState.

**Comment by maskit** [comment]
#3762 should cover this.

**Comment by maskit** [comment]
Now QUICStream is responsible for retransmitting STREAM frames, and it should respect own stream state.
