### ISSUE TITLE
Download page must link to KEYS file

### ISSUE THREAD

**Issue by sebbASF** [apache/trafficserver#4321]
The download page [1] MUST link to the KEYS file at

https://www.apache.org/dist/trafficserver/KEYS

It should also describe how to use the sigs or hashes to verify downloads.

MD5 and SHA1 hashes are now deprecated and should not be linked from the download page.

**Comment by sebbASF** [comment]
This has still not been properly fixed.

The link to the KEYS file must use https://www.apache.org/dist/trafficserver/KEYS.
It is currently using http and the archive server.

Also the link name should be KEYS to make it easy to find on the page.

**Comment by sebbASF** [comment]
PING - please fix this

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.

**Comment by sebbASF** [comment]
(I cannot re-open the issue as I did not close it)
Sorry, but the page is still wrong.

The link to the KEYS file must use https://www.apache.org/dist/trafficserver/KEYS.
It is currently using http and the archive server.

Also the link name should be KEYS to make it easy to find on the page.

Furthermore, MD5/SHA1 hashes should not be linked from the download page unless there are no others for a historic release.
