### ISSUE TITLE
Ports configured for QUIC should not listen for TCP

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#4410]
QUIC uses only UDP but this configuration below also opens sockets for TCP:
```
4433:quic 4433:quic:ipv6
```

```
$ netstat -an | grep 4433
tcp        0      0 0.0.0.0:4433            0.0.0.0:*               LISTEN     
tcp6       0      0 :::4433                 :::*                    LISTEN     
udp        0      0 0.0.0.0:4433            0.0.0.0:*                          
udp6       0      0 :::4433                 :::*
```

It happens only if I run traffic_server with `trafficserver start`.

**Comment by SolidWallOfCode** [comment]
It doesn't happen if you run `traffic_server` directly? The port opening logic should be literally the same code.

**Comment by maskit** [comment]
I just double checked. This does not happen if I run `traffic_server` directly.

**Comment by maskit** [comment]
$ trafficserver start
```
$ lsof -i:4433 -P
COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
traffic_m 1763 masakazu   14u  IPv4  27408      0t0  TCP *:4433 (LISTEN)
traffic_m 1763 masakazu   15u  IPv6  27409      0t0  TCP *:4433 (LISTEN)
[TS_MAIN] 1769 masakazu   14u  IPv4  27408      0t0  TCP *:4433 (LISTEN)
[TS_MAIN] 1769 masakazu   15u  IPv6  27409      0t0  TCP *:4433 (LISTEN)
[TS_MAIN] 1769 masakazu   52u  IPv4  30286      0t0  UDP *:4433 
[TS_MAIN] 1769 masakazu   53u  IPv6  30287      0t0  UDP *:4433 
```

$ traffic_server
```
$ lsof -i:4433 -P
COMMAND    PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
[TS_MAIN] 1902 masakazu   42u  IPv4  36361      0t0  UDP *:4433 
[TS_MAIN] 1902 masakazu   43u  IPv6  36362      0t0  UDP *:4433
```

**Comment by bryancall** [comment]
@maskit Should we even fix this since traffic_manager is going away in ATS 10?

**Comment by zwoop** [comment]
So what should this look like?

```
80 80:ipv6 443:ssl:quic 443:ipv6:ssl:quic
```

or

```
80 80:ipv6 443:ssl 443:ipv6:ssl 443:quic 443:ipv6:quic
```

if we like the former, then just this should not bind TCP port 443, which seems a little confusing:

```
80 80:ipv6 443:quic 443:ipv6:quic
```

**Comment by maskit** [comment]
> Should we even fix this since traffic_manager is going away in ATS 10?

It depends on how it will be removed. If we just don't use traffic_manager anymore in terms of listening ports and traffic_server don't do similar things, then there will be nothing to do.

> So what should this look like?

I've been using the latter style because I use a different port at the moment (most implementers use 4433 for interop). I'm fine with either styles, but making `ssl` and `quic` exclusive would be easy to understand. We can think like:

Format:
```
port[:network-layer-protocol][:transport-layer-protocol]
```

Network layer protocol (exclusive):
- ipv4 (default): IPv4
- ipv6: IPv6

Transport layer protocol (exclusive):
- tcp(default): TCP
- ssl: TLS (TCP+TLS)
- quic: QUIC (UDP+TLS)

**Comment by maskit** [comment]
I had to fix this because traffic_manager still exists, and I found a bug that well-known ports are not available for QUIC.
