### ISSUE TITLE
ats7.1.4  push method sometime return ERR_INVALID_REQ/400  ，error log ：status 400 (Cache Write Failed)   the cpu io net all run in lowwater  why？？？

### ISSUE THREAD

**Issue by zxh555** [apache/trafficserver#4418]
1539676195.257 14 127.0.0.1 TCP_HIT/200 716 GET http://127.0.0.1:32125/rest/v1/content/53a016612043bbe39ccde07892f4ec0c/meta-info - NONE/- -
1539676195.272 0 127.0.0.1 TCP_MISS/200 118 PUSH http://127.0.0.1:32125/rest/v1/content/53a016612043bbe39ccde07892f4ec0c/meta-info - DIRECT/- -
1539676195.248 30 127.0.0.1 TCP_MISS/200 118 PUSH http://127.0.0.1:32125/rest/v1/content/a652ceda5764cbe7e13eb10b1d02d547/1/9 - DIRECT/- -
1539676195.277 2 127.0.0.1 TCP_MISS/201 123 PUSH http://127.0.0.1:32125/rest/v1/content/836af7e12773212cc14649dd0d4da9c4/1/7 - DIRECT/- -
1539676195.279 0 127.0.0.1 TCP_MEM_HIT/200 720 GET **http://127.0.0.1:32125/rest/v1/content/53a016612043bbe39ccde07892f4ec0c/meta-info - NONE/- -
1539676195.279 8 127.0.0.1 ERR_INVALID_REQ/400 410 PUSH** http://127.0.0.1:32125/rest/v1/content/53a016612043bbe39ccde07892f4ec0c/meta-info - NONE/- text/html
1539676195.289 2 127.0.0.1 TCP_MISS/201 123 PUSH http://127.0.0.1:32125/rest/v1/content/836af7e12773212cc14649dd0d4da9c4/1/8 - DIRECT/- -
1539676195.299 1 127.0.0.1 TCP_MISS/201 123 PUSH http://127.0.0.1:32125/rest/v1/content/836af7e12773212cc14649dd0d4da9c4/1/9 - DIRECT/- -
1539676195.284 23 127.0.0.1 TCP_MISS/200 118 PUSH http://127.0.0.1:32125/rest/v1/content/a652ceda5764cbe7e13eb10b1d02d547/1/13 - DIRECT/- -
1539676195.310 2 127.0.0.1 TCP_MISS/201 123 PUSH 

HttpTransact::HandlePushCacheWrite(State *s)
{
  switch (s->cache_info.write_lock_state) {
  case CACHE_WL_SUCCESS:
    // We were able to get the lock for the URL vector in the cache
    if (s->cache_info.action == CACHE_PREPARE_TO_WRITE) {
      s->cache_info.action = CACHE_DO_WRITE;
    } else if (s->cache_info.action == CACHE_PREPARE_TO_UPDATE) {
      s->cache_info.action = CACHE_DO_REPLACE;
    } else {
      ink_release_assert(0);
    }
    set_headers_for_cache_write(s, &s->cache_info.object_store, &s->hdr_info.server_request, &s->hdr_info.server_response);

    TRANSACT_RETURN(SM_ACTION_STORE_PUSH_BODY, nullptr);
    break;

  case CACHE_WL_FAIL:
  case CACHE_WL_READ_RETRY:
    // No write lock, can not complete request so bail
    HandlePushError(s, "Cache Write Failed");
    break;
  case CACHE_WL_INIT:
  default:
    ink_release_assert(0);
  }
}

会走入 case CACHE_WL_READ_RETRY:

**Comment by scw00** [comment]
If you update an object which has been written for other writer. And the other writer has not written the first fragment down. This error will occur to signal user the object has been written by other routine.
