### ISSUE TITLE
Confusing/misleading code for ProxyClientSession class.

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#4428]
The only two entries in the eventmap array that are actually used are for SSN_START and SSN_CLOSE.

There are various data members (api_hookid, api_current, api_scope, perhaps more) that are used to iterate over hooked continuations for a particular hook.  These should be replaced by an instance of an iterator subclass.

**Comment by ywkaras** [comment]
@dyrock is working on improving hook handling more generally:  https://github.com/apache/trafficserver/pull/4141

**Comment by ywkaras** [comment]
Hmm 4141 has been closed.  I closed https://github.com/apache/trafficserver/pull/4710 because 4141 was supposed to be a more comprehensive fix for this problem.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
