### ISSUE TITLE
ats7.1.4 get method sometime has no response 

### ISSUE THREAD

**Issue by zxh555** [apache/trafficserver#4440]
**request**
![image](https://user-images.githubusercontent.com/17612824/47210146-c069a580-d3c4-11e8-838f-7efa64c133be.png)

**ats do not responds in 500ms**
![image](https://user-images.githubusercontent.com/17612824/47275672-ec16a680-d5e3-11e8-8aa2-15b74f010cb0.png)

**some key debug log (in another request**
![image](https://user-images.githubusercontent.com/17612824/47276719-bd9cc980-d5eb-11e8-9043-65424225e65f.png)

**detail debug log**
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2431 (HandleCacheOpenReadHitFreshness)> (http_trans) [26480] [HandleCacheOpenReadHitFreshness] response_received_time : 1539921470
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7296 (calculate_document_freshness_limit)> (http_match) [26480] calculate_document_freshness_limit --- max_age set, freshness_limit = 157680000
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7387 (calculate_document_freshness_limit)> (http_match) [26480] calculate_document_freshness_limit --- final freshness_limit = 31536000
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7517 (what_is_document_freshness)> (http_match) [26480] [what_is_document_freshness] fresh_limit:  31536000  current_age: 8669
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7564 (what_is_document_freshness)> (http_match) [26480] [..._document_freshness] initial age limit: 31536000
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7620 (what_is_document_freshness)> (http_match) [26480] document_freshness --- current_age = 8669
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7621 (what_is_document_freshness)> (http_match) [26480] document_freshness --- age_limit   = 31536000
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7622 (what_is_document_freshness)> (http_match) [26480] document_freshness --- fresh_limit = 31536000
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7623 (what_is_document_freshness)> (http_seq) [26480] document_freshness --- current_age = 8669
[Oct 19 14:22:19.944] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7624 (what_is_document_freshness)> (http_seq) [26480] document_freshness --- age_limit   = 31536000
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7625 (what_is_document_freshness)> (http_seq) [26480] document_freshness --- fresh_limit = 31536000
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:7644 (what_is_document_freshness)> (http_match) [26480] [..._document_freshness] document is fresh; returning FRESHNESS_FRESH
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2441 (HandleCacheOpenReadHitFreshness)> (http_seq) [26480] [HttpTransact::HandleCacheOpenReadHitFreshness] Fresh copy
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2522 (need_to_revalidate)> (http_seq) [26480] [HttpTransact::HandleCacheOpenReadHit] Authentication not needed
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:7204 (call_transact_and_set_next_state)> (http) [26480] State Transition: SM_ACTION_API_READ_CACHE_HDR -> SM_ACTION_API_CACHE_LOOKUP_COMPLETE
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:1417 (state_api_callout)> (http) [26480] calling plugin on hook TS_HTTP_CACHE_LOOKUP_COMPLETE_HOOK at hook 0x2ad034028fe0
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:1296 (state_api_callback)> (http) [26480] [&HttpSM::state_api_callback, HTTP_API_CONTINUE]
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:1336 (state_api_callout)> (http) [26480] [&HttpSM::state_api_callout, HTTP_API_CONTINUE]
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2620 (HandleCacheOpenReadHit)> (http_seq) [26480] [HttpTransact::HandleCacheOpenReadHit] Authentication not needed
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2690 (HandleCacheOpenReadHit)> (http_trans) [26480] CacheOpenRead --- needs_auth          = 0
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2691 (HandleCacheOpenReadHit)> (http_trans) [26480] CacheOpenRead --- needs_revalidate    = 0
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2692 (HandleCacheOpenReadHit)> (http_trans) [26480] CacheOpenRead --- response_returnable = 1
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2693 (HandleCacheOpenReadHit)> (http_trans) [26480] CacheOpenRead --- needs_cache_auth    = 0
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2694 (HandleCacheOpenReadHit)> (http_trans) [26480] CacheOpenRead --- send_revalidate     = 0
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2826 (HandleCacheOpenReadHit)> (http_trans) [26480] CacheOpenRead --- HIT-FRESH
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2828 (HandleCacheOpenReadHit)> (http_seq) [26480] [HttpTransact::HandleCacheOpenReadHit] Serve from cache
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:2925 (build_response_from_cache)> (http_trans) [26480] [build_response_from_cache] Match! Serving full document.
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTransact.cc:6873 (handle_content_length_header)> (http_trans) [26480] [handle_content_length_header] RESPONSE cont len in hdr is 2097152
-- State Machine Id: 26480
-- State Machine Id: 26480
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:7204 (call_transact_and_set_next_state)> (http) [26480] State Transition: SM_ACTION_API_CACHE_LOOKUP_COMPLETE -> SM_ACTION_SERVE_FROM_CACHE
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:5775 (perform_cache_write_action)> (http) [26480] perform_cache_write_action CACHE_DO_SERVE
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTunnel.cc:683 (add_producer)> (http_tunnel) [26480] adding producer 'cache read'
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTunnel.cc:738 (add_consumer)> (http_tunnel) [26480] adding consumer 'user agent'
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpTunnel.cc:1162 (producer_handler)> (http_tunnel) [26480] producer_handler [cache read VC_EVENT_READ_COMPLETE]
[Oct 19 14:22:19.945] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:3352 (tunnel_handler_cache_read)> (http) [26480] [&HttpSM::tunnel_handler_cache_read, VC_EVENT_READ_COMPLETE]
[Oct 19 14:22:19.946] Server {0x2ad0325cc700} DEBUG: <HttpTunnel.cc:1359 (consumer_handler)> (http_tunnel) [26480] consumer_handler [user agent VC_EVENT_WRITE_READY]
[Oct 19 14:22:19.946] Server {0x2ad0325cc700} DEBUG: <HttpTunnel.cc:1359 (consumer_handler)> (http_tunnel) [26480] consumer_handler [user agent VC_EVENT_ERROR]
[Oct 19 14:22:19.946] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:3183 (tunnel_handler_ua)> (http) [26480] [&HttpSM::tunnel_handler_ua, VC_EVENT_ERROR]
[Oct 19 14:22:19.946] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:2607 (main_handler)> (http) [26480] [HttpSM::main_handler, HTTP_TUNNEL_EVENT_DONE]
[Oct 19 14:22:19.946] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:2879 (tunnel_handler)> (http) [26480] [&HttpSM::tunnel_handler, HTTP_TUNNEL_EVENT_DONE]
[Oct 19 14:22:19.946] Server {0x2ad0325cc700} DEBUG: <HttpSM.cc:6947 (kill_this)> (http) [26480] deallocating sm

**source code**
void
write_to_net_io(NetHandler *nh, UnixNetVConnection *vc, EThread *thread)
{
  NetState *s       = &vc->write;
  ProxyMutex *mutex = thread->mutex.get();

  MUTEX_TRY_LOCK_FOR(lock, s->vio.mutex, thread, s->vio._cont);

  if (!lock.is_locked() || lock.get_mutex() != s->vio.mutex.get()) {
    write_reschedule(nh, vc);
    return;
  }

  // This function will always return true unless
  // vc is an SSLNetVConnection.
  if (!vc->getSSLHandShakeComplete()) {
    int err, ret;

    if (vc->get_context() == NET_VCONNECTION_OUT) {
      ret = vc->sslStartHandShake(SSL_EVENT_CLIENT, err);
    } else {
      ret = vc->sslStartHandShake(SSL_EVENT_SERVER, err);
    }

    if (ret == EVENT_ERROR) {
      vc->write.triggered = 0;
      write_signal_error(nh, vc, err);
    } else if (ret == SSL_HANDSHAKE_WANT_READ || ret == SSL_HANDSHAKE_WANT_ACCEPT) {
      vc->read.triggered = 0;
      nh->read_ready_list.remove(vc);
      read_reschedule(nh, vc);
    } else if (ret == SSL_HANDSHAKE_WANT_CONNECT || ret == SSL_HANDSHAKE_WANT_WRITE) {
      vc->write.triggered = 0;
      nh->write_ready_list.remove(vc);
      write_reschedule(nh, vc);
    } else if (ret == EVENT_DONE) {
      vc->write.triggered = 1;
      if (vc->write.enabled) {
        nh->write_ready_list.in_or_enqueue(vc);
      }
    } else {
      write_reschedule(nh, vc);
    }

    return;
  }

  // If it is not enabled,add to WaitList.
  if (!s->enabled || s->vio.op != VIO::WRITE) {
    write_disable(nh, vc);
    return;
  }

  // If there is nothing to do, disable
  int64_t ntodo = s->vio.ntodo();
  if (ntodo <= 0) {
    write_disable(nh, vc);
    return;
  }

  MIOBufferAccessor &buf = s->vio.buffer;
  ink_assert(buf.writer());

  // Calculate the amount to write.
  int64_t towrite = buf.reader()->read_avail();
  if (towrite > ntodo) {
    towrite = ntodo;
  }

  int signalled = 0;

  // signal write ready to allow user to fill the buffer
  if (towrite != ntodo && buf.writer()->write_avail()) {
    if (write_signal_and_update(VC_EVENT_WRITE_READY, vc) != EVENT_CONT) {
      return;
    }

    ntodo = s->vio.ntodo();
    if (ntodo <= 0) {
      write_disable(nh, vc);
      return;
    }

    signalled = 1;

    // Recalculate amount to write
    towrite = buf.reader()->read_avail();
    if (towrite > ntodo) {
      towrite = ntodo;
    }
  }

  // if there is nothing to do, disable
  ink_assert(towrite >= 0);
  if (towrite <= 0) {
    write_disable(nh, vc);
    return;
  }

  int needs             = 0;
  int64_t total_written = 0;
  int64_t r             = vc->load_buffer_and_write(towrite, buf, total_written, needs);

  if (total_written > 0) {
    NET_SUM_DYN_STAT(net_write_bytes_stat, total_written);
    s->vio.ndone += total_written;
    net_activity(vc, thread);
  }

  // A write of 0 makes no sense since we tried to write more than 0.
  ink_assert(r != 0);
  // Either we wrote something or got an error.
  // check for errors
  if (r < 0) { // if the socket was not ready, add to WaitList
    if (r == -EAGAIN || r == -ENOTCONN || -r == EINPROGRESS) {
      NET_INCREMENT_DYN_STAT(net_calls_to_write_nodata_stat);
      if ((needs & EVENTIO_WRITE) == EVENTIO_WRITE) {
        vc->write.triggered = 0;
        nh->write_ready_list.remove(vc);
        write_reschedule(nh, vc);
      }

      if ((needs & EVENTIO_READ) == EVENTIO_READ) {
        vc->read.triggered = 0;
        nh->read_ready_list.remove(vc);
        read_reschedule(nh, vc);
      }

      return;
    }

    vc->write.triggered = 0;
    write_signal_error(nh, vc, (int)-total_written);
    return;
  } else {                                        // Wrote data.  Finished without error
    int wbe_event = vc->write_buffer_empty_event; // save so we can clear if needed.

    // If the empty write buffer trap is set, clear it.
    if (!(buf.reader()->is_read_avail_more_than(0))) {
      vc->write_buffer_empty_event = 0;
    }

    // If there are no more bytes to write, signal write complete,
    ink_assert(ntodo >= 0);
    if (s->vio.ntodo() <= 0) {
      write_signal_done(VC_EVENT_WRITE_COMPLETE, nh, vc);
      return;
    }

    int e = 0;
    if (!signalled) {
      e = VC_EVENT_WRITE_READY;
    } else if (wbe_event != vc->write_buffer_empty_event) {
      // @a signalled means we won't send an event, and the event values differing means we
      // had a write buffer trap and cleared it, so we need to send it now.
      e = wbe_event;
    }

    if (e) {
      if (write_signal_and_update(e, vc) != EVENT_CONT) {
        return;
      }

      // change of lock... don't look at shared variables!
      if (lock.get_mutex() != s->vio.mutex.get()) {
        write_reschedule(nh, vc);
        return;
      }
    }

    if ((needs & EVENTIO_READ) == EVENTIO_READ) {
      read_reschedule(nh, vc);
    }

    if (!(buf.reader()->is_read_avail_more_than(0))) {
      write_disable(nh, vc);
      return;
    }

    if ((needs & EVENTIO_WRITE) == EVENTIO_WRITE) {
      write_reschedule(nh, vc);
    }

    return;
  }
}
**in this function load_buffer_and_write return -32 EPIPE error**
int64_t  r             = vc->load_buffer_and_write(towrite, buf, total_written, needs);

**Comment by scw00** [comment]
What does get method error mean ? Can you share more information?

**Comment by zxh555** [comment]
> What does get method error mean ? Can you share more information?

set the client read timeout from 500ms to 2s ，the problem resovled。thanks for your attention。

**Comment by zxh555** [comment]
> What does get method error mean ? Can you share more information?

set the client read timeout from 500ms to 2s,the problem resolved , thanks for your attention.
