### ISSUE TITLE
QUIC Discarding Unused Keys 

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#4446]
>4.9. Discarding Unused Keys
>After QUIC moves to a new encryption level, packet protection keys for previous encryption levels can be discarded. This occurs several times during the handshake, as well as when keys are updated (see Section 6).
Packet protection keys are not discarded immediately when new keys are available. If packets from a lower encryption level contain CRYPTO frames, frames that retransmit that data MUST be sent at the same encryption level. Similarly, an endpoint generates acknowledgements for packets at the same encryption level as the packet being acknowledged. Thus, it is possible that keys for a lower encryption level are needed for a short time after keys for a newer encryption level are available.
An endpoint cannot discard keys for a given encryption level unless it has both received and acknowledged all CRYPTO frames for that encryption level and when all CRYPTO frames for that encryption level have been acknowledged by its peer. However, this does not guarantee that no further packets will need to be received or sent at that encryption level because a peer might not have received all the acknowledgements necessary to reach the same state.
After all CRYPTO frames for a given encryption level have been sent and all expected CRYPTO frames received, and all the corresponding acknowledgments have been received or sent, an endpoint starts a timer. For 0-RTT keys, which do not carry CRYPTO frames, this timer starts when the first packets protected with 1-RTT are sent or received. To limit the effect of packet loss around a change in keys, endpoints MUST retain packet protection keys for that encryption level for at least three times the current Retransmission Timeout (RTO) interval as defined in [QUIC-RECOVERY]. Retaining keys for this interval allows packets containing CRYPTO or ACK frames at that encryption level to be sent if packets are determined to be lost or new packets require acknowledgment.
Though an endpoint might retain older keys, new data MUST be sent at the highest currently-available encryption level. Only ACK frames and retransmissions of data in CRYPTO frames are sent at a previous encryption level. These packets MAY also include PADDING frames.
Once this timer expires, an endpoint MUST NOT either accept or generate new packets using those packet protection keys. An endpoint can discard packet protection keys for that encryption level.

**Comment by maskit** [comment]
Discarding Initial Keys was done with these two commits.
0636a4a6ffb51729354ea329a882b86eb4bd10e7
22364902841f999e933c2439baa3491e24f507dd

> The successful use of Handshake packets indicates that no more
   Initial packets need to be exchanged, as these keys can only be
   produced after receiving all CRYPTO frames from Initial packets.
   Thus, a client MUST discard Initial keys when it first sends a
   Handshake packet and a server MUST discard Initial keys when it first
   successfully processes a Handshake packet.  Endpoints MUST NOT send
   Initial packets after this point.

**Comment by scw00** [comment]
When generating packets, It seems we can skip the encrypt level  which key has been discarded .

**Comment by maskit** [comment]
Good point. You mean this part, right?

https://github.com/apache/trafficserver/blob/0636a4a6ffb51729354ea329a882b86eb4bd10e7/iocore/net/QUICNetVConnection.cc#L1247-L1250

Yeah, we can skip encryption levels that we don't have keys for.

**Comment by scw00** [comment]
exactly.

**Comment by maskit** [comment]
Suspend this for a while because new frames that control key drop timing might be introduced.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
