### ISSUE TITLE
verify_config segfaults

### ISSUE THREAD

**Issue by ema** [apache/trafficserver#4466]
`traffic_server -C verify_config` segfaults on ATS 8.0.0 with the following output:
    
    root@sid:~# traffic_server -C verify_config
    Traffic Server 8.0.0 Oct 17 2018 18:40:51 localhost
    traffic_server: using root directory '/usr'
    NOTE: VERIFY

    traffic_server - STACK TRACE:
    /lib/x86_64-linux-gnu/libpthread.so.0(+0x128e0)[0x7f7b2c9138e0]
    traffic_server(_Z16reloadUrlRewritev+0x66)[0x560a4391d366]
    traffic_server(+0xf7d17)[0x560a4370ed17]
    traffic_server(main+0x14f2)[0x560a436cb162]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f7b2c42eb17]
    traffic_server(_start+0x2a)[0x560a436d674a]
    Segmentation fault

@SolidWallOfCode confirmed on IRC that master is affected too, and mentioned "the ref counting stuff for remap rules" as the possible culprit.

The issue is surely not reproducible on 7.1.3, I haven't had the chance to try 7.1.4.

**Comment by ema** [comment]
Fixed in master, closing.

**Comment by poblahblahblah** [comment]
Did this ever make it's way into a valid 8.x branch? We're seeing this issue on 8.1.1.
