### ISSUE TITLE
RecGetRecordString() should provide the out-string length

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#4467]
Since RecGetRecordString() (and _xmalloc version) does essentially a strlcpy, it'd be nice if it returned the length of the string it copied. We can keep the return codes, but make it take an int* out type. I also think all these functions have the wrong return type, it ought to be e.g.

```
RecErrT RecGetRecordString(const char *name, char *buf, int buf_len, int  *out_len, bool lock);
```

**Comment by zwoop** [comment]
This is true for a lot of these APIs btw, where the return type ought to be RecErrT

**Comment by SolidWallOfCode** [comment]
These should return a `string_view` instead of doing any copying at all. The value is essentially static in the records data, correct? Or is a config reload a concern?

**Comment by zwoop** [comment]
Note that these existing string APIs do either does a malloc, or copies to a provided buffer. I don't know for sure how important that, but imagine that's what your concern about reloadable configs comes in?

**Comment by bryancall** [comment]
We shouldn't use string_view here since we have to make a copy of the string.

**Comment by SolidWallOfCode** [comment]
The point would be to be able avoid a copy if it's not needed, if all that's needed is to parse it while it's on the stack.

**Comment by bryancall** [comment]
I am closing this.  When we move to YAML things are going to change.
