### ISSUE TITLE
Seems wrong that the copy and move constructor for class Errata do exactly the same thing.

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#4511]
https://github.com/apache/trafficserver/blob/master/lib/tsconfig/Errata.cc#L78

**Comment by SolidWallOfCode** [comment]
Did you look at [PR 4209](https://github.com/apache/trafficserver/pull/4209)?

**Comment by ywkaras** [comment]
I guess it 's best to make it clear.  The rules for the compiler generating a move constructor are more complex than I though.  https://godbolt.org/z/Aaljt3
