### ISSUE TITLE
cannot install mysql_remap plugin

### ISSUE THREAD

**Issue by chuyenim** [apache/trafficserver#4525]
Hello,
I've installed trafficserver but mysql_remap plugin is not installed.

```
wget https://github.com/apache/trafficserver/archive/7.1.4.tar.gz
tar -zxvf 7.1.4.tar.gz
cd trafficserver-7.1.4/
```

```
autoreconf -i
./configure --enable-experimental-plugins && make
make install
```
Find the plugin:
`find / -name mysql_remap.so # not found anything`

Please help me or give me any suggestion.

System: Centos 7

**Comment by maskit** [comment]
Do you have `mysql.h` on your build environment? You may need to install some package (maybe mysql-devel) to build the plugin.

**Comment by chuyenim** [comment]
> Do you have `mysql.h` on your build environment? You may need to install some package (maybe mysql-devel) to build the plugin.

Thank for your suggestion, I will trying to install mysql first.

**Comment by chuyenim** [comment]
```
checking mysql/mysql.h usability... yes
checking mysql/mysql.h presence... yes
checking for mysql/mysql.h... yes
checking for mysql_info in -lmysqlclient... no
```

I installed all mysql/mariadb-devel libraries but mysql_info still is NO! :(

**Comment by chuyenim** [comment]
Hi, I found this but I don't know how to do that:

`
NOTE: you may need to open the Makefile and adjust the paths to MySQL client includes & libraries
`

**Comment by maskit** [comment]
configure.ac need to be fixed, but a workaround would be:
```
$ LDFLAG="-L /usr/lib64/mysql" ./configure .....
```

**Comment by chuyenim** [comment]
> configure.ac need to be fixed, but a workaround would be:

Hi, it works, but require no space between "L" and "/usr/.."

```
$ LDFLAGS="-L/usr/lib64/mysql" ./configure .....
```

Thank you very much

**Comment by chuyenim** [comment]
The mysql_remap plugin is installed successfully but I cannot use it. An error found:

```
Fatal: unable to load '/usr/local/trafficserver/libexec/trafficserver/mysql_remap.so': /usr/local/trafficserver/libexec/trafficserver/mysql_remap.so: undefined symbol: _Z18iniparser_freedictP12_dictionary_
```

**Comment by maskit** [comment]
Weird. Looks like `_Z18iniparser_freedictP12_dictionary_ ` is in `mysql_remap/lib/iniparser.c`.
What does happen if you uninstall the package?

**Comment by chuyenim** [comment]
> Weird. Looks like `_Z18iniparser_freedictP12_dictionary_ ` is in `mysql_remap/lib/iniparser.c`.
> What does happen if you uninstall the package?

Yes, I can found mysql_remap exists.

```
[root]# less /usr/local/trafficserver/libexec/trafficserver/mysql_remap.so
"/usr/local/trafficserver/libexec/trafficserver/mysql_remap.so" may be a binary file.  See it anyway? 
```

But I don't know why it cannot loaded.

**Comment by maskit** [comment]
I'm saying that we may not need to install iniparser package with yum, because the library seems like included in mysql_remap plugin directory and is linked statically.

**Comment by chuyenim** [comment]
Yes, I also don't install iniparser but the results are not improved.
I created a new Centos7 instance from Vultr the run fhese commands as below:

```
# The following packages must be installed:
sudo yum -y install gcc gcc-c++ pkgconfig pcre-devel tcl-devel expat-devel openssl-devel
sudo yum -y install libcap libcap-devel hwloc hwloc-devel ncurses-devel libcurl-devel mariadb-devel
sudo yum -y install autoconf automake libtool yum-utils
# Install package 7.1.4
cd /usr/local/src/
wget https://github.com/apache/trafficserver/archive/7.1.4.tar.gz
## wget https://github.com/apache/trafficserver/archive/8.0.0.tar.gz
## tar -zxvf 8.0.0.tar.gz && cd trafficserver-8.0.0/
tar -zxvf 7.1.4.tar.gz && cd trafficserver-7.1.4/

autoreconf -i
LDFLAGS="-L/usr/lib64/mysql" ./configure --enable-experimental-plugins && make
make install
## DONE
```
Then these commands for mysql-server:
```
wget https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
sudo rpm -ivh mysql57-community-release-el7-9.noarch.rpm
sudo yum install mysql-server
sudo systemctl start mysqld
```
After that:

-- create mysql_remap database & edit hostname table
-- create new file: `mysql_remap.ini`
-- edit records.config
-- edit plugin.config, add new line: `mysql_remap.so /usr/local/etc/trafficserver/mysql_remap.ini`
-- start trafficserver
-- bin/traffic_server -T "mysql_remap"

**Comment by maskit** [comment]
I realized that the source files are a mix of C++ and C. This is the reason it cannot find some symbols. Try this patch.

```diff
--- a/plugins/experimental/mysql_remap/mysql_remap.cc
+++ b/plugins/experimental/mysql_remap/mysql_remap.cc
@@ -22,7 +22,9 @@
 #include <unistd.h>
 
 #include "mysql/mysql.h"
+extern "C" {
 #include "lib/iniparser.h"
+}
 #include "default.h"
 
 MYSQL mysql;

```

**Comment by chuyenim** [comment]
Hi, I want to make some changes in mysql_remap plugin. How can I re-compile it without installing ATS again?
Thank you in advanced!

**Comment by chuyenim** [comment]
Hello,
I think if we can use Redis to remap it will faster than Mysql.

**Comment by maskit** [comment]
Let's keep this issue about build issues on mysql_remap plugin. Please create a new issue for feature requests.

**Comment by maskit** [comment]
If you keep posting mysql_remap plugin issues here, this issue won't be closed forever. Please create new issues appropriately.

And I'm afraid I've never used this plugin so I'm not sure the port issue is a limitation. As far as I know, plugins can't control what ports ATS listen on. The configuration is in records.config.

**Comment by chuyenim** [comment]
I've opened port 8080 and setup in remap.config it works well but when I used mysql_remap plugin, it couldn't work.

**Comment by chuyenim** [comment]
Thanks @maskit for your help. The installation is fixed. This issue could be closed.

**Comment by maskit** [comment]
> I've opened port 8080 and setup in remap.config it works well but when I used mysql_remap plugin, it couldn't work.

OK, then it must be a limitation or a bug in the plugin.

Although workarounds for the build issues are posted here, I'm going to keep this issue open as a known issue until we fix them on our repo.

**Comment by bryancall** [comment]
We are planning on deprecating the plugin for 9.0.0.  There will be an email going out to the users@ mailing list about this.  Please give feedback on the mailing list if you still want this plugin.

If this is still an issue please reopen.
