### ISSUE TITLE
I cannot isntall trafficserver 8.0 on Centos 7

### ISSUE THREAD

**Issue by chuyenim** [apache/trafficserver#4530]
Hi,
I spent several days to trying to install trafficserver on my VPS (Centos7) but it's not success.

```
# For ATS v8.0.0 and later, a compiler with support for C++17 is required. 
# You can install this using devtoolset-7 on both CentOS 6 and 7:
sudo yum install centos-release-scl
sudo yum-config-manager --enable rhel-server-rhscl-7-rpms
sudo yum install devtoolset-7
```

However, the error displays like this:
```
checking checking whether c++ -std=c++17 supports -std=c++17... no
configure: error: *** A compiler with support for -std=c++17 is required.
```

**Comment by SolidWallOfCode** [comment]
You also need to source the "enable" script to enable Dev Tool Set 7. E.g., at your command prompt
```
source /opt/rh/devtoolset-7/enable
```
I have that in my ".bashrc". You can check if this has been done with
```
which g++
```
If the returned path isn't in "/opt/rh/devtoolset-7" then you're not using the compiler in Dev Tool Set 7.

**Comment by maskit** [comment]
The instruction on our wiki needs to be updated.
https://cwiki.apache.org/confluence/display/TS/CentOS

@SolidWallOfCode Can you update the instruction with appropriate command lines?
`scl` command seems like another option, but I'm not sure what the difference is.
https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

**Comment by SolidWallOfCode** [comment]
OK.

**Comment by SolidWallOfCode** [comment]
Wiki instructions updated.

The `scl` command is just another way of running the `enable` script. I find it too cumbersome to recommend, better to just `enable` in your `.bash-rc`.
