### ISSUE TITLE
Add weights to consistent_hash algorithm

### ISSUE THREAD

**Issue by mustafa1024m** [apache/trafficserver#4549]
Hi,
I have multiple parent servers, but they are not similar in size, I want to assign weight to each server in the consistent_hash algorithm and I couldn't find it in parent.config nor anywhere else.
I could find traces to weights in the code.
https://github.com/apache/trafficserver/blob/master/proxy/ParentConsistentHash.cc

**Comment by zwoop** [comment]
@vmamidi @jrushford This is something to consider for the next-hop projects. In general, I think we need to look at what commercial load balancers allows here, and I think weights makes sense.

**Comment by mlibbey** [comment]
We actually do have this feature. 
parent="p1.x.com:80|1.0,p2.x.com:80|2.0" round_robin=consistent_hash
will have p2.x get twice the number of requests as p1.

It appears I inadvertently removed the example in the v6 doc. In my defense, it wasn't mentioned anywhere else though!

**Comment by mustafa1024m** [comment]
> We actually do have this feature.
> parent="p1.x.com:80|1.0,p2.x.com:80|2.0" round_robin=consistent_hash
> will have p2.x get twice the number of requests as p1.
> 
> It appears I inadvertently removed the example in the v6 doc. In my defense, it wasn't mentioned anywhere else though!

This is great, thank you :+1:  Can you please add it to the documentation, so everybody can see it.
Should I close this issue, or you will?

**Comment by mlibbey** [comment]
I'm fighting the doc build requirements, I'll use this issue to link the PR. If I can't get the build stuff to work soon, I'll just hope that the format comes out fine :)

**Comment by mlibbey** [comment]
@mustafa1024m think we can close this now?

**Comment by mustafa1024m** [comment]
> @mustafa1024m think we can close this now?

Yes, thank you for the doc updates :)
