### ISSUE TITLE
mysql_remap plugin cannot listen on the port not 80

### ISSUE THREAD

**Issue by chuyenim** [apache/trafficserver#4563]
mysql_remap cannot listen on ports not 80 (ex: 8080)

```
+----+--------------+----------------+---------+------------+
| id | from_scheme | from_host | from_port | to_scheme | to_host    | to_port  |
|  1 | http        | ts.gcod.net   |     80 | http      | gaopppro.com   |    80 |    
|  2 | http        | ts1.gcod.net  |   8080 | http      | domain.com     |    80 |  
+----+--------------+----------------+---------+------------+
```
ID#1 works well but ID#2 doesn't work.

**Comment by bryancall** [comment]
You would have to modify the ports for ATS to listen on port 8080:
https://docs.trafficserver.apache.org/en/8.0.x/admin-guide/files/records.config.en.html?highlight=records.config#proxy-config-http-server-ports
