### ISSUE TITLE
Configurable TLS version by SNI context

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#4593]
With ssl_server_name.yaml, it would be nice to specify the TLS version. Specifically, we get asked if we could turn off TLS 1.0 on particular domains/properties/SNIs/whatever you want to call it :) But, other domains may need to handle the ancient clients that can't do >=TLS1.1. Perhaps a minimum TLS version?

**Comment by bryancall** [comment]
This has been added.
