### ISSUE TITLE
move assignment table id from storage.config to cache data

### ISSUE THREAD

**Issue by djcarlin** [apache/trafficserver#4608]
can the assignment table key be part of the cache data?

So when a stripe comes online, it knows the key because its in the cache data - instead of having the assignment table id mapping in storage.config

Would make maintaining systems with 30 spindles easier.

**Comment by bryancall** [comment]
On modern Linux kernels you can use disk uuids

**Comment by zwoop** [comment]
Often times, I wish that disk management and initialization was an out-of-band thing, e.g.

```
% sudo traffic_cache_tool initialize /dev/sda /dev/sdb /dev/sdc
```

Which generates the headers necessary for these disks, including the "hash key" (which can now be randomly generated). Then, when we start traffic_server, it can simply scan all block devices, looking for the appropriate ATS disk header, and add those as needed. This could theoretically eliminate storage.config, and disk management becomes a task for when you bring up the box; just like you initialize file systems, you initialize ATS cache disks as part of the setup.

**Comment by bryancall** [comment]
The consensus is to use uuid or udev
