### ISSUE TITLE
Should we get rid of the ssl.wire_trace feature?

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#4652]
We had used it for a while in an attempt to debug TLS issues and do some packet capture.  However, we have moved on to use other mechanisms.  If others are not using this feature, we should probably remove it.  I fear that it will fail with other TLS reworks if no one is watching it.

**Comment by zwoop** [comment]
I agree.

**Comment by bryancall** [comment]
+1 we should remove it.

**Comment by bryancall** [comment]
Blocks #5457

**Comment by shinrich** [comment]
Looks like it is now gone.

**Comment by bryancall** [comment]
It was removed in this commit: 6ee5c616d165b969b42a86c4eb2ca0b1be86b881
