### ISSUE TITLE
Problem with using it as reverse proxy 

### ISSUE THREAD

**Issue by 1a1a11a** [apache/trafficserver#4665]
Hi there, I am new to ATS, I cloned the repo and installed it on a VM under home directory, then I try to test as a reverse proxy. So I follow the tutorial change the settings in `record.config` and `remap.config`, I have attached the `remap.config` and the log below. I am trying to redirect traffic to port 8096 to 2048 where I have a server listening on, but it is blocked somewhere. 

```                                                
map http://127.0.0.1:80/ http://127.0.0.1:2048  
map http://127.0.0.1:8096/ http://127.0.0.1:2048
```

```
[Nov 29 18:51:12.667] {0x7f15f51d2f40} NOTE: [ProxyStateSet] Traffic Server Args: ' -M'                             
[Nov 29 18:51:12.667] {0x7f15f51d2f40} NOTE: [LocalManager::listenForProxy] Listening on port: 8096 (ipv4)          
[Nov 29 18:51:12.667] {0x7f15f51d2f40} NOTE: [LocalManager::listenForProxy] Listening on port: 8096 (ipv6)          
[Nov 29 18:51:12.667] {0x7f15f51d2f40} NOTE: [LocalManager::startProxy] Launching ts process                        
[Nov 29 18:51:12.672] {0x7f15f51d2f40} NOTE: [LocalManager::pollMgmtProcessServer] New process connecting fd '12'   
[Nov 29 18:51:12.672] {0x7f15f51d2f40} NOTE: [Alarms::signalAlarm] Server Process born                              
[Nov 29 18:51:14.678] {0x7f15f51d2f40} NOTE: [Alarms::signalAlarm] Server Process was reset                         
[Nov 29 18:51:15.679] {0x7f15f51d2f40} NOTE: Relaunching proxy after 60 sec...                                      
```

**Comment by shinrich** [comment]
You might try setting the the debug tags for http.  That should provide messages in traffic.out. https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-diags-debug-enabled

What client are you using to general the initial request?  You might also try to catch folks in the IRC for more interactive ideas.

**Comment by 1a1a11a** [comment]
Thank you very much! I have re-compiled and installed it, then it began to work. The debug tag you pointed out is really useful!

**Comment by 1a1a11a** [comment]
What is the IRC?
