### ISSUE TITLE
keep-alive is buggy in 8.0.1 with https

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#4728]
looking if https://github.com/apache/trafficserver/issues/3502 got better it turned out things are much worser in 8.0.1 - with more than 300 requests "ab" don't finish at all while keep-alive is no problem without https

Concurrency Level:      150
Time taken for tests:   0.182 seconds
Complete requests:      300
Failed requests:        150
   (Connect: 0, Receive: 0, Length: 0, Exceptions: 150)
Keep-Alive requests:    150

Concurrency Level:      150
Time taken for tests:   0.120 seconds
Complete requests:      150
Failed requests:        4
   (Connect: 0, Receive: 0, Length: 0, Exceptions: 4)
Keep-Alive requests:    86

[builduser@buildserver:/rpmbuild/SPECS]$ ab -c 150 -n 400 -k https://proxy.test.rh:8443/rte/upload/logo.gif
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/
Benchmarking proxy.test.rh (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 300 requests completed

**Comment by zwoop** [comment]
Yes, we ran into this as well, and I've already reverted the offending commit. So, latest 8.0.x branch should not experience this problem any more. It'll go into 8.0.2 as well.

**Comment by zwoop** [comment]
The commit to apply to 8.0.1 is f6fe5f0079005813d33d1cddd9d127c75a1f5e0b.

**Comment by thelounge-zz** [comment]
is there some planned time window for 8.0.2?
i mean that's a serious bug and version numbers are cheap
