### ISSUE TITLE
logfile permissions

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#4729]
is there any reason why a) the permissions are always changed at restart and b) are that inconstistent?
when i say "chmod 0660 *.log" i mean that until i say the opposite  - period

[root@buildserver:/var/log/trafficserver]$ ls
insgesamt 8,0K
-rw-r--r-- 1 ats ats 2,0K 2018-12-20 11:32 diags.log
-rw-rw---- 1 ats ats    0 2018-12-20 11:29 error.log
-rw-r--r-- 1 ats ats 1,5K 2018-12-20 11:31 manager.log

**Comment by bryancall** [comment]
@bneradt Can you please verify the permissions are correct for the files.

**Comment by bneradt** [comment]
The ATS chmod calls are actually a configurable feature. We have three separate records.config parameters for this:

* [proxy.config.output.logfile_perm](https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-output-logfile-perm)
* [proxy.config.log.logfile_perm](https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-log-logfile-perm)
* [proxy.config.diags.logfile_perm](https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-diags-logfile-perm)

These each take a full Unix DAC specification (`rw-rw----`, e.g.). Between these three, you should be able to control all permission modifications on all log files written to by Traffic Server. I verified on one of our internal ATS boxes that this is the case for our set of log files. (Notice the documented comment about umask and how that limits what permissions ATS can set, however.) The permissions are changed upon the first write to a particular log file after the service comes up.

**Comment by thelounge-zz** [comment]
don't get me wrong but calling chmod and have config settings for logfile permissions is pervert
this is done by UMASK and the only job you have is open the file and bail out if you can't
