### ISSUE TITLE
ATS7.1.2 Some logs print twice into traffic.out

### ISSUE THREAD

**Issue by hankai17** [apache/trafficserver#4742]
reproduce：

```
CONFIG proxy.config.diags.debug.enabled INT 1
CONFIG proxy.config.diags.debug.tags STRING http.*|dns.*
```

then restart ats

tailf traffic.out you can see that situation

**Comment by hankai17** [comment]
Are there any new changes  in LogSys?

**Comment by zwoop** [comment]
Can you show an example of the lines that are duplicated? Are they all duplicated ??
