### ISSUE TITLE
QUIC: Acknowledge the retransmitted INITIAL frame 

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#4743]
The retransmitted initial frame is not acknowledged when handshake is not complete.

**Comment by scw00** [comment]
>Prior to validating the client address, servers MUST NOT send more than three times as many bytes as the number of bytes they have received. This limits the magnitude of any amplification attack that can be mounted using spoofed source addresses. In determining this limit, servers only count the size of successfully processed packets.

>Clients MUST pad UDP datagrams that contain only Initial packets to at least 1200 bytes. Once a client has received an acknowledgment for a Handshake packet it MAY send smaller datagrams. Sending padded datagrams ensures that the server is not overly constrained by the amplification restriction.

Because ngtcp2 will retransmit INITAIL Frame multi-times. The server only ack the latest  3 times of a Initial frame in INITIAL level. 

Actually we should send the several bytes as client sent.

**Comment by maskit** [comment]
This may be related to #4905 and things may changed, because we currently send only 3 packets on a non-validated path and the limitation was replaced with a new limitation based on transferred data size.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
