### ISSUE TITLE
plugins/experimental/slice/    How to  PURGE  ?

### ISSUE THREAD

**Issue by GarfieldLinux** [apache/trafficserver#4790]
hey  
   Awesome , I noticed that  new   plugin "slice"   But  problems  here:

  1. How to  PURGE  Object in  cache  
    cache_key like this "http://test.com/test.tar.gz-bytes=0-1"
                                     "http://test.com/test.tar.gz-bytes=2-3"
                                     "http://test.com/test.tar.gz-bytes=3-4"
   
   May be  many times PURGE(via cache_key) , Does this impair system performance and Disk IO(I'm sure that the method PURGE  need read disk)? 

By the way , good job on plugin slice  .  Thanks  .

**Comment by traeak** [comment]
The self healing slice plugin now by default uses the first slice by default.  To purge it just purge the first slice.  A missing first slice will result in no asset found, otherwise it will cause new matching asset slices to be fetched.
