### ISSUE TITLE
Fatal: unable to load remap.config in ats 7.1.5

### ISSUE THREAD

**Issue by zhang15535135608** [apache/trafficserver#4795]
I add rule "map http://a.com http://b.com @plugin=regex_remap.so @pparam=maps.r" in remap.config. 

the log is:
 #   ./traffic_server 
traffic_server: using root directory '/usr/local/ats'
[Jan 14 19:24:14.638] Server {0x7f143e657780} DIAG: (regex_remap) Plugin is successfully initialized
Fatal: unable to load remap.config

**Comment by BeijingWks** [comment]
I also encountered the same problem, how did you solve it in the end?
