### ISSUE TITLE
traffic_server naming confusion 

### ISSUE THREAD

**Issue by 1a1a11a** [apache/trafficserver#4800]
I accidentally thought I was using `traffic_server`, then things like IPC (`traffic_ctl`) stops working, and `traffic_server` are not ran in the background. I can't figure out for a while, then I realized that I should be using `trafficserver` instead of `traffic_server`, this is really confusing.

**Comment by shinrich** [comment]
Actually you want to be using trafficserver.service if you are using systemd.   Ultimately you will be using some starting script that is appropriate for your daemon management system.  

But yes, for just starting off, it isn't necessarily clear which program/script kicks everything off.  The getting started documentation or README could be improved no doubt.

**Comment by 1a1a11a** [comment]
Thank you for pointing out this, Susan! @shinrich Does ATS accept pull request on documentation? And what are the requirements?

**Comment by mlibbey** [comment]
Yes please! We prefer to have the commit start with Doc: or Documentation ... and if you can, assign a Documentation label to the PR.
