### ISSUE TITLE
fast_signal passed in but not used `ProtectedQueue::enqueue(Event *e, bool fast_signal)`

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#4813]
Seems fast_signal is deprecated. Better to remove it from the signature.

**Comment by zizhong** [comment]
@oknet @scw00 @SolidWallOfCode any inputs?

**Comment by bryancall** [comment]
This was removed between 8.1.x and 9.0.x

**Comment by masaori335** [comment]
@duke8253 did it by https://github.com/apache/trafficserver/pull/6104. Thanks!
