### ISSUE TITLE
Server Process was reset infinitely (v.7.1.5)

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#4821]
in some of my servers, i found traffic_server restart infinitely,  following is the clues i had found:

1) /var/log/syslog
traffic_cop[7983]: (test) write failed [111 'Connection refused']
traffic_cop[7983]: server heartbeat failed [1]
traffic_cop[7983]: (test) write failed [111 'Connection refused']
traffic_cop[7983]: server heartbeat failed [2]
traffic_cop[7983]: killing server
traffic_server[8714]: NOTE: --- traffic_server Starting ---
traffic_server[8714]: NOTE: traffic_server Version: Apache Traffic Server - traffic_server - 7.1.5 - (build # 011710 on Jan 17 2019 at 10:34:52)
traffic_server[8714]: NOTE: RLIMIT_NOFILE(7):cur(1000000),max(1000000)

2) only cache.db &  host.db.syncing generated, but no host.db ( storage.config)

3) server process was reset every 20 seconds for the first three reset
[Jan 17 11:34:17.703] Manager {0x7f7ae45ef780} NOTE: [Alarms::signalAlarm] Server Process was reset
[Jan 17 11:34:37.729] Manager {0x7f7ae45ef780} NOTE: [Alarms::signalAlarm] Server Process was reset
[Jan 17 11:34:57.754] Manager {0x7f7ae45ef780} NOTE: [Alarms::signalAlarm] Server Process was reset
[Jan 17 11:35:17.781] Manager {0x7f7ae45ef780} NOTE: [Alarms::signalAlarm] Server Process was reset
[Jan 17 11:35:47.812] Manager {0x7f7ae45ef780} NOTE: [Alarms::signalAlarm] Server Process was reset
[Jan 17 11:36:17.835] Manager {0x7f7ae45ef780} NOTE: [Alarms::signalAlarm] Server Process was reset

4)some timeout & retry config
proxy.config.http.connect_attempts_timeout: 5
proxy.config.http.cache.open_read_retry_time: 10
proxy.config.dns.lookup_timeout: 6
proxy.config.hostdb.lookup_timeout: 6
proxy.config.ssl.ocsp.request_timeout: 15
proxy.config.icp.query_timeout: 2
proxy.config.socks.server_connect_timeout: 5
proxy.config.lm.pserver_timeout_secs: 1
proxy.config.cluster.mc_poll_timeout: 5
proxy.config.cluster.startup_timeout: 10
proxy.config.process_manager.timeout: 5
proxy.config.vmap.down_up_timeout: 10
proxy.config.alarm.script_runtime: 5
proxy.config.http.congestion_control.default.dead_os_conn_timeout: 15
proxy.config.net.poll_timeout: 10
proxy.config.http.connect_attempts_max_retries: 2
proxy.config.cache.read_while_writer.max_retries: 5
proxy.config.http.cache.open_read_retry_time: 10
proxy.config.cache.mutex_retry_delay: 2
proxy.config.dns.retries: 3
proxy.config.log.collation_retry_sec: 5
proxy.config.update.retry_count: 10
proxy.config.update.retry_interval: 2
proxy.config.http.congestion_control.default.proxy_retry_interval: 10
proxy.config.http.congestion_control.default.live_os_conn_retries: 2
proxy.config.http.congestion_control.default.dead_os_conn_retries: 1
proxy.config.http.safe_requests_retryable: 1
proxy.config.http.cache.max_open_write_retries: 1
proxy.config.net.retry_delay: 10

**Comment by shukitchan** [comment]
anything else shown in error.log/diags.log/manager.log ?

**Comment by esmq2092** [comment]
after several hours debuging,  the problem become clean ...
the remap.config contains too many entries that have tslua plugin enabled，
traffic_server can't start while it found having too many scripts to load...
