### ISSUE TITLE
Inconsistent clang-format check

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#4822]
Our git pre-commit hook runs clang-format against ".h.in" but "make clang-format" doesn't. If you had changes on "apidefs.h.in" and it wasn't formatted well, you wouldn't be able to commit anything (even if you ran suggested command line `$ make -j clang-format`).

**Comment by maskit** [comment]
IIRC, files under "tsconfig" can cause the same problem. But I don't remember why the files are not subject to clang-format.

**Comment by SolidWallOfCode** [comment]
As for "tsconfig", it is because some of them are generated. The plan, long term, is to replace all of that with YAML support.

I do agree that you can get in to a situation where the pre-commit hook blocks you while 'make clang-format` doesn't fix it.
