### ISSUE TITLE
fast signal for schedule an event with small timeout

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#4825]
To avoid the delay that scheduling an event with a small timeout to a sleeping thread.

**Comment by scw00** [comment]
event which schedule from negative event  or event scheduled to another thread might be delay. See #4695

**Comment by SolidWallOfCode** [comment]
When does this happen? It should be the case that when doing this, `signalActivity()` is invoked to wake up the sleeping thread. If you can point out a path where this doesn't happen, we can fix it.

**Comment by scw00** [comment]
See here:

https://github.com/apache/trafficserver/blob/bbcffa075ede77058dbb713d8c9bc42e2f0f9e81/iocore/eventsystem/UnixEThread.cc#L245-L261

What happen if we schedule event in negative queue it seems we have no chance check external queue unless we are going to next loop.

**Comment by SolidWallOfCode** [comment]
Gah, we need to get rid of the negative queue.

**Comment by bryancall** [comment]
@SolidWallOfCode got rid of the negative queue
