### ISSUE TITLE
If a TSCont has an associated TSMutex, destroying the TSCont with TSContDestroy() increases TSMutex reference count.

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#4854]
A minimal plugin and Au test is in https://github.com/ywkaras/trafficserver/tree/it_sucks , illustrating the problem.  Here is a capture from gdb, stepping thorough tests/tools/plugins/it_sucks.c:

```
Thread 1 "traffic_server" hit Breakpoint 1, TSPluginInit (n_args=1, args=0x7fffffffdae0)
    at /Users/wkaras/REPOS/TS2/tests/_sandbox/it_sucks/ts/plugin/it_sucks.c:38
38	  TSMutex m = TSMutexCreate();
Missing separate debuginfos, use: dnf debuginfo-install hwloc-libs-1.11.9-1.fc28.x86_64 libcap-2.25-9.fc28.x86_64 libgcc-8.1.1-1.fc28.x86_64 libstdc++-8.1.1-1.fc28.x86_64 libtool-ltdl-2.4.6-24.fc28.x86_64 numactl-libs-2.0.11-8.fc28.x86_64 openssl-libs-1.1.0h-3.fc28.x86_64 pcre-8.42-1.fc28.x86_64 systemd-libs-238-8.git0e0aa59.fc28.x86_64 xz-libs-5.2.4-2.fc28.x86_64 zlib-1.2.11-8.fc28.x86_64
(gdb) n
39	  TSCont c  = TSContCreate(ef, m);
(gdb) p ((ProxyMutex *) m)->m_refcount
$1 = 0
(gdb) n
40	  TSContDestroy(c);
(gdb) p ((ProxyMutex *) m)->m_refcount
$2 = 1
(gdb) n
41	  TSMutexDestroy(m);
(gdb) p ((ProxyMutex *) m)->m_refcount
$3 = 2
(gdb) n
Fatal: traffic_server/InkIOCoreAPI.cc:256: failed assertion `((ProxyMutex *)m)->refcount() == 0`

Thread 1 "traffic_server" received signal SIGABRT, Aborted.
0x00007ffff529ef2b in raise () from /usr/lib64/libc.so.6
(gdb)
```

Presumably TSContDestroy() should decrement the mutex reference count, not increment it.

**Comment by SolidWallOfCode** [comment]
I think this is an artifact of delayed destruction for the `TSCont`. If it can't be deleted immediately, then an event is scheduled to check again later. This event will have a mutex and that will be the same as the mutex for the `TSCont`, thereby bumping the reference count. You'd want to look at `m_deletable` and `m_deleted` in the `TSCont` to see what those are.

**Comment by ywkaras** [comment]
For some reason the m_deletable flag is initialized to 1:
```
Thread 1 "traffic_server" hit Breakpoint 1, TSPluginInit (n_args=1, args=0x7fffffffdae0)
    at /Users/wkaras/REPOS/TS2/tests/_sandbox/it_sucks/ts/plugin/it_sucks.c:38
38	  TSMutex m = TSMutexCreate();
(gdb) n
39	  TSCont c  = TSContCreate(ef, m);
(gdb) n
40	  TSContDestroy(c);
(gdb) p ((INKContInternal *) c)->m_deletable
$2 = 0
(gdb) 
```

**Comment by SolidWallOfCode** [comment]
What is `m_deleted`? I think it would be instructive to step through the TS code as it handles these calls to see what happens, and see where exactly the count is incremented instead of decremented. I looked through the source and the only place I could see a possible increment on the mutex reference count was in the event scheduling.

**Comment by oknet** [comment]
@ywkaras The `TSMutex` object will be freed by `TSContDestroy`, and you should not do `TSMutexDestroy` for it.
