### ISSUE TITLE
FreeList vs NUMA structure 

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#4861]
Not sure here .

The global freelist allocate  a chunk from system. But the thread local cache (ProxyAllocator) only apply a piece of chunk memory. It might do great harm to the numa structure.

**Comment by shinrich** [comment]
Given the great progress of allocator libraries (tcmalloc, jemalloc, mimalloc), we would probably be better served by using one of those rather than making our internal allocators smarter.
