### ISSUE TITLE
proxy.config.ssl.client.verify.server INT mapping incorrect

### ISSUE THREAD

**Issue by pixitha** [apache/trafficserver#4865]
According to the docs for [proxy.config.ssl.client.verify.server](https://docs.trafficserver.apache.org/en/8.0.x/admin-guide/files/records.config.en.html#proxy-config-ssl-client-verify-server) strict should be mapped to 1 (verification fails = terminate), however when set to 1 it actually appears to be using moderate policy, of log and continue.

`/usr/local/bin/traffic_server --version
Traffic Server 8.0.1 Jan 17 2019 15:14:49 localhost
traffic_server: using root directory '/usr/local'
Apache Traffic Server - traffic_server - 8.0.1 - (build # 011715 on Jan 17 2019 at 15:14:49)`

records.config:
`CONFIG proxy.config.ssl.client.verify.server INT 1`

`[Jan 25 15:08:54.904] {0x2ac2af523700} WARNING: Core server certificate verification failed for (example.com). Action=Continue Error=self signed certificate server=notexample.com(10.xx.xx.xx) depth=0
[Jan 25 15:08:54.904] {0x2ac2af523700} WARNING: SNI (example.com) not in certificate. Action=Continue server=notexample.com(10.xx.xx.xx)`

records.config:
`CONFIG proxy.config.ssl.client.verify.server INT 2`

`[Jan 25 15:53:54.073] {0x2b25b13a1700} WARNING: Core server certificate verification failed for (example.com). Action=Terminate Error=self signed certificate server=notexample.com(10.xx.xx.x) depth=0
[Jan 25 15:53:54.073] {0x2b25b13a1700} ERROR: SSL connection failed for 'example.com': error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed`

**Comment by bryancall** [comment]
This issue was resolved in 8.1.0, fixed by #5234
