### ISSUE TITLE
Questions about TSHttpTxnServerIntercept

### ISSUE THREAD

**Issue by zhang15535135608** [apache/trafficserver#4887]
I use TSHttpTxnServerIntercept in TS_HTTP_POST_REMAP_HOOK.  I expect to intercept  request and do response at this hook.

But, I not setup connet to backend server(os), and I don't know backend server(os) addr. So far, it's just a fake address. 

So  intercept_contp receive TS_EVENT_NET_ACCEPT_FAILD still. I can't respond in case.  I simply expect to block a http in the plug-in to make my own response,  I excpet callback TS_EVENT_NET_ACCEPT event. But why does this API require connect  OS?

**Comment by zhang15535135608** [comment]
I fake a 'right' address solved it.

**Comment by SolidWallOfCode** [comment]
I'm not sure what you mean by that. For example, the TLS Bridge plugin in "plugins/experimental/tls_bridge" ([see here](https://docs.trafficserver.apache.org/en/8.0.x/developer-guide/plugins/example-plugins/tls_bridge.en.html)) does an intercept and doesn't have to use a fake IP address. I'd recommend going through the code in "plugins" and "plugins/experimental" looking for examples.
