### ISSUE TITLE
Fix Address Validation During Connection Establishment

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#4905]
ATS limits sending 3 **packets** before validating the client address and sometimes we hit this limitation on quic.ogre.com server with long TPs. But the spec is changed somewhere around draft-15.

> 8.1.  Address Validation During Connection Establishment
>
>   Prior to validating the client address, servers MUST NOT send more
   than three times as many bytes as the number of bytes they have
   received.

Also client behavior should be changed.

> Clients MUST pad UDP datagrams that contain only Initial packets to
   at least 1200 bytes.  Once a client has received an acknowledgment
   for a Handshake packet it MAY send smaller datagrams.  
> ...
> If the client has no data to retransmit and does
   not have Handshake keys, it SHOULD send an Initial packet in a UDP
   datagram of at least 1200 bytes.

**Comment by masaori335** [comment]
Status: server side is fixed, but client side is not fixed yet.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
