### ISSUE TITLE
Check received retry token length

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#4906]
At interop session in Tokyo, some endpoints used long retry token which exceeded our limit of packet header length. For workaround, I relaxed the limitation (https://github.com/apache/trafficserver/commit/c83350134c8e4fd3629292e378f7bb365c1cf860). It'd better to check the retry token length when it's received.

**Comment by maskit** [comment]
What do you mean by "check" ? What's expected behavior?

**Comment by masaori335** [comment]
Add some maximum limit for retry token length and compare with it. If the length is too long, it'd be better for client to close the connection. I don't know how long is suitable, but I think we need some limitation.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
