### ISSUE TITLE
Cachekey plugin assumes requestUrl in TSRemapRequestInfo is remapped URL

### ISSUE THREAD

**Issue by dsouza93** [apache/trafficserver#4929]
Seems like https://github.com/apache/trafficserver/issues/4026 was addressed
I am currently working off of master and noticed that the requestUrl within TSRemapRequestInfo inside a DoRemap function is always the pristine URL. I believe that the cachekey plugin currently assumes that this URL is the remapped URL.

**Comment by dsouza93** [comment]
I noticed that the following PR was merged and core remapping after all plugins is intended behavior https://github.com/apache/trafficserver/pull/4531 

I've updated this issue to make changes to the cachekey plugin

**Comment by gtenev** [comment]
@dsouza93, PR #4964 implemented what was agreed on the [dev mailing list](https://mail-archives.apache.org/mod_mbox/trafficserver-dev/201902.mbox/%3c9101332D-8777-41CE-92F4-3C8A39FD211A@apache.org%3e) - email thread "[PROPOSAL] Rewrite url after running all remap plugins", according to the new proposal "[rewrite url before all remap plugins run](https://mail-archives.apache.org/mod_mbox/trafficserver-dev/201902.mbox/%3c9101332D-8777-41CE-92F4-3C8A39FD211A@apache.org%3e)" cachekey's assumption is accurate.

Closing this issue, please reopen if any problems or concerns!
