### ISSUE TITLE
TSHttpEventNameLookup stops working in version 8.0.2

### ISSUE THREAD

**Issue by 1a1a11a** [apache/trafficserver#4978]
I was using the github version and the function works fine, but I have switched to 8.0.2 today and I noticed that TSHttpEventNameLookup stops working when the event is TS_Event (for example, session start, session close), however it still works with VC_EVENT.

**Comment by SolidWallOfCode** [comment]
Internally the event IDs changed between 8.x and 9.x. This isn't a problem for a consistent build, but if you use a plugin built with 9.x in an 8.x instance of TS, you are likely to get this problem. Please verify that you see this problem in 8.0.2 with a plugin built with the 8.0.2 environment / SDK.

TS does not guarantee that major versions of ATS have a binary compatible plugin API, and therefore in general a plugin needs to be built with the same major version of ATS.

**Comment by 1a1a11a** [comment]
Hi Alan, thank you for the reply! Yes, I was using the GitHub version and now I have switched to 8.0.2, but I have also changed the compile tools to 8.0.2 and the plugin is freshly compiled.

**Comment by 1a1a11a** [comment]
Hi Alan, I think you are right about this, it should be caused by version problem. I have my plugin in the folder which contains GitHub version, but I did use the tsxs from installed (v8.0.2) version, am I doing something wrong?

**Comment by bryancall** [comment]
@1a1a11a Are you still having problems with this?  We have multiple tests in our tree and plugins that use this API.  Please reopen if it is still an issue.
