### ISSUE TITLE
About metric: Value of "proxy.process.cache.bytes_used" will only increase  

### ISSUE THREAD

**Issue by hankai17** [apache/trafficserver#4983]
Test in 5.3.2 & 7.x
Command: traffic_ctl metric get proxy.process.cache.bytes_used.
The value only increase，Even if remove(just call cacheProcessor.remove()) some url.

**Comment by oknet** [comment]
Yes, it is.

The cache volume just like ring buffer.
From the 2nd cycle, the new content will overwrite the old content, and the `bytes_used` is always equal to `bytes_total`.

Please check the below code from Cache.cc:

```
int64_t
cache_bytes_used(int volume)
{
  uint64_t used = 0;

  for (int i = 0; i < gnvol; i++) {
    if (!DISK_BAD(gvol[i]->disk) && (volume == -1 || gvol[i]->cache_vol->vol_number == volume)) {
      if (!gvol[i]->header->cycle) {
        used += gvol[i]->header->write_pos - gvol[i]->start;
      } else {
        used += gvol[i]->len - gvol[i]->dirlen() - EVACUATION_SIZE;
      }
    }
  }

  return used;
}
```

**Comment by rebill** [comment]
how can i get really disk usage?

**Comment by SolidWallOfCode** [comment]
The size of the cache. After an initial warm up, it's effectively all used, all the time.
