### ISSUE TITLE
auth_server_session_private and attach_server_session_to_client

### ISSUE THREAD

**Issue by muodov** [apache/trafficserver#4985]
I'm confused about a specific combination of options.

I set both `auth_server_session_private` and `attach_server_session_to_client` to 1.
I can see in network dump that ATS is actually reusing the backend connection for several requests from the same frontend connection, even though the very first request contained an Authorization header.

This is very good actually, because I am using it to support NTLM authentication, which authenticates a (TCP) connection, not a single HTTP request.

But I want to make sure that the backend connection is never reused for the requests from _other_ frontend connections (again, because it would mean that other clients might be erroneously NTLM-authenticated). I tried to confirm my theory looking at the code, but it's difficult. Could someone from the dev team clarify this?

**Comment by SolidWallOfCode** [comment]
Yes, that is correct. When the current user agent uses a different upstream connection, the private one will be marked for the server pool, but the "private" marking will prevent it from actually being added and therefore will never be used by other user agents.
