### ISSUE TITLE
Send two Packets when PTO firing 

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#4993]
>6.2.2.2.  Sending Probe Packets
>When a PTO timer expires, the sender MUST send one ack-eliciting
   packet as a probe.  A sender MAY send up to two ack-eliciting
   packets, to avoid an expensive consecutive PTO expiration due to a
   single packet loss.

Currently , we send nothing in "QUICLossDetector::send_two_packets"

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
