### ISSUE TITLE
Mime scanner happily overwrites const data.

### ISSUE THREAD

**Issue by bgaff** [apache/trafficserver#5022]
I discovered this by mprotecting a region of memory as PROT_READ before passing it to an http request parser and to my surprise I received a fault that something was trying to write to my const memory, all the pointers down are const char * so there really shouldn't be a reason for this otherwise IMO this api should change to acknowledge that the memory can be modified. FWIW, I don't think this represents a serious concern but I can't figure out why that code would be relevant anymore anyway.

https://github.com/apache/trafficserver/blob/master/proxy/hdrs/MIME.cc#L2431-L2438

That's the following block:

```c++
   if (ParseRules::is_ws(*raw_input_c)) {
        char *unfold = const_cast<char *>(raw_input_c - 1);

        *unfold-- = ' ';
        if (ParseRules::is_cr(*unfold)) {
          *unfold = ' ';
        }
        S->m_state = MIME_PARSE_INSIDE; // back inside the field.
      } else {
```

I'm really not sure why this code decides to blow away the \r\n at the end of the field? I suspect this is something that was added LONG LONG ago to conform to some old browser?

More or less I wrote the following code that demonstrates this:
```c++

  // Prevent this mapping from being written to further.
  mprotect(buf2, aligned_len, PROT_READ);

  HTTPHdr* hdr = new HTTPHdr();
  hdr->create(HTTP_TYPE_REQUEST);

  const char* start = buf2;
  HTTPParser parser;
  http_parser_init(&parser);
  hdr->parse_req(&parser,&start, start + len, true, false);
  http_parser_clear(&parser);
```

**Comment by SolidWallOfCode** [comment]
It's handling [line folding](https://tools.ietf.org/html/rfc7230#section-3.2.4). It makes the next line look like a continuation of the current line by replacing the CR-LF with spaces. E.g.
```
Field: var1=value1, var2=value2,
  var3=value3
```
becomes
```
Field: var1=value1,var2=value2,   var3=value3
```
I've been in the midst of rewriting that logic, if you want to review some PRs....

**Comment by bgaff** [comment]
Hello amc! :wave:

Learn something new everyday, I hadn't heard of line folding before, after reading the RFC:

> Historically, HTTP header field values could be extended over
>    multiple lines by preceding each extra line with at least one space
>    or horizontal tab (obs-fold).  This specification deprecates such
>    line folding except within the message/http media type
>    (Section 8.3.1).  A sender MUST NOT generate a message that includes
>    line folding (i.e., that has any field-value that contains a match to
>    the obs-fold rule) unless the message is intended for packaging
>    within the message/http media type.
> 
>    A server that receives an obs-fold in a request message that is not
>    within a message/http container MUST either reject the message by
>    sending a 400 (Bad Request), preferably with a representation
>    explaining that obsolete line folding is unacceptable, or replace
>    each received obs-fold with one or more SP octets prior to
>    interpreting the field value or forwarding the message downstream.

It sounds like this is something that can be dropped entirely though?

**Comment by bgaff** [comment]
or perhaps we can correct the line folding after attaching the header field? But if all this code is getting re-written I'll just close this bug :)

**Comment by SolidWallOfCode** [comment]
You can't really fix it after attaching the field value, as the presumption is the value is a contiguous string. It would be possible by copying the effective field value, in to say the header heap. If I were going to change something, though, I'd have ATS return a 400 in this case, as is recommended by the specification.

**Comment by bgaff** [comment]
So do you think we should do that? Should I reopen?

**Comment by SolidWallOfCode** [comment]
Let me work on this other related stuff first. I am happy that  you've volunteered to do all the code reviews for it. Thanks! You're the best.
