### ISSUE TITLE
How to use basic authentication (username:password) ?

### ISSUE THREAD

**Issue by YoyoKarimov** [apache/trafficserver#5028]
How can I use basic authentication for forward proxy?

**Comment by rob05c** [comment]
ATS doesn't currently have this feature. You could write a plugin to do it.

But also, Client Certificates are a better way to do this, if you can. ATS does fully support Client Certificates / TLS Mutual Auth.
See 
https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/
https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/files/sni.yaml.en.html
https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/files/records.config.en.html#proxy-config-ssl-ca-cert-filename
https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/files/records.config.en.html#proxy-config-ssl-client-certification-level
