### ISSUE TITLE
Hung up while MIOBuffer is full

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5055]
Because the throttle is limited by `MIOBuffer` 

https://github.com/apache/trafficserver/blob/c811aea9e0484433fbdd63e0fa6b9fbab87085eb/iocore/eventsystem/P_IOBuffer.h#L1000-L1007

Large `proxy.config.cache.target_fragment_size`  will delay the cache consuming. And the writer will always wait for consuming data.  And it is a deadlock.

**Comment by scw00** [comment]
`proxy.config.cache.target_fragment_size` should not large than MAX_FRAG_SIZE. But if  it does it should give an assertion or Warning because the Cache will not write this Data.

**Comment by SolidWallOfCode** [comment]
Put in a `static_assert`.
