### ISSUE TITLE
Cache corruption in #4874

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5061]
#4874 This pr changed the marshal buffer . And it need to cleanup the old cache entirely .

**Comment by SolidWallOfCode** [comment]
If this really changes the size of the cached header, then we'll need to bump the cache version # and put in logic to convert current versions to the updated version.

**Comment by scw00** [comment]
#5063 Is the alternate changes. And I prefer to bumping the cache version or another better changes that can avoid cache cleaning.

The cache is leaking on 3 scenarios : 
 - Read side. Because the CacheHTTPInfoVector is a part of  Doc's buffer. it should be free when doc's buffer freed (If this fragment didn't put to ram cache).
 - Write side. While we are trying to update a vector, the `CacheHTTPInfoVector` doesn't  free the `frag_offsets`. Because `CacheHTTPInfoVector::insert` doesn't check overwriting of the alternate.
 - Ram side. The `frag_table` should be freed along with the buffer free.

See #5063

**Comment by scw00** [comment]
Close via #5075
