### ISSUE TITLE
8.x logging.yaml rolling enabled options dont work as expected

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#5080]
From the docs its expected that you should be able to use the previous numeric roll options, 0/1/2/etc, or be able to use the old lua version of log.roll.none, log.roll.both, etc. In testing it seems like none of those work and the only way I could get the roll option to work was to specify like 'both', 'size'

**Comment by zwoop** [comment]
Looks like this was resolved? Please remember to add e.g "fixes #5080" to the PR commit message that fixes an issue.
