### ISSUE TITLE
Crash in certificate selection when running with openssl-1.1.1b

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#5084]
1.1.1b came out yesterday and fixes a problem with later TLS1.3 messages looking like renegotiation requests.

But when I tried running Traffic Server with it, it crashed almost immediately after taking on traffic.  With the fix they made in 1.1.1a, they indicated that they thought the new hello_callback would be a better place to make the certificate decision.  So at this point, that is probably what we should do to ensure that future moves through openssl are stable.

Or maybe it is something else entirely.  Wanted to share an early heads up since I figured that many of us would be trying to move forward with 1.1.1b

```
(gdb) bt
#0  0x00002b12fc839315 in asn1_do_lock () from /opt/oath/openssl/1.1.1/lib/libcrypto.so.1.1
#1  0x00002b12fc836658 in asn1_item_embed_free () from /opt/oath/openssl/1.1.1/lib/libcrypto.so.1.1
#2  0x00002b12fc836785 in ASN1_item_free () from /opt/oath/openssl/1.1.1/lib/libcrypto.so.1.1
#3  0x00002b12fc995383 in OPENSSL_sk_pop_free () from /opt/oath/openssl/1.1.1/lib/libcrypto.so.1.1
#4  0x00002b12fc52a5d1 in ssl_cert_clear_certs () from /opt/oath/openssl/1.1.1/lib/libssl.so.1.1
#5  0x00002b12fc52a655 in ssl_cert_free () from /opt/oath/openssl/1.1.1/lib/libssl.so.1.1
#6  0x00002b12fc536653 in SSL_set_SSL_CTX () from /opt/oath/openssl/1.1.1/lib/libssl.so.1.1
#7  0x00000000007771da in set_context_cert(ssl_st*) () at SSLUtils.cc:376
#8  0x0000000000777557 in ssl_cert_callback (ssl=0x2b1439056800) at SSLUtils.cc:496
#9  0x00002b12fc55ac1d in tls_post_process_client_hello () from /opt/oath/openssl/1.1.1/lib/libssl.so.1.1
#10 0x00002b12fc54a7cb in state_machine.part.5 () from /opt/oath/openssl/1.1.1/lib/libssl.so.1.1
#11 0x00002b12fc535e44 in SSL_do_handshake () from /opt/oath/openssl/1.1.1/lib/libssl.so.1.1
#12 0x00000000007782ed in SSLAccept (ssl=0x2b1439056800) at SSLUtils.cc:2478
#13 0x0000000000763597 in SSLNetVConnection::sslServerHandShakeEvent (this=this@entry=0x2b1443d8ead0, err=@0x2b1303b13350: -18795776) at SSLNetVConnection.cc:1201
#14 0x0000000000766bd9 in SSLNetVConnection::sslStartHandShake(int, int&) () at SSLNetVConnection.cc:1030
#15 0x0000000000768112 in SSLNetVConnection::net_read_io(NetHandler*, EThread*) () at SSLNetVConnection.cc:502
#16 0x000000000077d049 in NetHandler::waitForActivity(long) () at UnixNet.cc:497
#17 0x00000000007c36c3 in EThread::execute_regular (this=0x2b1301054c00) at UnixEThread.cc:275
#18 0x00000000007c1d72 in spawn_thread_internal (a=0x2b12fef91080) at Thread.cc:85
#19 0x00002b12fd175dc5 in start_thread () from /lib64/libpthread.so.0
#20 0x00002b12fdea476d in clone () from /lib64/libc.so.6
```

**Comment by shinrich** [comment]
I have a fix that moves the cert selection from the cert callback to the client hello callback.  However, when I run that code against openssl-1.1.1b I get frequent memory-based errors (looks like double frees).  If I move back to openssl-1.1.1a, no memory error.  It is possible that openssl-1.1.1b has memory errors or that openssl-1.1.1b changes are exercising latent memory errors in Traffic Server

**Comment by shinrich** [comment]
Turns out that changing the cert selection did not fix the issue.  Thanks to ASAN I tracked the issue down to one of our plugins and how they are using BIO's.  I think it was affected by commit 492f70645ca912d82af02b9bc06e9472bf0730a0 in openssl.  Still staring at things to determine whether it is a latent bug in our plugin or something to bring up with the openssl folks.

I'll go ahead and put up a PR to move the certificate selection code at some point.  I think that will be better in the long run.

**Comment by shinrich** [comment]
Filed issue with openssl https://github.com/openssl/openssl/issues/8375

**Comment by shinrich** [comment]
The fix will be in openssl-1.1.1c.  In the meantime, we adjusted a library used by one of our plugins to avoid the problem code. Specifically, the library originally did this as part of the logic to leverage the base64 encode/decode logic in the BIOS.
```
        BUF_MEM *bufferPtr;
	BIO_get_mem_ptr(bio, &bufferPtr);		
        char *data = NULL;	
	BIO_set_close(bio, BIO_NOCLOSE);		l
        ong data_size = BIO_get_mem_data(bio, &data);
	BIO_free_all(bio);		
        *b64text = (char*)calloc(sizeof(char), data_size + 1);
			
	int size = (length+2)/3*4;	
	*b64text = (char*)calloc(sizeof(char), size + 1);
        strncpy(*b64text, (*bufferPtr).data, size);		
        strncpy(*b64text, data, data_size);
	BUF_MEM_free(bufferPtr);
```

We changed it to the following
```
	char *data = NULL;	
	BIO_set_close(bio, BIO_NOCLOSE);		
        long data_size = BIO_get_mem_data(bio, &data);
	BIO_free_all(bio);		
        *b64text = (char*)calloc(sizeof(char), data_size + 1);
        strncpy(*b64text, data, data_size);
	BUF_MEM_free(bufferPtr);			
        BIO_free_all(bio);
```
So we didn't have to make an openssl-1.1.1b+ in the interim.

**Comment by randall** [comment]
thanks @shinrich ! It's good to hear that core is not affected.

**Comment by masaori335** [comment]
FWIW, openssl-1.1.1c is released.

**Comment by shinrich** [comment]
Closing issues now that openssl-1.1.1c is out.
