### ISSUE TITLE
Remove cache v23 support

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5092]
It seems we have been supporting cache v23 for a really long time since ATS2.0. And I don't believe that there is someone still use such old version.  So do we still need to support this version ?

**Comment by zwoop** [comment]
Please make a PR. Also, can we get rid of proxy.config.cache.http.compatibility.4-2-0-fixup at the same time ?

**Comment by zwoop** [comment]
https://github.com/apache/trafficserver/pull/5386
