### ISSUE TITLE
8.1.x - body_factory directory problem

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#5102]
If you use the default value and dont set a templates dir then it starts up fine

However if you change it to be the actual default:
CONFIG proxy.config.body_factory.template_sets_dir STRING etc/trafficserver/body_factory

Then you get an error during startup:
[Mar  1 18:28:26.624] {0x2b166b3fda40} WARNING: <HttpBodyFactory.cc:302 (reconfigure)> Unable to access() directory '/opt/trafficserver/etc/trafficserver/etc/trafficserver/body_factory': 2, No such file or directory
[Mar  1 18:28:26.624] {0x2b166b3fda40} WARNING: <HttpBodyFactory.cc:303 (reconfigure)>  Please set 'proxy.config.body_factory.template_sets_dir'
[Mar  1 18:28:26.624] {0x2b166b3fda40} WARNING: <HttpBodyFactory.cc:632 (load_sets_from_directory)> can't open response template directory '/opt/trafficserver/etc/trafficserver/etc/trafficserver/body_factory' (No such file or directory)
[Mar  1 18:28:26.624] {0x2b166b3fda40} WARNING: <HttpBodyFactory.cc:633 (load_sets_from_directory)> no response templates --- using default error pages

So it is not using set values relative to the PREFIX value but instead it is using set values relative to the DEFAULT value

**Comment by shinrich** [comment]
Seeing this in 9.0.x as well.  I had to set it to body_factory.   If it is set to assume that the install directory is the relative path root, the body factory fails to load and all error messages return.  From the client's perspective the connection just closes with no header or body.  But the logging occurs as expected.

In production, we would see clients retry the same failed request 1000's of times.  On a working system, we didn't see this repetition, because the client actually got a reasonable 404 response.

**Comment by zwoop** [comment]
Did this not get resolved ?

**Comment by shinrich** [comment]
Not to my knowledge.  I have two PR's up to address it in different ways.

https://github.com/apache/trafficserver/pull/6203

https://github.com/apache/trafficserver/pull/6232

But maybe someone else's PR got pulled in.

**Comment by ezelkow1** [comment]
tested it on a master build here and Im still seeing it:

set:
CONFIG proxy.config.body_factory.template_sets_dir STRING etc/trafficserver/body_factory

output:
[May 11 14:39:23.771] traffic_server WARNING: Unable to access() directory '/opt/trafficserver/etc/trafficserver/etc/trafficserver/body_factory': 2, No such file or directory
[May 11 14:39:23.771] traffic_server WARNING:  Please set 'proxy.config.body_factory.template_sets_dir'
[May 11 14:39:23.771] traffic_server WARNING: can't open response template directory '/opt/trafficserver/etc/trafficserver/etc/trafficserver/body_factory' (No such file or directory)
[May 11 14:39:23.771] traffic_server WARNING: no response templates --- using default error pages

**Comment by ezelkow1** [comment]
I havent tested it but my preference would be #6203 as well. Gets it back to how it used to act

**Comment by shinrich** [comment]
#6203 merged to master.  Needs to be cherry-picked back to appropriate branches.

**Comment by ezelkow1** [comment]
Fixed in 6203
