### ISSUE TITLE
hash collision of key 0x39393939... in the same segment and the same bucket

### ISSUE THREAD

**Issue by rienzi2012** [apache/trafficserver#5175]
recently, hash collision of key appears in our online circumstance and the collisions focus on one segment and one bucket. the result of collision looks like this picuture:
![图1](https://user-images.githubusercontent.com/7855555/54471329-22063280-47f2-11e9-8cf3-4c875bc5a236.png)

  after troubleshooting, we find that the collision is from the same value 0x39393939. this bug appears in all of our servers and it exists in the code for a long time. at last we find the reason of this critical bug. that is, in CacheVC::openReadStartEarliest, when dir_probe returns false, the code runs and earliest_key will be assigned to zero_key. as the code runs, agg_copy will be called and prev_CacheKey will be called in agg_copy. then because of earliest_key is zero, the result of prev_CacheKey is 0x39393939... . this evil number is assigned to doc->key and flushed to disk. at last while another dir_insert is called and 0x39393939... is passed to this function, hash collision appears.

  think about this situation: one url constrcts two alternate objects, one has a Very header in its response and one has not, for example. when one of these two alternates is wiped out by the write cursor of disk in the next phase and becomes invalid, the function dir_probe will return false in CacheVC::openReadStartEarliest from a new request. then the key 0x393939... occurs. the number will be stored in the key field of a new Doc, the new Doc is created for index the other valid alternate left behind. as the object can not be found in disk, the request will be send to origin server. after response is received, the new object must be indexed. then it is our 0x39393939... appearance, the value in the key field of the top Doc is used to index this new object. and dir_insert is called for 0x39393939... .a larger number of times of this stituation lead to one result that is showed by the picture pasted previously.

  the scene we described just now could be reproduced in my development circumstance. it is showed as below. ignore the hack code for log print:
![图2](https://user-images.githubusercontent.com/7855555/54471359-b96b8580-47f2-11e9-93d1-bf3c4376995b.png)

  zero_key can be assigned to vc->earliest_key in evacuation also. we find a fix for this bug: substitute prev_CacheKey in agg_copy for rand_CacheKey while vc->earliest_key equals to zero_key. we could copy the code of the do while loop for rand_CacheKey in Cache::open_write. we are investigating to understand if this fix is appropriate and it seems to work right until now.

**Comment by oknet** [comment]
@SolidWallOfCode @bryancall @zwoop
