### ISSUE TITLE
Sampling more streams to measure error rate correctly

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#5195]
"Closing a H2 connection with high stream error rate" is added by 693b3cb465d2867379a80e882899aca8ea98f389.
The close event could be triggered when the first stream got error regardless value of `proxy.config.http2.stream_error_rate_threshold`. Because the error rate bacomes `1`. We should wait for more streams to measure stream error rate correctly.

https://github.com/apache/trafficserver/blob/9b73fc965e209b7e846aa8699430cbeaf9ecfcad/proxy/http2/Http2ClientSession.cc#L383-L384

https://github.com/apache/trafficserver/blob/9b73fc965e209b7e846aa8699430cbeaf9ecfcad/proxy/http2/Http2ConnectionState.h#L224-L233

**Comment by maskit** [comment]
> We should wait for more streams to measure stream error rate correctly.

Why? If a client sent 1 request and it failed, the error rate is obviously 100%.

A error rate won't be less than 10% until a client makes 10 requests if a stream error happened on the first stream, and it would be 20 if the threshold was 5%.

Do we want more requests from a client that cannot do things correctly on the first stream?

**Comment by masaori335** [comment]
Closed by #6525
