### ISSUE TITLE
CacheControl: never-cache and ttl-in-cache may be all setted during a HttpRequest

### ISSUE THREAD

**Issue by garfieldonly** [apache/trafficserver#5200]
When a http request hit  two rules in cache.config, one is never-cache,the other on is ttl-in-cache,we should set the never-cache to false,Just like the codes below(CacheControlRecord::UpdateMatch):
```
 case CC_NEVER_CACHE:
if (this->CheckForMatch(h_rdata, result->never_line) == true) {
      result->never_cache = true;
      result->never_line  = this->line_num;
      match               = true;
    }
    break;
```
```
 case CC_TTL_IN_CACHE:
    if (this->CheckForMatch(h_rdata, result->ttl_line) == true) {
      result->ttl_in_cache = time_arg;
      result->ttl_line     = this->line_num;
      // ttl-in-cache overrides never-cache
      result->never_cache = false;
      result->never_line  = this->line_num;
      match               = true;
    }
    break;
```
However ,this may not be work. According to the order of function call by the code below:
```
template <class Data, class MatchResult>
void
ControlMatcher<Data, MatchResult>::Match(RequestData *rdata, MatchResult *result)
{
  if (hostMatch != nullptr) {
    hostMatch->Match(rdata, result);
  }
  if (reMatch != nullptr) {
    reMatch->Match(rdata, result);
  }
  if (urlMatch != nullptr) {
    urlMatch->Match(rdata, result);
  }
  if (ipMatch != nullptr) {
    ipMatch->Match(rdata->get_ip(), rdata, result);
  }
  if (hrMatch != nullptr) {
    hrMatch->Match(rdata, result);
  }
}
```

For example，we have two rules in cache.config,one is never-cache,the other one is ttl-in-cache
Now we have two situations:
  1 :     First rule ttl-in-cache  ,second rule never-cache .
          obviously, ttl-in-cache true,never-cache false
  2:   First rule never-cache, second rule ttl-in-cache.
        If the rule never-cache is set before the rule ttl-in-cache, never-cache will be override by ttl-in-cache
        If the rule nerver-cache is set after the rule ttl-in-cache, ttl-in-cache will be true,and never-cache will also be set to true
        
I have write something about CacheControl below in Chinese:
https://github.com/garfieldonly/ats_code_analysis/blob/master/CacheControl

**Comment by oknet** [comment]
Could please show your cache.config for these two situations ?

**Comment by garfieldonly** [comment]
S1:
```
cache.config 
dest_domain=www.google.com scheme=http action=never-cache
url_regex=google.* scheme=http ttl-in-cache=11
```
when a request hit both rules, ttl-in-cache=11, never-cache= false

S2:
```
cache.config 
url_regex=google.* scheme=http action=never-cache
dest_domain=www.google.com scheme=http ttl-in-cache=11
```
when a request hit both rules, ttl-in-cache=11, never-cache= true
