### ISSUE TITLE
proxy.config.ssl.server.TLSv1_3.cipher_suites don't really work

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#5244]
what's the point of that config setting when it does nothing?

---------------------------

Trafficserver 8.0.1: 

CONFIG proxy.config.ssl.server.honor_cipher_order INT 1
CONFIG proxy.config.ssl.server.TLSv1_3.cipher_suites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256:TLS_CHACHA20_POLY1305_SHA256

Firefox (show page informations): TLS_AES_256_GCM_SHA384, TLS1.3

---------------------------

httpd:

SSLHonorCipherOrder On
SSLCipherSuite TLSv1.3 TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256:TLS_CHACHA20_POLY1305_SHA256

Firefox (show page informations): TLS_AES_128_GCM_SHA256, TLS1.3

**Comment by masaori335** [comment]
I tried your settings with ats-8.0.1 and firefox-66.0.2, but it looks like the config is working correctly. Also, I checked ServerHello TLS msg via Wireshark, ATS looks honer the settings.
Could you try again?

**Comment by thelounge-zz** [comment]
i restarted ATS multiple times and cleared cache

**Comment by masaori335** [comment]
Restarting ATS should load the config. Do you have any error message like "invalid tls server cipher suites in records.config" ?

https://github.com/apache/trafficserver/blob/3b95fffa07c212e35218c024f33ed3321758c8b5/iocore/net/SSLUtils.cc#L1850

**Comment by thelounge-zz** [comment]
no, only WARNING: Unrecognized configuration value 'proxy.config.ssl.TLSv1_3' which is clear because 8.0.1 don't have that setting but sadly everything after 8.0.1 is completly ususable (https://github.com/apache/trafficserver/issues/4921#issuecomment-473451304)

fact is i have the same AES-256 ciphers as without the confgi setting at all on port 8443 while port 443 with the httpd-orgini directly perfeers the desired AES-128 one as both did before TLS 1.3 with the old cipher settings

[root@testserver:/var/log/trafficserver]$ cat diags.log
[Apr  9 03:17:03.220] {0x7f315c9ae6c0} STATUS: opened /var/log/trafficserver/diags.log
[Apr  9 03:17:03.220] {0x7f315c9ae6c0} NOTE: updated diags config
[Apr  9 03:17:03.252] {0x7f315c9ae6c0} NOTE: ip_allow.config updated, reloading
[Apr  9 03:17:03.257] {0x7f315c9ae6c0} NOTE: logging initialized[3], logging_mode = 1
[Apr  9 03:17:03.257] {0x7f315c9ae6c0} NOTE: loading plugin '/usr/lib64/trafficserver/plugins/compress.so'
[Apr  9 03:17:03.260] {0x7f315c9ae6c0} NOTE: loading plugin '/usr/lib64/trafficserver/plugins/header_rewrite.so'
[Apr  9 03:17:03.265] {0x7f315c9ae6c0} NOTE: loading /etc/trafficserver/ssl_server_name.yaml
[Apr  9 03:17:03.265] {0x7f315c9ae6c0} WARNING: /etc/trafficserver/ssl_server_name.yaml is empty
[Apr  9 03:17:03.265] {0x7f315c9ae6c0} NOTE: ssl_server_name.yaml done reloading!
[Apr  9 03:17:03.265] {0x7f315c9ae6c0} NOTE: loading SSL certificate configuration from /etc/trafficserver/ssl_multicert.config
[Apr  9 03:17:03.343] {0x7f315c9ae6c0} NOTE: ssl_multicert.config done reloading!
[Apr  9 03:17:03.372] {0x7f314ee23700} NOTE: recovery clearing offsets of Vol /var/cache/trafficserver/cache.db 16384:4094 : [2277376, 10665984] sync_serial 43 next 44
[Apr  9 03:17:03.373] {0x7f315c9ae6c0} WARNING: Unrecognized configuration value 'proxy.config.ssl.TLSv1_3'
[Apr  9 03:17:03.375] {0x7f3156ce1700} NOTE: cache enabled
[Apr  9 03:17:03.377] {0x7f315c9ae6c0} NOTE: traffic server running
[root@testserver:/var/log/trafficserver]$

**Comment by thelounge-zz** [comment]
nevermind

CONFIG proxy.config.ssl.server.TLSv1_3.cipher_suites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256:TLS_CHACHA20_POLY1305_SHA256

versus

CONFIG proxy.config.ssl.server.TLSv1_3.cipher_suites STRING TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256:TLS_CHACHA20_POLY1305_SHA256

*that* is something ATS *really* could warn when the third column is not a valid type!

**Comment by mlibbey** [comment]
It warns for me.
Apr 27 08:37:15 s_sys@myhostname traffic_manager[17394]: {0x7fa412d08780} WARNING: Could not parse line at '/opt/bazinga/etc/trafficserver/records.config:169' -- skipping line: 'CONFIG proxy.config.ssl.server.cipher_suite ECDHE-ECDSA-AES1     28-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA2     56:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA:AES128-SHA256:AES256-SHA256'
