### ISSUE TITLE
 ☂ Proper "top level" name space for all yaml

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5245]
- [x] YAML: Cleanup logging.yaml
- [x] YAML: Cleanup sni.yaml

We should have a consistent top-level naming scheme, for all YAML formats. For logging, we would want to add something like:

```
logging:
   ....
```

We should make sure all existing, and new YAML formats have this.

**Comment by zwoop** [comment]
Blocks #5457

**Comment by zwoop** [comment]
IMO, we should just make the top-level tag the same as the config file name. I'm ok with renaming config files if that's a problem :).

**Comment by jrushford** [comment]
+1

**Comment by shinrich** [comment]
Sounds reasonable ssl_server_name for the top level tag sounds good.

**Comment by randall** [comment]
These 2 files updated.

**Comment by zwoop** [comment]
Awesome!
