### ISSUE TITLE
traffic_ctl host command does not set the reason tag is broken.

### ISSUE THREAD

**Issue by jrushford** [apache/trafficserver#5256]
It looks like the recent refactor of traffic_ctl, commit e137c7d394, has broken the traffic_ctl host subcommand.
when marking a host down using the optional reason tag, the reason string is always coming back empty from 'arguments.get("reason").value()' and the wrong host status reason stat is getting updated ie, the manual stat as it is the default.

# get status for p1.foo.com and all reasons have are up ie, 1
traffic_ctl host status p1.foo.com
proxy.process.host_status.p1.foo.com_active 1
proxy.process.host_status.p1.foo.com_local 1
proxy.process.host_status.p1.foo.com_manual 1
proxy.process.host_status.p1.foo.com_self_detect 1

# now mark down p1.foo.com for the 'active' healthcheck reason.
traffic_ctl host down --reason active p1.foo.com

#  Now check the status and the wrong reason stat shows down ie, manual.  'active' should be 0.
traffic_ctl host status p1.foo.com
proxy.process.host_status.p1.foo.com_active 1
proxy.process.host_status.p1.foo.com_local 1
proxy.process.host_status.p1.foo.com_manual 0
proxy.process.host_status.p1.foo.com_self_detect 1

**Comment by chitianhao** [comment]
Looks like I know what the issue is. I'll raise a PR fixing it.

**Comment by vmamidi** [comment]
thanks @chitianhao

**Comment by jrushford** [comment]
fixed by #5264
