### ISSUE TITLE
Revisit client_session_file/client_keylog_file when origin server side QUIC connection is supported

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#5263]
There're features and settings to support session resumption (`proxy.config.quic.client.session_file`) and session keylog (`proxy.config.quic.client.keylog_file`) for ATS QUIC client implementations (traffic_quic cmd).
This might also useful when we support origin server side QUIC connection. But we need to revisit these to support multiple sessions which traffic_quic cmd doesn't need.

The concern was raised on https://github.com/apache/trafficserver/pull/5231#discussion_r273957129

**Comment by maskit** [comment]
The setting for keylog was replaced with `proxy.config.ssl.keylog_file` by https://github.com/apache/trafficserver/pull/8337, and it's available for all connections that uses TLS.
