### ISSUE TITLE
MD5 check failure while 206 partial content download 

### ISSUE THREAD

**Issue by JHsorth** [apache/trafficserver#5288]
**ATS Version:** 4.2.3
**Description:**
(1) Single thread complete download the specify url , the MD5 is correct
(2) 206 partial content download the specify url, the range content MD5 is error 

> curl -x127.0.0.1:80 -so /tmp/part1 --range 488205666-732308498  http://a.foo.com/bigfile

**Debug Log:** 
![image](https://user-images.githubusercontent.com/26059949/56350559-9d963d80-61fd-11e9-8166-3fd42e741628.png)

why the cache_seek is a negative number ? 
Has anyone encountered a similar situation or explained it ? 
Thanks a lot .

**Comment by scw00** [comment]
Sorry, we didn't support 4.2.x anymore. 

Please feel free to reopen it if this is in our supported version.
