### ISSUE TITLE
Weird problem with Android emulator

### ISSUE THREAD

**Issue by swood** [apache/trafficserver#5332]
Hi everyone.

I'm trying to configure ATS as a squid (because squid doesn't support WebSocket protocol). However, I faced a problem when my desktop browser can work via ATS but doesn't work with the android emulator.
I ran ATS with debugging and saw log below:

>+++++++++ Proxy's Request +++++++++
>-- State Machine Id: 43
CONNECT 31.13.92.36:443 HTTP/1.1
Via: http/1.1 proxy[c2f3d559-6d34-47c8-a90f-4c5efa3dd1d3] (ApacheTrafficServer/9.0.0)
Host: 31.13.92.36:443

>[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpTransact.cc:1953 (LookupSkipOpenServer)> (http_trans) Next action next; HttpTransact::HandleResponse
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpSM.cc:7161 (call_transact_and_set_next_state)> (http) [43] State Transition: SM_ACTION_API_CACHE_LOOKUP_COMPLETE -> SM_ACTION_ORIGIN_SERVER_RAW_OPEN
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpSM.cc:4717 (do_http_server_open)> (http_track) entered inside do_http_server_open ][ipv4]
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpSM.cc:4748 (do_http_server_open)> (http) [43] open connection to 31.13.92.36: 31.13.92.36:443
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpSM.cc:4760 (do_http_server_open)> (http_seq) [HttpSM::do_http_server_open] Sending request to server
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpSM.cc:5066 (do_http_server_open)> (http) calling netProcessor.connect_re
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpSM.cc:2564 (main_handler)> (http) [43] [HttpSM::main_handler, NET_EVENT_OPEN/TS_EVENT_NET_CONNECT]
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpSM.cc:1086 (state_raw_http_server_open)> (http) [43] [&HttpSM::state_raw_http_server_open, NET_EVENT_OPEN/TS_EVENT_NET_CONNECT]
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpTransact.cc:3106 (OriginServerRawOpen)> (http_trans) [43] [HttpTransact::OriginServerRawOpen]
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpTransactHeaders.cc:638 (generate_and_set_squid_codes)> (http_trans) [Squid code generation] Hit/Miss: 1, Log: 3, Hier: 2
[Apr 23 17:44:54.822] [ET_NET 2] DEBUG: <HttpTransactHeaders.cc:1214 (add_server_header_to_response)> (http_trans) Adding Server: ATS/9.0.0
>+++++++++ Proxy's Response 2 +++++++++
>-- State Machine Id: 43
HTTP/1.1 200 OK
Date: Tue, 23 Apr 2019 17:44:54 GMT
Connection: keep-alive
Server: ATS/9.0.0

>[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <HttpTransact.cc:3127 (OriginServerRawOpen)> (http_trans) [43] [OriginServerRawOpen] connection alive. next action is ssl_tunnel
[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <HttpSM.cc:7161 (call_transact_and_set_next_state)> (http) [43] State Transition: SM_ACTION_ORIGIN_SERVER_RAW_OPEN -> SM_ACTION_SSL_TUNNEL
[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <HttpTunnel.cc:595 (add_producer)> (http_tunnel) [43] adding producer 'http server - tunnel'
[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <HttpTunnel.cc:650 (add_consumer)> (http_tunnel) [43] adding consumer 'user agent - tunnel'
[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <HttpTunnel.cc:595 (add_producer)> (http_tunnel) [43] adding producer 'user agent - tunnel'
[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <HttpTunnel.cc:650 (add_consumer)> (http_tunnel) [43] adding consumer 'http server - tunnel'
[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <HttpTunnel.cc:697 (tunnel_run)> (http_tunnel) tunnel_run started, p_arg is NULL
[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <Http1ClientSession.cc:214 (do_io_write)> (http_cs) tcp_init_cwnd_set 1
[Apr 23 17:44:54.823] [ET_NET 2] DEBUG: <HttpTunnel.cc:1288 (consumer_handler)> (http_tunnel) [43] consumer_handler [user agent - tunnel VC_EVENT_WRITE_READY/TS_EVENT_VCONN_WRITE_READY]
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <ProtocolProbeSessionAccept.cc:179 (mainEvent)> (http) probe needs data, read..
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpSessionAccept.cc:49 (accept)> (http_seq) [HttpSessionAccept:mainEvent 0x152fbc018d30] accepted connection from 10.10.126.115:16580 transport type = 1
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <Http1ClientSession.cc:184 (new_connection)> (http_cs) [44] session born, netvc 0x152fbc018d30
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <Http1ClientSession.cc:214 (do_io_write)> (http_cs) tcp_init_cwnd_set 0
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <Http1ClientSession.cc:451 (release)> (http_cs) [44] data already in buffer, starting new transaction
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <ProxyClientTransaction.cc:44 (new_transaction)> (http_txn) [44] Starting transaction 1 using sm [44]
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpSM.cc:2564 (main_handler)> (http) [44] [HttpSM::main_handler, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpSM.cc:607 (state_read_client_request_header)> (http) [44] [&HttpSM::state_read_client_request_header, VC_EVENT_READ_READY/TS_EVENT_VCONN_READ_READY]
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpSM.cc:754 (state_read_client_request_header)> (http) [44] done parsing client request header
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpTransact.cc:974 (ModifyRequest)> (http_trans) [44] START HttpTransact::ModifyRequest
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpTransact.cc:1048 (ModifyRequest)> (http_trans) [44] END HttpTransact::ModifyRequest
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpTransact.cc:1049 (ModifyRequest)> (http_trans) [44] Checking if transaction wants to upgrade
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpTransact.cc:1057 (ModifyRequest)> (http_trans) Next action SM_ACTION_API_READ_REQUEST_HDR; HttpTransact::StartRemapRequest
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpSM.cc:7161 (call_transact_and_set_next_state)> (http) [44] State Transition: SM_ACTION_UNDEFINED -> SM_ACTION_API_READ_REQUEST_HDR
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpTransact.cc:600 (StartRemapRequest)> (http_trans) [44] START HttpTransact::StartRemapRequest
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HttpTransact.cc:620 (StartRemapRequest)> (http_trans) [44] Before Remapping:
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) HTTP_HEADER 0x152fdc2cb888: [T: 3, L:   48, OBJFLAGS: 0]
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HTTP.cc:570 (http_hdr_describe)> (http) [TYPE: REQ, V: 10001, URL: 0x152fdc2cbb08, METHOD: "CONNECT", METHOD_LEN: 7, FIELDS: 0x152fdc2cb8b8]
[Apr 23 17:44:55.068] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) URL 0x152fdc2cbb08: [T: 2, L:  112, OBJFLAGS: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1594 (url_describe)> (http) [URLTYPE: 0, SWKSIDX: -1,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1596 (url_describe)> (http) 	SCHEME: "", SCHEME_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1597 (url_describe)> (http) 	USER: "", USER_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1599 (url_describe)> (http) 	PASSWORD: "", PASSWORD_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1600 (url_describe)> (http) 	HOST: "31.13.92.36", HOST_LEN: 11,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1602 (url_describe)> (http) 	PORT: "443", PORT_LEN: 3, PORT_NUM: 443
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1603 (url_describe)> (http) 	PATH: "", PATH_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1605 (url_describe)> (http) 	PARAMS: "", PARAMS_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1607 (url_describe)> (http) 	QUERY: "", QUERY_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1609 (url_describe)> (http) 	FRAGMENT: "", FRAGMENT_LEN: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) MIME_HEADER 0x152fdc2cb8b8: [T: 4, L:  592, OBJFLAGS: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <MIME.cc:2604 (mime_hdr_describe)> (http)
	[PBITS: 0x0000000000000000, SLACC: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, HEADBLK: 0x152fdc2cb8f8, TAILBLK: 0x152fdc2cb8f8]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <MIME.cc:2609 (mime_hdr_describe)> (http) 	[CBITS: 0x00000000, T_MAXAGE: 0, T_SMAXAGE: 0, T_MAXSTALE: 0, T_MINFRESH: 0, PNO$: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) FIELD_BLOCK 0x152fdc2cb8f8: [T: 5, L:  528, OBJFLAGS: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <MIME.cc:2625 (mime_field_block_describe)> (http) [FREETOP: 0, NEXTBLK: (nil)]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpTransact.cc:631 (StartRemapRequest)> (http_trans) [44] END HttpTransact::StartRemapRequest
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpTransact.cc:632 (StartRemapRequest)> (http_trans) Next action SM_ACTION_API_PRE_REMAP; HttpTransact::PerformRemap
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpSM.cc:7161 (call_transact_and_set_next_state)> (http) [44] State Transition: SM_ACTION_API_READ_REQUEST_HDR -> SM_ACTION_API_PRE_REMAP
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpTransact.cc:638 (PerformRemap)> (http_trans) [44] Inside PerformRemap
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpTransact.cc:639 (PerformRemap)> (http_trans) Next action SM_ACTION_REMAP_REQUEST; HttpTransact::EndRemapRequest
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpSM.cc:7161 (call_transact_and_set_next_state)> (http) [44] State Transition: SM_ACTION_API_PRE_REMAP -> SM_ACTION_REMAP_REQUEST
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpSM.cc:3968 (do_remap_request)> (http_seq) [HttpSM::do_remap_request] Remapping request
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpTransact.cc:645 (EndRemapRequest)> (http_trans) [44] START HttpTransact::EndRemapRequest
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpTransact.cc:651 (EndRemapRequest)> (http_trans) [44] EndRemapRequest host is 31.13.92.36
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HttpTransact.cc:789 (EndRemapRequest)> (http_trans) [44] After Remapping:
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) HTTP_HEADER 0x152fdc2cb888: [T: 3, L:   48, OBJFLAGS: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HTTP.cc:570 (http_hdr_describe)> (http) [TYPE: REQ, V: 10001, URL: 0x152fdc2cbb08, METHOD: "CONNECT", METHOD_LEN: 7, FIELDS: 0x152fdc2cb8b8]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) URL 0x152fdc2cbb08: [T: 2, L:  112, OBJFLAGS: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1594 (url_describe)> (http) [URLTYPE: 0, SWKSIDX: -1,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1596 (url_describe)> (http) 	SCHEME: "", SCHEME_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1597 (url_describe)> (http) 	USER: "", USER_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1599 (url_describe)> (http) 	PASSWORD: "", PASSWORD_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1600 (url_describe)> (http) 	HOST: "31.13.92.36", HOST_LEN: 11,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1602 (url_describe)> (http) 	PORT: "443", PORT_LEN: 3, PORT_NUM: 443
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1603 (url_describe)> (http) 	PATH: "", PATH_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1605 (url_describe)> (http) 	PARAMS: "", PARAMS_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1607 (url_describe)> (http) 	QUERY: "", QUERY_LEN: 0,
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <URL.cc:1609 (url_describe)> (http) 	FRAGMENT: "", FRAGMENT_LEN: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) MIME_HEADER 0x152fdc2cb8b8: [T: 4, L:  592, OBJFLAGS: 0]
[Apr 23 17:44:55.069] [ET_NET 3] DEBUG: <MIME.cc:2604 (mime_hdr_describe)> (http)
	[PBITS: 0x0000000000000000, SLACC: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, HEADBLK: 0x152fdc2cb8f8, TAILBLK: 0x152fdc2cb8f8]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <MIME.cc:2609 (mime_hdr_describe)> (http) 	[CBITS: 0x00000000, T_MAXAGE: 0, T_SMAXAGE: 0, T_MAXSTALE: 0, T_MINFRESH: 0, PNO$: 0]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) FIELD_BLOCK 0x152fdc2cb8f8: [T: 5, L:  528, OBJFLAGS: 0]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <MIME.cc:2625 (mime_field_block_describe)> (http) [FREETOP: 0, NEXTBLK: (nil)]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HttpTransact.cc:808 (EndRemapRequest)> (http_trans) [44] END HttpTransact::EndRemapRequest
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HttpTransact.cc:814 (EndRemapRequest)> (http_trans) Next action SM_ACTION_API_POST_REMAP; HttpTransact::HandleRequest
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HttpSM.cc:7161 (call_transact_and_set_next_state)> (http) [44] State Transition: SM_ACTION_REMAP_REQUEST -> SM_ACTION_API_POST_REMAP
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HttpTransact.cc:1094 (HandleRequest)> (http_trans) [44] START HttpTransact::HandleRequest
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HttpTransact.cc:5151 (check_request_validity)> (http_trans) [44] [init_stat_vars_from_req] set req cont length to 0
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HttpTransact.cc:6219 (is_request_valid)> (http_trans) [44] [is_request_valid] no request header errors
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HttpTransact.cc:1116 (HandleRequest)> (http_seq) [44] [HttpTransact::HandleRequest] request valid.
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) HTTP_HEADER 0x152fdc2cb888: [T: 3, L:   48, OBJFLAGS: 0]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HTTP.cc:570 (http_hdr_describe)> (http) [TYPE: REQ, V: 10001, URL: 0x152fdc2cbb08, METHOD: "CONNECT", METHOD_LEN: 7, FIELDS: 0x152fdc2cb8b8]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) URL 0x152fdc2cbb08: [T: 2, L:  112, OBJFLAGS: 0]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1594 (url_describe)> (http) [URLTYPE: 0, SWKSIDX: -1,
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1596 (url_describe)> (http) 	SCHEME: "", SCHEME_LEN: 0,
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1597 (url_describe)> (http) 	USER: "", USER_LEN: 0,
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1599 (url_describe)> (http) 	PASSWORD: "", PASSWORD_LEN: 0,
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1600 (url_describe)> (http) 	HOST: "31.13.92.36", HOST_LEN: 11,
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1602 (url_describe)> (http) 	PORT: "443", PORT_LEN: 3, PORT_NUM: 443
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1603 (url_describe)> (http) 	PATH: "", PATH_LEN: 0,
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1605 (url_describe)> (http) 	PARAMS: "", PARAMS_LEN: 0,
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1607 (url_describe)> (http) 	QUERY: "", QUERY_LEN: 0,
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <URL.cc:1609 (url_describe)> (http) 	FRAGMENT: "", FRAGMENT_LEN: 0]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) MIME_HEADER 0x152fdc2cb8b8: [T: 4, L:  592, OBJFLAGS: 0]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <MIME.cc:2604 (mime_hdr_describe)> (http)
	[PBITS: 0x0000000000000000, SLACC: 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, HEADBLK: 0x152fdc2cb8f8, TAILBLK: 0x152fdc2cb8f8]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <MIME.cc:2609 (mime_hdr_describe)> (http) 	[CBITS: 0x00000000, T_MAXAGE: 0, T_SMAXAGE: 0, T_MAXSTALE: 0, T_MINFRESH: 0, PNO$: 0]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <HdrHeap.cc:55 (obj_describe)> (http) FIELD_BLOCK 0x152fdc2cb8f8: [T: 5, L:  528, OBJFLAGS: 0]
[Apr 23 17:44:55.070] [ET_NET 3] DEBUG: <MIME.cc:2625 (mime_field_block_describe)> (http) [FREETOP: 0, NEXTBLK: (nil)]

My config is similar to default and I probably didn't change some important options:

>CONFIG proxy.config.exec_thread.autoconfig INT 1
CONFIG proxy.config.exec_thread.autoconfig.scale FLOAT 1.5
CONFIG proxy.config.exec_thread.limit INT 2
CONFIG proxy.config.accept_threads INT 1
CONFIG proxy.config.task_threads INT 2
CONFIG proxy.config.cache.threads_per_disk INT 8
CONFIG proxy.config.exec_thread.affinity INT 1
CONFIG proxy.config.http.server_ports STRING 3140
CONFIG proxy.config.http.insert_request_via_str INT 1
CONFIG proxy.config.http.insert_response_via_str INT 0
CONFIG proxy.config.http.parent_proxy_routing_enable INT 0
CONFIG proxy.config.http.parent_proxy.retry_time INT 300
CONFIG proxy.config.http.parent_proxy.connect_attempts_timeout INT 30
CONFIG proxy.config.http.forward.proxy_auth_to_parent INT 0
CONFIG proxy.config.http.uncacheable_requests_bypass_parent INT 1
CONFIG proxy.config.http.keep_alive_no_activity_timeout_in INT 120
CONFIG proxy.config.http.keep_alive_no_activity_timeout_out INT 120
CONFIG proxy.config.http.transaction_no_activity_timeout_in INT 30
CONFIG proxy.config.http.transaction_no_activity_timeout_out INT 30
CONFIG proxy.config.http.transaction_active_timeout_in INT 900
CONFIG proxy.config.http.transaction_active_timeout_out INT 0
CONFIG proxy.config.http.accept_no_activity_timeout INT 120
CONFIG proxy.config.net.default_inactivity_timeout INT 86400
CONFIG proxy.config.http.connect_attempts_max_retries INT 3
CONFIG proxy.config.http.connect_attempts_max_retries_dead_server INT 1
CONFIG proxy.config.http.connect_attempts_rr_retries INT 3
CONFIG proxy.config.http.connect_attempts_timeout INT 30
CONFIG proxy.config.http.post_connect_attempts_timeout INT 1800
CONFIG proxy.config.http.down_server.cache_time INT 60
CONFIG proxy.config.http.down_server.abort_threshold INT 10
CONFIG proxy.config.http.negative_caching_enabled INT 0
CONFIG proxy.config.http.negative_caching_lifetime INT 1800
CONFIG proxy.config.http.insert_client_ip INT 1
CONFIG proxy.config.http.insert_squid_x_forwarded_for INT 1
CONFIG proxy.config.http.push_method_enabled INT 0
CONFIG proxy.config.http.cache.http INT 1
CONFIG proxy.config.http.cache.ignore_client_cc_max_age INT 1
CONFIG proxy.config.http.normalize_ae INT 1
CONFIG proxy.config.http.cache.cache_responses_to_cookies INT 1
CONFIG proxy.config.http.cache.cache_urls_that_look_dynamic INT 1
CONFIG proxy.config.http.cache.when_to_revalidate INT 0
CONFIG proxy.config.http.cache.required_headers INT 2
CONFIG proxy.config.http.cache.heuristic_min_lifetime INT 3600
CONFIG proxy.config.http.cache.heuristic_max_lifetime INT 86400
CONFIG proxy.config.http.cache.heuristic_lm_factor FLOAT 0.10
CONFIG proxy.config.net.connections_throttle INT 30000
CONFIG proxy.config.net.max_connections_in INT 30000
CONFIG proxy.config.net.max_connections_active_in INT 10000
CONFIG proxy.config.cache.ram_cache.size INT -1
CONFIG proxy.config.cache.ram_cache_cutoff INT 4194304
CONFIG proxy.config.cache.limits.http.max_alts INT 5
CONFIG proxy.config.cache.max_doc_size INT 0
CONFIG proxy.config.cache.min_average_object_size INT 8000
CONFIG proxy.config.log.logging_enabled INT 3
CONFIG proxy.config.log.max_space_mb_for_logs INT 25000
CONFIG proxy.config.log.max_space_mb_headroom INT 1000
CONFIG proxy.config.log.rolling_enabled INT 1
CONFIG proxy.config.log.rolling_interval_sec INT 86400
CONFIG proxy.config.log.rolling_size_mb INT 10
CONFIG proxy.config.log.auto_delete_rolled_files INT 1
CONFIG proxy.config.log.periodic_tasks_interval INT 5
CONFIG proxy.config.diags.debug.enabled INT 1
CONFIG proxy.config.diags.debug.tags STRING http.*|dns.*
CONFIG proxy.config.url_remap.remap_required INT 0
CONFIG proxy.config.url_remap.pristine_host_hdr INT 1
CONFIG proxy.config.reverse_proxy.enabled INT 1
CONFIG proxy.config.ssl.client.verify.server INT 0
CONFIG proxy.config.ssl.client.CA.cert.filename STRING NULL
CONFIG proxy.config.ssl.server.cipher_suite STRING ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
CONFIG proxy.config.diags.debug.enabled INT 1
CONFIG proxy.config.diags.debug.tags STRING http|dns
CONFIG proxy.config.dump_mem_info_frequency INT 0
CONFIG proxy.config.http.slow.log.threshold INT 0

**Comment by swood** [comment]
I found the main difference between ATS and Squid. As I mentioned, Android expects something that ATS didn't provide.
The answer from ATS looks like (in tcpdump level) like below:
http://prnt.sc/nj3r0y
And the answer from Squid looks dramatically different:
http://prnt.sc/nj5e29

I can't affirm this a cause of my problem, but may I ask is there a way to change it? I mean, to make it similar as squid answer?
@maskit

**Comment by maskit** [comment]
If you want to remove or modify headers, you may be able to do it with header_rewrite plugin.
https://docs.trafficserver.apache.org/en/8.0.x/admin-guide/plugins/header_rewrite.en.html

But I'm not sure at all. I've never used CONNECT method.

**Comment by bryancall** [comment]
@swood is this still and issue?  If so please reopen
