### ISSUE TITLE
TLSv1.3 session resumption not working if early data is enabled

### ISSUE THREAD

**Issue by duke8253** [apache/trafficserver#5341]
While trying to get 0-rtt working as mentioned in #4128, I discovered that session resumption with TLSv1.3 is currently broken in ats. Reason being that in TLSv1.3, it only uses a new generic PSK mechanism, both session IDs and session tickets are obsolete. So before we can fix the session resumption issue, we won't be able to get 0-rtt to work. 

The way to verify resumption is working has also changed, here's the debug output of a successful resumption, and early data was sent:
```
Reused, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was accepted
Verify return code: 18 (self signed certificate)
```
And here's one that wasn't successful:
```
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was rejected
Verify return code: 18 (self signed certificate)
```

**Comment by masaori335** [comment]
I tried in my local box, with latest master and openssl v1.1.1b. It looks like working.

```
$ /usr/local/opt/openssl@1.1/bin/openssl s_client -connect localhost:4443 --sess_out /tmp/ssn -tls1_3 | grep "TLSv1.3, Cipher"
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
$ /usr/local/opt/openssl@1.1/bin/openssl s_client -connect localhost:4443 --sess_in /tmp/ssn -tls1_3 | grep "TLSv1.3, Cipher"
Reused, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
```

**Comment by duke8253** [comment]
Looks like I'm missing something here, the resumption is affected by just calling `SSL_set_max_early_data` to enable early data, if I remove the call resumption works just fine.

**Comment by duke8253** [comment]
So the problem is actually addressed by this ticket on openssl's page https://github.com/openssl/openssl/issues/6313

So we'll need to add the `SSL_OP_NO_ANTI_REPLAY` option, if we set `proxy.config.ssl.session_cache` to 2 in `records.config`.

**Comment by zwoop** [comment]
Remember to clear the Milestone / Projects on PRs that are closed.
