### ISSUE TITLE
Can we remove WCCP?

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5361]
This is an RFC, is anyone still using / requiring WCCP ?  I hear that some people might use it with 6.0.0, but going forward with e.g. 9.0.0, can we get rid of this? The argument against WCCP is that it's a protocol that's not useful / supported going forward, and does not have IPv6 support.

**Comment by zwoop** [comment]
@oknet Can you confirm that you still need WCCP for ATS v9.0.0?

**Comment by oknet** [comment]
If I am the only user of WCCP, let's remove WCCP from ATS.

I just don't want to see the ATS function getting less and less.

But I still working on Socks Proxy.

**Comment by zwoop** [comment]
Entirely up to you, if you think you'll maintain it, we'll keep it. @randall already gracefully migrated the configurations.

**Comment by oknet** [comment]
@zwoop @randall 

There are 2 ways to support WCCP within ATS:

1. By `traffic_wccp` daemon.
2. By `traffic_manager` command line tool.

The only difference is that `traffic_wccp` does not have any statistics for WCCP.
