### ISSUE TITLE
Rename or eliminate non-errroneous ssl error metrics

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5389]
Talking to Susan, these would be candidates for renaming, or elimination:

```
proxy.process.ssl.ssl_error_want_write
proxy.process.ssl.ssl_error_want_read
proxy.process.ssl.ssl_error_zero_return
```

The problem I have with these is that they are normal behavior, so at a minimum putting them into the error category is confusing / misleading. They might not even be useful at all, but I'll leave that to the Good Dr. to decide.

**Comment by shinrich** [comment]
Will put up a PR next week.

**Comment by shinrich** [comment]
Merged in relevant PR.
