### ISSUE TITLE
☂Plugins to promote to stable for v9.0.0

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5394]
- [x] cache_range_requests (need docs)
- [x] certifier (or move to examples)
- [x] multiplexer
- [x] prefetch
- [x] remap_purge

@mlibbey  Please double check for correctness.

**Comment by zwoop** [comment]
This list also needs to be vetted on the mailing list.

**Comment by zwoop** [comment]
Blocks #5457

**Comment by SolidWallOfCode** [comment]
I definitely want certifier in either experimental or plugins, it's supposed to be usable as is in production.

I think moving multiplexer up is fine as well, that's gotten production use here.

**Comment by zwoop** [comment]
I'm postponing promotion of remap_stats, it should be rewritten to use e.g. std::unordered_map and C++, and be truly cross platform.

**Comment by zwoop** [comment]
Note that cache_promot was already promoted to stable ...
