### ISSUE TITLE
Complete or remove f_callback_on_open in NetAccept

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5418]
In current code there is no cont implement the `NET_EVENT_ACCEPT_FAILED` event and `NET_EVENT_ACCEPT_SUCCEED` event. and there is no way to set  `f_callback_on_open` to true. So it would be better to implement this callback or remove it . 

I prefer to completing it .

```
 // NetAccept::do_listen(bool non_blocking)
  if (opt.f_callback_on_open && !action_->cancelled) {
    if (res) {
      action_->continuation->handleEvent(NET_EVENT_ACCEPT_FAILED, this);
    } else {
      action_->continuation->handleEvent(NET_EVENT_ACCEPT_SUCCEED, this);
    }
    mutex = nullptr;
  }
```

**Comment by maskit** [comment]
@scw00 Can we close this?
