### ISSUE TITLE
compress plugin DeflateCompressionLevel / BrotliCompressionQuality

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#5422]
other than on httpd the ATS plugin seems not to support comression level, here some benchmarks (ab -c 10 -n 1000) and the size between the different levels for a very large and a very smalll http page

i didn't even try with the httpd default of 5 for BrotliCompressionQuality given that a lot of benchmakrs over the last years showed me that the overal performance is better with lower values

gzip:   36.24 KB (37,109 bytes) Requests per second: 257.70 (DeflateCompressionLevel 3)
brotli: 30.23 KB (30,953 bytes) Requests per second: 213.03 (BrotliCompressionQuality 4)
brotli: 31.70 KB (32,463 bytes) Requests per second: 224.33 (BrotliCompressionQuality 3)

gzip:   5.80 KB (5,937 bytes) Requests per second: 1126.73 (DeflateCompressionLevel 3)
brotli: 5.29 KB (5,415 bytes) Requests per second: 1086.02 (BrotliCompressionQuality 4)
brotli: 5.66 KB (5,799 bytes) Requests per second: 1131.71 (BrotliCompressionQuality 3)

**Comment by randall** [comment]
The plugin is currently hardwired for 6.

From compress.cc:
```
const int ZLIB_COMPRESSION_LEVEL = 6;
const int BROTLI_COMPRESSION_LEVEL = 6;
```

**Comment by thelounge-zz** [comment]
6 is a terrible high default anyways

just look at gzip 4 versus gzip 6 with a input string of  341.7 KB
0.45278000831604 verus 0.62832188606262 seconds compress time with 100 loops
36.3 KB versus 34.4 KB but wasting 30% cpu time

the numbers are from a php script using gzcompress / gzuncompress and was years ago my justification set the compression level to 4 on httpd's mod_deflate

----------------------

Level: 1
gzcompress: 0.22128701210022
bzcompress: 4.1618258953094
gzuncompress: 0.065831899642944
bzdecompress: 0.5602490901947

Level: 2
gzcompress: 0.22770714759827
bzcompress: 4.4017570018768
gzuncompress: 0.062705039978027
bzdecompress: 0.59332084655762

Level: 3
gzcompress: 0.23908400535583
bzcompress: 4.6610200405121
gzuncompress: 0.06245493888855
bzdecompress: 0.5973219871521

Level: 4
gzcompress: 0.45278000831604
bzcompress: 5.0547602176666
gzuncompress: 0.063812017440796
bzdecompress: 0.62671494483948

Level: 5
gzcompress: 0.50305700302124
bzcompress: 5.0774538516998
gzuncompress: 0.059491872787476
bzdecompress: 0.63701605796814

Level: 6
gzcompress: 0.62832188606262
bzcompress: 5.0966877937317
gzuncompress: 0.059906005859375
bzdecompress: 0.62324595451355

Level 1
Original: 341.7 KB
GZ: 39.2 KB
BZ2: 26.8 KB
GZ-Base64: 52.3 KB
BZ2-Base64: 35.7 KB

Level 2
Original: 341.7 KB
GZ: 39.1 KB
BZ2: 25.9 KB
GZ-Base64: 52.2 KB
BZ2-Base64: 34.5 KB

Level 3
Original: 341.7 KB
GZ: 38.1 KB
BZ2: 26 KB
GZ-Base64: 50.8 KB
BZ2-Base64: 34.6 KB

Level 4
Original: 341.7 KB
GZ: 36.3 KB
BZ2: 25.3 KB
GZ-Base64: 48.4 KB
BZ2-Base64: 33.7 KB

Level 5
Original: 341.7 KB
GZ: 35.4 KB
BZ2: 25.3 KB
GZ-Base64: 47.2 KB
BZ2-Base64: 33.7 KB

Level 6
Original: 341.7 KB
GZ: 34.4 KB
BZ2: 25.3 KB
GZ-Base64: 45.9 KB
BZ2-Base64: 33.7 KB

**Comment by bryancall** [comment]
@thelounge-zz If you would like this option, please reopen the issue and create a PR for it.
