### ISSUE TITLE
all_headers autest fails periodically

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#5437]
In this test, two requests are made and the loggging.yaml is set to exercise the all-headers versions of the client/proxy/server/cache request and response headers.

Two requests are made.  It is expected that the second request is read from cache and so the cache version of the all-headers log entries will be filled in and the proxy-request/server-response headers will be empty.

In the failure case, the response is not served from cache, so there is a gold file mismatch.  Although it appears that the logging all-headers values are good.

Not sure how to fix this one.  Given timing variances on an overloaded test machine, I don't think we can guarantee that the first request will be in cache before the second request comes in.  Traffic server does not delay the response to client until the item is safely in cache.

We could put some arbitrary time delay to reduce the likelihood of hitting this problem.  Or we could add a phase that makes curl request with the 'Cache-Control' header set to only-if-cached.  And keep querying until this curl returns a value.  But in that case your log file may have more than two entries and your gold file comparison will have to be a bit more clever. 

@ywkaras created this test initially.

**Comment by shinrich** [comment]
An example of an erroneous test_all_headers.log

```
 {{{Host}:{127.0.0.1:61996}}{{User-Agent}:{007}}{{Accept}:{*/*}}{{x-header0}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{x-header1}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{x-header2}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}} 200 {{{Cache-Control}:{max-age=85000}}{{Content-Length}:{3}}{{Date}:{Tue, 07 May 2019 14:35:43 GMT}}{{Age}:{0}}{{Connection}:{keep-alive}}{{Server}:{ATS/9.0.0}}} {{{Connection}:{close}}{{Cache-Control}:{max-age=85000}}{{Content-Length}:{3}}{{Date}:{Tue, 07 May 2019 14:35:43 GMT}}} {{{Host}:{127.0.0.1:61996}}{{User-Agent}:{007}}{{Accept}:{*/*}}{{x-header0}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{x-header1}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{x-header2}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{Client-ip}:{127.0.0.1}}{{X-Forwarded-For}:{127.0.0.1}}{{Via}:{http/1.1 880e10456466[132f61c3-2770-4fa9-ac53-1dd115c1c72c] (ApacheTrafficServer/9.0.0)}}} {}
 {{{Host}:{127.0.0.1:61996}}{{User-Agent}:{007}}{{Accept}:{*/*}}{{x-header0}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{x-header1}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{x-header2}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}} 200 {{{Cache-Control}:{max-age=85000}}{{Content-Length}:{3}}{{Date}:{Tue, 07 May 2019 14:35:43 GMT}}{{Age}:{0}}{{Connection}:{keep-alive}}{{Server}:{ATS/9.0.0}}} {{{Connection}:{close}}{{Cache-Control}:{max-age=85000}}{{Content-Length}:{3}}{{Date}:{Tue, 07 May 2019 14:35:43 GMT}}} {{{Host}:{127.0.0.1:61996}}{{User-Agent}:{007}}{{Accept}:{*/*}}{{x-header0}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{x-header1}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{x-header2}:{abcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnopabcdefghijklmnop}}{{Client-ip}:{127.0.0.1}}{{X-Forwarded-For}:{127.0.0.1}}{{Via}:{http/1.1 880e10456466[132f61c3-2770-4fa9-ac53-1dd115c1c72c] (ApacheTrafficServer/9.0.0)}}} {}
```

**Comment by SolidWallOfCode** [comment]
I'm not clear on how this can happen. Once the first transaction completes, e.g. the user agent has read the response, the object is in the cache, or it isn't. Waiting should make no difference. If the requests are made in the same curl, or different process instances, I don't see how the second transaction can start before the first one has completed.

**Comment by ywkaras** [comment]
This test case is skipped in the Verizon-customized version of 7.1, due to this problem.  We had not seen it previously in Apache master.

**Comment by ywkaras** [comment]
One work around I tried in our 7.1 was to force the object into cache with a PUSH request.  But this caused cache write errors when run in our docker-based CI regression testing.

**Comment by ywkaras** [comment]
Another workaround, which does seem to work, is to do the GET a bunch of times.  https://github.com/ywkaras/trafficserver/commit/eaacb569a7e9fb41a9f7c5b1d95828e1e880a05a

It seems like at least the last GET will be reliably cached, but @shinrich did not like this workaround.

**Comment by ywkaras** [comment]
I ran the all_headers test with the two fixes from ASF master in the Vz CI pipeline.  Did not fail once.

**Comment by shinrich** [comment]
I think we are in good shape now on this test.
