### ISSUE TITLE
Remove 	proxy.config.http.cache.vary_default_*

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5461]
This includes

```
	proxy.config.http.cache.vary_default_text
	proxy.config.http.cache.vary_default_images
	proxy.config.http.cache.vary_default_other

```

**Comment by zwoop** [comment]
Blocks #5457

**Comment by mlibbey** [comment]
I could be wrong, but I don't think you can do that much with Vary in header_rewrite.
https://github.com/apache/trafficserver/issues/2925

**Comment by zwoop** [comment]
But that's multi-value headers, right ? Vary: would be a single value ?

**Comment by mlibbey** [comment]
Yeah, got all the things mixed up. Nothing to see here!
