### ISSUE TITLE
traffic_ctl config reload changes permissions of records.config

### ISSUE THREAD

**Issue by ema** [apache/trafficserver#5486]
Related to #2505, `traffic_ctl config reload` changes the permissions of records.config in certain cases:

```
root@traffic-upload-stretch:/etc/trafficserver# ls -l records.config
-r-------- 1 trafficserver trafficserver 3119 May 13 15:27 records.config
root@traffic-upload-stretch:/etc/trafficserver# traffic_ctl config get proxy.config.http.cache.required_headers
proxy.config.http.cache.required_headers: 2
root@traffic-upload-stretch:/etc/trafficserver# sed -i 's/proxy.config.http.cache.required_headers INT 2/proxy.config.http.cache.required_headers INT 1/' records.config
root@traffic-upload-stretch:/etc/trafficserver# traffic_ctl config reload
root@traffic-upload-stretch:/etc/trafficserver# traffic_ctl config get proxy.config.http.cache.required_headers
proxy.config.http.cache.required_headers: 1
root@traffic-upload-stretch:/etc/trafficserver# ls -l records.config
-rw-r--r-- 1 trafficserver trafficserver 3119 May 13 15:28 records.config
```
I've applied 84ca16577c8cb5d3885bffd0ea877598eed722d3 by @randall locally and verified that the patch leaves the permissions of records.config unchanged if proxy.config.disable_configuration_modification is enabled.

**Comment by zwoop** [comment]
That setting is becoming mandatory: #5474.

That doesn't help 8.0.x / 8.1.x though, maybe we need some fixes there ?

**Comment by ema** [comment]
> That doesn't help 8.0.x / 8.1.x though, maybe we need some fixes there ?

Ah yes! I forgot to mention that the bug affects 8.0.3, and that I've applied the patch to such version.

**Comment by bryancall** [comment]
I am pretty sure this has been fixed in the 9.x branch
