### ISSUE TITLE
HttpSM performs Http1.1 Logic

### ISSUE THREAD

**Issue by a-canary** [apache/trafficserver#5488]
The HttpSM and HttpTransact does a large amount of Http1.1 logic which increases complexity and convolutes Http2 and Http3 code paths and state machine states. 

Solutions to this have been described in previous summits*, PR attempts** and projects***.  
 
[PROPOSAL] HttpSM to interface with a ProxyTransaction (a base class for all protocols). Which requires Http1.1 logic to be refactored into a Http1Transaction, Http1ClientSession, and Http1ServerSession.

.* [Http/2 to Origin Update](https://cwiki.apache.org/confluence/display/TS/Presentations+-+2018?preview=/75958509/80453132/Cork_%20%20Http2%20to%20origin.pdf)
.** https://github.com/shinrich/trafficserver/pull/1
.*** https://github.com/apache/trafficserver/projects/9

**Comment by a-canary** [comment]
@masaori335 
This simplified diagram shows what I am working towards in my refactors. Ideally, HttpSM will only interface with ProxyTransaction, and know nothing of Http1/2/3 specific implementations. 

![Transactions](https://user-images.githubusercontent.com/24980792/58572885-2b544800-8202-11e9-9ab6-fb53e0c91471.png)

**Comment by masaori335** [comment]
@a-canary Nice! 
> Ideally, HttpSM will only interface with ProxyTransaction, and know nothing of Http1/2/3 specific implementations.

Looks reasonable. Is this mean HTTP header parsing will be done on ProxyTransaction side ? I'm wondering about #5230 and this. It might be next step.

**Comment by a-canary** [comment]
I'll take a look at it. It sounds like the kind of thing we are trying to abstract out of HttpSM.

**Comment by maskit** [comment]
#6545 reminded me how H2 handle Cookie headers. We should probably keep Cookie headers separated if the connection for an origin is also H2.

**Comment by bryancall** [comment]
we have other issues tracking h2 to origin
