### ISSUE TITLE
dir_token is useless anymore is should be removed

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5505]

**Comment by bryancall** [comment]
This is used in:
` iocore/cache/CacheDir.cc:    if (!dir_token(e) && dir_offset(e) >= static_cast<int64_t>(start) && dir_offset(e) < static_cast<int64_t>(end)) {`

Please reopen if this still needs to be fixed.

**Comment by SolidWallOfCode** [comment]
That reads it, but I can't find any place it would be set. There is `dir_set_token` but it's never called. I think @scw00 is correct, those bits are never set, and therefore are not useful.

**Comment by masaori335** [comment]
FWIW, the `dir_set_token()` calls were dead code and removed by this commit.

https://github.com/apache/trafficserver/commit/6f155f44466c91aa892b861777c914b1ddde7b99#diff-b194c2cc95f7657ac89659cbad6b6d3b3dd80ff4ad5757ff1bbe4b0ac482b983L240
