### ISSUE TITLE
New feature to ignore self detect in parent selection.

### ISSUE THREAD

**Issue by jrushford** [apache/trafficserver#5519]
I wish to be able to configure a parent.config entry to ignore that a parent is marked down for self detection so that I may use parent selection in a cache group of peers.  All the members within this cache group would be listed as parents and requests to a particular member would be served by members of this cache group including the local cache handling the request using parent selection with consistent hashing.  This would allow more efficient cache storage of a large video library across an edge cache group.

So, I would add a flag to parent.config, 'ignore_self_detect=true' to make use of this peering behavior.  'ignore_self_detect' would default to 'false'.

**Comment by zwoop** [comment]
Blocks #5457

**Comment by vmamidi** [comment]
fixed with #5544.
