### ISSUE TITLE
Ignore unknown HTTP/3 frames

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#5545]
H3 has unknown type frame which have to be ignored. 
ATS can handle it correctly after https://github.com/apache/trafficserver/commit/142dd26851659214316d50bb76b29879affe609e, but no exercise nor unit test.

> Stream types of the format "0x1f * N + 0x21" for integer values of N
   are reserved to exercise the requirement that unknown types be
   ignored.

- https://tools.ietf.org/html/draft-ietf-quic-http-20#section-3.2.3

e.g.
```
ff ff ff ff ff ff ff fe 00
```

```
ff ff ff ff ff ff ff fe 12 47 52 45 41 53 45 20 69 73 20 74 68 65 20 77 6f 72 64
```

**Comment by duke8253** [comment]
I'm a bit confused, doesn't this test this?

https://github.com/apache/trafficserver/blob/89f15f8d028889846c0dbaed3c22dd180ce659d9/proxy/http3/test/test_Http3Frame.cc#L258-L268

**Comment by duke8253** [comment]
Yeah, that's also what I was thinking about adding.
