### ISSUE TITLE
☂ Tasks for removing traffic_manager

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5563]
These are the open tasks for removing

- [x] Handle traffic_manager tasks in traffic_server threads. #1372
- [x] Add back in stack trace when ATS crashes https://github.com/apache/trafficserver/pull/10811

**Comment by scw00** [comment]
So How do you manage sockets after server crash if we remove the traffic manager?

**Comment by zwoop** [comment]
We will manage sockets in traffic_server only.

**Comment by scw00** [comment]
I mean, as @shukitchan point in last summit, if the server crash, then every connection request will be reseted. But if we have the manager, the socket will be hold until the server restart successfully.

**Comment by traeak** [comment]
If traffic_server crashes, instead of lying to the client using some intermediary program isn't it better just to send a real status like a 503 Service Unavailable and let the client deal with it?  If traffic_server crashes it's kind of not available.

**Comment by zwoop** [comment]
Damien, there's still a few mentions of traffic_manager in the master branch now, can we clean that up please? It's not longer deprecated it's completely removed.

**Comment by brbzull0** [comment]
> Damien, there's still a few mentions of traffic_manager in the master branch now, can we clean that up please? It's not longer deprecated it's completely removed.

@zwoop  Do we want to even wipe out the "deprecated" mentions of it?
