### ISSUE TITLE
Shouldn't we autodetect brotli?

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5576]
It seems you have to explicitly ask for Brotli, but shouldn't we just do what we normally do, and auto detect (png-config etc.) for the Brotli include files ?

This might be related to #4741 as well.

**Comment by zwoop** [comment]
Assigning to Randall for prioritization (i.e. does this need to go into 9.0.0 etc.). Or should we just ignore.

**Comment by zwoop** [comment]
Moving out to 9.1.x

**Comment by calavera** [comment]
Closing this issue since it's already fixed.
