### ISSUE TITLE
compile failure

### ISSUE THREAD

**Issue by zyz77** [apache/trafficserver#5581]
when I compile ats 7.1.4 on centos with arm64, i met an error.

==== Building LuaJIT 2.0.4 ====  
make -C src  
make[4]: Entering directory '../lib/luajit/src'  
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"  
 #error "No support for this architecture (yet)"  

Is this mean at this moment ats does not support arm64 or how to fix this problem?

./configure CC=--enable-hwloc
make -j32
make install

**Comment by shukitchan** [comment]
it looks like your immediate problem is luajit.
In 8.x, we removed the luajit library.
Can you upgrade to the latest 8.x and give it a try?

**Comment by zyz77** [comment]
I replaced luajit source code to version 2.10 on ats 7.1.4. and solved this problem.
