### ISSUE TITLE
how to  filter logs  by X-Forwarded-For header 

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#5601]
currently running ats v8.0.3,  after change logging.config to yaml ,

i found that can't filter logs by xff header,

i had try  this but without work:
condition: %<{X-Forwarded-For}cqh> CONTAIN xxx

when use ats v7.x, i can do that by
 filter.reject('%<{X-Forwarded-For}cqh> CONTAIN xxx')

**Comment by randall** [comment]
Are there any warnings or errors generated? 

Can you trying with quoting?

eg
```
condition: '%<{X-Forwarded-For}cqh> CONTAIN xxx'
```

**Comment by esmq2092** [comment]
here is the logs, when reload fail, no events get logged.
----------------------------------------
[Jun  5 18:11:35.417] {0x2aebfaf8ae00} NOTE: loading logging.yaml
[Jun  5 18:11:35.418] {0x2aebfaf8ae00} NOTE: failed to reload logging.yaml
[Jun  5 18:11:35.420] {0x2aebfaf8ae00} NOTE: logging initialized[3], logging_mode = 3
----------------------------------------
trying with quoting, i works.  ^-^
thanks for your help.
