### ISSUE TITLE
QUIC: Introduce QUICPacketSizeProvider and QUICPacketSizeSuggester 

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5612]
The main idea of this issue is trying to introduce QUICPacketSizeProvider and QUICPacketSizeSuggester to reactor the minimus and maximus packet size. 

>There are a few factors that affects min/max packet size (e.g. PMTU, path validation state, protocol requirement, randomness, etc).
We may want to have QUICPacketSizeProvider and QUICPacketSizeSuggester. A module that takes care of PMTU would be a QUICPacketSizeSuggester, and it can only suggest min and max sizes because it doesn't know other things. QUICPacketSizeProvider will gather info from suggesters and decide the min and max.

link to #5611

**Comment by zwoop** [comment]
@masaori335 Please prioritize (i.e. is this a 9.0.0 show stopper etc.).

**Comment by masaori335** [comment]
This is not blocker of quic-20 branch nor 9.0.0.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
