### ISSUE TITLE
proxy.process.http2.total_client_streams (and possibly other metrics) are always zero

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5619]
While looking for something else, I noticed that the H2 streams metrics are not working:

```
proxy.process.http2.total_client_streams 0
```

However, there's plenty of H2 connections:

```
proxy.process.http2.total_client_connections 5396
```

This is running current master on Docs / CI.

**Comment by zwoop** [comment]
This block #5457

**Comment by zwoop** [comment]
I suspect, but not certain, that this metrics might also be wrong, possibly others as well:

```
proxy.process.http2.current_client_streams 0
```

**Comment by masaori335** [comment]
It looks like it's broken somewhere on master after branching 8.x. I'll take a look deeply.
