### ISSUE TITLE
ts.client_request.get_url return mapped url instead of client's original url.

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#5621]
this is not a problem for v8.0.3，
but when i test aginst master branch, the tslua plugin change this behviour,
it return mapped url。。。

**Comment by shukitchan** [comment]
It is essentially calling TSHttpTxnEffectiveUrlStringGet()

can you provide me an example? e.g. what's the remap rules? What's the incoming request? And is the pristine host header setting changed or not?

**Comment by esmq2092** [comment]
`map http://game.example.com/ http://game.example.com.cats.netease.com/ @plugin=tslua.so @pparam=--states=64 @pparam=/home/trafficserver/etc/maps/tslua.mobile-h5 @plugin=conf_remap.so @pparam=/home/trafficserver/etc/maps/xx.example.com @plugin=cachekey.so
`

with pristine host header enabled...

the same config, works fine for v8.0.3, but not master branch

**Comment by esmq2092** [comment]
the same problem goes to regex_remap plugin,
as $h now refer to mapped host (not as it say to be from the original request)

**Comment by shukitchan** [comment]
ok. that narrowed it down. 
I think it is the effect of this PR - https://github.com/apache/trafficserver/pull/4964

**Comment by shukitchan** [comment]
I think regex_remap problem may be related to https://github.com/apache/trafficserver/pull/4964 
Still not too sure why the lua plugin will have that problem. 
Will try to setup the latest master branch to try it out

**Comment by shukitchan** [comment]
Ok. I verified. #4964 is causing this.
Specifically TSHttpTxnEffectiveUrlStringGet() is affected by this.
Perhaps I should be using TSHttpTxnPristineUrlGet() instead. 
I will make a PR for it.

**Comment by shukitchan** [comment]
Actually we already have ts.client_request.get_pristine_url() . 
I think you can use that instead.
I added a PR to document this existing function - https://github.com/apache/trafficserver/pull/5640/files
