### ISSUE TITLE
empty x-forwarded-for header be treated improperly on master

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#5629]
in ats v8.0.3, empty xff header will be  ignored totally，

but not the case when testing against master branch.

in master branch，empty xff will be treated as a "dot" character,  which cause some 400 error when goes to origin...

`--header 'X-Forwarder-For:'`，

btw. temporarily, i use header_rewrite plugin to rectify this ...

**Comment by zwoop** [comment]
@ezelkow1 Can you take a look please?

**Comment by zwoop** [comment]
One concern could be that we rewrote a lot of the Header parsing, so maybe another bug here? @SolidWallOfCode

**Comment by ezelkow1** [comment]
Tested with a master build and I think its OK?

curl -Lvsk -o /dev/null -H "X-Forwarder-For:" "http://localhost:8080"

I see it stripped in the returned output, and through the debug:
+++++++++ Incoming Request +++++++++
-- State Machine Id: 0
GET http://............my test origin............./ HTTP/1.1
Host: ............my test origin.............
User-Agent: curl/7.64.0-DEV
Accept: */*

+++++++++ Proxy's Request +++++++++
-- State Machine Id: 0
GET / HTTP/1.1
Host: ............my test origin.............
User-Agent: curl/7.64.0-DEV
Accept: */*
Client-ip: ::1
X-Forwarded-For: ::1
Via: http/1.1 testcache.com[a92d9745-a2ea-4e0f-88dc-b92f26d95390] (ApacheTrafficServer/9.0.0)

+++++++++ Incoming O.S. Response +++++++++
-- State Machine Id: 0
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=86400
Content-Length: 0
Content-Type: text/plain
Last-Modified: Tue, 09 Jul 2019 18:18:51 GMT
Date: Tue, 09 Jul 2019 18:18:51 GMT

+++++++++ Cached Request Hdr +++++++++
-- State Machine Id: 0
GET http://testorigin/ HTTP/1.1
Host: testorigin
User-Agent: curl/7.64.0-DEV
Accept: */*
Client-ip: ::1
X-Forwarded-For: ::1

+++++++++ Proxy's Response 2 +++++++++
-- State Machine Id: 0
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=86400
Content-Length: 0
Content-Type: text/plain
Last-Modified: Tue, 09 Jul 2019 18:18:51 GMT
Date: Tue, 09 Jul 2019 18:18:51 GMT
Age: 0
Connection: keep-alive
Via: http/1.1 testcache (ApacheTrafficServer/9.0.0 [uScMsSfWpSeN:t cCMp sS])
Server: ATS/9.0.0

So it looks like on mine it probably went to the origin, with the empty xff header

**Comment by bryancall** [comment]
@esmq2092 There have been a couple header fixes on master lately.  The issue looks like it might have been resolved.

If this is still an issue please reopen.
