### ISSUE TITLE
Remove use of Emergency() when parsing records.config strings

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5646]
As of commit 7f08ad6044, we call Emergency() when failing to parse in

```
IpMap *
HttpConfig::parse_redirect_actions();
```

This is generally a really bad idea, because it means if you have a parser error, and reload records.config, you will crash rather than using the old configuration value.

This is an obscure scenario though, and I'm not sure that ATS has a way to deal with this in an reasonable way other than ignoring this configuration change. But, I think that's better (with an error message) rather than crashing.

Likely we can change this to call Error() rather than Emergency().

**Comment by SolidWallOfCode** [comment]
Perhaps it should check if there is a valid current config and fail out if not.
