### ISSUE TITLE
API for explicit VIO shutdown.

### ISSUE THREAD

**Issue by SolidWallOfCode** [apache/trafficserver#5655]
It would be good to have an explicit "cancel IO" mechanism available in the core and to plugins. The failure scenario is

1.  Set up a VIO.
2.  Error happens and the VIO initiator shuts down and destroys its `Continuation`.
3.  IO happens and target of the VIO calls the now destroyed `Continuation`.

The goal would be to add a step "2A" which is "cancel VIO". Currently this is usually done by starting _another_ VIO but with null / zero values. That's ugly, unclear, and error prone. If that's how it's done internally, fine, but the external API should be clean and clear by having an explicit "stop this VIO".

**Comment by shinrich** [comment]
Seems like a good addition.   Where I generally see this being a problem is the VC times out.  But there still is a read_vio from the previous transaction active against the the VC.  The core logic sends the INACTIVITY_TIMEOUT event to the now deleted transaction (or other continuation associated with the now deleted transaction).  We tracked down a lot of these cases in core.  Just ran into this scenario in a plugin.

**Comment by bryancall** [comment]
If this is a proposal please tag it as a proposal and send an email to the dev@ mailing list with `[PROPOSAL]` in the subject.  Also, it should have a function declaration for the API.

**Comment by bryancall** [comment]
My guess is that
