### ISSUE TITLE
Parent Proxy sometimes lost Cache-Control header lines

### ISSUE THREAD

**Issue by nozomi1773** [apache/trafficserver#5679]
I noticed that trafficserver's parent proxy sometimes lost the 2nd and subsequent Cache-Control header lines when origin response have two or more Cache-Control header lines.  
I confirmed that this behavior occurs when trafficserver is configured Hierarchical Caching , and this behavior don't occur when trafficserver isn't so.  

For explaining about this behavior, I built trafficserver from latest source code ( commit: [75e7fc340a5de90c9453ebc8b5302a41a3f73ce8](https://github.com/apache/trafficserver/commit/75e7fc340a5de90c9453ebc8b5302a41a3f73ce8) ) on master branch, and did gold_tests on my repo ( [nozomi1773/trafficserver-test-docker--multiple-cache-control-heders
](https://github.com/nozomi1773/trafficserver-test-docker--multiple-cache-control-heders) ).  

The autest origin's response 2 Cache-Control line definitions are integrated into 1 Cache-Control line (It is a behavior of autest origin),
for that reason, I changed origin to nginx and ran this tests.  
I confirmed that this behavior is reproducible on [multi_cache_control_origin_is_nginx.test.py](https://github.com/nozomi1773/trafficserver-test-docker--multiple-cache-control-heders/blob/master/build_master/tests/gold_tests/multiple-cache-control/multi_cache_control_origin_is_nginx.test.py).  
I entered "via" informations in this *.test.py file.
Could you check this behavior ?

### logging information
I confirmed that this behavior occurs on version 8.0.3 too.  
And I collected log on parent and child .   
```
cqh_cache_control:%<{Cache-Control}cqh>
pqh_cache_control:%<{Cache-Control}pqh>
psh_cache_control:%<{Cache-Control}psh>
ssh_cache_control:%<{Cache-Control}ssh>
cssh_cache_control:%<{Cache-Control}cssh>
```
At the time of loss Cache-Control header lines,  the following content was logging.   

If origin have the following 2 Cache-Control lines.
```
Cache-Control: s-maxage=600, public
Cache-Control: no-cache
```

1st request was the following.
```
< Parent >
cqh_cache_control: -
pqh_cache_control: -
psh_cache_control: "s-maxage=600, public, no-cache"
ssh_cache_control: "s-maxage=600, public, no-cache"
cssh_cache_control: -

< Child >
cqh_cache_control: -
pqh_cache_control: -
psh_cache_control: "s-maxage=600, public, no-cache"
ssh_cache_control: "s-maxage=600, public, no-cache"
cssh_cache_control: -
```
  
2nd request was the following.
```
< Parent >
cqh_cache_control: -
pqh_cache_control: -
psh_cache_control: "s-maxage=600, public"            ← NOTE: on Proxy Response header lost "no-cache"
ssh_cache_control: "s-maxage=600, public, no-cache"
cssh_cache_control: -

< Child >
cqh_cache_control: -
pqh_cache_control: -
psh_cache_control: "s-maxage=600, public"
ssh_cache_control: "s-maxage=600, public"
cssh_cache_control: "s-maxage=600, public"
```

**Comment by zwoop** [comment]
@vmamidi Can you take a look please ?

**Comment by SolidWallOfCode** [comment]
Looks like there's some code that's not checking for duplicate fields. There is a clear loss of information which is wrong.

**Comment by ezelkow1** [comment]
> Looks like there's some code that's not checking for duplicate fields. There is a clear loss of information which is wrong.

Yes thats exactly what it is. Im also not sure this is directly related to parent selection.  Testing here when it gets to
HttpTransact::build_response, 
`[Sep 15 21:14:09.652] [ET_NET 12] DEBUG: <MIME.h:1555 (value_append)> (evan) mimehdr val append creating, name: Etag, len: 4, value: "5f5faad3-1a"Cache-Controlmax-age=5, publicCache-Controlno-cache, len: 13
[Sep 15 21:14:09.652] [ET_NET 12] DEBUG: <HttpTransact.cc:7866 (build_response)> (evan) [0] Appending field: Etag, len: 4, val: "5f5faad3-1a"Cache-Controlmax-age=5, publicCache-Controlno-cache, len: 13, total: 5
[Sep 15 21:14:09.652] [ET_NET 12] DEBUG: <MIME.h:1555 (value_append)> (evan) mimehdr val append creating, name: Cache-Control, len: 13, value: max-age=5, publicCache-Controlno-cache, len: 17
[Sep 15 21:14:09.652] [ET_NET 12] DEBUG: <HttpTransact.cc:7866 (build_response)> (evan) [0] Appending field: Cache-Control, len: 13, val: max-age=5, publicCache-Controlno-cache, len: 17, total: 5
[Sep 15 21:14:09.652] [ET_NET 12] DEBUG: <MIME.h:1555 (value_append)> (evan) mimehdr val append creating, name: Via, len: 3, value: http/1.1 traffic_server (ApacheTrafficServer/10.0.0 [uIcSsNfUpNeN:t cCSpSs ] [http/1.1 tcp ipv4]), len: 97
[Sep 15 21:14:09.652] [ET_NET 12] DEBUG: <HttpTransactHeaders.cc:1135 (add_server_header_to_response)> (http_trans) Adding Server: ATS/10.0.0
+++++++++ Base Header for Building Response +++++++++
-- State Machine Id: 0
HTTP/1.1 200 OK
Server: nginx/1.16.1
Date: Tue, 15 Sep 2020 21:14:09 GMT
Content-Type: text/plain
Content-Length: 26
Last-Modified: Mon, 14 Sep 2020 17:39:31 GMT
Connection: keep-alive
Accept-Ranges: bytes
Etag: "5f5faad3-1a"
Cache-Control: max-age=5, public
Cache-Control: no-cache

+++++++++ Proxy's Response 2 +++++++++
-- State Machine Id: 0
HTTP/1.1 304 Not Modified
Date: Tue, 15 Sep 2020 21:14:09 GMT
Etag: "5f5faad3-1a"
Cache-Control: max-age=5, public
Connection: keep-alive
Via: http/1.1 traffic_server (ApacheTrafficServer/10.0.0 [uIcSsNfUpNeN:t cCSpSs ] [http/1.1 tcp ipv4])
Server: ATS/10.0.0`

So it gets stripped out in that function. The value passed in to the mime parsing there has both headers combined in the value but the length only covers the first one and doesnt know how to parse dupes

Just throwing this in here, still looking in to it
