### ISSUE TITLE
Convert Http Header to Http2 Header

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5688]
Currently, we marshal http header as string. But we can marshal it as binary via HPack.

**Comment by maskit** [comment]
What area are you talking about?

**Comment by scw00** [comment]
cache

**Comment by maskit** [comment]
You mean HPACK String Literal Representation (nearly equal to Huffman encoding)? We obviously cannot use other representations because those require Static Table and Dynamic Table which is only meaningful until the end of a session (index number 42 can be something else on a different session).

cc @SolidWallOfCode

**Comment by scw00** [comment]
Yep. Dynamic Table should be special .

**Comment by bryancall** [comment]
You would have to store the dynamic table with the cache entry and it would make cached entries more complex.  Also, you wouldn't be able to use it directly since the dynamic table for a session would be different from cache, so you would still have to translate it anyways.

**Comment by maskit** [comment]
@bryancall I think you pointed out the same thing as my comment?

And my understanding is that the point is Huffman encoding (not use of Dynamic Table). Is it correct, @scw00 ?

**Comment by scw00** [comment]
Right. Most of the headers are already indexed in static table. So only few custom headers need to be encoded as string. So static table have already had const string to convert the index to the real human readable header string.

So it would be like this.
header(index): value

static table (huffman)
:path (index 0): ....
:content-type(index 1): ...
:content-encoding(index 2): ...

dynamic table (huffman or not)
:x-ats-debug: xxxx

This format will match both h1 case and also h2/h3 case.  It will decrease header payload and increase the data payload in one fragments.

**Comment by maskit** [comment]
Static Table would not work actually because the headers on H2 Static Table and H3 Static Table are different.

**Comment by scw00** [comment]
So can we involve our own table?

**Comment by maskit** [comment]
Well, that is perhaps possible, but I'm not too sure if it is really effective. It would require another table lookup and decoding before sending a header.

**Comment by bryancall** [comment]
I don't think there is a big advantage to storing Huffman encoded headers in cache
