### ISSUE TITLE
Ignore If_modified_since even if if_none_match field's value is empty. 

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5702]
https://tools.ietf.org/html/rfc7232#section-3.3

>A recipient MUST ignore If-Modified-Since if the request contains an If-None-Match header field;

IIUC we should ignore If-Modified-Since once the request contains If-None-Match header field. `Although the value is empty`.

**Comment by bryancall** [comment]
Look like this was fixed in #5701 and merged
