### ISSUE TITLE
H2 sni.yaml overrides do not work with accept threads off

### ISSUE THREAD

**Issue by zwoop** [apache/trafficserver#5720]
With accept threads off, i.e.

```
CONFIG proxy.config.accept_threads INT 0
```

There is no accept_obj at this point in the SNIAction handlers, so e..g this fails:

```
class DisableH2 : public ActionItem
{
public:
  DisableH2() {}
  ~DisableH2() override {}

  int
  SNIAction(Continuation *cont) const override
  {
    auto ssl_vc     = dynamic_cast<SSLNetVConnection *>(cont);
    auto accept_obj = ssl_vc ? ssl_vc->accept_object : nullptr;
    if (accept_obj && accept_obj->snpa && ssl_vc) {
```

This essentially makes it impossible to turn off H2 via sni.yaml, unless accept threads are enabled. I don't know if any other SNIAction() handlers would have similar issues.

**Comment by shinrich** [comment]
Fix merged to master
