### ISSUE TITLE
How to know how many bytes in cache is still fresh?

### ISSUE THREAD

**Issue by DrmagicE** [apache/trafficserver#5725]
How can i get the metric like “proxy.process.cache.fresh_bytes_used” ? Which means the cache object is still fresh.  
The `proxy.process.cache.bytes_used` metric always increase even if i make a PURGE request to remove the object. I need this info to do some load balancing work.

**Comment by zwoop** [comment]
This is not possible to calculate, and PURGE doesn't actually delete anything, it just makes it unreachable. The way ATSs cache works, there's really no way of knowing any of this.

If you need more details, please take this to the mailing list for more explanations / discussions.
