### ISSUE TITLE
Replace Ptr with std::shared_ptr

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5735]
Compare with current Ptr. We lost some feature of the ptr ownership. So it would be better to involve `std::shared_ptr`, `std::unique_ptr` and `std::auto_ptr` etc . 

I would involve this class to replace RefCountObj.
```
#include <memory>


class Freeable {
public:
  virtual void free() = 0;

  struct Deletor {
   void operator()(Freeable *f) {
        f->free();
   }
  };
};
```

So the object creator would be 
```
class ProxyMutex 
{
void free() override;
}

std::shared_ptr<ProxyMutex>
new_ProxyMutex()
{
   auto m = std::unique_ptr<ProxyMutex, Freeable::Deletor>(proxyMutexAllocator.alloc());
  m->init();
  return m;
}

```

**Comment by zizhong** [comment]
👍

**Comment by SolidWallOfCode** [comment]
I'm not sure we can do this. I recently ran in to a situation where `Ptr` works when `shared_ptr` would not.

The essence is that, given a raw pointer, it is safe to convert it to a `Ptr` but *not* safe to convert it to a `shared_ptr`. This comes up in plugins where various objects (most commonly a `MutexPtr`) is passed across the plugin API as a raw pointer. A very specific example is assigning the `HttpSM` mutex to a per transaction `Continuation`.

The C++ standard did not include Boost.IntrisuvePtr which is the equivalent of `Ptr`.

**Comment by maskit** [comment]
>  it is safe to convert it to a Ptr but not safe to convert it to a shared_ptr. 

Where does the difference come from? (How does Ptr make it safe?)
My understanding was that `Ptr` is equivalent of shared_ptr and it has been used just because historical reason, but sounds like it is not.

Wrapping a raw pointer with Ptr (or shared_ptr) without its ownership sounds dangerous. I'd be curious if Ptr does it safely.

**Comment by SolidWallOfCode** [comment]
This isn't going to happen in the foreseeable future.
