### ISSUE TITLE
[question]traffic_logstats execute failed

### ISSUE THREAD

**Issue by xq2248** [apache/trafficserver#5764]
[root@localhost ats]# bin/traffic_logstats 

critical:  squid.blog not enabled can't open log file 

OS: CentOS 7.4
GCC: devtoolset-7-gcc-c++-7.3.1-5.15.el7.x86_64
./configure --prefix=/opt/ats --enable-debug --disable-tests --enable-experimental-plugins --enable-example-plugins --with-ncurses

**Comment by xq2248** [comment]
What is the best C++ compiler for ATS 8.0.x in CentOS7/Redhat7?
There is no offical GCC 7.x.x.

**Comment by masaori335** [comment]
Does `squid.blog` exist? I saw the error message if the log file doesn't exist. The error message looks unclear, though.

For the build toolchain on CentOS 7, as you're using, devtoolset-7 is recommended.
https://cwiki.apache.org/confluence/display/TS/CentOS

**Comment by bryancall** [comment]
If this is still an issue please reopen.
