### ISSUE TITLE
ATS 8.0.3 traffic_server on CentOS 7.4 failed to start

### ISSUE THREAD

**Issue by xq2248** [apache/trafficserver#5776]
The new built ATS8.0.3 traffic_server process failed to start,  as the files of /opt/ts/var/trafficserver/ directory are missing.

The GCC version as follows:
[root@node1 trafficserver-8.0.3]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 

The build commands as follows:
  autoreconf -if
  ./configure --prefix=/opt/ts --enable-debug

[root@node1 ts]# bin/trafficserver start
Starting Apache Traffic Server:                            [FAILED]

[root@node1 trafficserver]# cat /opt/ts/var/log/trafficserver/traffic.out 
[E. Mgmt] log ==> [TrafficManager] using root directory '/opt/ts'
FATAL: Can't open server lockfile '/opt/ts/var/trafficserver/server.lock' (Permission denied)

[root@node1 trafficserver]# cd /opt/ts/var/
[root@node1 var]# ll
total 8
drwxr-xr-x 3 root   root   4096 Aug  6 17:01 log
drwxr-xr-x 2 nobody nobody 4096 Aug  6 17:01 trafficserver

The files of /opt/ts/var/trafficserver/ directory are missing.
[root@node1 var]# cd trafficserver/
[root@node1 trafficserver]# ll
total 0

The selinux has been turned off:
[root@node1 ts]# getenforce 
Disabled

**Comment by bryancall** [comment]
@xq2248 Is this still an issue?  If so please reopen
