### ISSUE TITLE
memory leak in example plugin blacklist_1

### ISSUE THREAD

**Issue by zhengxj91** [apache/trafficserver#5794]
enable dump_mem_info in records.config, noticed a memory leak in example plugin blacklist_1,  the memory of mutexAllocator is keep growing.  everything is fine when disable the blacklist_1 plugin. and i'm tried to using TSMutexDestroy to destroy the TSMux manually before using TSContDestroy, memory leak is not happend again.   The TSMux along with the TSCont can not auto destroyed using TSContDestroy?

I'm using the master branch, and nothing changed on the example plugin blacklist_1.
i had tested on system ubuntu 18.04 and centos 7.6.1810, same with memory leak problem.

```
              48960 |              45040 |         80 | memory/mutexAllocator
              61200 |              51760 |         80 | memory/mutexAllocator
              61200 |              58160 |         80 | memory/mutexAllocator
              73440 |              63200 |         80 | memory/mutexAllocator
              73440 |              69120 |         80 | memory/mutexAllocator
              85680 |              76000 |         80 | memory/mutexAllocator
              85680 |              82000 |         80 | memory/mutexAllocator
              97920 |              86800 |         80 | memory/mutexAllocator
              97920 |              92240 |         80 | memory/mutexAllocator
             110160 |              99280 |         80 | memory/mutexAllocator
             110160 |             105280 |         80 | memory/mutexAllocator
             122400 |             110400 |         80 | memory/mutexAllocator
```

**Comment by randall** [comment]
This might be https://github.com/apache/trafficserver/issues/5777. Can you try again once #6231 is merged?

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
