### ISSUE TITLE
About diagram for header_rewrite Hooks

### ISSUE THREAD

**Issue by hankai17** [apache/trafficserver#5795]
In https://github.com/apache/trafficserver/pull/2267
The order is reversed between READ_REQUEST_HDR_HOOK and READ_REQUEST_PRE_REMAP_HOOK

**Comment by mlibbey** [comment]
Thanks for your report. You can see the updated diagram here:
https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/header_rewrite.en.html#hook-conditions
Can you close this out?

**Comment by hankai17** [comment]
copy that
