### ISSUE TITLE
hostdb.host_file never re-read without restart

### ISSUE THREAD

**Issue by RamJett** [apache/trafficserver#5838]
Currently using 7.1.7 on Debian 9 with settings below:
```
CONFIG proxy.config.dns.resolv_conf STRING NULL
CONFIG proxy.config.hostdb.host_file.path STRING conf/hosts.origin
CONFIG proxy.config.hostdb.host_file.interval INT 300
```
The problem we are having is when file conf/hosts.origin is updated, the change will never happen unless you restart the trafficserver.

My tests to reproduce

1. On trafficserver update origin IP in conf/hosts.origin for testhost origin IP
2.  Watch logs on trafficserver tail -f logs/*.log
3. Local workstation use curl requests to site
4. After 10 minutes, still no change. Note: should be 300 seconds at most
5. restart trafficserver and instant updates

We have let it go over 24 hours and it never updates, even with a reload. A restart is only way to update.

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
