### ISSUE TITLE
pipe buffer size for log.pipe should be configurable

### ISSUE THREAD

**Issue by ericcarlschwartz** [apache/trafficserver#5860]
right now when ats creates a log.pipe object it just uses the standard pipe buffer size from the OS, which in addition to sometimes leading to backups of data in the pipe is also smaller than the max allowable log line size

**Comment by ericcarlschwartz** [comment]
PR here: https://github.com/apache/trafficserver/pull/5861

**Comment by ericcarlschwartz** [comment]
also, i don't know how to add labels but this is logging related

**Comment by randall** [comment]
#5863 and #5907 merged.
