### ISSUE TITLE
autest-site or autest-suite?

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#5871]
Now there is a directory `/tests/gold_tests/autest-site`.
IIRC, it used to be `autest-suite`.
A [test suite](https://en.wikipedia.org/wiki/Test_suite) is usually a collection of test cases. I guess it was not a very good name. As I can see, `autest-suite` is more like a collection of extensions.
I don't know what a `test site` is. Any explanation would be appreciated.
However, from source of [autest]( https://bitbucket.org/dragon512/reusable-gold-testing-system/src/b097479fe548aae44f3638980dcc88a48c26d951/src/autest/__main__.py#lines-41),  the option is `--autest-site` now.

It could be a typo. If yes, let's fix it. Probably good to rename it to `autest-ext` to avoid confusion.

**Comment by ywkaras** [comment]
@dragon512  ?

**Comment by SolidWallOfCode** [comment]
It's supposed to be "site". It corresponds to the Python / Perl directories like "site-lib". It is intended to contain AuTest support for the "site".
