### ISSUE TITLE
cashing problem ubuntu 18.04

### ISSUE THREAD

**Issue by saydulk** [apache/trafficserver#5874]
ATS not cache file as big as 1.5go into Ubuntu 18.04 LTS

**Comment by scw00** [comment]
Can you please share more information ?

**Comment by saydulk** [comment]
Hello, i was using this URL for setup

https://cwiki.apache.org/confluence/display/TS/Ubuntu

I did everything as that document says. But when i run ./configure && make it shows 
configure: error: Cannot find pcre library. Configure --with-pcre=DIR

![Screenshot from 2019-08-25 13-32-45](https://user-images.githubusercontent.com/1058663/63646986-dd85a800-c73c-11e9-8b2e-349b3f95e47c.png)

**Comment by scw00** [comment]
Hmm. You need to install the libraries before configure the ATS. the libraries list in https://github.com/apache/trafficserver/blob/master/README.
