### ISSUE TITLE
Hosting.config issue - not landing on proper volume

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#5886]
Set up a hosting.config with an entry for a test origin:
hostname=TESTORIGIN.net	volume=2

[Aug 27 22:24:21.359] [ET_NET 5] DEBUG: <CacheHosting.cc:523 (Init)> (cache_hosting) Host Record: 0x2b54780c9c98, Volume: 2, size: 268419072
[Aug 27 22:24:21.359] [ET_NET 5] DEBUG: <Cache.cc:1886 (build_vol_hash_table)> (cache_init) build_vol_hash_table index 0 mapped to 0 requested 32707 got 32707
[Aug 27 22:24:21.359] [ET_NET 5] DEBUG: <CacheHosting.cc:171 (NewEntry)> (cache_hosting) hostname: TESTORIGIN.net, host record: 0x2b54780c9c98
[Aug 27 22:24:21.359] [ET_NET 5] DEBUG: <CacheHosting.cc:523 (Init)> (cache_hosting) Host Record: 0x2b54780c9cd0, Volume: 2, size: 268419072

remap:
map / http://TESTORIGIN.net

However it still lands on the generic volume
[Aug 27 22:26:41.686] [ET_NET 33] DEBUG: <Cache.cc:3078 (key_to_vol)> (cache_hosting) Generic volume: 8c0c8838d for host: TESTORIGIN.net

**Comment by zwoop** [comment]
Which version(s) of ATS is this? Is this a regression, or something old?

**Comment by randall** [comment]
@ezelkow1 Is this with master or ATS 9?

**Comment by ezelkow1** [comment]
I cant remember at this point but I think it might have been both. @knutsel might have more info since he initially brought this to our attention and I just tested it and saw similar results. I think there might have been some changes since then to fix this within cachekey? @gtenev ?

**Comment by randall** [comment]
I'm going to make wild guess and say some form of #6193 will fix this. Prior to this fix, parent selection was wonky (with 9). And both these areas use `HostLookup`
