### ISSUE TITLE
Request for comments: unifdef TRACK_BUFFER_USER

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#5891]
IOBuffer has bunch of `#ifdef` of `TRACK_BUFFER_USER`. (52 in I_IOBuffer.h and P_IOBuffer.h)
This is a feature to track the location of the IOBuffer is allocated. 

IIUC, this macro is always defined even if it's release build. In other words, there're no way to disable this feature by configuration. And this has been defined since initial commit.

Could we remove this macro?

Definition:
https://github.com/apache/trafficserver/blob/0f86efc7678248c09f87ec8b99bc026456edc3f7/iocore/eventsystem/I_IOBuffer.h#L59-L61

E.g.
https://github.com/apache/trafficserver/blob/0f86efc7678248c09f87ec8b99bc026456edc3f7/iocore/eventsystem/I_IOBuffer.h#L1394-L1401

**Comment by oknet** [comment]
The `TRACK_BUFFER_USER` and `RES_PATH("memory/IOBuffer/")` are work together to track the memory allocation for IOBuffer.

You can dump the memory info by enabled the below 2 lines:
```
CONFIG proxy.config.dump_mem_info_frequency INT 30
CONFIG proxy.config.res_track_memory INT 1
```

With the `res_track_memory` set to 1, the allocation details of the IOBuffer will be displayed along with the freelist memory information. It is easy to find any IOBuffer leaks.

By copying the above code, we can use it to find memory leaks of other objects.

If you have too many types of trackers enabled, you will find that the memory allocation details are too long.

For example:

- TRACK_BUFFER_USER for IOBuffer tracking
- TRACK_INKCONT_USER for INKContinuation tracking
- etc ...

IMO, it is better to enable it with `--enable-debug`.

    `#if !defined(TRACK_BUFFER_USER) && defined(DEBUG)`

**Comment by masaori335** [comment]
Looks like we have some options here

1). always enable tracker regardless the value of `res_track_memory` (unifdef TRACK_BUFFER_USER)
  - pros: simplify code, but same to what we have now by removing dead code
  - cons: overhead of tracking the location in IOBuffer data structures (`const char *_location`)

2). add a configure option to enable this feature like (`--enable-track-memory`)
  - pros: no overhead in the IOBuffer data structures when this is disabled
  - cons: it's difficult to maintain IOBuffer data structures

3). enable this feature only with debug build
  - pros: no overhead with the release build
  - cons: 1). it's difficult to maintain IOBuffer data structures, and 2) we can't use this feature with the release build

**Comment by bryancall** [comment]
Merge changes in  #5906
