### ISSUE TITLE
QUIC error SSL

### ISSUE THREAD

**Issue by Jamboon-beurre** [apache/trafficserver#5910]
Hello,

I have an issue when running the ATS and trying to connect to the server using a browser, it get this error : ERR_SSL_PROTOCOL_ERROR.
In the debugs logs of the server attached, there seems to be a problem with the header.

When i run the traffic_quic client test, the connection seems to be working properly.

Would you have any idea  of what the problem may be ?

I run ATS 9.0.0 on Ubuntu 16.04.6.
Regards,

Nicolas

[serv_debug.txt](https://github.com/apache/trafficserver/files/3580328/serv_debug.txt)
[client_debug.txt](https://github.com/apache/trafficserver/files/3580333/client_debug.txt)

**Comment by maskit** [comment]
I think current major browsers still have not supported IETF QUIC. Which browser and version did you use? According to your server side log, ATS didn't talk QUIC at all on the two sessions.

**Comment by Jamboon-beurre** [comment]
I have the same error 'ERR_SSL_PROTOCOL_ERROR' on :

Google Chrome ver  76.0.3809.132
Chromium ver 78.0.3897.0 
Opera ver 63.0.3368.71

With Mozilla firefox ver 69.0 i have this error : SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by maskit** [comment]
Like I said, I think those browsers (at minimum, the official releases) don't support IETF QUIC yet. We don't have plans for supporting gQUIC.

For a bit more detail about gQUIC and IETF QUIC, please refer these slides below:
http://mile-high.video/files/mhv2019/pdf/day1/1_11_Swett.pdf

Please reopen / recreate issues if you have problems with IETF QUIC clients.
