### ISSUE TITLE
QUIC: Send ack even if cc window is 0

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#5923]
>7. Congestion Control
>QUIC hosts MUST NOT send packets if they would increase bytes_in_flight (defined in Appendix B.2) beyond the available congestion window, unless the packet is a probe packet sent after a PTO timer expires, as described in Section 6.2.

>bytes_in_flight:
The sum of the size in bytes of all sent packets that contain at least one ack-eliciting or PADDING frame, and have not been acked or declared lost. The size does not include IP or UDP overhead, but does include the QUIC header and AEAD overhead. Packets only containing ACK frames do not count towards bytes_in_flight to ensure congestion control does not impede congestion feedback.

**Comment by maskit** [comment]
Closing as we are dropping our own QUIC implementation.
