### ISSUE TITLE
Permanent memory leak

### ISSUE THREAD

**Issue by sitnikov** [apache/trafficserver#5931]
We use ats as caching server between frontend (nginx) and backend (nginx + php-fpm)
ats is constantly growing memory use, pls see attached pics from our monitoring

current ats ver 8.0.5 / CentOS Linux release 7.6.1810

![month graph](https://si.infonet.ee/temp/ats-memory-month.png)
![week graph](https://si.infonet.ee/temp/ats-memory-week.png)

**Comment by scw00** [comment]
How much ram cache memory did you use ?  How big is your fragments size ? Can you share your records.config and storage.config ?

**Comment by sitnikov** [comment]
CONFIG proxy.config.cache.ram_cache.size INT -1
CONFIG proxy.config.cache.ram_cache_cutoff INT 419430

[storage.config.txt](https://github.com/apache/trafficserver/files/3629534/storage.config.txt)
[records.config.txt](https://github.com/apache/trafficserver/files/3629535/records.config.txt)

**Comment by zwoop** [comment]
Setting RAM cache to -1 might be a bad idea if you have a very large disk size. It will then use RAM based on a percentage of disk space. We strongly encourage you to pick a RAM cache size that's fixed, which you know fits in your system. 

Are there any plugins in use? Anything else that might help identify the leak? Did you try sending the "kill -USR1" signal to the running traffic_server? Doing that with some delay (say 24h) can help give an indication where the memory is growing (assuming it's not the RAM cache, as above).

**Comment by sitnikov** [comment]
Current use proxy.config.cache.ram_cache.size = 25769803776
![image](https://user-images.githubusercontent.com/140812/66103141-7968c600-e5bd-11e9-94ed-501969c4262c.png)

```
[root@silo sitnikov]# ps axv| grep -E 'traffic_server|PID'
  PID TTY      STAT   TIME  MAJFL   TRS   DRS   RSS %MEM COMMAND
 1965 ?        Sl   1693:31     5  4186 53989849 47989868 72.9 /opt/ats/bin/traffic_server 
```

parent.config
dest_domain=.  parent="x.x.x.x:8080"   parent_is_proxy=false round_robin=strict

**Comment by bryancall** [comment]
If this is still an issue please reopen.
