### ISSUE TITLE
redirect is using /etc/trafficserver/body_factory/default/default as body

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#5936]
remap.config: redirect http://arrakis.rhsoft.net https://arrakis.rhsoft.net

why in the world ships ATS for redirects /etc/trafficserver/body_factory/default/default instead no body at all or a generated page with a link if the client for whatever reason don't follow the redirect?

[harry@srv-rhsoft:~]$ curl --head http://www.rhsoft.net/
HTTP/1.1 301 Redirect
Date: Fri, 13 Sep 2019 13:57:07 GMT
Connection: keep-alive
Cache-Control: no-store
Location: https://www.rhsoft.net/
Content-Type: text/html
Content-Language: en
Content-Length: 780

[harry@srv-rhsoft:~]$ curl http://www.rhsoft.net/ gives the content of /etc/trafficserver/body_factory/default/default which is plain wrong, a redirect is no error

**Comment by zwoop** [comment]
Which version(s) are you seeing this in? Did the behavior change at some point ?

**Comment by thelounge-zz** [comment]
8.0.1 since all follow up vesion are crashing randomly (https://github.com/apache/trafficserver/issues/4921) , dunno when this started, i just realized it randomly when calling curl without https

**Comment by thelounge-zz** [comment]
to make it clear: it should look like that (301 versus 302 don't really matter)

 <IfModule mod_rewrite.c>
  RewriteEngine          on
  RewriteCond            %{HTTPS} off
  RewriteCond            %{CONN_REMOTE_ADDR} !^10\.0\.0\.4
  RewriteCond            %{CONN_REMOTE_ADDR} !^10\.0\.0\.103
  RewriteCond            %{REQUEST_URI} !^\/\.well\-known\/acme\-challenge\/
  RewriteRule            (.*) https://%{HTTP_HOST}%{REQUEST_URI}
 </IfModule>

[harry@srv-rhsoft:~]$ curl http://local.rhsoft.net/
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://local.rhsoft.net/">here</a>.</p>
</body></html>

**Comment by zwoop** [comment]
Hmmm, not sure I'm understanding this, for sure I can't reproduce it:

```
leif@sleipnir ~/apache/ats-7.1.x ±7.1.x » curl -D - -s https://docs.trafficserver.apache.org/
HTTP/1.1 302 Found
Date: Wed, 20 Nov 2019 02:39:21 GMT
Server: ATS/9.0.0
Location: https://docs.trafficserver.apache.org/en/8.0.x/
Content-Length: 231
Content-Type: text/html; charset=iso-8859-1
Age: 0
Connection: keep-alive
Strict-Transport-Security: max-age=17280000
Via: http/1.1 traffic_server (ApacheTrafficServer/9.0.0 [cMsSf ])

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://docs.trafficserver.apache.org/en/8.0.x/">here</a>.</p>
</body></html>
```

Are you perhaps running into the issue of the configuration for proxy.config.body_factory.template_sets_dir changing between ATS 7 - > 8 ?

**Comment by thelounge-zz** [comment]
not touched that folder since 2012 and only recognized it by random when curl a URL with a https redirect and my records.config dates back to 2012 too

CONFIG proxy.config.body_factory.template_sets_dir STRING /etc/trafficserver/body_factory

[root@proxy:/etc/trafficserver/body_factory/default]$ ls
total 96K
-rw-rw-r-- 1 root ats  791 2012-08-14 12:28 access#denied
-rw-rw-r-- 1 root ats  822 2012-08-14 12:28 access#proxy_auth_required
-rw-rw-r-- 1 root ats  975 2012-08-14 12:28 access#redirect_url
-rw-rw-r-- 1 root ats  848 2012-08-14 12:28 access#ssl_forbidden
-rw-rw-r-- 1 root ats  926 2012-08-14 12:28 cache#not_in_cache
-rw-rw-r-- 1 root ats  788 2012-08-14 12:28 cache#read_error
-rw-rw-r-- 1 root ats  830 2012-08-14 12:28 congestion#retryAfter
-rw-rw-r-- 1 root ats  998 2012-08-14 12:28 connect#dns_failed
-rw-rw-r-- 1 root ats  825 2012-08-14 12:28 connect#failed_connect
-rw-rw-r-- 1 root ats  903 2012-08-14 12:28 connect#hangup
-rw-rw-r-- 1 root ats  783 2012-08-14 12:28 default
-rw-rw-r-- 1 root ats 1.1K 2012-08-14 12:28 interception#no_host
-rw-rw-r-- 1 root ats  883 2012-08-14 12:28 redirect#moved_temporarily
-rw-rw-r-- 1 root ats  930 2012-08-14 12:28 request#cycle_detected
-rw-rw-r-- 1 root ats  868 2012-08-14 12:28 request#no_content_length
-rw-rw-r-- 1 root ats 1.1K 2012-08-14 12:28 request#no_host
-rw-rw-r-- 1 root ats  868 2012-08-14 12:28 request#scheme_unsupported
-rw-rw-r-- 1 root ats  842 2012-08-14 12:28 request#syntax_error
-rw-rw-r-- 1 root ats  843 2012-08-14 12:28 response#bad_response
-rw-rw-r-- 1 root ats  901 2012-08-14 12:28 response#bad_version
-rw-rw-r-- 1 root ats  810 2012-08-14 12:28 timeout#activity
-rw-rw-r-- 1 root ats  833 2012-08-14 12:28 timeout#inactivity
-rw-rw-r-- 1 root ats  871 2012-08-14 12:28 transcoding#unsupported
-rw-rw-r-- 1 root ats 2.4K 2012-08-14 12:28 urlrouting#no_mapping
[root@proxy:/etc/trafficserver/body_factory/default]$

**Comment by bryancall** [comment]
@thelounge-zz It looks like you are missing:
`-rw-r--r--. 1 bcall bcall  299 Aug 30 16:32 redirect#moved_permanently`

**Comment by bryancall** [comment]
If this is still an issue please reopen.
