### ISSUE TITLE
ATS 7 vs ATS 9 profiling in production

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#5941]
Samples: 864K of event 'cycles:ppp', Event count (approx.): 251702384267
Overhead  Shared Object                                  Symbol
   1.37%  libcrypto.so.1.1                               [.] DES_encrypt2
   1.26%  libjemalloc.so.2                               [.] free
   1.16%  [ip_tables]                                    [k] ipt_do_table
   1.14%  traffic_server                                 [.] UrlRewrite::_regexMappingLookup
   1.13%  [kernel]                                       [k] smp_call_function_many
   0.97%  libc-2.17.so                                   [.] __memcpy_ssse3
   0.72%  libperl.so                                     [.] Perl_hv_common
   0.72%  [i40e]                                         [k] i40e_clean_rx_irq
   0.70%  [i40e]                                         [k] i40e_napi_poll
   0.68%  [kernel]                                       [k] tcp_ack
   0.67%  [kernel]                                       [k] menu_select
   0.62%  [kernel]                                       [k] system_call
   0.61%  libperl.so                                     [.] Perl_runops_standard
   0.56%  [kernel]                                       [k] _raw_spin_lock
   0.54%  libjemalloc.so.2                               [.] malloc
   0.54%  [i40e]                                         [k] i40e_xmit_frame_ring
   0.50%  [kernel]                                       [k] cpuidle_enter_state

Samples: 199K of event 'cycles:ppp', Event count (approx.): 59217730632
Overhead  Shared Object                                  Symbol
   2.28%  traffic_server                                 [.] UrlRewrite::_regexMappingLookup
   1.62%  libjemalloc.so.2                               [.] free
   1.48%  libz.so.1.2.7                                  [.] 0x0000000000002d11
   1.15%  libc-2.17.so                                   [.] __memcpy_ssse3
   1.08%  libcrypto.so.1.1                               [.] sha256_block_data_order_avx2
   1.08%  traffic_server                                 [.] IntrusiveHashMap<Http1ServerSession::FQDNLinkage>::insert
   0.97%  libjemalloc.so.2                               [.] malloc
   0.86%  traffic_server                                 [.] NetHandler::manage_active_queue
   0.84%  libcrypto.so.1.1                               [.] fe_mul
   0.83%  traffic_server                                 [.] ServerSessionPool::acquireSession
   0.83%  traffic_server                                 [.] InactivityCop::check_inactivity
   0.73%  libcrypto.so.1.1                               [.] bn_sqr8x_internal
   0.71%  libcrypto.so.1.1                               [.] __ecp_nistz256_mul_montq
   0.64%  traffic_server                                 [.] IntrusiveHashMap<Http1ServerSession::IPLinkage>::insert
   0.63%  libcrypto.so.1.1                               [.] x25519_fe51_sqr
   0.63%  libc-2.17.so                                   [.] __strncmp_sse42
   0.62%  libcrypto.so.1.1                               [.] ChaCha20_8x
   0.60%  [kernel]                                       [k] menu_select
   0.56%  libcrypto.so.1.1                               [.] __ecp_nistz256_sqr_montq
   0.56%  traffic_server                                 [.] huffman_decode
   0.52%  [kernel]                                       [k] system_call
   0.52%  [ip_tables]                                    [k] ipt_do_table
   0.50%  [i40e]                                         [k] i40e_napi_poll

**Comment by shinrich** [comment]
I assume the first one is from ATS 7 and the second is from ATS 9?
