### ISSUE TITLE
no_dns_just_forward_to_parent not work for Hit-Stale update.

### ISSUE THREAD

**Issue by pengzhixi** [apache/trafficserver#5946]
With no_dns_just_forward_to_parent enabled, the `HandleCacheOpenReadHitFreshness` is always try to update the Hit-Stale objects by OSDNSLookup.
By comparing with the `HandleCacheOpenReadMiss`, it will call the `find_server_and_update_current_info` to update the server info and send the request via parent proxy.

**Comment by bryancall** [comment]
This looks to be a duplicate for: #2376
