### ISSUE TITLE
Buffering post responses before sending them to origin servers

### ISSUE THREAD

**Issue by jvgutierrez** [apache/trafficserver#6018]
**EDIT:** The behaviour described below is produced because ATS isn't buffering the requests and receiving them completely before sending them to the origin servers.

We've observed the following behaviour in our ATS/8.0.5 instances (and I can reproduce it locally with master as well). Sometimes aborted transactions are reaching the origin servers, I've been able to reproduce this locally with HTTP/1.1 and HTTP/.2 using the following curl CMDs:
```
# http/1.1
timeout 5 curl --http1.1 -X POST -d "test" -H "Content-Length: 10" https//127.0.0.1:3129/post
# http/2
curl -X POST -d "test" -H "Content-Length: 10" https//127.0.0.1:3129/post
```

Setting a really small slowlog threshold (1ms) we observe the following milestones:
```
# http/1.1
[ET_NET 1] ERROR: [20] Slow Request: client_ip: 192.168.16.1:43428 protocol: http url: http://ats_httpbin_1:80/delay/1?random=29193 status: 0 unique id:  redirection_tries: 0 bytes: 0 fd: -1 client state: 0 server state: 0 ua_begin: 0.000 ua_first_read: 0.000 ua_read_header_done: 0.000 cache_open_read_begin: -0.001 cache_open_read_end: -0.001 dns_lookup_begin: 0.053 dns_lookup_end: 0.053 server_connect: 0.053 server_connect_end: 0.069 server_first_read: -0.001 server_read_header_done: -0.001 server_close: -0.001 ua_write: -0.001 ua_close: 4.959 sm_finish: 4.959 plugin_active: 0.002 plugin_total: 0.002
# http/2
{0x2b360f0f7700} ERROR: [40] Slow Request: client_ip: 192.168.16.1:49532 protocol: http/2 url: http://ats_httpbin_1:80/delay/1 status: 0 unique id:  redirection_tries: 0 bytes: 0 fd: 39 client state: 0 server state: 0 ua_begin: 0.000 ua_first_read: 0.000 ua_read_header_done: 0.000 cache_open_read_begin: -0.001 cache_open_read_end: -0.001 dns_lookup_begin: 0.000 dns_lookup_end: 0.000 server_connect: 0.000 server_connect_end: 0.002 server_first_read: -0.001 server_read_header_done: -0.001 server_close: -0.001 ua_write: -0.001 ua_close: 0.003 sm_finish: 0.003 plugin_active: 0.000 plugin_total: 0.000
```

I assume that what we are seeing in our production environment is caused by clients with poor connectivity. What's bugging me the most is the fact that ATS sometimes blocks this requests and other times reach the origin servers. What is the expected behaviour here?

**Comment by jvgutierrez** [comment]
[Apparently](https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html#proxy-config-http-send-100-continue-response) setting `proxy.config.http.send_100_continue_response` to `0` (the default value) should force ATS to buffer the request till the POST body is received and then send the request to the origin server. From the observed behaviour, this is not happening. Also the old buffer_upload plugin has been removed as part of #5395. What's the current way of buffering POST requests to stop "incomplete" requests from reaching origin servers?

**Comment by jvgutierrez** [comment]
Answering my own question, it looks like for ATS <= 8.x the buffer_upload plugin can be used. The plugin allows to buffer requests either on memory or on disk and set a maximum request size to be buffered on memory, but if on disk buffering is enabled, it doesn't matter the size of the request body, it will always use the disk for buffering purposes. This can result on a performance penalty for small requests.
For ATS >= 8.x `proxy.config.http.request_buffer_enabled` can be used after cherry-picking #6024. This option lacks disk buffering support so it's only valid on environments where `proxy.config.http.post_copy_size` can be set to a rather small value due to obvious security reasons. Also if the POST body size exceeds `proxy.config.http.post_copy_size`, a 403 is returned and the request is rejected even if `proxy.config.http.max_post_size` is set to `0`

**Comment by PSUdaemon** [comment]
@jvgutierrez can this issue be closed now?

**Comment by bryancall** [comment]
I am going to close this.  If you want to buffer a POST you should create a plugin.  We have done this ourselves before and can provide an example plugin.
