### ISSUE TITLE
assert error if the post body is sent with the request header with proxy.config.http.request_buffer_enabled

### ISSUE THREAD

**Issue by zizhong** [apache/trafficserver#6022]
>... triggers a ATS crash upon an innocent POST request like curl --http1.1 -X POST --data "test" http://127.0.0.1:3128/post -o /dev/null -v on https://github.com/apache/trafficserver/blob/master/proxy/http/HttpTunnel.cc#L510
proxy/http/HttpTunnel.cc:510
  ink_release_assert(0);

From the traffic server slack channel.

**Comment by jvgutierrez** [comment]
Thanks for the fix, `curl --http1.1 -X POST --data "test" http://127.0.0.1:3128/post` no longer crashes ATS but I'm seeing a weird behaviour with the requests described on #6018.
For debugging purposes I've set the slow log threshold to 1ms `proxy.config.http.slow.log.threshold: 1`.
A successful request like `curl --http1.1 -X POST --data "test" http://127.0.0.1:3128/post` gets logged as expected:
```
Slow Request: client_ip: 192.168.16.1:39530 protocol: http url: http://ats_httpbin_1:80/post status: 200 unique id:  redirection_tries: 0 bytes: 601 fd: 36 client state: 0 server state: 0 ua_begin: 0.000 ua_first_read: 0.000 ua_read_header_done: 0.000 cache_open_read_begin: -0.001 cache_open_read_end: -0.001 dns_lookup_begin: 0.000 dns_lookup_end: 0.000 server_connect: 0.000 server_connect_end: 0.008 server_first_read: 0.024 server_read_header_done: 0.024 server_close: 0.029 ua_write: 0.029 ua_close: 0.029 sm_finish: 0.029 plugin_active: 0.000 plugin_total: 0.000
```
but a faulty one like `timeout 5 curl --http1.1 -X POST -d "test" -H "Content-Length: 10" http://127.0.0.1:3129/post` doesn't get logged at all and it should be definitely logged taking into account that the client socket stays open for ~5 secs

**Comment by zizhong** [comment]
Thanks for reporting the issue. I'll look into that later.

**Comment by zizhong** [comment]
The original issue is fixed
