### ISSUE TITLE
QUIC compile

### ISSUE THREAD

**Issue by MarcoStuurman** [apache/trafficserver#6030]
Hi,

I tried to compile ATS with HTTP/3 QUIC support. I can't figure out why the configure says:

> checking whether APIs for QUIC are available... no

and when forcing it to build QUIC, the following error pops up:

```
QUICTLS_openssl.cc: In function ‘void log_secret(SSL*, int, const unsigned char*, size_t)’:
QUICTLS_openssl.cc:165:10: error: ‘SSL_KEY_CLIENT_EARLY_TRAFFIC’ was not declared in this scope
     case SSL_KEY_CLIENT_EARLY_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
QUICTLS_openssl.cc:165:10: note: suggested alternative: ‘SSL_R_CLIENTHELLO_TLSEXT’
     case SSL_KEY_CLIENT_EARLY_TRAFFIC:
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
          SSL_R_CLIENTHELLO_TLSEXT

```

I've compiled and installed https://github.com/tatsuhiro-t/openssl/tree/openssl-quic after that configured with  ./configure  --with-openssl=/root/opensslats/openssl/build --enable-debug

Anyone an idea to help me a step further?

**Comment by maskit** [comment]
The OpenSSL repo is correct, but I think you are on different branch. Can you rebuild OpenSSL on quic-draft-22 branch?

**Comment by MarcoStuurman** [comment]
I was using -23, thank you!

**Comment by maskit** [comment]
It's in a bit complicated state. ATS supports QUIC draft-23, but we need to use quic-draft-22 for now, because -23 has different APIs. We are going to catchup the API change but it takes time a little.
