### ISSUE TITLE
ATS 8.x appends DNS servers from /etc/resolv.conf by default.  Changed from ATS vers.  <8.x

### ISSUE THREAD

**Issue by pipps** [apache/trafficserver#6040]
ATS 8.x appends DNS servers from /etc/resolv.conf by default.  Changed from ATS vers.  <8.x
This should be called out as the new default behavior in the documentation. Listing creating a bogus file as a work round.

**Comment by zwoop** [comment]
I think this would need to go into the release notes for 8.0.x as well.

**Comment by abh** [comment]
Why is having it work this way a feature?  It's at best surprising and hard to see why anyone would want "both" like this.
