### ISSUE TITLE
Problem with ATS7.x using a parent proxy 

### ISSUE THREAD

**Issue by tatsuaki96** [apache/trafficserver#6091]
IOS devices cannot access to https website when ATS7.x uses parent proxy.

Windows PC --> ATS7.x --> Squid --> Website(HTTPS) : The webpage showed correctly.
Windows PC --> ATS7.x --> Squid --> Website(HTTP) : The webpage showed correctly.
iOS devices --> ATS7.x --> Squid --> Website(HTTP) : The webpage showed correctly.
iOS devices --> ATS7.x --> Squid --> Website(HTTPS) : The webpage does not showed.

**Comment by randall** [comment]
@tatsuaki96 Do you have any details as to the errors you are seeing ?

**Comment by tatsuaki96** [comment]
The browser just times out without displaying any errors.
I also looked into the ATS's logs, but it seems that does not contain any errors.
So I enabled debug mode and checked the debug logs, then I found differences in it between iPad and others.
Other than iPad, these has a port number (443) in the Host header in the HTTP request, but iPad does not have it.
I guess it affects the behavior of ATS.


iPad:

+++++++++ Incoming Request +++++++++
-- State Machine Id: 67882
CONNECT www.titsol.co.jp:443 HTTP/1.1
Host: www.titsol.co.jp
User-Agent: Mozilla/5.0 (iPad; CPU OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1
Connection: keep-alive
Proxy-Connection: keep-alive

+++++++++ Proxy's Request +++++++++
-- State Machine Id: 67882
CONNECT www.titsol.co.jp:443 HTTP/1.1
Host: www.titsol.co.jp
User-Agent: Mozilla/5.0 (iPad; CPU OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1
X-Forwarded-For: 192.168.29.235
Via: http/1.1 localhost[7535a247-a785-4e91-b5fc-27e9549fac4c] (ApacheTrafficServer/7.1.2)


Others(Windows - Firefox):

+++++++++ Incoming Request +++++++++
-- State Machine Id: 67974
CONNECT www.titsol.co.jp:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
Proxy-Connection: keep-alive
Connection: keep-alive
Host: www.titsol.co.jp:443

+++++++++ Proxy's Request +++++++++
-- State Machine Id: 67974
CONNECT www.titsol.co.jp:443 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
Host: www.titsol.co.jp:443
X-Forwarded-For: 192.168.69.95
Via: http/1.1 localhost[7535a247-a785-4e91-b5fc-27e9549fac4c] (ApacheTrafficServer/7.1.2)

**Comment by randall** [comment]
This might be https://github.com/apache/trafficserver/issues/5156 (fixed with #5185). You might want to try cherry-picking 031f321be814c71047a700b4b8c507382d51f709

**Comment by tatsuaki96** [comment]
@randal You are quite right!
As mentioned #5156, the ATS send response "Transfer-Encoding: chunked", and then client would not send the ssl handshake data after the response.
I also saw that the issue does not hapepen on ATS 9.0. Thank you very much.

**Comment by devZer0** [comment]
https://github.com/apache/trafficserver/issues/2861
