### ISSUE TITLE
Very poor performance when diags.debug is enabled

### ISSUE THREAD

**Issue by calavera** [apache/trafficserver#6150]
We've ran some benchmarks and the difference between having diags.debug enabled or not is abysmal. You can easily reproduce, the numbers in the screenshot below are from running h2load on my local machine:

`h2load --h1 -t 40 -D 60 -n 10000 -c 40 http://localhost`

![Screenshot from 2019-11-06 15-30-07](https://user-images.githubusercontent.com/1050/68348782-cace0e80-00af-11ea-9bf3-1b22f12053de.png)

Being able to see debug logs is critical in trace issues in production, we use them extensively, and this drop in performance is a big issue for us:

```
finished in 60.03s, 6488.28 req/s, 3.66MB/s 
drops to 
finished in 60.06s, 19.47 req/s, 11.16KB/s
```

**Comment by ywkaras** [comment]
I'm planning to put up a PR in the next few weeks to improve this.

**Comment by ywkaras** [comment]
Closing this.  Typically, if enough tracing is enabled to be useful, it will inevitably be slow simply due to the added output overhead.
