### ISSUE TITLE
ATS 7.1.8: traffic_manager crashed when stop the service

### ISSUE THREAD

**Issue by lexisen** [apache/trafficserver#6161]
![image](https://user-images.githubusercontent.com/17465233/68568869-b6b35400-0497-11ea-8d41-71d39e0fd00e.png)

**### diags.log**
[Nov  9 13:53:44.985] Server {0xffff88f31010} NOTE: ssl_multicert.config done reloading!
[Nov  9 13:53:44.997] Server {0xffff88f31010} NOTE: traffic server running
[Nov  9 13:53:45.048] Server {0xffff870d81c0} NOTE: cache enabled
**[Nov  9 13:57:00.275] Server {0xffff883ee1c0} ERROR: last system error 32: Broken pipe**
[Nov  9 13:57:00.275] Server {0xffff883ee1c0} FATAL: [ProcessManager::processSignalQueue] Error writing message!
[Nov  9 13:57:03.342] Server {0xffffbcc36010} STATUS: opened /var/share/oss/U2020-1/APINotifyProxyService/ts/var/log/trafficserver/diags.log
[Nov  9 13:57:03.342] Server {0xffffbcc36010} NOTE: updated diags config
[Nov  9 13:57:03.343] Server {0xffffbcc36010} WARNING: connect_attempts_rr_retries (1) is greater than connect_attempts_max_retries (0), this means requests will never redispatch to another server
[Nov  9 13:57:03.345] Server {0xffffbcc36010} NOTE: cache clustering disabled
[Nov  9 13:57:03.351] Server {0xffffbcc36010} NOTE: ip_allow.config updated, reloading
[Nov  9 13:57:03.356] Server {0xffffbb0e31c0} WARNING: bad nameserver config, fallback to loopback
[Nov  9 13:57:03.357] Server {0xffffbcc36010} NOTE: cache clustering disabled
[Nov  9 13:57:03.359] Server {0xffffbcc36010} NOTE: logging initialized[3], logging_mode = 3
[Nov  9 13:57:03.359] Server {0xffffbcc36010} NOTE: loading plugin '/var/share/oss/U2020-1/APINotifyProxyService/ts/plugins/forward-blacklist.so'
[Nov  9 13:57:03.360] Server {0xffffbcc36010} NOTE: loading SSL certificate configuration from /var/share/oss/U2020-1/APINotifyProxyService/ts/etc/trafficserver/ssl_multicert.config
[Nov  9 13:57:03.360] Server {0xffffbcc36010} NOTE: ssl_multicert.config done reloading!
[Nov  9 13:57:03.373] Server {0xffffbcc36010} NOTE: traffic server running
[Nov  9 13:57:03.421] Server {0xffffbaddd1c0} NOTE: cache enabled

**Comment by bryancall** [comment]
If this is still an issue please reopen.
