### ISSUE TITLE
The remap_stats plugin is causing traffic server to crash.

### ISSUE THREAD

**Issue by jrushford** [apache/trafficserver#6177]
The remap_stats plugin is causing traffic server to crash.  Found this while load testing a build of traffic server from master with remap_stats enabled in plugin.config.

`Fatal: ../../include/tscore/BufferWriter.h:350: failed assertion
Traffic Server 10.0.0 Nov 15 2019 16:24:43 ipcdn-cache-34.cdnlab.comcast.net
traffic_server: using root directory '/opt/trafficserver'
traffic_server: received signal 6 (Aborted)
traffic_server - STACK TRACE:
/opt/trafficserver/bin/traffic_server(crash_logger_invoke(int, siginfo_t*, void*)+0xc3)[0x63935b]
/lib64/libpthread.so.0(+0xf5d0)[0x2b83ad4ef5d0]
/lib64/libc.so.6(gsignal+0x37)[0x2b83ae1552c7]
/lib64/libc.so.6(abort+0x148)[0x2b83ae1569b8]
/opt/trafficserver/lib/libtscore.so.10(ink_warning(char const*, ...)+0x0)[0x2b83abe3bb0c]
/opt/trafficserver/lib/libtscore.so.10(ats_base64_encode(unsigned char const*, unsigned long, char*, unsigned long, unsigned long*)+0x0)[0x2b83abe38b3f]
/opt/trafficserver/bin/traffic_server(ts::FixedBufferWriter::reduce(unsigned long)+0x3b)[0x7caf5b]
/opt/trafficserver/libexec/trafficserver/remap_stats.so(+0xccea)[0x2b83dfae4cea]
/opt/trafficserver/libexec/trafficserver/remap_stats.so(+0xcf68)[0x2b83dfae4f68]
/opt/trafficserver/bin/traffic_server(INKContInternal::handle_event(int, void*)+0x13a)[0x6478a0]
/opt/trafficserver/bin/traffic_server(Continuation::handleEvent(int, void*)+0xc9)[0x63d6c1]
/opt/trafficserver/bin/traffic_server(APIHook::invoke(int, void*) const+0xe9)[0x648271]
/opt/trafficserver/bin/traffic_server(HttpSM::state_api_callout(int, void*)+0x922)[0x6c6e6c]
/opt/trafficserver/bin/traffic_server(HttpSM::do_api_callout_internal()+0x218)[0x6d69ce]
/opt/trafficserver/bin/traffic_server(HttpSM::do_api_callout()+0x27)[0x6e6ffd]
/opt/trafficserver/bin/traffic_server(HttpSM::kill_this()+0x249)[0x6dd303]
/opt/trafficserver/bin/traffic_server(HttpSM::main_handler(int, void*)+0x388)[0x6cc09c]
/opt/trafficserver/bin/traffic_server(Continuation::handleEvent(int, void*)+0xc9)[0x63d6c1]
/opt/trafficserver/bin/traffic_server(HttpTunnel::main_handler(int, void*)+0x1c4)[0x72da22]
/opt/trafficserver/bin/traffic_server(Continuation::handleEvent(int, void*)+0xc9)[0x63d6c1]
/opt/trafficserver/bin/traffic_server[0x8f60aa]
/opt/trafficserver/bin/traffic_server[0x8f62e3]
/opt/trafficserver/bin/traffic_server(write_to_net_io(NetHandler*, UnixNetVConnection*, EThread*)+0x7ce)[0x8f7427]
/opt/trafficserver/bin/traffic_server(write_to_net(NetHandler*, UnixNetVConnection*, EThread*)+0x81)[0x8f6c56]
/opt/trafficserver/bin/traffic_server(NetHandler::process_ready_list()+0x16a)[0x8ece84]
/opt/trafficserver/bin/traffic_server(NetHandler::waitForActivity(long)+0x614)[0x8ed5c8]
/opt/trafficserver/bin/traffic_server(EThread::execute_regular()+0x3d2)[0x928192]
/opt/trafficserver/bin/traffic_server(EThread::execute()+0x107)[0x928393]
/opt/trafficserver/bin/traffic_server[0x926ee7]
/lib64/libpthread.so.0(+0x7dd5)[0x2b83ad4e7dd5]
/lib64/libc.so.6(clone+0x6d)[0x2b83ae21d02d]`

**Comment by SolidWallOfCode** [comment]
Fixed by #6181.
