### ISSUE TITLE
ATS9: performance regression

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#6178]
Just synced our internal test branch with the open source 9.0.x branch.  When I installed the resulting package on our canary production box, the average response latency more than doubled from around 120ms to over 450ms.

Running my python analysis script over squid.log files with the previous build and the new build show that the change is in HTTP/2 transactions.

Previous build H2 stats
```
total 1203448 entrys 50%=27 80%=146 90%=304 95%=464 99%=1054 max=%858135
```
New build H2 stats
```
total 561087 entrys 50%=26 80%=193 90%=417 95%=1670 99%=9980 max=%857883
```

If I revert  @masaori335's commit 2baa388c3e3cb3ff71c468c8b0b4c68d8a0320fe, then the average latency goes back down.

**Comment by shinrich** [comment]
Working on the HTTP/2 support for http-replay, I think I see the cause of the problem.

When working with master, replaying a 304 response was stalling.  The header would come back right away, but the EOS bit was not set.  A little later after the inactivity timeout triggered, a DATA frame with the EOS bit set was sent.

Reverting this commit from master and trying again, the response was sent and the stream was closed in a timely manner.  However, even in this case the EOS bit was not set in the HEADER frame.  Rather an empty DATA frame with the EOS bit set was sent immediately.

I think we should be checking the staus code in Http2ConnectionState:send_headers_frame and asset the EOS bit in the header if that code cannot return data.

I must head out for a meeting, but I will work on some options here later this afternoon.

**Comment by shinrich** [comment]
Unfortunately, I just installed a test build on our canary production box with the PR #6196 patch applied, and the average response time is still inflated.  A little better than without the patch, but not as good as reverting the Dechunk commit.  370ms 9.0.x plus this EOS path vs 100-200ms with the Dechunk commit reverted.

**Comment by masaori335** [comment]
It looks like #6196 only works for HEAD and CONNECT requests. `is_response_body_precluded(HTTPStatus status_code)` might work for GET IMS request.
However, IMO, we should not rely on the HTTP method nor status code for EOS. Let me think of another approach.

**Comment by masaori335** [comment]
@shinrich Could you try #6199? In these header-only response cases, the upstream layer of H2 set the `write_vio.nbytes`, so when `write_vio.ntodo()` becomes 0, the stream could be set END_STREAM flag. ( In this 304 response case, `HttpTunnel::producer_run()` set it )
This is the same way of what HTTP/1.1 is doing.

**Comment by shinrich** [comment]
#6196 does check both the status code and the method.  In fact in my test case, the data was a 304 response code.
```
is_response_body_precluded(resp_header->status_get(), stream->get_method_wksidx()
```

I'll check out #6199 too.  And looking at the EXPECT problem,
