### ISSUE TITLE
assert abort in doc->magic == DOC_MAGIC

### ISSUE THREAD

**Issue by zhangqiang-01** [apache/trafficserver#6230]
I had a problem using 7.1.1

Fatal: Cache.cc:2350: failed assertion `doc->magic == DOC_MAGIC`
traffic_server: using root directory '/usr'
traffic_server: received signal 6 (Aborted)
traffic_server - STACK TRACE:
/usr/bin/traffic_server(_Z19crash_logger_invokeiP9siginfo_tPv+0x9a)[0x556ff911d1d1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x2b5ca1975890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x2b5ca25de067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x2b5ca25df448]
/usr/lib/trafficserver/libtsutil.so.7(_Z11ink_warningPKcz+0x0)[0x2b5ca0626be6]
/usr/lib/trafficserver/libtsutil.so.7(_Z17ats_base64_encodePKhmPcmPm+0x0)[0x2b5ca062517e]
/usr/bin/traffic_server(_ZN7CacheVC14handleReadDoneEiP5Event+0x48f)[0x556ff930afd5]
/usr/bin/traffic_server(_ZN7EThread13process_eventEP5Eventi+0x363)[0x556ff93a8ffd]
/usr/bin/traffic_server(_ZN7EThread7executeEv+0x634)[0x556ff93a9b9e]
/usr/bin/traffic_server(+0x34d7ad)[0x556ff93a87ad]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8064)[0x2b5ca196e064]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x2b5ca269163d]

**Comment by hankai17** [comment]
Maybe not clear disk when upgrade ats

**Comment by zhangqiang-01** [comment]
It's impossible， We didn't upgrade ats.

**Comment by zhangqiang-01** [comment]
It's really our problem. The disk has been formatted.
