### ISSUE TITLE
Remove INKUDPXX api

### ISSUE THREAD

**Issue by scw00** [apache/trafficserver#6245]
If nobody use the these APIs, we can remove this or update it to TS API.

https://github.com/apache/trafficserver/blob/080889f68701c994826e2e5781d2564b4ed6733d/include/ts/InkAPIPrivateIOCore.h#L138-L198

**Comment by sudheerv** [comment]
Worth sending an email to dev@

**Comment by alokrahul513** [comment]
Hi, I want to work on this issue. How to get started?

**Comment by abhi-jeet-kumar** [comment]
has this been fixed?

**Comment by bryancall** [comment]
All the INKUDP* APIs have been removed for the 10.0.0 release
