### ISSUE TITLE
Custom proxy.config.output.logfile has no effect

### ISSUE THREAD

**Issue by xeron** [apache/trafficserver#6249]
trafficserver version: 8.0.5.
OS: Amazon Linux v1 (CentOS 6 based)

Related config parts:

```
CONFIG proxy.config.log.logfile_dir STRING /mnt/logs/trafficserver
CONFIG proxy.config.output.logfile STRING /mnt/logs/trafficserver/traffic.out
```

Actual files:
```
# ls -l /mnt/logs/trafficserver/
total 56
-rw-r--r-- 1 ats ats  6522 Dec 10 08:44 access.log
-rw-r--r-- 1 ats ats 19891 Dec 10 09:04 diags.log
-rw-r--r-- 1 ats ats 21905 Dec 10 09:04 manager.log

# ls -l /opt/trafficserver/var/log/trafficserver/
total 8
-rw-r--r-- 1 root root 5844 Dec 10 09:04 traffic.out
```

**Comment by xeron** [comment]
Other issues I noticed which are kind of related:

* The following options have no effect on diags/manager/error logs and only affect `access.log`:
```
CONFIG proxy.config.log.rolling_enabled INT 3
CONFIG proxy.config.log.rolling_offset_hr INT 3
CONFIG proxy.config.log.rolling_interval_sec INT 86400
CONFIG proxy.config.log.rolling_size_mb INT 1000
CONFIG proxy.config.log.auto_delete_rolled_files INT 1
```

* The following options have no effect on `traffic.out`:
```
CONFIG proxy.config.output.logfile.rolling_enabled INT 3
CONFIG proxy.config.output.logfile.rolling_interval_sec INT 86400
CONFIG proxy.config.output.logfile.rolling_size_mb INT 1000
```

**Comment by xeron** [comment]
Just found that default init script sets `--bind_stdout` and `--bind_stderr` on redhat… could be the reason I guess?

**Comment by bneradt** [comment]
Yes, I happened to just come across this code while working on #7937. Our documentation is a bit misleading about `proxy.config.output.logfile`. It currently, it says:

https://docs.trafficserver.apache.org/en/latest/admin-guide/files/records.config.en.html?highlight=proxy.config.output.logfile#proxy.config.output.logfile

> The name and location of the file that contains warnings, status messages, and error messages produced by the Traffic Server processes. If no path is specified, then Traffic Server creates the file in its logging directory.

This is mostly true, in a very literal sense. But most readers will read this as implying that this becomes the name of the file that gets created by the ATS process for stdout/stderr logs. In fact, this is not how this configuration works. The name of the stdout/stderr file is set, as you observed, via `--bind_stdout` and `--bind_stderr` arguments to the process. The `proxy.config.output.logfile` isn't used to set the name of the file, but to configure ATS concerning what the file was named via these command line parameters for the purpose of log rotation. If you configure `proxy.config.output.logfile` differently than `--bind_stdout` and `--bind_stderr` then log rotation of that file will not work.

Thus, to restate this:

* The name of the file ATS creates and writes to for process output is set via `--bind_stdout` and `--bind_stderr` command line parameters.
* If you want that output file to be rotated by the ATS process, you have to separately tell ATS what the name of the file you set on the command line with `--bind_stdout` and `--bind_stderr` via the `proxy.config.output.logfile` records.config parameter.

I'll update the docs to make this clearer.
