### ISSUE TITLE
Trafficserver redirection URL 

### ISSUE THREAD

**Issue by RSK14** [apache/trafficserver#6289]
Hi,
We have created the rewrite rule to redirect the client request to a dynamic URL when the requested content is not available in the origin server.

Here the challenge is we have to form the redirection URL based on the source URL. We would like to get the $1 value from the client requested URL.

Thanks,
Satheesh

**Comment by bryancall** [comment]
Please take a look at the regex_remap plugin.  This does what you ask: https://docs.trafficserver.apache.org/en/9.1.x/admin-guide/plugins/regex_remap.en.html?highlight=regex_remap
