### ISSUE TITLE
fail to load webp_transform plugin

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#6314]
compile the trafficserver in debian 10 x64 environment ( gcc 8.3.0), 

build the webp_transform plugin successfully but fail to load...

following is the error log

`[Jan  8 08:20:46.975] {0x7f882dee0740} FATAL: unable to load '/usr/local/trafficserver-8.0.5-d10/libexec/trafficserver/webp_transform.so': /usr/local/trafficserver-8.0.5-d10/libexec/trafficserver/webp_transform.so: undefined symbol: _ZTIN9atscppapi20TransformationPluginE`

**Comment by esmq2092** [comment]
some warnings when i build the plugins, but it comes out anyway ...
- 
![1](https://user-images.githubusercontent.com/13267484/71962389-483f0800-3234-11ea-9429-0ae801f24a7f.png)

**Comment by ywkaras** [comment]
_ZTIN9atscppapi20TransformationPluginE == typeinfo for atscppapi::TransformationPlugin  ( demangler.com )

**Comment by ywkaras** [comment]
A potential work around is to use:

LD_PRELOAD=/your/path/libtscppapi.so traffic_server ...

**Comment by esmq2092** [comment]
without luck, same error message emit
![2](https://user-images.githubusercontent.com/13267484/72030325-9b13d080-32c3-11ea-99d3-af03188a3ced.png)

**Comment by randall** [comment]
Can you post the output of `nm -A -D /usr/local/trafficserver/lib/libts*.so | grep Transformation` ?

**Comment by randall** [comment]
Is /usr/local/trafficserver a symlink to /usr/local/trafficserver-8.0.5-d10 ? (Or vice versa?)

**Comment by esmq2092** [comment]
@randall   /usr/local/trafficserver is a symlink to /usr/local/trafficserver-8.0.5-d10 

![3](https://user-images.githubusercontent.com/13267484/72036053-a8858680-32d4-11ea-88b3-08047c7b9450.png)

**Comment by ywkaras** [comment]
The -C option on nm will demangle the C++ names.

**Comment by ywkaras** [comment]
@esmq2092 I think you need to use:
```
export LD_PRELOAD=/your/path/libtscppapi.so
traffic_server ...
```
if you assign the shell variable on a separate line.  Generally people assign it at the beginning of the line so it's only set just for that command.

**Comment by ywkaras** [comment]
I've seen this sort of problem a few times before.  It was because the shared lib was linked without specifying all the shared libraries it itself depended on.  The shared lib may still load because core TS directly loads all the libs it depends on first, or because core TS loads other plugins first that load the depended-on libs.  But this can break, by changes to core TS make files, or changes in plugin.config or remap.config.

**Comment by esmq2092** [comment]
learn from above tips, i found that it is all about my broken testing environment,

after reinstall OS, then all works fine.

sorry for disturb you.

**Comment by ywkaras** [comment]
I suggest running the ldd utility on your plugin.  If it does not give a full path for all the shared libraries it needs, that means it's depending on the core or other plugins to load them properly, or the LD_LIBRARY_PATH environment variable.
