### ISSUE TITLE
Browser and JS client failing on ATS generated 502 status

### ISSUE THREAD

**Issue by rgresino** [apache/trafficserver#6320]
Consider adding optional logic in trafficserver/proxy/http/HttpTransact.cc to enable a response header: Access-Control-Allow-Origin: * when a 502 is generated by ATS.  This would allow browser and JS client to retry correctly when a 502 is returned.

**Comment by bryancall** [comment]
You can conditionally set this header with the header_rewrite plugin.  Please reopen if this can't be don't with the plugin for some reason.
