### ISSUE TITLE
head method will cause ats crash for the first request wile kick in webp transform

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#6322]
HEAD method will cause trafficserver crash immediately When Cache miss.

`terminate called after throwing an instance of 'Magick::ErrorBlob'
  what():  traffic_server: zero-length blob not permitted `' @ error/blob.c/BlobToImage/349
`traffic_server: received signal 6 (Aborted)
`

**Comment by bryancall** [comment]
@esmq2092 I am pretty sure that has try catch block was put around the calls to imagemagick for this type of reason.  Please reopen if this is still an issue.
