### ISSUE TITLE
the length of logging filter name will be limited when upgrade to ats v8

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#6336]
after upgrade to ats v8,  some logging filters failed to work  ( previous work for ats v7 )

at last i found that filter will be ignore when it's name too long...
`
 filter name: acceptCommon  -> work
`
`
 filter name: acceptGameWebCommon  -> does't work
`

**Comment by ywkaras** [comment]
Names longer than `acceptGameWebCommon` work in 9.1:  https://github.com/apache/trafficserver/blob/e5aa88032d29ce26a13f790454af1d38f2a35b69/tests/gold_tests/logging/log-filter.test.py#L41 .  Going to close this, please request it in the Slack channel if anyone feels we need a bugfix release for this, in any release before 9.1.
