### ISSUE TITLE
[LGTM] - Slicing - sslutils

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#6356]
https://lgtm.com/projects/g/apache/trafficserver/?mode=tree&ruleFocus=2160040902

Removes the derived members from the class

**Comment by ywkaras** [comment]
This is not an actual problem.  You could change it to:
```
  ssl_termios(int fd)
  {
     _fd = -1;
     // populate base class data
     if (tcgetattr(fd, static_cast<termios *>(this)) == 0) { // success
       _fd = fd;
     }
     // save our copy
    _initialAttr = *static_cast<termios *>(this);
  }
```
to perhaps get the latest spawn of lint to be happy with it.  But it would generate exactly the same object code.
