### ISSUE TITLE
Random traffic lock in 9.0.x

### ISSUE THREAD

**Issue by calavera** [apache/trafficserver#6383]
I just realized that I never opened an issue about this problem, and we should look into it.

We deployed https://github.com/apache/trafficserver/commit/c4b7d10c7c88f939f789ffe5f793a9978bff5578 in two canary boxes serving full production traffic and bump into an issue where TrafficServer stopped processing any transaction after some time. The time was aleatory, the first occurrence happened in one box after 8 hours, it happened sooner in that box after a restart, it was in less than 4 hours. The second box worked normally for about three days, until it arrived to this deadlock.

We saw this problem because in our graph, all TCP connections were suddenly blocked:

![Screenshot from 2020-01-24 08-52-25](https://user-images.githubusercontent.com/1050/73678951-5420bd00-466e-11ea-91ec-7768baf80c89.png)

![Screenshot from 2020-01-24 09-51-55](https://user-images.githubusercontent.com/1050/73678965-58e57100-466e-11ea-9615-b220d01135b8.png)

@shinrich mentioned that she was investigating something similar.

**Comment by ywkaras** [comment]
You don't see anything odd in the logs?

**Comment by calavera** [comment]
> You don't see anything odd in the logs?

nothing with the default logs, all processing stalls, but we'll try to run with debug enabled in one box to see if we get more information.

**Comment by randall** [comment]
Can you run pstack on the traffic_server process before restarting?

**Comment by calavera** [comment]
> Can you run pstack on the traffic_server process before restarting?

will do

**Comment by ywkaras** [comment]
Might be work a try to cherry-pick https://github.com/ywkaras/trafficserver/commit/ecde23cf0368a47e4124612bbbbb75341d901463 into 9 to make a load to run with debug output enabled.

**Comment by shinrich** [comment]
PR #6396 may help.  But it implies there still is an initial thread that is blocking the others.  In our case, we are sometimes seeing luajit get stuck in GC.

**Comment by calavera** [comment]
> PR #6396 may help.

Thanks @shinrich. We can test it as soon as it lands in the 9.0.x branch

**Comment by calavera** [comment]
We have not had time to investigate this as much as I wanted, but I'm starting to think that this is caused by one of our plugins, and not the core.

I think this should not be considered a blocker for the 9.0.x release.

**Comment by zwoop** [comment]
@calavera Is this still an issue that needs to be addressed upstream?

**Comment by calavera** [comment]
We have not checked since May, so I don't know. We're working on being able to test again, and if we don't find this problem anymore, I'll close the issue.

**Comment by calavera** [comment]
Closing this because we've not seen it in new tests.
