### ISSUE TITLE
Bring in LGTM fixes in to 9.1.x

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#6430]
We had a lot of fixes from the lgtm report go in to master. We should bring these back in to 9.1.x

There is a pr, https://github.com/apache/trafficserver/pull/6429, that has these all picked in which we can hold for 9.1.x

**Comment by masaori335** [comment]
Do you mean 9.0.x? 9.1.x is not branched yet.

**Comment by ezelkow1** [comment]
@masaori335 I dont know what @zwoop 's plan was, he just mentioned wanting these in 9.1. Not sure if we want to hold off for that or put them in 9.0
