### ISSUE TITLE
autest: change the way we build the *.c and *.cc files

### ISSUE THREAD

**Issue by bryancall** [apache/trafficserver#6438]
We are not building the C and C++ code under the tests directory on all of our supported platforms and we are not running them through clang-analyzer.

They should build as part of the build system, with a configure flag.  I would recommend renaming --enable-test-tools (doesn't look like it is used) and rename it to --enable-tests.

**Comment by ywkaras** [comment]
Here is the point in the python code where Au tests build C/C++ into test-specific plugins:  https://github.com/apache/trafficserver/blob/0f1f028d0e0e562bc88027408cbf68b5299b6b8b/tests/gold_tests/autest-site/trafficserver_plugins.test.ext#L43
It uses tsxs.

It would be hypothetically possible for an Au test to generate C/C++ code when it ran, then build a plugin from it.  But I don't think any test does this currently.  We _could_ move all plugins for core Au tests to the tree under the core plugins subdirectory.
