### ISSUE TITLE
ATS as a S3 proxy configuration

### ISSUE THREAD

**Issue by 80kk** [apache/trafficserver#6529]
Hi,
This is configuration help/explanation issue rather than bug. I am considering using ATS as a S3 proxy running as a container, however looking on https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/s3_auth.en.html
I don't know what is `session_token=<token>` and how can I get it. Is it a token taken from EC2 meta data?
Could anyone put more light on this please?

**Comment by mlibbey** [comment]
I think the session token is from
https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#UsingTemporarySecurityCredentials
in practice, we don't use it for v4 authentication.

**Comment by bryancall** [comment]
Looks like this has been fixed.  Please reopen if there is still an issue.
