### ISSUE TITLE
When is this data deallocated?

### ISSUE THREAD

**Issue by klebertarcisio** [apache/trafficserver#6627]
Look at this file:
https://github.com/apache/trafficserver/blob/master/plugins/experimental/mysql_remap/mysql_remap.cc

I would like to know when data is released.

` my_data *data = static_cast<my_data *>(malloc(1 * sizeof(my_data)));`
` data->query = static_cast<char *>(TSmalloc(QSIZE * sizeof(char)));`

Regards

**Comment by ywkaras** [comment]
You don't have to create issues in order to ask questions.  See Get Support and Get Involved on http://trafficserver.apache.org/ .

**Comment by klebertarcisio** [comment]
I'm sorry. I will close this issue.

Regards

**Comment by ywkaras** [comment]
This is a "global" plugin.  These are optional dynamically linked libraries that are loaded when trafficserver starts up.  TSPluginInit() is called when the library is loaded.  Once loaded, global plugins are never unloaded.  These two memory buffers are used until trafficserver exits, so there is no real need to explicitly deallocate them (except perhaps to avoid an ASAN diagnostic message).

**Comment by ywkaras** [comment]
It looks like whoever wrote this plugin did not understand that transactions happen in parallel, so the query variable needs to be a local (stack) variable in do_mysql_remap().  You could reopen this and title it "Mutual exclusion problem in mysql_remap plugin".

**Comment by klebertarcisio** [comment]
> It looks like whoever wrote this plugin did not understand that transactions happen in parallel, so the query variable needs to be a local (stack) variable in do_mysql_remap(). You could reopen this and title it "Mutual exclusion problem in mysql_remap plugin".

thanks, i will do that.
