### ISSUE TITLE
ATS as a proxy for S3 configuration issue

### ISSUE THREAD

**Issue by 80kk** [apache/trafficserver#6629]
Hi,
I am trying to configure ATS to act as a proxy for S3 bucket. However I'm struggling with the propper remap configuration and I need a help. What I want to achieve is call a S3 object using `curl http://localhost:8080/object` which will be mapped to `https://bucket_name.s3-eu-west-1.amazonaws.com/` (or https://s3.amazonaws.com/bucket_name/ or https://bucket_name.s3-eu-west-1.amazonaws.com/)

in my remap.config I have tried:
`#map http://localhost:8080/ https://bucket_name.s3-eu-west-1.amazonaws.com/ @plugin=s3_auth.so @pparam=--config @pparam=s3_auth_v4.config`

`#map http://localhost:8080/ https://s3.amazonaws.com/bucket_name/ @plugin=s3_auth.so @pparam=--config @pparam=s3_auth_v4.config`

`map http://localhost:8080 https://bucket_name.s3-eu-west-1.amazonaws.com @plugin=s3_auth.so @pparam=--config @pparam=s3_auth_v4.config`

all I can get while calling http://localhost:8080/ is a list of buckets in the AWS account.

**Comment by mlibbey** [comment]
My bet is on ```proxy.config.url_remap.pristine_host_hdr``` -- that it's sending the host: header "localhost" to s3 instead of the Host: that amazon wants. 
https://docs.trafficserver.apache.org/en/8.0.x/admin-guide/files/records.config.en.html#proxy-config-url-remap-pristine-host-hdr
Since this config is overridable, you can use the conf_remap plugin to set it, like
`@plugin=conf_remap.so @pparam=proxy.config.url_remap.pristine_host_hdr=0`

It should be helpful to turn on debug logs
 proxy.config.diags.debug.tags  to "http_hdrs| s3_auth"
proxy.config.diags.debug.enabled to 1
... the debug lines would show in traffic.out (or wherever you have proxy.config.output.logfile configured)

(then don't forget to turn off debug logs ;)

**Comment by 80kk** [comment]
That helped, thanks. Now I am able to access bucket content while calling inside the docker container and while calling it in the web browser running on my laptop, but I am getting:

`Cycle Prohibited`
`Description: Could not process your request for the document because it would cause an HTTP proxy cycle.  Please check the URL and your browser's proxy settings.`

when I am trying to access it from the local network. I am looking in documentation but can't find anything specific to that error.

**Comment by mlibbey** [comment]
Are you chaining multiple ATS together (like using parent.config)? Generally the Cycle Prohibited means that the request came into an ATS, then was somehow sent back to the same ATS. The way its matched is by the server name in the Via header -- so, if you are using parents, and both the child and parent are named the same (I think proxy.config.proxy_name ?), then it may think that the same machine has already processed the request.

Some troubleshooting ideas:
- use the debug tags above... perhaps you can see the loop.
- do you get the same behavior via curl vs web browser? If not, perhaps that give some clues where to look.

**Comment by 80kk** [comment]
No, ATS is running in Docker container on my local machine (laptop), there is no another proxy/reverse proxy or ATS instance. Just Docker network routing (created automatically). It is fine when accessing within the container or in my local web browser, but not when calling it from the local network (192.168.x.y). Could it be something related to version of ATS? ATS package in Ubuntu is 7.1.2.

**Comment by 80kk** [comment]
It doesn't matter which version of ATS I have. My configs:

records.config: https://pastebin.com/YAzD14j3

remap.config: 
`map http://localhost:80 http://bucket_name.s3.eu-west-1.amazonaws.com @plugin=s3_auth.so @pparam=--config @pparam=s3_auth_v4.config`
`reverse_map http://bucket_name.s3.eu-west-1.amazonaws.com http://localhost:80`
(I have also tried without reverse_map)

region_map.config:
`s3.amazonaws.com                     : eu-west-1`
`s3.dualstack.eu-west-1.amazonaws.com : eu-west-1`
`s3.eu-west-1.amazonaws.com           : eu-west-1`
`: eu-west-1`

s3_auth_v4.config 
`access_key=x`
`secret_key=x`
`version=4`
`v4-region-map=region_map.config`

**Comment by mlibbey** [comment]
Sounds like this was sorted on the users@ list, 
```
"CONFIG proxy.config.url_remap.remap_required INT 0"
This means requests go through even if there is no matching remap rule. Therefore a request to 127.0.0.1:80 will go through, and connect back to ATS, thereby creating a loop. If ATS is running on a host with address 172.16.0.1 and a request for that address arrives, exactly the same thing will happen. This may be what using your private IP address is doing.

Because the remap rule is for port 80, requests to other ports on localhost or 127.0.0.0/8 will also loop, e.g. HTTPS requests (port 443).```

Can we close this?

**Comment by 80kk** [comment]
Yes, the issue was in mapping to localhost not to fqdn plus remap_required set to 0.
