### ISSUE TITLE
HPACK Dynamic Table Size Update cannot clear the table and causes an error

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#6748]
HPACK Dynamic Table Size Update can be used to clear Dynamic Table, like the spec says:

> This mechanism can be used to completely clear entries from the
   dynamic table by setting a maximum size of 0, which can subsequently
   be restored.

https://tools.ietf.org/html/rfc7541#section-4.2

It was implemented correctly at the very beginning of our HPACK implementation, but was accidentally broken by [TS-3719](https://issues.apache.org/jira/browse/TS-3719) (96bd1fa785c3e6adbca8e11f1ad7a578e945625e), which is very old commit as well.

Current code causes COMPRESSION_ERROR and connection close.

**Comment by bryancall** [comment]
96bd1fa didn't break anything it fixed a security issue.  The check it done inside the while loop to prevent deleting a header that didn't exist.  After it was refactored the check is outside of the for loop.  Looks like whoever refactored it created the bug.
