### ISSUE TITLE
According to RFC7230:3.2.4,whitespace in repsonse header fieldname should be removed,not just return parse error

### ISSUE THREAD

**Issue by garfieldonly** [apache/trafficserver#6793]
In the commit below
https://github.com/apache/trafficserver/commit/08512deb11a610ae7084ce678b19bd637e30b3e1

we treat it as parse error while we found white space between field name and colon.
It's right when we found ws in request.
However,we should remove white space when we found it in response.

`No whitespace is allowed between the header field-name and colon.  In
   the past, differences in the handling of such whitespace have led to
   security vulnerabilities in request routing and response handling.  A
   server MUST reject any received request message that contains
   whitespace between a header field-name and colon with a response code
   of 400 (Bad Request).  A proxy MUST remove any such whitespace from a
   response message before forwarding the message downstream.`

@oknet @bryancall

**Comment by oknet** [comment]
Link to #3192
