### ISSUE TITLE
⛱️ Refactoring closing HTTP/2 session

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#6877]
There are too many paths to close/free Http2ClientSession/Http2ConnectionState. I know this is result of fixing bunch of issues step by step in the past. However, having similar name functions and call them each other doesn't make sense and it making us hard to find bugs.

## Notes
- The order of SSN/TXN close hook is a matter (#6364, #787)
- `vc->add_to_keep_alive_queue()` call could be pitfall (https://github.com/apache/trafficserver/issues/4504#issuecomment-460917346)

## TODOs
- [ ] Rename `Http2ConnectionState::release_stream()` because the name doesn't describe what the function does
- [ ] Design how to close Http2ClientSession/Http2ConnectionState simply

**Comment by maskit** [comment]
Removing Http2ConnectionState (moving its functions into H2Ssn/Txn) would make things much easier.

**Comment by masaori335** [comment]
#7845 covers this.
