### ISSUE TITLE
Compiler errors on Ubuntu 20.04

### ISSUE THREAD

**Issue by calavera** [apache/trafficserver#6895]
[The fix for Ubuntu 16](https://github.com/apache/trafficserver/pull/6875) seems to break building TrafficServer on Ubuntu 20, with gcc and clang, as far as I can tell.

I don't know why that change was made since there is no issue associated to the PR. This is the error I get compiling on Ubuntu 20.04:

```
ink_res_init.cc:97:3: error: excess elements in scalar initializer
  {HOST_RES_PREFER_IPV4, HOST_RES_PREFER_IPV6, HOST_RES_PREFER_NONE}};
  ^                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

These are the commands I run:

```
./configure CXXFLAGS=-std=c++17 CC=clang CXX=clang++
make
```

I've tried with Clang 10(default version in Ubuntu 20), Clang 9, and GCC 9.3.0(default version in Ubuntu 20).

**Comment by brbzull0** [comment]
I can have a look at this, as seems related to a change I introduced [#6820](https://github.com/apache/trafficserver/pull/6820)

**Comment by brbzull0** [comment]
This change was reverted on 9, and I've tried the three compilers you've mentioned with no issues.
