### ISSUE TITLE
autest on PR commit update runs against old commit

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#6912]
I have noticed this over the last couple weeks.  When I push a new commit to a PR to fix an autest, autest fails again and from looking at the output appears to be running against the old code.  Running [approve ci autest] fixes it.

**Comment by ezelkow1** [comment]
+1, I have also had this happen on a couple PRs

**Comment by shinrich** [comment]
Closing this in deference to issue #6909 which has some more details.
