### ISSUE TITLE
Increase in ERR_CLIENT_ABORT (due to logcode change)

### ISSUE THREAD

**Issue by sudheerv** [apache/trafficserver#6960]
As part of our upgrade from ats6.2 to ats9, we ran into a problem with elevated ERR_CLIENT_ABORT counts. After a lot of investigation, it turned out to be not a regression or due to a functional problem, but just due to a cause code change with PR #4267 (https://github.com/apache/trafficserver/pull/4267). The same rate of errors have been there before too but were being put into other buckets such as ERR_UNKNOWN and are just shuffled around. I confirmed this by removing this specific patch that the ERR_CLIENT_ABORTS went back to our older baseline levels.

Creating this issue so others that may run into a similar problem will not have to spend time troubleshooting this.

**Comment by vmamidi** [comment]
Now, this is documented; maybe we should close this issue as it's not an issue?
