### ISSUE TITLE
[8.0.8] systemd unit file will not installed

### ISSUE THREAD

**Issue by tuxmaster5000** [apache/trafficserver#6970]
Under the rc directory the needed files (makefile etc.) are present, but on an "make install" the systemd unit file are not installed.

**Comment by ezelkow1** [comment]
Discussing this I dont think we want our make install process to determine these sorts of things and would rather leave it up to the packages and distro specific installs. There is an example specfile that can be used that I believe will install the systemd unit. Putting this in the make system though would need all sorts of distro/systemd/etc checks and I dont think are normally guaranteed via a make install, and preferred to leave it up to the package creator to handle it.

The provided systemd file is there and can be used as is or modified, I believe many groups modify this file for their own uses anyway
