### ISSUE TITLE
CONFIG proxy.config.net.max_requests_in - unrecognized

### ISSUE THREAD

**Issue by AD5GB** [apache/trafficserver#7030]
This warning is logged to diags.log when max_requests_in is configured: 
WARNING: Unrecognized configuration value 'proxy.config.net.max_requests_in

Version 10, Git branch: master

**Comment by jvgutierrez** [comment]
`proxy.config.net.max_requests_in` has been introduced in ATS 9.x, on previous versions you should configure `proxy.config.net.max_connections_in`

**Comment by AD5GB** [comment]
# #7031

**Comment by sudheerv** [comment]
For some odd reason, the magic bullet "This fixes.." on the PR didn't seem to close this issue automatically. 

Closing it manually before it annoys @zwoop by remaining open.
