### ISSUE TITLE
TCP_SWAPFAILS_MISS cause incorrect http response(incomplete response content)

### ISSUE THREAD

**Issue by twoholes** [apache/trafficserver#7051]
Recently, we found some taged 'TCP_SWAPFAIL_MISS' logs on ts-6.2.2. These urls can not be completely downloaded but interrupted halfway.
the log like this:
-|25/Jul/2020:18:26:10 +0800|163|TCP_REFRESH_MISS|GET|XXX|HTTP/0.0|200|1447602|638|-|Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1;)|FIN|FIN|200
-|25/Jul/2020:18:26:10 +0800|1|TCP_HIT|GET|XXX|HTTP/1.1|200|1447602|597|-|Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1;)|-|FIN|000
-|25/Jul/2020:18:26:10 +0800|172|TCP_SWAPFAIL_MISS|GET|XXX|HTTP/1.1|200|1065|639|-|Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1;)|-|FIN|000

 I guess the problem relate to read while write or negative cache, but I don't know how to do ...
who can help me ...

**Comment by WolfgangBai** [comment]
I think you can reproduce it in the test environment and gradually narrow the scope of the problem.

**Comment by twoholes** [comment]
> 
> 
> I think you can reproduce it in the test environment and gradually narrow the scope of the problem.

I try it, but can not reproduce it .
this is the same problem:  https://github.com/apache/trafficserver/issues/2983

**Comment by WolfgangBai** [comment]
you can set proxy.config.cache.enable_read_while_writer 0 to close read while writer.
Observe whether it recurs. 
I  read some code,it must be occur read error in HttpSM::tunnel_handler_cache_read function.

**Comment by twoholes** [comment]
It's really a cursing problem.  I have not reappeared it in my test env.  
I think  someone has resolved this problem in https://github.com/apache/trafficserver/issues/2983 , but he closed the issue...

**Comment by randall** [comment]
Do you see these types of WARNINGS?

```
[Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} WARNING: Middle: Doc magic does not match for 35F56632C2D0FBA66E571906B0AB0D0A
[Dec 26 14:58:07.752] Server {0x2ba4d4e0d700} WARNING: Document E04141550AB2802F5818C7C0460D598C truncated
```

**Comment by twoholes** [comment]
I have open the debug mode, the return code in CacheRead.cc, 
openReadReadDone -> dir_probe(&key, vol, &dir, &last_collision) return 0   -> goto Ldone  -> return VC_EVENT_EOS

**Comment by bneradt** [comment]
It is possible this was an issue in the 6.x train but is now fixed. If desired, please re-test on a later release and re-open if this is still an issue.
