### ISSUE TITLE
Comment for ats_base64_ functions seems wrong

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#7108]
The comment says functions return pointers for malloc-ed buffers, but the implementations don't seem like so.
https://github.com/apache/trafficserver/blob/c196db5f0a5b957983351ad51ef360bfc68fbd66/include/tscore/ink_base64.h#L34-L35

**Comment by maskit** [comment]
I think the routines do not allocate memory.

**Comment by alokrahul513** [comment]
Hi, I want to work on this issue. How to get started?

**Comment by Sid672** [comment]
@maskit can you tell me what changes you want? 
Removal of comments or modify them?

**Comment by maskit** [comment]
If you think the behavior is obvious and the comment is unnecessary, remove it.
If you think documentation is necessary, modify the comment so that it describes the behavior.

I think documentation is always nice to have, but it should not tell a lie if it exists. I'd modify the comment.

Here is the implementations if you need to know what the functions do.
https://github.com/apache/trafficserver/blob/master/src/tscore/ink_base64.cc

**Comment by Sid672** [comment]
@maskit please correct me if I am wrong.
Functions:
```
1) bool ats_base64_encode(const char *inBuffer, size_t inBufferSize, char *outBuffer, size_t outBufSize, size_t *length);

2) bool ats_base64_encode(const unsigned char *inBuffer, size_t inBufferSize, char *outBuffer, size_t outBufSize, size_t *length);

3) bool ats_base64_decode(const char *inBuffer, size_t inBufferSize, unsigned char *outBuffer, size_t outBufSize, size_t *length);
```
- The first function call the 2nd function. 
- 2nd function converts the character into binary up to the length of Buffersize and returns true if it is completed.
- 3rd function decode the buffer and returns true after completion.

So can I add these comments:
```
* These routines convert char's of string and return true. 
```

**Comment by bryancall** [comment]
@willwendorfvm Do you want to take a look at this?

**Comment by bryancall** [comment]
@moonchen is going to take a look at this
