### ISSUE TITLE
7.1.x Crash on HandleCacheOpenReadMiss 

### ISSUE THREAD

**Issue by tpcanhang** [apache/trafficserver#7139]
I use 7.1.11 , traffic server restarts frequently，here is the crashlog：
0    0x000000000051fa9d crash_logger_invoke(int, siginfo*, void*) + 0x98
1    0x0000003ba100f710 __restore_rt + (nil)
2    0x0000003ba0c32925 gsignal + 0x35
3    0x0000003ba0c34105 abort + 0x175
4    0x00002b848301c767 ink_abort(char const*, ...) + 0xa8
5    0x00002b848301996a _ink_assert + 0x32
6    0x0000000000652f71 HttpTransactHeaders::copy_header_fields(HTTPHdr*, HTTPHdr*, bool, long) + 0x73
7    0x000000000064770c HttpTransact::build_request(HttpTransact::State*, HTTPHdr*, HTTPHdr*, HTTPVersion) + 0x128
8    0x0000000000632116 HttpTransact::HandleCacheOpenReadMiss(HttpTransact::State*) + 0x9e0
9    0x0000000000610799 HttpSM::call_transact_and_set_next_state(void (*)(HttpTransact::State*)) + 0x71
10   0x00000000005f96aa HttpSM::handle_api_return() + 0x8e
11   0x00000000005f94dc HttpSM::state_api_callout(int, void*) + 0x9ea
12   0x0000000000608a30 HttpSM::do_api_callout_internal() + 0x1ca
13   0x0000000000618a17 HttpSM::do_api_callout() + 0x27
14   0x000000000061094c HttpSM::set_next_state() + 0x66
15   0x00000000006108d5 HttpSM::call_transact_and_set_next_state(void (*)(HttpTransact::State*)) + 0x1ad
16   0x00000000005fc845 HttpSM::state_hostdb_lookup(int, void*) + 0x1c5
17   0x00000000005fe5bd HttpSM::main_handler(int, void*) + 0x339
18   0x0000000000522cee Continuation::handleEvent(int, void*) + 0x72
19   0x00000000006fefd5 reply_to_cont(Continuation*, HostDBInfo*, bool) + 0x2b3
20   0x0000000000703c92 HostDBContinuation::dnsEvent(int, HostEnt*) + 0x1372
21   0x0000000000522cee Continuation::handleEvent(int, void*) + 0x72
22   0x000000000071798c DNSEntry::postEvent(int, Event*) + 0xcc
23   0x0000000000522cee Continuation::handleEvent(int, void*) + 0x72
24   0x00000000007e35b6 EThread::process_event(Event*, int) + 0x136
25   0x00000000007e37de EThread::process_queue(Queue<Event, Event::Link_link>*) + 0xa0
26   0x00000000007e3900 EThread::execute_regular() + 0x4c
27   0x00000000007e3bf2 EThread::execute() + 0xf8
28   0x00000000007e2aa0 spawn_thread_internal(void*) + 0x75
29   0x0000003ba10079d1 start_thread + 0xd1
30   0x0000003ba0ce8b6d clone + 0x6d
31   0x0000000000000000 0x0 + 0x6d

**Comment by scw00** [comment]
Could you please share the `HttpSM::history`?

**Comment by tpcanhang** [comment]
Just crash.log, no core file find

**Comment by ywkaras** [comment]
Please see if this can be reproduced in a supported release.

**Comment by ywkaras** [comment]
Please reopen this issue if the problem is seen in a currently supported release.
