### ISSUE TITLE
stms log field can have bad values.

### ISSUE THREAD

**Issue by traeak** [apache/trafficserver#7196]
Observed in ats80x and ats81x, master.

We tried to enable the stms field in our logs.  We started observing invalid values in some circumstances.

When the parent isn't visited the value is -1.  This isn't a valid value for a time field, it should be '0' since '0' time was spent contacting the origin.  stmsf in this case is set to '-.001', sts to '0' and stmsh to 'ffff...'

In the case an intercept plugin is in play (like the stats_over_http or slice plugins), the stms value is set to utc milliseconds (ie: 1600263600889).  I speculate that the stms field is initialized to some start time but never resolved with an end time later in the transaction.

**Comment by mtorluemke** [comment]
+1 for getting this fix in -- seeing this issue in production as well.
