### ISSUE TITLE
About upgrading from 7.x to 8.x

### ISSUE THREAD

**Issue by yamatsum** [apache/trafficserver#7201]
I'm trying to upgrade trafficserver from 7.x to 8.x.
I build it on docker and start it with the "traffic_manager" command.
I can check the logs of diags.log and manager.log as before, but only extended2.log is not output.
Looking at manager.log, I could see the following output, so I think this area is suspicious.
`[Sep 17 16: 33: 20.398] traffic_manager NOTE: [Rollback :: openFile] Open of logging.yaml failed: Permission denied`
Do I need to make any changes around the log?

By the way, I proceeded with reference to the following document, but since it did not work at first, I also introduced python3.
https://cwiki.apache.org/confluence/display/TS/Upgrading+to+v8.0

**Comment by randall** [comment]
The config file changed between those versions. Unfortunately, it's not mentioned in the upgrade wiki you linked to.

From https://docs.trafficserver.apache.org/en/8.0.x/admin-guide/files/logging.yaml.en.html :

```
This configuration file replaces the XML based logs_xml.config, as well as the Lua based logging.config from past Traffic Server releases. If you are upgrading from a Traffic Server release which used either the XML or the Lua configuration file format, and you have created custom log formats, filters, and destinations, you will need to update those settings to this format.
```

**Comment by yamatsum** [comment]
@randall 
Thanks for the reply.
I placed the yaml format configuration file and confirmed that the log was output.

By the way, is there anything else that has changed from 7.x to 8.x?
The log is output, but it is not working the same as before

**Comment by yamatsum** [comment]
Specifically, the remapped PATCH method request has timed out.
It works fine in 7.x, so it doesn't depend on the server you're requesting from

**Comment by yamatsum** [comment]
Is the difference of the default value such as record.config collected somewhere?

**Comment by randall** [comment]
> Is the difference of the default value such as record.config collected somewhere?

Maybe `traffic_ctl config diff` ?

**Comment by yamatsum** [comment]
@randall 

After examining each one, I found that the initial values of the `proxy.config.http.number_of_redirections` and `proxy.config.http.redirection_enabled` settings are different between v7 and v8.

> In previous versions proxy.config.http.redirection_enabled had to be set to 1 before this setting was evaluated. Now setting proxy.config.http.number_of_redirections to a value greater than zero is sufficient to cause Traffic Server to follow redirects.

https://docs.trafficserver.apache.org/ja/8.1.x/admin-guide/files/records.config.en.html#proxy-config-http-number-of-redirections

Thank you for your help
