### ISSUE TITLE
dead vs down server - standardize terminology

### ISSUE THREAD

**Issue by djcarlin** [apache/trafficserver#7283]
I find it a little confusing that dead and down are used interchangeably - can all setting names mention either dead OR down?

proxy.config.http.down_server.cache_time: 180
proxy.config.http.down_server.abort_threshold: 10
proxy.config.http.connect_attempts_max_retries_dead_server: 1

**Comment by shinrich** [comment]
Another thing that is confusing about our terminology is the use of retries like for the following timeouts

```
proxy.config.http.connect_attempts_max_retries
proxy.config.http.connect_attempts_rr_retries
```

While those settings say retries, they are really specifying tries.
