### ISSUE TITLE
Update README to include zlib dependency

### ISSUE THREAD

**Issue by mingzym** [apache/trafficserver#7303]
we need to update README to include zlib dependency. just find out that on a fresh installed Ubuntu.

**Comment by maskit** [comment]
Yes, and I think we should check the availability on configure script. #5837

**Comment by alokrahul513** [comment]
Hi, I want to work on this issue. How to get started?

**Comment by mingzym** [comment]
@danwt make a good start there, I think we can find out what is the package needed on all other OS too, sometimes there may be different in naming the dev-libs. include all that will make a good commit.
thanks
