### ISSUE TITLE
header rewrite overrides request_header_max_size too late

### ISSUE THREAD

**Issue by traeak** [apache/trafficserver#7310]
Tested with 8.1.x In a remap header rewrite file the following:

cond %{REMAP_PSEUDO_HOOK}
set-config proxy.config.http.request_header_max_size 1

doesn't get applied until *after* the header size check is made in HttpSM.

The code and docs seem to indicate that this parameter should be overrideable.

workaround for this particular issue is to use the cqhl log value.

**Comment by bryancall** [comment]
@traeak Can you update the docs that this is not possible and use the cqhl value?

**Comment by traeak** [comment]
Looking at the document code it's not marked as overrideable anyways.  Not exactly sure how to document this directly.
