### ISSUE TITLE
regex_revalidate immutable rules confusing

### ISSUE THREAD

**Issue by traeak** [apache/trafficserver#7322]
Through traffic control we have a limited way for end users to issue revalidations.  Unfortunately the regex_revalidate plugin as-is will skip new rules with a certain regex if that rule has already been loaded.  If an end user sets a 30 day revalidation for a live linear asset manifest endpoint the reissue has no effect and we end up issuing a new equivalent regex but different regex to start new invalidations.

Based on communication with the traffic control team it may be best for the regex_revalidate plugin to be able to switch from first rule wins to last rule wins and also to "reset" the revalidation if the end time is changed.

**Comment by mitchell852** [comment]
Here is what we are experienceing:

```
Path: /opt/trafficserver/etc/trafficserver/regex_revalidate.config

http://my.origin.net/foo.png 1606758714 <-- this rule was created on 11/13 with an expiration of 11/30 (the invalidation may occur at anytime betwen 11/13 - 11/30)
http://my.origin.net/foo.png 1606758714 <-- this rule was created because the user needed to invalidate foo.png AGAIN...but it is blocked until 11/30 due to rule #1
```

Since we don't really know when the invalidation for rule #1 occurs, we leave that rule in until it expires....which basically blocks subsequent rules...

**Comment by traeak** [comment]
I'll change this to what we know is a mess, which is duplicated rules will be constantly reloaded.

**Comment by traeak** [comment]
Just ensure non duplicate rules in a file being loaded.
