### ISSUE TITLE
Support inline comments in parent.config

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficserver#7388]
[The ATC project](https://github.com/apache/trafficcontrol) would like for ATS to support inline comments in `parent.config`. For debugging and troubleshooting, it would be helpful to be able to include an inline comment on a `parent.config` line like the following:
```
dest_domain=foo.example.org port=10080 parent="bar.example.org:10080|1.0" secondary_parent="baz.example.ort:10081|1.0" round_robin=false go_direct=false qstring=ignore parent_is_proxy=false parent_retry=both unavailable_server_retry_responses="500,502,503"  max_simple_retries=2 max_unavailable_server_retries=1 # this line brought to you by the topology 'foo'
```
Additionally, it appears that `remap.config` supports inline comments like this just fine, but I'm not sure about other config files.

Tested on ATS version 8.1.0.

**Comment by bneradt** [comment]
@ezelkow1 and @jrushford : since the current plan is to replace this with strategies.yaml which supports comments, do you think we can close this issue?

**Comment by rawlinp** [comment]
As the issue opener, I'm ok with closing this issue. The ATC project has resorted to using full-line comments in `parent.config`, so there's no need for this feature anymore from ATC's perspective.

**Comment by ezelkow1** [comment]
Closing since the opener is good without it, and may be fixed in strategies anyway

**Comment by jrushford** [comment]
I'm good with closing it too.
