### ISSUE TITLE
header_rewrite doc bug for %{RANDOM}

### ISSUE THREAD

**Issue by mlibbey** [apache/trafficserver#7442]
https://docs.trafficserver.apache.org/en/8.0.x/admin-guide/plugins/header_rewrite.en.html#random
says
RANDOM
cond %{RANDOM:<n>} <operand>
Generates a random integer between 0 and \<n\>, inclusive.

When I configure using 
```
cond %{SEND_RESPONSE_HDR_HOOK}
    set-header Random %{RANDOM:3}
```
I never see 3 as an answer:
```
$ for i in $(seq 100); do curl -IXGET http://127.0.0.1/ | grep Random >> /tmp/x; done; sort /tmp/x | uniq -c | sort -nr
     37 Random: 0
     35 Random: 2
     28 Random: 1

```
Think we need to change doc to say 
Generates a random integer from 0 to <n>, eg, [0,\<n\>) -- \<n\> will not appear.

Suggestions for better wording?

**Comment by masaori335** [comment]
Comment on the `ConditionRandom` says
https://github.com/apache/trafficserver/blob/f7bdee616ebec26b2746ce50c75eaacab7571554/plugins/header_rewrite/conditions.cc#L110

**Comment by bryancall** [comment]
The docs have been updated.

**Comment by bneradt** [comment]
Thanks Miles for filing this. Looks like this has been updated. See:
https://docs.trafficserver.apache.org/en/8.1.x/admin-guide/plugins/header_rewrite.en.html#random

> Generates a random integer from 0 up to (but not including) \<n\>. Mathmatically, [0,n) or 0 <= r < n.
