### ISSUE TITLE
Build failed on FreeBSD w/ clang 10

### ISSUE THREAD

**Issue by gaod** [apache/trafficserver#7456]
At the latest release 8.1.1, while enabling WCCP on FreeBSD 12.2 with built-in clang 10.0.1:
```
ld: error: undefined symbol: wccp::detail::cache::CacheData::idAddr() const
>>> referenced by WccpMsg.cc:1029
>>>               WccpMsg.o:(wccp::CacheViewComp::fill(wccp::MsgBuffer&, wccp::detail::cache::GroupData const&)) in archive wccp/libwccp.a
>>> referenced by WccpMsg.cc:1625
>>>               WccpMsg.o:(wccp::detail::Assignment::fill(wccp::detail::cache::GroupData&, unsigned int)) in archive wccp/libwccp.a
c++: error: linker command failed with exit code 1 (use -v to see invocation)
````
But it can pass on FreeBSD 12.2 with gcc 9.3.

**Comment by maskit** [comment]
Confirmed that the link error happens on master as well. Not really a workaround but it links successfully if I run configure with `--enable-debug`.

**Comment by maskit** [comment]
Removing `inline` solves the issue, but I'm not sure if we want to do it.
https://github.com/apache/trafficserver/blob/a1a47b93ad29ffd3d3168d1c74c8ef20bbe7b28e/src/wccp/WccpEndPoint.cc#L360-L364

@SolidWallOfCode Can you take a look?
