### ISSUE TITLE
how to increase the chance of webp transform

### ISSUE THREAD

**Issue by esmq2092** [apache/trafficserver#7459]
As we known，origin servers will not send any `Vary` header when response to ordinary requests for images.

and I found that when ats had image files cached in original encoding ( such as jpeg or png ），it will return cached object directly without doing webp transform， even client support webp.

the following two methods can enforce webp transform，but either are not perfect.

1. change proxy.config.http.cache.ignore_accept_mismatch from 2 to 1 （ not safe )
2. enforce origin server return Vary: Accept headers for images files （ cause cache miss )

i wonder is there any way to do it better。。。

**Comment by shukitchan** [comment]
A bit tedious but i will do the following

- normalize the Accept headers in the read_request hook. Similar to
how Accept-Encoding can be normalized through
proxy.config.http.normalize_ae . You can also normalize it and keep
the results in a separate header (,e,g Normalized-Accept). This can be
done using either header_rewrite or lua plugin
- you can also use lua/header_rewrite plugin to add the Vary:
Normalized-Accept for you in the read_response hook.

Kit

**Comment by esmq2092** [comment]
thanks for your advice, i'll have a try.

**Comment by shukitchan** [comment]
does this solve your problem?

**Comment by esmq2092** [comment]
follow your advice, i use header_rewrite to achieve the goal. ^-^

cond %{READ_REQUEST_HDR_HOOK}
cond %{HEADER:Accept} /webp/
set-header TEST-IMG-FMT webp

cond %{READ_RESPONSE_HDR_HOOK}
cond %{HEADER:Content-Type} /image/
add-header Vary TEST-IMG-FMT
add-header TEST-IMG-FMT webp

**Comment by shukitchan** [comment]
Looks like this is resolved
