### ISSUE TITLE
L7 Ingress/Egress transaction status

### ISSUE THREAD

**Issue by a-canary** [apache/trafficserver#7508]
Internally Verizon is starting to use UserArgs to flag transactions that are going to a peer, to signal to other plugins to skip egress transforms. 

Having an Ingress/Egress status standard convention between all plugins will be necessary with more sophisticated CDN architectures, but should it be made part of the core API? 

Note that one of our goals is to have a single config for all nodes in the CDN. Thus all nodes are configured to run ingress and egress transforms unless flagged as a regress by our upstream selection logic. This will remove unwanted transforms from happening between cache hops within the CDN, and reduce overhead.

**Comment by bryancall** [comment]
This can be accomplished by using the CDN loop detection header defined in RFC 8586 (https://datatracker.ietf.org/doc/html/rfc8586).  The header could be created or appended to on ingress and then fetch the header and look for the matching string.
