### ISSUE TITLE
TS_SSL_CLIENT_HELLO_HOOK is unavailable with BoringSSL

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#7510]
TS_SSL_CLIENT_HELLO_HOOK  is not called if you use ATS with BoringSSL. This is because `SSL_CTX_set_client_hello_cb` is not available on BoringSSL. We might be able to use `SSL_CTX_set_select_certificate_cb` instead.

Autest tls_hooks16, 17 and 18 fail because of this.

**Comment by randall** [comment]
I believe this can be closed now. ATS now uses SSL_CTX_set_select_certificate_cb with BoringSSL (added in #8014)
