### ISSUE TITLE
Spurious log messages on config file updating

### ISSUE THREAD

**Issue by mtorluemke** [apache/trafficserver#7530]
ATS's "include" mechanism for remap config files causes wrong log messages in ATS 9.x+: 

```<date> <time> <hostname> traffic_manager[<pid>]: traffic_manager NOTE: [fileUpdated] <ATS directory>/<include directory>/<included config file> changed, need restart.```

These files do get reloaded fine, so it's just a logging issue. Seems to stem from PR #4392.

**Comment by shinrich** [comment]
Do you still get reloads when the included file changes?

Did you previously see a message like?
```
[fileUpdated] Unknown config file updated <ATS directory>/<include directory>/<included config file>
``
