### ISSUE TITLE
Is it possible to depool a backend within ATS?

### ISSUE THREAD

**Issue by paladox** [apache/trafficserver#7637]
I'm not sure where to ask this question but here it goes.

In varnish you are able to easily depool/repool and have backends.

In ats i see you can do this via parent.config but it doesn't seem to support depooling and you have to restart to remove/add a backend.

I had an idea on doing this via a lua plugin within do_remap but it seems math.random is cached so we cannot do that.

Does anyone know how I can do this? (we're thinking of moving from varnish to ats)

**Comment by mlibbey** [comment]
Parent.config is reloadable. When we add/remove a server from a line in parent.config, we run `traffic_ctl config reload`, and the removed server is depoolled/repoolled -- all while continuing to serve traffic.

**Comment by paladox** [comment]
When I run change the backend and run `traffic_ctl config reload` it doesn't appear to use it. Continues to use the backends I removed.

Even tried `service trafficserver reload`.

**Comment by paladox** [comment]
Ah! I had to change the user permissions on the parent.config file.

**Comment by mlibbey** [comment]
Shall we close this then?

**Comment by paladox** [comment]
Yup, one last thing. Did you implement a healthcheck that automatically depools a backend?

**Comment by mlibbey** [comment]
We have found that when we think the server is going to be down "temporarily" (hours to days), we prefer to use 
traffic_ctl host down/up $servername
as it's an easier command for the monitoring/healthcheck/whatever things to issue
and longer term (days to weeks) remove from parent.config.

ATS has built in passive health monitoring for these, but there are benefits to active monitoring (and administratively marking parents down).

**Comment by paladox** [comment]
Thank you so much!

**Comment by paladox** [comment]
Also do you know how we get it to stop

**Comment by paladox** [comment]
Also do you know how we get it to stop creating a new config after reload (e.g <config>_4.config) @mlibbey

**Comment by paladox** [comment]
Also any idea how we can get the details of which server is downed?

**Comment by mlibbey** [comment]
- `traffic_ctl metric match proxy.process.host_status` will give you the full list of servers and their status.
- there is a way to not let ATS cp the old file to the _N.config, but, I can't seem to find it, and I think most people just let it happen -- having a quick way to revert can be nice to have.
