### ISSUE TITLE
Compress not logging properly on 301

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#7688]
Doing a curl with gzip (this is with caching compressed turned off so it is on the fly):
curl http://localhost:8080/index.html -Lvsk -o /dev/null -H "Accept-Encoding: gzip"
with remap
map / http://google.com @plugin=compress.so @pparam=compress.config

That remap will force a redirect to www.google.com. 
< Content-Encoding: gzip
but still gzip the content. The plugin reports:
[ET_NET 12] DIAG: (compress) INFO: Kicking off compress plugin for request
[ET_NET 12] DIAG: (compress) INFO: normalized accept encoding to gzip
[ET_NET 12] DIAG: (compress) INFO: handling compression of cached object
DIAG: (compress) INFO: http response status [301] is not compressible

So it did still compress, and i could see the proper content encoding. However in the logging
pce="""-"""
pce="""%<{Content-Encoding}psh>"""

So even though we got a compressed response it was not logged as gzipped

If you change the remap to www.google.com instead so you avoid the redirect then everything is logged as it should be

**Comment by YuanYingdong** [comment]
Did you set ats to follow redirect? Maybe curl visited the os directly after receiving 301. Here is what I got:
```
~/bin/ats# curl http://localhost:8080/index.html -Lvsk -o /dev/null -H "Accept-Encoding: gzip"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /index.html HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Accept-Encoding: gzip
>
< HTTP/1.1 301 Moved Permanently
< Location: http://www.google.com/index.html
< Content-Type: text/html; charset=UTF-8
< Date: Sun, 11 Apr 2021 13:56:19 GMT
< Expires: Tue, 11 May 2021 13:56:19 GMT
< Cache-Control: public, max-age=2592000
< Server: ATS/10.0.0
< Content-Length: 229
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Age: 203
< Connection: keep-alive
<
* Ignoring the response-body
{ [229 bytes data]
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://www.google.com/index.html'
*   Trying 2404:6800:4003:c04::69...
* TCP_NODELAY set
* Connected to www.google.com (2404:6800:4003:c04::69) port 80 (#1)
> GET /index.html HTTP/1.1
> Host: www.google.com
> User-Agent: curl/7.58.0
> Accept: */*
> Accept-Encoding: gzip
>
< HTTP/1.1 200 OK
< Date: Sun, 11 Apr 2021 13:59:42 GMT
< Expires: -1
< Cache-Control: private, max-age=0
< Content-Type: text/html; charset=ISO-8859-1
< P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
< Content-Encoding: gzip
< Server: gws
< Content-Length: 5933
< X-XSS-Protection: 0
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: 1P_JAR=2021-04-11-13; expires=Tue, 11-May-2021 13:59:42 GMT; path=/; domain=.google.com; Secure
< Set-Cookie: NID=213=isJeOSAJw0LuEmxqZhSpoxhQzElgt0Lpt-QiAw-8JckxsmpXM_S5wOn9xLiSxPYlFC6Ua58BjygoCzcMIVAggSzUkq4W7MCQc28wN72iJRj2Q9Jp5eVCUMa28fB_AZHUfiJGQ-igF1BOglUdbOsI8rOYJJFjIFmbOCiFmubvptY; expires=Mon, 11-Oct-2021 13:59:42 GMT; pat
h=/; domain=.google.com; HttpOnly
<
{ [5933 bytes data]
* Connection #1 to host www.google.com left intact
```

**Comment by ezelkow1** [comment]
oh possibly could be it, i can give it a shot when i get a chance again

**Comment by ezelkow1** [comment]
Yea, misconfig issue on my part, my bad :)
