### ISSUE TITLE
Failure in schedule_on_thread test

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#7741]
Saw this failure in PR #7736.  I think this is unrelated to the PR, so I am noting it here before I move on.

This is the output of the traffic_server process
```
[Apr 23 07:40:02.093] traffic_server DIAG: (TSContSchedule_test.init) initializing plugin for testing TSContScheduleOnThread
[Apr 23 07:40:02.144] [ET_TASK 1] DIAG: (TSContSchedule_test.schedule) [TSContSchedule_test] scheduling continuation
[Apr 23 07:40:02.145] [ET_NET 10] DIAG: (TSContSchedule_test.handler) TSContScheduleOnThread handler 1 thread [0x7f2637b4a010]
[Apr 23 07:40:02.145] [ET_NET 10] DIAG: (TSContSchedule_test.handler) [TSContSchedule_test] scheduling continuation
[Apr 23 07:40:02.145] [ET_NET 10] DIAG: (TSContSchedule_test.handler) TSContScheduleOnThread handler 2 thread [0x7f2637b4a010]
[Apr 23 07:40:02.145] [ET_NET 10] DIAG: (TSContSchedule_test.handler) TSContScheduleOnThread handler 2 thread [0x7f2637b4a010]
[Apr 23 07:40:02.145] [ET_NET 10] DIAG: (TSContSchedule_test.check) pass [should be the same thread]
Traffic Server 10.0.0 Apr 23 2021 07:24:41 docker-gd-2
traffic_server: using root directory '/var/tmp/ausb-7736.15400/schedule_on_thread/ts
```

The output is missing 
```
(TSContSchedule_test.check) pass [should no be the same thread]
```

The test case command is just a print.  The real test is launched from the plugin init.  Perhaps the test is shutting down before the final bits of the test complete?

**Comment by duke8253** [comment]
Hmm, haven't seen this before, let's see if it appears again.

**Comment by ywkaras** [comment]
That reminds me a little of problems I saw with this PR that adds a couple of new Au tests.  I had to make a few tweaks to the core to get them to work:  https://github.com/apache/trafficserver/pull/6832/files#diff-cf25e3f0fdf3c4f2ff21559a905429230def7afc1bb6815a3c33209742ff07fb
