### ISSUE TITLE
Can ATS be build on platforms like ARM, PPC, MIPS ?

### ISSUE THREAD

**Issue by Kullu14** [apache/trafficserver#7754]
Is it possible to build ATS on other platforms like ARM, PPC, MIPS ? Has anyone tried it yet ?

**Comment by WolfgangBai** [comment]
I only test ARM, It is Ok.

**Comment by Kullu14** [comment]
Did you have to do any modifications to make the build of trafficserver work on ARM platforms?

**Comment by WolfgangBai** [comment]
1.luajit can't compile, I disable it by --disable-luajit. 
2. machine page size may have problem. it need Memory alignment. you can search STORE_BLOCK_SIZE in ATS code.it may fix in latest code.

**Comment by Kullu14** [comment]
I did disable luajit. Have cross-compiled trafficserver for ARM platform ?

**Comment by WolfgangBai** [comment]
I only compile in ARM machine.

**Comment by Kullu14** [comment]
Okay Thank you for your help. I tried to cross-compiled ARM on x86-64 machine 
I get following error
/bin/sh: ./CompileParseRules: cannot execute binary file: Exec format error

**Comment by WolfgangBai** [comment]
The problem has nothing to do with ATS，You can see the link below.
https://askubuntu.com/questions/648555/bash-program-cannot-execute-binary-file-exec-format-error

**Comment by zwoop** [comment]
It has been possible to build and run on 64-bit ARM in the past. I haven't tried lately.

**Comment by Kullu14** [comment]
@WolfgangBai it is trying to execute ./CompileParseRules to detect the leaks by executing following command 
"ParseRulesCType: CompileParseRules
        LSAN_OPTIONS='detect_leaks=0' ./CompileParseRules" while cross-compiling trafficserver 
this is build using aarch64 crosscompiler n trying to execute in host Machine (which x86_64) for me that why getting above error.

**Comment by Kullu14** [comment]
@zwoop  have you cross-compiled it or ran it on ARM machine only

**Comment by bryancall** [comment]
Talking to the community and we would need an owner for MIPS and PPC.  We are interested in supporting ARM and M1 chips going forward and are interested in setting up CI to compile on those platforms.

Please reopen if you want to support MIPS or PPC.
