### ISSUE TITLE
Presence of (unused) strategies.yaml causes request to 503

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#7785]
Here is the Au test:  https://github.com/ywkaras/trafficserver/commit/9b6857fe42d05e645a3faa2802ef993db60e7d14

If I change line 92 to `if False:` , the request returns 200.

Here is the debug trace:  https://gist.github.com/ywkaras/12286036e422666f39379ea0a5c941cb

**Comment by ywkaras** [comment]
Here is the debug trace when there is no strategies.yaml:  https://gist.github.com/ywkaras/300e5943adae1891efed8d510216f72d

**Comment by ywkaras** [comment]
Seeing this in the debug trace:
```
[May  6 02:06:56.667] traffic_server DEBUG: <HostStatus.cc:443 (createHostStat)> (host_statuses) stat name: proxy.process.host_status.172.17.0.2, data: HOST_STATUS_UP,ACTIVE:UP:0:0,LOCAL:UP:0:0,MANUAL:UP:0:0,SELF_DETECT:UP:0
[May  6 02:06:56.667] traffic_server DEBUG: <HostStatus.cc:319 (setHostStatus)> (host_statuses) for host 172.17.0.2 set status: HOST_STATUS_DOWN, Reason:SELF_DETECT
```
Even though `proxy.config.http.parent_proxy.self_detect` is set to 0.

**Comment by ywkaras** [comment]
Looks like this is where it's marked down:  https://github.com/apache/trafficserver/blob/f7939769974a54969c18159d65d9ba05a07331f7/proxy/http/remap/NextHopSelectionStrategy.cc#L186

**Comment by jrushford** [comment]
@ywkaras, yes and that’s what’s intended.  You override the self detect down in the particular strategy by setting “ignore_self_detect: true”

From: Walt Karas ***@***.***>
Reply-To: apache/trafficserver ***@***.***>
Date: Wednesday, May 5, 2021 at 8:52 PM
To: apache/trafficserver ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [apache/trafficserver] Presence of (unused) strategies.yaml causes request to 503 (#7785)


Looks like this is where it's marked down: https://github.com/apache/trafficserver/blob/f7939769974a54969c18159d65d9ba05a07331f7/proxy/http/remap/NextHopSelectionStrategy.cc#L186<https://urldefense.com/v3/__https:/github.com/apache/trafficserver/blob/f7939769974a54969c18159d65d9ba05a07331f7/proxy/http/remap/NextHopSelectionStrategy.cc*L186__;Iw!!CQl3mcHX2A!QkUApe6FxmeLiKOxwxeCHrMWaBwaowXFJQFSM6a1oPMXwsB6et8EWUspJ3aJbDwlYxiemi8$>

**Comment by ywkaras** [comment]
Works as designed.  Any local host address will be marked as down, if it is used as a host in strategies.yaml, regardless of any self detect settings.
