### ISSUE TITLE
Reloadable plugins eventually causes ATS to crash on config reload

### ISSUE THREAD

**Issue by mtorluemke** [apache/trafficserver#7846]
After running ATS9 for ~45 days (reloading configs once/day), crashes are seen when configs are reloaded with a message like: 

`traffic_manager[<<PID>>]: warning: Could not load shared library symbols for 8 libraries, e.g. /var/run/trafficserver/<<UUID>>/<<ATS installed directory>>/plugins/conf_remap.so.`

And, the stack trace is always: 

`RemapPlugins::run_single_remap() RemapProcessor::perform_remap(Continuation*, HttpTransact::State*) HttpSM::do_remap_request(bool) HttpSM::set_next_state() HttpSM::call_transact_and_set_next_state(void (*)(HttpTransact::State*)) HttpSM::state_api_callout(int, void*) HttpSM::state_api_callback(int, void*) TSHttpTxnReenable INKContInternal::handle_event(int, void*) APIHook::invoke(int, void*) const health_check_origin stats_origin HttpSM::state_read_client_request_header(int, void*) HttpSM::main_handler(int, void*) HttpSM::state_add_to_list(int, void*) HttpSM::attach_client_session(ProxyTransaction*, IOBufferReader*) ProxyTransaction::new_transaction(bool) Http1ClientSession::release(ProxyTransaction*) ProxySession::state_api_callout(int, void*) TSHttpSsnReenable Http1ClientSession::new_connection(NetVConnection*, MIOBuffer*, IOBufferReader*) HttpSessionAccept::accept(NetVConnection*, MIOBuffer*, IOBufferReader*) ProtocolProbeTrampoline::ioCompletionEvent(int, void*) read_signal_and_update(int, UnixNetVConnection*) UnixNetVConnection::net_read_io(NetHandler*, EThread*) NetHandler::process_ready_list() NetHandler::waitForActivity(long) non-virtual thunk to NetHandler::waitForActivity(long) EThread::execute_regular() EThread::execute() spawn_thread_internal(void*)`

**Comment by randall** [comment]
Wasn't not the case? Not a time-based issue, rather a double-delete issue: https://github.com/apache/trafficserver/pull/7862

**Comment by bryancall** [comment]
If this is still an issue please reopen.  @vmamidi Says this was fixed by #7862.
