### ISSUE TITLE
Should add log format for whether origin TLS connection resumed an existing TLS session

### ISSUE THREAD

**Issue by shinrich** [apache/trafficserver#7850]
With PR #7479 ATS support session reuse for connections to the origin.  For the client-side request we can log `%<cqssr>` which indicates whether the user-agent connect was started by resuming an existing TLS connection.

We should have a similar entry for the connection from ATS to origin.  Maybe `%<pqssr>`

https://docs.trafficserver.apache.org/en/latest/admin-guide/logging/formatting.en.html?highlight=logging%20format#ssl-encryption

**Comment by zwoop** [comment]
Remember to clear Milestones and Projects when closing a PR.
