### ISSUE TITLE
SEGV on CacheDisk destructor

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#7865]
```
[ 00 ] libpthread-2.17.so waitpid 
[ 01 ] traffic_server crash_logger_invoke(int, siginfo_t*, void*) ( Crash.cc:165 ) 
[ 02 ] libpthread-2.17.so 
[ 03 ] traffic_server CacheDisk::~CacheDisk() ( List.h:293 ) 
[ 04 ] traffic_server CacheDisk::~CacheDisk() ( CacheDisk.cc:112 ) 
[ 05 ] traffic_server CacheProcessor::diskInitialized() ( Cache.cc:767 ) 
[ 06 ] traffic_server CacheDisk::openStart(int, void*) ( CacheDisk.cc:213 ) 
[ 07 ] traffic_server AIOCallbackInternal::io_complete(int, void*) ( eventsystem/I_Continuation.h:160 ) 
[ 08 ] traffic_server EThread::process_event(Event*, int) ( I_Continuation.h:160 ) 
[ 09 ] traffic_server EThread::process_queue(Queue<Event, Event::Link_link>*, int*, int*) ( UnixEThread.cc:170 ) 
[ 10 ] traffic_server EThread::execute_regular() ( UnixEThread.cc:230 ) 
[ 11 ] traffic_server spawn_thread_internal(void*) ( Thread.cc:85 ) 
[ 12 ] libpthread-2.17.so start_thread 
```
Affected version: 8.1.2

**Comment by masaori335** [comment]
It looks like ATS found a bad disk and tried to delete it, but got SEGV on `disk_vols[i]->dpb_queue.pop()`.

https://github.com/apache/trafficserver/blob/cbb20d4fe05e1598943590a1a65fbb2d3f5015d2/iocore/cache/Cache.cc#L764-L767

https://github.com/apache/trafficserver/blob/cbb20d4fe05e1598943590a1a65fbb2d3f5015d2/iocore/cache/CacheDisk.cc#L117

**Comment by shinrich** [comment]
About 6 months ago, I spent many iterations trying to fix our crash on bad disk problem.  What version are you running?  I thought I had pushed those fixes to master.

**Comment by masaori335** [comment]
The version we got this crash is almost the same as the current head of the 8.1.x branch.

**Comment by shinrich** [comment]
Take a look at PR #7218.  I thought I had to make multiple attempts here, but this is the only relevant looking PR I see on master.  I'll review my internal work and make sure it all made to to ASF.  It could be that I delayed making an ASF PR until we got it all under control.

**Comment by shinrich** [comment]
Take a look at PR #7218.  I thought I had to make multiple attempts here, but this is the only relevant looking PR I see on master.  I'll review my internal work and make sure it all made to to ASF.  It could be that I delayed making an ASF PR until we got it all under control.
