### ISSUE TITLE
Unpin the docs Sphinx package once 4.x has the fix for building our code

### ISSUE THREAD

**Issue by bneradt** [apache/trafficserver#7941]
In order for our Sphinx doc build to succeed, we have to pin the Spinx package to 3.x rather than the latest 4.x. This is due to the following Sphinx issue we filed:
https://github.com/sphinx-doc/sphinx/issues/9322

To unblock our doc builds, our [doc/Pipfile](https://github.com/apache/trafficserver/blob/3d584af796bad1e9e3c03b2af5485b630ffedafb/doc/Pipfile#L33) was configured to pin the Sphinx package to 3.x via this PR: #7940. 

There is a Sphinx PR open to address the bug which blocks our doc builds on 4.x:
https://github.com/sphinx-doc/sphinx/pull/9334

Once that Sphinx PR is merged in and released, we should unpin our Sphinx package version. I'm filing this issue to document and remind ourselves to do this.

**Comment by bryancall** [comment]
@bneradt This looks like it was fixed in 4.0.3
