### ISSUE TITLE
PANIC: unprotected error in call to Lua API (undefined symbol: lua_gettop)

### ISSUE THREAD

**Issue by vipergc** [apache/trafficserver#7960]
My environment is Lua-5.4.2 Luasocket-3.0-rc1, when I direct run lua script, it work success. When i run it within c language, 

Error Msg is :
PANIC: unprotected error in call to Lua API (error running script: error loading module 'socket.core' from file '/usr/local/lib/lua/5.4/socket/core.so':  undefined symbol: lua_gettop)
Aborted(core dumped)

Does anyone know why? 

My code is follow:
test.lua:
#!/usr/local/bin/lua
local socket = require("socket")
print(socket._VERSION)

main.c:
int main(void)
{
    lua_State *L;
    L = luaL_newstate();
    luaopen_base(L);
    luaL_openlibs(L);

    printf("lua enter\n");
    if (luaL_dofile(L, "test.lua"))
    {
        luaL_error(L, "error running script: %s", lua_tostring(L, -1));
    }
    printf("lua exit\n");

    while(1) pause();
    lua_close(L);
    return 0;
}

**Comment by shukitchan** [comment]
What version of ATS you are using? 

Anyway, we recommend to use luajit with ATS for the plugin. In 7.x luajit is part of the binary and in 8.x and beyond, the ATS lua plugin is compiled only with luajit is found in the system. 

For luasocket to work with luajit, you need to compile that accordingly . This is what i do 

e.g. 

```
curl -R -O http://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz && \
tar zxf LuaJIT-2.1.0-beta3.tar.gz && \
cd LuaJIT-2.1.0-beta3 && \
make && \
sudo make install

wget https://github.com/diegonehab/luasocket/archive/v3.0-rc1.tar.gz && \
tar zvf v3.0-rc1.tar.gz && \
cd luasocket-3.0-rc1 && \
sed -i "s/LDFLAGS_linux=-O -shared -fpic -o/LDFLAGS_linux=-O -shared -fpic -L\/usr\/lib -lluajit-5.1 -o/" src/makefile && \
ln -sf /usr/lib/libluajit-5.1.so.2.1.0 /usr/lib/libluajit-5.1.so && \
make && \
sudo make install-unix

```

**Comment by shukitchan** [comment]
And if you are just running the C program you are showing, i think you should use lua5.1 instead and see if it works.

**Comment by shukitchan** [comment]
I looked like it is not specific to ATS.
Closing for now.

**Comment by vipergc** [comment]
> And if you are just running the C program you are showing, i think you should use lua5.1 instead and see if it works.

I have tried it in lua-5.1, the problem is the same.

**Comment by vipergc** [comment]
> What version of ATS you are using?
> 
> Anyway, we recommend to use luajit with ATS for the plugin. In 7.x luajit is part of the binary and in 8.x and beyond, the ATS lua plugin is compiled only with luajit is found in the system.
> 
> For luasocket to work with luajit, you need to compile that accordingly . This is what i do
> 
> e.g.
> 
> ```
> curl -R -O http://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz && \
> tar zxf LuaJIT-2.1.0-beta3.tar.gz && \
> cd LuaJIT-2.1.0-beta3 && \
> make && \
> sudo make install
> 
> wget https://github.com/diegonehab/luasocket/archive/v3.0-rc1.tar.gz && \
> tar zvf v3.0-rc1.tar.gz && \
> cd luasocket-3.0-rc1 && \
> sed -i "s/LDFLAGS_linux=-O -shared -fpic -o/LDFLAGS_linux=-O -shared -fpic -L\/usr\/lib -lluajit-5.1 -o/" src/makefile && \
> ln -sf /usr/lib/libluajit-5.1.so.2.1.0 /usr/lib/libluajit-5.1.so && \
> make && \
> sudo make install-unix
> ```

What is the ATS? Do you have download link?

**Comment by shukitchan** [comment]
ATS is apache traffic server. you are submitting your issue here already - https://github.com/apache/trafficserver/
