### ISSUE TITLE
disable_freelist flag '-f' appears to do nothing

### ISSUE THREAD

**Issue by c-taylor** [apache/trafficserver#7973]
https://github.com/apache/trafficserver/blob/f8ec81d7b8c28ca00ceedff282a76af47314dfcb/src/traffic_server/traffic_server.cc#L201

The '-f' flag and all documentation exists, but it appears to have no action.
This should be removed.

**Comment by duke8253** [comment]
Hmm, which version are you on? Can you find this line in `traffic_server.cc`
```
ink_freelist_init_ops(cmd_disable_freelist, cmd_disable_pfreelist);
```

**Comment by duke8253** [comment]
Pretty sure it's working as intended, `-f` disables freelist only in Class Allocators, `-F` includes `-f`, and also disables it in Proxy Allocators.

**Comment by c-taylor** [comment]
Thanks for looking at this, I think we can file it under "fool in a hurry".

I had been testing with '-F' and reading the behaviour of `cmd_disable_pfreelist` in ProxyAllocator.cc and I_ProxyAllocator.h.
I missed `ink_freelist_init_ops`.
