### ISSUE TITLE
Load balancing using parent selection

### ISSUE THREAD

**Issue by taojishou** [apache/trafficserver#8020]
How to realize the load balancing? the source station has five IP addresses . plz help me

**Comment by mlibbey** [comment]
We:
- in remap.config the inbound domain to the same domain. Like
`map http://example.com/ http://example.com`
- use parent.config (https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/files/parent.config.en.html) to balance the next hops:
`dest_host=example.com scheme=http parent="machine1.example.com:80,machine2.example.com:80"  round_robin=strict go_direct=false`

In the latest ATS, there is a nicer strategies.yaml https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/files/strategies.yaml.en.html that can be referred to directly in the remap line.

**Comment by jrushford** [comment]
@taojishou may we close this issue?

**Comment by bryancall** [comment]
If this is still an issue please reopen.
