### ISSUE TITLE
Add PS debug to nexthop during mark up/down

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#8050]
In relation to #8049 , we should add similar debug to the new nexthop strategies during parent mark down and up

**Comment by rob05c** [comment]
Petition to not mark stale or close, this is very useful and very easy. In fact, adding good-first-issue

**Comment by Mayuresh0072** [comment]
@rob05c @ezelkow1  Hi, can you please assign me this issue , I am interested in solving this issue and please guide me

**Comment by cybertunnel** [comment]
Is this what you had in mind? `[Jul  3 09:49:57.824] [ET_NET 9] NOTE: [0] NextHop initially marked as down p1.example.com for request example.com`
