### ISSUE TITLE
url_sig plugin pristine plugin arg should be in the config file

### ISSUE THREAD

**Issue by traeak** [apache/trafficserver#8065]
Since the url_sig plugin uses a configuration file the pristine plugin argument should likely be moved into the config file as an option.

**Comment by rob05c** [comment]
I'll note URL Sig is the old format which is never going to be standardized. URI Signing is the new protocol which is likely to be standard, which everyone should be using if possible.

But, I don't object to this, if someone wants to put in the time.

**Comment by traeak** [comment]
Pr addressing this was merged into master.
