### ISSUE TITLE
Curr conn..

### ISSUE THREAD

**Issue by taojishou** [apache/trafficserver#8072]
When the number of curr conn exceeds 8.5k, it is unstable .
Can high concurrency configuration parameters be adjusted?

**Comment by shinrich** [comment]
What version is this running?  How is it unstable?  Does traffic_server crash? Is the current connection metric unreliable?

**Comment by taojishou** [comment]
v9.0.2   curr connexceeds 8.5k ， half the bandwidth
![image](https://user-images.githubusercontent.com/20332592/126278978-594125b1-970f-404c-a310-80e382f27d8f.png)

**Comment by taojishou** [comment]
traffic_server no crash, but link speed will become very slow

**Comment by taojishou** [comment]
I doubt the TCP configuration of the system, but I have checked them all   bosh  CentOS 7.6 and CentOS 8.0 have the same problem

**Comment by shinrich** [comment]
Can you share your current records.config settings?  I.e. output of "traffic_ctl config match proxy.config"?

What are you traffic characteristics?  Smaller responses or larger responses?  Only GET traffic or a mix of GET and POST?  I assume all TLS.  Are you using HTTP/2?

There is also tuning at the OS level with the sys.net settings.  @bryancall or @zwoop can point you to guidance there if you have concerns at that level.

In our environment we regularly run on Rhel 7 with 80K current connections and our RPS grows accordingly.  Our traffic is smaller bodies with a mix of GET and POST.  This has been fine for both 9.0.x and now 9.1.x.

**Comment by taojishou** [comment]
CONFIG proxy.config.exec_thread.autoconfig INT 1
CONFIG proxy.config.exec_thread.autoconfig.scale FLOAT 1.0
CONFIG proxy.config.exec_thread.limit INT 2
CONFIG proxy.config.accept_threads INT 1
CONFIG proxy.config.task_threads INT 2
CONFIG proxy.config.cache.threads_per_disk INT 8
CONFIG proxy.config.exec_thread.affinity INT 1
#    https://docs.trafficserver.apache.org/records.config#proxy.config.http.server_ports
#CONFIG proxy.config.http.server_ports STRING 80 80:ipv6
CONFIG proxy.config.http.server_ports STRING 80 443:proto=http2;http:ssl
#     https://docs.trafficserver.apache.org/records.config#proxy-config-http-insert-response-via-str
CONFIG proxy.config.http.insert_request_via_str INT 1
CONFIG proxy.config.http.insert_response_via_str INT 0
# Parent proxy configuration, in addition to these settings also see parent.config. Docs:
#    https://docs.trafficserver.apache.org/records.config#parent-proxy-configuration
CONFIG proxy.config.http.parent_proxy_routing_enable INT 1
CONFIG proxy.config.http.parent_proxy.retry_time INT 300
CONFIG proxy.config.http.parent_proxy.connect_attempts_timeout INT 30
CONFIG proxy.config.http.forward.proxy_auth_to_parent INT 0
CONFIG proxy.config.http.uncacheable_requests_bypass_parent INT 1
CONFIG proxy.config.http.keep_alive_no_activity_timeout_in INT 180
CONFIG proxy.config.http.keep_alive_no_activity_timeout_out INT 180
CONFIG proxy.config.http.transaction_no_activity_timeout_in INT 30
CONFIG proxy.config.http.transaction_no_activity_timeout_out INT 30
CONFIG proxy.config.http.transaction_active_timeout_in INT 900
CONFIG proxy.config.http.transaction_active_timeout_out INT 0
CONFIG proxy.config.http.accept_no_activity_timeout INT 120
CONFIG proxy.config.net.default_inactivity_timeout INT 86400
CONFIG proxy.config.http.connect_attempts_max_retries INT 3
CONFIG proxy.config.http.connect_attempts_max_retries_dead_server INT 1
CONFIG proxy.config.http.connect_attempts_rr_retries INT 3
CONFIG proxy.config.http.connect_attempts_timeout INT 180
CONFIG proxy.config.http.post_connect_attempts_timeout INT 1800
CONFIG proxy.config.http.down_server.cache_time INT 60
CONFIG proxy.config.http.down_server.abort_threshold INT 10
CONFIG proxy.config.http.negative_caching_enabled INT 0
CONFIG proxy.config.http.negative_caching_lifetime INT 1800
#    https://docs.trafficserver.apache.org/records.config#proxy-user-variables
CONFIG proxy.config.http.insert_client_ip INT 1
CONFIG proxy.config.http.insert_squid_x_forwarded_for INT 1
CONFIG proxy.config.http.push_method_enabled INT 0
CONFIG proxy.config.http.cache.http INT 1
CONFIG  proxy.config.cache.enable_read_while_writer  INT 1
CONFIG  proxy.config.http.background_fill_active_timeout  INT 0
CONFIG  proxy.config.http.background_fill_completed_threshold  FLOAT 0.000000
CONFIG  proxy.config.cache.max_doc_size  INT 0
CONFIG proxy.config.http.cache.max_open_read_retries INT 38000
CONFIG proxy.config.http.cache.open_read_retry_time INT 100
CONFIG proxy.config.http.cache.ignore_client_cc_max_age INT 1
CONFIG proxy.config.http.normalize_ae INT 1
CONFIG proxy.config.http.cache.cache_responses_to_cookies INT 1
CONFIG proxy.config.http.cache.cache_urls_that_look_dynamic INT 1
    # https://docs.trafficserver.apache.org/records.config#proxy-config-http-cache-when-to-revalidate
CONFIG proxy.config.http.cache.when_to_revalidate INT 0
    # https://docs.trafficserver.apache.org/records.config#proxy-config-http-cache-required-headers
CONFIG proxy.config.http.cache.required_headers INT 2
CONFIG proxy.config.http.cache.heuristic_min_lifetime INT 3600
CONFIG proxy.config.http.cache.heuristic_max_lifetime INT 86400
CONFIG proxy.config.http.cache.heuristic_lm_factor FLOAT 0.10
CONFIG proxy.config.net.connections_throttle INT 30000
CONFIG proxy.config.net.max_connections_in INT 30000
CONFIG proxy.config.net.max_requests_in INT 0
CONFIG proxy.config.cache.ram_cache.size INT 300G
CONFIG proxy.config.cache.ram_cache_cutoff INT 4194304
    # https://docs.trafficserver.apache.org/records.config#proxy-config-cache-limits-http-max-alts
CONFIG proxy.config.cache.limits.http.max_alts INT 5
    # https://docs.trafficserver.apache.org/records.config#proxy-config-cache-max-doc-size
CONFIG proxy.config.cache.max_doc_size INT 0
CONFIG proxy.config.cache.min_average_object_size INT 18000
CONFIG proxy.config.log.logging_enabled INT 3
CONFIG proxy.config.log.max_space_mb_for_logs INT 25000
CONFIG proxy.config.log.max_space_mb_headroom INT 1000
CONFIG proxy.config.log.rolling_enabled INT 1
CONFIG proxy.config.log.rolling_interval_sec INT 86400
CONFIG proxy.config.log.rolling_size_mb INT 10
CONFIG proxy.config.log.auto_delete_rolled_files INT 1
CONFIG proxy.config.log.periodic_tasks_interval INT 5
# These settings control remapping, and if the proxy allows (open) forward proxy or not. Docs:
CONFIG proxy.config.url_remap.remap_required INT 1
    # https://docs.trafficserver.apache.org/records.config#proxy-config-url-remap-pristine-host-hdr
CONFIG proxy.config.url_remap.pristine_host_hdr INT 0
    # https://docs.trafficserver.apache.org/records.config#reverse-proxy
CONFIG proxy.config.reverse_proxy.enabled INT 1
CONFIG proxy.config.ssl.client.verify.server.policy STRING PERMISSIVE
CONFIG proxy.config.ssl.client.verify.server.properties STRING ALL
CONFIG proxy.config.ssl.client.CA.cert.filename STRING NULL
CONFIG proxy.config.ssl.server.cert.path STRING /etc/trafficserver/ssl/
CONFIG proxy.config.ssl.server.private_key.path STRING /etc/trafficserver/ssl/
CONFIG proxy.config.diags.debug.enabled INT 0
CONFIG proxy.config.diags.debug.tags STRING http|dns
CONFIG proxy.config.dump_mem_info_frequency INT 0
CONFIG proxy.config.http.slow.log.threshold INT 0


The service is VOD cache , all tls and sys.net settings has been adjusted

**Comment by taojishou** [comment]
do you have a system  net optimization scheme?

**Comment by bryancall** [comment]
@taojishou are you still having issues when your number of connections increase?

**Comment by bryancall** [comment]
If this is still an issue please reopen.
