### ISSUE TITLE
Q: how to open debug mode to build

### ISSUE THREAD

**Issue by flymoondust** [apache/trafficserver#8171]
i want to open the debug mode to see the full build messages, but i don't find the way.
my build message:
CX   ***.o
CXX  ***.lo
AR   ***.a
CXXLD  ***.la

my compile command:
autoreconf -vfi
./configure
make

**Comment by brbzull0** [comment]
You can use VERBOSE option to run the make `V=1 make`

**Comment by randall** [comment]
or configure with `--disable-silent-rules` set.

**Comment by flymoondust** [comment]
it works,thanks.
Command as below:
make V=1
