### ISSUE TITLE
Monitoring traffic server

### ISSUE THREAD

**Issue by Bharat786** [apache/trafficserver#8174]
I have deployed traffic server and wants to monitor it.
But I cant find any exporter for traffic server, can someone help how I can monitor?

**Comment by jvgutierrez** [comment]
We're successfully using in production https://github.com/gdvalle/trafficserver_exporter via the debian version packaged for buster: https://packages.debian.org/sid/main/prometheus-trafficserver-exporter

**Comment by Bharat786** [comment]
Thanks for the help,
But when i am starting the exporter, it is giving metrics at port 9122 but its logs are also showing 

````
DEBUG:trafficserver_exporter.collector:Metric trafficserver_transactions_total value proxy.node.http.origin_server_total_transactions_count not found
DEBUG:trafficserver_exporter.collector:Metric trafficserver_transactions_total value proxy.node.http.user_agents_total_transactions_count not found
DEBUG:trafficserver_exporter.collector:Collection complete
WARNING:trafficserver_exporter.trafficserver_exporter:Unable to read pidfile; process metrics will fail!
````

and when I am specifying the pid file while starting the exporter like 
./prometheus-trafficserver-exporter -vv --endpoint=http://ip/_stats --pidfile /usr/local/var/trafficserver/server.lock

it is showing this error 

````
DEBUG:trafficserver_exporter.collector:Gathering metrics
DEBUG:trafficserver_exporter.collector:Metric trafficserver_transactions_total value proxy.node.http.origin_server_total_transactions_count not found
DEBUG:trafficserver_exporter.collector:Metric trafficserver_transactions_total value proxy.node.http.user_agents_total_transactions_count not found
DEBUG:trafficserver_exporter.collector:Collection complete
DEBUG:trafficserver_exporter.trafficserver_exporter:Registering ProcessCollector
Traceback (most recent call last):
  File "./prometheus-trafficserver-exporter", line 11, in <module>
    load_entry_point('trafficserver-exporter==0.3.2', 'console_scripts', 'trafficserver_exporter')()
  File "/usr/lib/python3/dist-packages/trafficserver_exporter/trafficserver_exporter.py", line 126, in main
    pid=lambda: get_ts_pid(args.pidfile), namespace="trafficserver"
  File "/usr/lib/python3/dist-packages/prometheus_client/registry.py", line 29, in register
    duplicates))
ValueError: Duplicated timeseries in CollectorRegistry: {'trafficserver_process_cpu_seconds_total', 'trafficserver_process_open_fds', 'trafficserver_process_resident_memory_bytes', 'trafficserver_process_start_time_seconds', 'trafficserver_process_cpu_seconds_created', 'trafficserver_process_virtual_memory_bytes', 'trafficserver_process_max_fds'}
````

**Comment by rob05c** [comment]
There are a lot of different things you can monitor, I'm not entirely clear what you want to monitor here.

If you want to monitor system stats (like /proc/net/dev and /proc/loadavg), and/or remap rule statistics, the `stats_over_http` plugin serves those over HTTP:

https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/stats_over_http.en.html

Further, the Apache Traffic Control (ATC) project is a CDN, and part of that is Health Monitoring ATS caches. The ATC Traffic Monitor polls ATS stats_over_http and aggregates, and serves those aggregated stats as well as deciding whether caches are "Healthy" and serving boolean availability:

https://traffic-control-cdn.readthedocs.io/en/latest/admin/traffic_monitor.html

**Comment by bryancall** [comment]
If this is still an issue please reopen.
