### ISSUE TITLE
escalate plugin not working as expected when transforming response through lua

### ISSUE THREAD

**Issue by VibhorGupta1991** [apache/trafficserver#8185]
Hi Team,

I have been facing a weird issue on my traffic server running on version: 9.0.2

My setup has lua enabled and I am transforming the response using the following code 

function modify_response(data,eos)
   ts.debug("modifying response") //this never gets printed in the logs
   return data,eos
end

function do_remap() 
   ts.hook(TS_LUA_RESPONSE_TRANSFORM, modify_response)
   return 0
end

I recently enabled escalate plugin to proxy the request to a different origin when the first origin returns a 5xx. 
And the retry request on the second origin doesn't work until I comment the hook mentioned above. I did a ts.debug inside the modify_response function but I am not able to see this in logs as well for the retry request. So I suspect its not executing the function but stuck somewhere else.

Have been stuck with this for a while. Has anyone else ever faced this issue? 

Thank you!

**Comment by shukitchan** [comment]
Not too sure what's wrong. Will give it a try this week. 

Meanwhile, are there any messages in diags.log/traffic.out/error.log ?

**Comment by VibhorGupta1991** [comment]
Hey,

Nothing in the diags.log but I could see the following in access logs for a single request from the browser.

172.16.211.80 - - [03/Aug/2021:18:52:45 -0000] "GET http://<origin>/<path>?test&ss&snkss&ss HTTP/1.1" 500 0 500 0 0 0 878 0 979 169 0 DIRECT FIN FIN TCP_MISS_X_REDIRECT
172.16.211.80 - - [03/Aug/2021:18:52:45 -0000] "GET http://<failover_origin>/<path>?test&ss&snkss&ss HTTP/1.1" 000 0 200 0 0 0 856 0 968 293 31 DIRECT TIMEOUT FIN ERR_CLIENT_ABORT
172.16.211.80 - - [03/Aug/2021:18:53:16 -0000] "GET http://<origin>/<path>?test&ss&snkss&ss HTTP/1.1" 500 0 500 0 0 0 878 0 979 169 0 DIRECT FIN FIN TCP_MISS_X_REDIRECT
172.16.211.80 - - [03/Aug/2021:18:53:16 -0000] "GET http://<failover_origin>/<path>?test&ss&snkss&ss HTTP/1.1" 000 0 200 0 0 0 856 0 968 293 30 DIRECT TIMEOUT FIN ERR_CLIENT_ABORT
172.16.211.80 - - [03/Aug/2021:18:53:48 -0000] "GET http://<origin>/<path>?test&ss&snkss&ss HTTP/1.1" 500 0 500 0 0 0 878 0 979 169 0 DIRECT FIN FIN TCP_MISS_X_REDIRECT
172.16.211.80 - - [03/Aug/2021:18:53:48 -0000] "GET http://failover_origin/<path>?test&ss&snkss&ss HTTP/1.1" 000 0 200 0 0 0 856 0 968 293 30 DIRECT TIMEOUT FIN ERR_CLIENT_ABORT
.
.
.
.

Two things to note here:
a) the response from origin is instant and responds with 500 while the retried request on the failover origin returns a 200 from origin but the proxy status code is 000 as its getting timed out with ERR_CLIENT_ABORT.
b) it looks like its somehow going into recursion as well

**Comment by shukitchan** [comment]
I suspect that the work done by escalate plugin is making the transform event to not come through. After all, the transform is set up for the original response , which is now abandoned. And with the transform not getting run, the original continuation cannot resume as well. Thus resulting in error. Perhaps we need to register the transform only if we know we are not needing escalate to do the work (e.g. do it in do_os_response function instead of do_remap). And then we need to have separate transform registered for both the original and retry response. I suppose you want the same transform to be done on either the original and retry response when either one of them comes through. right ? 

Can you also show me how you are using the escalate plugin ?  (i.e. your remap.config for the line using both lua and escalate plugins, i think ) That can help me a bit and see what's the right way to make them work together.

**Comment by VibhorGupta1991** [comment]
Hi shukitchan,

Sorry for the delay, had been struggling with few other things so didn't find time to look at this.

About your queries:
1) Yes, we would eventually want to run the same transform on both the original and retry response but for now only running the transform also works. 
Few queries about the do_os_response method, can you confirm?
a) Only one of the functions either do_remap or do_os_response gets called for a transaction?
b) I believe only few hooks can be attached in the do_os_response function, so I can't attach other hooks in do_remap() which are not allowed in do_os_response? 
c) I can't find any documentation around this do_os_response() function hence struggling a little bit with it.
 
2) I am trying to use do_os_response as per your suggestion but my response is not getting modified even for the original response. I even tried to put a debug message in the do_os_response() function but it doesn't get called it seems. Is there something I am doing wrong here?  

function do_os_response()
        ts.debug("HELLO")
        ts.hook(TS_LUA_RESPONSE_TRANSFORM,modify_response)
end


Please find the remap statement for escalate and lua plugin below:
map / http://server.com @plugin=/usr/local/libexec/trafficserver/escalate.so @pparam=500,404:retry.com @pparam=--pristine @plugin=/usr/local/libexec/trafficserver/tslua.so @pparam=/usr/local/etc/trafficserver/script/L1/simple.lua


Thanks in advance.

**Comment by VibhorGupta1991** [comment]
Hi @shukitchan ,

I was able to make it work by attaching the response transform hook only when the response code is 200 using the code below.

function read_response()
        local code =ts.server_response.get_status()
        if code == 200 then
        ts.hook(TS_LUA_RESPONSE_TRANSFORM,modify_response)
        end
end
function do_remap()
        ts.hook(TS_LUA_HOOK_READ_RESPONSE_HDR,read_response)
        return 0
end


Do you think it is okay to attach a hook inside another hook callback function? It does work but just want to know if it is something that shouldn't be done. 

Thanks

**Comment by shukitchan** [comment]
I think this should be fine.

**Comment by shukitchan** [comment]
To answer a few questions in this issue

1) both do_remap and do_os_response will be called when they are present.
2) Yes. Only a few hooks can be added to do_os_response . Please see https://docs.trafficserver.apache.org/en/latest/admin-guide/plugins/lua.en.html#hook-point-constants

Closing this for now.
