### ISSUE TITLE
Error using lua plugin lpeg.so with trafficserver.

### ISSUE THREAD

**Issue by Bharat786** [apache/trafficserver#8222]
I build trafficserver version 9.0.2 from the source code and since luajit (LuaJIT 2.1.0-beta3) was installed, it was able to generate tslua.so plugin and then i installed lpeg using luarocks, but when i ran trafficserver it is showing this error :

```
[Aug  9 10:37:54.289] [ET_NET 2] NOTE: hosting.config loading ...
[Aug  9 10:37:54.289] [ET_NET 2] NOTE: hosting.config finished loading
[Aug  9 10:37:54.289] [ET_NET 2] NOTE: cache enabled
[Aug  9 10:37:54.331] traffic_server ERROR: [ReverseProxy] failed to add remap rule at /usr/local/etc/trafficserver/remap.config line 203: failed to create instance for plugin /usr/local/libexec/trafficserver/tslua.so: [ts_lua_add_module] lua_pcall /usr/local/etc/trafficserver/script/bidexchange/rewrite.lua failed: error loading module 'lpeg' from file '/usr/local/lib/lua/5.1/lpeg.so':
	/usr/local/lib/lua/5.1/lpeg.so: undefined symbol: lua_gettop
[Aug  9 10:37:54.332] traffic_server WARNING: something failed during BuildTable() -- check your remap plugins!
[Aug  9 10:37:54.332] traffic_server FATAL: remap.config failed to load
```

Dont know what went wrong.can anyone help with this.

**Comment by shukitchan** [comment]
That should be because the lpeg.so is compiled to expect the lua related symbols in the executing context. In a normal lua program, those should be expected to be present. In ATS, they are not and you will need to compile your shared object to require a dynamic link to the luajit library. 

You can check out a similar problem here - https://github.com/apache/trafficserver/issues/5158

**Comment by shukitchan** [comment]
actually you do have https://github.com/luvit/lpeg/blob/master/makefile
you can try out changing 

"DLLFLAGS = -shared -fPIC"

and add " -lluajit-5.1" to the end and then use "make linux" to compile and see.
