### ISSUE TITLE
compress plugin not giving control to modify cached response before compression

### ISSUE THREAD

**Issue by VibhorGupta1991** [apache/trafficserver#8317]
Hi Team,

I have been facing an issue on my traffic server running on version: 9.0.2

My setup has lua and compress plugins enabled and following is my compress config

enabled true
compressible-content-type text/*
cache false
range-request false
remove-accept-encoding true
flush true
supported-algorithms gzip,br

I tried using this config both ways, with my remap rule as well as globally. 

Remap Rule:
map / http://<origin> @plugin=/usr/local/libexec/trafficserver/tslua.so @pparam=/usr/local/etc/trafficserver/script/L1/simple.lua  @plugin=/usr/local/libexec/trafficserver/compress.so @pparam=/usr/local/etc/trafficserver/plugin_configs/compress_rules.config

Inside my lua file, I am trying to modify the response only when its fetched from cache. 

```
function modify_response(data, eos)
	  if ts.ctx['len'] == nil then
		local finalData = "hello" .. data
		local sz = ts.http.resp_transform.get_upstream_bytes()
		if sz ~= TS_LUA_INT64_MAX then
			ts.http.resp_transform.set_downstream_bytes(sz + string.len(finalData))
		end
			ts.ctx["len"] = true
			return finalData, eos
        else
			return data, eos
        end
end

function read_cached_response()
	local cache_status = ts.http.get_cache_lookup_status()
	if cache_status == TS_LUA_CACHE_LOOKUP_HIT_FRESH then
		code = ts.cached_response.get_status()
		if code == 200 or code == 304 then
			ts.hook(TS_LUA_RESPONSE_TRANSFORM,modify_response)
			ts.http.resp_cache_transformed(0)
			ts.http.resp_cache_untransformed(1)
		end
	end
end

function do_remap()						
	ts.hook(TS_LUA_HOOK_CACHE_LOOKUP_COMPLETE,read_cached_response)
	return 0
end

```
I am trying to append "hello" to my response when it comes from cache, but looks like due to the compress plugin I am already getting compressed data due to which my transformation is failing and a blank response is sent to client.  

I tried enabling debug tags for compress plugin and also went through their code, looks like their transform is running before my transform and hence I get compressed data on which I cannot perform any transformation myself. 

Is there a way to run my transform first? or anyway I can delay transformation of compress plugin?

Any help would be appreciated. 

Thank you!

**Comment by shukitchan** [comment]
So you have a compress plugin used in plugin.config ? That's why that is always run before the lua script attached to the remap rule. 

You can try to do the transform in lua added to the plugin.config . And make sure it is before the compress plugin in plugin.config. Also the entry function should be do_global_read_request() instead do_remap() when you are using lua script in plugin.config

Also you then dont need to have the lua plugin and compress plugin in the remap rule.

**Comment by VibhorGupta1991** [comment]
Hi,  nope I had disabled compress in plugin.config when I added it in remap

Here is my current plugin.config

#/usr/local/libexec/trafficserver/compress.so /usr/local/etc/trafficserver/plugin_configs/compress_rules.config
/usr/local/libexec/trafficserver/xdebug.so
/usr/local/libexec/trafficserver/stats_over_http.so
/usr/local/libexec/trafficserver/healthchecks.so /usr/local/etc/trafficserver/plugin_configs/healthchecks.conf

So both my compress plugin and lua plugin are present only in the remap config file and the order is as described in the post above.

**Comment by VibhorGupta1991** [comment]
@shukitchan 

I had made some changes at my end in remap rule to try to make this work by changing the order of compress and lua plugins yesterday. I tried again with the above remap config that I posted and it seems to be working fine now. Will update here if I find the reason / issue at my end why it wasn't working before. 

Thanks a lot

We can close this @shukitchan
