### ISSUE TITLE
8.1.2 don't build on Fedora 34 / GCC 11

### ISSUE THREAD

**Issue by thelounge-zz** [apache/trafficserver#8342]
the only package which can't be rebuilt on F34 and no i don't want TS9 for now :-(

In file included from ../../include/tscore/ink_inet.h:34,
                 from ../../include/tscore/Diags.h:41,
                 from P_RecUtils.h:26,
                 from RecConfigParse.cc:34:
../../include/tscore/BufferWriterForward.h:63:28: error: 'numeric_limits' is not a member of 'std'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                            ^~~~~~~~~~~~~~
../../include/tscore/BufferWriterForward.h:63:43: error: expected primary-expression before 'unsigned'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                                           ^~~~~~~~
../../include/tscore/BufferWriterForward.h: In constructor 'constexpr ts::BWFSpec::BWFSpec()':
../../include/tscore/BufferWriterForward.h:44:24: error: member 'ts::BWFSpec::_max' must be initialized by mem-initializer in 'constexpr' constructor
   44 |   constexpr BWFSpec() {}
      |                        ^
../../include/tscore/BufferWriterForward.h:63:16: note: declared here
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                ^~~~
make[2]: *** [Makefile:719: RecConfigParse.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ../../include/tscore/ink_inet.h:34,
                 from ../../include/tscore/Diags.h:41,
                 from P_RecUtils.h:26,
                 from RecFile.cc:28:
../../include/tscore/BufferWriterForward.h:63:28: error: 'numeric_limits' is not a member of 'std'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                            ^~~~~~~~~~~~~~
../../include/tscore/BufferWriterForward.h:63:43: error: expected primary-expression before 'unsigned'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                                           ^~~~~~~~
../../include/tscore/BufferWriterForward.h: In constructor 'constexpr ts::BWFSpec::BWFSpec()':
../../include/tscore/BufferWriterForward.h:44:24: error: member 'ts::BWFSpec::_max' must be initialized by mem-initializer in 'constexpr' constructor
   44 |   constexpr BWFSpec() {}
      |                        ^
../../include/tscore/BufferWriterForward.h:63:16: note: declared here
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                ^~~~
In file included from ../../include/tscore/ink_inet.h:34,
                 from ../../include/tscore/Diags.h:41,
                 from P_RecUtils.h:26,
                 from RecDebug.cc:24:
../../include/tscore/BufferWriterForward.h:63:28: error: 'numeric_limits' is not a member of 'std'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                            ^~~~~~~~~~~~~~
../../include/tscore/BufferWriterForward.h:63:43: error: expected primary-expression before 'unsigned'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                                           ^~~~~~~~
../../include/tscore/BufferWriterForward.h: In constructor 'constexpr ts::BWFSpec::BWFSpec()':
../../include/tscore/BufferWriterForward.h:44:24: error: member 'ts::BWFSpec::_max' must be initialized by mem-initializer in 'constexpr' constructor
   44 |   constexpr BWFSpec() {}
      |                        ^
../../include/tscore/BufferWriterForward.h:63:16: note: declared here
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                ^~~~
In file included from ../../include/tscore/ink_inet.h:34,
                 from ../../include/tscore/Diags.h:41,
                 from I_RecCore.h:26,
                 from P_RecCore.h:32,
                 from RecCore.cc:30:
../../include/tscore/BufferWriterForward.h:63:28: error: 'numeric_limits' is not a member of 'std'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                            ^~~~~~~~~~~~~~
../../include/tscore/BufferWriterForward.h:63:43: error: expected primary-expression before 'unsigned'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                                           ^~~~~~~~
../../include/tscore/BufferWriterForward.h: In constructor 'constexpr ts::BWFSpec::BWFSpec()':
../../include/tscore/BufferWriterForward.h:44:24: error: member 'ts::BWFSpec::_max' must be initialized by mem-initializer in 'constexpr' constructor
   44 |   constexpr BWFSpec() {}
      |                        ^
../../include/tscore/BufferWriterForward.h:63:16: note: declared here
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                ^~~~
In file included from ../../include/tscore/ink_inet.h:34,
                 from ../../include/tscore/Diags.h:41,
                 from P_RecUtils.h:26,
                 from P_RecCore.cc:33:
../../include/tscore/BufferWriterForward.h:63:28: error: 'numeric_limits' is not a member of 'std'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                            ^~~~~~~~~~~~~~
../../include/tscore/BufferWriterForward.h:63:43: error: expected primary-expression before 'unsigned'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                                           ^~~~~~~~
../../include/tscore/BufferWriterForward.h: In constructor 'constexpr ts::BWFSpec::BWFSpec()':
../../include/tscore/BufferWriterForward.h:44:24: error: member 'ts::BWFSpec::_max' must be initialized by mem-initializer in 'constexpr' constructor
   44 |   constexpr BWFSpec() {}
      |                        ^
../../include/tscore/BufferWriterForward.h:63:16: note: declared here
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                ^~~~
In file included from ../../include/tscore/ink_inet.h:34,
                 from ../../include/tscore/Diags.h:41,
                 from /home/builduser/rpmbuild/BUILD/trafficserver-8.1.2/lib/records/I_RecCore.h:26,
                 from RecHttp.cc:24:
../../include/tscore/BufferWriterForward.h:63:28: error: 'numeric_limits' is not a member of 'std'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                            ^~~~~~~~~~~~~~
../../include/tscore/BufferWriterForward.h:63:43: error: expected primary-expression before 'unsigned'
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                                           ^~~~~~~~
../../include/tscore/BufferWriterForward.h: In constructor 'constexpr ts::BWFSpec::BWFSpec()':
../../include/tscore/BufferWriterForward.h:44:24: error: member 'ts::BWFSpec::_max' must be initialized by mem-initializer in 'constexpr' constructor
   44 |   constexpr BWFSpec() {}
      |                        ^
../../include/tscore/BufferWriterForward.h:63:16: note: declared here
   63 |   unsigned int _max = std::numeric_limits<unsigned int>::max(); ///< Maxium width
      |                ^~~~
make[2]: *** [Makefile:719: RecFile.o] Error 1
make[2]: *** [Makefile:719: RecDebug.o] Error 1
make[2]: *** [Makefile:719: RecCore.o] Error 1
make[2]: *** [Makefile:719: P_RecCore.o] Error 1
make[2]: *** [Makefile:719: RecHttp.o] Error 1
make[1]: *** [Makefile:594: all-recursive] Error 1
make: *** [Makefile:866: all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.qI90Dt (%build)

**Comment by bneradt** [comment]
Thank you @thelounge-zz for reporting this issue. A PR for 8.1.x has been created and should be merged into that branch soon.

**Comment by thelounge-zz** [comment]
please keep in mind that Fedora 33 is EOL in roughly a month and so new releases at https://downloads.apache.org/trafficserver/ would be good!
