### ISSUE TITLE
Conflict between --with-openssl and --with-jemalloc build options

### ISSUE THREAD

**Issue by duke8253** [apache/trafficserver#8490]
While building with `--with-jemalloc`, I keep getting the error message `configure: error: jemalloc has bogus version`. After some digging I found that this started happening after commit https://github.com/apache/trafficserver/commit/3412c4f69552b10779cfe0ce1bc6a71971734491

After that commit, if I specify both `--with-openssl` and `--with-jemalloc` options, I get the error message, if I only specify `--with-jemalloc` everything works as expected.

**Comment by randall** [comment]
I'd guess it's the ` TS_ADDTO(LIBS, [$OPENSSL_LIBS])` in that change. I didn't save off the  value before setting LIBS and restore it after the check.I'll create a PR for that.

**Comment by randall** [comment]
@duke8253 Can you test #8492 and see if that fixes things for you?
