### ISSUE TITLE
cachekey parent_selection_url may be broken

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficserver#8503]
While working on a complicated config I was trying to do:

- use regex_remap to change destination host to a variety of domains slightly different from the original remapped url
- This messes with parent selection so then use cachekey with parent_selection_url to set the PS url back to the original remapped version so that it can land on a certain set of hosts

I can see in the debug the regex_remap changing my url properly, then the cachekey debug setting the parent selection URL back to the old one, however it then finds no parents to use.

Then if I copy and paste my parent.config line for the what should be the new PS-URL and set the dest to be what regex_remap sets it to, then it starts selecting parents. However It then explicitly says "Using Over-Ride String=........" which references the value it should have been via cachekey

So something along the line is checking the wrong PS-URL before it can get into parent selection based on the cachekey ps-url, but then it does use it correctly once it is choosing parents

[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (regex_remap) Target match string is `/west/asset.cmfv'
[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (regex_remap) New URL is estimated to be 143 bytes long, or less
[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (regex_remap) New URL is http://my-dummy.west.invalid/asset.cmfv (length 140)
[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (regex_remap)     matched rule 2 [^/(adswest)/(.*)]
[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (cachekey) cachekey/cachekey.cc:253:CacheKey() setting parent selection url from a remap plugin
[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (cachekey) cachekey/cachekey.cc:266:CacheKey() using remap uri 'http://my-dummy.west.invalid/asset.cmfv'
[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (cachekey) cachekey/cachekey.cc:392:appendPrefix() added static prefix, key: 'http://my-dummy.invalid/'
[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (cachekey) cachekey/cachekey.cc:752:finalize() finalizing parent selection url 'http://my-dummy.invalid//asset.cmfv' from a remap plugin
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <InkAPI.cc:5786 (TSHttpTxnParentSelectionUrlSet)> (parent_select) TSHttpTxnParentSelectionUrlSet() parent_selection_url : addr = 0x2b9eb9fdbe40 val = 0x2b9eb9fdbe48
[Nov  9 01:04:32.562] [ET_NET 16] DIAG: (cachekey) cachekey/cachekey.cc:800:finalize() set parent selection URL to http://my-dummy.invalid//asset.cmfv

[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <HttpTransact.cc:3040 (HandleCacheOpenReadMiss)> (http_trans) [0] [HandleCacheOpenReadMiss] --- MISS
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <HttpTransact.cc:4993 (get_ka_info_from_config)> (http_trans) [0] get_ka_info_from_config, server_info->http_version 65537, check_hostdb 0
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <ParentSelection.cc:117 (findParent)> (parent_select) In ParentConfigParams::findParent(): parent_table: 0x17e1f00.
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <ParentSelection.cc:121 (findParent)> (parent_select) policy.ParentEnable: 1

(This point is where the version without a parent.config line matching the regex_remap'd url ends up finding no parents and setting PARENT_DIRECT, Continues below with version that does have the parent.config line)

[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <ParentSelection.cc:882 (UpdateMatch)> (parent_select) Matched with 0x184fe78 parent node from line 254
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <ParentConsistentHash.cc:147 (selectParent)> (parent_select) ParentConsistentHash::selectParent(): Using a consistent hash parent selection strategy.
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <ParentConsistentHash.cc:80 (getPathHash)> (parent_select) Using Over-Ride String='http://my-dummy.invalid//asset.cmfv'.
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <ParentConsistentHash.cc:211 (selectParent)> (parent_select) Initial parent lookups: 1
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <ParentConsistentHash.cc:310 (selectParent)> (parent_select) Additional parent lookups: 1
[Nov  9 01:04:32.562] [ET_NET 16] DEBUG: <ParentConsistentHash.cc:335 (selectParent)> (parent_select) Chosen parent:..............

**Comment by elsloo** [comment]
I was unable to reproduce this issue. Based on the following line, it appears that the configuration had a `--static-prefix` plugin parameter:

```
(cachekey) cachekey/cachekey.cc:392:appendPrefix() added static prefix, key: 'http://my-dummy.invalid/'
```

This line is only printed when `prefix` is not empty. This variable is actually the configuration instance variable `_prefix` which is passed into `CacheKey::appendPrefix()` and is only set via `Configs::init()` when processing plugin parameters. Without the `--static-prefix` argument, the initial value is not clobbered as shown in this example.
