### ISSUE TITLE
How long does ATS take to reinstate a downed parent?

### ISSUE THREAD

**Issue by amoghyermalkar123** [apache/trafficserver#8519]
ATS version : 8.1.1

To be more descriptive : I'm trying to figure out what is the amount of time a child node takes to reinstate it's respective parent node after it has been marked down due to any reasons.

What I have done:
I have gone through detailed debug logs to find out parameters and timing under which a child node decides to try to mark a parent up after it has been downed by ATS. All I have found is there is some sort of ticker based mechanism, but I'm unclear as to it's timing and deciding factors if any.

Please provide a detailed answer or a documentation link which I can refer to. I have referred parent.config and other such configs but have not found anything helpful that gives me a detailed answer.

Thank you in advance.

**Comment by rob05c** [comment]
The settings are in records.config: 

https://docs.trafficserver.apache.org/en/8.1.x/admin-guide/files/records.config.en.html#parent-proxy-configuration

There are a lot of variables here. 

First, it will retry a parent `proxy.config.http.parent_proxy.fail_threshold` times before marking it down. Each time, the timeout will be `proxy.config.http.parent_proxy.connect_attempts_timeout`. The time before the attempt fails can be up to that time, such as if a firewall is simply dropping packets, but maybe be shorter, such as a firewall returning a TCP Reset. 

If your `proxy.config.http.parent_proxy.total_connect_attempts` is less than `proxy.config.http.parent_proxy.fail_threshold`, the time to mark down will also depend on how long in-between client requests.

After a parent is marked down, ATS will wait `proxy.config.http.parent_proxy.retry_time` before trying it again for a future client request.

ATS will make `proxy.config.http.parent_proxy.per_parent_connect_attempts` to a single parent. Then it will try the next parent (per the parent selection algorithm - round_robin, strict, consistent hash). After making a total of `proxy.config.http.parent_proxy.total_connect_attempts` attempts, it will return an error to the client.

So, the time to reinstate a downed parent after the initial attempt could be as much as `proxy.config.http.parent_proxy.fail_threshold * 
(proxy.config.http.parent_proxy.connect_attempts_timeout + proxy.config.http.parent_proxy.retry_time) * "the time between clients requesting" + 
proxy.config.http.parent_proxy.retry_time + 
proxy.config.http.parent_proxy.connect_attempts_timeout`

Or as little as `proxy.config.http.parent_proxy.fail_threshold`.

Assuming my math is right. Again, there are a lot of variables in-flight here.

This is also assuming you're using parent.config and have `proxy.config.http.parent_proxy_routing_enable` set to `1`. If you're not, the similar settings here will be used instead:

https://docs.trafficserver.apache.org/en/8.1.x/admin-guide/files/records.config.en.html#origin-server-connect-attempts

You might also find this helpful: 

https://docs.trafficserver.apache.org/en/8.1.x/admin-guide/performance/index.en.html#timeout-settings

**Comment by amoghyermalkar123** [comment]
Thank you @rob05c I think that answers my question, also thank you for the documentation links.
Closing the issue.

**Comment by dhairav** [comment]
Thank you @rob05c for the detailed explanation!
