### ISSUE TITLE
Link error under RHEL7 with ATS 9.1.1 and jemalloc.

### ISSUE THREAD

**Issue by pbchou** [apache/trafficserver#8529]
@randall -- We had an issue with the linker when building ATS 9.1.1 under RHEL7. I had no problems with my development box, which is Ubuntu 20.04 LTS, but our build environment is still RHEL7 with the newer compiler installed. The problem was fixed when I reverted #8285 in our internal branch. We had previously built 9.0.2 and 9.1.0 with no issues as well. Any ideas?

```
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /root/trafficserver-9.1.1/src/tscore/.libs/libtscore.so: undefined reference to symbol '_ZdlPv'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /opt/jemalloc521/lib/libjemalloc.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by randall** [comment]
Can you see if https://github.com/apache/trafficserver/pull/8492 fixes things for you?

**Comment by pbchou** [comment]
No, I cannot due to merge conflicts. This is because #8492 depends upon #8048, which is only in the 9.2.x branch or later. The possibility of #8492 was mentioned to my colleague on the slack channel earlier, but it seems to be a different issue since that issue was introduced in 9.2.x according to that issue's reporter in #8490.

**Comment by randall** [comment]
Sorry about that. I'll rollback the change.

**Comment by randall** [comment]
@pbchou When you get a chance, can you try #8533 ?

**Comment by pbchou** [comment]
@randall -- We tested your PR #8533 against 9.1.x in our RHEL7 build environment. It was able to be built successfully.

@bryancall  -- By the way, do we still have RHEL7 in our CI environment? I understand it is getting old.
