### ISSUE TITLE
Proposed lib tool to detect wild writes of heap

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#8535]
This would only be used in test builds.  The test builds could be run in a production environment, but with some perf degradation.

The tool would provide a "private" heap for dynamic memory allocation from a contiguous, page-aligned range.  The test build would require changes to allocate the heap objects to be monitored from this private heap.  All entry point functions to this tool would have to take a single common mutex (slow).  The heap could be implemented with:  https://github.com/wkaras/heap-memory-manager .  The heap's memory pages would be read-only by default.  "alloc" and "free" calls would make the whole heap writable.  For non-error writes, it would be necessary to call a function to enable, then disable, writing to the page(s) containing the variable(s) to be written.

**Comment by SolidWallOfCode** [comment]
Might want to base this on the existing `MemArena` class.

**Comment by ywkaras** [comment]
Ahh linked lists from hell!!!
