### ISSUE TITLE
Feature: Add "logging field" to identify proxy protocol client's IP address (previous proxy hop) 

### ISSUE THREAD

**Issue by shadyabhi** [apache/trafficserver#8544]
Relevant fields for this discussion (from https://docs.trafficserver.apache.org/en/latest/admin-guide/logging/formatting.en.html#admin-logging-fields-network) 

| Field | Source | Description |
| --- | --- | --- |
| chi | Client | IP address of the client’s host |
| pps | Proxy Protocol Source IP | Source IP received via Proxy Protocol context from the LB to the Traffic Server |

With only these relevant fields available, if a `proxy-protocol` client connects to ATS while passing the right `proxy-protocol` headers, both fields `chi` and `pps` are updated with the `true client IP address`, ie, the IP address of the user-agent. (meaning a typical user on the internet)

This means we lose the ability to identify the `IP address` of the previous `hop` when proxy protocol is used. Is there a need for adding a new field that signals the IP address of the `previous hop` when proxy protocol is used?

**Comment by masaori335** [comment]
IMO, the `chi` should always be the `previous hop`. We need to check why it's updated.
