### ISSUE TITLE
Test of thread pool example plugin

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#8561]
The thread_pool example plugin (psi) has some tests, but it's not built nor running. Do we want to maintain this test or KIWF?

https://github.com/apache/trafficserver/tree/master/example/plugins/c-api/thread_pool
https://github.com/apache/trafficserver/tree/master/example/plugins/c-api/thread_pool/test/SDKTest

**Comment by bryancall** [comment]
@masaori335 please create a PR to remove these plugins
