### ISSUE TITLE
Limitations on remap.config

### ISSUE THREAD

**Issue by amoghyermalkar123** [apache/trafficserver#8566]
Hi,

I was wondering about the limit of mappings for remap.config. How many such entries can one remap.config can have, and what could be a point where ATS will start to hit performance bottleneck.

```
map https://something.somehost.com http://127.0.0.1:8000/ \
  @plugin=geoip_acl.so @pparam=country @pparam=allow @pparam=AF @pparam=allow @pparam=AX @pparam=html::/var/www/html/index.nginx-debian.html \
  @plugin=cachekey.so @pparam=--remove-all-params=true \
  @plugin=prefetch.so @pparam=--fetch-policy=simple @pparam=--fetch-path-pattern=/(.*-)(\d+)(.*)/$1{$2+1}$3/ @pparam=--fetch-count=5 @pparam=--metrics-prefix=prefetch @pparam=--front=true @pparam=--log-name=/var/log/trafficserver/prefetch.log
```

**Comment by bryancall** [comment]
In production we have 20 to 30 thousand.  If you are only using `map` the limit should be memory since it is a hash lookup on the host name and a trie for the path.

**Comment by amoghyermalkar123** [comment]
I also have a bunch of `redirects` , you could say if I have N `map` then I'd have N/2 `redirect`. Something along this ratio. 
Would this be problematic and in what way will it affect the system once the N starts to hit 10k ?

I do monitor my system but I want to be proactive about this.

**Comment by bryancall** [comment]
I believe the redirects are also a hashmap on the hostnames.  It has been awhile since I have read over that code.  The issue you would see is higher CPU in that location in the code when running ` perf top`.  We have a bunch of `regex_map`  (the most expensive rule) in our remap files and have 20-30k configuration lines.

**Comment by amoghyermalkar123** [comment]
Got it, thanks alot for this. Closing this issue. :)
