### ISSUE TITLE
which variable represent the http_proxy url?

### ISSUE THREAD

**Issue by bywangxp** [apache/trafficserver#8567]
when use ats to access ,for example:   curl -x xxx.myproxy.com:8080 www.baidu.com

i want print  proxy url:xxx.myproxy.com in access_log.  which variable represent？

**Comment by bywangxp** [comment]
@calavera @janfrode @biilmann  help

**Comment by bryancall** [comment]
We don't get the name of the proxy server that is used from `curl -x`.  We do have the hii, hiih, and php to record the ip and port that the client is connecting to:  https://docs.trafficserver.apache.org/admin-guide/logging/formatting.en.html#network-addresses-ports-and-interfaces

**Comment by mlibbey** [comment]
phn is apparently undocumented, but contains the proxy.config.proxy_name in records.config (https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-proxy-name)

**Comment by bryancall** [comment]
If this is still an issue please reopen.
