### ISSUE TITLE
S3 Auth plugin does not work for consecutive spaces in header

### ISSUE THREAD

**Issue by hejcz** [apache/trafficserver#8583]
According to https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html 

"To create the canonical headers list, convert all header names to lowercase and remove leading spaces and trailing spaces. Convert sequential spaces in the header value to a single space."

Traffic server does not remove sequential spaces from values what in our case leads to different headers signatures calculated by traffic server and minio server we use and 403 error.

**Comment by duke8253** [comment]
fixed by #8579
