### ISSUE TITLE
404 Multi Hop Cycle Issue

### ISSUE THREAD

**Issue by amoghyermalkar123** [apache/trafficserver#8712]
I have a remap on a child node that looks like this - 
```
map http://something.some.com/ http://something.some.com/
```

On parent node, the respective mapping is 
```
map http://something.some.com/ http://originserver.com/
```

I currently have only one parent configured in parent.config, so if for some reason the parent server fails, 
ATS tries to DNS resolve `something.some.com` - this is problematic for me.

`something.some.com` when DNS resolved, points to the child server itself. This results in a 404 Multi Hop.

How can I avoid this?

**Comment by amoghyermalkar123** [comment]
@bryancall please help.

**Comment by amoghyermalkar123** [comment]
My goal is to only use remap as an outbound request formation logic and use parent.config to route to parent. 
If parent is unreachable it should just send 4xx. Not try to DNS resolve the outbound host header.

**Comment by jrushford** [comment]
Try this on the reverse proxy child node.  
remap.config:

`map http://something.some.com/ http://originserver.com/`

parent.config:

`dest_domain=originserver.com port=80 parent="parent.some.com:80" round_robin=false go_direct=true`

If the parent fails, it'll retry by going to the origin directly.  If you don't want your child to go directly to the origin, then change go_direct=false.  In this case, when the parent fails, you'll get a 502 back.

Your parent.som.com is a forward proxy you don't really need the remap.config unless you require remap in records.config.  If you require the remap then your remap.config on the parent is:

`map http://originserver.com/ http://originserver.com/`

**Comment by amoghyermalkar123** [comment]
My concern here is that when a child receives 5xx codes it will mark the parent down. This is problematic in the cases of consistent hash or when we only have one parent. How would we know when it'll be marked back up? What are the counters used here or is it something heuristic?

**Comment by amoghyermalkar123** [comment]
Hi @jrushford , your mappings helped alot, I am indeed not seeing multi-hop cycle anymore with the following configurations : (although I might need to test a bit more)

child remap:
`map http://something.some.com/ http://something.some.com/`

child parent:
`dest_domain=something.some.com method=get port=443 parent="some_ip_address:443" scheme=https round_robin=strict go_direct=false
`

========================

parent remap:
`map http://something.some.com/ http://originserver.com/`

========================

As you said, I am seeing 502 Next hop connection failure. 
I have a few follow up questions regarding this approach : 

1) When a parent gives a child 5xx, child will mark parent as down, correct?
2) if 1. is true, how do we know when the child will mark the parent up?  (question stands even if mark down/up is per remap)
3) Do you have any pointers on the updated configs I have attached? Anything I might miss, something I should be aware of?

**Comment by jrushford** [comment]
@amoghyermalkar123 Here are my replies

1.  Yes, it will mark the parent down but, there are some configuration parameters to be aware of:
     [proxy.config.http.parent_proxy.fail_threshold](https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-http-parent-proxy-fail-threshold)

2. **proxy.config.http.parent_proxy.retry_time ** is basically sliding retry window.  Once the retry_time expires, a down parent is selected and is retried.  If the transaction is successful, the parent is marked up.  If the connection fails, the parent is left down and the retry time is set again.

**Comment by amoghyermalkar123** [comment]
@jrushford I really appreciate your help, thanks alot !

Have been testing, and haven't been seeing any multi-hops since, closing this issue.
