### ISSUE TITLE
support TS_HTTP_REQUEST_CLIENT_HOOK / TS_HTTP_RESPONSE_CLIENT_HOOK in lua plugin

### ISSUE THREAD

**Issue by vmamidi** [apache/trafficserver#8746]
Lua doesn't support TS_HTTP_REQUEST_BUFFER_READ_COMPLETE_HOOK.

**Comment by shukitchan** [comment]
This should hopefully be simple and similar to https://github.com/apache/trafficserver/blob/master/example/plugins/c-api/request_buffer/request_buffer.c

The lua plugin will support the hook and the corresponding handler lua function can call a pre-defined function to retrieve the body. Inside the lua function, you can save the string in "ctx" and thus it can be used in other hook handler function under the same continuation.

**Comment by shukitchan** [comment]
I checked out a recent PR from Brian - https://github.com/apache/trafficserver/pull/8804/files

And it looks like this is a better hook to support to provide request body for lua script programmer. It supports for even when the data is not buffered and also it has a similar hook for response as well. 

So I think I will go in this new direction instead

**Comment by shukitchan** [comment]
following #8804 , i will also do this work on 10-Dev branch
