### ISSUE TITLE
AuTest: Replace httpbin with proxy-verifier

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#8767]
We saw all httpbin based AuTest was failed. ( This is fixed by #8765 ) For the long term, we need to migrate these AuTest using the proxy-verifier. It looks like the proxy-verifier has equivalent features that we're using. If not, we can add it.

List of the httpbin based tests are below
```
» grep Test.MakeHttpBinServer -R ./* | awk -F ':' '{print $1}'
./autest-site/httpbin.test.ext
./cache/background_fill.test.py
./connect/connect.test.py
./h2/nghttp.test.py
./h2/httpbin.test.py
./h2/h2spec.test.py
./logging/new_log_flds.test.py
./post/post-continue.test.py
./proxy_protocol/proxy_protocol.test.py
```

**Comment by masaori335** [comment]
Seem like https://github.com/mccutchen/go-httpbin is the successor of the httpbin.

**Comment by SunMoon97** [comment]
Hey!please assign me this issue.
