### ISSUE TITLE
Update well known strings

### ISSUE THREAD

**Issue by masaori335** [apache/trafficserver#8777]
It's time to compare the list of well-known strings and the HTTP Field Name Registry.
https://www.iana.org/assignments/http-fields/http-fields.xhtml

I think we had a similar discussion about adding some strings from HTTP/2 & HPACK before.

**Comment by bryancall** [comment]
We also need to update the cache version when this happens or bad this will occur.

**Comment by masaori335** [comment]
Duplicated with #9636.
