### ISSUE TITLE
Replace pthread_* calls with C++11 thread_local

### ISSUE THREAD

**Issue by c-taylor** [apache/trafficserver#8781]
Under load you can see the pthread calls in the functions:
  `ink_thread_(key_create|setspecific|getspecific|key_delete)`

Start to feature in perf traces.

Please review and consider migrating native C11 `thread_local` which should be faster, and _may_ also be copy free.

A good example of where this is currently observed is in `TSHttpTxnReenable`.

```
 92.40 │       mov    Thread::thread_data_key@@Base,%edi
  1.59 │       callq  pthread_getspecific@plt
```

**Comment by masaori335** [comment]
@cmcfarlen is working on this.
