### ISSUE TITLE
Forward proxy to Origin server over H3

### ISSUE THREAD

**Issue by zk45** [apache/trafficserver#8796]
Does trafficserver support H3 connections to the origin server? 

Noticing that the origin server sends an alt-svc h3 header but trafficserver never tries to connect to it using h3 over quic (fwiw, the client is connecting to trafficserver using http 1.1).

**Comment by bryancall** [comment]
@zk45 ATS currently doesn't have H3 support for the origin.  We do have experimental H3 support on the client side.

**Comment by bryancall** [comment]
If this is still an issue please reopen.
