### ISSUE TITLE
h2spec on a docker image for CI job is too old

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#8836]
I found h2spec on a docker image that is used for our CI Autest job is too old (2.0.0). The latest version (2.6.0) has more tests, so we should update it.

I was about to merge a PR that has an issue, but I luckily found the issue when I ran h2spec locally.

**Comment by bneradt** [comment]
Thank you @maskit for pointing this out.

I've updated the Dockerfile for our Rocky Linux 8 image to use the latest v2.6.0 version. I verified, using that image, that the h2spec AuTest should run and work and use that version:

```
Running Test h2spec:. Passed

Generating Report: --------------
Total of 1 test
  Unknown: 0
  Exception: 0
  Failed: 0
  Warning: 0
  Skipped: 0
  Passed: 1
[root@43b4f06c021f tests]# h2spec --version
Version: 2.6.0 (70ac2294010887f48b18e2d64f5cccd48421fad1)
```

This can be verified like so:

```
docker pull ci.trafficserver.apache.org/ats/rockylinux:8
docker run -it --name test_h2spec ci.trafficserver.apache.org/ats/rockylinux:8 /bin/bash

[root@76f43274dc86 ~]# which h2spec
/usr/local/bin/h2spec
[root@76f43274dc86 ~]# h2spec --version
Version: 2.6.0 (70ac2294010887f48b18e2d64f5cccd48421fad1)

```

All of our CI machines should now be using that updated image.
