### ISSUE TITLE
Purging Takes a long time with the cache inspector API

### ISSUE THREAD

**Issue by amoghyermalkar123** [apache/trafficserver#8851]
We've been using the cache inspector API as the main API to bulk purge content via regex, i.e. `http://serverIP/ats-cache/delete_regex?url=domain/*`. Ofcourse, these requests are made locally through another service. 
The time it takes for this API to respond is 20+ minutes every time and the response is empty i.e. `empty reply from server`.

We are also using a few other alternatives that ATS provides, i.e. the remap purge plugin, revalidate plugin. The only thing we are unsure of is how can we actually delete something from the disk. If the first mentioned API fails, and the 2 plugins basically invalidate the cache and request the origin server, how can we (if it is even possible) delete something from the disk?

**Comment by amoghyermalkar123** [comment]
And also according to your personal opinions, is it an antipattern to want to delete something from the disk? Or is disk deletion executed only when a defined threshold is reached?
I know delete ops are heavy and may consume disk IO, so not only was I wondering the answer to my first question but also the best practises around deletion in CDN environments.

**Comment by amoghyermalkar123** [comment]
If it helps, the iotop command's output:

```
39501 be/4 traffics   43.13 M/s    0.00 B/s  0.00 % 57.73 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 7:62]]
39500 be/4 traffics   13.92 M/s    0.00 B/s  0.00 % 51.09 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 6:62]]
39497 be/4 traffics   28.34 M/s    0.00 B/s  0.00 % 49.57 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 3:62]]
39498 be/4 traffics   24.27 M/s    0.00 B/s  0.00 % 48.39 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 4:62]]
39495 be/4 traffics   14.66 M/s    0.00 B/s  0.00 % 46.53 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 1:62]]
39499 be/4 traffics   13.43 M/s    0.00 B/s  0.00 % 26.31 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 5:62]]
39494 be/4 traffics    9.98 M/s    0.00 B/s  0.00 % 12.62 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 0:62]]
```

**Comment by amoghyermalkar123** [comment]
if it helps, `iotop` command output:

```
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
39501 be/4 traffics   41.69 M/s    0.00 B/s  0.00 % 78.48 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 7:62]]
39499 be/4 traffics   16.53 M/s    0.00 B/s  0.00 % 61.35 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 5:62]]
39496 be/4 traffics   25.57 M/s    0.00 B/s  0.00 % 59.32 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 2:62]]
39498 be/4 traffics   22.12 M/s    0.00 B/s  0.00 % 49.73 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 4:62]]
39494 be/4 traffics   22.57 M/s    0.00 B/s  0.00 % 48.60 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 0:62]]
39500 be/4 traffics   29.11 M/s    0.00 B/s  0.00 % 48.52 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 6:62]]
39495 be/4 traffics   11.10 M/s    0.00 B/s  0.00 % 14.42 % traffic_server -M --httpport 80:fd=8,443:fd=9:ssl:proto=http,443:fd=10:ipv6 [[ET_AIO 1:62]]
```

**Comment by amoghyermalkar123** [comment]
Latest Challenges - 
So I was experimenting with the revalidate plugin since it seems to be the most viable option for us, I stumbled upon a problem. How can one use this plugin in a cache hierarchy?

My test - 
1) cache a piece of content on a child and a parent node.
2) set the revalidate.config file (the plugin config file) with the contents domain regex and an expiry (on child and parent)
3) request for the same content, the child server sends out a conditional request to parent server, but the parent server itself verifies whether the content changed or not, i.e. acting on behalf of the origin server. Shouldn't the request not go to the origin server to verify whether the content changed or not?
4) if the content has not changed parent server gives out 304 which again should be a responsibility of the origin server.

Am I missing something in the test case? Please help me progress in this problem.

**Comment by amoghyermalkar123** [comment]
Sample log lines -
child node log - 
```
1653897325 296 -1 103.208.69.91 TCP_REFRESH_HIT 200 236619 GET https domain.com content_url HTTP/1.1 PARENT_HIT parent-domain.com application/octet-stream curl/7.68.0
```
 
parent node log - 
```
1653897325 158 -1 14.192.2.115 TCP_IMS_HIT 304 133 GET https domain.com content_url HTTP/1.1 NONE - - curl/7.68.0
```

**Comment by amoghyermalkar123** [comment]
@bryancall can I get some suggestions here?
Thanks in advance :)

**Comment by mlibbey** [comment]
I don't think the community uses/relies upon the cache inspector. Instead think folks:
- Run the regex revalidation plugin https://docs.trafficserver.apache.org/en/9.1.x/admin-guide/plugins/regex_revalidate.en.html (which would force a revalidation on requests matching a regex)
- run https://docs.trafficserver.apache.org/en/9.1.x/admin-guide/plugins/remap_purge.en.html ... or set/increment the proxy.config.http.cache.generation for a remap
- attempt to only purge for regulatory purposes (like these specific urls can't be served anymore ... run -X PURGE on the requested specific urls)
- log the urls and generate reports from them and run PURGE on them
- encourage origin owners to version assets -- so that a new version of the javascript has a new cache key and thus gets fetched/cached as their new content goes live.
- encourage origin owners to choose smaller max-ages that balance desire for freshness and origin load.

**Comment by amoghyermalkar123** [comment]
Thanks @mlibbey.
One follow-up question. How does ATS handle a full disk? Lets say i have 15 TB worth of physical memory thats full. 
And there won't be any purges any time soon, but we do have newer content thats hot. 
How does ATS handle such a scenario?

**Comment by mlibbey** [comment]
The way to think of it is a circular buffer. Start writing at the beginning of the disk, and as you get to the end, start back at the beginning, overwriting what was there.

**Comment by amoghyermalkar123** [comment]
Thanks @mlibbey, that answers all my questions.
Great help as always!
