### ISSUE TITLE
Workaround on older version of ATS for : `traffic_ctl metric reset` does not work

### ISSUE THREAD

**Issue by 0foo** [apache/trafficserver#8863]
Due to various reasons forced to use an older version of ATS at the moment.

In this version:  `traffic_ctl metric reset` does not work.

Is there a file somewhere I can just delete to reset the metrics?

I tried deleting cache.db and the log files to no avail.

**Comment by 0foo** [comment]
I found out I might be using a different cache.db.

How does one identify which cache.db is being used?

traffic_ctl storage status says it's not implemented.

**Comment by 0foo** [comment]
I see the diag.log.

**Comment by brbzull0** [comment]
> Due to various reasons forced to use an older version of ATS at the moment.
> 
> In this version: `traffic_ctl metric reset` does not work.
> 
> Is there a file somewhere I can just delete to reset the metrics?
> 
> I tried deleting cache.db and the log files to no avail.

Hello, ok I see you closed this now.
For the records: we had this [issue](https://github.com/apache/trafficserver/issues/5188 ) and it was [fixed](https://github.com/apache/trafficserver/pull/8172)
