### ISSUE TITLE
Test suite "test_PluginFactory"

### ISSUE THREAD

**Issue by petershh** [apache/trafficserver#8887]
OS: Alpine Linux Edge
Traffic Server Version: 9.1.2

I am trying to build Traffic Server from source, and one of the test suites fails.

Here is the test suite log: [test-suite.log](https://github.com/apache/trafficserver/files/8854115/test-suite.log)

**Comment by bryancall** [comment]
```
-------------------------------------------------------------------------------
unit-tests/test_PluginFactory.cc:995
...............................................................................

unit-tests/test_PluginFactory.cc:1000: FAILED:
  CHECK( global_plugin_v1.dlOpenHandle() == plugin_v2->_plugin.dlOpenHandle() )
with expansion:
  0x00007f4db73e0dc0 == 0x00007f4db73eadc0

unit-tests/test_PluginFactory.cc:1004: FAILED:
  CHECK( 1 == getPluginVersion(plugin_v2->_plugin) )
with expansion:
  1 == 2

unit-tests/test_PluginFactory.cc:1011: FAILED:
  CHECK( tsRemapInitSym_v1_t2 == tsRemapInitSym_v2_t2 )
with expansion:
  0x00007f4db6dcc275 == 0x00007f4db6dc7275
```

**Comment by bryancall** [comment]
@cmcfarlen is going to try to reproduce the issue.

**Comment by cmcfarlen** [comment]
Hello, Alpine Linux uses musl libc.  The way dynamic loading is implemented in musl does not meet the requirements ATS has for reloadable plugins (which this test exercises).  As far as I can tell, ATS doesn't make any claims about correctness when using musl libc, but perhaps it will run as long as you don't require the affected features (i.e. reloadable plugins).  There is some more information on musl differences here: https://wiki.musl-libc.org/functional-differences-from-glibc.html
