### ISSUE TITLE
How to use access control plugin with aws s3?

### ISSUE THREAD

**Issue by hugmahit** [apache/trafficserver#8930]
I want to use aws s3 as origin server and `access control` plugin to access control. Can do that ?
I'm  using `s3_auth` plugin of `traffic server` to aws s3
authentication.

**Comment by mlibbey** [comment]
The access control plugin needs the origin to decide if a user is authorized to get a piece of content (and really that they are authenticated as well). It seems unlikely that amazon simple storage service would be able to do that. It may be possible to use other amazon cloud services to perform the authentication/authorization functions and do the cookie dance with the plugin to deputize it to release the content from cache.

**Comment by HugManh** [comment]
Thank @mlibbey .

**Comment by hugmahit** [comment]
Thank @mlibbey .
