### ISSUE TITLE
How to encrypts & decrypts the content?

### ISSUE THREAD

**Issue by HugManh** [apache/trafficserver#8958]
In docs:
![Capture](https://user-images.githubusercontent.com/43240025/178645073-e04653cd-2827-4260-b615-d398c226c000.PNG)
Link: [https://docs.trafficserver.apache.org/en/latest/admin-guide/security/index.en.html](url)
I want encrypts the content when traffic server sends it to the client. Do it support this? Plugin or config ?
Thank.

**Comment by mlibbey** [comment]
This is talking about https. An object can be fetched from origin via http (no s),and stored in cache. Then a client request via https will result in the object sent over tls. So no plug-in required. Generally, you’ll need a cert for the inbound host name (configured in ssl_multicert), and a remap rule in remap.config.

**Comment by bneradt** [comment]
@HugManh : did this answer your question?
