### ISSUE TITLE
Money trace plugin does not generate the next trace context in case of cache hit, but stale scenario

### ISSUE THREAD

**Issue by androzes** [apache/trafficserver#9002]
ATS version: 8.1.x

Money trace plugin does not generate the next trace context in case of cache hit, but stale scenario. So, the same trace context is forwarded to the parent.

Code reference: https://github.com/apache/trafficserver/blob/8.1.x/plugins/experimental/money_trace/money_trace.cc#L82

Is this expected? if yes, what is the rational behind it?

**Comment by traeak** [comment]
Very likely it is a bug.  With 9.2.x the money trace plugin was rewritten.
