### ISSUE TITLE
metrics discrepancies after updating to ATS 9.1.2 from 8.0.8

### ISSUE THREAD

**Issue by jvgutierrez** [apache/trafficserver#9028]
After updating to ATS 9.1.2 we have detected an increase on self-reported metrics by ATS. On both 8.x and 9.x instances TTFB is gathered with `%<{TS_MILESTONE_UA_BEGIN_WRITE-TS_MILESTONE_SM_START}msdms>`. As it can be seen in this dashboard:
![image](https://user-images.githubusercontent.com/4091505/184326941-6c404867-a3ae-4e7b-9b0c-b79c3c7f1d10.png)
TTFB as reported by ATS has increased ~25% while ATS reported by the varnish instances that feed traffic to ATS remained basically the same.

We've also detected some differences on reported plugin time, we log total plugin time on both 8.x and 9.x instances with `%<{TS_MILESTONE_PLUGIN_TOTAL-TS_MILESTONE_SM_START}msdms>`. ATS 8.x instances almost always report a total plugin time of 0ms:
```
vgutierrez@cp6015:~$ curl -s http://127.0.0.1:3904/metrics |egrep "total_plugin_time_(sum|count)" |grep appservers-rw 
trafficserver_backend_total_plugin_time_sum{backend="appservers-rw.discovery.wmnet",prog="atsbackend.mtail"} 0.33
trafficserver_backend_total_plugin_time_count{backend="appservers-rw.discovery.wmnet",prog="atsbackend.mtail"} 8.036859e+06
```
While ATS 9.x instances report >0ms more often (bucket measures time in seconds not ms):
```
trafficserver_backend_total_plugin_time_sum{backend="appservers-rw.discovery.wmnet",prog="atsbackend.mtail"} 1486.0159999757298
trafficserver_backend_total_plugin_time_count{backend="appservers-rw.discovery.wmnet",prog="atsbackend.mtail"} 3.439146e+06
```

As expected, the described behavior hasn't changed after updating to 9.1.3

**Comment by bryancall** [comment]
@shinrich Do you want to take a look at this issue?

**Comment by jvgutierrez** [comment]
I think I've found an explanation for this.

ATS 9.1.x reports `:%<{TS_MILESTONE_CACHE_OPEN_READ_END-TS_MILESTONE_CACHE_OPEN_READ_BEGIN}msdms>` and `%<{TS_MILESTONE_CACHE_OPEN_WRITE_END-TS_MILESTONE_CACHE_OPEN_WRITE_BEGIN}msdms>` as `-1` more often than ATS 8.x. This added to the fact that we failed to track requests with any of those two milestones set to -1 (fixed in https://github.com/wikimedia/puppet/commit/e42685e53307ec9ffe2f6fcbd2044bf90fef4b0a) triggered the issue.
