### ISSUE TITLE
How ATS customizes the return origin Host？

### ISSUE THREAD

**Issue by dandinw** [apache/trafficserver#9036]
I want to customize the origin  host. for example. this is the remap.config

map  http://www.test.com   http://www.test.com

Due to the business needs of the company, I must configure the map rule as follows

The  parent.config  configuration is as follows:

dest_domain=www.test.com   scheme=http   parent="www.origin.com"  round_robin=strict

I hope the host header received by the source station is www.test.com. I tried the header_ rewrite plugin Modify the host header. But it doesn't seem to work

I want to know how to realize my needs. I hope to receive your reply as soon as possible. Thank you here

**Comment by maskit** [comment]
I'm not sure if I understand what you need, but this setting might help.
https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy.config.url_remap.pristine_host_hdr

**Comment by dandinw** [comment]
> I'm not sure if I understand what you need, but this setting might help. https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy.config.url_remap.pristine_host_hdr

I have tried this option. for example. this is the remap.config. and the proxy.config.url_remap.pristine_host_hdr value is 1

map http://www.test3.com   http://www.example.com

the  traffic.out log The following contents are displayed:
+++++++++ Proxy's Request after hooks +++++++++
-- State Machine Id: 41
GET http://www.example3.com/ HTTP/1.1
User-Agent: curl/7.29.0
Host: www.test3.com
Accept: */*
Client-ip: 127.0.0.1
X-Forwarded-For: 127.0.0.1
Via: http/1.1 traffic_server[b6f7022b-cc37-48b5-a0af-d10c976883dd] (ApacheTrafficServer/9.1.2)

the nginx access.log:
host = "www.example3.com"   [16/Aug/2022:10:23:09 +0800] "GET http://www.example3.com/ HTTP/1.1" 200 42 "-" "curl/7.29.0" "127.0.0.1"

The host is still www.example3.com.so I want to change the URL after remap.

**Comment by dandinw** [comment]
At present, I have solved this problem by writing plugins. The key APIs used are TSHttpTxnServerReqGet, TSHttpHdrUrlGet, and TSUrlHostSet

**Comment by dandinw** [comment]
At present, I have solved this problem by writing plugins. The key APIs used are TSHttpTxnServerReqGet, TSHttpHdrUrlGet, and TSUrlHostSet
