### ISSUE TITLE
unable to find TSPluginInit function in maxmind_acl.so plugin in trafficserver 9.1.x

### ISSUE THREAD

**Issue by thatsk** [apache/trafficserver#9051]
Hello Team,

I am trying to load maxmind_acl.so plugin in trafficserver 9.1.x but failed to load due to this error.
```
[Aug 23 10:07:58.073] traffic_server FATAL: unable to find TSPluginInit function in '/usr/lib64/trafficserver/plugins/maxmind_acl.so': /usr/lib64/trafficserver/plugins/maxmind_acl.so: undefined symbol: TSPluginInit
```

**Comment by thatsk** [comment]
@randall @AD5GB

**Comment by randall** [comment]
This is a remap-only only plugin. Are you trying to load it via `plugin.config`?

**Comment by thatsk** [comment]
Yes

**Comment by thatsk** [comment]
without registering to plugins.config it will throw an error 
```
Aug 24 04:04:17.434] traffic_server ERROR: [maxmind_acl] Failed to initialize maxmind with maxmind.yaml
[Aug 24 04:04:17.434] traffic_server ERROR: [ReverseProxy] failed to add remap rule at /etc/trafficserver/remap_integration_msp.config line 57: failed to create instance for plugin maxmind_acl.so: Unknown plugin error
```

**Comment by thatsk** [comment]
@randall can you help on this

**Comment by randall** [comment]
you'll need to enable debug logging for that plugin.

```
CONFIG proxy.config.diags.debug.enabled INT 1
CONFIG proxy.config.diags.debug.tags STRING maxmind_acl
```

and post a redacted version of your `maxmind.yaml` config file here.

**Comment by thatsk** [comment]
K i will update shortly

**Comment by thatsk** [comment]
```
---
maxmind:
 database: GeoIP2-City.mmdb
 html: deny.html
 allow:
  country:
   - IN
  ip:
   - 127.0.0.1
 deny:
  country:
   - US
```

**Comment by thatsk** [comment]
when I remove from plugins.config and copy the GeoIP2-City.mmdb into /etc/trafficserver
```
root@trafficserver: /etc/trafficserver# traffic_server -Cverify_config -D/etc/trafficserver
traffic_server: using root directory '/usr'
NOTE: VERIFY

NOTE: VERIFY config dir: /etc/trafficserver...

[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) remap plugin is successfully initialized
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) Initialized MMDB with /etc/trafficserver/GeoIP2-City.mmdb
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) Loaded Allow ruleset
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) Loaded Deny ruleset
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) Loaded HTML from /etc/trafficserver/deny.html
[Aug 24 17:02:53.734] traffic_server DIAG: (maxmind_acl) created remap instance with configuration maxmind.yaml
INFO: Successfully loaded remap.config

INFO: Successfully loaded records.config

INFO: Successfully loaded plugin.config

INFO: Successfully loaded ssl multicert.config

INFO: Successfully initialized SSL client context
```

**Comment by thatsk** [comment]
does it loaded now

**Comment by ezelkow1** [comment]
Sorry my github email notifications werent working properly. So it looks like it loads properly now. By default the plugin will look in the default ATS config directory, which is usually ##SOME_PATH###/etc/trafficserver, wherever things like remap.config, records.config, etc live at for your install.  You can also specify a full path to the maxmind database you want to use in the yaml config file, e.g. something like 

`---
maxmind:
 database: /etc/trafficserver/GeoIP2-City.mmdb`

**Comment by thatsk** [comment]
is there way we can check which plugins are loaded so that we know that maxmind plugin is loaded properly debug is not helping so much

**Comment by thatsk** [comment]
@ezelkow1 i updated path as you mentioned but seems like plugins still not working . it still allowing me to access so I need to confirm whether the plugin is loaded or not is there command we can check plugin is loaded after trafficserver start

**Comment by ezelkow1** [comment]
If you see the debug for it then it should be loaded, but it is only going to be active on the remap that you have the plugin placed on. If you leave the maxmind debug enabled and do a request then you should see it's debug output for each request it sees. If it does not see any then it may not be active on the remap for the request you are using

**Comment by thatsk** [comment]
the problem is how do we ensure is that plugin loaded or not
and when I restart trafficserver it still loading my page so I'm not sure where I am doing wrong.

**Comment by thatsk** [comment]
when i run
 ```
traffic_server -Cverify_config -D/etc/trafficserver
```
```
traffic_server: using root directory '/usr'
NOTE: VERIFY

NOTE: VERIFY config dir: /etc/trafficserver...

[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) remap plugin is successfully initialized
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) Initialized MMDB with /usr/share/GeoIP/GeoIP2-City.mmdb
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) loading ip: valid: 1, fam 2 
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) Loaded Allow ruleset
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) Loaded Deny ruleset
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) Loaded HTML from /etc/trafficserver/deny.html
[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) created remap instance with configuration maxmind.yaml
INFO: Successfully loaded remap.config

INFO: Successfully loaded records.config

ERROR: Failed to load plugin.config, exitStatus 4

INFO: Successfully loaded ssl multicert.config

INFO: Successfully initialized SSL client context

````
but as per expectation its not blocking or denying page its give me response

**Comment by thatsk** [comment]
@ezelkow1

**Comment by thatsk** [comment]
in the example in trafficserver page you are mentioning about city and giving country code is that correct
https://docs.trafficserver.apache.org/admin-guide/plugins/maxmind_acl.en.html

```
maxmind:
 database: GeoIP2-City.mmdb
 html: deny.html
 allow:
  country:
   - US
  ip:
   - 127.0.0.1
   - 192.168.10.0/20
 deny:
  country:
   - DE
  ip:
   - 127.0.0.1
  regex:
   - [US, ".*\\.txt"]  # Because these get parsed you must escape the escape of the ``.`` in order to have it be escaped in the regex, resulting in ".*\.txt"
   - [US, ".*\\.mp3"]```

**Comment by ezelkow1** [comment]
yes it is loaded due to 
`[Aug 24 18:11:35.759] traffic_server DIAG: (maxmind_acl) created remap instance with configuration maxmind.yaml`

Also the -City name in that database is just because that is the default naming scheme from Maxmind, it has country data in it along with city level data.

What does your remap.config look like (you may or may not need to scrub this)? Is it possible your request is coming in and going to a remap line that does not have the plugin loaded on it? In that case the plugin will not see the request to allow or deny it.

Also what does you request look like? If you are testing with something like `http://localhost:port` that is interpreted in ATS differently than `http://external-ip-of-box:port`. ATS will see the incoming request differently. Also both of those examples would only work on a remap that was basically a blanket remap of everything, i.e.:
`map / http://your-origin.com @plugin=maxmind_acl.so @pparam=maxmind.yaml`

**Comment by thatsk** [comment]
```
map https://xxxxx/geofence.json http://xxx/geofence.json \
    @plugin=maxmind_acl.so @pparam=maxmind.yaml
```
```
root@trafficserver: /etc/trafficserver# cat maxmind.yaml 
maxmind:
 database: /usr/share/GeoIP/GeoIP2-Country.mmdb
 html: deny.html
 allow:
  country:
   - US
  ip:
   - 127.0.0.1
 deny:
  country:
   - IN
```

**Comment by thatsk** [comment]
when i try to access its still able to access from India countly

**Comment by thatsk** [comment]
my api is returing response so not sure where it is missing or where should I debug

**Comment by randall** [comment]
```

**Comment by randall** [comment]
if you enable the debug tags, and you're hitting the remap line with the plugin, you should see debug output regarding IP/country/etc matching.

**Comment by thatsk** [comment]
resolved thanks for the stuff
