### ISSUE TITLE
Confused about memory allocation

### ISSUE THREAD

**Issue by frostnotfall** [apache/trafficserver#9111]
I want to know about memory allocation.
I think there are 2 parts of memory allocation, both are disk storage relevant.
1. RAM Cache . 
2.  Cache directory is used as a memory resident structure

# RAM Cache
There are 2 statements, but contradictory.
1. 10MB to 1GB. https://docs.trafficserver.apache.org/en/latest/admin-guide/performance/index.en.html?highlight=ssd#memory-allocation
2. 1MB to 1GB.  https://docs.trafficserver.apache.org/en/latest/admin-guide/storage/index.en.html#changing-the-size-of-the-ram-cache

Q: what is real?

# Cache directory is used as a memory resident structure
In my opinion, Disk cache directory has indexed in memory. As HDD space grows, so does memory usage.
Q: So, for example, how many memory the indexes are used when for 1TB hard disk?

**Comment by cmcfarlen** [comment]
Reading the code I see that, unless the size is specified, the ram cache for each cache volume is set to 10x the directory length of the volume (in bytes).  Running an experiment, this worked out to about 1.2% of the total configured cache size.  Based on this, the 10MB per 1GB is closer to correct.  Since this is based on the cache size and not available RAM, I recommend you specify the ram cache size in your config rather than rely on this heuristic.  I think this was just meant to be a gentle default.

I'm sorry but I do not understand the second part of your question.

**Comment by frostnotfall** [comment]
> Reading the code I see that, unless the size is specified, the ram cache for each cache volume is set to 10x the directory length of the volume (in bytes). Running an experiment, this worked out to about 1.2% of the total configured cache size. Based on this, the 10MB per 1GB is closer to correct. Since this is based on the cache size and not available RAM, I recommend you specify the ram cache size in your config rather than rely on this heuristic. I think this was just meant to be a gentle default.
> 
> I'm sorry but I do not understand the second part of your question.

# Cache directory is used as a memory resident structure
In my opinion, Disk cache directory has indexed in memory. As HDD space grows, so does memory usage.
So, for example,  how many memory the indexes are used  when for 1TB hard disk.

**Comment by cmcfarlen** [comment]
If you run traffic_server with the `-Tcache_init` argument, it will print some allocation info about space used for directory vs volume size:

```
(init)> (cache_init) Vol /opt/ats/var/trafficserver/cache.db 16384:2883584: allocating 29474816 directory bytes for a 23622320128 byte volume (0.124775%)
```

**Comment by frostnotfall** [comment]
Post my test.
My settings：
12 HDD * 3TB = 36TB, close RamCache, the mem usage is 50.16GB.

(In addition, my machine has 12 HDD, every is 8TB，but I can‘t use all of them， because I just have 64GB memory)
