### ISSUE TITLE
open_read_retry_time not being honored in ATS 9.1.3

### ISSUE THREAD

**Issue by jvgutierrez** [apache/trafficserver#9118]
While using the default configuration regarding Open Read Retry Timeout (and RWW disabled):
```
$ traffic_ctl config match open_read
proxy.config.http.cache.max_open_read_retries: -1
proxy.config.http.cache.open_read_retry_time: 10
```
the expected behavior according the documentation available in https://docs.trafficserver.apache.org/admin-guide/configuration/cache-basics.en.html#open-read-retry-timeout:

> The configurations are (with defaults):

> CONFIG proxy.config.http.cache.max_open_read_retries INT -1
> CONFIG proxy.config.http.cache.open_read_retry_time INT 10
> The defaults are such that the feature is disabled and every connection is allowed to go to origin without artificial delay. When enabled, you will try max_open_read_retries times, each with an open_read_retry_time timeout.

But we're occasionally (p999) seeing that the cache read time goes up to 1 second:
 
![image](https://user-images.githubusercontent.com/4091505/193617733-0eb69c8e-aab3-44d5-9cbf-19bac0bcfa3e.png)

same behavior happens with the following values:
```
CONFIG proxy.config.http.cache.max_open_read_retries INT 1
CONFIG proxy.config.http.cache.open_read_retry_time INT 10
```

Cache read time is being measured via logging with the following expression: `CacheReadTime:%<{TS_MILESTONE_CACHE_OPEN_READ_END-TS_MILESTONE_CACHE_OPEN_READ_BEGIN}msdms>`

We've also noticed that requests with a high cache read time happen every 9 minutes (reported by `cqtt` even if the duration of the connection doesn't match between them (reported by `ttms` or `TS_MILESTONE_SM_FINISH-TS_MILESTONE_SM_START`):

```
$ cut -f1-2 -d' ' readtime.log |sort |uniq -c
    215 Date:2022-10-04 Time:09:24:52
     65 Date:2022-10-04 Time:09:33:51
    144 Date:2022-10-04 Time:09:33:52
     66 Date:2022-10-04 Time:09:42:51
    147 Date:2022-10-04 Time:09:42:52
    163 Date:2022-10-04 Time:09:51:51
     41 Date:2022-10-04 Time:09:51:52
    169 Date:2022-10-04 Time:10:00:51
$ cut -f1-2,7,9 -d' ' readtime.log |head -10
Date:2022-10-04 Time:09:24:52 CacheReadTime:712 TotalSMTime:712
Date:2022-10-04 Time:09:24:52 CacheReadTime:420 TotalSMTime:421
Date:2022-10-04 Time:09:24:52 CacheReadTime:176 TotalSMTime:177
Date:2022-10-04 Time:09:24:52 CacheReadTime:545 TotalSMTime:545
Date:2022-10-04 Time:09:24:52 CacheReadTime:513 TotalSMTime:513
Date:2022-10-04 Time:09:24:52 CacheReadTime:727 TotalSMTime:727
Date:2022-10-04 Time:09:24:52 CacheReadTime:460 TotalSMTime:461
Date:2022-10-04 Time:09:24:52 CacheReadTime:460 TotalSMTime:460
Date:2022-10-04 Time:09:24:52 CacheReadTime:686 TotalSMTime:687
Date:2022-10-04 Time:09:24:52 CacheReadTime:111 TotalSMTime:111

```

**Comment by jvgutierrez** [comment]
This could be potentially related to #8598

**Comment by jvgutierrez** [comment]
As pointed out by @zwoop on Slack, the 9 minutes periodicity is related to a `cache_dir_sync` operation. The undocumented configuration setting `proxy.config.cache.dir.sync_frequency` is set to its default value of 60 seconds but this cannot be honored because the operation takes 8 minutes so effectively a cache_dir_sync happens every 9 minutes as its being shown by debug logging:
```
[Oct  5 10:09:15.541] [ET_NET 11] DEBUG: <CacheDir.cc:1099 (mainEvent)> (cache_dir_sync) sync started
[Oct  5 10:09:15.541] [ET_NET 11] DEBUG: <CacheDir.cc:1111 (mainEvent)> (cache_dir_sync) Dir disk.0 294912:195351687: waiting for agg buffer                                                                                                                                                                               
[Oct  5 10:09:15.542] [ET_AIO 5:166] DEBUG: <CacheDir.cc:1099 (mainEvent)> (cache_dir_sync) sync started
[Oct  5 10:09:15.542] [ET_AIO 5:166] DEBUG: <CacheDir.cc:1118 (mainEvent)> (cache_dir_sync) pos: 615841923072 Dir disk.0 294912:195351687 dirty...syncing to disk                                                                                                                                                          
[Oct  5 10:17:15.702] [ET_NET 11] DEBUG: <CacheDir.cc:1054 (mainEvent)> (cache_dir_sync) sync done
[Oct  5 10:18:15.728] [ET_NET 11] DEBUG: <CacheDir.cc:1099 (mainEvent)> (cache_dir_sync) sync started
```
We're using `Dell Ent NVMe AGN MU AIC 1.6TB` as disk storage and 8 threads per disk, any suggestions on how this could be mitigated?

**Comment by bryancall** [comment]
@jvgutierrez Sounds like this issue is the same as #9124.  Can we close this issue and track it in #9124.

**Comment by jvgutierrez** [comment]
Sure! let's focus on #9124
