### ISSUE TITLE
Skip cache if cookie is present

### ISSUE THREAD

**Issue by khrizt** [apache/trafficserver#9131]
Hi,

I'm new to Apache Traffic Server and I'm reading all the documentation to see if I can use it in our platform. I've managed to install and configure Traffic Server but I have a couple of questions that I wasn't able to answer with the documentation.

The question is "Is there a way to avoid cache if there's a certain cookie present?".

My use case is I want to cache all the documents from our public section of the platform but only for non-logged users and I was thinking of the best method to achieve that, and the cookie detection was the best I could do. If there's any way to achieve this or any other method it'd be helpful.

The other question is, to cache a document in different languages I saw that I can use the [Cache key manipulation plugin](https://docs.trafficserver.apache.org/admin-guide/plugins/cachekey.en.html) so I can assign a value from a cookie to the cache key and then show cached documents with the correct language to our users.

Any help on those questions woud be great. Thanks.

**Comment by jvgutierrez** [comment]
> The question is "Is there a way to avoid cache if there's a certain cookie present?"

Yes. Current documentation [states](https://docs.trafficserver.apache.org/admin-guide/files/records.config.en.html#proxy-config-http-cache-http) that `proxy.config.http.cache.http` is overridable. This means that it can be changed on a per-request basis.
It could be done using a lua script with:
```
ts.http.config_int_set(TS_LUA_CONFIG_HTTP_CACHE_HTTP, 0)
```
 ATS exposes the Cookies in lua via `ts.client_request.header['Cookies']`

It could be also done leveraging the header rewrite plugin. The [COOKIE condition](https://docs.trafficserver.apache.org/admin-guide/plugins/header_rewrite.en.html#cookie) could be used to detect the cookie and [the set-config operator](https://docs.trafficserver.apache.org/admin-guide/plugins/header_rewrite.en.html#set-config) could be used to set `proxy.config.http.cache.http`to `0` effectively disabling caching for that request.

> The other question is, to cache a document in different languages I saw that I can use the [Cache key manipulation plugin](https://docs.trafficserver.apache.org/admin-guide/plugins/cachekey.en.html) so I can assign a value from a cookie to the cache key and then show cached documents with the correct language to our users.

Usually this is achieved with the `Vary: Accept-Language` HTTP header, you have more information on https://docs.trafficserver.apache.org/admin-guide/configuration/cache-basics.en.html?highlight=vary%20http%20header#caching-http-alternates. But you should apply some heavy normalization to the Accept-Language header to avoid cache fragmentation issues.

**Comment by khrizt** [comment]
Wow, so detailed answer. Thanks a lot. I'll try this, but I have a couple questions left, sorry about that.

Do I need to enable Lua plugin? And if I need to enable it do I need to re-build the Traffic Server (I installed from ubuntu repositories).

And about the language, if I put the `Vary: Accept-Language` header it will store variations of the same page in different language, but how it will get the correct one, using the Accept-Language header? Is there a way to do that with a cookie value?

Thanks a lot for the support.

**Comment by jvgutierrez** [comment]
the lua plugin is a stable plugin and should be shipped with the ubuntu packages. If you don't wanna use Lua you can achieve the same with the header rewrite plugin, see its documentation here: https://docs.trafficserver.apache.org/admin-guide/plugins/header_rewrite.en.html

You can do it with a cookie, but I'd recommend extracting the language choice from the cookie to a custom header like X-Language and then Vary the cache on this X-Language header. Otherwise anything else included in the cookies will mess with your cache.

**Comment by khrizt** [comment]
Ok, much appreciated @jvgutierrez Thanks a lot!!
