### ISSUE TITLE
Does ATS support SSD+HDD as hot/cold cache?

### ISSUE THREAD

**Issue by frostnotfall** [apache/trafficserver#9145]
Does ATS support SSD+HDD as hot/cold cache?
I read the whole documentation and it doesn't mention it, just a little configuration for SSD. However, before 6.0, SSD can be used as the middle layer. https://cwiki.apache.org/confluence/display/TS/SSDSupport

**Comment by frostnotfall** [comment]
Any advice please?

_While a more detailed discussion of storage stratification is covered in [Cache Partitioning](https://docs.trafficserver.apache.org/en/latest/admin-guide/performance/index.en.html#cache-partitioning) below, very briefly you may be able to realize gains in performance by separating more frequently accessed content onto faster disks (PCIe SSDs, for instance) while maintaining the bulk of your on-disk cache objects, which may not receive the same high volume of requests, on lower-cost mechanical drives._  ---from https://docs.trafficserver.apache.org/en/latest/admin-guide/performance/index.en.html#disk-storage

But no more...

**Comment by bryancall** [comment]
No, ATS doesn't have a way to do tiered support for the drives.  A few companies that use ATS have setup the cache as a hierarchy with a  tier of SSD servers backed by rotational drive servers.

**Comment by frostnotfall** [comment]
> No, ATS doesn't have a way to do tiered support for the drives. A few companies that use ATS have setup the cache as a hierarchy with a tier of SSD servers backed by rotational drive servers.

Thanks
