### ISSUE TITLE
coverage build fail

### ISSUE THREAD

**Issue by 0x34d** [apache/trafficserver#9158]
```
CC=clang
CXX=clang++
./configure --enable-debug --enable-coverage
```

```
/usr/bin/ld: .libs/freelist_benchmark: hidden symbol `atexit' in /usr/lib64/libc_nonshared.a(atexit.oS) is referenced by DSO
/usr/bin/ld: final link failed: bad value
```

**Comment by bryancall** [comment]
Here is a script I ran testing a coverage build on Fedora 36 and it works with master.  You can also take a look at our coverage script that we use in our CI system:  https://github.com/apache/trafficserver/blob/master/ci/coverage

```
#/bin/bash

set -x
set -e

CC=clang
CXX=clang++

git clean -xdf
autoreconf -if
./configure --enable-debug --enable-coverage
make -j
lcov --quiet --capture --initial --directory . --output-file initial.info
make -j test
lcov  --quiet --capture --directory . --output-file tests.info
```

**Comment by 0x34d** [comment]
Well, it's not using the clang compiler.

This code closes the shell and has a similar issue.

```

#/bin/bash

set -x
set -e

export CC=clang
export CXX=clang++

git clean -xdf
autoreconf -if
./configure --enable-debug --enable-coverage
make -j

```

with GCC it works but with clang, it doesn't.

**Comment by bryancall** [comment]
I get the same error with clang (updated the script above).  I tried setting various flags and couldn't get it to compile.  Is there a reason you need to do code coverage with clang?

**Comment by 0x34d** [comment]
> I get the same error with clang (updated the script above). I tried setting various flags and couldn't get it to compile. Is there a reason you need to do code coverage with clang?

Need coverage for HTPP fuzzer in 
https://github.com/google/oss-fuzz/pull/8832

I also try with some hacks it doesn't compile. 
I do believe that `Cmake` can fix this.
