### ISSUE TITLE
ATS memory continuous increase caused by free list

### ISSUE THREAD

**Issue by dboyzhong** [apache/trafficserver#9162]
## env
- CPU: 64 core
- memory :256G
- OS: CentOS
- ATS Version: 8.1.3
## ATS configuration
- ram_cache: 100G
## what happended
- memory cost upto 200G even ram_cache only configured 100G:
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/8457200/197698392-cb0aeed4-6467-47ea-9323-70d5c876ad82.png">

## why?
- the freelist held by ioBufAllocator alloc too much memory and never free, the memory dump below:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/8457200/197698809-c6c3d022-a485-42e6-938e-89f199fdf59b.png">

- It is an known issue that freelist[i] (i from 0 ~ 14) maybe "in use" and cost memory then "not use" but never return memory to OS, example below has a maxim memory twice then expeceted, and if 100G ram_cache, the worse case, it will exhaust 15 * 100G = 1500 G memory:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/8457200/197699595-2cea85cd-224c-47e8-bdf4-6bc8ebd7c64c.png">

- i know the reclaimable-free-list has been introduced in ATS 4.0.x to solve the problem but then removed，i want to know how  to solve this issue in alternatively?

**Comment by bryancall** [comment]
Have you tried turning off freelist.  This is how we are running ATS in production:
```
-bash-4.2$ grep binary records.config
CONFIG proxy.config.proxy_binary_opts STRING -M -f -F

```

Documentation on the options: https://docs.trafficserver.apache.org/appendices/command-line/traffic_server.en.html#traffic-server

**Comment by cmcfarlen** [comment]
While `-f` will return memory allocated back to the OS, it will also greatly increase the number of malloc, free and (sometimes most importantly) madvise calls.  On a high transaction server, this can have an impact on performance.  If you run with the `-f` option, I recommend that you configure jemalloc or mimalloc as well as they have their own internal freelists that will return memory to the OS eventually.  The `-F` option doesn't apply to ioBufAllocator as these are not proxy allocated.

**Comment by dboyzhong** [comment]
> Have you tried turning off freelist? This is how we are running ATS in production:
> 
> ```
> -bash-4.2$ grep binary records.config
> CONFIG proxy.config.proxy_binary_opts STRING -M -f -F
> ```
> 
> Documentation on the options: https://docs.trafficserver.apache.org/appendices/command-line/traffic_server.en.html#traffic-server

thanks for your suggestion, i will try to turn off free list and using jemalloc to instead of free list

**Comment by dboyzhong** [comment]
> While `-f` will return memory allocated back to the OS, it will also greatly increase the number of malloc, free and (sometimes most importantly) madvise calls. On a high transaction server, this can have an impact on performance. If you run with the `-f` option, I recommend that you configure jemalloc or mimalloc as well as they have their own internal freelists that will return memory to the OS eventually. The `-F` option doesn't apply to ioBufAllocator as these are not proxy allocated.

i will configure jemalloc, thanks

**Comment by dboyzhong** [comment]
> > While `-f` will return memory allocated back to the OS, it will also greatly increase the number of malloc, free and (sometimes most importantly) madvise calls. On a high transaction server, this can have an impact on performance. If you run with the `-f` option, I recommend that you configure jemalloc or mimalloc as well as they have their own internal freelists that will return memory to the OS eventually. The `-F` option doesn't apply to ioBufAllocator as these are not proxy allocated.
> 
> i will configure jemalloc, thanks

**Comment by dboyzhong** [comment]
the reclaimable-free-list has been introduced in ATS 4.0.x， then remove the feature in ATS 5.0.x， i want to know whether the "buddy allocation scheme" still be considered ？
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/8457200/198175154-8b0d60dd-6986-4e22-b6ff-662a2b9d424a.png">

**Comment by dhairav** [comment]
@dboyzhong I'm facing the same set of problems you are regarding RAM consumption by TrafficServer.
Could you please tell me how you've enabled Jemalloc with the systemd setup?
I already have an ATS build compiled with Jemalloc support, any help would be appreciated. Thanks.
