### ISSUE TITLE
NetVC EOS/TIMEOUT is not propagated to H3 session

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#9392]
EOS and TIMEOUT events (or events that notifie EOL of NetVC) are not propagated from QuicNetVC to H3Session. The session instance is deleted after all when QuicNetVC is freed, but that's not what happens on H2 session.

**Comment by bryancall** [comment]
![image](https://github.com/apache/trafficserver/assets/216749/f6b6bf52-b0c3-4cd2-b704-569ba3cdc884)
