### ISSUE TITLE
What happened to DerivativeMetrics from traffic_manager?

### ISSUE THREAD

**Issue by cmcfarlen** [apache/trafficserver#9396]
When traffic_manager was removed, the DerivativeMetrics.cc code was removed from the build but the files were left in the tree.  Was the intention to remove the code as well or move this feature to another place?

The same is true for WebMgmtUtils.cc.

I removed the files in #9388 but want to make sure what the intent was on these features.

**Comment by brbzull0** [comment]
There are some leftovers from the removal of TM which are in my queue.  I would probably wipe them out.

https://github.com/apache/trafficserver/issues/5563

**Comment by bryancall** [comment]
@brbzull0 Can you please send an email to the users@ and dev@ mailing lists warning and asking if it is ok to remove the derivative metrics.

**Comment by zwoop** [comment]
@brbzull0 Any update on this ?

**Comment by brbzull0** [comment]
DerivativeMetrics were removed
