### ISSUE TITLE
Make active_connection_id_limit configurable

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#9419]
We have `proxy.config.quic.proxy.config.quic.num_alt_connection_ids` for `active_connection_id_limit` transport parameter, but it's not used for quiche impl.

It should be set by https://docs.rs/quiche/latest/quiche/struct.Config.html#method.set_active_connection_id_limit

**Comment by brbzull0** [comment]
@maskit Should we rename `proxy.config.quic.num_alt_connection_ids` to `proxy.config.quic.active_connection_id_limit` ?

**Comment by maskit** [comment]
Actually the description is wrong. We have `proxy.config.quic.active_cid_limit_in/out` for the transport parameter, which tells how many CIDs ATS wants.

It seems like `proxy.config.quic.proxy.config.quic.num_alt_connection_ids` is for the number of CIDs ATS provides, although it's currently unused.
