### ISSUE TITLE
Enforce H3 header size constraints

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#9426]
Need to support `SETTINGS_MAX_FIELD_SECTION_SIZE`.
https://datatracker.ietf.org/doc/html/rfc9114#name-header-size-constraints

There are similar thing in H2 as well and we have `proxy.config.http2.max_header_list_size` for it.
https://datatracker.ietf.org/doc/html/rfc9113#name-limits-on-field-block-size

Note that the size is not the total of the lengths of field names and values.
> The size of a field list is calculated based on the uncompressed size of fields, including the length of the name and value in bytes plus an overhead of 32 bytes for each field.

**Comment by maskit** [comment]
Actually, I found `Http3SettingsId::HEADER_TABLE_SIZE`. It seems like the name was changed on the spec at some point.  We may just need to rename variables and functions.

**Comment by duke8253** [comment]
Actually I think it's the `Http3SettingsId::MAX_HEADER_LIST_SIZE` that's been renamed.

https://datatracker.ietf.org/doc/html/rfc9114#appendix-A.3-4.12.1
