### ISSUE TITLE
Set DF bit to UDP datagrams for QUIC

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#9488]
> UDP datagrams MUST NOT be fragmented at the IP layer. In IPv4 [[IPv4](https://datatracker.ietf.org/doc/html/rfc791)], the Don't Fragment (DF) bit MUST be set if possible, to prevent fragmentation on the path.[¶](https://datatracker.ietf.org/doc/html/rfc9000#section-14-7)

**Comment by ywkaras** [comment]
Can you give a reference explaining why this is necessary?  When IP fragments a UDP packet, does it reassemble it, or pass the fragments through to the application?
