### ISSUE TITLE
remap not work

### ISSUE THREAD

**Issue by taojishou** [apache/trafficserver#9503]
map https://europe.123.com/ http://50.7.218.1:80/
map https://europe.123.com/ http://50.7.218.2:80/
This configuration of multiple origin stations does not work,How to configure multiple back-to-source servers？

**Comment by taojishou** [comment]
Apache Traffic Server - 10.0.0

**Comment by mlibbey** [comment]
The newer strategies.yaml 
https://docs.trafficserver.apache.org/en/latest/admin-guide/files/strategies.yaml.en.html 
and older parent.config 
https://docs.trafficserver.apache.org/en/latest/admin-guide/files/parent.config.en.html
are ATS' mechanism for load balancing

**Comment by taojishou** [comment]
hosts:
  - &p1
    host: europe.123.com
    protocol:
      - scheme: http
        port: 80
        health_check_url: http://50.7.218.1:80:80
      - scheme: http
        port: 80
        health_check_url: http://50.7.218.2:80:80
strategies.yaml  configured like this？
parent.config No health check

**Comment by taojishou** [comment]
Can you give me a simple example with strategies.yaml?

**Comment by taojishou** [comment]
I don't understand   hosts match the domain name

**Comment by ywkaras** [comment]
There are examples for strategies.yaml in the ATS documentation:  https://docs.trafficserver.apache.org/admin-guide/files/strategies.yaml.en.html .

There are Au tests for strategies:  https://github.com/apache/trafficserver/tree/master/tests/gold_tests/next_hop

**Comment by taojishou** [comment]
Yes, the problem is still there, we haven't solved it yet

**Comment by ywkaras** [comment]
How far did you get looking at the documentation and the Au tests?

**Comment by ywkaras** [comment]
@taojishou can we close this, are you still having problems?

**Comment by ywkaras** [comment]
I'm going to close this, please reopen if you're still having the problem.
