### ISSUE TITLE
HTTP/2 specific error code=0x0b

### ISSUE THREAD

**Issue by cheluskin** [apache/trafficserver#9536]
ATS 10 diags log
```
[Mar 18 18:20:46.163] [ET_NET 6] ERROR: HTTP/2 connection error code=0x0b client_ip=x.x.x.x session_id=44554 stream_id=0 Erroneous client window update
```

from RFC "The endpoint detected that its peer is exhibiting a behavior that might be generating excessive load." 

Can this be fixed with the escalation plugin? If so, what is the error code that needs to be specified in order for it to work. Perhaps other settings that allow less load on origin?

**Comment by bneradt** [comment]
> Do you have details on how to reproduce this issue?

I second this: your reproduction steps would be helpful. I notice in the HTTP/2 to origin branch (#9366), the source code that would reply with this is commented out:

https://github.com/apache/trafficserver/pull/9366/files#diff-4229308c46f79900709a78c541d8de01a25fffe8073673ac798828517d879f30R2651

Are you perhaps running gRPC?

This issue may, therefore, go away for you once we merge in HTTP/2 to origin PR. That should land in 10.x

**Comment by cheluskin** [comment]
> > Do you have details on how to reproduce this issue?
> 
> I second this: your reproduction steps would be helpful. I notice in the HTTP/2 to origin branch (#9366), the source code that would reply with this is commented out:
> 
> https://github.com/apache/trafficserver/pull/9366/files#diff-4229308c46f79900709a78c541d8de01a25fffe8073673ac798828517d879f30R2651
> 
> Are you perhaps running gRPC?
> 
> This issue may, therefore, go away for you once we merge in HTTP/2 to origin PR. That should land in 10.x

not gRPC
Thank you, I will try this too.
Based on my observations, the average response time for HTTP/2 is 3-4 times better. However, while I used to be able to run the configuration on 8GB of memory, with HTTP/2 enabled, the memory runs out during periods of high loads.

**Comment by cheluskin** [comment]
The reduction of the default value by half for the option proxy.config.http2.min_avg_window_update did not change anything.

**Comment by maskit** [comment]
`min_avg_window_update` is to protect ATS from DoS attack, so you can change it to 1 with a risk if you need.

Appropriate value depends on your use case. For example, if data was going to be transferred intermittently like 100 bytes, pause, 100 bytes, pause ..., then you'd have to set `min_avg_window_update` to 100 or less.

**Comment by cheluskin** [comment]
> `min_avg_window_update` is to protect ATS from DoS attack, so you can change it to 1 with a risk if you need.
> 
> Appropriate value depends on your use case. For example, if data was going to be transferred intermittently like 100 bytes, pause, 100 bytes, pause ..., then you'd have to set `min_avg_window_update` to 100 or less.

If this works, then it means there's a problem with the default parameter. I have regular HLS traffic. The client requests a new file every 5-10 seconds. And there are massive triggers from thousands of different IPs in the log. Let's check. Thank you for your help.

**Comment by cheluskin** [comment]
CONFIG proxy.config.http2.min_avg_window_update FLOAT 1.0
This value solves my problem. The logs are clean. However, it's unclear why this is happening, considering there was no DDOS, only regular users and HLS traffic.
