### ISSUE TITLE
Trafficserver has double IO when slice plugin is enabled

### ISSUE THREAD

**Issue by frostnotfall** [apache/trafficserver#9553]
Here is the previous Remap configured(enable slice):
```
map http://127.0.0.1/ http://x.x.x.x/ \
    @plugin=slice.so  @pparam=--blockbytes=2m @pparam=--remap-host=loopback

map http://loopback/ http://x.x.x.x/ \
    @plugin=cachekey.so @pparam=--include-headers=Range @pparam=--remove-prefix=true @pparam=--remove-all-params=true \
    @plugin=cache_range_requests.so @pparam=--no-modify-cachekey @pparam=--consider-ims
```
Read Bytes:
![image](https://user-images.githubusercontent.com/38377709/227124960-2c9cdc27-248c-4a2d-aa9b-17a0295f9c30.png)

This is the current remap configuration(disable slice)：
```
map http://127.0.0.1/ http://x.x.x.x/ \
    @plugin=cachekey.so @pparam=--include-headers=Range @pparam=--remove-prefix=true @pparam=--remove-all-params=true \
    @plugin=cache_range_requests.so @pparam=--no-modify-cachekey @pparam=--consider-ims
```
Read Bytes:
![image](https://user-images.githubusercontent.com/38377709/228408877-bcbb87ce-08a5-4540-a6cb-bc41fd495db8.png)

**Comment by frostnotfall** [comment]
I have a guess, is it because the slice plugin sets two rules that cause the read byte count to double?

**Comment by traeak** [comment]
When using slice with loopback into the same remap rule we use a 'php != 0' filter on our logs to remove the loopback served bytes.  I hope this helps.

**Comment by frostnotfall** [comment]
> When using slice with loopback into the same remap rule we use a 'php != 0' filter on our logs to remove the loopback served bytes. I hope this helps. The loopback part might also qualify as an internal transaction as well for code purposes (needs verification).

Unfortunately, it doesn't help, the IO is actual disk IO.
