### ISSUE TITLE
10.0.x: debian master builds fail `make check` due to `undefined symbol: http_rsb`

### ISSUE THREAD

**Issue by bneradt** [apache/trafficserver#9601]
The CI branch builds are demonstrating an issue with `make check` runs on latest master. Running some of the tests fail with `undefined symbol: http_rsb`. Here's a recent log:

https://ci.trafficserver.apache.org/job/master/job/os_build/15948/console

```
FAIL: test_HttpTransact
=======================

/home/jenkins/workspace/master/os_build/src/proxy/http/.libs/test_HttpTransact: symbol lookup error: /home/jenkins/workspace/master/os_build/src/proxy/http/.libs/test_HttpTransact: undefined symbol: _Z31forceLinkRegressionHttpTransactv
FAIL test_HttpTransact (exit status: 127)
```

We need to figure out how to address this symbol issue.

**Comment by ywkaras** [comment]
```
wkaras ~/REPOS/TS
O$ c++filt
_Z31forceLinkRegressionHttpTransactv
forceLinkRegressionHttpTransact()
wkaras ~/REPOS/TS
O$
```
I do see this warning about `http_rsb`:
```
/usr/bin/ld: ../../proxy/http/HttpTransact.o: warning: relocation against `http_rsb' in read-only section `.text'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
```
Not clear how the two diagnostic messages are related.  But, I think that in the test_HttpTransact unit test executable, we would want to omit this code in HttpTransact.cc:
```
#if TS_HAS_TESTS
void forceLinkRegressionHttpTransact();
void
forceLinkRegressionHttpTransactCaller()
{
  forceLinkRegressionHttpTransact();
}
#endif
```
We can add `-DHTTP_TRANSACT_UNIT_TEST` to `test_HttpTransact_CPPFLAGS` in `proxy/http/Makefile.am` and change the first line of the above code to:
```
#if TS_HAS_TESTS && !defined(HTTP_TRANSACT_UNIT_TEST)
```
But I don' t understand why we'd only see this problem on the Debian check.  Do we run the unit tests on other checks?

**Comment by lzx404243** [comment]
@ywkaras  On the Debian branch build, an additional `--enable-hardening` flag is passed when configuring the build. The regular Debian check doesn't have this so that goes okay.  This seems to be related to the hardening flags.

**Comment by lzx404243** [comment]
The build last succeed on Mar 22, 2023. Looking into what changes may break this.
