### ISSUE TITLE
AuTest: Switch from curl for proxy_protocol.test.py

### ISSUE THREAD

**Issue by bneradt** [apache/trafficserver#9652]
The current proxy_protocol.test.py uses curl to verify Proxy Protocol usage. The gold file for the test expects curl to output the Proxy Protocol header it sends. Recent versions of curl do not output this string anymore. Maybe that's not a big deal - we can probably assume it does send the Proxy Protocol header. But it would probably be preferable to use Proxy Verifier for this test.

**Comment by ywkaras** [comment]
Is this related to https://github.com/apache/trafficserver/issues/9550 ?

**Comment by bneradt** [comment]
> Is this related to #9550 ?

Interesting. Thanks for providing the link. Switching to Proxy Verifier will address that. Or, at least, be a helpful part of the process of investigating that.
