### ISSUE TITLE
Remove deprecated debug output functions from all source files.

### ISSUE THREAD

**Issue by ywkaras** [apache/trafficserver#9717]

**Comment by ywkaras** [comment]
357 source files left to be updated as of May 17, 2023.

**Comment by jpeach** [comment]
> 



> 357 source files left to be updated as of May 17, 2023.

It could be a bit of a rabbit hole, but it might be possible to write a clang refactoring tool to update the code automatically. Here's something I put together for Envoy, which might help as an example https://github.com/jpeach/rewrite-fmt-format

**Comment by ywkaras** [comment]
Generally most of the changes I can largely automate with search and substitute.  The bottle neck is getting the changes reviewed.
