### ISSUE TITLE
docs.trafficserver.apache.org web server issue

### ISSUE THREAD

**Issue by randomizedcoder** [apache/trafficserver#9906]
G'day,

Sorry, not a bug with the code, but something seems to be wrong with the docs web severing, which I think is hosted by GoDaddy.  Wasn't sure the best way to let somebody know.

When browsing to the guide, some pages don't load, or they take a very long time.
https://docs.trafficserver.apache.org/en/latest/admin-guide/

Just now browsing to: https://docs.trafficserver.apache.org/en/latest/preface/index.en.html#other-resources
Request Timeout
Server timeout waiting for the HTTP request from the client.

`host docs.trafficserver.apache.org
docs.trafficserver.apache.org has address 72.167.42.180
`

Thanks,
Dave

**Comment by mhomaid1** [comment]
I'm facing the same issue, it happened to me a lot of times

**Comment by maskit** [comment]
Sorry for the inconvenience. We were testing the latest ATS with HTTP/3 and QUIC enabled, and I think that caused the issues. I just turned off a setting and I think it makes the server less unstable.

The test is to make sure next version of ATS is stable by the release, and the server is probably less stable until we make 10.0 release but it should not cause much trouble. If you are continuously having trouble with accessing the server, please reach out on our slack channel. Somebody should be able to check the server and take care of it.

**Comment by randomizedcoder** [comment]
Thanks so much!
