### ISSUE TITLE
[PLugin] OpenTelemetry Tracer Plugin make request processing time increase

### ISSUE THREAD

**Issue by HugManh** [apache/trafficserver#9961]
Hi everyone,
I using TrafficSrever branch: master - [#828b7d3](https://github.com/apache/trafficserver/commit/828b7d3e40655982f8abc88a5e634ed17ec39681). I trying OpenTelemetry Tracer Plugin to manage tracer for system. When i use the plugin, it make request processing time increase.

When use plugin:
![has_otel](https://github.com/apache/trafficserver/assets/43240025/0f16c616-0dae-49b0-a131-83a9d186b8ec)
![req_has_otel](https://github.com/apache/trafficserver/assets/43240025/79af44b5-568d-40fb-b392-8f2454d1d7cc)

Don't use plugin:
![no_otel](https://github.com/apache/trafficserver/assets/43240025/3e421b75-6b3b-46b4-8e4e-7aa4efd922ad)
![req_no_otel](https://github.com/apache/trafficserver/assets/43240025/9f2606d7-f50e-4bc7-9d13-63315ef391ad)

Has anyone used this plugin yet?

**Comment by shukitchan** [comment]
How does your observability stack look like? 

The plugin is sending a OTLP http request for sending the trace info to a backend. So if your backend is quite far away, it can take quite some time. 

One alternative is this - https://opentelemetry.io/docs/collector/deployment/agent/ 
You can have the deployment of an agent/collector on the same host of your ATS. And you configure the plugin to send OTLP request to the agent/collector instead. That should be much faster. And then you let the agent/collector do its work to send the info to a real backend.

**Comment by shukitchan** [comment]
300+ms is still a lot. 
I think we should try having the agent/collector in the local host. 

I have not got the time to try the latest opentelemetry-cpp release. So I can't say if there is anything changed in the sdk that will cause this much latency.

**Comment by HugManh** [comment]
@shukitchan Have you tried using opentelemetry without collector?

**Comment by HugManh** [comment]
I think i found problem in the plugin. I change span processor from SimpleSpanProcessor to BatchSpanProcessor. This solved my problem.
@shukitchan Thank you very much!
