### ISSUE TITLE
Require one SETTINGS frame on the control stream

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#9993]
> If the first frame of the control stream is any other frame
   type, this MUST be treated as a connection error of type
   H3_MISSING_SETTINGS.

https://datatracker.ietf.org/doc/html/rfc9114#section-6.2.1-2

**Comment by duke8253** [comment]
Pretty sure I already did this one with #9864

**Comment by maskit** [comment]
Yeah, you did. I've been mapping which paragraph/sentence was covered by which PR, but I missed the PR covered this part as well.
