### ISSUE TITLE
Don't send connection-specific headers

### ISSUE THREAD

**Issue by maskit** [apache/trafficserver#9995]
>    An intermediary transforming an HTTP/1.x message to HTTP/3 MUST
   remove connection-specific header fields as discussed in
   Section 7.6.1 of [HTTP], or their messages will be treated by other
   HTTP/3 endpoints as malformed.

https://datatracker.ietf.org/doc/html/rfc9114#section-4.2-5

**Comment by bneradt** [comment]
Here's the corresponding language for HTTP/2:

>   This means that an intermediary transforming an HTTP/1.x message to
   HTTP/2 will need to remove any header fields nominated by the
   Connection header field, along with the Connection header field
   itself.  Such intermediaries SHOULD also remove other connection-
   specific header fields, such as Keep-Alive, Proxy-Connection,
   Transfer-Encoding, and Upgrade, even if they are not nominated by the
   Connection header field.

https://www.rfc-editor.org/rfc/rfc7540.html#section-8.1.2.2

**Comment by duke8253** [comment]
This is already implemented  https://github.com/apache/trafficserver/blob/8dc2273bce276fa1a6ce5151b3a610ef3a55b009/proxy/hdrs/VersionConverter.cc#L308-L317
